### ISSUE TITLE
Wallet restore does not produce expected result

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#1012]
A bit of history:

I’ve been mining on testnet2 since April 5. As I have a fast cpu I mined a lot of blocks. At some point `wallet info` and `wallet outputs` started emitting a “WARNING: Failed to verify wallet contents with grin server”. The server was (and had been for quite some time) running normally. As there were many reports of this issue already (notably in Gitter/lobby), with suggestions that an upcoming commit would resolve the issue, I ignored it. The amounts reported in both `wallet info` and `wallet outputs` were consistent with the mining activities as observed in the log file.

When the re-factored grin server came along, with a separate grin-miner, I update grin and found that it had reduced my wallet.dat file to size 0. At least one other person reported that on Gitter/lobby if my memory doesn't fail me.

At that point I decided that this would be a good occasion to test a `wallet restore`. After some initial confusion because the (by default enabled) stratum server would panic without a wallet.dat file, but the `wallet restore` would not run with a wallet.dat file present, solved by disabling the stratum server in grin.toml, I got the wallet restore running. It took about 4 hours to complete.

This is what it found (grep’ed for brevity):
```
Apr 26 10:24:39.593 DEBG Found 0 wallet_outputs
Apr 26 10:24:53.105 DEBG Found 0 wallet_outputs
Apr 26 10:25:06.612 DEBG Found 0 wallet_outputs
Apr 26 10:25:20.091 DEBG Found 0 wallet_outputs
Apr 26 10:25:33.634 DEBG Found 0 wallet_outputs
Apr 26 10:25:47.142 DEBG Found 0 wallet_outputs
Apr 26 10:26:00.659 DEBG Found 0 wallet_outputs
Apr 26 10:26:14.183 DEBG Found 0 wallet_outputs
Apr 26 10:26:27.695 DEBG Found 0 wallet_outputs
Apr 26 10:26:41.195 DEBG Found 0 wallet_outputs
Apr 26 10:26:54.708 DEBG Found 0 wallet_outputs
Apr 26 10:27:08.185 DEBG Found 0 wallet_outputs
Apr 26 10:27:24.321 DEBG Found 89 wallet_outputs
Apr 26 10:27:44.524 DEBG Found 103 wallet_outputs
Apr 26 10:27:58.052 DEBG Found 0 wallet_outputs
Apr 26 10:28:12.350 DEBG Found 9 wallet_outputs
Apr 26 10:28:38.540 DEBG Found 119 wallet_outputs
Apr 26 10:29:34.102 DEBG Found 247 wallet_outputs
Apr 26 10:31:56.951 DEBG Found 450 wallet_outputs
Apr 26 10:38:12.968 DEBG Found 730 wallet_outputs
Apr 26 10:45:26.659 DEBG Found 576 wallet_outputs
Apr 26 10:54:34.322 DEBG Found 575 wallet_outputs
Apr 26 11:07:45.093 DEBG Found 679 wallet_outputs
Apr 26 11:12:45.815 DEBG Found 220 wallet_outputs
Apr 26 11:17:30.593 DEBG Found 197 wallet_outputs
Apr 26 11:28:36.448 DEBG Found 440 wallet_outputs
Apr 26 11:35:58.577 DEBG Found 267 wallet_outputs
Apr 26 11:36:54.238 DEBG Found 25 wallet_outputs
Apr 26 11:45:00.963 DEBG Found 277 wallet_outputs
Apr 26 11:59:20.232 DEBG Found 461 wallet_outputs
Apr 26 12:04:41.376 DEBG Found 158 wallet_outputs
Apr 26 12:21:32.548 DEBG Found 485 wallet_outputs
Apr 26 12:40:19.942 DEBG Found 504 wallet_outputs
Apr 26 13:00:47.699 DEBG Found 511 wallet_outputs
Apr 26 13:24:19.001 DEBG Found 548 wallet_outputs
Apr 26 13:52:54.301 DEBG Found 621 wallet_outputs
Apr 26 14:05:34.358 DEBG Found 259 wallet_outputs
Apr 26 14:10:04.085 DEBG Found 86 wallet_outputs
Apr 26 14:21:55.941 DEBG Found 227 wallet_outputs
Apr 26 14:22:11.289 DEBG Found 0 wallet_outputs
Apr 26 14:22:16.305 DEBG Found 0 wallet_outputs
```

The total grin_outputs amount to 8863. In this case we can safely assume that 1 output corresponds to 60 coinbase grin, resulting in a total of 531780 grin. That is consistent with what my `wallet info` used to indicate before the switch to grin-cum-stratum, give or take some transaction fee grins. The pattern of these grin_outputs lines in the log file is also consistent with my mining history. 

However, this is what `wallet info` shows me after the `wallet restore`:
```
Apr 26 14:39:06.008 INFO This is Grin version 0.2.0 (git testnet2-85-g2b2e13b), built for x86_64-unknown-linux-gnu by rustc 1.25.0 (84203cac6 2018-03-25).

____ Wallet Summary Info at 43835 (from server node) ____

 Total                            | 29483.999000000 
 Awaiting Confirmation            | 29483.999000000 
 Confirmed but Still Locked       | 0.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 


WARNING: Failed to verify wallet contents with grin server. Above info is maybe not fully updated or invalid! Check that your `grin server` is OK, or see `wallet help restore`
```
Not what I expected.

Keeping the seed from before the introduction of the stratum server safe, I ran several re-sync’s from scratch, both in fast sync and in archive mode, each time followed by a wallet restore, each time giving the same results. Following a suggestion on gitter/lobby I separated the wallet into it’s own directory, separate from the grin server, ran a full archive re-sync in one directory, followed by a `wallet restore` in the other directory, all with the same result. The last run was done with the latest git pull: mimblewimble/grin@5966418 

Before I switched over to the stratum version I checked with grinscan and I was fully sync’ed up with them. I mean I could see the blocks I mined showing up in their overview (at grinscan.net)
I also send some 600 grin from that wallet just before the switch (could be 2 or 3 days before), successfully.

As far as I can see there are 2 issues that might or might not have a common cause: 1) is the erroneous wallet restore and 2) is the failure of the wallet to connect with a grin server even though it’s there. All I can think of that makes this case unique is the amount of grin in the wallet (before the wallet.dat file was reduced to 0), but I might be wrong as I have no knowledge of the amount of grin in other people’s wallets.

At this point I’m ready to hand my wallet.seed file over to someone more competent for further analysis of the issue.

PS A full grin re-sync in archive mode takes about 2 hours on my machine and a wallet restore takes about 4 hours. I’m more than willing to repeat the exercise if someone can give me instructions that might lead to a solution or better insight into the issue. In the meantime I'm going to proceed in a different directory with the lastet git pull, a full archive re-sync and a virgin wallet.

After I wrote all that I realised how verbose it was  and maybe not useful at all. I'm going to leave it here for future reference, not expecting an immediate resolution. Please close or delete this issue as you see fit.

**Comment by yeastplume** [comment]
Could you PM me your seed in gitter, please? (Keep in mind testnet coins are worth exactly 0 anythings :D)

**Comment by yeastplume** [comment]
Okay, after some fixes (here: https://github.com/mimblewimble/grin/pull/1013) I'm able to restore and get a useful balance from that wallet seed:

```
____ Wallet Summary Info at 44669 (from server node) ____

 Total                            | 531625.634000000
 Awaiting Confirmation            | 0.000000000
 Confirmed but Still Locked       | 531625.634000000
 Currently Spendable              | 0.000000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000
```

Once I've commit the PR can you try grin wallet info again? It will take a while.

**Comment by photis** [comment]
Came back very late last night, tried first thing this morning. Success! 
Thanks.
