### ISSUE TITLE
validate blocks via output_sum and kernel_sum (store them in rocksdb)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1021]
We do not validate the overall input|output|kernel sums when we validate a single block (via block propagation say).
Block validation just checks that inputs|outputs|kernels are internally consistent within the block.
This does not prevent a "double spend" from occurring as each block where a spend occurs is itself internally consistent.

See #1019 for a contrived example (where we corrupt the rm_log to effect a "double spend").

The double spend is only identified and rejected if we validate the full txhashset.

Proposal: 
* for each block store `output_sum` and `kernel_sum` in rocksdb 
    * note: running totals of the chain so far, not sums for the individual block
* block validation -
    * `output_sum - total_supply == kernel_sum + kernel_offset`
* block validation (with prev block): 
    * `prev_output_sum + new outputs == output_sum`
    * `prev_kernel_sum + new kernels == kernel_sum`
    * `prev_output_sum + new outputs - new inputs == kernel_sum + kernel_offset`   

In this way we can validate "proof of unspentness" (i.e. prevent double spend attempts) at the block validation level, _before_ we start applying the block to our local txhashset MMRs.

Putting this here so I don't forget it - 
> The output_sum commits to an amount equal to the total supply.
But _in addition_ it actually represents _where_ this value comes from - the commitment includes information about all the private keys of all the unspent outputs that make up this aggregate amount.
Hence - a double spend will invalidate this.

Related - #1020. Storing the total kernel_offset as a commitment makes the code a lot cleaner and removes the need to store and pass around the offset as a blinding_factor.
This fits in well with the "everything is just a commitment" tenet of Grin.

  * output_sum (commitment)
  * kernel_sum (commitment)
  * kernel_offset (commitment)

We do need to store the `kernel_sum` and the `kernel_offset` separately as we need the `kernel_offset` when validating the txhashset (we get the `kernel_sum` by summing the MMR contents).

But when validating individual blocks (or block headers) we will use `kernel_sum + kernel_offset`.

~Needless to say - all this is `consensus breaking` and cannot be added (easily) to testnet2.~

-------------

TASKS -
 
- [x] store `kernel_offset` on block header as commitment (see #1020)
- [x] store `output_sum` and `kernel_sum` running totals, for each block, stored in rocksdb
- [x] modify block validation to check `output_sum` against `kernel_sum`
- [x] modify block validation to perform necessary checks against previous block

**Comment by ignopeverell** [comment]
I'm ok with the validation but I'm not sure why we'd need to store the sums on the block header. Both kernel excess and output commitments are committed to in the header already by way of the MMR roots and have to be computed to validate blocks in the first place. That feels like adding redundant data.

**Comment by antiochp** [comment]
Hmm ok.

Do these sums belong in the index then rather than on the block header?
It is expensive to sum them up from the MMR each time - so I think we need to store them somewhere.

I'd also argue it is not _completely_ redundant data as the root is of the full TXO set, whereas the sum is solely from the UTXO set

**Comment by antiochp** [comment]
Discussed on gitter.
Going to store these somewhere in rocksdb. They don't belong in the header itself.
Storing them in rocksdb as a local cache (purely to speed things up). We can always go back to the txhashset MMRs to reconstruct these sums (and if anything _was_ corrupted we'd know about it when validating the reconstructed sums).

**Comment by antiochp** [comment]
Resolved in #1043.
