### ISSUE TITLE
.unwrap() on Err value Io(Custom { kind: Other... failed to lookup address information...

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#1024]
@mably asked: What does this error mean? https://gist.github.com/mably/7b93d36ce5377d541e02fabb660c3260

I guess the first line suggests it's a DNS lookup issue.

````
Apr 29 17:44:21.813 ERRO Thread 'apis' panicked with message:
"called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: StringError("failed to lookup address information: Name or service not known") })"
See grin.log for further details.
````

The error value Io(...) is similar to https://www.reddit.com/r/rust/comments/5jgcow/reqwest_ipv6/
but without the outer http so our case is a similar error but without hyper.

**Comment by ignopeverell** [comment]
Right, either an issue with IPv6 or a misconfigured host name (like a hostname that wouldn't be in /etc/hosts).
