### ISSUE TITLE
official https support for grin-tech.org

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1029]
GitHub (finally) announced official support for HTTPS support on custom domains on GitHub pages.
So it should be fairly easy to enable https://grin-tech.org

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

I don't see "settings" on my view of the repo so I'm not able to do this. But can someone with admin rights @ignopeverell @yeastplume see if we can enable it?

**Comment by ignopeverell** [comment]
That required a DNS record update which I just did. It should propagate over the next few hours, then we can test whether it loads properly over https. Once that works, I can enable https redirection to always have ssl.

Thanks for spotting this!

**Comment by ignopeverell** [comment]
I'm guessing there are still some bumps for them to figure out. They're still using the guthub.io cert when going to https://grin-tech.org, which leads to a Scary Browser Message.

**Comment by antiochp** [comment]
Looks good from here, probably just took a while to propagate.

<img width="465" alt="screen shot 2018-05-02 at 3 23 48 pm" src="https://user-images.githubusercontent.com/30642645/39544708-e7560d56-4e1c-11e8-8d07-ca43a0a63042.png">

**Comment by kargakis** [comment]
Works perfect now, I guess you can close this issue.

**Comment by antiochp** [comment]
I do see a difference between -
* `https://grin-tech.org` (good)
* `https://www.grin-tech.org` (bad)

I'm not sure what GitHub says it attempts to do with the `www` subdomain?
