### ISSUE TITLE
Dandelion update from Bitcoin Core mailing list

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1059]
Looks like Dandelion have been "updated". We might have to implement the changes that they propose.
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-May/015956.html

**Comment by antiochp** [comment]
Interesting - putting this on my reading list.

**Comment by quentinlesceller** [comment]
Yeah I'm currently looking at the docs and test suite.
Looks like the "per-inbound-edge" requires having more than one Dandelion relay (which right now is not the case). I need to find where we discussed that. 
Other than that no big difference for us. Tests are mostly similar to what we already have.

**Comment by quentinlesceller** [comment]
Okay found it

> Giulia Fanti @gfanti févr. 22 10:44
@ignopeverell regarding the 2 stem peers--I was just about to mention this to you all. At the time we wrote the BIP, we thought that having 2 stem peers provided more robustness to attacks in which the adversary learns the graph. However, our understanding of the problem has developed since then, and we found that there's very little difference between having a stem peer set with 1 or 2 nodes--in fact, having only 1 stem peer may provide some extra protection against linking transactions (not sure how this would be affected by mimblewimble's tx aggregation). My collaborators and I discussed this, and we think for your purposes, it probably makes sense to just have 1 outbound stem peer at a time.

We might have to reconsider this.

**Comment by gfanti** [comment]
Per-incoming-edge routing is not necessary if you only use one Dandelion relay. We made the number of Dandelion relays a parameter in our reference implementation, so Core could easily switch from two Dandelion relays to one, and it would reduce to what you already have. The anonymity guarantees are similar, and there are minor tradeoffs associated with either choice. In short, we don't see any significant reason for you to change your initial plans.

**Comment by quentinlesceller** [comment]
Hey @gfanti, thank you for the clarification!
I'll leave this issue open for a few days in anyone wants to follow the status of Dandelion.

**Comment by sesam** [comment]
Adding this for reference https://gitter.im/grin_community/dev?at=5b06099160209a1187dbebf3 about not letting someone disable dandelion on a node simply by flooding it with (valid) transactions.
