### ISSUE TITLE
stuck at height 61454 until restart

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#1063]
I update my master branch today, rebuild, copied the new grin.toml and cleared .grin/ and then ran grin server.
After a long time staying at height 0, it moved up to height 6, stayed there for a long time and then jumped to height 61454 where it seemed to get stuck. See http://tromp.github.io/grin.log

I just quit and restarted the grin server, and it immediately got unstuck.
See http://tromp.github.io/grin.log.2
(or https://raw.githubusercontent.com/tromp/tromp.github.io/master/grin.log.2 since for some reason the above gives a 404 Not Found)
Any idea why a restart is required to make progress?

**Comment by chri2** [comment]
Had the same behaviour. Documented it in #1056 because in the end I couldn't get past a certain range and ended up with an error.

**Comment by ignopeverell** [comment]
I'll check your logs. I'm assuming that was a debug build?

**Comment by ignopeverell** [comment]
State download took about 4 min and then 16 min for validation on a debug build. After that it looks like body sync failed to kick in to finish up sync with the last 2000 blocks or so. Going to check what could have happened.

**Comment by ignopeverell** [comment]
Fixed by ce1dca1b
