### ISSUE TITLE
Stuck in tight loop processing orphan

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1065]
```
# git branch
* master
# cat .git/refs/heads/master
4121ea124092081148273ec5846397cc001d7fa2
```

```
May 13 17:38:37.892 DEBG handle_payload: CompactBlock: c9776b51
May 13 17:38:37.892 DEBG Received compact_block c9776b51 at 65607 from 10.32.0.1:13414, going to process.
May 13 17:38:37.892 DEBG pipe: process_block c9776b51 at 65607 with 0 inputs, 1 outputs, 1 kernels
May 13 17:38:37.893 DEBG process_block: orphan: c9776b51, # orphans 1
...
...
May 13 17:47:57.228 DEBG process_block: orphan: c9776b51, # orphans 2
```
Here is a link to more log:  https://ipfs.io/ipfs/Qmeiz8D1Mq5kZEA4v6oweNGEquKRb3RdDLFg1cuM78BrLh

Warning, its very large - 209M.  I dont see any new info at the bottom so downloading the first part is probably enough.

**Comment by ignopeverell** [comment]
Any scenario to help reproducing this would be helpful.

**Comment by bladedoyle** [comment]
It may be worth mentioning that this was running inside a docker container inside Kubernetes.  The network overlay uses NAT and seems to have the unfortunate side effect of making it appear as though every inbound connection is from the gateway address.  10.32.0.1 in this case.

This is an archive node that accepts p2p connections.  It had been up about 4 days.  I was not interacting with it at the time.  Seems like it had a healthy number of peers:

`May 13 17:41:56.041 DEBG monitor_peers: 9 connected (7 most_work). all 230 = 15 healthy + 0 banned + 215 defunct`

**Comment by garyyu** [comment]
@bladedoyle  Could you please tell me how to produce [this table](https://ipfs.io/ipfs/QmTBMKAg89iidRD2RVQyukS2Ntkgf3BBpns33C4NApzM5x)  which you mentioned in Gitter?  Thanks.

**Comment by garyyu** [comment]
@bladedoyle  thanks for the info. Before looking what's wrong, I'm trying to reproduce the problem.

**Comment by bladedoyle** [comment]
@garyyu   Ugh, I confused two different issues.  My comments above about a node lagging behind the head block does not apply here, that is a separate problem.  This issue is about a grin node getting stuck in a tight loop while trying to process an orphan.

**Comment by alice-bob-dlfs** [comment]
I'm probably seeing the same issue.

The text UI shows

```
Current Status: Syncing - Latest header: 125238
Connected Peers: 17
Chain Height: 0
Total Difficulty: 1000
```

I've checked the `125238` number with grinscan.net and confirmed that it's up-to-date.  But the zero chain height looks suspicious.

And from the `grin.log`
```
...
Jun 28 18:12:23.970 DEBG process_block: orphan: 88d2e078, # orphans 55
Jun 28 18:12:23.975 DEBG process_block: orphan: 64ecbec3, # orphans 55
Jun 28 18:12:24.189 DEBG process_block: orphan: 64ecbec3, # orphans 55
Jun 28 18:12:24.385 DEBG process_block: orphan: 64ecbec3, # orphans 55
Jun 28 18:12:41.685 DEBG process_block: orphan: f50e6c63, # orphans 56
Jun 28 18:12:42.621 DEBG process_block: orphan: f50e6c63, # orphans 56
Jun 28 18:13:04.329 DEBG process_block: orphan: 0ba1f5de, # orphans 57
Jun 28 18:13:04.359 DEBG process_block: orphan: 0ba1f5de, # orphans 57
Jun 28 18:13:04.739 DEBG process_block: orphan: 0ba1f5de, # orphans 57
Jun 28 18:13:04.744 DEBG process_block: orphan: 0ba1f5de, # orphans 57
Jun 28 18:13:04.881 DEBG process_block: orphan: f50e6c63, # orphans 57
Jun 28 18:13:04.917 DEBG process_block: orphan: 0ba1f5de, # orphans 57
Jun 28 18:13:05.148 DEBG process_block: orphan: 0ba1f5de, # orphans 57
```

**Comment by bladedoyle** [comment]
I have not seen this issue recently.  Its possible that the commits around July 20 for block sync issues fixed this.

**Comment by hashmap** [comment]
Closing, feel free to reopen
