### ISSUE TITLE
redundant blake2b hashing on pre-pow header

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#1066]
header pow validates as Cuckoo::new(&bh.pre_pow_hash()[..], cuckoo_sz).verify(bh.pow.clone(), consensus::EASINESS as u64),

passing the blake2b hash of the pre-pow header as first argument, but Cuckoo::new considers its first argument a header rather than the siphash keys, and hashes it (again!) with blake2b.

**Comment by ignopeverell** [comment]
Good catch, slipped through one of the many changes to that interface. Going to have to fix this in `consensus_breaking`.

**Comment by tromp** [comment]
This is consensus breaking if you change block header validation.

**Comment by yeastplume** [comment]
Just had to trace through this myself again to remind me, just saving my work below. As @ignopeverell says it looks like it just got missed with all of the changes.

The verification function is stored as a function pointer within the chain... looking at in chain/src/pipe.rs (219)
```
!·if !ctx.opts.contains(Options::SKIP_POW) {
!·!·let n = global::sizeshift();
!·!·**if !(ctx.pow_verifier)(header, n)** {
!·!·!·error!(
```
At this point the header is just a block header ref, not a hash.

The function is instantiated at server startup, as follows (servers/src/grin/server.rs) 135 or so:

```
!·!·let shared_chain = Arc::new(chain::Chain::init(
!·!·!·config.db_root.clone(),  
!·!·!·chain_adapter.clone(),
!·!·!·genesis.clone(),         
!·!·!·pow::verify_size,        
!·!·)?);
```

Verify size is defined as: 

```
/// Validates the proof of work of a given header, and that the proof of work
/// satisfies the requirements of the header.
pub fn verify_size(bh: &BlockHeader, cuckoo_sz: u8) -> bool {
!·Cuckoo::new(&bh.pre_pow_hash()[..], cuckoo_sz)
!·!·.verify(bh.pow.clone(), consensus::EASINESS as u64)
} 
```
Which hashes, and then Cuckoo::new hashes again:
```
!·pub fn new(header: &[u8], sizeshift: u8) -> Cuckoo {
!·!·let size = 1 << sizeshift; 
!·!·let hashed = blake2::blake2b::blake2b(32, &[], header);
!·!·let hashed = hashed.as_bytes();
```

Just as a reminder, in cuckoo miner the hash passed to the solvers is:
```
blake2(pre_nonce|nonce)
```

So the hash being passed to the solver is correct... so now I'm having a 'how the hell is this working at all?' moment.

**Comment by phooton** [comment]
The current C++ miner plugins think they are getting block header and hash the hash again. So miner and verifier both double hash. External mozkomor miner now also has to double hash pre_pow to get correct solutions for the node.

**Comment by yeastplume** [comment]
Okay, digging a bit further into the miners now, in @tromp's cuckoo.h:
```
// convenience function for extracting siphash keys from header
void setheader(const char *header, const u32 headerlen, siphash_keys *keys) {
  char hdrkey[32];
  // SHA256((unsigned char *)header, headerlen, (unsigned char *)hdrkey);
  blake2b((void *)hdrkey, sizeof(hdrkey), (const void *)header, headerlen, 0, 0);
#ifdef SIPHASH_COMPAT
  u64 *k = (u64 *)hdrkey;
  u64 k0 = k[0];
```
(blake2b is):
```
  int blake2b( void *out, size_t outlen, const void *in, size_t inlen, const void *key, size_t keylen );
```

@phooton correct, just came to the same conclusion :D... so the optimisation appears to be to send just the block header from cuckoo miner and not the hash alongside updating the Cuckoo::new function. Thanks!

**Comment by ignopeverell** [comment]
Ah. The code highlighted by @tromp was the test miner, I thought the real miner was doing the right thing given that the header is always what's provided. Thanks for double-checking behind me.

**Comment by ignopeverell** [comment]
Okay, I think I'm closer this time. #1071 takes care of the changes in Grin, cleaning a few things up. Separately there's https://github.com/mimblewimble/cuckoo-miner/commit/6fcecf516a111424d8bd5542fe20250e4f02cd8f also in a `consensus-breaking` branch to remove hashing before sending the header data to the Cuckoo plugin.

@phooton you might want to keep an eye on when all of this get merged (most likely testnet3)

**Comment by ignopeverell** [comment]
Fixed in `consensus_breaking`.
