### ISSUE TITLE
How to best manage consensus_breaking branch 

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1077]
Opening this issue now for discussion later today (team sync up).

The current long-lived `consensus_breaking` branch has some of the changes from master on it, plus some actual consensus_breaking changes, plus some changes that ended up getting reverted.
It has had both merge commits and "rebase from master" commits merged onto it (my fault).
I'm sure it is also missing some smaller changes that went into master.
The result is the commit history on this branch is not particularly clean right now and it is becoming difficult to reconcile it against master.

At a rough estimate we have the following high level breaking changes on there - 
* new style Merkle proofs (serialization change)
* latest version of libsecp (incompatible bulletproof impl)
* pow header hashing changes

Q) Is there anything else on that branch?

I am wondering if this single long-lived branch is actually the right approach.
It is difficult to keep it up to date with master while also keeping it in a clean state.

Possible proposal - What would it look like if we kept these 3 or 4 "features" as long-lived PRs against master. Each one could be more easily rebased against master as necessary.

At some yet to be determined future point in time (i.e. when testnet3 is imminent) we merge these consensus_breaking PRs and build the new branch (or master?) at that time.
If we have a situation where we need to test multiple PRs together earlier than this we can do this locally on a throwaway branch as necessary.

Summary: maybe instead of having a single long-lived `consensus_breaking` branch that is difficult to maintain, we have multiple (more focused) long-lived `consensus_breaking` PRs.
There will be more easily maintained, and can be integrated locally for any necessary testing.

**Comment by sesam** [comment]
Nice. IMHO it seems pragmatic to build each consensus breaking change in its own branch, and rebase it only when / if it becomes necessary. Branches don't hurt (much) if they aren't rebased for a while.

Each not-yet-integrated feature has some nonzero chance of
1) becoming obsolete before we integrate it,
and makes it easier for bystanders to grasp, one of whom might see it as a nice learning challenge to
2a) rebase such branches (at least I tried that with one of Igno's branches once)
2b) or integrate non-breaking parts of the change into master

**Comment by ignopeverell** [comment]
During the dev meeting we agreed to:

1. Keep individual PRs (and re-create the ones that were merged in `consensus_breaking`)
2. Tag them as `consensus_breaking` pick the next milestone they apply to (`beta / testnet3`)
3. When we're getting close to realse, rebase and merge into master.

**Comment by yeastplume** [comment]
Think we're good here now.
