### ISSUE TITLE
Three change outputs generated instead of one

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#1078]
### Info
- sender & recipient both on MacBook Pros (2016) 
- running release build from commit id: 7281dc947374c31b4518208eb1a08d99b6ec95f8

### Steps to reproduce
1. Sender has 1 grin in their wallet received from a previous transaction.
1. Sender sends 0.000001 grin successfully.
1. Sender runs `grin wallet info`

### Current outcome
See terminal state: https://pastebin.com/UD261e2H
1. Sender successfully sent 0.000001 grin to Recipient who received it in order.
1. Meanwhile on the Sender wallet side a balance of 2.9759970 is awaiting confirmation, consisting of 3 change outputs of 0.991999 each.
    

### Expected outcome
1. Sender successfully sent 0.000001 grin to Recipient who received it in order.
1. Sender should have received just one change output.

**Comment by ignopeverell** [comment]
Grin uses an output-based model so it's normal the whole grin was locked to spend a microgrin out of it. With fees the change is likely correct as well. So the issue seems to be you got 3 change outputs generated instead of one...

**Comment by lehnberg** [comment]
Ah I see, okay. I've updated title and description to reflect this.
