### ISSUE TITLE
Slow wallet performance for large wallets

### ISSUE THREAD

**Issue by urza** [mimblewimble/grin#1082]
When wallet.dat contains lot of outputs, some operations take very long.
From testing our mozkomor miner we have wallet.dat that is about 10 MB in size (cca 500 000 testnet grins)

For example 
`grin wallet info`
takes cca 1 minute to output results on my 6 core machine.
(Running on release, latest master)

With new/empty wallet, the response is near instantaneous.

Another place where you can observe this effect is in stratum server. When miner finds valid block and submits it to stratum server, there is cca 30 seconds delay before stratum server sends new job. Again with new/empty wallet, this is near instantaneous. My guess is that grin node is synchronously saving the newly mined block coinbase before assembling new candidate block for mining...

Let me know if we can provide anything additional to help pin this down.

**Comment by yeastplume** [comment]
Unfortunately, this is unlikely to be a particular issue with a single fix. Each `wallet info` command checks each and every output in the wallet against the server, and the server retrieves outputs one-by-one from the UTXO set, which involves several locks, a database lookup and a file seek and read. The process is very un-optimised, and speeding it up will need some profiling and tuning. Also, there's no good way to 'batch' retrievals from the underlying storage, each UTXO needs to be looked up and accessed individually.

**Comment by ignopeverell** [comment]
We could prolly easily solve that for the stratum implementation at least, I don't think it needs to do a full wallet refresh.

**Comment by yeastplume** [comment]
Yes, agreed. A round of performance enhancements on UTXO retrieval will be good for the overall wallet experience, though wouldn't expect we'll get a wallet with 8000 outputs to completely refresh itself in sub-second time. We may want some feature to get UTXO deltas from block to block to allow for partial wallet refreshes instead of having to refresh every output every time

**Comment by ignopeverell** [comment]
I'll take a look, I'm around that code anyway (to do the cleanup of old unconfirmed).

**Comment by hashmap** [comment]
Wallet performance has been sufficiently improved (or it just got hard to get a large wallet)
