### ISSUE TITLE
latest master currently experiencing banning by older nodes

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1099]
We have the following - 
https://github.com/mimblewimble/grin/blob/ec3c2e89a4509eaa1900e9206534eeca71781592/p2p/src/msg.rs#L76-L96

And we index into the `MAX_MSG_SIZES` array like this - 
https://github.com/mimblewimble/grin/blob/ec3c2e89a4509eaa1900e9206534eeca71781592/p2p/src/msg.rs#L193

i.e. we use an enum and treat it as a `usize`...
😲 

1. I'm actually surprised you can do this in Rust.
2. This is _very_ brittle because this enum can and should be expected to change as we add new msg types. Any ordering/renumbering changes here will break the p2p layer while we have old and new nodes on the network.

**Comment by hashmap** [comment]
Stable Rust allows to convert c-style enum variants to number, but not vice versa. However we use an external crate to support this behaviour too (the macros add `num::FromPrimitive` implementation)

https://github.com/mimblewimble/grin/blob/ec3c2e89a4509eaa1900e9206534eeca71781592/p2p/src/msg.rs#L51

**Comment by quentinlesceller** [comment]
I actually did something similar in https://github.com/mimblewimble/grin/pull/1085.

**Comment by antiochp** [comment]
@quentinlesceller yeah - I merged master in post #1085 and saw this happen locally.

**Comment by hashmap** [comment]
I agree with @antiochp  it looks a bit hacky. I'm not sure if additional data would work, I suspect this enum was designed to be c-style. I'm also not sure about hashmap (not me, a real one), I'd suggest to have a function with `match` inside to make sure that all variants are covered.

**Comment by antiochp** [comment]
:+1: on the `match` (so we cover all the variants).
PR up here - https://github.com/mimblewimble/grin/pull/1101
