### ISSUE TITLE
consider removing enum_from_primitive! and ser/deser enums explicitly

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1102]
The `enum_from_primitive!` macro makes it convenient to convert to/from a primitive integer.
But it is brittle and susceptible to accidental renumbering of the enums themselves - where it is not obvious the ordering of the enum definition matters.

Related - #1099 & #1101.

**Comment by quentinlesceller** [comment]
Commenting here what I said on Gitter. It seems like the only way we can do that now would be to do:
```
/// Types of connection
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Direction {
    Inbound,
    Outbound,
}

impl Direction {
    pub fn from_u8(n: u8) -> Option<Direction> {
        match n {
            0 => Some(Direction::Inbound),
            1 => Some(Direction::Outbound),
            _ => None,
        }
    }
}
```
But in that case we need to maintain two indexes. Or we can use match guards:
```
impl Direction {
    pub fn from_u8(n: u8) -> Option<Direction> {
        match n {
            n if n == Direction::Inbound as u8 => Some(Direction::Inbound),
            n if n == Direction::Outbound as u8 => Some(Direction::Outbound),
            _ => None,
        }
    }
}
```
Which make the code less readable.

**Comment by antiochp** [comment]
Yeah - lets leave it as we have it for now.
We just need to remember to use explicit values if we ever add a new enum like this.
