### ISSUE TITLE
Check difficulty adjustment before T3 Launch

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1109]
The difficulty adjustment at T2 launch didn't work as expected, and there have since been changes by @tromp (I need to dig up that PR) as well as fixes to the difficulty 'simulator' which has real values from the T2 launch. Before we launch a T3 chain, we need to ensure that the difficulty calc behaves as expected (if set far too high, it should halve consistently until it comes into range.)

**Comment by tromp** [comment]
For testnet 3 we'll need to make the one line change already mentioned in lines 242-245 of consensus.rs :

	// AVOID BREAKING CONSENSUS FOR NOW WITH OLD DOUBLE TRUNCATION CALC
	let difficulty = (diff_sum / DIFFICULTY_ADJUST_WINDOW) * BLOCK_TIME_WINDOW / adj_ts;
	// EVENTUALLY BREAK CONSENSUS WITH THIS IMPROVED SINGLE TRUNCATION DIFF CALC
	// let difficulty = diff_sum * BLOCK_TIME_SEC / adj_ts;

**Comment by ignopeverell** [comment]
Right. I applied that on the `consensus_breaking` branch a few weeks back and was planning in redoing that PR today.

**Comment by yeastplume** [comment]
happy enough with this now via #1212
