### ISSUE TITLE
compactor error and consecutive erros in peer and stratum_server

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#1127]
Logfile can be found [here](http://z9.de/log-2018-06-02.bz2).

@jaspervdm wrote on gitter that he'd created a block containing >2000 inputs just before this happened. Could be coincidence, but the first error (compactor) occured just one block before receiving block 94001 with >2000 inputs.

Afterwards peer threw errors each time block 94001 has been received.

After stop and restart of grin server the server synced up to the top of the chain without further problems.

Grin version 0.2.0 (git testnet2-135-gb6c31eb), built for x86_64-unknown-linux-gnu by rustc 1.26.0 (a77568041 2018-05-07). Built with profile "release", features "" on Wed, 30 May 2018 20:09:48 GMT.

**Comment by ignopeverell** [comment]
Can you see if the following reproduces the issue?

```
curl -X POST 127.0.0.1:13413/v1/chain/compact
```

If so, it'd be great to have a stacktrace on a debug build.

**Comment by chri2** [comment]
Didn't reproduce. But also: There is no logging on level trace about anything related to that http-post.

**Comment by chri2** [comment]
Happend again at block height 98000. Log is [here](http://z9.de/log-2018-06-05.bz2).

**Comment by antiochp** [comment]
I reproduced this locally a couple of times - investigating here as well.
It looks to be related to the data file during compaction the 2nd time, the hash file appears to behave correctly.
