### ISSUE TITLE
error: paths in `use` groups are experimental (see issue #44494)

### ISSUE THREAD

**Issue by waaslandwolf** [mimblewimble/grin#1145]
Hi all,

Noob dev here so be patient :-)

I'm looking to install grin but get the following error:
error: paths in `use` groups are experimental (see issue #44494)
  --> wallet/src/libwallet/internal/selection.rs:18:28

Build output and system info below. Rust installed through rustup. I would appreciate any pointers. 

john@server-nas:~/grin$ cargo build --release --verbose
       Fresh gcc v0.3.54
       Fresh maplit v1.0.1
       Fresh safemem v0.2.0
       Fresh serde v0.8.23
       Fresh lazy_static v0.2.11
       Fresh memoffset v0.2.1
       Fresh build_const v0.2.0
       Fresh quote v0.3.15
       Fresh matches v0.1.6
       Fresh term v0.4.6
       Fresh strsim v0.7.0
       Fresh scoped-tls v0.1.1
       Fresh typeable v0.1.2
       Fresh version_check v0.1.3
       Fresh winapi v0.2.8
       Fresh stable_deref_trait v1.0.0
       Fresh utf8-ranges v1.0.0
       Fresh take v0.1.0
       Fresh ansi_term v0.11.0
       Fresh byteorder v1.2.1
       Fresh bitflags v0.8.2
       Fresh route-recognizer v0.1.12
       Fresh enumset v0.3.3
       Fresh slab v0.4.0
       Fresh unicode-normalization v0.1.5
       Fresh vec_map v0.8.0
       Fresh regex-syntax v0.3.9
       Fresh xi-unicode v0.1.0
       Fresh lazycell v0.6.0
       Fresh peeking_take_while v0.1.2
       Fresh percent-encoding v1.0.1
       Fresh bitflags v1.0.1
       Fresh take_mut v0.2.2
       Fresh smallvec v0.2.1
       Fresh void v1.0.2
       Fresh constant_time_eq v0.1.3
       Fresh unicode-width v0.1.4
       Fresh semver-parser v0.7.0
       Fresh scopeguard v0.3.3
       Fresh futures v0.1.21
       Fresh cfg-if v0.1.2
       Fresh language-tags v0.2.2
       Fresh libc v0.2.40
       Fresh lazy_static v1.0.0
       Fresh rustc-serialize v0.3.24
       Fresh ucd-util v0.1.1
       Fresh utf8-ranges v0.1.3
       Fresh sequence_trie v0.2.1
       Fresh adler32 v1.0.2
       Fresh bufstream v0.1.3
       Fresh nodrop v0.1.12
       Fresh httparse v1.2.4
       Fresh siphasher v0.2.2
       Fresh dtoa v0.4.2
       Fresh modifier v0.1.0
       Fresh slab v0.3.0
       Fresh unicode-xid v0.1.0
       Fresh rustc-demangle v0.1.7
       Fresh unicode-xid v0.0.4
       Fresh make-cmd v0.1.0
       Fresh same-file v1.0.2
       Fresh slog v2.2.3
       Fresh array-macro v1.0.0
       Fresh pkg-config v0.3.9
       Fresh itoa v0.1.1
       Fresh winapi-build v0.1.1
       Fresh itoa v0.4.1
       Fresh podio v0.1.6
       Fresh unicode-segmentation v1.2.0
       Fresh odds v0.2.26
       Fresh glob v0.2.11
       Fresh either v1.5.0
       Fresh traitobject v0.1.0
       Fresh linked-hash-map v0.4.2
       Fresh dtoa v0.2.2
       Fresh encode_unicode v0.3.1
       Fresh unicode-bidi v0.3.4
       Fresh owning_ref v0.3.3
       Fresh base64 v0.6.0
       Fresh base64 v0.9.0
       Fresh term v0.5.1
       Fresh unreachable v1.0.0
       Fresh textwrap v0.9.0
       Fresh semver v0.9.0
       Fresh tokio-executor v0.1.1
       Fresh tokio-service v0.1.0
       Fresh relay v0.1.1
       Fresh crossbeam-utils v0.3.2
       Fresh crossbeam-utils v0.2.2
       Fresh log v0.4.1
       Fresh num_cpus v1.8.0
       Fresh iovec v0.1.2
       Fresh memmap v0.6.2 (https://github.com/danburkert/memmap-rs?tag=0.6.2#b8b5411f)
       Fresh daemonize v0.3.0
       Fresh memchr v2.0.1
       Fresh memchr v1.0.2
       Fresh memchr v0.1.11
       Fresh rand v0.4.2
       Fresh isatty v0.1.6
       Fresh time v0.1.39
       Fresh net2 v0.2.32
       Fresh atty v0.2.8
       Fresh syntex_pos v0.58.1
       Fresh conduit-mime-types v0.7.3
       Fresh regex-syntax v0.6.0
       Fresh regex-syntax v0.5.3
       Fresh miniz_oxide v0.1.2
       Fresh arrayvec v0.4.7
       Fresh proc-macro2 v0.2.3
       Fresh synom v0.11.3
       Fresh walkdir v2.1.4
       Fresh arrayvec v0.3.25
       Fresh itertools v0.7.8
       Fresh unsafe-any v0.4.2
       Fresh error v0.1.9
       Fresh lru-cache v0.1.1
       Fresh idna v0.1.4
       Fresh num-traits v0.2.4
       Fresh serde v1.0.66
       Fresh thread_local v0.3.5
       Fresh log v0.3.9
       Fresh futures-cpupool v0.1.8
       Fresh bytes v0.4.6
       Fresh aho-corasick v0.6.4
       Fresh csv v0.15.0
       Fresh nom v3.2.1
       Fresh aho-corasick v0.5.3
       Fresh rand v0.3.22
       Fresh msdos_time v0.1.5
       Fresh mio v0.6.14
       Fresh clap v2.31.2
       Fresh syntex_errors v0.58.1
       Fresh crossbeam-epoch v0.4.1
       Fresh blake2-rfc v0.2.18
       Fresh crossbeam-epoch v0.3.1
       Fresh quote v0.4.2
       Fresh syn v0.11.11
       Fresh libloading v0.4.3
       Fresh typemap v0.3.3
       Fresh crc v1.7.0
       Fresh url v1.7.0
       Fresh num-traits v0.1.43
       Fresh num-integer v0.1.38
       Fresh num-complex v0.1.43
       Fresh uuid v0.6.5
       Fresh toml v0.4.5
       Fresh serde_json v1.0.13
       Fresh unicase v1.4.2
       Fresh unicase v2.1.0
       Fresh slog-async v2.3.0
       Fresh mime v0.2.6
       Fresh tokio-io v0.1.6
       Fresh regex v0.2.10
       Fresh regex v1.0.0
       Fresh prettytable-rs v0.7.0
       Fresh cexpr v0.2.3
       Fresh syntex_syntax v0.58.1
       Fresh crossbeam-deque v0.3.0
       Fresh crossbeam-deque v0.2.0
       Fresh syn v0.12.14
       Fresh synstructure v0.6.1
       Fresh enum-map-derive v0.2.4
       Fresh ncurses v5.91.0
       Fresh kernel32-sys v0.2.2
       Fresh clang-sys v0.21.2
       Fresh plugin v0.2.6
       Fresh enum_primitive v0.1.1
       Fresh serde_json v0.8.6
       Fresh num-iter v0.1.35
       Fresh num-bigint v0.2.0
       Fresh num-bigint v0.1.43
       Fresh secp256k1zkp v0.7.1 (https://github.com/mimblewimble/rust-secp256k1-zkp?tag=grin_integration_19#800e9b3e)
       Fresh phf_shared v0.7.22
       Fresh mime v0.3.5
       Fresh hyper v0.10.13
       Fresh tokio-reactor v0.1.1
       Fresh env_logger v0.4.3
       Fresh quasi v0.32.0
       Fresh aster v0.41.0
       Fresh syntex v0.58.1
       Fresh tokio-threadpool v0.1.1
       Fresh rayon-core v1.4.0
       Fresh serde_derive_internals v0.22.1
       Fresh failure_derive v0.1.1
       Fresh enum-map v0.2.24
       Fresh thread-id v2.0.0
       Fresh num-rational v0.1.42
       Fresh phf v0.7.22
       Fresh phf_generator v0.7.22
       Fresh iron v0.5.1
       Fresh tokio-udp v0.1.0
       Fresh tokio-tcp v0.1.0
       Fresh quasi_codegen v0.32.0
       Fresh rayon v1.0.1
       Fresh serde_derive v1.0.35
       Fresh thread_local v0.2.7
       Fresh num v0.1.42
       Fresh phf_codegen v0.7.22
       Fresh persistent v0.3.0
       Fresh mount v0.3.0
       Fresh router v0.5.1
       Fresh tokio v0.1.4
       Fresh cc v1.0.9
       Fresh jsonrpc-core v8.0.1
       Fresh regex v0.1.80
       Fresh cursive v0.8.2-alpha.0 (https://github.com/yeastplume/Cursive?tag=grin_integration_1#e23a5cd3)
       Fresh chrono v0.4.0
       Fresh bodyparser v0.5.0
       Fresh bodyparser v0.7.0
       Fresh tokio-core v0.1.16
       Fresh cmake v0.1.29
       Fresh env_logger v0.3.5
       Fresh slog-term v2.4.0
       Fresh urlencoded v0.5.0
       Fresh tokio-retry v0.1.1
       Fresh tokio-proto v0.1.1
       Fresh bindgen v0.29.1
       Fresh mime_guess v1.8.4
       Fresh hyper v0.11.24
       Fresh libz-sys v1.0.18
       Fresh miniz_oxide_c_api v0.1.2
       Fresh backtrace-sys v0.1.16
       Fresh bzip2-sys v0.1.6
       Fresh iron v0.6.0
       Fresh flate2 v1.0.1
       Fresh backtrace v0.3.5
       Fresh libgit2-sys v0.7.3
       Fresh bzip2 v0.3.2
       Fresh router v0.6.0
       Fresh librocksdb-sys v5.11.3
       Fresh failure v0.1.1
       Fresh git2 v0.7.1
       Fresh zip v0.4.0
       Fresh rocksdb v0.10.0
       Fresh built v0.3.0
       Fresh grin_util v0.2.0 (file:///home/john/grin/util)
       Fresh grin_keychain v0.2.0 (file:///home/john/grin/keychain)
       Fresh grin_core v0.2.0 (file:///home/john/grin/core)
       Fresh grin_store v0.2.0 (file:///home/john/grin/store)
       Fresh grin_pool v0.2.0 (file:///home/john/grin/pool)
       Fresh grin_p2p v0.2.0 (file:///home/john/grin/p2p)
       Fresh grin_chain v0.2.0 (file:///home/john/grin/chain)
       Fresh grin_api v0.2.0 (file:///home/john/grin/api)
   Compiling grin_wallet v0.2.0 (file:///home/john/grin/wallet)
     Running `rustc --crate-name grin_wallet wallet/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=b28ff9c0d430c5c2 -C extra-filename=-b28ff9c0d430c5c2 --out-dir /home/john/grin/target/release/deps -L dependency=/home/john/grin/target/release/deps --extern prettytable=/home/john/grin/target/release/deps/libprettytable-6b6f5ec661597ba9.rlib --extern grin_util=/home/john/grin/target/release/deps/libgrin_util-e7585fd1d9a795d4.rlib --extern urlencoded=/home/john/grin/target/release/deps/liburlencoded-e87f75ece18bed28.rlib --extern slog=/home/john/grin/target/release/deps/libslog-c099bef5ebcb4279.rlib --extern tokio_retry=/home/john/grin/target/release/deps/libtokio_retry-85764138040d2653.rlib --extern serde_json=/home/john/grin/target/release/deps/libserde_json-29384a9670998270.rlib --extern uuid=/home/john/grin/target/release/deps/libuuid-d63d9c864874a397.rlib --extern grin_keychain=/home/john/grin/target/release/deps/libgrin_keychain-bcac9163074958d7.rlib --extern term=/home/john/grin/target/release/deps/libterm-2b6f4e6451dcd73d.rlib --extern byteorder=/home/john/grin/target/release/deps/libbyteorder-ecc1add84d07e5c8.rlib --extern serde=/home/john/grin/target/release/deps/libserde-e14e8f430ba5c236.rlib --extern blake2_rfc=/home/john/grin/target/release/deps/libblake2_rfc-bc1c9bf716d00215.rlib --extern failure_derive=/home/john/grin/target/release/deps/libfailure_derive-199ff39e5454f6a2.so --extern grin_api=/home/john/grin/target/release/deps/libgrin_api-45fe1d25584a1f2b.rlib --extern grin_core=/home/john/grin/target/release/deps/libgrin_core-77a78989ed560dc8.rlib --extern hyper=/home/john/grin/target/release/deps/libhyper-23250fb55692e557.rlib --extern failure=/home/john/grin/target/release/deps/libfailure-7a720f6a1cbe0489.rlib --extern tokio_core=/home/john/grin/target/release/deps/libtokio_core-a84a525dd44526ec.rlib --extern futures=/home/john/grin/target/release/deps/libfutures-9a22f1e83b2fbc20.rlib --extern iron=/home/john/grin/target/release/deps/libiron-4e531c7a3a853925.rlib --extern bodyparser=/home/john/grin/target/release/deps/libbodyparser-9a9ee180f6407df1.rlib --extern serde_derive=/home/john/grin/target/release/deps/libserde_derive-642655a0640144ef.so --extern router=/home/john/grin/target/release/deps/librouter-bd65bf548fd242c7.rlib --extern rand=/home/john/grin/target/release/deps/librand-293516021ccedf09.rlib -L native=/home/john/grin/target/release/build/backtrace-sys-5d00e9b7787c02b5/out/.libs -L native=/home/john/grin/target/release/build/secp256k1zkp-f7395e958f186c53/out -L native=/home/john/grin/target/release/build/bzip2-sys-aacde9590fd8985f/out -L native=/home/john/grin/target/release/build/librocksdb-sys-1dc6d851fab45da2/out -L native=/home/john/grin/target/release/build/librocksdb-sys-1dc6d851fab45da2/out`
error: paths in `use` groups are experimental (see issue #44494)
  --> wallet/src/libwallet/internal/selection.rs:18:28
   |
18 | use libtx::{build, tx_fee, slate::Slate};
   |                            ^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `grin_wallet`.

Caused by:
  process didn't exit successfully: `rustc --crate-name grin_wallet wallet/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=b28ff9c0d430c5c2 -C extra-filename=-b28ff9c0d430c5c2 --out-dir /home/john/grin/target/release/deps -L dependency=/home/john/grin/target/release/deps --extern prettytable=/home/john/grin/target/release/deps/libprettytable-6b6f5ec661597ba9.rlib --extern grin_util=/home/john/grin/target/release/deps/libgrin_util-e7585fd1d9a795d4.rlib --extern urlencoded=/home/john/grin/target/release/deps/liburlencoded-e87f75ece18bed28.rlib --extern slog=/home/john/grin/target/release/deps/libslog-c099bef5ebcb4279.rlib --extern tokio_retry=/home/john/grin/target/release/deps/libtokio_retry-85764138040d2653.rlib --extern serde_json=/home/john/grin/target/release/deps/libserde_json-29384a9670998270.rlib --extern uuid=/home/john/grin/target/release/deps/libuuid-d63d9c864874a397.rlib --extern grin_keychain=/home/john/grin/target/release/deps/libgrin_keychain-bcac9163074958d7.rlib --extern term=/home/john/grin/target/release/deps/libterm-2b6f4e6451dcd73d.rlib --extern byteorder=/home/john/grin/target/release/deps/libbyteorder-ecc1add84d07e5c8.rlib --extern serde=/home/john/grin/target/release/deps/libserde-e14e8f430ba5c236.rlib --extern blake2_rfc=/home/john/grin/target/release/deps/libblake2_rfc-bc1c9bf716d00215.rlib --extern failure_derive=/home/john/grin/target/release/deps/libfailure_derive-199ff39e5454f6a2.so --extern grin_api=/home/john/grin/target/release/deps/libgrin_api-45fe1d25584a1f2b.rlib --extern grin_core=/home/john/grin/target/release/deps/libgrin_core-77a78989ed560dc8.rlib --extern hyper=/home/john/grin/target/release/deps/libhyper-23250fb55692e557.rlib --extern failure=/home/john/grin/target/release/deps/libfailure-7a720f6a1cbe0489.rlib --extern tokio_core=/home/john/grin/target/release/deps/libtokio_core-a84a525dd44526ec.rlib --extern futures=/home/john/grin/target/release/deps/libfutures-9a22f1e83b2fbc20.rlib --extern iron=/home/john/grin/target/release/deps/libiron-4e531c7a3a853925.rlib --extern bodyparser=/home/john/grin/target/release/deps/libbodyparser-9a9ee180f6407df1.rlib --extern serde_derive=/home/john/grin/target/release/deps/libserde_derive-642655a0640144ef.so --extern router=/home/john/grin/target/release/deps/librouter-bd65bf548fd242c7.rlib --extern rand=/home/john/grin/target/release/deps/librand-293516021ccedf09.rlib -L native=/home/john/grin/target/release/build/backtrace-sys-5d00e9b7787c02b5/out/.libs -L native=/home/john/grin/target/release/build/secp256k1zkp-f7395e958f186c53/out -L native=/home/john/grin/target/release/build/bzip2-sys-aacde9590fd8985f/out -L native=/home/john/grin/target/release/build/librocksdb-sys-1dc6d851fab45da2/out -L native=/home/john/grin/target/release/build/librocksdb-sys-1dc6d851fab45da2/out` (exit code: 101)

System info:

john@server-nas:~/grin$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
john@server-nas:~/grin$ rustc --version
rustc 1.24.1
john@server-nas:~/grin$ cargo --version
cargo 0.25.0
john@server-nas:~/grin$ cmake --version
cmake version 3.5.1

**Comment by waaslandwolf** [comment]
Rust was installed through rustup.rs (as mentioned). Rust version was:
$ rustc --version
rustc 1.24.1

Updated Rust through the following command:
`curl https://sh.rustup.rs -sSf | sh -s -- -y
`
Rust 1.26.2 was installed. Still the same error.

**Comment by ignopeverell** [comment]
Did you try a `rustup update`?

**Comment by waaslandwolf** [comment]
Yes. Says it is already the latest version. I rebooted and it is building again now so we'll see how that goes. 

Thanks for the comments so far, I appreciate the help!
