### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by Remi-Tuy** [mimblewimble/grin#1149]
I have been trying to build the latest version but during the compilation I keep getting an error when the scripts try to compile: secp256k1zkp v0.7.1 

Here is the error I get: 

> error: failed to run custom build command for `secp256k1zkp v0.7.1 (https://github.com/mimblewimble/rust-secp256k1-zkp?tag=grin_integration_19#800e9b3e)`
> process didn't exit successfully: `/home/ubuntu/grinNode/target/release/build/secp256k1zkp-3ca4f7ac93abebd1/build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("3")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("false")
> running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "depend/secp256k1-zkp/" "-I" "depend/secp256k1-zkp/include" "-I" "depend/secp256k1-zkp/src" "-g" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-DUSE_ENDOMORPHISM=1" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_GENERATOR=1" "-DENABLE_MODULE_RECOVERY=1" "-DENABLE_MODULE_RANGEPROOF=1" "-DENABLE_MODULE_BULLETPROOF=1" "-DENABLE_MODULE_AGGSIG=1" "-Wall" "-Wextra" "-o" "/home/ubuntu/grinNode/target/release/build/secp256k1zkp-5c16d5fd5c533823/out/depend/secp256k1-zkp/contrib/lax_der_parsing.o" "-c" "depend/secp256k1-zkp/contrib/lax_der_parsing.c"
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("3")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("false")
> running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "depend/secp256k1-zkp/" "-I" "depend/secp256k1-zkp/include" "-I" "depend/secp256k1-zkp/src" "-g" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-DUSE_ENDOMORPHISM=1" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_GENERATOR=1" "-DENABLE_MODULE_RECOVERY=1" "-DENABLE_MODULE_RANGEPROOF=1" "-DENABLE_MODULE_BULLETPROOF=1" "-DENABLE_MODULE_AGGSIG=1" "-Wall" "-Wextra" "-o" "/home/ubuntu/grinNode/target/release/build/secp256k1zkp-5c16d5fd5c533823/out/depend/secp256k1-zkp/src/secp256k1.o" "-c" "depend/secp256k1-zkp/src/secp256k1.c"
> cargo:warning=virtual memory exhausted: Cannot allocate memory
> exit code: 1
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "depend/secp256k1-zkp/" "-I" "depend/secp256k1-zkp/include" "-I" "depend/secp256k1-zkp/src" "-g" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-DUSE_ENDOMORPHISM=1" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_GENERATOR=1" "-DENABLE_MODULE_RECOVERY=1" "-DENABLE_MODULE_RANGEPROOF=1" "-DENABLE_MODULE_BULLETPROOF=1" "-DENABLE_MODULE_AGGSIG=1" "-Wall" "-Wextra" "-o" "/home/ubuntu/grinNode/target/release/build/secp256k1zkp-5c16d5fd5c533823/out/depend/secp256k1-zkp/src/secp256k1.o" "-c" "depend/secp256k1-zkp/src/secp256k1.c" with args "cc" did not execute successfully (status code exit code: 1).
> 
> ', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

`

Looking at the logs I though it could have been a memory error but after restarting the machine, I have plenty of RAM to compile but no success. Here is the result of df -h:
`Filesystem      Size  Used Avail Use% Mounted on
udev            488M     0  488M   0% /dev
tmpfs           100M  3.0M   97M   3% /run
/dev/xvda1      7.7G  2.7G  5.0G  36% /
tmpfs           496M     0  496M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           496M     0  496M   0% /sys/fs/cgroup
tmpfs           100M     0  100M   0% /run/user/1000`

**Comment by quentinlesceller** [comment]
Maybe try to add swap space. Also ```df -h```does not display available memory but available disk space?

**Comment by yeastplume** [comment]
local environment issue, closing. If you still need help with this, feel free to get in touch on the gitter channel
