### ISSUE TITLE
txhashset.zip can contain arbitrary files

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1171]
Currently we just zip the local `.grin/txhashset` dir up and send it across (and implicitly trust we have no local files in there that should not be exposed to other nodes).
And on the receiving side we just unzip it (and implicitly trust there is nothing unwanted or malicious in there).

We should probably explicitly list the contents of the zip file on both ends and filter everything else out.

Related - #1147 (proposing to generate snapshot utxo files and send those over to support rewind).

**Comment by sesam** [comment]
In Steve Gibsons latest, "Security Now 667 Zippity Do... or Don't" has related infotainment.
This is probably a very prioritised issue.
If you worry about security, wipe your boxen - or learn to love living with (intentionally or not permanently root-infested hardware.

**Comment by quentinlesceller** [comment]
I got this.
