### ISSUE TITLE
Document the StratumServer RPC 

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1176]
Documenting RPC for the StratumServer will make it easier for miners and pools to integrate.  

At least the following should be captured:
* Each Request / Response in JSON
* Each possible error code/message and meaning
* miners SHOULD randomize the job nonce before starting (not the way it is now, the way it should be)
* miners MUST continue mining the same job until the server sends a new one, though a miner MAY request a new job at any time
* miners MUST NOT send an rpc response to a job request from the server 
* miners MAY set the RPC "id" and expect responses to have that same id
* miners MAY send a keepalive message
* miners MAY send a login request (to identify which miner finds shares / solutions in the logs), the login request MUST have all 3 params.
* miners MUST return the supplied job_id with submit messages.
* Link to the "grin-miner" client.rs file as a reference implementation

**Comment by quentinlesceller** [comment]
### Error codes:
```
* -32701: Node is syncing - please wait
* -32600: Invalid Request
* -32601: Method not found
* -32500: Login first
* -32501: Share rejected due to low difficulty
* -32502: Failed to validate solution
* -32503: Solution Submitted too late
```

JSON RPC 2.0 Specification: https://www.jsonrpc.org/specification

**Comment by ignopeverell** [comment]
Should a doc under grin/docs be started? Or a wiki page?

**Comment by quentinlesceller** [comment]
Mmm, I might actually start a doc under grin/docs this week.
