### ISSUE TITLE
Investigate Confidential Assets in MW

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#119]
From @apoelstra on the the mailing list - 
https://lists.launchpad.net/mimblewimble/msg00103.html

Paper - 
https://blockstream.com/bitcoin17-final41.pdf

Potential impact to "Wallet Import/Export Format " - #28 (can a wallet identify UTXOs that belong to the wallet)?

(starting an issue here to track relevant reading material etc.)
@ignopeverell please feel free to close this out if not immediately relevant given where Grin is today.

**Comment by ignopeverell** [comment]
Definitely relevant, thank you for creating an issue.

**Comment by antiochp** [comment]
Opened related issue mimblewimble/rust-secp256k1-zkp#6 to expose the surjection module from secp256k1-zkp lib (which I believe we need for CA).

**Comment by antiochp** [comment]
I'm closing this as I don't think the issue adds any value itself.
We know that Confidential Assets is something that we will explore further at some future date.
