### ISSUE TITLE
timelocked coinbase outputs (relative timelock against coinbase kernel)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1191]
If/when we implement #1190 I suspect we can rework our "coinbase maturity" handling follow the same approach.

Currently we "lock" coinbase outputs for 1,000 blocks by requiring a Merkle proof to prove the age of the output being spent.
I _think_ we can rework this to take advantage of the fact we know which _kernel_ is involved in the original coinbase output being created, and require a kernel Merkle proof (rather than an output Merkle proof) on the tx kernel spending it (and not the input spending the output as we have today).

This would also give us the following advantages - 
* if we have a tx spending many coinbase outputs we would only need a single kernel Merkle proof (against the most recent coinbase kernel) to prove they have all matured sufficiently.
Right now we require an output Merkle proof on each one individually (on the individual inputs).
* We sign tx kernels and kernels are not pruned, so this would be potentially be verifiable, even for historical validators.

The coinbase reward (output) for mining a block is associated with a corresponding coinbase kernel.
We can prove maturity against this kernel (and not the output as we do currently).

Related - #1190 and #1187.

**Comment by ignopeverell** [comment]
> The coinbase reward (output) for mining a block is associated with a corresponding coinbase kernel.

How do we know which coinbase output is related to which kernel?

**Comment by antiochp** [comment]
I was going to spend some time seeing if we could use the relationship between a coinbase output and the corresponding coinbase kernel but I don't think we need to.

I think we can actually separate a couple of different but related concepts here to do what we need -
1) a relative timelock proving the tx (spending the coinbase) is at least 1,000 blocks after the referenced tx 
    1) the kernel Merkle proof provides us with a referenced block header
    1) from this block header we know the output_mmr_size
1) all coinbase outputs being spent must be earlier than this (pos <= output_mmr_size) 
    1) spending coinbase outputs _requires_ a kernel Merkle proof to facilitate this

The kernel Merkle proof from (1) does not have to refer to the original coinbase output. It would probably be convenient and simplest if it did, but these two concepts are now distinct.
We need a (any) Merkle proof to define the timelock.
And we need a (any) timelock that meets the maturity rules (at least 1,000 blocks) to spend coinbase outputs.

This is just thinking out loud but it decouples the Merkle proofs from coinbase spending and allows them to be more generic (compared to the coinbase specific inputs we have now).

**Comment by antiochp** [comment]
Alternatively (or maybe in addition to) - if we know the coinbase tx kernel and we know the block reward from the header then we can identify the coinbase output commitment.
`kernel = output - reward`

This wouldn't work if the miner built a "non-standard" block reward with either multiple outputs or multiple kernels. But if they are 1-1 then this would work and we could identify the output.

**Comment by antiochp** [comment]
Actually now that we commit to `output_mmr_size` and in the block header we don't even need the Merkle proof (or a kernel derived "relative" locktime) for this.

* We know current block height.
* We can identify the block 1,000 previous.
* From this we know the `output_mmr_size`.
* We just need to check that _any_ coinbase outputs being spent have pos less than or equal to this `last_pos`.

So it might have been nice to exercise the "relative locktime" stuff for coinbase maturity - but we can do this in a simpler (and faster) way.

**Comment by ignopeverell** [comment]
All good points, those additional header fields are coming quite handy...

**Comment by antiochp** [comment]
Yeah in this case they basically give us (relative) timestamps due to the append-only MMR.

**Comment by antiochp** [comment]
Resolved in #1203.
