### ISSUE TITLE
Investigate reason for high number of **rejected** mined shares

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1215]
A fast miner (1080 ti GPU) sees a high number of both rejected and stale shares.  ex:
 "974 accepted, 44 rejected and 25 stales"

A slow miner (1-core on an i7 cpu) sees far fewer stale shares but still sees many shares rejected due to invalid POW.  ex:
"109 accepted, 16 rejected, 0 stale"

We need to understand why the shares are **rejected**:
* does the miner return invalid pow?
* does the data get corrupted in transit?
* is there some issue with the validation code?
* something else?

---
The grin.log messages associated with rejected shares:
```
Jun 30 00:25:29.786 DEBG pipe: process_block b67f0bcb at 126038 with 0 inputs, 1 outputs, 1 kernels
Jun 30 00:25:29.787 ERRO pipe: validate_header failed for cuckoo shift size 30
Jun 30 00:25:29.787 INFO Rejected block b67f0bcb at 126038: InvalidPow
Jun 30 00:25:29.789 ERRO (Server ID: StratumServer) Failed to validate solution at height 126038: InvalidPow
```

**Comment by yeastplume** [comment]
This appears to be happening just after the `attempt_time_per_block` timeout expires and the server builds a new block with a new timestamp and nonce. If grin-miner returns a solution for the previous block, it's rejected as invalid (presumably because the nonce it returns doesn't match the new block).

**Comment by yeastplume** [comment]
No, scratch that.. it seems to be happening every time a solution is returned very quickly after the job is sent out, which is very odd (why should that pow not verify in that case?)

**Comment by yeastplume** [comment]
This (and potentially some cases of #1216) appear to have been caused by reading the wrong solution from an underlying solution output queue.. so if two solutions are found in rapid succession and one meets difficulty, the next job would read an old solution from the queue. Fixed this within cuckoo-miner and the latest version of grin-miner, so will monitor for a while now to see if this occurs again.

**Comment by ignopeverell** [comment]
Nice! Thanks for looking.

**Comment by bladedoyle** [comment]
I think (at least part of) the problem is in the Stratum Server.

The stratum server just uses whatever header a miner submits and attaches that to the "current block". If the stratum server just built a new block, and the miner sends a solution for the previous one, the block wont validate (even if none of the transactions changed the timestamp will).

1) The stratum server will need to version the templates it sends - probably by adding an "id" field to the job template struct.
AND
2) the stratum server needs to keep a history of the blocks it built in the past for the current chain height so it can accept shares for previous versions of the same block.

**Comment by bladedoyle** [comment]
I believe this is fully resolved, please re-open if necessary.

**Comment by HT-Moh** [comment]
Hi 
I am having same issue with a version 4.0.0 alpha.1 

![Screenshot from 2020-05-01 15-00-41](https://user-images.githubusercontent.com/34759569/80807148-ad8c7f80-8bbc-11ea-809d-d166ee8aa2b6.png)

**Comment by quentinlesceller** [comment]
You certainly using the wrong mining plugin @HT-Moh

**Comment by HT-Moh** [comment]
@quentinlesceller  Thanks for your response can you please tell how to identify which plugin to use ?

**Comment by quentinlesceller** [comment]
You have to use Cuckaroom.

**Comment by HT-Moh** [comment]
Thanks @quentinlesceller 
Ok I compiles from source and installed the plugin wasn't straightforward but yes it seems to work but not everything, I am having this error on the logs I am not sure if my configurations are correct can you please check  

![save](https://user-images.githubusercontent.com/34759569/80822850-d8d29700-8bdb-11ea-8602-14b38ac802af.png)
![save_2](https://user-images.githubusercontent.com/34759569/80822861-dc661e00-8bdb-11ea-9b18-aae611038fe8.png)

**Comment by quentinlesceller** [comment]
Is it with the latest master?

**Comment by HT-Moh** [comment]
Yes its master 
I got this error as well 

![Screenshot from 2020-05-01 20-56-34](https://user-images.githubusercontent.com/34759569/80833364-b007cd00-8bee-11ea-95f6-0c38aa2dafb0.png)

**Comment by quentinlesceller** [comment]
Okay the ban is unrelated. I'm fixing the error in the log above. But other than that everything is fine and the error in grin-miner logs are okay (not going to cause any problems).

**Comment by HT-Moh** [comment]
I can ignore as well the ban, right? one more question the size column in the mining device is always 0 and the graph time column as well is that normal ?

**Comment by HT-Moh** [comment]
I am getting often Error parsing message, so I tried to debug this and saw that I am getting often a message with value a 10 which cause Error parsing message. can you please check screenshot attached.
![debug](https://user-images.githubusercontent.com/34759569/80867763-214e8b00-8c96-11ea-97c3-9800639053e7.png)

**Comment by quentinlesceller** [comment]
@HT-Moh I believe it’s because of this https://github.com/mimblewimble/grin/pull/3315. The stratum sends an empty message.
