### ISSUE TITLE
Investigate reason for high number of **stale** mined shares

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1216]
A fast miner (1080 ti GPU) sees a high number of stale shares. ex:
"974 accepted, 44 rejected and 25 stales"

In this example, 2.6% of submitted shares were too late
* Is that ratio high?  

If its too high, we need to understand why the shares are submitted late:
* is the grin node slow to build a new block template?
* is the stratum server slow to send it?
* is the miner slow to start on new jobs?
* something else?

---
A few examples from my grin.log.
```
Jul 01 11:07:47.514 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 168872
Jul 01 11:07:47.528 DEBG (Server ID: StratumServer) sending block 127062 to stratum clients
Jul 01 11:07:48.934 ERRO (Server ID: StratumServer) Share at height 127061 submitted too late

Jul 01 22:50:18.235 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 169194
Jul 01 22:50:18.246 DEBG (Server ID: StratumServer) sending block 127384 to stratum clients
Jul 01 22:50:18.247 ERRO (Server ID: StratumServer) Share at height 127383 submitted too late

Jul 02 19:50:37.892 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 169811
Jul 02 19:53:48.081 DEBG (Server ID: StratumServer) sending block 128001 to stratum clients
Jul 02 19:53:48.081 ERRO (Server ID: StratumServer) Share at height 128000 submitted too late

Jul 02 21:05:56.238 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 169841
Jul 02 21:05:56.249 DEBG (Server ID: StratumServer) sending block 128031 to stratum clients
Jul 02 21:05:56.901 ERRO (Server ID: StratumServer) Share at height 128030 submitted too late

Jul 03 01:45:27.234 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 169984
Jul 03 01:45:27.241 DEBG (Server ID: StratumServer) sending block 128174 to stratum clients
Jul 03 01:45:27.242 ERRO (Server ID: StratumServer) Share at height 128173 submitted too late

Jul 03 06:03:13.005 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 170168
Jul 03 06:03:13.023 DEBG (Server ID: StratumServer) sending block 128358 to stratum clients
Jul 03 06:03:13.981 ERRO (Server ID: StratumServer) Share at height 128357 submitted too late
```

**Comment by yeastplume** [comment]
This seems to happen when a miner finds many valid solutions in rapid succession (satisfying difficulty 1, at least), and sends them all to the server in rapid succession. If one meets the target difficulty and moves on to the next block, the others are rejected as stale before the server sends out the next job message.

I might suggest that once a block meeting target difficulty is found, keep it around and accept shares for the previous block for a brief interval. Only report something as 'stale' or 'submitted too late' if it's an actual target-meeting solution for a block that's already been found.

**Comment by bladedoyle** [comment]
I worry some that could mask a future problem, should one occur.  I prefer to leave the late share reporting as-is if they are legitimately late.

Testing with a fast miner this morning I get:
Jul 14 08:51:02.045 INFO Status for worker 46 - Height: 8112, Difficulty: 1, (197/0/2)

so 1% late shares does not feel too high to me.

**Comment by bladedoyle** [comment]
From the sample of logs above, this one seems to be the "worst":

```
Jul 03 06:03:13.005 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 1, cumulative difficulty 170168
Jul 03 06:03:13.023 DEBG (Server ID: StratumServer) sending block 128358 to stratum clients
Jul 03 06:03:13.981 ERRO (Server ID: StratumServer) Share at height 128357 submitted too late
```
There is almost 1 second between when the stratum server sends a new job and when the late share is processed.  For a 60 second block interval, is that too long?

**Comment by ignopeverell** [comment]
It depends. There's no reason for it to take 1 sec if the delay is happening at the block building or stratum communication level. if it's systemic, that's a lot. On the other hand, it may just be that you're CPU-mining and a Cuckoo Cycle search ccan't be interrupted after it already started, which should be expected (and less of an issue ultimately).
