### ISSUE TITLE
grin wallet info - incorrect block heights

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1239]
I think `grin wallet info` is showing the wrong block heights.
Not sure if this is a new issue or if we just haven't ever noticed this before...

```
Wallet Outputs - Block Height: 1262
-----------------------------------------------------------------------------------------------------------------------------------
 Key Id                Child Key Index  Block Height  Locked Until  Status       Is Coinbase?  Num. of Confirmations  Value 
===================================================================================================================================
 695bce7618475f1b0243  299              1263          2263          Unconfirmed  true          0                      60.000000000 
-----------------------------------------------------------------------------------------------------------------------------------
 d3a367aadc253684c585  320              1260          0             Unspent      false         3                      16.156000000 
-----------------------------------------------------------------------------------------------------------------------------------
 2dfb9a218e44534d7ada  321              1260          0             Unspent      false         3                      1.000000000 
-----------------------------------------------------------------------------------------------------------------------------------
```

Compare the above - 2 unspent outputs with block height `1260`, to the info about block 1262 (which appears to be the block this tx was actually included in) - 

https://grinscan.net/block/1262

We can see the `lock_height` of the tx kernel is 1260, but the block height is actually 1262.

I suspect we are incorrectly displaying the `lock_height` via `grin wallet info` (and incorrectly calculating the # confirmations from this).

**Comment by yeastplume** [comment]
It's entirely likely it wasn't noticed before... will have a look as part of ongoing wallet work.

**Comment by yuntai** [comment]
It seems related to I am wanting to tackle next - 'wallet restore' which currently doesn't resolve block height for each output. thinking since node does not necessarily have all the blocks scanning pmmr combined with cumulative pmmr size in the block header can be used to restore the correct block for the output. currently, wallet doesn't seem to monitor blockchain so no way to know the correct block height to which a tx is included.

**Comment by yeastplume** [comment]
@yuntai absolutely correct, just haven't got to it yet, please feel free

**Comment by antiochp** [comment]
I think we are/were setting the "next block height" making ther assumption that this is the correct block height for the new txs.
This was _roughly_ correct when txs were likely to be included in the next block.
But Dandelion adds a few mins of delay - which means we're always off by a few blocks now.

@yuntai the wallet does a refresh/update to get block heights here - 
https://github.com/mimblewimble/grin/blob/42bc03f5f32bff88c41353ea1bdbcb242023f06d/wallet/src/libwallet/internal/updater.rs#L134-L136

**Comment by yuntai** [comment]
not so sure. ‘height’ here is the current height. and only spent and unsoent state seems being updated here. as my unerstanding (keyid -> commit-> pmmr index -> exists?unspent:spent).

**Comment by antiochp** [comment]
Closing as pretty sure this has been resolved.
