### ISSUE TITLE
mining and forked blocks

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1243]
This block has 3 "child" blocks (thanks @jaspervdm for finding this!) - 
https://grinscan.net/block/1623

One becomes the "main" chain and the other two are short lived forks.

`0dd016` becomes the main chain - https://grinscan.net/block/1624
mined: 2018-07-10 03:18:56 UTC
diff: 537 

`0a078b` is treated as a losing fork
mined: 2018-07-10 03:18:59 UTC
diff: 740

`0bfb84` is also treated as a losing fork
mined: 2018-07-10 03:18:59 UTC
diff: 619

`00bc70` is the next block on the main chain https://grinscan.net/block/1625
mined: 2018-07-10 03:22:08 UTC
diff: 10,085

Is it strange that both `0a078b` and `0bfb84` have greater diff than the winning `0dd016` at height 1624?

I'm not that familiar with what happens on a mining node when it sees forked blocks like this.
It looks like the "first one seen" won.
But it also seems like the one with greatest total difficulty _should_ have been the winning block?
There were a few minutes, ignoring clock differences between nodes, before the next block at height 1625 was mined.

**Comment by antiochp** [comment]
Oh hang on - total diff is based on sum of target diff, not the actual diff.
(that's what I was missing)

So this is working as designed - "first one seen wins" unless the total diff (sum of target diffs) is greater for a given height.

So we need a fork where the target diff actually increases for a reorg to occur between forks.
Is this a min of 2 blocks on a fork or is this even larger in practice?

**Comment by yeastplume** [comment]
This looks fine to me.. all 3 blocks meet the same network difficulty check (the actual difficulty isn't relevant in this case), so the first one to be seen should win.

**Comment by antiochp** [comment]
:+1:

**Comment by antiochp** [comment]
Closing.
