### ISSUE TITLE
grin api returns 505 when a block is not found in fast_sync node

### ISSUE THREAD

**Issue by yuntai** [mimblewimble/grin#1247]
`wget -O- http://127.0.0.1:13413/v1/blocks/5
--2018-07-12 01:55:14--  http://127.0.0.1:13413/v1/blocks/5
Connecting to 127.0.0.1:13413... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2018-07-12 01:55:14 ERROR 500: Internal Server Error.`

which is not very informative

**Comment by ignopeverell** [comment]
We should return a `404` with a more explanatory message, especially if the node is in fast sync mode. Generally, if a node admin wants to be able to retrieve any block locally, she should run it in archival mode.
