### ISSUE TITLE
Block is Unfit: Already Known

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1254]
Currently experiencing an issue where Grin received an already known block and crash. Node is currently mining.
Logs : https://pastebin.com/40hJfq79

**Comment by yuntai** [comment]
Not necessarily when receiving an already known block. 
`thread 'unnamed' panicked at 'called ''Result::unwrap()`` on an ``Err`` value: "PoisonError { inner: .. }"`
`8:     0x564d4c950d58 - grin_servers::mining::stratumserver::accept_workers::h897336354e9c94cd`
To me these two lines suggest another worker thread panicked and Mutex is poisoned before this error happened. Perhaps it'd be helpful to find the very first backtrace in the log.

**Comment by ignopeverell** [comment]
Correct, the `PoisonError` is usually the result of a previous thread crash.

**Comment by hashmap** [comment]
Agree, some previous panic is a real cause, `accept_workers` is running in a separate thread, some panic happened in this tread before while holding the mutex. I checked my logs, don't have such error. Perhaps it is specific to your system, potentially it may happen here https://github.com/mimblewimble/grin/blob/master/servers/src/mining/stratumserver.rs#L123 which is easy to check by greping "set_nonblocking call failed""

**Comment by quentinlesceller** [comment]
Another log without any mining: https://pastebin.com/FkY8kAwp

**Comment by quentinlesceller** [comment]
Maybe this is just normal behavior here ? Node already has the block hence do not process it.

**Comment by hashmap** [comment]
Right, `Block is Unfit: Already Known` is normal behavior and it's not a panic. However `PoisonError` is not normal and result of a panic, perhaps described in https://github.com/mimblewimble/grin/issues/1255

**Comment by quentinlesceller** [comment]
Okay closing this issue.
