### ISSUE TITLE
Make grin.toml config optional

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1256]
Config should default to all current values without needing the toml file. If options need to be overwritten, we should be able to accept a file with only those few options.

**Comment by i1skn** [comment]
I would like to whelp with one.

**Comment by i1skn** [comment]
I did some expirement with removing `grin.toml` and making possible to run `grin` without it.
It ends up, that default values set in the `grin.toml` sometimes are different from ones in the code.

I did collect ones are different below (this was done by dumping `println!("{:?}",global_config);` with and without config) :
```
// Each field has a format of <value_in_the_code> | <value_in_grin.toml>

GlobalConfig {
    members: Some(ConfigMembers {
        server: ServerConfig {
            chain_type: UserTesting | Testnet3,
            p2p_config: P2PConfig {
                ban_window: Some(10800) | None,
                peer_max_count: Some(25) | None,
                peer_min_preferred_count: Some(8) | None,
            }
            stratum_mining_config: Some(StratumServerConfig {
                enable_stratum_server: None | Some(true),
                stratum_server_addr:  None | Some("127.0.0.1:13416"),
                attempt_time_per_block: 4294967295 | 15,
            })
            skip_sync_wait: None |  Some(false),
            run_tui: None | Some(true),
            run_wallet_owner_api: Some(false) |  Some(true),
            use_db_wallet: Some(false) |  None
        },
        mining_server: Some(StratumServerConfig {
            enable_stratum_server: None |  Some(true),
            stratum_server_addr: None |  Some("127.0.0.1:13416"),
            attempt_time_per_block: 4294967295 | 15,
        }),
        logging: Some(LoggingConfig {
            stdout_log_level: Debug | Warning,
            log_to_file: false | true,
            file_log_level: Trace | Debug,
            log_file_append: false | true,
        }),
        wallet: WalletConfig {
            check_node_api_http_addr: "http://127.0.0.1:13413" | "http://localhost:13413"
        }
    })
}
```

Now, my question is which constants in the code we should change to ones from `grin.toml` file?
Also, do we need both `server.stratum_mining_config` and `mining_server` in `GlobalConfig`?

**Comment by antiochp** [comment]
Thanks for this - this is really useful.
There's one more bit of complexity here, for some of these values we have a "default" deeper in the code if its not set. For example `run_tui` I believe will default to 'true' if its not set (set to None) in `grin.toml`.

Given the fact we distribute an example `grin.toml` and instruct users to move it to the correct place as part of the install/run instructions I would be inclined to go with the `grin.toml` values as sane defaults (and have them default the same way in the code).

**Comment by i1skn** [comment]
@antiochp Agree with approach to "migrate" what we have now in the `grin.toml` file to the code. So, it should be the same with or without default `grin.toml` 👍

**Comment by hashmap** [comment]
We can close it

**Comment by quentinlesceller** [comment]
Closing.
