### ISSUE TITLE
Use a working directory under the user home

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1257]
Currently grin uses the current directory to load different databases, write its logs, read configuration, save wallet files, etc. We should instead rely on a `.grin` under the user home like pretty much all other blockchain daemons.

**Comment by pcdinh** [comment]
Should it be configurable? I think that lots of hard core miners and users may want to move the working directory to a dedicated disk (mount point) for good reasons

**Comment by ignopeverell** [comment]
Yes of course, I should have been clearer that under the home folder should be a default, with a custom location configurable.

**Comment by haarts** [comment]
I think that using the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) should be used here (that uses `~/.local` and `~/.config`). Most modern pieces of software do and that would be expected behavior.

**Comment by yeastplume** [comment]
Done via #1433
