### ISSUE TITLE
Get rid of the clang dependency

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1264]
Building croaring requires clang. However the underlying C implementation does not, clang-format is an optional dependency (assumingly, only for code formatting). So there's likely a missing option in the Rust binding. Figure this out.

Nothing personal against clang but it's a large dependency and creates all sorts of wrinkles from one environment to another and we end up with all sorts of user build errors. So if it's not required, better not have it.

**Comment by jpbriquet** [comment]
I have tried to investigate a little bit about croaring and clang.

It seems that croaring/croaring-sys crates relies on the bindgen crate.
The [bindgen crate](https://github.com/rust-lang-nursery/rust-bindgen) has clang as a dependency and use it to generate rust bindings for croaring C code, that can be seen in the croaring-sys crate build system:
https://github.com/saulius/croaring-rs/blob/master/croaring-sys/build.rs

I could be wrong but I think it will not be possible to remove easily this dependency without changing the croaring-sys crate. 
It might be possible to have a specific process to generate these rust bindings outside of the build.rs, however I'm not sure it would be a accepted by the crate maintainer as it changes lots of things, generated bindings have to be stored on git, a CI must launch the generation process etc...

Rust dependency tree (extract):
│   ├── grin_chain v0.3.0
│   │   ├── ...
│   │   ├── croaring v0.3.2
│   │   │   ├── croaring-sys v0.3.5
│   │   │   │   └── libc v0.2.42 (*)
│   │   │   │   [build-dependencies]
│   │   │   │   ├── bindgen v0.37.4
│   │   │   │   │   ├── ...
│   │   │   │   │   ├── clang-sys v0.23.0
│   │   │   │   │   │   ├── glob v0.2.11
│   │   │   │   │   │   ├── libc v0.2.42 (*)
│   │   │   │   │   │   └── libloading v0.5.0
│   │   │   │   │   │       [build-dependencies]
│   │   │   │   │   │       └── cc v1.0.17
│   │   │   │   │   ├── ...
│   │   │   │   └── gcc v0.3.54 (*)
│   │   │   └── libc v0.2.42 (*)

**Comment by ignopeverell** [comment]
Could that be done easily if we forked `croaring-rs`?

**Comment by jpbriquet** [comment]
I will fork it and will try to remove the dep. If this approach is working I'll let you know.

**Comment by antiochp** [comment]
If we fork `croaring-rs`, remove the dependency on bindgen and use a hand-written ffi.rs (as proposed in #1292) it feels like we are trading one set of complexities for another - 

bindgen - 
* relies on clang dependency

forked repo and custom ffi.rs - 
* more stuff to maintain

My (limited) understanding is that bindgen is the de-facto standard approach for wrapping libs in this way.

I wonder if the benefits outweigh the additional maintenance costs of doing this?

Do we lose any portability (or performance optimizations) if we write `ffi.rs` ourselves? At a glance it appears not but I'm not 100% sure?

**Comment by antiochp** [comment]
As @ignopeverell suggested - if we do this then I think we should consider writing our own minimal `ffi.rs` wrapper around the underlying croaring lib.

i.e. not forking croaring-rs but writing a minimal wrapper from scratch.

But again - this swaps one set of complexity out for another.

**Comment by ignopeverell** [comment]
The difference is that everyone bulding runs into the bindgen complication, while a `ffi.rs` would be only ours to maintain. But let's see how much more pain this causes, it may all be moot as soon as we start distributing binaries.

**Comment by garyyu** [comment]
I close this issue for now, since it looks like this building optimization is not needed anymore.

Anyway, if needed, we can easily re-use the solution provided in #1292
