### ISSUE TITLE
A lot of "refused by chain: Block is unfit: already known"

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1271]
Testnet3, new build on master branch, after completely synced and mined some new blocks, the node then becomes always late from the network, for example, on this writing, the latest height is 11424, but my node is on 11419, and keep the words "downloading blocks 99%". 
```

Jul 17 11:52:12.032 DEBG Block 01d92413 at 11413 is unfit at this time: already known
Jul 17 11:52:12.033 DEBG adapter: process_block: block 01d92413 refused by chain: Block is unfit: already known 
... ... (a lot)
Jul 17 11:54:16.337 DEBG Block 14db084d at 11418 is unfit at this time: already known
Jul 17 11:54:16.338 DEBG adapter: process_block: block 14db084d refused by chain: Block is unfit: already known 
... ... (a lot)
... ... (a lot other blocks)
Jul 17 11:57:38.440 DEBG Block 14db084d at 11418 is unfit at this time: already known
Jul 17 11:57:38.440 DEBG adapter: process_block: block 14db084d refused by chain: Block is unfit: already known 
... ... (a lot)
```

**Comment by garyyu** [comment]
[grin.log.gz](https://github.com/mimblewimble/grin/files/2200188/grin.log.gz)
The full logs could help to address the problem.

**Comment by ignopeverell** [comment]
Quick question: is that on a release build?

**Comment by garyyu** [comment]
Just started another fresh installation on another pc with fresh folder, the sync procedure stuck at height 0 after full headers downloaded, also with a lot of "refused by chain" logs. Now I just kill the process.

This log file is much more simple and smaller, please let me know this will help, then I can upload this new log.

**Comment by ignopeverell** [comment]
A pause of 10-15 min after all headers are downloaded is expected. Or are you running an archive node? In any case more logs would be useful.

**Comment by garyyu** [comment]
I test it again from a new clean **release** build on latest code and install, with all config at default (so, this is a fast mode), run it for **one hour**, the TUI status show "`Downloading headers: 100%, step 1/4`".

grep the log and find 435 lines "`refused by chain`". The full log (file name: `grin.0720.1.log.gz`) attached, please take a look at this major bug.
```
$ grep -c "refused"  grin.log 
435
```
[grin.0720.1.log.gz](https://github.com/mimblewimble/grin/files/2212373/grin.0720.1.log.gz)

**Comment by garyyu** [comment]
Same time but in another mac, also a new clean **release** build on latest code and **clean** install, with all config at **default**, run also for one hour, TUI status also show "`Downloading headers: 100%, step 1/4`", "`Chain Height: 0`".
```
$ grep -c "refused by chain" grin.log
0
```

But in this log, no any "refused by chain". The full log (file name: `grin.0720.2.log.gz`) attached.

[grin.0720.2.log.gz](https://github.com/mimblewimble/grin/files/2212405/grin.0720.2.log.gz)

**Comment by kargakis** [comment]
I run a grin node built from 4a5a41f for +1 hour. It seems stuck in downloading headers (or at least that's what the tui says) and I also see lots of the "Block is unfit" errors.

Log: [grin.log.tar.gz](https://github.com/mimblewimble/grin/files/2214333/grin.log.tar.gz)

**Comment by kargakis** [comment]
Built from https://github.com/mimblewimble/grin/commit/f5b03a6d5acb5aab8607a2545e9537787abff529, still seems an issue

[grin.log.tar.gz](https://github.com/mimblewimble/grin/files/2217412/grin.log.tar.gz)

**Comment by garyyu** [comment]
I think this issue can be closed since related fixes #1281 and #1285 have been merged. 

And @kargakis  could you confirm it's OK? I read your logs but it seems that's syncing normal, (received blocks from block 19249 at 22:31:33 to block 19304 at 23:13:07.  what's the problem you saw? since you said "still seems an issue" :)

**Comment by kargakis** [comment]
Tui seemed stuck on the first step

**Comment by kargakis** [comment]
https://github.com/mimblewimble/grin/commit/3b6b85ec57d62578dd762f3958adf9ceca62d38c seems to have fixed my issue, thanks! :)

**Comment by garyyu** [comment]
OK, Thanks. So I close this issue:)
