### ISSUE TITLE
'wallet_owner_listener' config is hardcoded instead of using external config (grin.toml)

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1274]
```
.//src/bin/grin.rs:471:				wallet::controller::owner_listener(wallet, "127.0.0.1:13420").unwrap_or_else(|e| {
.//src/bin/grin.rs:650:				wallet::controller::owner_listener(wallet, "127.0.0.1:13420").unwrap_or_else(|e| {
```
Should this config go into `grin.toml`?  and could need enable/disable.

**Comment by beaver-tooth** [comment]
Ah! This makes sense. I was getting an `addr already in use` for `wallet_listener`error when running multiple nodes locally.

**Comment by kargakis** [comment]
Making just the port configurable is an option.

**Comment by ignopeverell** [comment]
Closing this for now until someone cares enough to configure the port to make a PR.
