### ISSUE TITLE
wallet send long waiting issue

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1284]
Testnet3, lastest master branch, release build.  wallet send when block height at 18222 (2018-07-22 02:16:54 UTC), but this transaction waited 120 blocks and finally was included into a block 18343 (2018-07-22 03:41:49 UTC) https://grinscan.net/block/18343 

What could cause this long wait for 1 hour 25 minutes for a transaction to be included in a block? normally it should be very fast.

On the sender side:
```
$ ./target/release/grin wallet send -d http://192.168.1.129:13415 7.7 -c 6 -s smallest
Jul 22 10:53:16.651 INFO This is Grin version 0.3.0 (git testnet3-42-gf948b48), built for x86_64-apple-darwin by rustc 1.27.1 (5f2b325f6 2018-07-07).
Jul 22 10:53:16.660 DEBG Built with profile "release", features "" on Sat, 21 Jul 2018 13:02:16 GMT.
Jul 22 10:53:16.738 DEBG Building input (spending coinbase): 60000000000, 165717329209d2569b0a
Jul 22 10:53:16.745 DEBG Building an output: 52292000000, 626fdf9d57d96682809e
Jul 22 10:53:16.764 TRCE Builder - Pedersen Commit is: Commitment(086da42ffa4f871e91305858daa7b70e492810b07b0499c8f8ae8c239b717aa643)
Jul 22 10:53:16.885 DEBG Posting transaction slate to http://192.168.1.129:13415/v1/wallet/foreign/receive_tx
Jul 22 10:53:17.143 DEBG Validating final transaction
Jul 22 10:53:17.247 INFO Tx created: 7.700000000 grin to http://192.168.1.129:13415 (strategy 'smallest')
Jul 22 10:53:17.341 INFO Tx sent
```

Log on the recipient side:
```
Jul 22 10:53:16.913 DEBG Building an output: 7700000000, d92c411ad53c99eb7b29
Jul 22 10:53:16.933 TRCE Builder - Pedersen Commit is: Commitment(086d94cc05b39610a02881337892de123538fa2016dfb1c9ebd6274c1a8a11264a)

```
Netlog:
`"height":18222,"lock_height":18222`

**Comment by hashmap** [comment]
The similar case was reported in gitter by @photis today:

Trying to consolidate my wallets outputs in one fell swoop (all of the coins). Tx sent successful, but receive still lacking after 70 blocks mined.
```
Aug 16 08:08:10.297 DEBG Posting transaction slate to http://127.0.0.1:13415/v1/wallet/foreign/receive_tx
Aug 16 08:08:10.490 DEBG Validating final transaction
Aug 16 08:08:10.595 INFO Tx created: 849472.000000000 grin to http://127.0.0.1:13415 (strategy 'all')
Aug 16 08:08:10.818 INFO Tx sent
```
Now 80 blocks have been mined. The transaction was sent at block height 53813

**Comment by hashmap** [comment]
I also experienced it couple times sending all coins.  Might it be related to https://github.com/mimblewimble/grin/issues/1325?

**Comment by ignopeverell** [comment]
I think things are much better now. If they're still slow it's prolly for different reasons, which would be worth another issue.
