### ISSUE TITLE
Secure access to the grin API by default

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1290]
Access to the node API is unsecure by default, which means I can easily write a script to determine all nodes that expose their API to the public, and fiddle with them (eg. ban other peers). grin should provide an option to selectively limit access to its APIs via some sort of auth layer. I can see use cases where someone would want to expose some parts of the API like chain height but not others like peers or access to mutating calls. If exposing the web server publicly is not recommended and we don't care about auth, we should at least document it.

**Comment by bladedoyle** [comment]
By default, access to the API is limited by the sockets listening only on 127.0.0.1

https://github.com/mimblewimble/grin/blob/54d3fc0af2c6e012f234358b5dd2722172c61238/grin.toml#L21
