### ISSUE TITLE
[sync] remaining issues

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1293]
lehnberg @lehnberg 17:12

```
FYI, built the latest from master just now and removed .grin as discussed before, this time around I synced seamlessly. Can’t have taken me more than five minutes. ✌️
git fetch upstream
git merge upstream/master
cargo clean
cargo build --release
rm -rf .grin
RUST_BACKTRACE=1 ./target/release/grin
```

Gary Yu @garyyu 17:34
`less than 5 minutes is also odd :) do you have a powerful PC? even the fastsync mode, the validation procedure is slow on my mac air. will measure how long I need.`

Gary Yu @garyyu 19:08
```
@lehnberg I’m not lucky, fastest time I need 15 minutes to sync. so it’s possible your MBP 2016 is 3 times faster than my macpro 2013.
and sync procedure still buggy :(
I tested 2 times:
1st time on my poor old mac:

- spent 2’30” for header download,
- spent 5 minutes to download the TxHashsets, ( not lucky! could download from a very slow peer! )
- spent 7' to validate chain state,
- spent 24 minutes to download remaining blocks and finish syncing. (buggy here! paused for a * while no any blocks coming and force to quit and start again).

2nd time, on a mac pro 2013

- spent 1’46” for header download,
- spent 6" to download the TxHashsets, (buggy here! paused for Error summing and verifying kernel sums, and have to force quit and start again, 6 seconds is for 2nd time).
- spent 8' to validate chain state,
- spent 5’30" to download remaining blocks and finish syncing.

```

**Comment by garyyu** [comment]
1st question is: what's the root cause of an `Error summing and verifying kernel sums`?

**Comment by ignopeverell** [comment]
It generally means the downloaded kernels failed to validate. It could be a consensus failure but it's a lot more likely to be caused by some download failure or corrupted file.

**Comment by garyyu** [comment]
Is there possibility to restart downloading the TxHashsets in case errors?  in current implementation it will stuck here. I checked before, it seems no existing way to notify sync thread about this error event .

**Comment by ignopeverell** [comment]
We should maybe rely on the sync status to communicate those errors across parts of the system. This would allow fast sync to retry I believe.

**Comment by garyyu** [comment]
Good idea :)
I prefer to add a `sync_error` field into `SyncState` to communicate those errors:

```
/// Current sync state. Encapsulates the current SyncStatus.
pub struct SyncState {
	current: RwLock<SyncStatus>,
	sync_error: RwLock<Result<String, String>>,
}
```

**Comment by garyyu** [comment]
Eventually, 3 fixed merged for this one:

1. txhashset validation fail will restart the fast_sync;
2. handle sending request failure of 'send_txhashset_request';
3. use a 10-mins timeout to handle no-response failure, in case a peer ignore our txhashset request, or in case a peer fail to send a file for some reason.

That should be enough to handle all those sync error cases~
So I close this issue. If any new sync issue happen, please create new one to follow.
