### ISSUE TITLE
Conform to BIP-schnorr

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#1294]
Ensure that Grin's implementation of Schnorr signatures conforms to what will be supported in Bitcoin: https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

From /dev on Gitter:
>John Tromp @tromp Jul 16 00:06
actually, we should adopt the bitcoin proposal https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

**Comment by quentinlesceller** [comment]
@jaspervdm Isn't it already implemented? Can we close it?

**Comment by jaspervdm** [comment]
Yes, this can be closed.
