### ISSUE TITLE
discussion: data validation during read()

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1337]
Right now we have validation rules in `read()` that we use to ensure we are not deserializing "corrupt" data from the network.

Feels like we are putting validation rules in two different places with this pattern, both in `validate()` and `read()`. And its going to become increasingly complex to maintain these over time.

One exampe of this is validating timestamps in `BlockHeader::read()` - 
https://github.com/mimblewimble/grin/blob/9c05471979082753c7dd047d8be7ec5f43bb6f44/core/src/core/block.rs#L194-L196

It would be nice to have these validation rules in a single place.
See #1334 for one approach where we call `tx.validate()` from `Transaction::read()`.

But I'm not sure we can (or if it makes sense to) do this everywhere?
Do we have cases where these validation rules are specific to serialization/deserialization?

There are also cases where validation (currently) relies on external state. We need current chain state to validate a block for example.
But it would be nice to be able to validate a block as part of read() deserialization, for example.

Related - #1333.

**Comment by hashmap** [comment]
Not sure if it's possible for all rules, but we should try to move as much as possible to `validate`.

> Do we have cases where these validation rules are specific to serialization/deserialization?

Your block example is actually deserialization-specific, we can't create BlockHeader with invalid timestamp, `chrono` will panic (don't understand why they don't use `Result` but panic internally)
