### ISSUE TITLE
Measure performance at size limits

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1343]
To avoid bad surprises we should measure times to:

* Add a block close to max weight to an empty chain.
* Add a block close to max weight to a larger chain.
* Add a transaction close to max weight to an empty pool.
* Add a transaction close to max weight to a full pool.
* Add lots of small transactions to a full pool.
* Any other?

Ideally we'd have a utlity somewhere to run these scenarios (a bit like @hashmap fuzzer) whenever we want to. Probably not fit for travis CI at the moment.

Related: #1336. Data is the only way to come up with sensible constant values.

**Comment by antiochp** [comment]
Indirectly related to this - working on adding the ability to create multiple change outputs during tx building from the wallet. So we have some flexibility around _increasing_ the number of outputs to make scenarios like this easier to test.

**Comment by antiochp** [comment]
These are not at the weight/size limits of txs or blocks but its an early data point -

```
Aug 22 20:55:35.830 DEBG handle_payload: received tx: msg_len: 372802
Aug 22 20:55:44.405 DEBG Received tx b02ee67c, inputs: 500, outputs: 496, kernels: 1, going to process.
Aug 22 20:55:52.578 DEBG pool [txpool]: add_to_pool: b02ee67c, TxSource { debug_name: "p2p", identifier: "?.?.?.?" }, inputs: 500, outputs: 496, kernels: 1 (at block 30f4d37c)
```

```
Aug 22 20:56:04.339 DEBG handle_payload: received compact block: msg_len: 1192
Aug 22 20:56:04.340 DEBG Received compact_block 1edf9407 at 307 from 127.0.0.1:13414, outputs: 1, kernels: 1, kern_ids: 1, going to process.
Aug 22 20:56:04.342 DEBG adapter: txs from tx pool - 1
Aug 22 20:56:12.488 DEBG adapter: successfully hydrated block from tx pool!
Aug 22 20:56:12.488 DEBG pipe: process_block 1edf9407 at 307 with 500 inputs, 497 outputs, 2 kernels
Aug 22 20:56:20.598 DEBG pipe: chain head 1edf9407 @ 307
Aug 22 20:56:20.599 DEBG adapter: block_accepted: 1edf9407
```

**Comment by ignopeverell** [comment]
Doesn't look too good, especially with many outputs. Hopefully batch verification will help a lot.

**Comment by antiochp** [comment]
Yeah... that might have been a false alarm...

Just ran that manual test again locally after seeing #1412 had been merged - 

```
Aug 23 22:10:18.695 DEBG handle_payload: received tx: msg_len: 358318
Aug 23 22:10:19.111 DEBG Received tx 42217ba7, inputs: 74, outputs: 496, kernels: 1, going to process.
Aug 23 22:10:19.416 DEBG pool [txpool]: add_to_pool: 42217ba7, TxSource { debug_name: "p2p", identifier: "?.?.?.?" }, inputs: 74, outputs: 496, kernels: 1 (at block 35258062)
```

```
Aug 23 22:10:20.018 DEBG handle_payload: received compact block: msg_len: 1192
Aug 23 22:10:20.018 DEBG Received compact_block 1abdad75 at 248 from 127.0.0.1:13414, outputs: 1, kernels: 1, kern_ids: 1, going to process.
Aug 23 22:10:20.019 DEBG pipe: process_block_header at 248 [1abdad75]
Aug 23 22:10:20.019 DEBG adapter: txs from tx pool - 1
Aug 23 22:10:20.449 DEBG adapter: successfully hydrated block from tx pool!
Aug 23 22:10:20.449 DEBG pipe: process_block 1abdad75 at 248 with 74 inputs, 497 outputs, 2 kernels
Aug 23 22:10:20.843 DEBG pipe: chain head 1abdad75 @ 248
Aug 23 22:10:20.844 DEBG adapter: block_accepted: 1abdad75
```

I suspect my original test was a Cargo `development` and not `release` build...

**Comment by ignopeverell** [comment]
Yes, we should do that memoization at least for every piece that's costly and indivisible (like outputs and kernels). For comparison, bitcoin core has a cache of already validated signatures, so that even later when they appear in blocks they don't need to be rechecked.

**Comment by antiochp** [comment]
Cool - I'm working on that today for a bit - likely just starting with rangeproofs initially as this is pretty localized in terms of validation of these anyway.

Does bitcoin core have a cache in memory or does it store this in the db? I'm guessing in the db so it persists across restarts?

**Comment by ignopeverell** [comment]
I'm not positive but I think it's a memory cache. After a restart, which usualy wont be immediate, most of the cache is going to be irrelevant.

**Comment by antiochp** [comment]
See #1419 for initial pass at a memory cache for rangeproof and kernel signature verification.

**Comment by ignopeverell** [comment]
@antiochp do you still have those tests handy? Wouldn't it be good to commit them (even if turned off)?

**Comment by antiochp** [comment]
These were "tests" - creating big txs locally via `grin wallet send` cli...

**Comment by ignopeverell** [comment]
Going to close this. A fair amount of testing has already been done on the various testnets.
