### ISSUE TITLE
block processing feels slower

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1344]
Running a sync to catch up after having a node turned off for several hours.
Something feels slow - each block is taking approx 300-400ms to process.
I'm _sure_ we used to process blocks significantly faster than this.

This is with a development build so it will be slower than a release build but it still seems slower than it used to be (although I have no evidence to actually show this).

Could rocksdb vs lmdb have an impact here somewhere in the block processing pipeline?
Or do we have something that is slowing processing down as chain state grows?

```
Aug 11 09:30:02.249 DEBG pipe: process_block 0bc1f046 at 46581 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:02.613 DEBG pipe: chain head 0bc1f046 @ 46581
Aug 11 09:30:02.618 DEBG pipe: process_block 0fdace74 at 46582 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:02.978 DEBG pipe: chain head 0fdace74 @ 46582
Aug 11 09:30:02.982 DEBG pipe: process_block 0cfb2e7f at 46583 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:03.361 DEBG pipe: chain head 0cfb2e7f @ 46583
Aug 11 09:30:03.364 DEBG pipe: process_block 0bf1dc24 at 46584 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:03.726 DEBG pipe: chain head 0bf1dc24 @ 46584
Aug 11 09:30:03.730 DEBG pipe: process_block 0f24bf46 at 46585 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:04.098 DEBG pipe: chain head 0f24bf46 @ 46585
Aug 11 09:30:04.101 DEBG pipe: process_block 09a318bb at 46586 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:04.462 DEBG pipe: chain head 09a318bb @ 46586
Aug 11 09:30:04.465 DEBG pipe: process_block 0e87377f at 46587 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:04.837 DEBG pipe: chain head 0e87377f @ 46587
Aug 11 09:30:04.840 DEBG pipe: process_block 12c9d39c at 46588 with 0 inputs, 1 outputs, 1 kernels
Aug 11 09:30:05.219 DEBG pipe: chain head 12c9d39c @ 46588
```

**Comment by ignopeverell** [comment]
Still feeling it?

**Comment by antiochp** [comment]
Related - #1419.
I _think_ this is linked to our changes around block deserialization.
We added a step to the deserialization to validate the block, and treat a validation error as a deserialization error, specifically to check for max weight. This was also verifying kernel signatures and output rangeproofs.
We then fully validated the block a second time during the block processing pipeline, verifying the kernel signatures and output rangeproofs a second time.

The rangeproof verification takes a noticeable amount of time in a debug build so doing this twice per block was having an impact here.
