### ISSUE TITLE
sync head in apparent loop when syncing from scratch

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1357]
Trying to sync the chain from scatch, and each time I re-start grin the sync head appears to progress for a while, but then gets stuck apparently processing a range of blocks over and over again. Had to restart dozens of times to get the header download to 100%. Haven't had time yet to look into this much further as I'm trying to get some secp256 stuff out of the way, but here's the log in the meantime:

[grin-problem-sync-loop.log](https://github.com/mimblewimble/grin/files/2290099/grin-problem-sync-loop.log)

**Comment by ignopeverell** [comment]
Someone sent you block headers late. We don't check whether the header is already known before saving and resetting the sync head and header head (oops). So it flips flops, and then you ask for more headers for the flip and the flop, leading to more flip-flopping.

**Comment by yeastplume** [comment]
Still occurring with 100% consistency on latest master.. see attached log from trying to re-sync after not running node for a couple of days:

[grin.log](https://github.com/mimblewimble/grin/files/2302179/grin.log)

**Comment by ignopeverell** [comment]
Slightly better, at least you're progressing... albeit very slow because it looks like every header is triple-processed. More headers are getting requested  regularly before the previous batch is done with, going to check that out now.

**Comment by yeastplume** [comment]
Did a fast-sync now from scratch, no issues. All good here.
