### ISSUE TITLE
Aggsig signature hash being computed incorrectly

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1358]
See: https://github.com/mimblewimble/secp256k1-zkp/pull/21/files

Only the first 8 bytes of the public key in the sighash are being hashed into the signature hash, whereas the full 32 bytes should be written. Will need to wait for a hard fork and provide a switch to that function in order to fix this.

**Comment by ignopeverell** [comment]
Oops. Yes. Nicely spotted @garyyu

**Comment by ignopeverell** [comment]
Is this merged? Can we close this now?

**Comment by garyyu** [comment]
Yes. Closed by #1501 and the PR in secp256k1-zkp repo: https://github.com/mimblewimble/secp256k1-zkp/pull/22
