### ISSUE TITLE
Skip reading commitments in `wallet info`

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#1370]
and other places where we don't show outputs.

(Related to https://github.com/mimblewimble/grin/pull/1365) There's an additional db read per output (to get the commitment). It's ok to pay this price in wallet operations where we show outputs, but it also slows down `grin wallet info`. I time-d it on a wallet with ~1900 outputs:
The current maser
```
real    0m2.704s
user    0m2.228s
sys     0m0.011s
```
same code + revert of the commit:
```
real    0m1.070s
user    0m0.504s
sys     0m0.023s
```

`grin wallet outputs` takes the same time, but it doesn’t feel slow, user has different expectations.

Would be nice to skip commitments reading for ops when we don’t show outputs.

**Comment by i1skn** [comment]
I would like to tackle on this one

**Comment by yeastplume** [comment]
I've done some work around this recently (and the DB read is much, much preferable to having to recalculate them). I think we're okay here unless this is identified as a bottleneck on mainnet code
