### ISSUE TITLE
2 versions of Hyper in dependencies

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#1371]
Reqwest `0.7.3` brings Hyper `0.11` in addition to already existing Hyper `0.12`.  We may want to upgrade to Reqwest `0.8.8`, however as I can  see on crates.io it still depends on Hyper `0.11` despite the fact that in the repo upgrade to `0.12` was merged a while ago and crate was published after that:
https://github.com/seanmonstar/reqwest/commit/c417d6dab823324cde59e2badeb861a3e677e958

**Comment by yeastplume** [comment]
The Reqwest version of hyper should only be a build dependency, and I thought it was pulling in hyper 0.12 as well. Will have another look at this and see if there's an alternative to Reqwest.. all it's doing is downloading a file

**Comment by hashmap** [comment]
``` 
cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 11 security advisories (from /home/arch/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (269 crate dependencies)
error: Vulnerable crates found!

ID:	 RUSTSEC-2018-0003
Crate:	 smallvec
Version: 0.2.1
Date:	 2018-07-19
URL:	 https://github.com/servo/rust-smallvec/issues/96
Title:	 Possible double free during unwinding in SmallVec::insert_many
Solution: upgrade to: >= 0.6.3 OR ^0.3.4 OR ^0.4.5 OR ^0.5.1
```

I found that `0.2.1` is a dep of `tokio-proto 0.1` which is a dep of hyper `0.11` which is a dep of `reqwest`. Will try to fix it.

**Comment by hashmap** [comment]
I resolved this issue by bumping `reqwest`. Hyper version update has not been published yet, so nothing we can do. Let's close it, a simple version bump in the future will resolve it.
