### ISSUE TITLE
Make Grin Less Monolithic

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1378]
A meta issue based on a brief discussion on gitter yesterday, hopefully we can discuss a strategy here.

Right now Grin comes fully loaded with several ancillary services by default, including:

* 'Core' grin p2p service
* Node API
* Stratum server
* Transaction pool
* Wallet and wallet APIs
* Static Web server for the wallet application

It's probably preferable to be able to build a 'minimal' grin with just the core p2p/validation service, and optionally include some, all or none of the other components.

There would be a few ways of achieving this, but the path of least resistance would probably be to conditionally build and include each component as compile time features. We'd want to be sure that if a component is excluded, then all associated code isn't built into the binary. Another possibility could be to split up the features into separate projects on top of grin.

However it's done, a good amount of rejigging is likely to be required.

**Comment by ignopeverell** [comment]
Another simple possibility would be to have a couple different main crates under `src/bin`. I think we'd only need a couple of these, maybe 3 at most. Overall, grin is already fairly compartmentalized.

**Comment by kargakis** [comment]
Web server and the wallet are out now. Anymore for anymore?

**Comment by ignopeverell** [comment]
This was a little too vague anyway.
