### ISSUE TITLE
Amount sent is 1 nanogrin short

### ISSUE THREAD

**Issue by yorickdowne** [mimblewimble/grin#1384]
Edit - please check further down, fee was right, but amount sent was 1 nanogrin short of 66.6.

Okay here's one for the grin crew. When I sent 66.6, with a 0.005 fee, it actually didn't use a 0.005 fee, it used a 0.004999(etc) fee, like this:
Sent Tx 4d23408a-b8a8-4d63-82ec-b71a56c55e5c 2018-08-19 12:11:23 true 2018-08-19 16:11:05 4 1 118.395000001 185.0 0.005 -66.604999999

**Comment by yorickdowne** [comment]
Repeated the test
grin wallet send -d http://1.testnet.grin.mably.com:13415 66.6

And have replicated the issue. Fee 0.007, actual fee applied 0.00699999(etc)

 10  Sent Tx             3c1b0588-411d-4312-ac16-fc7d8a3fdd96  2018-08-19 21:03:51  false       None                 2            1             55.120000002     121.727000001   0.007  -66.606999999

**Comment by yorickdowne** [comment]
Correction: The fee is correctly applied, but the recipient is short 1 nanogrin.
https://i.imgur.com/2vzbSkR.png

**Comment by yorickdowne** [comment]
yorick@meepu:~/grin$ grin wallet txs -i 10

Transaction Log - Block Height: 58892
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Id  Type     Shared Transaction Id                 Creation Time        Confirmed?  Confirmation Time    Num. Inputs  Num. Outputs  Amount Credited  Amount Debited  Fee    Net Difference
============================================================================================================================================================================================
 10  Sent Tx  3c1b0588-411d-4312-ac16-fc7d8a3fdd96  2018-08-19 21:03:51  true        2018-08-19 21:21:33  2            1             55.120000002     121.727000001   0.007  -66.606999999
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Wallet Outputs - Block Height: 58892
---------------------------------------------------------------------------------------------------------------------------------------------------
 Output Commitment                                                   Block Height  Locked Until  Status   Coinbase?  # Confirms  Value          Tx
===================================================================================================================================================
 0801e184bde5a59fcf3b43e5ab0322b35a0d234dac9d4678db9f394382312461a3  58831         0             Spent    false      62          111.727000001  10
---------------------------------------------------------------------------------------------------------------------------------------------------
 09a487fc1c638fecb5f9d6ae83af6b1b2bd92ee0032a3c98f844c3e76d75f994ac  58834         0             Spent    false      59          10.000000000   10
---------------------------------------------------------------------------------------------------------------------------------------------------
 09d900e4c382b5f2b8cebf886c4556ba8941559a8d84eded4f91c3748039fd0ef4  58860         0             Unspent  false      33          55.120000002   10
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by yorickdowne** [comment]
First test
```
yorick@meepu:~/grin$ grin wallet txs -i 6

Transaction Log - Block Height: 58897
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Id  Type     Shared Transaction Id                 Creation Time        Confirmed?  Confirmation Time    Num. Inputs  Num. Outputs  Amount Credited  Amount Debited  Fee    Net Difference
============================================================================================================================================================================================
 6   Sent Tx  4d23408a-b8a8-4d63-82ec-b71a56c55e5c  2018-08-19 12:11:23  true        2018-08-19 16:11:05  4            1             118.395000001    185.0           0.005  -66.604999999
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Wallet Outputs - Block Height: 58897
-------------------------------------------------------------------------------------------------------------------------------------------------
 Output Commitment                                                   Block Height  Locked Until  Status  Coinbase?  # Confirms  Value         Tx
=================================================================================================================================================
 0996adbddacb554a65a667646ccc0bccb9e5bca75e2c9cd7278911302b35f1f383  42947         43947         Spent   true       15951       60.000000000  6
-------------------------------------------------------------------------------------------------------------------------------------------------
 08b570624b6717196f5617fcc60c8d9de1be4da3f73ae47e3b01136c8637ded922  44845         0             Spent   false      14053       5.000000000   6
-------------------------------------------------------------------------------------------------------------------------------------------------
 087791bf085299046141360e2cedffe7068e043dbebd461b85631ede6de3844bf7  47047         48047         Spent   true       11851       60.000000000  6
-------------------------------------------------------------------------------------------------------------------------------------------------
 081624fb9cb016306bbde011ccb951a04d1534233b8b97855cdf2a3db1147d39c8  56975         57975         Spent   true       1923        60.000000000  6
-------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by antiochp** [comment]
So the first thing we do (as far as I can tell) is convert the amount being sent (6.66 grin) into a u64 internally - 

https://github.com/mimblewimble/grin/blob/105bfacaa6ff2f5dbc24c00e0b3164999d025c8b/src/bin/cmd/wallet.rs#L160-L161

https://github.com/mimblewimble/grin/blob/105bfacaa6ff2f5dbc24c00e0b3164999d025c8b/core/src/core/mod.rs#L198-L204

So its not immediately obvious why we're getting the fee wrong here (we're not operating on an amount represented as a float).

**Comment by yorickdowne** [comment]
Just a quick comment: I thought the fee was wrong but it’s not. It appears the amount sent itself is 1 nanogrin short.

Happy to test this again at anytime

**Comment by OpticFlowX** [comment]
I'm not fluent in Rust, but it seems to me that: 
The "amount" string is parsed as float, the constant GRIN_BASE is cast from unsigned integer to float, then the two float values are multiplied and the result is cast to unsigned integer. 

"Casting from a float to an integer will round the float towards zero" -- https://doc.rust-lang.org/book/first-edition/casting-between-types.html#numeric-casts

**Comment by yorickdowne** [comment]
No solution right now, and yes, the floating point arithmetic before casting to u64 has to be at issue here. This claims that f64 in rust can be fickle:
https://stackoverflow.com/questions/50361151/how-to-deal-with-inexact-floating-point-arithmetic-results-in-rust

One option might be to have a way to parse this input that literally moves the decimal point in the string, then parses as int; rather than parsing as float first.

**Comment by ignopeverell** [comment]
Yes, exactly (for the option).
