### ISSUE TITLE
Proposal - decouple public wallet receiver from wallet private keys

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#140]
Recent topics have got me thinking a bit about how the current wallet implementation could be improved.
Today we have a single "wallet receiver" that sits listening for http requests on a given port.
This process needs to be publicly accessible _and_ requires access to the wallet private key.

A sending wallet posts a partial txn to the receiver wallet (so receiver needs to be publicly accessible).
Schnorr signatures will change the flow but the wallets will still need to interact.

Ideally the process that has access to the wallet private keys is not publicly accessible and this suggests a slightly different topology - 

```
(wallet sender) --> [internet] --> (wallet receiver) --> (private wallet process)
```

* The `wallet receiver` listens on `0.0.0.0:13417`
* The `private wallet process` listens on `127.0.0.1:13416`
* A mining node talks to the `private wallet process` locally to build coinbase outputs.
* A wallet sender could talk to both the `private wallet process` (to build the partial txn) and the wallet receiver on the other side of the txn.

At the cost of additional complexity this would allow the process with access to the private key/seed to be locked down to only accept local connections, while allowing a more open wallet receiver to be run as a standalone process (effectively proxying requests to the private wallet).

Thoughts?

**Comment by ignopeverell** [comment]
I agree with your separation, it's something that needs to be done.

Separately (and just because this seems like a good time to mention it), @apoelstra mentioned a trick with the range proofs where we can introduce both a spending key and a view key, both having different characteristics. It has impacts on the range proof size though.

Regardless, the change you propose is a good first step.

**Comment by antiochp** [comment]
Yeah I remember seeing that mentioned somewhere (probably the mailing list).
I'm assuming this would be done down in the secp256k1-zkp lib?

**Comment by yeastplume** [comment]
I agree with the need for this, but really don't like the idea of having yet another port to configure and manage.. we're now talking about having to manage two processes to run a simple server, and three to run a mining server, and having to lock them all down appropriately. Given MW's already a bit more cumbersome than usual to run due to the need for a wallet listener, I think we should actively aim to keep the setup complexity to a minimum.

Are there other ways to do ensure that the key is kept of the public-facing process without having to manage another port? Forking, execing, spawning a separate daemon process... I know we're working with rust as opposed to posix directly, and also have to consider the fact we'd potentially want this to run on windows one day, so another port might just be the only solution (unless we come up with something clever), but I'd still like to have a think about other ways of addressing this.

**Comment by antiochp** [comment]
Yeah - even if we fork off or spawn a separate process we're going to need to communicate between them.
Just been reading about this - https://github.com/softprops/hyperlocal
> rustlang hyper bindings for local unix domain sockets

So something like that *may* be one option to explore.

We may also want to consider something like zeromq where we can do something lower level than http but still have decent message semantics between processes.
This could be done via IPC over local sockets for example - 
http://zeromq.org/
http://api.zeromq.org/2-1:zmq-ipc

I think initially we should stick with simple http apis between the various processes (and live with additional ports) - but there are definitely other options for inter-process communications.
And some may give us easier ways to avoid the "many ports" problem.

Running/operating wallets is going to be a *really* high barrier to entry for Grin outside of an initial early adopter group.
There is considerably more "product" involved in simply enabling one user to send coins to another user - 
* no public addresses
* identity/discovery - some user has some wallet url somewhere
* transaction construction is interactive
* need to securely run a public web server
* need to traverse a wide variety of network infrastructure from wallet A <--> wallet B
* etc.

I'm not convinced the public "wallet receiver" is really a viable solution long-term.
Somebody will lose their coins at some point because of a misconfigured firewall or router.

And yeah - I'm hoping eventually the wallet keys are in a hardware wallet, Trezor or similar. Keys never leave the device. And the wallet receiver (wherever it lives, whatever form it takes) communicates with it as needed.

**Comment by apoelstra** [comment]
I agree this needs to be done but we should think carefully about how the separate processes communicate with each other. In particular the privkey-holding process should be something that can be done on a hardware token with minimal or no shimming.

We might consider looking at PKCS#11 and seeing if we can fit entirely within that spec.

**Comment by antiochp** [comment]
Ahh ok. I was thinking most of the wallet functionality would be on the "private wallet api" and that only the "receive partial txn" endpoint would be on the public api.

But I think you're suggesting an alternative approach where the *only* piece of this on the separate process is the key management part of it.
That makes a lot of sense.

**Comment by antiochp** [comment]
Interesting overlaps with discussion here around both handling secure data in hardware and contact discovery - 
https://signal.org/blog/private-contact-discovery/

**Comment by yeastplume** [comment]
Just occurring to me reading this that hardware wallets are going to be large pain as well for hardware wallet developers, as all MW specific private-key sensitive operations implemented in secp such as commits and rangeproofs will have to be implemented in a smartcard environment. With schnorr sigs it may become more prevalent to send partial transactions around in a more offline fashion and then have them completed on a hardware device then posted.

PKCS#11 is fairly flexible, (though I can't say with certainty all these operations will fit without some investigation,) but I think it's the right direction to be looking in given the increasing prevalence of hardware wallets.

**Comment by antiochp** [comment]
This looks interesting (future research) - 
https://github.com/baidu/rust-sgx-sdk

**Comment by maufl** [comment]
I'm sorry if this is off topic, but this seems to be the most fitting open issue so far. Also, I don't understand too much of the crypto involved so this might be a silly question.
Could the concept of stealth addresses be used to make MimbleWimble transactions non interactive?

**Comment by sesam** [comment]
Interesting question. My quick guess is this would require some kind of scripting, i.e. Scriptless Scripts. Should be doable that way, sometime in the future. But I'm guessing.

If you don't get other answers here, maybe try to reach the more theoretically aware people on the [mailing list](lists.launchpad.net/mimblewimble/)

**Comment by yeastplume** [comment]
@maufl @sesam The short answer is no. MW doesn't have the concept of addresses, and there is no way to put a transaction together without both sender and receiver taking part; those are just fundamental properties of the MW format. 

@maufl I'd suggest reading through the intro doc here https://github.com/mimblewimble/grin/blob/master/doc/intro.md as a start. There are some good links there to further information, including a decent link to a relatively digestible introduction to EC fundamentals.

**Comment by maufl** [comment]
Thanks for the pointers. I read the intro, this is why I got the idea that stealth addresses might be applicable. As far as I understand MW, the payment receiver must add an excess value to the transaction, which is a ecc public key. As far as I understand stealth addresses in Bitcoin, the idea is that a payer can non interactively generate a ecc public key for a payee, so that only the payee can generate the corresponding private key. This is why I thought it could work here. But reading the intro again, I see that the payee has to generate a signature using the excess value key, which would again require interaction.

**Comment by sesam** [comment]
Once youve digested the docs/* related things, maybe try this document https://github.com/mimblewimble/docs/wiki/Design-discussions that might be a bit easier to digest than what's on the mailing list

**Comment by sesam** [comment]
@antiochp what is left to be done on this bug now after you've landed #652  ?

**Comment by antiochp** [comment]
#652 is only tangentially related.

The bigger issue here (and this is more a research question and less concrete code impl) -
If we require a process to be online and accessible via http - how do we keep the private keys secure?

We are _literally_ running a web server with our private keys held in process memory.

So if we start from the perspective of "assume the keys were held in a Trezor-like device" - what would communication look like between the wallet process and the hardware device?
And then short-term - can we do something analogous to this with a standalone software process (so the process holding the keys is not exposed to the internet).

And if tx creation is interactive - what does that communication look like (say you had to push a button on the hardware device to "approve" a tx, but you're not at your computer when the tx arrives...)

**Comment by antiochp** [comment]
This looks interesting (hardware key management and tx signing) - http://blog.opendime.com/coldcard-annoucement/

Runs micropython on device, so _potentially_ something that could be Grin compatible? We'd need something more sophisticated than simply generating signatures - ability to generate commitments, rangeproofs etc. on device so the keys can stay on device.

**Comment by antiochp** [comment]
Closing this - wallet architecture has gone through several design and impl iterations.
