### ISSUE TITLE
wrap TcpStream in BufStream (buffered read and write)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1402]
From reading about `TcpStream` in Rust it looks like a common pattern is to wrap it in a `BufStream` - 

https://docs.rs/bufstream/0.1.3/bufstream/

We may be able to 
a) simplify some of our code this way
b) get better performance (maybe?)

**Comment by ignopeverell** [comment]
Yes on b). On a) it's worth a try, but keep in mind that most of the code you're thinking of (I think) is here to tackle async TCP connections, which the standard libraries don't help much with.

**Comment by garyyu** [comment]
No, that won't help anything. I tried before when I give optimization for HeaderSync.

Let me write a demo code for you:  https://gist.github.com/garyyu/05231bd2c09fd561729e89cffd45a0d4

And the test result for 100_000 loops:
```
$ ./target/release/bufstream-test 
TcpStream with BufReader()	took 479.92334ms
TcpStream with Read()		took 473.214472ms

BufStream with Read()		took 477.705873ms
```

**Comment by antiochp** [comment]
Closing.
