### ISSUE TITLE
msg:write_all vs. conn::write_all

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1403]
We call `msg::write_all()` is a bunch of places.
But we have some instances of calling `conn.write_all()` directly.

https://github.com/mimblewimble/grin/blob/b74e0fbc1fb2810f970a5e2f1eac51c77635cf76/p2p/src/conn.rs#L115

https://github.com/mimblewimble/grin/blob/25e03aadeffb8dd5241cd77cd1dfd53bfe134f26/p2p/src/msg.rs#L253

Should we be calling our own `msg::write_all()` consistently?

**Comment by ignopeverell** [comment]
It'd be good for write_all, that could cause some `WouldBlock` errors. On the read side we have to be more careful as there are places where we want to block on read, mostly for message bodies, and places where we don't want to, mostly to check whether we can read a header now or not.
