### ISSUE TITLE
thread::yield_now() vs thread::sleep()

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1404]
I open this issue to record this little research.

To recap the discussion in Gitter:

> Ignotus Peverell @ignopeverell 11:53
> 
> makes me think there should be a better alternative to sleep(1) in read_exact as well, that seems suboptimal
>
> Gary Yu @garyyu 12:01
> yield_now() will give more chance to read since read is on a async TcpStream, Yes? I can try it to check whether the count number increase. We want less sleep() call, right?
>
> Ignotus Peverell @ignopeverell 12:03
> the sleep exists just to let some time for the buffer to fill and have the next read get something, but 1ms is a long time, we actually a short pause to avoid a busy loop, so yield_now() might be it
alternatively, sleep for some nanosecs instead of 1 ms
>
> Gary Yu @garyyu 12:04
> OK, will try it
> 
> Ignotus Peverell @ignopeverell 12:05
> thanks! I was rewriting the whole p2p crate when I wrote this so didn't really have time to finick or check perfs around it
> so thanks for looking into it!
> 

1. About `std::thread::yield_now()`, I test it and it's very strange that it doesn't work like our expectation, look like once call it, the `scheduler` will never come back to wake up this thread anymore. Then suddenly I realized that `yield_now()` is not what we want, because in our `read_exact()` context, we indeed want to stick in this thread for the TCP stream data integrity.

2. And about changing `thread::sleep(1 ms)` to `thread::sleep(1 us)` (or `10 us`), need more test to check the impact and will update later.

**Comment by garyyu** [comment]
I change to `10us`, and add a line of log for test here:
```
pub fn read_exact(
    ...
		match conn.read(buf) {
			Ok(0) => break,
			Ok(n) => {
				let tmp = buf;
				buf = &mut tmp[n..];
				read += n;
				debug!(                        <<<< add a line of log here!
					LOGGER,
					"read_exact - read {} bytes, progress: {}/{}, yield count: {}", n, read, exact, count,
				);
			}

```

And then test with the `txhashset` downloading.

Sometimes it looks good, only sleep for tens or at most hundreds of macro seconds:
```
...
Aug 22 16:11:23.152 DEBG read_exact - read 2896 bytes, progress: 3376/8000, yield count: 1
Aug 22 16:11:23.153 DEBG read_exact - read 2896 bytes, progress: 6272/8000, yield count: 3
Aug 22 16:11:23.153 DEBG read_exact - read 1728 bytes, progress: 8000/8000, yield count: 4
Aug 22 16:11:23.153 DEBG read_exact - read 4064 bytes, progress: 4064/8000, yield count: 0
Aug 22 16:11:23.154 DEBG read_exact - read 1448 bytes, progress: 5512/8000, yield count: 1
Aug 22 16:11:23.154 DEBG read_exact - read 2488 bytes, progress: 8000/8000, yield count: 23
Aug 22 16:11:23.154 DEBG read_exact - read 4752 bytes, progress: 4752/8000, yield count: 0
Aug 22 16:11:23.154 DEBG read_exact - read 1448 bytes, progress: 6200/8000, yield count: 1
Aug 22 16:11:23.155 DEBG read_exact - read 1448 bytes, progress: 7648/8000, yield count: 5
Aug 22 16:11:23.155 DEBG read_exact - read 352 bytes, progress: 8000/8000, yield count: 6
Aug 22 16:11:23.155 DEBG read_exact - read 2544 bytes, progress: 2544/8000, yield count: 0
Aug 22 16:11:23.156 DEBG read_exact - read 1448 bytes, progress: 3992/8000, yield count: 1
Aug 22 16:11:23.156 DEBG read_exact - read 2896 bytes, progress: 6888/8000, yield count: 2
Aug 22 16:11:23.156 DEBG read_exact - read 1112 bytes, progress: 8000/8000, yield count: 3
Aug 22 16:11:23.157 DEBG read_exact - read 4680 bytes, progress: 4680/8000, yield count: 0
Aug 22 16:11:23.157 DEBG read_exact - read 1448 bytes, progress: 6128/8000, yield count: 1
Aug 22 16:11:23.158 DEBG read_exact - read 1872 bytes, progress: 8000/8000, yield count: 11
Aug 22 16:11:23.158 DEBG read_exact - read 5368 bytes, progress: 5368/8000, yield count: 0
Aug 22 16:11:23.159 DEBG read_exact - read 2632 bytes, progress: 8000/8000, yield count: 1
Aug 22 16:11:23.159 DEBG read_exact - read 3160 bytes, progress: 3160/8000, yield count: 0
Aug 22 16:11:23.159 DEBG read_exact - read 4840 bytes, progress: 8000/8000, yield count: 1
Aug 22 16:11:23.159 DEBG read_exact - read 952 bytes, progress: 952/8000, yield count: 0
Aug 22 16:11:23.160 DEBG read_exact - read 2896 bytes, progress: 3848/8000, yield count: 15
Aug 22 16:11:23.160 DEBG read_exact - read 2896 bytes, progress: 6744/8000, yield count: 18
Aug 22 16:11:23.160 DEBG read_exact - read 1256 bytes, progress: 8000/8000, yield count: 19
Aug 22 16:11:23.161 DEBG read_exact - read 1640 bytes, progress: 1640/8000, yield count: 0
Aug 22 16:11:23.161 DEBG read_exact - read 2896 bytes, progress: 4536/8000, yield count: 1
Aug 22 16:11:23.161 DEBG read_exact - read 2896 bytes, progress: 7432/8000, yield count: 2
Aug 22 16:11:23.161 DEBG read_exact - read 568 bytes, progress: 8000/8000, yield count: 4
Aug 22 16:11:23.162 DEBG read_exact - read 2328 bytes, progress: 2328/8000, yield count: 0
Aug 22 16:11:23.162 DEBG read_exact - read 2896 bytes, progress: 5224/8000, yield count: 1
Aug 22 16:11:23.162 DEBG read_exact - read 2776 bytes, progress: 8000/8000, yield count: 3
Aug 22 16:11:23.162 DEBG read_exact - read 120 bytes, progress: 120/8000, yield count: 0
Aug 22 16:11:23.163 DEBG read_exact - read 2896 bytes, progress: 3016/8000, yield count: 53
Aug 22 16:11:23.163 DEBG read_exact - read 4344 bytes, progress: 7360/8000, yield count: 54
Aug 22 16:11:23.163 DEBG read_exact - read 640 bytes, progress: 8000/8000, yield count: 55
...
```

and sometimes (in same downloading test) it actually sleep for tens of milliseconds:
```
Aug 22 16:11:23.338 DEBG read_exact - read 3608 bytes, progress: 8000/8000, yield count: 6946
Aug 22 16:11:23.338 DEBG read_exact - read 3632 bytes, progress: 3632/8000, yield count: 0
Aug 22 16:11:23.500 DEBG read_exact - read 1448 bytes, progress: 5080/8000, yield count: 6253
Aug 22 16:11:23.501 DEBG read_exact - read 2920 bytes, progress: 8000/8000, yield count: 6254
Aug 22 16:11:23.501 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.501 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.501 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.502 DEBG read_exact - read 6384 bytes, progress: 6384/8000, yield count: 0
Aug 22 16:11:23.504 DEBG read_exact - read 1616 bytes, progress: 8000/8000, yield count: 45
```

and sometimes (in same downloading test) it never sleep (that means our read is slower than network receiving).
```
Aug 22 16:11:23.505 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.505 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.505 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.506 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.506 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.506 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.507 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.507 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.508 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.508 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.510 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.511 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.511 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0
Aug 22 16:11:23.511 DEBG read_exact - read 8000 bytes, progress: 8000/8000, yield count: 0

```

So, this sleep time is quite depending on network condition.  Since it don't have any side effect to use smaller value for sleep, we can take `10us` as the final sleep parameter here.

Will give a PR for this change.

**Comment by garyyu** [comment]
> we need to switch to async/future-based IO

@hashmap  What do you mean?  Is `async I/O` a different thing from `non-blocking i/o (TcpStream.set_nonblocking)`?   sorry if it's a stupid question:)

**Comment by hashmap** [comment]
@garyyu to be fair I don't understand how we use `TcpStream.set_nonblocking` (I saw we set it). We have one connection per thread (or peer), even if our thread would block on connection OS scheduler should suspend it and give cpu time to another thread. 

The model which is more scalable is to have just one thread (to be even more scalable we can have as many thread as cpu cores, but it is built on top of one thread model) which handles many connections. This thread registers itself as a handler in `epoll` call (on Linux), so when a connection is ready to be used this thread get a notification and handles the event. In this model we have one thread for multiple connection and the thread is more or less busy all the time.

In our case we check if we would block and block itself by calling `sleep` because we can't switch to handling another connection in the same thread. But as I said I don't fully understand how it was done in Grin, take it with a grain of salt, I probably said a lot of stupid things.

In Rust non-blocking IO as I described was historically handled by MIO package, then Tokio was built on top, then Futures were introduced and made its way to Tokio, then async/await is coming to simplify it one more time.

**Comment by ignopeverell** [comment]
And I can tell you that none of these approaches really work... except perhaps mio if you're willing to deal with the complexity. I'm quite happy with the current design, we'll never need thousands of threads.

**Comment by hashmap** [comment]
Btw I rewrote some parts of p2p to use blocking IO (running read and write in separate threads) to see if linux kernel manages threads better then we do using `sleep()`, got the same time.

**Comment by garyyu** [comment]
close by #1453
