### ISSUE TITLE
Add `grin wallet backup` subcommand 

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#1405]
Backup of a grin wallet is currently a manual process that is opaque and error prone.

Introduce a `grin wallet backup` subcommand that automatically backs up a user's wallet in a format compatible for future `grin wallet restore` commands. 

Specification:
- It should be clear to the user what has been backed up, where, and how to later restore from this backup.
- The resulting backup file(s) should be timestamped, to support having multiple backups.
- Backup file(s) should be portable, and support being moved to different devices and restored from there.
- The backup functionality should be exposed to grin-web-wallet in order for inclusion in the GUI as well.  

Relevant [chat thread](https://gitter.im/grin_community/dev?at=5b7c3e31d8d36815e56d83d4).

**Comment by yeastplume** [comment]
I know it the process might look a bit opaque and probably needs to be a bit better documented, but not sure I'm wholly in agreement here.

If the user backs up the entire wallet, it's a copy of the `wallet.seed` + the `wallet_data` directory. However, unless the wallet is backed up after each and every transaction, there will always be a need to run `wallet restore` with the seed file to recover any outputs that may have been created after the backup. Therefore, unless the wallet is backed up on each and every transaction, it's pointless to back up the `wallet_data` directory.

So all a `grin wallet backup` command would do at the moment is copy the `wallet.seed` file somewhere else and rename it. Surely at the moment it's possible to just output something to the effect of `put a copy of this file somewhere safe` when running `grin wallet init`?

Of course we'll ultimately want a BIP39 mneumonic as well, and the key derivation will change somewhat, but I wouldn't expect the backup process (keep a file somewhere safe) to change much.

**Comment by ignopeverell** [comment]
So close? Add to usage documentations?

**Comment by yeastplume** [comment]
Think we're good with current command and docs
