### ISSUE TITLE
Add a maximum size to the stem transaction pool

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1416]
Currently the test as to whether the pool is full is made by `is_acceptable` which doesn't consider the stem pool size. So as long as the regular pool size is fine, a peer can feed as many stem transactions at it pleases. Doing so may be a little tricky because some of them will get fluffed, but done quickly enough it may be used to crash a given node due to high memory use. No point in risking that.

**Comment by aupiff** [comment]
The current implementation of `total_size` in `pool/src/transaction_pool.rs`:

```rust
/// Get the total size of the pool.
/// Note: we only consider the txpool here as stempool is under embargo.
pub fn total_size(&self) -> usize {
	self.txpool.size()
}
```

Based on the comments above the `total_size` function, I assume you want to add an additional configuration parameter `pub max_stempool_size: usize` to the `PoolConfig` struct.

As opposed to doing something like:

```rust
pub fn total_size(&self) -> usize {
	self.txpool.size() + self.stempool.size()
}
```

 What does the comment "stempool is under embargo" mean?
