### ISSUE TITLE
Define Wallet TX Exchange Standards

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1426]
From Gitter discussions, the consensus appears to be that Grin shouldn't attempt to enforce a particular transaction/slate exchange model, but should instead provide the base tools for all possibilities, and allow the community to implement/test varying models for different needs (e.g. https://github.com/vault713/grinbox/)

Some examples would be:
* The existing 1-1 exchange
* A model whereby the sender opens a listener and waits for a recipient to modify the internally-held slate
* A centralised model that avoids direct connection issues by having participants connect to a semi-trusted service

We want to encourage authors of such solutions to build them in such a way that they remain compatible with other solutions, and a good way to do this is to define a standardised slate exchange API. This would have functions such as (many of these already exist in some form, but need to be standardised):

* Post new slate
* Retrieve transaction slate
* Modify slate remotely / Update slate
* Verify slate contents
* Post transaction to node

This is probably just a simple JSON API exchange, but the main idea here as that the exchange API is published and versioned, similar to the Stratum protocol.

**Comment by ignopeverell** [comment]
Current state of affairs seems as standard as we'll ever get before mainnet?

**Comment by yeastplume** [comment]
agree
