### ISSUE TITLE
Wallet BIP-32 Compatibility

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1428]
At the moment, the wallet key derivation is a simple master/child keys setup, but it should be modified to conform to BIP-32, allowing for master node/child wallet key derivations (which should make the life of wallet authors and service providers much easier).

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by mcdallas** [comment]
I would like to give this a go, however BIP32 uses HMAC-SHA512 instead of blake2 as well as SHA256 and RIPEMD160 (also pbkdf2 if BIP39 support is to come later). This needs one or more crypto libraries as dependancies. What should be the approach to this?

**Comment by antiochp** [comment]
If we can I think we should stick with blake2 which does not require any special HMAC construction and keep as close as this allows to BIP32.

**Comment by hashmap** [comment]
However we may want to consider hw wallets support there.  Trezor SDK supports BIP-32 directly, Ledger Nano S SDK provides HMAC-SHA512, SHA256  and RIPEMD160 (perhaps BIP-32 on higher level) and doesn't support blake2. Of course we can bring additional libraries as part of the app, but size limits are pretty tough.

**Comment by yeastplume** [comment]
I was looking into getting dirty with crypto functions again, but it seems everyone's favourite cryptographer @apoelstra has already gone and done the bulk of the work for us here: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/bip32.rs

So in my head this work should entail:

* Cut and paste what's needed from the above code
* Modifying the above code to use use blake2 (or perhaps allow for many hash algos given @hashmap's very valid point above? Probably best to slot the hashing into a trait for now and perform tests with a few different hashing algos, ensuring the BIP32 test vectors match at all times). 
* Interfacing into grin's BIP32 extended key via an implementation of the Keychain trait
* Modifying Keychain trait in accordance with whatever findings come from trying to integrate the BIP32 key derivation
* Using trait in wallet by default (for new wallets) but also allowing existing wallets to use the existing key derivation (need to flag this somewhere). To keep annoyance to a minimum, wallets should use one derivation or the other, not both
* Wallet restore needs to support both types of derivation

**Comment by apoelstra** [comment]
BIP32 uses SHA-512 rather than SHA-256; it will need a separate hash function no matter what, at least a 64-byte version of blake. Also, since these computations only happen in wallets and never in consensus code, it may be worth just sticking with SHA-512 for the sake of compatibility with existing tooling.

**Comment by apoelstra** [comment]
Yeah, probably the simplest thing is to cram everything into the 31-and-a-bit bytes that we have... 8 bytes amount, 12 bytes for a 3-level BIP32 path, and 11 bytes of zeroes to act as a sentinel to detect non-owned outputs.

**Comment by yeastplume** [comment]
Right, so right now it's just encrypting the value into alpha, so that should become alpha|i1|i2|i3... so we need to add an optional "message" into api to append there. Do we need to store a couple of bits indicating whether the indices are hardened as well?

**Comment by yeastplume** [comment]
@apoelstra Would you mind quickly looking over this commit if you have any time?

https://github.com/mimblewimble/secp256k1-zkp/commit/e6f1191da78b031c5c7bd00527756b74adecf0e3

It's just embedding an optional 16 bytes of message into alpha alongside the value (to keep it clean) with 8 bytes of 'sentinel'. We should be able to use this to get our 12 bytes of BIP32 path + flags for hardened keys.

**Comment by apoelstra** [comment]
@yeastplume yep, it looks good after cursory review

**Comment by yeastplume** [comment]
excellent, thanks! let me know if you want it upstream at any point

**Comment by truongdinhluyen** [comment]
XIN CHÀO .
máy tính tôi không đủ điều kiện theo yêu cầu .nhưng máy điện thoại tôi đang dùng nó là phiên bản mới nhất đủ điều kiện hoạt động .các bạn giúp tôi tìm tài liệu tôi cần .
[](url) tôi cần tài liệu về( tóc ) thật cốt lõi

**Comment by ignopeverell** [comment]
Is this merged? Can we close this now?
