### ISSUE TITLE
investigate libp2p networking stack

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1437]
Rust impl is still a work in progress but this might be worth investigating as a base layer to our p2p networking stack.
It may be preferable to leverage work in this space without resorting to rolling our own implementation.

https://github.com/libp2p/specs
https://github.com/libp2p/rust-libp2p

Kademlia DHT in libp2p (nodejs, Rust potentially "coming soon...")
https://github.com/libp2p/js-libp2p-kad-dht

**Comment by hashmap** [comment]
I heard recently that Rust implementation was kinda released, at least Polkadot switched to it. It's mostly developed by Parity (as well as Polkadot). It's tokio-based, I think in Grin we switched to a simpler thread-based approach from tokio-based, but I can't comment on that. I like simplicity of the current implementation, but we can get some nice features for free.

**Comment by eupn** [comment]
Maidsafe's CRUST: https://github.com/maidsafe/crust
>Reliable p2p network connections in Rust with NAT traversal. One of the most needed libraries for any server-less, decentralised project.

**Comment by lehnberg** [comment]
Related: https://github.com/mimblewimble/grin/issues/1798
