### ISSUE TITLE
what happens when we compact the chain on an archival node?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1447]
We can curl the following to kick off a manual chain compaction against a node - 
```
curl 127.0.0.1:13413/v1/chain/compact
```

* What happens if we accidentally do this on an archival node?

* What happens if this was the _last_ archival node on the network?

We should probably prevent compaction from running if the node is in full archival mode.
I do not think we prevent this currently.

**Comment by ignopeverell** [comment]
Agree.
