### ISSUE TITLE
Some outputs without block_height and merkle_proof

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1462]
I'm confused by the following API output for http://127.0.0.1:13413/v1/blocks/76691:
```
"outputs": [
{
"output_type": "Transaction",
"commit": "09feb9b81f8dfb0a6c373b1378a1481b2fa494ba9b9476f64c5b77cda350dff44b",
"spent": true,
"proof": null,
"proof_hash": "66789c39d3cb4c1dcb5dba82cc0b05012d548d060f99e802fa5cd092b8a017b7",
"block_height": null,
"merkle_proof": null
},
{
"output_type": "Transaction",
"commit": "097cfb9610caefd03d239b35094717b1ae03f1cccd14aab4d74af26c719a3067fd",
"spent": false,
"proof": null,
"proof_hash": "cad6b0e185caa51a46af1605194029f6a81dbc47654ee3bf4b468627042f0c12",
"block_height": 76691,
"merkle_proof": null
},
{
"output_type": "Coinbase",
"commit": "08534f1f1d01829466e1cec68672bbb0d29169f8518d4272b65b4e79f6ccd43e77",
"spent": false,
"proof": null,
"proof_hash": "0895373476353a794c4d8b7cb3fd061628bc4690872e9c3471ffdcb841f14176",
"block_height": 76691,
"merkle_proof": "000000000002bc90000000000000000954bc5d2f6bf46e2e078a05f90a7be374db794f20152b0ab7..."
}
],
```

In which case we will not give `block_height` or/and  `merkle_proof`?  is it because the node is not a full node?

Block 76691 is not the only one, also http://127.0.0.1:13413/v1/blocks/76680, there could be more.

**Comment by garyyu** [comment]
Check the code and find this is the designed behavior, not a bug. Sorry for the noise.

- Only UTXO can have this `block_height` info
- Only `Coinbase` output type can have the `merkle_proof` info

```
impl OutputPrintable {
	pub fn from_output(
	...
		let spent = chain.is_unspent(&out_id).is_err();
		let block_height = match spent {
			true => None,
			false => Some(chain.get_header_for_output(&out_id).unwrap().height),
		};
		...

		if output
			.features
			.contains(core::transaction::OutputFeatures::COINBASE_OUTPUT) && !spent
			&& block_header.is_some()
		{
			merkle_proof = chain.get_merkle_proof(&out_id, &block_header.unwrap()).ok()
		};

```

**Comment by sesam** [comment]
@garyyu maybe a PR to add some documentation in the places where you didn't find it the on your first try? Also worth to check if `grin wallet list` behaves in the expected way.

**Comment by garyyu** [comment]
@sesam  Where would you like to put this 'documentation'?   Wiki?

**Comment by sesam** [comment]
The smallest step forward is 
https://github.com/mimblewimble/docs/wiki/API-documentation
and hope that someone will pick it up.

Longer term, we should probably autogenerate API docs from .rs code. That can be a new issue tagged #research and #helpwanted

The comment on block_height and merkle_proof could also be added already now into the code - maybe in the api endpoint handler functions.

Just my 0.02 testgrins.

**Comment by garyyu** [comment]
Thanks @sesam . Since the draft Wiki page has been created there, let's wait someone to pick it up:)

I close this issue since it's not needed anymore.
BTW, I tried `cargo doc grin_api`, but the doc generated is not very interested. Could need another PR to clean all those `rust doc` things.
