### ISSUE TITLE
Dual proof-of-work

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1476]
Implement block header and validation modifications to support 2 proof of work algos with a difficulty ratio as described here:

https://www.grin-forum.org/t/proof-of-work-update/713

The exact 2nd proof-of-work does not need to be known at this point, it could both be Cuckoo30+ as long as there's a way to differentiate them.

**Comment by ignopeverell** [comment]
Missed #1438, this is a dup, closing.

**Comment by Asad144** [comment]
am running Jira version 5.2.7 by the way.
