### ISSUE TITLE
Turtle speed API - /v1/blocks/{hash}

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1477]
A terrible slow API of:
```
http://127.0.0.1:13413/v1/blocks/{hash}
```

I spent **9 hours** to import the whole block data (from height 80,399) into a local database.  There must be a performance evil there to make this terrible slow.  will check it later.

```
Sep 04 22:29:02.284 DEBG txhashset: merkle_proof: output: Commitment(08fb8902d00265c6fc7911e600b5ac03e4b8ece9dd38b2eb1ecc773234d2a80f01), block: 1d2902f6
Sep 04 22:29:02.285 DEBG merkle_proof  186771, last_pos 186771
Sep 04 22:29:02.404 DEBG txhashset: merkle_proof: output: Commitment(0842ad33e2b85fea96e340a4fcee45c7e39547a754e4c8171213d767f0f525cb18), block: 07ce5af6
Sep 04 22:29:02.405 DEBG merkle_proof  186769, last_pos 186770

...
Sep 05 07:47:25.235 DEBG txhashset: merkle_proof: output: Commitment(099c1a79f74f33499dbb3e12e55803b3c76dea00cf9c0047d4877aa922b4fb3f28), block: 036974b8
Sep 05 07:47:26.583 DEBG merkle_proof  17, last_pos 18
Sep 05 07:47:26.635 DEBG txhashset: merkle_proof: output: Commitment(098bae744202a19d270ac99dfe497fd808b084efdf299c6d055c739147e002261a), block: 0386b7d5
Sep 05 07:47:27.994 DEBG merkle_proof  11, last_pos 11

```

looks like it's very fast at the beginning, and more and more slower when height decreasing.

**Comment by sesam** [comment]
Possibly we have throttling / rate limiting on the API endpoints. Sorry I don't
remember where / how / if it was implemented. Maybe see beginning of
handlers.rs or there around.

**Comment by quentinlesceller** [comment]
Agree also observed than when I updated my explorer. I don't remember of any kind of rate limiting in the API though.

**Comment by garyyu** [comment]
The 'evil' function could be `rewind()` function in txhashset.rs, will take this chance to dig into txhashset and pmmr, for better understanding of this code.

**Comment by garyyu** [comment]
#1528 should have great improvement for this issue. The original `9 hours` could be `1 hour` now already, but not tested.

What's I'm thinking now is that API `/v1/blocks/{hash}` or `/v1/blocks/{height}` is too heavy for blocks importing purpose, which could be a native database importing for example the https://github.com/mimblewimble/grin-explorer/blob/master/grinexplorer/blockchain/management/commands/import_from_tip.py

The most heavy part is the `merkle_proof` of the `output`, which will call that `rewind()` function optimized in #1528. But actually, if `merkel_proof` in external database is not used (for example, the current https://grinexplorer.net), it's purely wasting most of time here for exporting `merkle_proof`.

My idea is to write a new light API as the optional, to export the block without the `merkle_proof` for each `output`.

@quentinlesceller  @hendi  does this make sense?

**Comment by ignopeverell** [comment]
How about just a URL parameter to turn off the Merkle proof extraction? Something like `/v1/blocks/{hash}?merkle_proof=false`?

**Comment by invis87** [comment]
Is this issue still valid? I didn't find any Merkle tree related code in
`BlockHandler -> chain.get_block -> impl Readable for Block -> body.validate_read` functions

**Comment by antiochp** [comment]
@invis87 check the api code - its not part of a core block but I suspect it is part of a "printable" block.

**Comment by invis87** [comment]
hope I did it right :) https://github.com/mimblewimble/grin/pull/2843

**Comment by hashmap** [comment]
Thanks @invis87 for taking care of it
