### ISSUE TITLE
Provide JSON RPC endpoints for mining and stratum spec

### ISSUE THREAD

**Issue by sammy007** [mimblewimble/grin#1489]
Needed for pools to run stratum in a different process. Also, while it's not too late "standardise" stratum protocol so miner authors can use it as reference and don't invent anything else.

**Comment by quentinlesceller** [comment]
Hi @sammy007 could you clarify what do you mean by "JSON RPC endpoint for mining and stratum spec"?

**Comment by quentinlesceller** [comment]
Closing. Feel free to comment if you feel like it needs to be addressed and I'll reopen.

**Comment by sammy007** [comment]
I mean is there anything like `getblocktemplate` so I can get all required data for mining from a node and distribute it to many miners?
