### ISSUE TITLE
Duplicate commit for potential coinbase detected. Trying next derivation.

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1491]
I am seeing this "duplicate commit" error frequently.  In some cases it will loop a few times trying new derivations and then continue, but other times it gets stuck in this retry loop forever and the node needs to be restarted.

https://ipfs.io/ipfs/QmZDXDCJzd5cBmFifuKMQKZYdJ5gVsnH3Vd8HFj4zTCTHa
https://ipfs.io/ipfs/QmcByH7AT9RJVhNVjUqoHJMaEFtjmC4SoVeMhdtzXgoTQo

Its possible that this issue is contributing to high numbers of "late" shares:  
https://github.com/mimblewimble/grin/issues/1216

**Comment by yeastplume** [comment]
A lot of work has gone into this recently, particularly in the case of multiple wallets using the same seed. Please reopen if you see similar on mainnet
