### ISSUE TITLE
API for finding out node’s exact version

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1493]
Grin API should add an interface to find out node’s exact version.
For example: `Grin version 0.3.0 (git release_test_1-28-gda87f5f)`

And perhaps this version info can be added to peer's info also, on `/v1/peers`.

**Comment by quentinlesceller** [comment]
There is already the user agent. We can add the git commit in there while we are in testnet mode.

**Comment by ignopeverell** [comment]
Agreed for the local agent. For peers, I'd prefer not exposing this too obviously for privacy reasons.

**Comment by kargakis** [comment]
> For peers, I'd prefer not exposing this too obviously for privacy reasons.

More like security but +1

**Comment by garyyu** [comment]
Since all 3 comments are against putting git commit short id into the peer info, I close this one:)

**Comment by garyyu** [comment]
I reopen this case to share more info:)

Here is the official Ethereum geth shell command output (should by its API):
```
> admin.peers
[{
    caps: ["eth/62", "eth/63"],
    id: "043f2d14f37f4d32ac43acc9e258365ba6e0d00b1cff7e3e3450095849abdb7ad9b641ae436e4b957de8c47afbebe35edfce619280464cc13be43512334c5ec8",
    name: "Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9",
    network: {
      localAddress: "59.60.13.202:30303",
      remoteAddress: "142.167.179.92:62349"
    },
    protocols: {
      eth: {
        difficulty: 2.0247040968971282e+21,
        head: "0xee0da442e0b0816eb9f1a4fa3e6249aa3a61a1fd6268a32940533dddb25f6861",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    id: "167f7f74f0d7e123dc6b6f271aaf12fa7242f77a7c0d679e8ffc63509c20a2c2a46585b7247af9eb3e6bd6fefc27e88da9766a4b9ffcd701d76a29c0ddc07aaa",
    name: "Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2",
    network: {
      localAddress: "59.60.13.202:30303",
      remoteAddress: "13.56.155.145:43890"
    },
    protocols: {
      eth: {
        difficulty: 2.035047677185467e+21,
        head: "0xf7df8da493fb97a7e04f0055737d10dfc853b4d08574d3e4abb7e9feaa677e43",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    id: "1bfb7c3cff48b93f004be6ad71c9ce691cb4387e00b0894b5ce6dfbea53c86d05ed6630f12b24d52b4c18e022b22aeb22895e41388a0e3b21990a2c1539d2d69",
    name: "Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9",
    network: {
      localAddress: "59.60.13.202:30303",
      remoteAddress: "47.52.175.243:45354"
    },
    protocols: {
      eth: {
        difficulty: 2.034895619893508e+21,
        head: "0xdc0902e944adcf09724dc8d4f982e3a3a20b479e2f31c89d0526b283eecaf627",
        version: 63
      }
    }
}, {
...
```

Look at the **name**, for example:  "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9".

**Comment by garyyu** [comment]
Oh, perhaps misunderstanding here. What's the exact meaning of `local node to return`?

For example:
```
http://127.0.0.1:13413/v1/peers/all
```
Do you name this API as **local** or **remote**?

**Comment by ignopeverell** [comment]
I mean this as remote as you'll get information about other peers, which I think wouldn't be great for privacy. For example, if I wasn't too careful, I could very well dox myself by connecting with the git id for one of my PRs, that just I am working on, revealing my IP.

But I see no issue with an endpoint that would return the version of grin locally running given that normally it's not exposed (and you ought the be thinking hard about it if you do expose it).

**Comment by garyyu** [comment]
Understood, thanks for explain.

For the local node, this version info is already displayed on TUI, by click `Version Info` menu.

So, close by not taking into account for peers.
