### ISSUE TITLE
duplicate commitments or duplicate outputs?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1497]
We currently check for "duplicate outputs" via - 

https://github.com/mimblewimble/grin/blob/da87f5fef4a3830c7c0f3dc8c7ec9d3414e63f44/chain/src/txhashset.rs#L661-L675

* look in the `output_pos` index for the commitment
* if we find an entry, lookup the hash at that pos
* compare the hash with the hash of the output

But I think this is not an exhaustive check and I _think_ maybe there is an issue here.

Note that we use the __commitment__ to lookup the pos in the MMR.
But we compare the hash of the __output__.

It is possible to have two different _outputs_ (with different hashes), both with the same _commitment_, specifically one could be a coinbase output and one a regular output (differing only in features).

So if we generated a (60 grin) coinbase output and reused the commitment for a (again 60 grin) regular output then we would have two different outputs, but they would share a non-unique commitment, even though they would hash to different values.

@ignopeverell - my understanding was that we wanted to disallow duplicate commitments in the output MMR. 
Is this correct? 
Or is it that we want to disallow duplicate outputs (which we do currently)?

**Comment by ignopeverell** [comment]
Both. But disallowing duplicate commitments also disallows duplicate outputs, for the most part. So yes, looks like a bug.
