### ISSUE TITLE
Use Rustdoc to auto-generate API docs

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#1530]
Current API docs is manually documented in 
https://github.com/mimblewimble/docs/wiki/API-documentation. 

As per https://github.com/mimblewimble/grin/issues/1462#issuecomment-418072626:
> Longer term, we should probably autogenerate API docs from .rs code. That can be a new issue tagged #research and #helpwanted

This would be desired, but it's unclear to what extent this is possible and produces documentation of sufficient quality. Possibly `rustdoc` could be used. See https://doc.rust-lang.org/beta/rustdoc/what-is-rustdoc.html

## Status as of April 8 2019
- [ ] grin node
- [X] grin-wallet

**Comment by kargakis** [comment]
Dropping a link to the OpenAPI spec which is another option

https://swagger.io/specification/

**Comment by ignopeverell** [comment]
RustDoc would be for Rust APIs, I don't think it'd work very well for our JSON/HTTP API. Swagger is commonly used, the issue is I'm not aware of an easy way to generate it from Rust code annotations, so we'd be left maintaining it by hand as well.

**Comment by hashmap** [comment]
I don't see how it would be possible to automate, what we could automate is spec/imp parity check using smth like Dredd https://github.com/apiaryio/dredd to make

**Comment by kargakis** [comment]
This is now a thing for the [wallet](https://www.grin-forum.org/t/yeastplume-progress-update-thread-mar-19-to-sep-19/4303/12)

**Comment by lehnberg** [comment]
I believe this is now mostly fixed thanks to @yeastplume's recent efforts with the v2 api:
https://github.com/mimblewimble/grin-wallet/pull/24
https://github.com/mimblewimble/grin-wallet/pull/31
https://github.com/mimblewimble/grin-wallet/pull/33

**Comment by kargakis** [comment]
The node apis are still not doing this so it may be worth to keep it open.

**Comment by lehnberg** [comment]
Right. Good point @kargakis. I've updated the original description and comments and re-opened.

**Comment by yeastplume** [comment]
Believe this is handled for the node as well thanks to the node's V2 API courtesy of @quentinlesceller  https://docs.rs/grin_api/3.0.0/grin_api/trait.OwnerRpc.html and https://docs.rs/grin_api/3.0.0/grin_api/struct.Owner.html
