### ISSUE TITLE
block validation does *not* currently prevent double spends

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1554]
Discussion on gitter yesterday around "proving unspentness" got me thinking (again) about how we validate blocks.

The simplified example below illustrates what I think is a gap in how we do block validation currently.

__tl;dr__ 
* Full txhashset validation (during fast-sync) validates against the full UTXO set and proves we have no double-spends.
* Current block validation is done "in isolation" and only verifies the block is self-consistent. It does not prevent a previously spent output from being spent a second time.

--------

```
Block 1:
    Coinbase output: 17*G + 1*H
    Coinbase kernel: 17*G + 0*H

# We now have a 1 Grin output (the coinbase reward from block 1) to spend.

# Spend it in block 2 (ignore fees and coinbase maturity for simplicity) -

Block 2: 
    Coinbase output: 27*G + 1*H
    Coinbase kernel: 27*G + 0*H
    Tx1: (113*G + 1*H) - (17*G + 1*H) = 96*G + 0*H

Block 2 validation:
    Outputs - Inputs	
    = (113*G + 1*H) + (27*G + 1*H) - (17*G + 1*H)
    = 123*G + 1*H

    Kernels 		
    = (27*G + 0*H) + (96*G + 0*H)
    = 123*G + 0*H

    (Outputs - Inputs) - Kernels	
    = (123*G + 1*H) - (123*G + 0*H)
    =  0*G + 1*H
    => supply increases by 1 Grin (the block reward in this example).
    => block validates successfully

Full txhashset validation at block 2:
    sum(utxos)
    = (27*G + 1*H) + (113*G + 1*H)
    = 140*G + 2*H

    sum(kernels)
    = (17*G + 0*H) + (123*G + 0*H)
    = 140*G + 0*H

    sum(utxos) - sum(kernels)
    = (140*G + 2*H) - (140*G + 0*H)
    = 0*G + 2*H
    => Which equals our supply (2 Grin for 2 blocks) so full txhashet validates successfully


# Now double-spend that same output (17*G + 1*H) in block 3 -

Block 3:
    Coinbase output: 37*G + 1*H 
    Coinbase kernel: 37*G + 0*H
    Tx2: (50*G + 1*H) - (17*G + 1*H) = 33*G + 0*H

Block 3 validation:
    Outputs - Inputs	
    = (50*G + 1*H) + (37*G + 1*H) - (17*G + 1*H)
    = 70*G + 1*H

    Kernels			
    = (37*G + 0*H) + (33*G + 0*H)
    = 70*G + 0*H

    (Outputs - Inputs) - Kernels	
    = (70*G + 1*H) - (70*G + 0*H)
    = 0*G + 1*H
    => supply increases by 1 Grin
    => block validates successfully 

# We just double-spent the output (17*G + 1*H).
# Both blocks validated successfully (in isolation).
# Nowhere in our block validation do we check against the full UTXO sum.

Compare with full txhashset validation at block 2:
    sum(utxos)
    = (27*G + 1*H) + (37*G + 1*H) + (123*G + 1*H) + (50*G + 1*H)
    = 237*G + 4*H

    sum(kernels)
    = (17*G + 0*H) + (123*G + 0*H) + (70*G + 0*H)
    = 210*G + 0*H

    sum(utxos) - sum(kernels)
    = (237*G + 4*H) - (210*G + 0*H)
    = 27*G + 4*H
    => this does *not* equal the total supply (3 grin) so full validation fails
```

We currently rely on the remove/prune behaviour of our output MMR to identify and prevent double-spends.
We can enhance our block validation to validate against the full UTXO sum and make this significantly more robust.
We would need the UTXO sum at each block.

A "long time ago" we experimented with adding `total_kernel_sum` and `total_utxo_sum` per block to the db/index.
Related - https://github.com/mimblewimble/grin/pull/1019
Related - https://github.com/mimblewimble/grin/issues/1021
This issue was from way back in May (poorly) demonstrating the same thing.

We added the `total_kernel_sum` to the header in https://github.com/mimblewimble/grin/pull/1163.

But without a `total_utxo_sum` (maintained somewhere) we cannot efficiently do a "full validation" at the block level (i.e. validate the block against the full utxo sum), which is what I believe we need to be doing.

I think we understand this whole thing better now...

**Comment by antiochp** [comment]
@ignopeverell

**Comment by antiochp** [comment]
If we can rework block validation to use the `total_utxo_sum` of the previous block (maintained in the db?) then we can rely on Grin/MW to identify and prevent double spends (and spends of non-existent outputs) without needing the UTXO set from the output MMR.
We would not need to rely on remove/prune behaviour of the MMR to identify double-spends.

This would also allow us to simplify further the txpool validation process.
We would not need to apply "raw_txs" to the txhashset.
We would just need to sum the right stuff up to do a "full validation" against the kernels and the utxo sums at that point in time (based on on current block + txs in the pool).

**Comment by antiochp** [comment]
For reference: This is where we originally added `BlockSums` to the db (which we later removed) - https://github.com/mimblewimble/grin/pull/1043

**Comment by antiochp** [comment]
Fixed here - #1559.

**Comment by ignopeverell** [comment]
There are 2 ways to do a fully correct validation:

1. Validate the whole state, for example in fast sync.
2. Incremental validation, for example anytime a new block, which must:
    1. Have validated the prior state and extracted related sums.
    2. Validate the increment's sums with the prior ones.

So yes, this is good. Especially the part where you get to remove a whole bunch of code :smiley:

**Comment by antiochp** [comment]
The part I'm actually most interested in is the ability now to verify kernel sums on a (BlockSums, Transaction) tuple.
This will let us verify double-spends etc. in the txpool (and the stempool).
We'll have a really simple way of verifying a transaction can be added to existing chain state.

**Comment by antiochp** [comment]
Umm... I think there is a flaw in my thinking here...

Example with a single block. 
Note we spend a non-existent 1,000 grin output here.

```
Block 1:
    Coinbase output: 17*G + 1*H
    Coinbase kernel: 17*G + 0*H
    Tx1: (113*G + 1000*H) - (18*G + 1000*H) = 95*G + 0*H

Block 1 validation:
    Outputs - Inputs
    = (113*G + 1000*H) + (17*G + 1*H) - (18*G + 1000*H)
    = 112G + 1*H

    Kernels 
    = (95*G + 0*H) + (17*G + 0*H)
	= 112G + 0*H

    (Outputs - Inputs) - Kernels
    = (112G + 1*H) - (112G + 0*H)
    = 0*G + 1*H
    => *** But we spent a non-existent 1,000 grin and created a new 1,000 grin output... ***

```

Everything still sums correctly.
We "spend" 1,000 grin and create an offsetting 1,000 grin output.
It's just that the original 1,000 grin never existed in the first place.

It never existed in the UTXO set but we're not checking this here.
We're not looking at the output MMR to ensure that all inputs are spending pre-existing (unspent) outputs.

In this example we do have a 1,000 grin output, it just appears _later_ than the 1,000 grin input.
So it all sums correctly.

Am I missing something here?

@ignopeverell

**Comment by tromp** [comment]
> Am I missing something here?

There's more to validation than correct sums. We also check inputs being in the UTXO,
and in the case of fast sync, that there is a valid UTXO matching the TXO MMR commitment.
I don't see your examples accounting for this.

**Comment by ignopeverell** [comment]
And just sticking to sums, I also don't see how block 1 once added to the UTXO set could sum against total supply.

**Comment by antiochp** [comment]
Closing this - the sums are not sufficient, we _always_ need the UTXO set to fully validate.

We achieve this now during block validation with this (as a quick early check against the UTXO set). 

```
fn validate_utxo(block: &Block, ext: &txhashset::Extension) -> Result<(), Error> {
	let utxo = ext.utxo_view();
	utxo.validate_block(block)?;
	Ok(())
}
```

And then "belt and suspenders" style (we were always doing this and continue to do this) we verify we can prune the output MMR successfully during `apply_input()` called from `apply_output()`.

For transaction validation when adding to the txpool we can do something similar against the _current_ UTXO set. For performance reasons we can do this against the `utxo_view` (which only cares about the output MMR) and it is _readonly_ via rust type safety and borrow checker.
We do not need to start a full writeable txhashset extension here to validate the tx.

```
pub fn validate_tx(&self, tx: &Transaction) -> Result<(), Error> {
	let txhashset = self.txhashset.read().unwrap();
	txhashset::utxo_view(&txhashset, |utxo| {
		utxo.validate_tx(tx)?;
		Ok(())
	})
}
```

**Comment by ignopeverell** [comment]
All sounds great :+1:
