### ISSUE TITLE
'grin server start' stale run

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1561]
I can't get any output from grin when I start it with `grin server start`. It doesn't write anything in the log apart from the following
```
Sep 19 19:51:19.684 INFO Using configuration file at /home/mkargaki/.grin/grin-server.toml
Sep 19 19:51:19.684 INFO This is Grin version 0.3.0 (git release_test_1-59-ga0deb18), built for x86_64-unknown-linux-gnu by rustc 1.28.0.
Sep 19 19:51:19.684 DEBG Built with profile "release", features "" on Mon, 17 Sep 2018 16:34:29 GMT.
```
Seeing the same thing on two separate machines w/ different architecture.

**Comment by quentinlesceller** [comment]
Hey @kargakis looks like a duplicate of https://github.com/mimblewimble/grin/issues/1342. Daemonize does not really work right now. I recommend creating a systemd service while we fixed that.

**Comment by kargakis** [comment]
Thanks for the reply @quentinlesceller, closing as a duplicate
