### ISSUE TITLE
Improve Github Issue Labels

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#1564]
_**Edit:** Updated original description to reflect thread discussion._
_**Edit Oct 10:** Adding colours and cleaning description up._
_**Edit Oct 13:** Color tweak after seeing them in action._ 

---

Update our current label system. 

## Change summary from current
* ADD `task` label
* ADD `fixed` label
* ADD `needs more info` label
* Update colours of labels

## Proposed Labels:

Label name | Color
-- | --
enhancement | `#9eebcf`
task | `#2F4F4F `
bug | `#e7040f`
must-have | `#ff8c00 `
fixed | `#006b75 `
cannot reproduce |`#e6e6e6 `
invalid | `#e6e6e6 `
duplicate | `#e6e6e6 `
wontfix | `#e6e6e6 `
good first issue | `#96ccff`
help wanted | `#00449e`
consensus breaking | `#ffde37`
needs more info |`#fcc4c8 `
question | `#d5008f`
research | `#5e2ca5`

**Comment by garyyu** [comment]
`Statuses` and `Resolutions`, also the `Priorities` are the common concepts of **change tracking system**.  Only `Types` (or name `label` in Github) is feasible here.

And perhaps the `Priorities` can be considered to be used (also as labels but with `P0`, `P1`, `P2`, 3 level enough) here,  and IMO, it's just an option, we don't have hundreds or thousands of remaining issues, so no need to make it too complex.

**Comment by garyyu** [comment]
But indeed, current existing labels are not enough.  Why?   because I can't find a suitable one to label this one 😸  ha ha

**Comment by ignopeverell** [comment]
Going to to try to slash it quite a bit :-) Gotta be simple. So:

* I don't think we need all these P0...PX. For an open source project, knowing whether it'll block a release or not is enough (current "must-have").
* Status is overkill too I think. The amount of time an issue is worked on is usually negligible compared to how long it sits there. If you want to see if it's worked on, open it check if a PR references it.
* Not sure the distinction between "new feature" and "improvement" is useful.

By the way, there are quite a few resources out there that'll give you a visually pleasant palette of high contrast colors for free. For example (unfortunately full of ads nowadays): https://www.colourlovers.com/palettes

**Comment by lehnberg** [comment]
I would have been disappointed if you hadn't! :)

* `must-have` only it is then. Or perhaps `blocker` is more descriptive?
* Re status, you raise good points. Less is more, at least until there's a need for sth different. 
* One question I had as I was working these through was if there ever was a need to label efforts as 'abandoned'? How is this usually handled today? Do you just close issues when the "star of the show" goes missing?
* Re `new feature` versus `improvement`, I think the main use for them are to be able to distinguish between them in data later on, and to make it more clear whether a component / functionality is being introduced from scratch, or whether it's a matter of iterating on something that's already there. The latter tends to be a less complex exercise (at times). I don't feel particularly strong about the need of keeping it, but I do think it makes sense. If you rather go with a single `improvement` or `enhancement` just say so.

With a shorter list, we can simplify labels names, and without statuses `needs more info` just becomes a description instead. It's basically for anything that's not well defined enough yet. The refined list is then:

## Proposed Labels:

#### Types
new feature
improvement
task
bug

#### Priorities
must-have

#### Resolutions
fixed
cannot reproduce
wontfix
invalid
duplicate

#### Descriptions
good first issue
help wanted
consensus breaking
needs more info

-----
Better?

**Comment by lehnberg** [comment]
Haha BIP32 support is `new feature` as it's new functionality introduced to the Wallet component. Conversely Gary Yu fast sync optimisation is an example of an `improvement` of the node. ^^

But FIIINE. What is your thinking here? We drop `new feature`? Keep `improvement`? As you already use `enhancement` today I suppose we just keep this instead? And then any issue that requires development and is not a bug would be an `enhancement` by definition. Does that sound right?

**Comment by garyyu** [comment]
I second the point of `be simple`.

I propose to focus on existing labels and:
- ONLY give optimization on it
- Plus the **problem** fixing part for example those issues without any label and no existing suitable label for them

@lehnberg  Yes. `enhancement` = `new feature` + `improvement`.

And we can have 2nd layer detail of `enhancement` type by git commit title, i.e.  https://www.grin-forum.org/t/github-pr-pull-request-title-prefix-rule-optional/842, welcome to discuss there.

- feat:     A new feature
- fix:      A bug fix
- docs:     Documentation only changes
- style:    Formatting, missing semi-colons, white-space, etc
- refactor: A code change that neither fixes a bug nor adds a feature
- perf:     A code change that improves performance
- test:     Adding missing tests
- chore:    Maintain. Changes to the build process or auxiliary tools/libraries/documentation

**Comment by lehnberg** [comment]
@garyyu 
1. Cool, I've updated so `enhancement` now replaces `improvement`. ✌️
1. Can you motivate the rationale for the `perf` label, which is what I assume you refer to with "optimisation"? Why is it needed? And aren't all enhancements performance optimisations? :)
1. There are currently 12 labels in use. Current proposal has them becoming 13, but some with different titles. As a quantity, do you feel +1 would be acceptable?
1. Even if labels are useful across both pull request and issues, they seem most suitable for triaging. The prefixes have their usefulness as well, but seem to be focused primarily on describing pull requests. I am definitely open to using prefixes as well, but I still would like to see a rigid, well-defined, and well color-coded label system.

More broader speaking, I also have questions about the existing **question** label (see what I did there?): To me, something that's not dev-related and not a bug, would be a `task`. A task might `need more info` and might also have `help wanted`. But I'm not sure what a `question` is here in this context and why it's helpful. Usually if you ask a question, there's a reason for why you are asking.  To put it in other words, it's great to have a discussion and a debate. But if the discussion is not centred around a development issue or a bug, wouldn't it just be a task? And if not, should it really be an issue in the first place?

Similarly, I also don't understand the rationale for the existing **research** label. What's research? It needs more research? It's a research exercise? Again, if it's a (future) development issue, it would be an `enhancement`, and if it's not fully defined yet it would `need more info`, possibly again with `help wanted` as optional. If it's not a development issue, then it would be a `task` no? For example "Research how other GitHub projects do issue labelling". The task would be completed when the effort is done. 

---

I am sorry if I come off as obtuse or bike-shedding here, it's just that I am quite passionate about  structures, and in my experience good and intuitive structures help, whilst messy structures... add friction. I am not a repo contributor, so I fully appreciate that my voice carries relatively little weight in this context. I mean well, and am totally cool with whatever solution is accepted in the end.

**Comment by garyyu** [comment]
>  Can you motivate the rationale for the perf label, which is what I assume you refer to with "optimisation"? Why is it needed? And aren't all enhancements performance optimisations? :)

Indeed 👍 an redundant one by myself! since `performance` issue or enhancement is either `bug` or `enhancement`.  I will remove this one.

> I am not a repo contributor, so I fully appreciate that my voice carries relatively little weight in this context. 

You're definitely a user of Github issues, and we're discussing the issues label.  So `my voice carries 
 relatively little weight in this context` is not applied here 😄  I appreciate your discussions here 👍

**Comment by garyyu** [comment]
And one more point:

Why the issue label matter?
- Because the automatic generated change log (for binary release) is heavily relying on issue label.

Please see more detail on:  https://github.com/github-changelog-generator/github-changelog-generator

**Comment by lehnberg** [comment]
Ticket is updated; added color suggestions. Feedback welcome.

**Comment by ignopeverell** [comment]
I'm all good with the colors. Why `fixed`? Aren't fixed issues closed?

**Comment by garyyu** [comment]
Thanks @lehnberg continue this task! My 2 cents:
- `fixed` not needed. When an issue is fixed, its state will change to close by system automatically.
- generally color scheme is good, with some change need:
  1. red color is most critical color, we don't want see all red when opening our git issue page 😄 so, `bug` should not be red, `question` and `must have` also.
  2. `consensus breaking` should be one of most serious one, so red for it is reasonable.
  3. color also need a test to know its real effect, so once we're near to the agreed nice scheme, we can apply them and feel them in the system, and give a 2nd round adjustment (could be minor change then) to get a final satisfied color scheme.

**Comment by lehnberg** [comment]
@ignopeverell @garyyu `fixed` is a _reason_ for why you are closing an issue. You can close a ticket for many reasons, for example `wontfix`, `duplicate` or `cannot reproduce`. A `fixed` reason makes sense as it makes it easy to filter out non-fixed issues from your stats and track the fixed over time.

@garyyu `bug` is red in GitHub defaults and most other issue tracking systems. `consensus breaking` is important to note, but it's not 'serious' in the sense that it's not urgent (like `must-have`) and it's not a defect (like `bug`). So a clear warning colour here makes sense. And I thought yellow was doing the trick well: ⚠️

`question` is actually more like dark pink than red and I _think_ would not be conflicted with red once it's on a label.

Agree we need to test these in real life, we'll probably want to tweak colors once we see them in the wild and start working using the labels.

**Comment by quentinlesceller** [comment]
I'm all good with this choice. I like that `bug` is in red since normally it's something that need our attention asap.

**Comment by lehnberg** [comment]
Shall we give this a shot? @ignopeverell is possible for me to get "labelling" rights so that I can update the labels myself, and also help with triaging?

**Comment by ignopeverell** [comment]
Added you as a collaborator, give it a shot.

**Comment by lehnberg** [comment]
Thanks, this has now been implemented with some coloring tweaks (description updated). Any issues just let me know here and we can improve.
