### ISSUE TITLE
Evaluate bitcoin_hashes to be the replacement of rust-crypto crate

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1589]
To avoid us forget this topic, I create this issue to track it.

Recap the discussion of https://github.com/mimblewimble/grin/pull/1573 :

---
> In PR#1573, replace the unmaintained rust-crypto crates with https://github.com/RustCrypto/hashes, https://github.com/RustCrypto/MACs and https://github.com/RustCrypto/traits.
---

> quentinlesceller commented:
> It's just that rust-crypto relies on old dependencies and is unmaintained since two years.
Whereas https://crates.io/crates/sha2 is two years old (so not that new) and relies on modern dependencies.

> mcdallas commented:
> I think the idea is to migrate to https://github.com/rust-bitcoin/bitcoin_hashes once it's ready (according to https://github.com/mimblewimble/grin/pull/1454#issuecomment-418294933)
---

> quentinlesceller commented:
> I don't see the issue with using RustCrypto/Hashes/HMac instead of rust-crypto. And I don't see why bitcoin_hashes would be better a better replacement (except maybe less dependencies).
---

> sesam commented:
> bitcoin_hashes is worked on by @apoelstra
> ... I suspect bitcoin_hashes is the nicest option longer term, ...
---

> apoelstra commented:
>  just need @TheBlueMatt (nudge, nudge) to merge the open PRs on bitcoin_hashes, then I think it will be done and in maintenance mode.
---

> ignopeverell commented:
> @garyyu that's a lot of risky code to maintain (rust-crypto) when we only use a fraction of it. This PR (#1573) is a net improvement, possibly with more improvements to come.
---

Just want to evaluate using `bitcoin_hashes`,  once https://github.com/rust-bitcoin/bitcoin_hashes finish the merging of the open PRs and enter the maintenance mode.

**Comment by yeastplume** [comment]
I think this is very out-of-date by now, closing
