### ISSUE TITLE
Unexpected behavior/state when sending transactions to self

### ISSUE THREAD

**Issue by gavinmcdermott** [mimblewimble/grin#1605]
In order to prevent locking up more outputs than necessary (and while network tx fees are low), we want to send a zero-conf. transaction to ourselves for the amount+fee of a particular transaction. But I am reproducibly running into the same issue. 

### Workflow
The workflow to produce what I am talking about is shown below:
1. `POST` to the the `owner / issue_send_tx` route with the `method` attribute set to `file`,
2. `POST` the result from step 1 to the `foreign / receive_tx` route,
3. `POST` to the `finalize_tx` route with the signed transaction from step 2.
In the process above, @quentinlesceller discovered that the `finalize_tx` http endpoint does not actually broadcast the transaction. But, since steps 1 and 2 worked, then a `finalize` call from the cli should work to broadcast the transaction. 

### Resulting Tx State
The transactions resulting from steps 1 and 2 above, wind up in an unexpected state. The tx data is below:
```sh
 12  Sent Tx                  fe61c548-b413-407e-8116-a6e038ddd123  2018-09-28 00:14:43  false       None                 1            1             496.992          500.0           0.008  -3.008          Exists
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 13  Received Tx              fe61c548-b413-407e-8116-a6e038ddd123  2018-09-28 00:14:43  false       None                 0            1             3.0              0.0             None   3.0             None
```
- tx 12 is the self-send 
- tx 13 is the incoming tx (received from tx 12)

Since tx 12 was not finalized, I manually tried to `finalize` and `repost`. But an unexpected error results (shown below):
```sh
╰─ grin wallet finalize -i 12 
Sep 28 10:33:26.219 WARN Using wallet configuration file at /Users/*/.grin/grin-wallet.toml

╰─ grin wallet finalize -i 13
Sep 28 10:33:49.512 WARN Using wallet configuration file at /Users/*/.grin/grin-wallet.toml

╰─ grin wallet repost -i 13
Sep 28 10:34:07.111 WARN Using wallet configuration file at /Users/*/.grin/grin-wallet.toml
Sep 28 10:34:07.201 ERRO api: repost_tx: completed transaction at 13 does not exist.
Sep 28 10:34:07.201 ERRO Transaction reposting failed: Transaction building not completed: 13

╰─ grin wallet repost -i 12
Sep 28 16:01:40.186 WARN Using wallet configuration file at /Users/*/.grin/grin-wallet.toml
Sep 28 16:01:40.247 ERRO api: repost_tx: failed with error: Client Callback Error: Posting transaction to node
Sep 28 16:01:40.247 ERRO Transaction reposting failed: Client Callback Error: Posting transaction to node
```
To me the transactions appear to be in an odd state. If they are not, I'd like to clear up my understanding. 

### Questions:
- Is my understanding correct that since I successfully `POST`ed to `owner / issue_send_tx` and to `foreign / receive_tx` that I should only need to POST to `finalize_tx` with the blob signed by both?
- Is my understanding correct that since the `http` call is currently broken, I should only need to call `grin wallet finalize -i 12` to successfully broadcast tx 12. Then both transactions (12 and 13) should be confirmed at some point (which is not currently happening).

If my understanding is off and this is the expected behavior, I could use some direction on what steps I'm missing. But if this behavior is unexpected, I'd love to know what's going on. 

Thanks in advance.

**Comment by quentinlesceller** [comment]
Not sure if we answered your questions so I'm just going to answer them here:

>Is my understanding correct that since I successfully POSTed to owner / issue_send_tx and to foreign / receive_tx that I should only need to POST to finalize_tx with the blob signed by both?

Yes.

> Is my understanding correct that since the http call is currently broken, I should only need to call grin wallet finalize -i 12 to successfully broadcast tx 12. Then both transactions (12 and 13) should be confirmed at some point (which is not currently happening).

Since https://github.com/mimblewimble/grin/pull/1795, you can now broadcast the transaction with `post_tx`

So the flow is the following:
- `issue_send_tx`
- `receive_tx`
- `finalize_tx`
- `post_tx`

Finally this issue is fixed by https://github.com/mimblewimble/grin/pull/1939.
