### ISSUE TITLE
Autoreload auth secret during runtime

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1610]
It would be nice to autoreload the auth secret on the fly w/o having to restart grin.

Proposed solution: run a separate thread to read .api_secret every X seconds and update it in memory.

**Comment by hashmap** [comment]
I'd say it may apply to any config param, what makes the secret special? But to be fair I see it as a nice to have feature.
I'm not sure about auto-reloading per se (btw modern Linux and OSX supports filesystem events). Usually config update is more explicit and  it's done by handling `SIGHUP` signal for daemons or just exposing it in UI.

Unrelated - I think we need to have a secret file for grin config, api key is just one param, there will be more (eg tls pass for p12 keys)

**Comment by kargakis** [comment]
> I'd say it may apply to any config param, what makes the secret special? But to be fair I see it as a nice to have feature.

Maybe? I wouldn't go that far here, the secret is special because it's something you want to be able to rotate effectively as opposed to any other configurable.

> I'm not sure about auto-reloading per se (btw modern Linux and OSX supports filesystem events). 

This is not portable across OSs. Also, a simple loop is much simpler to understand and maintain.

> Usually config update is more explicit and it's done by handling `SIGHUP` signal for daemons or just exposing it in UI.

True about SIGHUP but it is also not portable and its meaning slightly differs between applications.

> Unrelated - I think we need to have a secret file for grin config, api key is just one param, there will be more (eg tls pass for p12 keys)

Hrm, need to think the implications for this through but my gut feeling is keep each file separate and maybe standardize on a secrets directory.

**Comment by kargakis** [comment]
> Hrm, need to think the implications for this through but my gut feeling is keep each file separate and maybe standardize on a secrets directory.

Rotation of these is going to be simpler if they are separate files (delete old, generate new). Honestly, I don't think a separate directory is needed but that's just me.

**Comment by quentinlesceller** [comment]
@hashmap Adding a server-secret.toml/wallet-secret.toml would probably make senses.

**Comment by quentinlesceller** [comment]
This feels like a nice to have feature. Going to close it since we have a lot of them and I'm not a big fan of using the Github tracker for 2 year old feature requests. Feel free to open another issue if you feel this is really needed so this might be addressed by someone.
