### ISSUE TITLE
[GIP]: Transactions of Aggregated Range Proof 

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1613]
**Note**: here's a draft version, to be reviewed and discussed.

# Aggregated Range Proof
There're two similar but separate concepts: **aggregation** is when a prover combines multiple range proofs into one, while **batching** is when a verifier checks multiple separate proofs at once.

A demo of aggregation can be found [here](https://github.com/garyyu/rust-secp256k1-zkp/wiki/Range-Proof#4-range-proof-aggregation).

Just remember 1 simple fact and ignore the complex detail things:
- when aggregate `2^n` commitments, the aggregated range proof result increase **64*n** bytes.
- that is, for `2^n` commitments, the aggregated range proof size is **675 + 64 * n** bytes
- for example: 
  - 2 commits = 675+1*64 = 739 bytes
  - 4 commits = 675+2*64 = 803 bytes
  - 8 commits = 675+3*64 = 867 bytes

# Use Cases
## Mining Pools Rewards Payment
Pool need regularly distribute the rewards to the miners. A typical pool contains about from thousands to hundreds of thousands miners.

 Let's give an example here, say 10,000 miners. There're different ways of pool rewards payment, to give a simple example here, let's say the payment is weekly. So, in this simple example, a typical pool need 10k payments / Week, that is, 520k payments / Year. For same simple reason, we suppose each transaction use 1 input and 10k+1 outputs (ignore the chain limitation for simple), so the transaction fee is `40` Grin / Tx. So the estimated transaction fee for this pool is about 2080 Grin / Year.

Now, let's switch to a view of chain loads for above example.

A typical transaction with 1 input and 2 outputs is about 1.6k bytes in current implementation, the main part is the bullet proof on each output. A huge transaction with 10k outputs will need about 6.8M bytes data. 

For a transaction with 10k output payments (to 10k miners), say we aggregate them into 10 range proofs, then the final transactions data can be suppressed into about 13k bytes (i.e. (674 + 64 * 10) * 10). Since the aggregated data save a lot of chain loads (13k bytes vs 6.8M bytes), this huge transaction could cost only 1%, i.e. `0.4` Grin / Tx. So the estimated transaction fee for this pool is about 20.8 Grin / Year compared to 2080 Grin / Year without aggregation.

## Monthly / Weekly Salary Payment

For company or organization with big numbers of employees, the monthly or weekly salary payment is quite similar to above mining pool use case.

Actually, it's feasible for all similar 1:N payment use cases, to save 99% transaction fee (or in another words, much more compact data in the chain).

## Other Use Cases
Lottery prizes claim,  etc.  (TODO: add more here )

# TODO Dev Works
1. Problem fixing in `rust-secp256k1-zkp` for aggregated bullet proof.
2. Transaction fee weight calculation algorithm. Currently it's just taking into account the inputs and outputs numbers:  transaction weight = `MAX(-1 * input_size + 4 * output_size + 1, 1)`.
3. Multiple outputs share one range proof.
4. Mixed batch verification for single range proof and aggregated range proof.

# Contraints
1. No rewind feature for aggregated range proof, just like the range proof for multi-party commitment.

**Comment by ignopeverell** [comment]
While it would be great to leverage, aggregate range proofs for multiple outputs aren't practical for Grin because outputs will be pruned when spent and we can't expect them to be spent at the same time. But I do think your 1st and 2nd point make sense.

I also think their may be other parts of the code where we expect a fixed size for bulletproofs, may be worth tracking these down.

**Comment by antiochp** [comment]
Cross-posting here from gitter - 

> the core issue with "aggregated rangeproofs" is the effect it has on the transaction graph. We save bandwidth and storage space but at the cost of permanently linking the associated outputs together
if out1, out2, out3 all share a rangeproof then every node on the network knows a single actor was responsible for generating that rangeproof and owns the private keys for all the associated outputs

> I'm not sure there is a way to avoid the linkage though - every node needs to know which rangeproof is associated with which output commitment (otherwise there's no way to prove the commitment value is greater than zero) - and if multiple commitments are linked to one rangeproof then they are all linked by association

**Comment by garyyu** [comment]
Close not taken into account.
