### ISSUE TITLE
Ratelimit requests to the API

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1614]
Currently requests to the REST API are not ratelimited so it's easy to dos a node. This may also be true for the p2p connection but I haven't tested that.

**Comment by quentinlesceller** [comment]
With current code it should be relatively easy to add such middleware.

**Comment by ignopeverell** [comment]
I'm not sure rate limiting makes sense in Grin. By default the API is only started on loopback. If you choose to expose it, you need to be aware of the risks. There are multiple valid ways to add rate limiting as well, like a proxy or iptables.

**Comment by kargakis** [comment]
> I'm not sure rate limiting makes sense in Grin. By default the API is only started on loopback. If you choose to expose it, you need to be aware of the risks. There are multiple valid ways to add rate limiting as well, like a proxy or iptables.

From a look I had in testnet back when I reported https://github.com/mimblewimble/grin/issues/1290, a bunch of nodes were serving their API out in the clear, not fronted by any kind of proxy so I am not sure you can expect all deployments to follow best practices.

**Comment by antiochp** [comment]
If this can be isolated to some kind of middleware cleanly without it hooking into the p2p layer too deeply then it might be worth considering.

**Comment by quentinlesceller** [comment]
I kinda agree with @ignopeverell on that one. We want to have a minimal implementation. 
By default the Grin Block API is not supposed to served the whole internet.
However, the foreign Wallet API is exposed, thus vulnerable to dos ?

**Comment by kargakis** [comment]
It's good to stay minimal, but not at the expense of security.

**Comment by kargakis** [comment]
Also the implementation for this should be fairly straightforward or
minimal if you wish. A middleware handler that gets to run on every request
and the actual implementation of the logic that backs the handler. Is it
possible to decide on the order that the handlers get executed?

**Comment by quentinlesceller** [comment]
Yes it's possible to decide which handler get executed first.

**Comment by ignopeverell** [comment]
Let me count the complications:

* What limits? Per second? Minute? Hour?
* Limit on every endpoint or global? Per API?
* What numbers we pick? Optimize for a low-load environment? A laptop?
* How do we configure limits when they're too low? Global configuration? Per endpoint? Per API?
* What happens when someone gets over limits? Request is rejected? IP ban? For how long?

I can keep going for a bit longer if you want. For security, we bind to 127.0.0.1. If you change it, we assume you know what you're doing. And I wouldn't take a testnet as a measure of what people will do for mainnet.

I'm also not aware of any other node that has rate limiting on its RPC APIs.

**Comment by kargakis** [comment]
> What limits? Per second? Minute? Hour?

Standard ratelimiting practice is to use something like the token bucket algorithm where we configure a **burst size** (number of queries up to which no ratelimiting is imposed) with a **qps** (how many queries per second we allow after the burst size has been exceeded). The burst size may refill at a rate of qps. That's an example. We can slice and dice it however we want.

> Limit on every endpoint or global? Per API?

The point of ratelimiting is to exclude pathological clients from saturating your app's resources. The simplest approach is to apply it globally for individual clients.

> What numbers we pick? Optimize for a low-load environment? A laptop?
> How do we configure limits when they're too low? Global configuration? Per endpoint? Per API?

I guess the defaults are up for discussion but I am confident we can come up with a set that is reasonable and does not get in the way of non-malicious clients.

> What happens when someone gets over limits? Request is rejected? IP ban? For how long?

The simplest approach is to reject the request and wait for the bucket for that client to refill in order to start accepting requests from it again. IP ban is interesting. 

> For security, we bind to 127.0.0.1. If you change it, we assume you know what you're doing. 

As @quentinlesceller mentioned, wallets still need to be public. At that point, you probably need to be shielding both.

> I'm also not aware of any other node that has rate limiting on its RPC APIs.

Not sure this says as much about not doing it here as it says about the rest of the communities.

**Comment by kargakis** [comment]
This is mostly mitigated now by running w/ basic auth
