### ISSUE TITLE
improvement for store.batch() dead lock risk

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1618]
Recap the discussion in https://github.com/mimblewimble/grin/issues/1611

---
> So, each `store.batch()` call is a `__pthread_mutex_lock_full`, we have dead lock for `store.batch()`, which make the function `txhashset_write()` will never return.

https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/struct.WriteTransaction.html#method.new

>> trying to start two top-level read-write transactions on the same thread will deadlock
---

> @garyyu was just reading the same docs in lmdb_zero crate... 😄
> 
> So that implies we cannot blindly call store.batch() to begin a new "batch" without being aware of other places a batch may have already been started...
> 
> This will attempt to start a read-write transaction in lmdb regardless of if there is one already existing in that thread.
> 
> Let me think a bit more about this.
---

> @antiochp I think we need another discussion thread (with a new issue) to find a better solution for this dead lock risk, to avoid any future dead lock.

So, please let's use this issue to track the improvement solution on this risk.

**Comment by ignopeverell** [comment]
I do think you successfully tracked down the cause of the deadlock in #1611. However this seems like a red-herring to me because we have no practical way to start 2 top-level transactions in the same thread. All these calls are blocking, unless done in a different thread.

**Comment by garyyu** [comment]
Oh, yes. This seems to be an invalid 'improvement'. 

So let's close it.
