### ISSUE TITLE
Travis-CI Speed Optimization

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1635]
To follow the discussion in Gitter:  https://gitter.im/grin_community/dev?at=5bb32d47600c5f64233f55f3  on 2th Oct,  I will take the following tasks

- [x] switch off the mac Travis-CI test temporarily, today
- [x] speed-up the Travis-CI test speed
- [ ] when dual platforms Travis-CI speed is acceptable for us, switch back the mac Travis-CI test. **[Suspended]**

As a baseline of this speed optimization on Travis-CI test, I take a smaller number: 22 Minutes, not strictly fastest one but should be ok as a baseline here. Some references: 
- https://travis-ci.org/mimblewimble/grin/builds/432079350 : 22 minutes, 9 days ago
- https://travis-ci.org/mimblewimble/grin/builds/428607370 : 42 minutes, 18 days ago
- https://travis-ci.org/mimblewimble/grin/builds/424522595 : 27 minutes, 27 days ago

**Comment by antiochp** [comment]
Just to be clear - I don't think we necessarily agreed on these specific steps, just that we should -_discuss_ possible approaches.

I'd propose an alternative approach (that was discussed on gitter) - 

* for branch and PR builds, only run linux builds (and keep them as fast as possible)
* on master run a more exhaustive build against linux + MacOS
  * or alternatively, run a daily scheduled build against MacOS

Even if we can optimize a linux + MacOS build down to sub 20 mins, if the linux only build is sub 10 mins then I'd still personally prefer running the minimal linux only build to give us a tighter feedback loop from travis on dev and branch builds etc.

**Comment by lehnberg** [comment]
For what it's worth I second the approach @antiochp is suggesting. The logic being that (as far as I'm aware) most actual dev work is being done on linux, and macOS is (mainly) for consumption, i.e. end-users.

End users of Grin should be ok with a daily build, I think. Happy to be proven wrong here, but just seems quite sensible to do whatever possible to reduce unnecessary waiting time in development.

**Comment by quentinlesceller** [comment]
I agree with @antiochp too. And as a macOS user, I think it's okay to have daily/master only macOS CI builds. 
Moreover, the macOS specific issues are, for now, extremely rare.

**Comment by garyyu** [comment]
@lehnberg 
> The logic being that (as far as I'm aware) most actual dev work is being done on linux

How do you get this conclusion? Is there real statistics numbers?  I believe most dev on mac.

> , and macOS is (mainly) for consumption, i.e. end-users.

I agree most of the servers are running Linux, so, from **product** point of view, Linux is more important.

**But** pls remember developer's importance for software, especially for open-source community driven project. 

What's the favorite dev environment for developers? You can google it.
- https://www.quora.com/Why-do-most-professional-programmers-prefer-Macs
- https://www.macworld.co.uk/feature/apple/why-programmers-think-mac-os-x-is-best-os-use-3638706/
- https://hackernoon.com/why-do-developers-run-macs-9ad81d58d177

**Comment by antiochp** [comment]
Bitcoin dev (and by extension Grin dev) is likely to be weighted toward Linux over MacOS for a variety of reasons.
I would hesitate to assume that this dev community is representative of tech as a whole.

**Comment by jaspervdm** [comment]
> I'm afraid a middle road for example `MacOS Travis-CI for Non-PR building` doesn't have a real meaning, who will care those failure NOT from a PR? no clear responsibility on those building failures, compare to PR, the responsibility is quite clear and simple, the one who submit PR will have to fix the Travis-CI failure.

Maybe we could have 1 designated person who checks these Mac specific failures and tries to fix them, should they ever appear.

**Comment by mfronczyk** [comment]
I compile master on Mac, although I can't name myself as a Grin dev.

**Comment by ignopeverell** [comment]
@mfronczyk as long as you build frequently and are willing to report build issues when you run into one, that counts.

I think if enough devs run Mac OS, it's a non-issue. Regressions will be caught quickly and fixed quickly. So let's not focus on this too much, except for the release process which we still need to figure out (maybe a `release` branch we merge `master` in regularly?).

And besides, I really can't get behind an OS that requires drag-and-drop to install applications instead of good old `make`.

**Comment by garyyu** [comment]
I close this task for now, since the speed already doubled by #1647 and its fix: #1687 

For a remaining issue:  **the binary release of macos**, I will use another PR to complete it, and need research how to avoid any Travis-CI speed impact.
