### ISSUE TITLE
Do not parse block body before header has been validated

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1642]
The current code and data structures read a full block all at once. This could make a short-lived (because banning would still be relatively quick) DDoS attack.

**Comment by c410-f3r** [comment]
I guess this was already been implemented.

https://github.com/mimblewimble/grin/blob/9c32321c57016cf9542bf5454a7e5818d312a1ee/core/src/core/block.rs#L303-L309

**Comment by antiochp** [comment]
> I guess this was already been implemented.

No. We are still parsing the full block prior to this.

**Comment by c410-f3r** [comment]
I will then fix it
