### ISSUE TITLE
Node API: Multiple Handlers are not displayed

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1653]
When accessing `/v1/` multiple handers are not visible:

-`/v1/header/`
-`/v1/txhashset/merkleproof`

Also not documented in the code that:
- lastrangeproofs
- lastkernels
accepts the parameters `?n=x` in the query.

Also not documented that `/v1/txhashset/merkleproofs?n=x` does not actually requires a position in the txhashset but an output id.

**Comment by coolmike885** [comment]
This is from my device?

**Comment by haarts** [comment]
I believe the relevant endpoint is `/headers` and not `/header`.
