### ISSUE TITLE
Sync opens possible DoS against mining node

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1654]
#1643 aimed to fix an issue where a mining node adds a block while syncing. This results in resetting the header head which then confuses sync (and possibly other parts of the system).

However, as mentioned by @antiochp this opens up a possible attack:

> Miner is fully sync'd
> Miner happily mining on latest block
 > peer advertises new fork with greater cumulative difficulty
> Miner kicks into sync mode and stops mining
> turns out peer was lying about the fork
> Miner now furious

There ought to be away we can prevent the attack without causing the previous issue (i.e. some "syncing but not trusting the total work yet"). This likely ties into #1139 as well.

**Comment by antiochp** [comment]
> syncing but not trusting the total work yet

Would fit quite nicely with fast-fast-sync (flyclient, not yet downloaded all the headers) and other "async" things we can do with sync (verifying huge number of rangeproofs in the background etc.)
