### ISSUE TITLE
transaction routing (send txs direct to miners)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1659]
Problem: _All_ nodes see _all_ regular broadcast transactions. Any node can build a relatively complete transaction graph (for all post-Dandelion transactions, some but not all of which may be aggregated).

What if nodes sent transactions directly to miners or mining pool instead of broadcasting them to peers?

Feels like you would need a way for nodes to advertise themselves (via features or capabilites?) as "accepts transaction".

Any node would be able to lie about this, presumably to either - 
  * DoS the network by dropping transactions, or
  * to monitor and analyse transactions

But what if nodes were selected based on recent mining activity? i.e. the list of nodes allowed to accept txs was based on those recently known to have mined blocks in some recent time period?

Dandelion would work as before - randomly "stemming" through the network until it "fluffs" at a random node on the stem. At this point the node broadcasts the transaction out to a number of "known active miners".

Miners would not broadcast or propagate the tx any further.
Maybe miners agree to send to other miners (determined as above)?

So either - 

* tx gets to a miner that ends up mining the next block (all good)
* tx gets to a miner that ends up mining a block further out in the future (still ok?)
* tx gets dropped or lost and never gets mined (bad, unlikely but not impossible today)

Feels like this would increase the security/privacy of transactions.
At the cost of trusting miners to not mess with the transactions (more than via broadcast today).

Could this work?

**Comment by atlanticcrypto** [comment]
I'm new here. If I say something that is blatantly uninformed, just punch me in the mouth.

Pre-selecting nodes to accept transactions precludes smaller miners from full participation - they may not have mined a block in the 'activity window' - on a theoretical level, the network should not want miners who will not include transactions, they limit throughput - this already happens in practice in other networks during times of low tx-fees.

There is a trade-off here between privacy and transaction fault tolerance - I believe transaction fault tolerance is highest when all nodes see a pending transaction, and privacy is highest when 1 mining node sees a pending transaction.

You may also wind up where there is a centralized node gateway (like Infura) that then charges mining pools to get access to their transaction queue.

**Comment by antiochp** [comment]
No those are all good points. Thanks for this.

> I believe transaction fault tolerance is highest when all nodes see a pending transaction, and privacy is highest when 1 mining node sees a pending transaction.

Yes absolutely. The nuance here for Grin is that we have some (possibly limited) opportunities in advance of nodes observing a pending transaction through Dandelion+Aggregation, where the tx that is observed may actually be an aggregated tx obscuring the details of the individual txs themselves.

There was a discussion yesterday on gitter about this - I think the takeaway was "a single mining node seeing all txs is just as likely to be constructing a tx graph than any other node on the network" so we don't really gain anything in terms of privacy by sending them direct to miners.

**Comment by antiochp** [comment]
Closing this.
