### ISSUE TITLE
Supported GPUs

### ISSUE THREAD

**Issue by pfolthof** [mimblewimble/grin#169]
I was wondering if GPU mining is CUDA (NVIDIA) only or if OpenCL (AMD) is planned?

**Comment by yeastplume** [comment]
At the moment, only cuda is 'planned' in that @tromp intends to do a cuda version of the mean miner. However it's very early days; I'm sure opencl miners will start appearing, and the code is structured to allow an OpenCL miner to be dropped in when someone develops one.

By the way, you'll probably get better results asking these kinds of questions on gitter: https://gitter.im/grin_community/Lobby
