### ISSUE TITLE
syncer creates and runs a difficulty_iter every 10ms

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1693]
We run the syncer loop with a 10ms sleep - 

https://github.com/mimblewimble/grin/blob/770aca9a2deaff444299154208cef9384361730d/servers/src/grin/sync/syncer.rs#L116

But in this (tight) loop we call `needs_syncing` which in turn calls `difficulty_iter()` - 

https://github.com/mimblewimble/grin/blob/770aca9a2deaff444299154208cef9384361730d/servers/src/grin/sync/syncer.rs#L118-L120

https://github.com/mimblewimble/grin/blob/770aca9a2deaff444299154208cef9384361730d/servers/src/grin/sync/syncer.rs#L188-L193

The `difficulty_iter()` creates a `batch` and load a non-trivial amount of data from the db (iterating back over block headers).

This is pretty expensive to be happening every 10ms just to check if we need to transition into sync mode.

**Comment by garyyu** [comment]
It was 1 second loop before.  I changed to 10ms for the sync speed optimization. Indeed need consider more on this.

**Comment by antiochp** [comment]
We should be able to rework this to loop fast when we are syncing, but loop more slowly when in NoSync without making this too complicated.

**Comment by garyyu** [comment]
Closed by https://github.com/mimblewimble/grin/pull/1705 .

And `difficulty_iter()` has been optimized by https://github.com/mimblewimble/grin/pull/1710
