### ISSUE TITLE
Message queue and one dedicated thread for blocks received handling

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1697]
Currently we process any data with a blocking call. For example:
- When received a block from a peer, we call `adapter.block_received(b, self.addr)` , and return until the block is well completed processing.
- Same for `CompactBlock`, `Header`, `Transaction`.

In case one block processing is blocked, the situation will become like this:
```
Thread 49
#4  0x0000555555b450e9 in grin_chain::chain::Chain::process_block_single ()
#5  0x0000555555b485ef in grin_chain::chain::Chain::check_orphans ()
#6  0x0000555555b4503e in grin_chain::chain::Chain::process_block ()
#7  0x000055555579a2b5 in grin_servers::common::adapters::NetToChainAdapter::process_block ()
...
Thread 48
#4  0x0000555555b450e9 in grin_chain::chain::Chain::process_block_single ()
#5  0x0000555555b45027 in grin_chain::chain::Chain::process_block ()
...
Thread 47
#4  0x0000555555b450e9 in grin_chain::chain::Chain::process_block_single ()
#5  0x0000555555b45027 in grin_chain::chain::Chain::process_block ()
...
Thread 46
#4  0x0000555555b450e9 in grin_chain::chain::Chain::process_block_single ()
#5  0x0000555555b45027 in grin_chain::chain::Chain::process_block ()
...
Thread 45
#4  0x0000555555b450e9 in grin_chain::chain::Chain::process_block_single ()
#5  0x0000555555b45027 in grin_chain::chain::Chain::process_block ()
...
Thread 43 (Thread 0x7effe1ffb700 (LWP 18832)):
#3  0x0000555555b45334 in grin_chain::chain::Chain::process_block_single ()
#4  0x0000555555b45027 in grin_chain::chain::Chain::process_block ()
...
```
In this example, I saw total 11 threads on  `process_block`. It could be more and more if wait longer in some exception cases.

Is it a good idea to give a message queue here and give one dedicated thread to handle these received block?  since it must only be handled one by one and  multi-thread for them doesn't make sense here.

**Comment by antiochp** [comment]
I think this is probably the direction we want the overall architecture toward.
There is limited benefit to handling any blocks or headers in parallel as they eventually get appended to our _single_ set of MMRs.
And even duplicate checks etc benefit from sequential operations as want to avoid processing a single block multiple times if we receive it from multiple peers simultaneously.

**Comment by yeastplume** [comment]
Very out of date at this point, closing
