### ISSUE TITLE
Stuck in loop: Error setting txhashet root to build a block

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1718]
Error is the following:
```
Oct 10 20:31:13.742 ERRO Error setting txhashset root to build a block: Error { inner: 

TxHashSetErr: output pmmr hash mismatch }
Oct 10 20:31:13.743 ERRO Chain Error: Other Error: Error { inner: 

TxHashSetErr: output pmmr hash mismatch } 
 Cause: Unknown 
 Backtrace: 
```

Two log files from two stratum nodes:
[grin1.log](https://github.com/mimblewimble/grin/files/2466434/grin1.log)
[grin2.log](https://github.com/mimblewimble/grin/files/2466435/grin2.log)

**Comment by quentinlesceller** [comment]
Downgrading to https://github.com/mimblewimble/grin/commit/4a1e3c27bb9236b2d8a7cd2d0093520645fe06cd "fix" the issue.

**Comment by antiochp** [comment]
What version were you on when this happened? Is there a chance it was not latest on master?

Bugs like these can be really sensitive to both timing and state of the rest of the network - so its not always easy to pinpoint the version.

**Comment by quentinlesceller** [comment]
Closing that one since I cannot reproduced it.

**Comment by quentinlesceller** [comment]
Reopening this issue. Looks like I had a similar problem on the latest master during the night.
4 nodes got stuck in loop. Unfortunately something weird happened with the logs and I don't have them prior the bug.

**Comment by yeastplume** [comment]
probably a bit ancient at this point, please reopen if this is found on mainnet
