### ISSUE TITLE
Commit to "prev_root" in block headers

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1726]
Related - #1555 (FlyClient).
This is definitely not a full flyclient impl but it moves us a step in that direction.

Starting this issue to track concrete steps toward committing to `prev_root` in our block headers.

Tasks - 
- [x] implement header MMR (see #1716) 
  - [x] merge onto `master` branch so we can test this early (not consensus breaking)
  - [x] if happy with impl we can merge onto `testnet4` branch
- [x] on `testnet4` branch introduce `prev_root` to block headers (leave `previous` hash in place)
  - [x] testnet4 PR #1764
  - [x] ideally this happens prior to testnet4 release (so we can avoid a hardfork to introduce it)

* subsequently on `testnet4` (or later) hardfork to remove `previous` hash on headers

I think - 
  a) We can get this into testnet4 without too much hassle.
  b) And that the benefits to doing so now are worth it.

@ignopeverell @yeastplume @tromp does this approach make sense?

**Comment by tromp** [comment]
That makes perfect sense. Before removing prevhash, have as many sanity checks as possible that it's consistent with the header MMR.

**Comment by yeastplume** [comment]
Yes, seems like a good approach, we can try it and work on removing previous hash if all goes well.

**Comment by antiochp** [comment]
Closing this. We are up and running on pre-testnet4. 🚀
