### ISSUE TITLE
Height in ping/pong is unnecessary

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#1779]
What's the point of having height in the ping/pong messages when we already have total_difficulty? 

I found this PR: https://github.com/mimblewimble/grin/pull/407 which suggests it was only necessary for testing purposes, but apparently at some point it ended up getting merged into master.

**Comment by antiochp** [comment]
nice catch

**Comment by DavidBurkett** [comment]
It seems inconsistent to not also have it in the hand/shake messages, though. If we're going to keep it in ping/pong, and therefore allow consumers to make decisions based on it, it seems like we should also include it in the handshake so they aren't required to wait for a ping/pong before having the info.
