### ISSUE TITLE
Translate `intro.md` to german

### ISSUE THREAD

**Issue by ossel** [mimblewimble/grin#1783]
Create 'intro_DE.md' and add link in original intro.md
inspired by #1707

**Comment by nagnok** [comment]
I hope I can do this over the holidays

**Comment by ossel** [comment]
I did already start some time ago but then I got busy. Please check out [my work] (https://github.com/ossel/grin/blob/master/doc/intro_DE.md). I will be able to finish it during the coming days but any kind of suggestions or review is highly appreciated!

**Comment by Roxxik** [comment]
@ossel I started looking into your fork and added my own changes (soon to be PRed to you).

I wonder what the ```Tongue Tying For Everyone``` title tries to convey. The only references I can imagine are tonguetwisters, that would be ```Zungenbrecher``` in german or the oral anomaly ```Tongue Tie``` which does not have a name in german and would translate to ```Ankyloglosson```, the medical term for this condition. 

Both seem not at all related to the content of the paragraph and translating it literally ```Zungenknoten``` does not make sense to me.

**Comment by Roxxik** [comment]
See https://github.com/Roxxik/grin/commit/51e2391bf197880be7c6a4354a9b976177607b8e (PR to ossel's work)

**Comment by Roxxik** [comment]
Ok, regarding ```Tongue Tying for Everyone```, I found references to a tongue-tying curse in Harry Potter that is called "MimbleWimble"...

So I'd suggest calling that paragraph ```Zungenzauber für Jeden``` or longer ```Zungenknoten zaubern für Jeden```

**Comment by ossel** [comment]
Thanks for the contribution. I didn't have the time to continue during the holidays. I will continue this weekend.

**Comment by yeastplume** [comment]
intro_DE is there now, closing in favour of more specific issues
