### ISSUE TITLE
Node did not get 6 headers via gossip

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#1799]
My node never received 6 headers via gossip in 12 hours, as result it was mining 3-8 block length forks. We broadcast to `peer_min_preferred_count `, perhaps it's too conservative and we should broadcast to all connected peers?
Another option is to add recursive header request as we do for blocks https://github.com/mimblewimble/grin/blob/master/servers/src/common/adapters.rs#L499, but it may be pandora box opening.
However it did not happen in last 24 hours. Perhaps we can live with that, blocks will be received in ext sync.

**Comment by antiochp** [comment]
I'm trying to think through the numbers though - if I'm connected to lots of peers and broadcast a new header to only 8 of those, and each of those then sends it to 8 others, what are the odds that you missed as header completely?
It feels unlikely that this is purely a problem with peer selection when choosing who to send to.

That said - it may be worth broadcasting headers (or compact_blocks in the case of a miner) to _all_ connected peers.

Regarding the "recursive" behavior - I suspect this is not actually that useful for full blocks - 
* we currently broadcast either headers of compact_blocks
* we then request compact_blocks or full blocks

So the *only* time a node will receive a full block is when they ask for it explicitly. And a node won't do that unless they have the previous block.

So if anything we should rework the "recursive" behavior to apply to compact_blocks and/or headers.
Say we see a _header_ but we don't have the previous _full block_ then go request the full block (or maybe the compact_block).
Or if we see a _compact_block_ but don't have the previous _full block_ then go request it.

**Comment by antiochp** [comment]
Something else to consider is going even more lightweight than "header first" and doing something like a bitcoin `INV` message to advertise a new block hash.
i.e. we broadcast "block hash first" which would be significantly smaller at 32 bytes vs a block header which weighs in at 1,255 bytes today.
Then we can happily broadcast it to _everyone_ without worrying about network congestion.

**Comment by sesam** [comment]
hashmap was doing up to 8 blocks long forks. How about INV x headers + max
tot diff. And send these INVx only if headers verify? Then we can punish
lying nodes.

**Comment by ignopeverell** [comment]
I'm suspecting this is due to hazardous network conditions at the beginning of T4 and not really how we gossip. Anything that would invalidate my suspicion?

**Comment by hashmap** [comment]
@ignopeverell https://github.com/mimblewimble/grin/issues/1924

**Comment by ignopeverell** [comment]
Just saw that yes. What bothers me is by gossiping to 8 we should already reach all peers with overwhelmingly high likelihood. So it'd be good to see what's going on before going too heavy handed on some alternate solution.

**Comment by yeastplume** [comment]
I'm seeing this happen with 100% consistency on a node.. as a matter of fact it's getting absolutely no blocks that it doesn't already know about whatsover. It's basically waiting 5 blocks then resyncing in a loop. Not just missing a single block, it doesn't appear to be getting any of them.
Latest code.

**Comment by ignopeverell** [comment]
Could you post logs prior to that last restart, that cover perhaps a couple fallbacks and then catch up? Not sure I'll be able to get much from that but might find some inspiration.

**Comment by yeastplume** [comment]
Think this should cover it (I couldn't find anything too remarkable in there,).. just need to grep for the first instance of TRACE to see where the restart that 'fixed' it occurred.

[grin-server-stuck.log](https://github.com/mimblewimble/grin/files/2596822/grin-server-stuck.log)

**Comment by ignopeverell** [comment]
Looking through the code here and there on what could clamp some gossip messages, nothing obviously wrong jumps out. If you can still reproduce on that node (without trace), it'd be useful if you could have it connect to either a seed or another node of yours to get logs from the other side when your node falls behind.

**Comment by hashmap** [comment]
Closing for now, I have a hunch it was caused by some cache logic we had
