### ISSUE TITLE
typo: unrelated module-level doc. comment in servers/src/grin/seed.rs

### ISSUE THREAD

**Issue by eupn** [mimblewimble/grin#1808]
At [this](https://github.com/mimblewimble/grin/blob/d11088c98784000175675e96c67c5aa2c23de76c/servers/src/grin/seed.rs#L15) line:

```rust
//! Mining plugin manager, using the cuckoo-miner crate to provide
//! a mining worker implementation
//!
```

IMO this comment is totally unrelated to the `seed` module functionality, misleading and should be replaced. Possibly this is a leftover from currently removed miner implementation introduced in commit 12480e73100fb6165710307226b6e12cabb0a3a1

**Comment by ignopeverell** [comment]
Sure, want to PR a removal?

**Comment by eupn** [comment]
@ignopeverell I thought it would've be simpler to fix via maintainer's commit to `master`

**Comment by ignopeverell** [comment]
Fair enough: f4eb116
