### ISSUE TITLE
Trying to run node at testnet v4

### ISSUE THREAD

**Issue by ArchangelGr** [mimblewimble/grin#1813]
Version

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Invocation** :  ~# ./grin/target/release/grin

**Result**:

Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: NotFoundErr("BLOCK HEADER: 04acb55c")

Store Error: NotFoundErr("BLOCK HEADER: 04acb55c") })"
See grin.log for further details.

**Comment by eupn** [comment]
>Searched for grin.log , it should be grin-server.log , the file is empty

Thank you for surfacing this issue with inconsistency in log file naming! Should be fixed in #1815 

On your issue, try to remove ~/.grin/chain_data directory to synchronise blockchain again

**Comment by ArchangelGr** [comment]
Done! up and running. Thank you:)
