### ISSUE TITLE
Issue of New Log

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1849]
Recently we switch to log4rs mainly for log rotation feature. It's a good improvement and Thanks to @eupn 

I want to highlight 2 issues here for this change:
- Travis-CI test log seems no grin logs any more. We have before. I'm thinking whether we need get it back or not. If need it back, we can simply modify the test script to add `--  --nocapture` for `cargo test`.
- The date time format looks like too long, for example `2018-10-26T21:28:38.360219+08:00`.  I prefer to simply it as `10-26  21:28:38.360219`.

**Comment by eupn** [comment]
Thank you @garyyu for feedback, I'd change timestamp format for something more simple and readable as well, so I'll change it soon.

**Comment by garyyu** [comment]
@eupn  Did you find the way to simply the timestamp format?

**Comment by eupn** [comment]
@garyyu yes, will create PR today

**Comment by quentinlesceller** [comment]
Also is it possible to bring back the level colours in the terminal?
