### ISSUE TITLE
Wallet Inconsistencies between txs and info

### ISSUE THREAD

**Issue by gonta71** [mimblewimble/grin#1851]
I have been having issues where `$ grin wallet info` and `$ grin wallet txs` show a discrepancy.  It probably stems from using it incorrectly.  

The txs call always shows the txs into the wallet, even if no password or a wrong password is specified for the -p parameter.

The info call sometimes shows the balance correctly, but after subsequent runs just shows 0.  A wallet "restore" call will reset the behavior to show the balance correctly (interesting, even if no password is specified).

This is on branch: ecb102e442259c8c0df5b7b3ed72c6e943f2c39b.

**Comment by sesam** [comment]
@gonta71 do you see this problem also on latest master, or on the [latest binary release](https://github.com/mimblewimble/grin/releases)?

**Comment by yeastplume** [comment]
closed pending furtner information
