### ISSUE TITLE
Compile doc for contracts we can support

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#187]
Until we have proper writeups, it would still be very useful to have a page that compiles links to mailing-list emails that detail the different contract ideas. At least to start with:

* atomic swaps
* secure transaction exchange
* LNs
* etc

Build a doc under our doc directory with those sections and links, that we can later fill-up with actual specs.

**Comment by bgmrk** [comment]
I've gotten this started. 
[Contract Ideas.txt](https://github.com/ignopeverell/grin/files/1400756/Contract.Ideas.txt)
