### ISSUE TITLE
Update stratum server code uses of global "edge_bits" value

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1874]
This does not look right to me:
https://github.com/mimblewimble/grin/blob/master/servers/src/mining/stratumserver.rs#L635

It does not make sense to have a single stratum-wide value for "edge_bits" (or cuckoo_size) now that we allow multiple sizes chosen by the miner on a per solution basis.

It looks like all the "status" stuff needs to be updated also

Does a single "minimum_share_difficulty" setting applied to all solution sizes (in the grin-server.toml) still make sense?

**Comment by bladedoyle** [comment]
I disagree with the "enhancement" tag.  Adding multiple POW was an enhancement.   Unmade changes needed as a result of that enhancement is a bug/technical debt. (imo at least)

**Comment by lehnberg** [comment]
Apologies, I read it as though something additional was needed beyond what was already in there. Not that previous functionality broke as part of changes. Updated.

**Comment by yeastplume** [comment]
I think we're okay here now
