### ISSUE TITLE
pruned hash malleability

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1883]
Discussion on gitter - https://gitter.im/grin_community/Lobby?at=5bd83a26ae7be94016dc111c

Recording it here for reference.

__Q.__ Does this matter in practice and do we need to mitigate it?

----

> John Tromp @tromp 11:01
i think the whole idea of utxo only fast sync implies that pruned hashes are malleable

It would be possible for a miner to mine a long fork predating the fast sync "horizon" and changing a pruned (spent) hash in the MMR.
This would change the root of the output MMR in such as way that existing nodes would see it as invalid, but freshly sync'd nodes would see it as valid.

Old nodes would see this block as invalid, eventually running a new "fast sync" to sync with this new fork.

We would have a block accepted as valid that would be _impossible_ to recreate by reapplying all historical transactions.

> Antioch Peverell @antiochp 11:10
@tromp so we end up with fast sync state that cannot be recreated from a full archival set of blocks...
@jaspervdm I don't think there is any reduced security with this
they can rewrite spent output hashes
but nobody cares

Miners could effectively "rewrite the STXO set", but this would be immaterial in terms of the UTXO set which Grin/MW actually cares about.

> John Tromp @tromp 11:15
we can avoid this by having fixed pruned hashes, but that loses other nice MMR properties

> John Tromp @tromp 11:16
all 0 hash for entire pruned subtree
that destroys append only property of MMR

**Comment by ignopeverell** [comment]
Interesting, I'm just not sure how it could matter very much either. If you have a long fork, and get to rewrite that whole section of history, I'm more worried about what one could do to the UTXO set. You can't really "malleate" them as you could with TXOs and lead to the weird situation described here, but the consequences seem a lot worse.

One mitigation solution could be to have a special handling for long forks and force a new state sync not up to horizon but up to the fork point, and then sync all blocks from that fork point. This way we can make sure the headers and the MMRs are consistent along the whole fork.

**Comment by antiochp** [comment]
Closing for now - consensus is that this is possible but not really an issue to be concerned with.
