### ISSUE TITLE
Genesis header MMR root validation

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1890]
This comment is confusing me given that genesis is at height 0, and at block 1 we should have some previous root hash (which should be something like the hash of genesis || 0).

https://github.com/mimblewimble/grin/blob/3efa7bdac92b60cf60ce0f4a235d4f229c000da7/chain/src/txhashset/txhashset.rs#L714

@antiochp am I missing something?

**Comment by antiochp** [comment]
Yeah that's a bug I think.
The comment is correct. But I think the check should be 
```
		if header.height == 0 {
			return Ok(());
		}
```
