### ISSUE TITLE
Blockchain / Sumtree visualisation

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#191]
RIght now trying to get the state of the blockchain or UTXO set is a very debugger-intensive process. It would be helpful to have tools that facilitate visualisation of the blockchain/sumtrees to allow for easier visualisation for tracing issues or just for general understanding. 

Perhaps not a full blockchain explorer at this point, but certainly some consideration of an API or views into the data set that would facilitate one.

**Comment by ignopeverell** [comment]
As sum trees have been at least partially separately handled, I'm going to close this and make an issue that's a little more explicit about block endpoints.
