### ISSUE TITLE
zip_read improvement with cache

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1928]
Copy from https://github.com/mimblewimble/grin/pull/1923

> @antiochp  Idea for further enhancement - we probably only need to generate one of these and return the same state file to both peers if we get multiple requests like this.
It can probably be "cached" locally and reused, at least for some period of time.

will do this improvement once I get time.

**Comment by hashmap** [comment]
Do we cache txhashet as part of https://github.com/mimblewimble/grin/pull/2813?

**Comment by antiochp** [comment]
I believe we do yes. We were already "caching" them based on current header hash, just not able to take advantage of it within that 60s period.
#2813 will extend this period to 12 hours I believe.
