### ISSUE TITLE
REST API Server Need Support Stop

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1934]
Our REST API server doesn't support `stop` like other servers, which cause an annoying `Address already in use` problem when I want to stop and restart a server (in a test case which is to be added for fork syncing test and so on).

https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/servers/src/grin/server.rs#L228-L235

https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/api/src/handlers/mod.rs#L89

https://github.com/mimblewimble/grin/blob/master/api/src/rest.rs#L161-L173
```
	/// Starts ApiServer at the provided address.
	/// TODO support stop operation
	pub fn start(
		&mut self,
		addr: SocketAddr,
		router: Router,
		conf: Option<TLSConfig>,
	) -> Result<thread::JoinHandle<()>, Error> {
		match conf {
			Some(conf) => self.start_tls(addr, router, conf),
			None => self.start_no_tls(addr, router),
		}
	}
```

Who would like to help to add the `stop` support?
just like https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/servers/src/grin/server.rs#L205,
https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/servers/src/grin/server.rs#L218,
https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/servers/src/grin/server.rs#L242
 and so on.

**Comment by hashmap** [comment]
Code for http server is in place, there was an issue with hyper, I’ll check if it was resolved. TLS part is not implemented yet.

**Comment by sesam** [comment]
I know the pain of hunting processes with open ports. As I understand @garyyu it's probably necessary to bring along the stop: Arc<AtomicBool> into start_rest_apis

**Comment by sesam** [comment]
There's a disabled stop() here, not far below the TODO about adding stopping support:

https://github.com/mimblewimble/grin/blob/0af1f13bf9ff98beae94fd7d73e5613a790e8477/api/src/rest.rs#L242

=)
Maybe still adding stop support differently might be useful?

**Comment by kargakis** [comment]
`Address already in use` looks like a port was leaked which is a different issue from supporting `stop`. We should ensure everything is cleaned up / gracefully terminated when grin receives a termination signal rather than adding the ability to `stop` grin which doesn't solve the underlying issue.

**Comment by kargakis** [comment]
Graceful shutdown is added at https://github.com/mimblewimble/grin/pull/2812.

I think we can close this issue now.

**Comment by hashmap** [comment]
Not yet, rest server internally doesn't try to stop gracefully because of a Hyper issue. It's in my todo list, as well as stop of stratum server.

**Comment by hashmap** [comment]
Will take care of it

**Comment by yeastplume** [comment]
What is the status of this?

**Comment by quentinlesceller** [comment]
Still unimplemented AFAIK.

**Comment by yeastplume** [comment]
implemented https://github.com/mimblewimble/grin/pull/3677
