### ISSUE TITLE
Peers - Concurrency Issues (Send + Sync)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1937]
We do the following in `Peers` and this is almost certainly hiding some potential (and potentially serious) concurrency issues.

```
unsafe impl Send for Peers {}
unsafe impl Sync for Peers {}
```

I assume we did this to make the compiler happy - but I suspect this is just hiding the problem and not actually resolving the underlying issue.

If we comment these two lines out then we get the following build errors -

```
...
error[E0277]: `std::sync::mpsc::Sender<()>` cannot be shared between threads safely
--> p2p/src/peers.rs:476:6  
...
error[E0277]: `std::sync::mpsc::Receiver<types::Error>` cannot be shared between threads safely
   --> p2p/src/peers.rs:476:6
...
```

From the `std::sync::mpsc` docs - 

https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html

> The sending-half of Rust's asynchronous channel type. This half can only be owned by one thread, but it can be cloned to send to other threads.

https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html

> The receiving half of Rust's channel (or sync_channel) type. This half can only be owned by one thread.

So we can fix the first compilation error by simply cloning the sender and sending it to the various peer threads. The sending is designed to be cloneable. By definition `mpsc` is multi-producer, single-consumer).

But the 2nd compilation error regarding the `Receiver` is worrying and we are just hiding it by explicitly making Peers implement `Send + Sync`.

To reiterate the docs -

> This half can only be owned by one thread.

And the error message - 

> `std::sync::mpsc::Receiver<types::Error>` cannot be shared between threads safely

----

https://doc.rust-lang.org/beta/nomicon/send-and-sync.html

> First and foremost, they're unsafe traits. This means that they are unsafe to implement, and other unsafe code can assume that they are correctly implemented.

> Since they're marker traits (they have no associated items like methods), correctly implemented simply means that they have the intrinsic properties an implementor should have. Incorrectly implementing Send or Sync can cause Undefined Behavior.

Implementing `Send + Sync` does not change _anything_ in terms of concurrency or thread safety, all we are doing is telling the rust compiler that we know more about the underlying shared data and that it should ignore any warnings/errors around sharing this data between threads.

This can (and likely will) result in _Undefined Behavior_ because we are passing a `Receiver` around between threads when the docs clearly state this should not be done.

The full compilation error is - 

```
error[E0277]: `std::sync::mpsc::Receiver<types::Error>` cannot be shared between threads safely                     
   --> p2p/src/peers.rs:476:6                                                                                       
    |                                                                                                               
476 | impl ChainAdapter for Peers {                                                                                 
    |      ^^^^^^^^^^^^ `std::sync::mpsc::Receiver<types::Error>` cannot be shared between threads safely           
    |                                                                                                               
    = help: within `peer::Peer`, the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Receiver<types::Error>`
    = note: required because it appears within the type `conn::Tracker`                                             
    = note: required because it appears within the type `enum_primitive::Option<conn::Tracker>`                     
    = note: required because it appears within the type `peer::Peer`                                                
    = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<peer::Peer>`
    = note: required because it appears within the type `(std::net::SocketAddr, std::sync::Arc<peer::Peer>)`        
    = note: required because it appears within the type `std::marker::PhantomData<(std::net::SocketAddr, std::sync::Arc<peer::Peer>)>`
    = note: required because it appears within the type `std::collections::hash::table::RawTable<std::net::SocketAddr, std::sync::Arc<peer::Peer>>`
    = note: required because it appears within the type `std::collections::HashMap<std::net::SocketAddr, std::sync::Arc<peer::Peer>>`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `lock_api::rwlock::RwLock<parking_lot::raw_rwlock::RawRwLock, std::collections::HashMap<std::net::SocketAddr, std::sync::Arc<peer::Peer>>>`
    = note: required because it appears within the type `peers::Peers` 
```

* Each `Peer` has a `Tracker` 
* The `Tracker` wraps two `Senders` and a `Receiver`.
* The outer `Peers` maintains a map of `Peer` instances keyed by `SocketAddr` (the connected peers).
* The `Adapter` in `Tracker` points back to the outer `Peers`. 

So every `Peer` (and every thread spawned for each peer) points to `Peers` which points to all the other `Peer` instances.
So we have a `Receiver` (the `error_channel`) for each `Peer` shared across all the threads.
And we are not allowed to do this - as dong this is effectively "Undefined Behavior".

Starting to come around to the idea that explicitly implementing `Send + Sync` on any complex type is a pretty serious anti-pattern.

We did something similar in https://github.com/mimblewimble/grin/pull/1694
Here we were using a `RefCell` (which is explicitly not thread-safe) and then telling the compiler to ignore this by implementing `Sync + Send` for `OneTime`.
This manifested itself as some _really weird_ "Undefined Behavior" relating to non-atomic reference counting.

Currently we have two instances of this in the grin codebase - 

```
// Issue described above.
unsafe impl Send for Peers {}
unsafe impl Sync for Peers {}


// Still investigating this one but 99% we should not be doing it here either. 
unsafe impl Sync for Chain {}
unsafe impl Send for Chain {}
```

----

How to solve this?

1) I'm lacking a clear understanding of what the topology of this actually should be - in terms of `Peer` vs. `Peers` and which threads have which responsibilities etc.
2) Should we have a single central `error_channel` responsible for peer connection health?
3) Alternatively can each peer manage connection health internally in the peer specific thread?

**Comment by hashmap** [comment]
You are right. I have a fix for that but I somehow forgot about it, I wrote when was removing unsafe code.

> Types that are not Sync are those that have "interior mutability" in a non-thread-safe form, such as cell::Cell and cell::RefCell. These types allow for mutation of their contents even through an immutable, shared reference. 
Another example of a non-Sync type is the reference-counting pointer rc::Rc. Given any reference &Rc<T>, you can clone a new Rc<T>, modifying the reference counts in a non-atomic way.

fair enough

> For cases when one does need thread-safe interior mutability, Rust provides atomic data types, as well as explicit locking via sync::Mutex and sync::RwLock. These types ensure that any mutation cannot cause data races, hence the types are Sync. Likewise, sync::Arc provides a thread-safe analogue of Rc.

We wrap `Peer` in `RwLock` so we must be safe right? Almost `RwLock` doesn't make a corresponding struct fields `Sync`, because you can have multiple readers, which unsafe, becuase T is not `Sync`.   `  RwLock` doc (both ours and `std::sync`) explains that:
> The type parameter T represents the data that this lock protects. It is required that T satisfies Send to be shared across threads and Sync to allow concurrent access through readers.

The simplest solution is to warp `tracker` into `Mutex`, which ensure that only one tread has access to it, which makes the entire structure `Sync`

**Comment by antiochp** [comment]
I'm not sure its that simple though. We cannot just wrap _anything_ in a `Mutex` and declare it safe to share between threads. What happens if the _thing_ uses some thread local storage for example?

I'm concerned that when the rust docs explicitly call out not being able to share a `Receiver` between threads that we cannot simply wrap it in a `Mutex` and have it work that way.

**Comment by antiochp** [comment]
Another example would be the lock guard you get from calling `RWLock.write()` - you are not allowed to simply wrap one of these lock guards in a `Mutex` and share it with other threads and magically have it be thread safe.

But you "can" do this by explicitly tagging a struct as `unsafe impl Send + Sync` - the code will compile but its on you to guarantee the thread safety is preserved (which it won't be).

**Comment by antiochp** [comment]
TIL about OIBITS...

https://internals.rust-lang.org/t/pre-rfc-renaming-oibits-and-changing-their-declaration-syntax/3086
