### ISSUE TITLE
replace c-roaring bitmaps with rust-only bitmap implementation

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1959]
CRoaring continues to be a major annoyance with its dependencies, and I've had some feedback that it's causing major issues trying to create libs for mobile wallets.

Some Possibilities:
* https://docs.rs/bitmap/3.1.3/bitmap/
* Roll our own (given we're probably only using a smallish subset of c-roaring functionality)

Of course, performance is going to be an issue. I can't say I've delved into croaring too deeply, so any thoughts/opinions here are welcome.

**Comment by antiochp** [comment]
Related - https://github.com/mimblewimble/grin/issues/1264 (clang and bindgen discussion).

**Comment by hashmap** [comment]
More annoying it limits us to 32 bits. I'd suggest t start from prioritizing the requirements - portability, minimizing dependencies, performance, compression, scalability etc

**Comment by antiochp** [comment]
@sesam We looked into `roaring` (vs. `croaring-rs`) when we first started looking at using bitmaps.
The repo hasn't been touched in almost 2 years.

**Comment by antiochp** [comment]
The bitmap lib is intended for small dense bitmaps.
> A dense bitmap, intended to store small bitslices (<= width of u64).

We need to be able to efficiently handle bitmaps with _millions_ of values in them.
And these bitmaps may have both very sparse regions and very dense regions in them.

For example - we use a bitmap to maintain the positions of all unspent outputs in the entire TXO set.

The issue is less around API compatibility with croaring and more around the necessity of an actual "roaring bitmaps" implementation.

**Comment by sesam** [comment]
Longer term, we could revive https://github.com/Nemo157/roaring-rs and PR or fork to add the minimal methods and test cases to be usable in grin. @rrybarczyk I did git clone the source and started grepping a bit... PM me on gitter when you're around :). Likely more marathon than a hackathon. But surely faster than rolling our own.

For regular users we can recommend our docker image that should build everything reliably.

For mobile, maybe for now investigate if anyone else has a solution to croaring on ios & android. Or we open an issue or ask croaring's devs.

**Comment by yeastplume** [comment]
I think after discussion this is a bad idea, and given we're doing binary releases now the issues with compilation only need to be dealt with by developers.
