### ISSUE TITLE
Add endpoint to query/visualize the current UTXO set state

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#196]
Among other things, get the current root(s), check existence (spent/unspent), get X latest leafs.

**Comment by yeastplume** [comment]
going to look at shortly as I think this is needed for the docker testnet

**Comment by ignopeverell** [comment]
Sounds good, let me know if you need help. Getting at least the root should be fairly straightforward.

**Comment by yeastplume** [comment]
Roots are easy enough to get, have that working, just going to wait on results from https://github.com/mimblewimble/grin/pull/205 before starting a PR. 

Just one question that's come up. The hashes are easy to get from the chain head, but in order to get the utxo root sum the only way is via the 'extending' function, which is obviously intended for append, and takes a write lock. Do you think it's okay to call this just to read the sum, something like:

```
	/// Returns the sumtree roots for the current head
	pub fn get_sumtree_roots(&self) -> Result<RootSet, Error> {
		let mut sumtrees = self.sumtrees.write().unwrap();

		let roots = sumtree::extending(&mut sumtrees, |extension| {
			Ok(extension.roots())
		})?;

		Ok(
			RootSet{
				utxo_root_hash : util::to_hex(roots.0.hash.to_vec()),
				utxo_root_sum : util::to_hex(roots.0.sum.commit.0.to_vec()),
				range_proof_root_hash: util::to_hex(roots.1.hash.to_vec()),
				kernel_root_hash: util::to_hex(roots.2.hash.to_vec()),
			}
		)
	}
```

**Comment by ignopeverell** [comment]
That's a bit overkill. First, you can just take a read lock. Second, you don't need to call extending (which has a commit/rollback overhead), you can just build the PMMRs and get their roots. Makes sense?

**Comment by yeastplume** [comment]
Yes, I'd tried something like that as well, which ended up calling something like:

```
			output_pmmr = PMMR::at(
				&mut trees.output_pmmr_h.backend,
				trees.output_pmmr_h.last_pos,
			),
```
Is that what you mean?

**Comment by ignopeverell** [comment]
#17837b :-) Should be easily callable from the chain with a lock.

**Comment by yeastplume** [comment]
Sorry, I have no idea what you're referring to with #17837b

**Comment by ignopeverell** [comment]
My bad, mixing github markup. Just committed 17837b that adds a root method to sumtrees in chain.

**Comment by yeastplume** [comment]
Haha, I wrote the same function earlier today... okay thanks very much!

**Comment by sesam** [comment]
@yeastplume Maybe this is a task you could delegate? :) I [went looking](https://github.com/yeastplume/grin/branches), but found no published WIP branch for this

**Comment by ignopeverell** [comment]
Already fixed by @yeastplume who's added a few endpoints for this. Potential improvements should get tracked separately.
