### ISSUE TITLE
Core Dumped during chain sync

### ISSUE THREAD

**Issue by faddat** [mimblewimble/grin#1966]
Right after the chain state finishes downloading, it says it is moving on to step 3/4 and then crashes when it says "preparing chain state for validation."  I then get an Illegal Instruction (core dumped) message in my terminal when Grin dies.

**Comment by ignopeverell** [comment]
Any trace or error in your logs (under `~/.grin/grin-server.log`)? Anything unusual about your running environment?

**Comment by faddat** [comment]
The running environment is a modern intel CPU, 8 GB RAM, and Ubuntu 18.04.  

I used the binary release for testnet 4 found on the releases page in GitHub.  

There *is* quite a bit in that log file and some of it seems not so good:

https://gist.github.com/faddat/53acf8c49916f66e66e9a7487e2925f6

(The stuff that doesn't look right is toward the end but I figure that I might as well provide the whole file.)

If I build today's code, does that connect to testnet 4?

Thanks!
-Jake

**Comment by jaspervdm** [comment]
That binary is already 3 weeks old, try building from master
> If I build today's code, does that connect to testnet 4?

yes

**Comment by faddat** [comment]
I had some issues building from master, seemingly with libssl (Installed it and it still didn't work) and ncurses (also installed but might've installed the wrong package).  

Is there a build guide out there?

**Comment by faddat** [comment]
thanks!
