### ISSUE TITLE
BLOCK_INPUT_WEIGHT, BLOCK_OUTPUT_WEIGHT,  BLOCK_KERNEL_WEIGHT optimization

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#1977]
Consider changing BLOCK_{INPUT,OUTPUT,KERNEL}_WEIGHT
from 1 / 10 / 2 to more easily motivated values like
1 / 21 / 3 which closely matches their relative sizes.

**Comment by ignopeverell** [comment]
Marked this as consensus breaking but unlikely to cause any issue in T4 due to relatively small block sizes.
