### ISSUE TITLE
secondary_pow_scaling bug and separate DAMP_FACTORs

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#1980]
the first line of this function

	let snd_count = 100 * diff_data.iter().filter(|n| n.is_secondary).count() as u64;

has a bug in that the first element of diff_data should be excluded as per the comment
	// DIFFICULTY_ADJUST_WINDOW + 1 (for initial block time bound)

Also, since the count is highly variable across a mere 60 blocks, it needs its own much larger DAMP_FACTOR. Experiments suggest a value around 13 might be appropriate.

**Comment by antiochp** [comment]
Damn - just saw that we count primary vs. secondary across the 60 blocks... which complicates my proposed perf improvements in #2013 (we need all 60 blocks and not just the first and last in that period).

**Comment by tromp** [comment]
No problem if you add number of AR blocks as header field...
You could even store it modulo 64 in 6 bits if you want to optimize for space:-)

**Comment by antiochp** [comment]
I'm really confused by this line of code + comment - 
```
	// Get the secondary count across the window, in pct (100 * 60 * 2nd_pow_fraction)
	let snd_count = 100 * diff_data.iter().filter(|n| n.is_secondary).count() as u64;
```

We count all the header infos that are `is_secondary` and then multiply this by 100.

And this seems to be very different to `in pct (100 * 60 * 2nd_pow_fraction)`.

**Comment by tromp** [comment]
That  comment equates a pct with 0.01, so getting a quantity in units of pct is dividing it by 0.01, or equivalenty, multiplying by 100.
The 2nd _pow_fraction is simply the count of secondaries divided by window size (60).
Feel free to change comment to 2nd_pow_count / 0.01

**Comment by antiochp** [comment]
Oh I get it now 🤦‍♂️ 

For 6 secondary blocks in a 60 block window - 

`100 * 60 * (6 / 60) == 100 * 6`
