### ISSUE TITLE
maybe: separate out wallet api (?) functions somewhat more (from yeastplume #1983)

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#1985]
in #1983 yeastplume suggested: 
> We may want to break up the wallet api somewhat to ensure that transaction building functions don't send anything to anyone, but just return the result of the current step to pass on / respond as required (that will probably make the workflow a bit more flexible).

Like moving more into wallet/src/libtx? Or make a new crate that wallet makers could integrate with directly?

> a person tried - unsuccessfully - to use the wallet crate from crates.io

What feature scope is wanted in a crate that wallet makers would want to use? @mcdallas @kylanhurt @i1skn
Maybe the minimal (but necessary and sufficient) features needed by every wallet UI that want's to encapsulate seed, password, transactions building, and nothing more?

That leaves any messaging / p2p to be handled by the UI creator, as was already seen in the grincon0 example ios wallet.

**Comment by yeastplume** [comment]
This is already covered by the current PR, thanks.
