### ISSUE TITLE
For discussion: Single fee per block.

### ISSUE THREAD

**Issue by andybellenie** [mimblewimble/grin#203]
Some insomnia thinking here,  please make allowances if my sleep-deprived brain makes no sense.

Fees have two purposes: a) to discourage abuse of the network, and b) to allow users to express the urgency of a transaction by including a higher fee. At times of high usage, a rational miner will include transactions with higher fees (as long as they get to keep them).

Commonly, transactions that are selected may end up paying more than was necessary in order to be included in a block.

To make transactions cheaper, instead of having a fixed fee, they could have a maximum fee. When creating a block, miners select the highest paying transactions as usual. Once a full block is assembled, the lowest fee used by an included transaction is then applied to all transactions in the block, and the remainder returned to the originator (via a change address?). In this way, the max fee operates like a bid in an auction and no one needs to pay more than necessary.

Anything that reduces the cost of transacting is a good thing. However, I wonder if returning the leftover fees would impact privacy somehow, or require so much additional data that it could actually cost more.

I'm also not sure how this is affected by the MW block format or fee burning. Comments welcome!

**Comment by andybellenie** [comment]
The same idea, proposed for bitcoin, by smarter folk than I...
https://medium.com/@avivzohar/rethinking-bitcoins-fee-market-ea9319e4ea57

**Comment by antiochp** [comment]
I don't think the refund of excess fees is possible with Grin/MW - each tx needs to be built interactively (all involved parties) including these refunds (and you would need to know the amounts in advance to build the tx).

**Comment by andybellenie** [comment]
Isn't the fee in clear? Is it not possible for a miner to take the transaction but include it in the block with a lower fee? once the block is confirmed that effectively becomes the amount you paid, it doesn't even need to be refunded. A miner wouldn't want to do that willingly, but could a consensus rule reject any blocks where one transaction is paying a high fee than another?

I guess the question is, is it possible for miner's to adjust fees downwards prior to confirming a block without breaking any of the cryptography.

**Comment by antiochp** [comment]
Yes the fee is in the clear but say we had the following - 

Party A spends `1000` coins to send `500` coins to B.
The fee is `10` coins.
A would generate an input `amount=1000` and an output `amount=500` for change.
B would generate an output `amount=490` (500 minus 10 in fees).

If the fees ended up being less then one of those inputs or outputs would not be correct (say the change should now be `amount=502` for example.

The fee is in the clear - but it is implicit in terms of the inputs and outputs, where the amounts do matter up front.

**Comment by andybellenie** [comment]
Ok, thanks, that makes sense.

**Comment by antiochp** [comment]
That said - we could potentially imagine a more complex interaction between parties where some kind of fee negotiation takes place for a single tx.
I'm not sure this could be achieved across an entire block though.
