### ISSUE TITLE
[investigate] "inverted" tx send

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#204]
Right now (with existing signature impl) - 

1) sender builds partial tx
1) sender sends partial tx to recipient
1) recipient builds full tx
1) recipient pushes tx to pool

It seems like it would be possible to flip this around so recipient is responsible for generating the partial tx - 

1) sender "sends" `amount=100` to recipient (basically asking for permission to send)
1) recipient builds partial tx to cover the single output + expected? fees
1) recipient sends partial tx back to sender
1) sender builds full tx
1) sender pushes tx to pool

The big benefit here (I think) is the partial tx goes from being an "anyone can spend" to an "anyone can send me this amount".

Is this even possible?
Does it make sense?

**Comment by andybellenie** [comment]
I was thinking about this the other day, retail transactions seem the obvious use case, especially as the inverted format would allow the recipient to pay the network fee (as per VISA)

**Comment by antiochp** [comment]
Closing this - aggsig is coming.
