### ISSUE TITLE
Genesis release process and script

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#2053]
We need to automate the genesis block release process so it's relatively quick and minimizes last moment errors (done a few of these on testnets). Writing it down in code will also help in normalizing what it should look like and avoid bad surprises.

The process itself should be the following:

1. Prepare a multisig output and kernel owned by the council treasurers for the coinbase. This can be down a few days prior.
2. Grab the latest bitcoin block hash.
3. Build a genesis block with the prepared coinbase and the bitcoin block hash as `prev_root`. The timestamp of the block should be 30 min ahead to leave enough time to run a build and start a node.
4. Mine the block so we have at least a valid Cuckatoo29 cycle. We don't require a given difficulty for that solution.
5. Finalize the block with the proof-of-work, inserting a high-enough difficulty (to be agreed upon separately).
6. Commit the block to github.
7. Tag version 1.0.0 (scary).
8. Dig a hole, hide in it for the next 48h.

Let me know if I missed anything.

**Comment by antiochp** [comment]
We should check the current code will actually handle a non-empty genesis block. 

I suspect there are some assumptions in the code around there being no outputs in there, particularly with the "supply/emission" logic relative to block height.

**Comment by mcdallas** [comment]
> 
> 
> Where do we sign up for one of the juicy genesis grins and/or our name carved into the concrete?

Merkle root of all github contributors!
