### ISSUE TITLE
Configuration option to auto-start wallet listener

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#2064]
Currently user has to run `grin wallet listen` manually. Would be nice to have a config option on `grin-server.toml` to auto start it (as it used to be). In this case impl of https://github.com/mimblewimble/grin/issues/2063 could use it to provide a better user experience and reduce number if question in the gitter channel.

**Comment by yeastplume** [comment]
We explicitly removed this and I think it should stay removed. Users should explicitly be creating and managing their wallets, which means initialising the wallet themselves, writing down their recovery phrases, and creating/using a password. If we had a config option to start this, we'd need somewhere for a user to store a password, or default to a blank password (which I don't think we want to do for mainnet.

I agree the user experience needs to be better, but I don't think this is the solution.

**Comment by hashmap** [comment]
@Onefox yes, if user needs more sophisticated setup we assume she knows how to do it. this is the default for "normal" users.

I'd ask the password directly on the node start (if this option is enabled). The rational is that a user doesn't want just a node, she wants it with the wallet.

The most confusing part with that is mining, the miner waits for wallet which is not obvious for the most of users, I see it daily in gitter

**Comment by yeastplume** [comment]
I think this is okay now given the instruction docs we have. I'm still wary of running anything by default, the user should explicitly create a wallet with a password and run the listener
