### ISSUE TITLE
Inconsistency between TX logs and outputs log.

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#2069]
Looks like my transaction logs is stuck on transaction 6283 while I can see that it goes up to more than 7013 in the outputs log. 

[outputs.txt](https://github.com/mimblewimble/grin/files/2640363/outputs.txt)
[txs.txt](https://github.com/mimblewimble/grin/files/2640364/txs.txt)

**Comment by quentinlesceller** [comment]
Again just happened today. The main issue is that if we send a file transaction it's basically impossible to finalise.
[outputs.txt](https://github.com/mimblewimble/grin/files/2669070/outputs.txt)
[tx.txt](https://github.com/mimblewimble/grin/files/2669071/tx.txt)

**Comment by yeastplume** [comment]
this should be fixed now by #2148, could you verify when you're able?

**Comment by quentinlesceller** [comment]
@yeastplume great. Yes I'm currently updating my nodes?

**Comment by yeastplume** [comment]
Does this seem resolved now?

**Comment by quentinlesceller** [comment]
Solved. Closing.
