### ISSUE TITLE
Sign hashed switch commitment in range proof

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#207]
Currently, the hashed switch commitment could be malleated along the way while relaying. If mine, this could have catastrophic consequences if the switched commitment hash is relied on, either to secure the output with QC or just for wallet recovery.

It turns out secp256k1-zkp now accepts additional data that can be signed by the range proof:

https://github.com/mimblewimble/secp256k1-zkp/blob/master/include/secp256k1_rangeproof.h#L247

We should pass the hashed switch commitment data to that (or maybe the whole output hash) to avoid the above problem.

**Comment by yeastplume** [comment]
Will take this on... sometime before Testnet 2 anyhow :D

**Comment by antiochp** [comment]
I wondered what that seemingly optional `extra_commit` was for when I was porting the secp256k1 stuff across to the mimblewimble repo...

**Comment by yeastplume** [comment]
See comments in https://github.com/mimblewimble/grin/issues/273... with bullet proofs we don't have anywhere near as much space to store messages... this+the amount may fit, but we need to be judicious with what we store in them.

**Comment by yeastplume** [comment]
Done via https://github.com/mimblewimble/grin/pull/730
