### ISSUE TITLE
Problems comings when I want to do example with 3 local nodes 

### ISSUE THREAD

**Issue by lvbin2012** [mimblewimble/grin#2087]
I want to do example with 3 local nodes . as https://github.com/mimblewimble/docs/wiki/How-to-use-grin#example-with-3-local-nodes.
problem 1:
I do this :
input command: grin wallet init
my password is "llw"
the I input command grin wallet -p "llw" -a "http://127.0.0.1:10001" listen -l 15000
Error is "Error decrypting wallet seed (check provided password)"

**Comment by lvbin2012** [comment]
problem 2:
~/code/rust/grin/target/release$ ./grin server -m -p 10000 -a 10001 -w "http://127.0.0.1:15000" run

error: Found argument '-m' which wasn't expected, or isn't valid in this context

USAGE:
grin server [OPTIONS] [SUBCOMMAND]

For more information try --help

**Comment by yeastplume** [comment]
Hi, this isn't an issue with the code. Please feel free to drop by the support channel and someone there will be able to help: https://gitter.im/grin_community/support
