### ISSUE TITLE
question about next_difficulty calculation

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2088]
For the calculations for `next_difficulty` we generate "synthetic" header_infos when we are close to the genesis block and do not have a full window (30 blocks) of data to look at.

We generate synthetic blocks "back in time" from the genesis block to fill the 30 block window.

Intuitively (and probably incorrectly) I would have expected us to backfill per-block difficulties back from the genesis block, based on the oldest block difficulty (i.e. the genesis block).
But it looks like we actually use the most recent block and backfill the blocks from that difficulty - 

```
height 1
[1856000]
backfilled to produce:
[1856000, 1856000, 1856000, ..., 1856000]

height 2
[1856000, 1856000]
backfilled to produce:
[1856000, 1856000, 1856000, ..., 1856000, 1856000]

height 3
[1856000, 1856000, 928000]
backfilled to produce:
[928000, 928000, 928000, ..., 1856000, 1856000, 928000]

height 4
[1856000, 1856000, 928000, 479466]
backfilled to produce:
[479466, 479466, 479466, ..., 1856000, 1856000, 928000, 479466]
```

Is this correct behavior? It looks weird when written down like this as the difficulties _jump_
at the first few real blocks.

I just want to understand what I'm looking at.

**Comment by tromp** [comment]
that's the intended behaviour
this is to allow the diff to come down at max possible rate
in case the hashpower is badly over estimated

also, we wanted to keep this code as simple as possible, as it is only used for a few hours,
but remains consensus critical forever.

**Comment by antiochp** [comment]
:+1: thanks for that background.
I think I get it now - we effectively weight the adjustment toward recent blocks and not the over estimated genesis block.

Just wanted to make sure I understood what I was seeing.
