### ISSUE TITLE
latest build failure

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#2102]
```
error: Edition 2018 is unstable and only available for nightly builds of rustc. 
                                                                                
error: Could not compile `grin_util`.                                           
warning: build failed, waiting for other jobs to finish...
error: build failed 
```
@hashmap seems related to your changes?

**Comment by hashmap** [comment]
Docs have been updated, stable rust 1.31 is needed, run `rustup update`

**Comment by kargakis** [comment]
I had run `rustup update` already but for some reason I had a rustc 1.30.1 binary leftover in my system. Fixed now, grin compilation proceeds, thanks!

**Comment by xxsyntax** [comment]
`rustup update` solved this issue for me as well.  thank you guys for posting this.

**Comment by wenqingyu** [comment]
when I ran`rustup update`, I got `rustup command not found error`

So I trying to install rustup with `curl https://sh.rustup.rs -sSf | sh`
However, I still error

`info: downloading installer
error: it looks like you have an existing installation of Rust at:
error: /usr/bin
error: rustup cannot be installed alongside Rust. Please uninstall first
error: if this is what you want, restart the installation with `-y'
error: cannot install while Rust is installed`

So I found this link: https://www.howtodojo.com/2017/09/install-rust-ubuntu-16-04/  to solve the issue!
