### ISSUE TITLE
Wallet receive can be called more than once on the same slate

### ISSUE THREAD

**Issue by PositronicBrain** [mimblewimble/grin#2118]
Currently `grin wallet receive` can be called multiple times on the same slate file, which results in many identical transactions appearing in the wallet. Once one of these transactions is confirmed the other ones remain as unconfirmed in the receiver's wallet.

Is this intentional? If not so I can work on this issue.

An approach to solve it would be to purge all the transactions referencing the same inputs once one of them is confirmed. Alternatively the wallet could forbid to add slates referencing the same inputs more than once.

**Comment by yeastplume** [comment]
No, it's not intentional, and good catch, thanks. It just needs to check whether a tx with the given slate ID exists and throw an error if so.
