### ISSUE TITLE
Remove bzip2 dependency

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2119]
#2111 changed the txhashset zip writer to write uncompressed zips, but bzip2 support needs to be maintained for a little bit to support the ability of new clients to sync from old clients. After a few weeks, when enough nodes are running the newer code, we can remove the dependency on bzip2 by changing the zip dependency to:

zip = {version = "0.4", default-features = false}

**Comment by yeastplume** [comment]
Surely now's the time to do this, just before floonet launch?

**Comment by yeastplume** [comment]
This evening at 9 UTC as far as I know, I can make the change as well, seeing as I'm in front of it

**Comment by DavidBurkett** [comment]
Go for it. Thanks

**Comment by quentinlesceller** [comment]
Fixed by #2190.
