### ISSUE TITLE
ERRO Failed to submit a solution

### ISSUE THREAD

**Issue by Goffmann** [mimblewimble/grin#2130]
Dec 11 23:37:39.074 ERRO Failed to submit a solution: Object({"code": Number(-32502), "message": String("Failed to validate solution")})

when i run grin-miner, i got this error, and i don't know how to fix it , help me !!!

and i have other question:

1。how to run the grin wallet listen in backgrounder?
2。run the grin-miner backgrounder?

**Comment by mably** [comment]
Github is not the right place for such questions, it's for code related issues only.

Use the Gitter support channel: https://gitter.im/grin_community/support

**Comment by quentinlesceller** [comment]
Hey @Goffmann @mably is right this is not the right place to ask. Feel free to join us in https://gitter.im/grin_community/support so we can help you.
