### ISSUE TITLE
testnet vs mainnet conditional logic

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2140]
If we decide on a permanent testnet we should remember to revisit various `is_testnet()` conditional logic.

We may want a temporary solution around `is_testnet4()` while testnet4 exists, but once we move to a (hopefully clean) testnet/mainnet we can get rid of any current HF block height logic specific to testnet4.

Related - #2125.

**Comment by ignopeverell** [comment]
I was thinking of branching for that permanent testnet (betanet?) so we can clean all these up, then set it up with a genesis and release as we've done with our other testnets. Sounds reasonable?

**Comment by antiochp** [comment]
Closing - `floonet/mainnet` implemented.
