### ISSUE TITLE
Stratum server accepts only string ids

### ISSUE THREAD

**Issue by NaN-git** [mimblewimble/grin#2149]
The stratum server does not seem to accept requests that contain non-string ids like in
`{"id":2,"method":"getjobtemplate","jsonrpc":"2.0","params":null}`
Using `{"id":"2","method":"getjobtemplate","jsonrpc":"2.0","params":null}` works though.

**Comment by quentinlesceller** [comment]
While strange to use string for int here, this is not an issue. It's also documented in the doc https://github.com/mimblewimble/grin/blob/master/doc/stratum.md. Not sure it's really important to change that.

**Comment by NaN-git** [comment]
Are there any plans or ideas how to make the stratum server JSON RPC 2.0 compliant? I don't think that this is possible without breaking compatibility with some clients.
Otherwise I would suggest that the server should also accept an integer as request id.

**Comment by yeastplume** [comment]
I don't think it's a big ask to allow the server to accept an integer as well as a string for that field. Labelled issue accordingly if anyone wants to pick this up
