### ISSUE TITLE
"wallet send" failing with "transaction does not exist"

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2169]
Not sure what is happening here. 

Tx appears to be built successfully but then fails during final validation step with `Wallet command failed: LibWallet Error: Transaction 28c02fa3-868b-4cbb-9cc7-94dca007dee3 doesn't exist` - 

```
20181216 22:00:09.965 DEBUG grin_wallet::adapters::http - Posting transaction slate to http://127.0.0.1:13415/v1/wallet/foreign/receive_tx
20181216 22:00:10.092 DEBUG grin_wallet::types - Using wallet seed file at: /grin/node1/wallet_data/wallet.seed
20181216 22:00:13.156 DEBUG grin_wallet::types - Using wallet seed file at: /grin/node1/wallet_data/wallet.seed
20181216 22:00:13.224 DEBUG grin_core::libtx::slate - Validating final transaction
Wallet command failed: LibWallet Error: Transaction 28c02fa3-868b-4cbb-9cc7-94dca007dee3 doesn't exist
```

**Comment by yeastplume** [comment]
This is likely happening when trying to update the stored transaction with the final version (there have been some changes recently but tests all pass), what are the steps to reproduce? Is this with every transaction?

**Comment by antiochp** [comment]
Not sure if its all transactions.

But just realized - this was a send to myself via 127.0.0.1 -

```
../target/release/grin wallet send 1.7 -d "http://127.0.0.1:13415" --fluff
```

And it was a transaction with a couple hundred inputs in it.

I'm guessing the error may be related to the send to 127.0.0.1?

**Comment by yeastplume** [comment]
yes, I have it, will push a fix shortly
