### ISSUE TITLE
Improve error thrown when compiling on ARM systems

### ISSUE THREAD

**Issue by liamaharon** [mimblewimble/grin#2202]
First off, huge thank you to all the Grin developers working on this project, it's really something special.

I ran into trouble compiling Grin on my Raspberry Pi 3 B+. 

The build fails when compiling `grin_store`, it seems the RPI architecture can't handle a usize type as big as specified in `store/src/lmdb` ln 75 (`env_builder.set_mapsize(549755813888).unwrap_or_else(|e| {`).

This is the error thrown:
![screenshot from 2018-12-22 15-45-09](https://user-images.githubusercontent.com/16665596/50370757-aa64a500-0600-11e9-9313-471921ea28ae.png)

a bit confusing for a newb like me who isn't familiar with system architecture limitations, or Rust. 

I suggest a check (or similar) is added before that line to ensure `usize::max_value()` is large enough to handle that value. If it's not large enough, we can throw a more friendly error to the user.

Even better, the check could be made before compilation starts so the user doesn't need to wait for a few hrs on a low power system before realising it isn't compatible.

If something like this makes sense, let me know and I'll have a go opening a PR to address it.

edit: 
could also add a line to https://github.com/mimblewimble/grin/blob/master/doc/build.md similar to 
"Not Windows 10 yet [grin kind-of builds. No mining yet. Help wanted!]" 
but for RPi / ARM

**Comment by sesam** [comment]
Is it possible to lower the map_size value to something small enough to work on ARM?

**Comment by kravens** [comment]
On the 1.0.0 release this is still an issue, hope a workaround is found soon.

> pi@raspberrypi:~/grin $ cargo build --release
   Compiling reqwest v0.9.5
   Compiling grin_store v1.0.0 (/home/pi/grin/store)
warning: unused import: `lmdb_zero`
  --> store/src/lib.rs:23:5
   |
23 | use lmdb_zero;
   |     ^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

>warning: unused import: `memmap`
  --> store/src/lib.rs:24:5
   |
>24 | use memmap;
   |     ^^^^^^

>error: literal out of range for usize
  --> store/src/lmdb.rs:77:16
   |
77 |         .set_mapsize(549_755_813_888)
   |                      ^^^^^^^^^^^^^^^
   |
   = note: #[deny(overflowing_literals)] on by default

>error: aborting due to previous error

>error: Could not compile `grin_store`.
>warning: build failed, waiting for other jobs to finish...
>error: build failed

**Comment by sesam** [comment]
Grin's choice of DB:
- We picked rocks for its fame and good rust bindings.
- Painful builds moved us to LMDB.
- We still have Windows/android/other troubles with LMDB, but we're happy with LMDB's better auto-recovery.

Probably just any key-value DB with i.e. transactions works, so we can avoid auto-recovering into an inconsistent state.

Every OS has some DB that the platform offers app developers, is that an option at all?
We could avoid compiling a DB engine together with grin, but looking around, I didn't find any existing solutions to reuse and we can't build that ourselves.

Did anyone look closer at https://docs.rs/unqlite/ yet?
> `UnQLite is a self-contained C library without dependency. It requires very minimal support from external libraries or from the operating system. This makes it well suited for use in embedded devices that lack the support infrastructure of a desktop computer. This also makes UnQLite appropriate for use within applications that need to run without modification on a wide variety of computers of varying configurations.`

If we one --feature= variant of grin that uses another DB, then unqlite seems at least worth trying.
Or maybe just add different clients to interface to whatever the OS has. Realistically we'll need raw performance only on linux for running grin node servers, and other users and platforms will primarily use wallets and merchant apps, which is also basically wallets.

Would you @kravens be up to testing out another DB with better ARM support? Maybe I can be of help.

**Comment by hashmap** [comment]
I assume this issue was fixed, we start with a low value and increase when needed. Feel free to reopen if needed
