### ISSUE TITLE
Support needed for mainnet values for BIP32 version/network

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2207]
Floonet uses 0x033C08DF for BIP32 network/version for public extended keys and 0x033C04A4 for private extended keys. We'll need new values for mainnet, and Keychain will need to change to support both networks running simultaneously.

**Comment by DavidBurkett** [comment]
But what about the keys already generated for floonet? They'll look like mainnet keys. We could just use mpub and mprv.

**Comment by DavidBurkett** [comment]
OTOH, they're talking relaunch tomorrow, so if this gets changed before then, @mcdallas suggestion could work.

**Comment by yeastplume** [comment]
#2235 should add this, would appreciate if someone could independently verify the values are correct
