### ISSUE TITLE
wallet send -> wallet receive api issues

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#221]
Looks like there's an issue with the api call between `wallet send` and `wallet receive`.
I am investigating.

**Comment by ignopeverell** [comment]
It's entirely possible that I missed a port when doing the 13416 -> 13415 change yesterday. But I did check fairly thoroughly.

**Comment by antiochp** [comment]
Fix up here - #222 
First problem was we were registering the handler on `GET /receive/transaction` (needs to be `POST`).
Then encountered an issue with json body not being what we expected - so I took what we had for `/receive/coinbase` and used the same pattern (with `bodyparser`).

**Comment by antiochp** [comment]
I've tested both `wallet send` and `wallet receive` and both are working locally.

**Comment by antiochp** [comment]
Resolved in #222
