### ISSUE TITLE
wallet locks both coinbase, although only one was spent

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#2213]
Johns-iMac:floonet tromp$ grin wallet  info
Password: 

____ Wallet Summary Info - Account 'default' as of height 3481 ____

 Total                            | 120.000000000 
 Awaiting Confirmation (< 10)     | 0.000000000 
 Locked by previous transaction   | 0.000000000 
 -------------------------------- | ------------- 
 Currently Spendable              | 120.000000000 

Command 'info' completed successfully

Johns-iMac:floonet tromp$ grin wallet send  -d http://185.8.164.22:13415 50
Password: 
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction slate (is recipient listening?)

Johns-iMac:floonet tromp$ grin wallet send  -d  http://185.8.164.22:13419  50
Password: 

Command 'send' completed successfully
Johns-iMac:floonet tromp$ grin wallet info
Password: 

____ Wallet Summary Info - Account 'default' as of height 3550 ____

 Total                            | 69.993000000 
 Awaiting Confirmation (< 10)     | 69.993000000 
 Locked by previous transaction   | 120.000000000 
 -------------------------------- | ------------- 
 Currently Spendable              | 0.000000000 

Command 'info' completed successfully

I assume the failed command doesn't keep the coinbase locked?!

**Comment by mcdallas** [comment]
The wallet uses all your outputs by default. You need to pass `-s smallest` if you want to use only one.

**Comment by tromp** [comment]
Oh; didn't realize.
So it wants to consolidate whole wallet balance into single change output.
There is something to be said for that...
