### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by kalderonski** [mimblewimble/grin#2220]
Hello
On Ubuntu Linux 18  I am gettinng this error when running grin-miner

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21

Backtrace gives this:

stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:210
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:224
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:487
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:394
   6: rust_begin_unwind
             at src/libstd/panicking.rs:321
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::panicking::panic
             at src/libcore/panicking.rs:59
   9: grin_miner::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:306
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:285
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

**Comment by hashmap** [comment]
Would you mind to open it in grin-miner project?

**Comment by mingderwang** [comment]
yes, it works if you run in the root directory of the project.

**Comment by earlystareyes** [comment]
I have same problem when I open grin-miner on mbp.how to deal with it?

**Comment by olealgoritme** [comment]
cd /your_folder/grin-miner ; target/debug/grin-miner
