### ISSUE TITLE
Send grin without node (offline tx building)

### ISSUE THREAD

**Issue by Onefox** [mimblewimble/grin#2227]
For tx creation via cli send command the block height is required according to https://github.com/mimblewimble/grin/blob/master/doc/wallet/transaction/basic-transaction-wf.png

It should not be to hard to add the block height as argument in the cli send command and the [issue_send_tx ](https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#post-issue-send-tx) REST API.

At the moment you are getting the following error when sending via a wallet without a running node:
`
Wallet command failed: LibWallet Error: Client Callback Error: Getting chain height from node
`

Are there any reasons against it?

**Comment by yeastplume** [comment]
The block height should definitely not be exposed as a user param. The wallet needs to contact a node during every transaction operation to make sure all of its outputs are still current against the latest block height, and the error you're seeing about chain height just happens to be the first error you get when you can't contact a node. Trying to build a transaction without the latest view on the current UTXO set would lead to all sorts of trouble.

**Comment by mably** [comment]
What kind of trouble besides the transaction being rejected as invalid by the network?

**Comment by yeastplume** [comment]
I think we already have enough troubles with all of the various cases for unconfirmed/uncleaned outputs in the wallet without adding completely offline and un-validated transaction building to the mix.

**Comment by mably** [comment]
Ok, we can definitely postpone it until the wallet gets hardened a bit.

**Comment by Onefox** [comment]
This would be a step to being able to manage UTXOs yourself.

That you can bring your wallet into an uncertain state about the UTXOs should be clear but I still think the possibility should be enabled.

Also this could help manage very basic cold storage or?

How is a tx handled for now if it wants to spend invalid outputs?

**Comment by sesam** [comment]
After mainnet is probably the best time to continue on this topic, but to not forget: there's also this idea https://lists.launchpad.net/mimblewimble/msg00604.html by garyyu that we don't know yet if it's doable. If you know some good bat signal for more cryptographers to take a look at the idea and try to find any not yet solved (or not solvable) problems that'd be great.

**Comment by yeastplume** [comment]
Closing

**Comment by Onefox** [comment]
Is there any news on this or other issues for offline tx building and signing?
