### ISSUE TITLE
Lost grins from delayed wallet receive and finalize

### ISSUE THREAD

**Issue by jasonxh** [mimblewimble/grin#2228]
Steps to reproduce:
1. `grin wallet send -m file -d 1.grin 1`
1. `grin wallet tx -i <txid>` shows all the involved inputs and change output.
1. Wait for a day. (Not sure of the exact time needed to repro, but at least a few hours).
1. `grin wallet tx -i <txid>` shows all the involved inputs, **but the change output is no longer showing up**.
1. `grin wallet receive -i 1.grin`, run either locally or from another wallet.
1. `grin wallet finalize -i 1.grin.response`. **It shows the command is successful.**
1. Wait sometime for the tx to be confirmed.
1. `grin wallet tx -i <txid>` still shows the tx as unconfirmed, but all inputs are now marked as spent, and the change output is still nowhere to be found. This results in lost change and a dangling tx.

I can then restore the entire wallet to recoup all the grins, but that results in loss of local tx data.

**Comment by yeastplume** [comment]
Right, there's a dusty bit of code there that cleans unconfirmed outputs more than 500 blocks old.. obviously this needs to be rethought.
