### ISSUE TITLE
docker error on run

### ISSUE THREAD

**Issue by vanities** [mimblewimble/grin#2245]
When running `$ docker run -it -v $HOME/.grin:/root/.grin grin`, the following error is produced:

```
thread 'main' panicked at 'Error loading server configuration: Error parsing configuration file at /root/.grin/grin-server.toml - unknown variant `Testnet4`, expected one of `AutomatedTesting`, `UserTesting`, `Floonet`, `Mainnet` for key `server.chain_type`', src/bin/grin.rs:128:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Onefox** [comment]
Reset your .grin folder, your Server config is not up to date there.

In the error it even states that your chain type is wrong within your config.
We are on Floonet now.

**Comment by vanities** [comment]
Thank you!

Ran `rm -rf ~/.grin` and it worked again. I suppose I could have just edited that line to fix it.
