### ISSUE TITLE
Transaction output not showing up correctly in the wallet

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#2248]
I did a file-based transaction yesterday and after finalizing it nothing started showing up in `grin wallet outputs`. The transaction I sent wasn't showing up in `grin wallet txs` either (only the initial tx where I got the money from a faucet and the change tx which is constructed during `grin wallet send` were showing up). I had to do a `grin wallet restore` which essentially nuked my tx log (only the change output tx shows up now), in order to see my change output show up in `grin wallet outputs`.

@yeastplume

**Comment by yeastplume** [comment]
I don't think there's much point in leaving this open, given I can't reproduce this (i.e. file base transactions seem to work fine when I test them) and there's no further detail on conditions that caused this. If something similar happens again, please feel free to report another issue with as much information on how to reproduce as you can.
