### ISSUE TITLE
Sync when a new peer advertises more work

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#226]
If a new peer initiates a connection once we're already fully synced, and said peer advertises more work than we have, we should sync with that peer as it's likely it has a winning fork. This should be done cautiously by checking the work on the header chain first to avoid liars.

**Comment by ignopeverell** [comment]
Note that this would happen as well in case of a fork for which we missed the losing side (because of temporary bad connectivity for example).

**Comment by antiochp** [comment]
Do we want to keep a sync process running in the background that checks for peers with more work?
I was playing around with this on a branch and realized that `most_work_peer` is a one-shot kind of thing. We only get the `total_difficulty` on initial connection and this is almost immediately stale.

If we implement `ping/pong` to keep connections open - is this maybe a good place to keep the `total_difficulty` of our peers updated? i.e. refresh this on every `ping/pong`?
That way we have an up to date view of `total_difficulty` across all our peers (and we would know if we get our of sync for whatever reason).

**Comment by ignopeverell** [comment]
Sounds like a good plan. Also means sync would finish but still keep running in the background to resume if it detects a growing lateness.

**Comment by antiochp** [comment]
Related- #350. This gives us peer total_difficulty at a regular interval so we can at least determine if we are behind and need to catch up via a sync (or similar).

**Comment by ignopeverell** [comment]
Fixed by a mix of #350 and #389.
