### ISSUE TITLE
Grin wallet recover fails with IO error - Mac OSX

### ISSUE THREAD

**Issue by phreaknik** [mimblewimble/grin#2279]
Hello all,

I am having an issue recovering my wallet using the seed phrase. I get an IO error, as can be seen below.

```
> $ grin --floonet wallet recover -p "word word word word word word word word word word word word word word word word word word word word word word word word"
Please provide a new password for the recovered wallet
Password:
Confirm Password:
20190102 14:07:33.230 ERROR grin_wallet::command - Error recovering seed with list 'word word word word word word word word word word word word word word word word word word word word word word word word' - IO error
Wallet command failed: IO error
```

I just rebuilt the latest grin v0.5.0 on Mac OSX. Any idea what this IO error relates to?

**Comment by ignopeverell** [comment]
Before recover, try to:

1. Run `grin --floonet wallet init`
2. Delete `~/.grin/floo/wallet_data/wallet.seed`

**Comment by phreaknik** [comment]
Ahh, indeed that worked. Thanks for your help.

Would it be worth automating that as part of the recovery process?

**Comment by Onefox** [comment]
I would also love to skip the init step, or give the init subcommand a recovery option.

**Comment by Onefox** [comment]
fixed with
https://github.com/mimblewimble/grin/pull/2330
