### ISSUE TITLE
Test evolution of target with multiple peers mining at different rates

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#23]
We have a test case (https://github.com/ignopeverell/grin/blob/f067e18644d1125159dfb3b48891ccdd7dddc282/grin/tests/simulnet.rs) that simulates 5 peers connecting to each other and one mining a block to check propagation. Expand this to multiple server instances mining in parallel at different rates and check the evolution of the difficulty target.

**Comment by yeastplume** [comment]
Hello there! I'd like to start contributing, but being new to Rust I'd like to start somewhere where I can do minimal damage while learning both the language and the code base.

The test in simulnet.rs seems quite out of date at the moment. What I'm proposing to do is refactor it to provide a bit of a library to perform common operations such as starting/stopping servers, running wallet servers and connecting to peers. Each server instance would run in its own 'container', i.e. its own directory with its own database and/or wallet files, with parameters denoting whether it should mine, run a wallet server, etc. So for instance, it should be possible quickly write a test that performs a 'Alice runs a wallet than starts a server in mining mode then Rebecca starts a server... etc... ' such as the process that was detailed in the last update mail, and check the results in the server container. These helpers can also be expanded as the code evolves, to send/receive transactions, etc..

**Comment by ignopeverell** [comment]
That would be a great way to start!

**Comment by yeastplume** [comment]
The latest commit into PR 66 has a test now that does this, with all of the changes/additions to port configurations needed to support this. At the moment it doesn't actually check for anything and tests aren't really meant to output, but it's handy to watch the mining difficulty evolution in the debug log. There are a lot of changes built up in there to support all of this, so please let me know if anything in there is no good/should be modified or put elsewhere in the code.

**Comment by yeastplume** [comment]
I think with the last PR #69 this is pretty well covered. The test 'simulate_parallel_mining' can easily be tweaked to play with difficulty adjustment parameters. The default params in there are just to allow for CI tests to pass, it's obviously a test to tweak and run manually. But I'm definitely able to run it for 5 or more simulated server threads on a new blockchain, then watch the difficulty start to adjust appropriately.

**Comment by ignopeverell** [comment]
This has been tested and even more covered by testnet1.
