### ISSUE TITLE
wallet info should show the total in the wallet

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#230]
* We should show some summary info for the wallet 
  * `Unspent` + non-coinbase `Unconfirmed`
  * show `Locked` summary?
* Might be nice to hide `Spent` outputs by default (flag to optionally include them in?)
* Bonus points for fixed width columns in the output of `wallet info`
* default units to display amounts in?

**Comment by yeastplume** [comment]
I've added the capability to display amount in grins just recently, but I think perhaps we may want the current wallet info output (i.e. a simple list of outputs) to be 'verbose' or even debug mode and accessible via a flag, and the default output should become a much simpler friendly user-facing summary, like what a typical user would see in the nice GUI.. i.e. total amount, how much of it is unconfirmed, and perhaps a just a summary of the last few transactions?

**Comment by antiochp** [comment]
@yeastplume that's exactly what I was thinking.
Maybe there could be -
* `wallet info`
* `wallet outputs`

**Comment by yeastplume** [comment]
Yes, I think that makes sense.. the wallet info should just be a few lines of summary information.

**Comment by yeastplume** [comment]
This is all in place now.

**Comment by antiochp** [comment]
Looks awesome! :+1:
