### ISSUE TITLE
TUI display negative blocks during sync

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#2309]
Just a display bug that shows -1...-100 blocks in Mining tab during sync.
<img width="1675" alt="capture d ecran 2019-01-06 a 23 15 52" src="https://user-images.githubusercontent.com/11842328/50748808-210cbf80-1209-11e9-8b40-206c79bfdc50.png">

**Comment by yeastplume** [comment]
That's as intended, those are faked 'pre-genesis' blocks used as the starting input to the difficulty calculation for the first 60 blocks. They'll disappear from the TUI very quickly after launch

**Comment by quentinlesceller** [comment]
Okay thanks for the clarification. Closing.
