### ISSUE TITLE
Grin server does not read config file when passing `--config_file` flag

### ISSUE THREAD

**Issue by haarts** [mimblewimble/grin#2317]
When starting grin with: `./target/debug/grin --floonet server --config_file /tmp/grin-server.toml run` the config file pointed to with the `--config_file` flag is ignored. Instead the on in `~/.grin/floonet/grin-server.toml` is read.

Curiously when changing directory to `/tmp` and re-running the command the file *is* correctly read.

## versions

Rust: 1.31.1
Grin version: 27801f6a93f8a4bf5defc9eacd86b6bfb1464923
OS: Ubuntu 18.10

**Comment by Onefox** [comment]
I have the same problem when running:
`grin server --config_file=~/xxx/privateTest/grin-server.toml`
With
`chain_type = "AutomatedTesting"``

I am getting: `Mainnet not ready yet! In the meantime run 'grin --floonet ...'`

**Comment by kargakis** [comment]
> `chain_type = "AutomatedTesting"`
> 
> I am getting: `Mainnet not ready yet! In the meantime run 'grin --floonet ...'`

This looks like a separate issue. Mind opening a new one?

**Comment by Onefox** [comment]
Sure, but I guess If the config is not loaded over all the value isn't read anyway :D 

I mean you get the same error if you run:
`grin server --config_file=~/xxx/privateTest/grin-server.toml`

With 
`chain_type = "Floonet"`
In the config...

**Comment by kargakis** [comment]
Sorry, I need more coffee. :)

**Comment by haarts** [comment]
I've studied the code a bit and I'm certain Michalis issues is different.
Michalis you need to add that parameter no matter what. It is one of the
first things checked.

Regarding my issue; the parameter is never used. There are two places the
code looks for the config file. In the directory grin is started and in
grins home directory (usually ~/.grin).
I believe I can fix this, but it requires some work.

I propose the following solution:
1. Grab the hardcoded default config.
1. Overwrite it with one of the supplied configs in this order of
precedence, command line flag, local sir, home for.
1. Overwrite further with command line flags like '--port' etc.

I could be convinced that you first need to generate a config (there is
already a command for that).

**Comment by kargakis** [comment]
If by "overwrite" you mean "merge" then I don't think this is a good idea. Most CLI tools that I have worked with are doing something like the following:
1. Accept config via a flag or an env variable (stomps everything else)
2. If no config is provided via flag/env, use a pattern where you read from someplace in `$HOME` (default - new users who don't need to care about configs can have their own generated here - already the case in Grin).

Grin is also reading from $PWD as a step 0 (I think). I guess we can still keep it around but I don't expect this is going to be used much in mainnet deployments.

**Comment by sesam** [comment]
I tried `cargo run --release -- --floonet server --config_file=~/.bashrc run` and it sure does seem to ignore the config param.

This is a [helpwanted] and [goodfirstissue] I'm quite sure.

**Comment by haarts** [comment]
@kargakis I agree. But how should we handle the server flags `--api_port` etc?
