### ISSUE TITLE
block notify for pool operators, etc.

### ISSUE THREAD

**Issue by russkidooski** [mimblewimble/grin#2321]
currently anyone that needs a block notify service has to continuously poll the grin node, if we had something like ZMQ to do notifications it would be nice.

**Comment by bladedoyle** [comment]
Note:   Similar to https://github.com/mimblewimble/grin/issues/2538

**Comment by kargakis** [comment]
@russkidooski this issue can be closed now that we have webhooks

**Comment by quentinlesceller** [comment]
Closing. Fixed by 
https://github.com/mimblewimble/grin/pull/2598.
