### ISSUE TITLE
Node fails to build block

### ISSUE THREAD

**Issue by nitronick600** [mimblewimble/grin#2327]
After a clean sync, I attempt to `getnewjobtemplate` 

20190110 06:49:20.589 DEBUG grin_servers::mining::mine_block - get_coinbase: BlockFees { fees: 0, height: 17846, key_id: Some(Identifier(030000000000000000000058ad00000000)) }
20190110 06:49:20.599 WARN grin_servers::mining::mine_block - Error building new block: Core(Transaction(Secp(InvalidRangeProof))). Retrying.
20190110 06:49:20.799 DEBUG grin_servers::mining::mine_block - get_coinbase: BlockFees { fees: 0, height: 17846, key_id: Some(Identifier(030000000000000000000058ae00000000)) }
20190110 06:49:20.808 WARN grin_servers::mining::mine_block - Error building new block: Core(Transaction(Secp(InvalidRangeProof))). Retrying.
20190110 06:49:21.011 DEBUG grin_servers::mining::mine_block - get_coinbase: BlockFees { fees: 0, height: 17846, key_id: Some(Identifier(030000000000000000000058af00000000)) }
20190110 06:49:21.018 WARN grin_servers::mining::mine_block - Error building new block: Core(Transaction(Secp(InvalidRangeProof))). Retrying.

This never repairs. This is from master at commit #5915580ab372dd85c0cc615d9df1c9aa6329f0f0

**Comment by yeastplume** [comment]
Please feel free to open again if this is still an issue on mainnet
