### ISSUE TITLE
Owner API port should be configurable

### ISSUE THREAD

**Issue by alesito85** [mimblewimble/grin#2328]
Currently it only listens on 13420 without the possibility to change unless one changes source and compiles.

**Comment by quentinlesceller** [comment]
You mean you'd like to be able to change the owner api from local 13420 to local another port?

**Comment by yeastplume** [comment]
This is intentional, see https://github.com/mimblewimble/grin/pull/1867

**Comment by quentinlesceller** [comment]
@yeastplume It seems like @alesito85 wanted to change *only* the API port and not the address? Which should be fine?

**Comment by yeastplume** [comment]
Yes, sorry, I read too hastily.

**Comment by alesito85** [comment]
As @quentinlesceller said, I'd like to configure just the port.

**Comment by ignopeverell** [comment]
Fixed by #2405
