### ISSUE TITLE
Error receiving grin coins via gringod

### ISSUE THREAD

**Issue by kalderonski** [mimblewimble/grin#2343]
I configured a node in google cloud and it's running ok as weel as the wallet.
When I try to receive some coins for testing using 

**curl gringod.info**

The following error appears

20190111 13:48:32.448 WARN grin_wallet::controller - Starting HTTP Foreign listener API server at 0.0.0.0:13415.
20190111 13:48:32.448 WARN grin_wallet::controller - HTTP Foreign listener started.
20190111 14:02:26.172 ERROR grin_wallet::controller - Request Error: Error { inner: stack backtrace:
   0:     0x55ee7576cebd - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x55ee7576b872 - backtrace::capture::Backtrace::new_unresolved::h6420b09e7b3c3878
   2:     0x55ee7576b3d1 - failure::backtrace::internal::InternalBacktrace::new::h66a13f523e857bc2
   3:     0x55ee7576af41 - <failure::backtrace::Backtrace as core::default::Default>::default::h32c8f0022b7e0500
   4:     0x55ee7576af99 - failure::backtrace::Backtrace::new::h220fff5d4e7a5d89
   5:     0x55ee7524e026 - <futures::future::chain::Chain<A, B, C>>::poll::h2642004938758cbe
   6:     0x55ee75254c88 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::ha63f4d9ada1eaceb
   7:     0x55ee75252dab - <futures::future::chain::Chain<A, B, C>>::poll::heda79db1f31522a4
   8:     0x55ee75254c78 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h262886fdff34b6ab
   9:     0x55ee75252396 - <futures::future::chain::Chain<A, B, C>>::poll::ha40c592ed840d1ae
  10:     0x55ee75254c98 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::haa5d7a0c13037bc6
  11:     0x55ee7524d1d5 - <futures::future::chain::Chain<A, B, C>>::poll::h26283cd0a49f9576
  12:     0x55ee7524f609 - <futures::future::chain::Chain<A, B, C>>::poll::h30cbef724c423d99
  13:     0x55ee751d7408 - <futures::future::or_else::OrElse<A, B, F> as futures::future::Future>::poll::h7e1face35118e3e2
  14:     0x55ee753b5a9d - <hyper::proto::h1::dispatch::Server<S> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::hd9667829b2e2df8c
  15:     0x55ee753c5345 - <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, T>>::poll_catch::h9bec0d1763edd6cd
  16:     0x55ee753b10bc - <futures::future::either::Either<A, B> as futures::future::Future>::poll::hd8019175698419b0
  17:     0x55ee75351f56 - <hyper::server::conn::upgrades::UpgradeableConnection<I, S, E> as futures::future::Future>::poll::h061e74f91082e1d5
  18:     0x55ee753cb3da - <hyper::server::conn::spawn_all::NewSvcTask<I, N, S, E, W> as futures::future::Future>::poll::hb759278e6e27826c
  19:     0x55ee75561ea1 - futures::task_impl::std::set::h521a3d2374a440d6
  20:     0x55ee75562aa5 - <futures::task_impl::Spawn<T>>::poll_future_notify::he9293aa99e72ff1a
  21:     0x55ee755662f0 - std::panicking::try::do_call::heae2c4c5c175dbd7
  22:     0x55ee7584fed9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  23:     0x55ee7556430b - tokio_threadpool::task::Task::run::hf017a34211692719
  24:     0x55ee7555c8e5 - tokio_threadpool::worker::Worker::run_task::h9173a849f036d796
  25:     0x55ee7555bd7d - tokio_threadpool::worker::Worker::run::h6443426a4416c449
  26:     0x55ee755466f5 - <std::thread::local::LocalKey<T>>::with::he1e004e3c79fc93f
  27:     0x55ee75546531 - <std::thread::local::LocalKey<T>>::with::hc3d03d9e0836f5da
  28:     0x55ee755462c8 - <std::thread::local::LocalKey<T>>::with::h0b1867339e66ccd4
  29:     0x55ee7554a555 - tokio::runtime::builder::Builder::build::{{closure}}::h730952323b1ebdba
  30:     0x55ee755635dc - <std::thread::local::LocalKey<T>>::with::h7d6474b3e153e51e
  31:     0x55ee75563741 - <std::thread::local::LocalKey<T>>::with::h8692b8aadc1059b8
  32:     0x55ee75566c2b - std::sys_common::backtrace::__rust_begin_short_backtrace::hf45fa12c3af79a37
  33:     0x55ee755662ab - std::panicking::try::do_call::h576b070b1292f8e2
  34:     0x55ee7584fed9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  35:     0x55ee75560d5f - <F as alloc::boxed::FnBox<A>>::call_box::h1742cf45920d262b
  36:     0x55ee7583a3bd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  37:     0x55ee75825735 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  38:     0x7f13bacc8493 - start_thread
  39:     0x7f13ba7f3ace - __clone
  40:                0x0 - <unknown>

Generic error: Invalid request body: unknown variant `bits`, expected `Plain` or `Coinbase` at line 1 column 240 }

**Comment by hashmap** [comment]
sounds like the faucet needs to be updated

**Comment by kalderonski** [comment]
Any instructions on how to do it?
