### ISSUE TITLE
Failed to validate share: Endpoints don't match up

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#2345]
We've been receiving this error from time to time (1/2000 shares).
Attaching a screen cap of the error, error is the following:
```
Error grin_servers;;mining::stratumserver ) (Server ID: 0) Failed to validate share at height 19168, hash 69df4f63, edge_bits 29, nonce 10929610044244915274, job_id 0. Err(Error { inner: 

Verification Error: endpoints don't match up }).
```

<img width="602" alt="capture d ecran 2019-01-10 a 23 21 07" src="https://user-images.githubusercontent.com/11842328/51043728-67f21080-158d-11e9-85cb-f8938fb40b32.png">

**Comment by hashmap** [comment]
It may be an issue with OpenCL solver, I see 1% rejections, but no point to solve it now, opencl code is being updated while we speak

**Comment by perezzloy** [comment]
This problem appeared in 3.0.0-beta.2 version. Here is my log:
`20191222 01:48:05.449 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0834a8f843ba198cb327d39dd3fbb8d33eccca75bbb26114dc9a5d1c4bd9d6a0d5 with     error Not found.
20191222 02:13:15.683 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Failed to validate share at height 487904, hash 03224009eae4, edge_bits 29, nonce 9827211212805590523, job_id 8. Err(Error { inner: Verification Error: endpoints don't match up })
wallet, server latest
@.Hardman Here are the records still there
This is Grin version 3.0.0-beta.2 (git v3.0.0-beta.2)`
and below repeats the following:
`20191222 06:57:04.665 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488169, edge_bits 29, nonce 1338988558841567891, job_id 0 submitted too late │
│                  ││ 20191222 06:58:35.837 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488171, edge_bits 29, nonce 5202105070846523904, job_id 2 submitted too late │
│                  ││ 20191222 06:59:04.306 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488172, edge_bits 29, nonce 7944335165563617279, job_id 1 submitted too late │
│                  ││ 20191222 07:00:34.376 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488175, edge_bits 29, nonce 1370264695374707709, job_id 1 submitted too late │
│                  ││ 20191222 07:04:58.485 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488183, edge_bits 29, nonce 2168162781659945857, job_id 0 submitted too late │
│                  ││ 20191222 07:22:09.708 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Share at height 488203, edge_bits 29, nonce 17500826794336612818, job_id 1 submitted too     │
│                  ││ late`

**Comment by quentinlesceller** [comment]
This is an invalid share.

**Comment by M-Adeel-Danish** [comment]
I am a newbie, running a synced node on the local machine. I couldn't find a way around this problem. No share is accepted from the miner. Can you explain what could go wrong?

![image](https://user-images.githubusercontent.com/26748478/73655639-47bd5400-46b0-11ea-8bfd-00f7d8c77d79.png)

![image](https://user-images.githubusercontent.com/26748478/73655713-67547c80-46b0-11ea-9480-24e6c2018de8.png)

**Comment by jaspervdm** [comment]
You are using the cuckarood plugin, but should be using cuckaroom

**Comment by M-Adeel-Danish** [comment]
Thank you very much for help. I am currently finding "cuckaroom" plugin, apparently, it is not included in official releases. Also, our rigs are CPU based, so kindly can you guide which plugin is most suitable?

**Comment by quentinlesceller** [comment]
Hi @M-Adeel-Danish, I don't think there is any CPU solver currently available.

**Comment by M-Adeel-Danish** [comment]
Thank you @quentinlesceller, that was a surprise though. If we shift on GPUs, which algo/plugins are supported on the latest grin release other than cuckaroom?

**Comment by M-Adeel-Danish** [comment]
Thanks a lot, it is working now. These algorithms are working **CuckaroomC29, CuckatooC31, CuckatooC32**.
