### ISSUE TITLE
Error while compiling GRIN wallet. error: Edition 2018 is unstable and only available for nightly builds of rustc. 

### ISSUE THREAD

**Issue by black-phillip616** [mimblewimble/grin#2346]
Ive had the wallet up and running before, i dont know why this error keeps happening, ive tried a few suggestions from grin discord with no avail. Ive seen a similar issue #2102 and have tried those fixes with no avail. here is the readout of the error. oh also i have tried `rustup install nightly` and `rustup default nightly` commands with no avail. 
 
`` error: Edition 2018 is unstable and only available for nightly builds of rustc. ``
                                                                                
 `` error:Could not compile zeroize                                          
warning: build failed, waiting for other jobs to finish...
error: build failed ``
this output is after running command ``  sudo cargo build --release ``
also after i `` curl https://sh.rustup.rs/ -sSf | sh; source $HOME/.cargo/env ``
is still have to manually install cargo via `` sudo apt-get install cargo `` not sure if that has anything to do with this as well
Thanks

**Comment by mattselkey** [comment]
thanks, I had the exact same issue and you saved me a lot of time working out why.

**Comment by texalex** [comment]
gracias, did the tricks :)
