### ISSUE TITLE
"v1/wallet/owner/retrieve_txs?refresh&tx_id="    api not work, return all tx to my

### ISSUE THREAD

**Issue by BeyongSpringWater** [mimblewimble/grin#2350]
![image](https://user-images.githubusercontent.com/6032172/51070262-55ed9c00-1679-11e9-8a78-f6fc8b28b506.png)

curl http://grin:O6eX6D3rq80oz4jejPss@localhost:13420/v1/wallet/owner/retrieve_txs?refresh&tx_id="e75b30aa-84e0-4031-9e6c-313eaa6af156"

[true,[{"parent_key_id":"0200000000000000000000000000000000","id":0,"tx_slate_id":"0eb346e6-1c03-42fd-8743-66c070184e95","tx_type":"TxReceivedCancelled","creation_ts":"2019-01-09T10:44:40.849173Z","confirmation_ts":null,"confirmed":false,"num_inputs":0,"num_outputs":1,"amount_credited":100000000000,"amount_debited":0,"fee":null,"stored_tx":null},{"parent_key_id":"0200000000000000000000000000000000","id":1,"tx_slate_id":"35485512-cfe6-4ebc-aa18-cfedb80b41cf","tx_type":"TxReceivedCancelled","creation_ts":"2019-01-09T10:44:51.734867Z","confirmation_ts":null,"confirmed":false,"num_inputs":0,"num_outputs":1,"amount_credited":10000000000,"amount_debited":0,"fee":null,"stored_tx":null},{"parent_key_id":"0200000000000000000000000000000000","id":2,"tx_slate_id":null,"tx_type":"TxReceived","creation_ts":"2019-01-09T12:26:21.967809Z","confirmation_ts":"2019-01-09T12:26:21.967810Z","confirmed":true,"num_inputs":0,"num_outputs":1,"amount_credited":10000000000,"amount_debited":0,"fee":null,"stored_tx":null},{"parent_key_id":"0200000000000000000000000000000000","id":3,"tx_slate_id":"abdd5e9e-1101-43f3-980e-9b8138d4089e","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T07:09:10.621549Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"abdd5e9e-1101-43f3-980e-9b8138d4089e.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":4,"tx_slate_id":"604b966f-6168-45d7-ad4b-42815a0faeda","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T07:29:24.353262Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"604b966f-6168-45d7-ad4b-42815a0faeda.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":5,"tx_slate_id":"604b966f-6168-45d7-ad4b-42815a0faeda","tx_type":"TxReceivedCancelled","creation_ts":"2019-01-10T07:32:13.164071Z","confirmation_ts":null,"confirmed":false,"num_inputs":0,"num_outputs":1,"amount_credited":1000000000,"amount_debited":0,"fee":null,"stored_tx":null},{"parent_key_id":"0200000000000000000000000000000000","id":6,"tx_slate_id":"292eac26-9fbf-45d7-a2b0-e06d8b652aaa","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T07:51:07.932597Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"292eac26-9fbf-45d7-a2b0-e06d8b652aaa.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":7,"tx_slate_id":"292eac26-9fbf-45d7-a2b0-e06d8b652aaa","tx_type":"TxReceivedCancelled","creation_ts":"2019-01-10T07:52:42.141879Z","confirmation_ts":null,"confirmed":false,"num_inputs":0,"num_outputs":1,"amount_credited":1000000000,"amount_debited":0,"fee":null,"stored_tx":null},{"parent_key_id":"0200000000000000000000000000000000","id":8,"tx_slate_id":"22b7b9d5-02f7-428f-b757-80051772f636","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T08:28:52.565036Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"22b7b9d5-02f7-428f-b757-80051772f636.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":9,"tx_slate_id":"6887e37b-6cba-4aae-9825-c4f5ad8d9854","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T09:28:15.002765Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"6887e37b-6cba-4aae-9825-c4f5ad8d9854.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":10,"tx_slate_id":"7dd94c51-644e-494c-bc86-5f2dc03c8f78","tx_type":"TxSentCancelled","creation_ts":"2019-01-10T11:54:01.811626Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":8956000000,"amount_debited":10000000000,"fee":44000000,"stored_tx":"7dd94c51-644e-494c-bc86-5f2dc03c8f78.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":11,"tx_slate_id":"e75b30aa-84e0-4031-9e6c-313eaa6af156","tx_type":"TxSent","creation_ts":"2019-01-11T03:48:07.084987Z","confirmation_ts":"2019-01-11T05:41:27.655135Z","confirmed":true,"num_inputs":1,"num_outputs":1,"amount_credited":8992000000,"amount_debited":10000000000,"fee":8000000,"stored_tx":"e75b30aa-84e0-4031-9e6c-313eaa6af156.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":12,"tx_slate_id":"106e889f-283d-48af-92c5-a342c6dfdaad","tx_type":"TxSentCancelled","creation_ts":"2019-01-11T05:44:25.496803Z","confirmation_ts":null,"confirmed":false,"num_inputs":1,"num_outputs":10,"amount_credited":7948000000,"amount_debited":8992000000,"fee":44000000,"stored_tx":"106e889f-283d-48af-92c5-a342c6dfdaad.grintx"},{"parent_key_id":"0200000000000000000000000000000000","id":13,"tx_slate_id":"c3220489-c145-4e04-bb19-9f981e9bccf3","tx_type":"TxSent","creation_ts":"2019-01-11T09:56:06.798267Z","confirmation_ts":"2019-01-11T10:26:03.227811Z","confirmed":true,"num_inputs":1,"num_outputs":1,"amount_credited":7984000000,"amount_debited":8992000000,"fee":8000000,"stored_tx":"c3220489-c145-4e04-bb19-9f981e9bccf3.grintx"}]]

**Comment by yeastplume** [comment]
You need to use the database transaction ID, not the slate UUID e.g. "id":13" above

**Comment by sven20181031** [comment]
@yeastplume How can I query txs using the slate UUID not the local transactionID?
or How can I get the local transaction ID using the slate UUID? 
now, I know the slate UUID and I want to query a tx related to this UUID by HTTP API, what should I do?
thanks.
