### ISSUE TITLE
txhashet filenames currently ending in ...

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2351]
Related - #2325 

Looks like we inadvertently included the nice pretty `...` in the block hash string itself... (and not just in the UI).

* displayed/used block hash should be 12 digits long
* UI is free to add `...` to the end, but this should not be used in the filename (obviously)

Lets be more careful with seemingly innocuous changes like this in the future. We should have considered any and _all_ usage of block.hash() here and clearly missed one, and probably other uses.

**Comment by garyyu** [comment]
Closed by #2355
