### ISSUE TITLE
Cannot print address?

### ISSUE THREAD

**Issue by iljah** [mimblewimble/grin#2363]
https://github.com/bisq-network/bisq/pull/2217 shows examples of grin (not IP) addresses but it doesn't seem to be possible to obtain those from command line client. For example https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet doesn't mention (grin) addresses at all. How can I see my address after running `grin wallet init`?

**Comment by lehnberg** [comment]
The commit (https://github.com/bisq-network/bisq/pull/2217/commits/05f6c87e4ce7119c700d82826314709321fad8e4) adds grinbox addresses. Grinbox support is not yet integrated in the default wallet, but is working with https://github.com/vault713/wallet713.

**Comment by mably** [comment]
@iljah You don't need to know your Grin address as there is no Grin address.  But you need to have grinbox address.  Check https://grinbox.io to know how to get one.

**Comment by iljah** [comment]
So is it impossible to buy/sell grin over bisq by using just github.com/mimblewimble/grin ? If yes, is this temporary? Your should probably also check out https://github.com/bisq-network/bisq/issues/2261

**Comment by mably** [comment]
Yes, it's impossible at the moment and will probably stay like that for some time to come.

You might have to wait until vault713 supports Tor: https://github.com/vault713/wallet713/issues/44

**Comment by lehnberg** [comment]
@iljah if you use the open source [wallet713](https://github.com/vault713/wallet713), you will have a grinbox address. Your IP would be exposed to the grinbox relay (unless you use a VPN of course), but it would not be exposed "to everyone using bisq". The only thing you reveal to bisq users is your grinbox address. Feel free to drop in to our dedicated [Gitter chat]( 
https://gitter.im/vault713/wallet713) if you like, happy to answer more questions.

**Comment by mably** [comment]
@lehnberg can Keybase be used to hide our IP address with wallet713?

**Comment by lehnberg** [comment]
@mably using keybase means the grinbox relay does not see your IP, but instead the keybase servers do. So it’s essentially the same thing, and a question of which service the users trust most with their IP.

**Comment by mably** [comment]
Ok, it looks like Keybase can be used with Tor, but I guess the grin wallet keybase plugin is not configured to use it though.

**Comment by iljah** [comment]
Thanks, guess I'll have to take a look at 713.

**Comment by mickaphd** [comment]
@lehnberg Do you know if any binaries are scheduled for wallet713 (for the noobs like me!)? Thanks

**Comment by lehnberg** [comment]
@mickaphd we'll try to provide, but no promises! you can track progress in https://github.com/vault713/wallet713/issues/61

**Comment by mickaphd** [comment]
Thanks much! And good luck for next week ;-)

**Comment by yeastplume** [comment]
Answered
