### ISSUE TITLE
Send/check unscaled minimal share difficulty in stratum server

### ISSUE THREAD

**Issue by bmhjyu** [mimblewimble/grin#2369]
Currently the stratum server is sending/checking the scaled minimal share difficulty. This is actually not convenient as only sending the unscaled one for both stratum servers & miners. Miners have to extract the secondary scaling or calculate the graph weight to be applied to the hash result. I would recommend sending/checking against the unscaled difficulty instead.

**Comment by sesam** [comment]
@bladedoyle @quentinlesceller thoughts?

**Comment by NaN-git** [comment]
I think that it would be necessary to extend the stratum protocol. Right now the share difficulty is just useless because miners can't easily find the value of the secondary scaling factor.
Either the scaling factor is directly added to each job/getjobtemplate message or two difficulties need to be send, but this would break compatibility.

**Comment by NaN-git** [comment]
A single difficulty works, but it's not good because the expected hash rate of one miner is very different for cuckaroo29 and cuckatoo31+. Therefore a pool would want to change the difficulties of the two algorithms independently, so that the share rate of both algorithms is roughly the same.

**Comment by bmhjyu** [comment]
I think there are some misunderstandings here. Right now the difficulty in stratum is actually means the difficulty after scaling. When a miner submit a share to the stratum server, the node calculates the blake2b hash of proofs, applies the secondary scaling or graph weight, and compares it with the difficulty it sends in the job to determine whether the share is accepted. Here I am proposing is send the UNSCALED difficulty. In this case the scaling in this process is eliminated and this applies to both algorithms.

**Comment by NaN-git** [comment]
I understood you. My argument still applies.

**Comment by bmhjyu** [comment]
Well a properly designed pool does not work like that. It usually sets an initial difficulty and an expected share submission interval. If the miner submits faster than expectation, it increases the difficulty and vice versa. The process is applied as "session" level, i. e. different miner-pool connection would have separate difficulty control. In this case the algorithm does not matter any more. The only thing matters is the hash rate.

**Comment by NaN-git** [comment]
The difficulty adjustment takes some time and the hash rates of the two algorithms differ by an order of magnitude, i.e. it's more difficult to find a sane default for both algorithms.

**Comment by bmhjyu** [comment]
Well the adjustment is not really taking much time, if the adjustment is implemented well enough. For example exponential increases actually works well.

**Comment by yeastplume** [comment]
Fixed in grin-miner 1.0.2

**Comment by bmhjyu** [comment]
> Fixed in grin-miner 1.0.2

I think in grin server we are still checking scaled one.
