### ISSUE TITLE
Thread 'main' panicked with message: "called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

### ISSUE THREAD

**Issue by h1-cwc** [mimblewimble/grin#2381]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': libcore/result.rs:1009stack backtrace:
   0:     0x5567004ea0bd - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x5567004e92d2 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x5567004e9349 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x556700472f50 - grin_util::logger::send_panic_to_log::{{closure}}::h9dfd05e2f10c03c7
   4:     0x5567005bab46 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x5567005ba691 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x5567005ba575 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5567006045ec - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x5566ffd2fdc9 - core::result::unwrap_failed::ha0c3868a9b78e917
   9:     0x5566ffceb030 - grin::cmd::server::start_server::hd08f9d9ce0e1a175
  10:     0x5566ffcebf20 - grin::cmd::server::server_command::hd6ce3947e95b34a1
  11:     0x5566ffd769bd - grin::real_main::hb3cbcedf020dd0fa
  12:     0x5566ffd75445 - grin::main::h6cbf10070b5d4461
  13:     0x5566ffd4ca22 - std::rt::lang_start::{{closure}}::h355f6dda1d0140bb
  14:     0x5567005ba512 - std::rt::lang_start_internal::{{closure}}::hafa8ecdacd368ebb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8c0dbb48abbdf4df
                        at libstd/panicking.rs:310
  15:     0x5567005ccbe9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  16:     0x55670059bd6a - std::panicking::try::hbc21637ba5f64d73
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h954917b922b8d970
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h5b2de3cc38c3b406
                        at libstd/rt.rs:58
  17:     0x5566ffd779e4 - main
  18:     0x7faf5c7cc82f - __libc_start_main
  19:     0x5566ffcb82c0 - <unknown>
  20:                0x0 - <unknown>

Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })"
See /home/grin-server/.grin/floo/grin-server.log for further details.

**Comment by hashmap** [comment]
closing as a duplicate
