### ISSUE TITLE
Nodes should maintain healthy mix of inbound/outbound peers

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2394]
Node running overnight configured with `peer_max_count = 100`.
* 1 outbound peer
* 99 inbound peers

We need a healthy number of outbound peers for Dandelion to function correctly as we choose a relay from our outbound peers.

I'm assuming that given the number of nodes on the network, all creating connections we have an imbalance here - 
* we (a single node) try to create outbound connections
* many other nodes try to create inbound connections to us

And as connections drop over time (for a variety of reasons) chances are our connection "slots" get grabbed by other nodes connecting to us and not by us connection to other nodes.

So our number of outbound connections grows smaller over time.

Is this because new nodes are coming online over time?

Is this because many nodes are behind NAT and not able to accept inbound connections leading to this imbalance on "open" nodes?

**Comment by antiochp** [comment]
We have the following config by default -
```
peer_min_preferred_count = 8
```

I wonder if this is as simple as checking the number of outbound peer connection in `monitor_peers` and keeping _this_ number above `peer_min_preferred_count` (instead of the total number of connected peers currently).

https://github.com/mimblewimble/grin/blob/8badb58665a9f9056599d59a5d76d3a92660706f/servers/src/grin/seed.rs#L189-L192

**Comment by ignopeverell** [comment]
Seems like a nice enough solution. Keep in mind your stats may be really skewed due to the recent release however.

**Comment by antiochp** [comment]
Will watch nodes over the next few days to see how they behave.

Pretty consistently seeing nodes lose all their outbound connections over a few hours though right now, with them being replaced by a ready stream of inbound connections.

Same node went from 18 outbound, 24 inbound after a restart, to 1 outbound, 99 inbound after approx 3 hours.

**Comment by lumirl** [comment]
The same happens with us. Is there any IP list of preferred "main" peers to keep them in config and to have both inbound and outboud connections?

**Comment by antiochp** [comment]
Not currently no - we have "preferred" peers but this only applies during initial node startup. Once we've peered we just (currently) keep the total between the min and max values.

I'll plan to work on making these proposed changes.

**Comment by antiochp** [comment]
Thinking a bit more about this, maybe we can be less invasive here by roughly attempting to maintain a 50/50 split between inbound/outbound peers.

Look for more peers if - 
* `connected_peers < peer_min_preferred_count`, or
* `connected_outbound_peers < peer_min_preferred_count / 2`

This way, using the default min_preferred_count of 8 peers we will attempt to maintain at least 4 outbound connections, opening new connections if we ever drop below this.

**Comment by antiochp** [comment]
Even with the proposed changes we are still seeing an issue here. 

We are getting so many inbound connections on mainnet that we are constantly up against max_peers. At this point we are not even trying to open new connections even after queueing them up.

I think we need to add some headroom to our max connections (still need to think through how to cleanly do this) to allow us some room for creating new connections in this situation.

If any given node has too many incoming connection requests it is not able to reach out and open an outbound connection. There are DDoS/censorship issues here as I suspect it is possible to isolate any given node from the network by flooding it with inbound connections.

**Comment by antiochp** [comment]
Node on mainnet with #2417 to test this out.
Reworked it so we are outbound node aware when trying to connect to addrs in the rx queue (see above).

Early results show the node maintaining some number of outbound connections and trying additional outbound connections over time even when we are at max_peer capacity.

**Comment by antiochp** [comment]
We may want to do something in `serv.rs` when we `check_undesirable()` on a new inbound peer connection as well.
Right now we happily accept connections regardless of how many we currently have (and let seed.rs clean up excess peers).

We may want to treat new peer connections as "undesirable" if we are already in excess of our max peer limit.
