### ISSUE TITLE
Transaction not confirmed

### ISSUE THREAD

**Issue by jochemin** [mimblewimble/grin#2407]
I have a tx unconfirmed for some hours now. My node is synced, I received the transaction file and sent the response file.

The sender also has the tx  unconfirmed.

![image](https://user-images.githubusercontent.com/6348955/51322525-f40ca800-1a65-11e9-83e0-217da8be5c62.png)

**Comment by abrkn** [comment]
Same issue

**Comment by jochemin** [comment]
> Same issue

You are the sender

**Comment by yeastplume** [comment]
Please feel free to ask for further help in the support channel.
