### ISSUE TITLE
Dockerfile doesn't build out directories

### ISSUE THREAD

**Issue by nipponese** [mimblewimble/grin#2410]
```
$ docker build -t grin -f etc/Dockerfile.floonet .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/<username>/etc: no such file or directory
```
Also tried with `sudo` and `etc/Dockerfile .` but didn't work.

Using Ubuntu 18.04 x64
Docker version 18.09.1, build 4c52b90

**Comment by kargakis** [comment]
`/home/<username>/etc`

This error doesn't make much sense I am afraid. Supposedly, you should have something like /home/<username>/grin/etc. Are you sure, you are running the command from the correct directory?

The docker build works fine on my machine (Fedora 28 with docker version 17.05.0-ce).

**Comment by nipponese** [comment]
Yeah, simple fix... I wasn't running it from the grin dir.
