### ISSUE TITLE
Wallet becomes corrupt and will not build a coinbase.

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2412]
MWGrinPool.com was down for a few hours today due to the wallet (becoming corrupt? and) failing to create new coinbase.

I was able to create a new wallet so we are mining again.  But now I have a mess.  My database with transactions data will no longer match the wallet.  Im not even sure all of the impact yet.

In case you are interested, these are the related logs:

```
Starting public wallet listener
20190118 03:50:31.013 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
20190118 03:50:31.014 INFO grin - Using wallet configuration file at /wallet/grin-wallet.toml
20190118 03:50:31.014 INFO grin - This is Grin version 1.0.0 (git v1.0.0-6-g320fc78), built for x86_64-unknown-linux-gnu by rustc 1.31.0 (abe02cefd 2018-12-04).
20190118 03:50:31.014 DEBUG grin - Built with profile "release", features "".
20190118 03:50:31.014 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190118 03:50:31.086 INFO grin_wallet - Using LMDB Backend for wallet
20190118 03:50:31.086 WARN grin_wallet::controller - Starting HTTP Foreign listener API server at 0.0.0.0:13415.
20190118 03:50:31.088 WARN grin_wallet::controller - HTTP Foreign listener started.
20190118 03:51:39.751 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190118 03:51:39.772 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner: 

Wallet store error }

Node API error }
20190118 03:51:44.881 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190118 03:51:44.911 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner: 

Wallet store error }

Node API error }
^C
```

and from the grin-server trying to create a coinbase:
```
20190118 03:38:10.033 ERROR grin_wallet::node_clients::http - Failed to get coinbase from http://grinwallet:13415/v1/wallet/foreign/build_coinbase. Run grin wallet listen? 
20190118 03:38:10.033 ERROR grin_wallet::node_clients::http - Underlying Error: Request error: Wrong response code 
20190118 03:38:10.033 ERROR grin_wallet::node_clients::http - Backtrace:
 20190118 03:38:10.033 ERROR grin_servers::mining::mine_block - Error building new block: Can't connect to wallet listener at "http://grinwallet:13415"; will retry
```

**Comment by bladedoyle** [comment]
I was able to ```grin wallet restore``` and gain access to the mature coins.

**Comment by ignopeverell** [comment]
It might be hard to pinpoint without more details about what led to the corruption. How was the wallet being used?

**Comment by bladedoyle** [comment]
I can share the wallet db I guess.  I transferred all the funds over to a new wallet.

It was being used in a number of ways:
https://github.com/grin-pool/grin-pool/blob/master/ansible/roles/pool/files/grinwallet.yaml

1) Running a public API server - generates coinbases
2) Running a private api server - payments

**Comment by dyzz** [comment]
same error here

`20190120 11:17:10.848 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug                                         
20190120 11:17:10.848 INFO grin - Using wallet configuration file at /root/.grin/main/grin-wallet.toml                                                                 
20190120 11:17:10.848 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).                  
20190120 11:17:10.848 DEBUG grin - Built with profile "release", features "".                                                                                          
20190120 11:17:16.467 WARN grin_wallet::types - Generating wallet seed file at: /root/.grin/main/wallet_data/wallet.seed                                               
20190120 11:17:16.468 INFO grin_wallet::command - Wallet seed file created                                                                                             
20190120 11:17:16.474 INFO grin_wallet::command - Wallet database backend created                                                                                      
20190120 11:22:32.639 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug                                         
20190120 11:22:32.639 INFO grin - Using wallet configuration file at /root/.grin/main/grin-wallet.toml                                                                 
20190120 11:22:32.639 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).                  
20190120 11:22:32.639 DEBUG grin - Built with profile "release", features "".                                                                                          
20190120 11:22:42.290 DEBUG grin_wallet::types - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed                                                   
20190120 11:22:42.295 INFO grin_wallet - Using LMDB Backend for wallet                                                                                                 
20190120 11:22:42.295 WARN grin_wallet::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3415.                                                        
20190120 11:22:42.295 WARN grin_wallet::controller - HTTP Foreign listener started.                                                                                    
20190120 11:23:27.442 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Debug, min. level: Trace                                        
20190120 11:23:27.442 INFO grin - Using wallet configuration file at /root/.grin/main/grin-wallet.toml                                                                 
20190120 11:23:27.442 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).                  
20190120 11:23:27.442 DEBUG grin - Built with profile "release", features "".                                                                                          
20190120 11:23:32.295 DEBUG grin_wallet::types - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed                                                   
20190120 11:23:32.299 INFO grin_wallet - Using LMDB Backend for wallet                                                                                                 
20190120 11:23:32.299 WARN grin_wallet::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3415.                                                        
20190120 11:23:32.299 WARN grin_wallet::controller - HTTP Foreign listener started.                                                                                    
20190120 11:23:35.161 DEBUG grin_wallet::types - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed                                                   
20190120 11:23:35.180 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner:                                                                     

Wallet store error }                                                                                                                                                   

Node API error }                                                                                                                                                       
20190120 11:23:36.171 DEBUG grin_wallet::types - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed                                                   
20190120 11:23:36.198 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner:                                                                     

Wallet store error }                                                                                                                                                   

Node API error }                                                                                                    `

**Comment by yeastplume** [comment]
It would appear useful information for the error is being swallowed by a debug formatter. I have an issue up here to fix that. It might help debug if you could use the latest master or just make this fix in your code base if you're building:

https://github.com/mimblewimble/grin/pull/2448

**Comment by prodigalprotagonist** [comment]
I was able to reproduce this on floonet right now a couple of times by running wallet check while a block is being mined, meaning the last one in the list show by wallet output is in status "Mining"

The message is   

> 20190130 01:07:45.684 WARN grin_wallet::libwallet::internal::restore - Unconfirmed output for 60000000000 with ID 0300000000000000000000001b00000000 (Commitment(096ccbf65ef8da094f1925500dbef141bb35dcc137a259fd6342b4c1e24fdb412f)) not in UTXO set. Deleting and cancelling associated transaction log entries.
20190130 01:07:45.731 WARN grin_wallet::command - Wallet check complete`

and 9 out of 13 outputs are gone when running info again while the node keeps printing

> 20190130 01:18:50.872 ERROR grin_wallet::node_clients::http - Backtrace: 
> 20190130 01:18:50.872 ERROR grin_servers::mining::mine_block - Error building new block: Can't connect to wallet listener at "http://127.0.0.1:13415"; will retry
>20190130 01:18:55.996 ERROR grin_wallet::node_clients::http - Failed to get coinbase from http://127.0.0.1:13415/v1/wallet/foreign/build_coinbase. Run grin wallet listen?
>20190130 01:18:55.996 ERROR grin_wallet::node_clients::http - Underlying Error: Request error: Wrong response code`

And the listener goes

> 20190130 01:19:26.731 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner: 
> 
> Wallet store error }
>
> Node API error }

Now I restarted both node and listener, waited for a bit for the reorg to finish, did check again, and had another output disappear, now only the first 3 are still there, out of 13 originally. This situation persists after moving wallet files aside and doing a restore, check.

This last time floonet seemed to go nuts at the same time and fast-forward a couple hundred in height, from 26264 to 2647 in an instant.

**Comment by dyzz** [comment]
> I was able to reproduce this on floonet right now a couple of times by running wallet check while a block is being mined, meaning the last one in the list shown by wallet output is in status "Mining"
> 
> The message is
> 
> > 20190130 01:07:45.684 WARN grin_wallet::libwallet::internal::restore - Unconfirmed output for 60000000000 with ID 0300000000000000000000001b00000000 (Commitment(096ccbf65ef8da094f1925500dbef141bb35dcc137a259fd6342b4c1e24fdb412f)) not in UTXO set. Deleting and cancelling associated transaction log entries.
> > 20190130 01:07:45.731 WARN grin_wallet::command - Wallet check complete`
> 
> and 9 out of 13 outputs are gone when running info again while the node keeps printing
> 
> > 20190130 01:18:50.872 ERROR grin_wallet::node_clients::http - Backtrace:
> > 20190130 01:18:50.872 ERROR grin_servers::mining::mine_block - Error building new block: Can't connect to wallet listener at "http://127.0.0.1:13415"; will retry
> > 20190130 01:18:55.996 ERROR grin_wallet::node_clients::http - Failed to get coinbase from http://127.0.0.1:13415/v1/wallet/foreign/build_coinbase. Run grin wallet listen?
> > 20190130 01:18:55.996 ERROR grin_wallet::node_clients::http - Underlying Error: Request error: Wrong response code`
> 
> And the listener goes
> 
> > 20190130 01:19:26.731 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner:
> > Wallet store error }
> > Node API error }
> 
> Now I restarted both node and listener, waited for a bit for the reorg to finish, did check again, and had another output disappear, now only the first 3 are still there, out of 13 originally. This situation persists after moving wallet files aside and doing a restore, check.
> 
> This last time floonet seemed to go nuts at the same time and fast-forward a couple hundred in height, from 26264 to 26473 in an instant.

confirmed. I can reproduce on mainnet as well.

**Comment by hashmap** [comment]
Can confirm.
Check finishes with:
```
20190130 12:05:17.939 WARN grin_wallet::libwallet::internal::restore - Identified 11 wallet_outputs as belonging to this wallet
20190130 12:05:19.009 WARN grin_wallet::libwallet::internal::restore - Unconfirmed output for 60000000000 with ID 0300000000000000000000013d00000000 (Commitment(082947993a0652c844f7d51770ac358194a20df6194ab0d5acdddc4bb81f188936)) not in UTXO set. Deleting and cancelling associated transaction log entries.
20190130 12:05:19.038 WARN grin_wallet::command - Wallet check complete
```
I extended error message in listener, so `wallet listen` starts complaining

```
20190130 12:06:15.083 ERROR grin_wallet::controller - Request Error: Error { inner: Error { inner:

Wallet store error: DB Not Found Error: Key Id: 0300000000000000000000013d00000000 }

Node API error }
```
about exactly the same key which was deleted by check command.

**Comment by hashmap** [comment]
@prodigalprotagonist excellent, thanks a lot!

**Comment by hashmap** [comment]
@prodigalprotagonist 
smth like
```
git remote add cycle https://github.com/cyclefortytwo/grin.git
git fetch cycle
git checkout fix-coinbase-key (or cycle/fix-coinbase-key if the name was taken before)
```
`git checkout master` to get back
