### ISSUE TITLE
Supply should be limited

### ISSUE THREAD

**Issue by cgilliard** [mimblewimble/grin#2423]
Been tracking MimbleWimble and the Grin project. Both are great, but I don't understand why there is no supply limit. On the wiki page it says "Emission rate: 1 grin per second forever.". That means supply is not limited like Bitcoin. Any chance you would consider modifying that to have a well defined limit?

**Comment by russkidooski** [comment]
the defined limit is the maximum 64bit number: 9,223,372,036,854,775,807
it will take around 226 billion years to reach it.

**Comment by jaspervdm** [comment]
https://www.grin-forum.org/t/emmission-rate-of-grin/171/88

**Comment by ignopeverell** [comment]
Now I deeply regret not creating this as issue 1 on this repository. And closing it as won't fix right away. Oh well, I'll just have to remember for the next cryptocurrency.
