### ISSUE TITLE
help correctly estimating miner hashrate from share difficulty and share submit rate

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin#2434]
I'm not familiar with the core code but hope someone can help. Stratum pools include a `difficulty` field int he `method: job` messages, which on most pools I see is fixed to `difficulty: 1`. But let's say it's `difficulty: D`. Currently I noticed most pools are misreporting the miner hashrate, some are overreporting (e.g. f2pool) others are underreporting.

From the pool's point of view, assuming I see a miner that submitted `N` shares during a time interval `T`, all at fixed difficulty `D` where `D` is the value in the json-rpc message, what is actually the correct formula to estimate the average graphs per second of the miner during that time period?

In other words, what's the formula to translate `d` from the json-rpc into float units in order to use the basic formula `hashrate = N * D / T` ?

Or does this not apply here? Do I understand correctly that `D` in the json-rpc message is a scaled value, and as such is worthless for this purpose? Does the `pre_pow` field contain the needed info?

It must be possible for a proxy to estimate miner hashrate based on the info passed in json-rpc, given the miner does receive information from the pool to provite it with a stopping criteria when searching for solutions and submitting them.

I coded stratum proxy software before for many other protocols and computing hashrate was usually easy (bitcoin, ethash, scrypt, etc). Beam was more interesting, and now Grin :)

**Comment by yeastplume** [comment]
Please feel free to ask in our [Support channel](https://gitter.im/grin_community/support)
