### ISSUE TITLE
Look up kernel status

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/grin#2460]
In order to prove a particular transaction has actually taken place, there are 2 things you could do:
- Look up status of transaction inputs/outputs
- Look up status of kernel

The former method is flawed, since outputs can be spent, re-used, cut-through etc. So really the only valid way would be the latter, to check if the kernel is included in a block.

Currently there is no API method to look up if a kernel is in a block or not. I am thinking of adding such a method. I think there are 2 possible approaches:
- Add an index for kernels
- Suggestion by @DavidBurkett on Gitter:
  > If you’re just talking a rust api, you probably would have to get the minimum height of the kernel, find the kernel mmr index of the block at that height, and I believe there’s a txhashset api to return all kernels after a specific mmr index

Which method do you think would be most desirable? Would it be a big issue to add an index, does it increase the storage requirements a lot?

Would really appreciate your input, before I start writing code that is not optimal.. Thanks!

**Comment by antiochp** [comment]
We're going to need something like this for "relative kernel lock heights".

We've discussed different approaches to this a few times.
I proposed an index like you are suggesting and I think @ignopeverell shot this down pretty quickly.
Kernels are ~100bytes. The index would add an additional ~40 bytes per kernel (commitment + height).

So one approach may be (as @DavidBurkett suggests) - 
* find the pos of the kernel in the kernel MMR (use earliest one in case of a duplicate?)
* then search over the headers in the header MMR to find first header where kernel_mmr_size > pos

We do something similar in the existing `chain.get_header_for_output()` for that second step.

**Comment by antiochp** [comment]
Thinking a bit more abut this - not sure full blocks actually gain us much for kernels.
Full blocks are useful for outputs as we have them in the blocks regardless of if they are subsequently spent. But for kernels we know we have them all in the kernel MMR anyway.

If I recall, the main argument against a kernel index is "most of the time we don't need it". Most kernels will simply be added to the kernel MMR and we have no need to go look them up afterwards.
For the few kernels where we _do_ care about their pos, we can go search for them as necessary.

This is in contrast to outputs, where we care about their pos when spent in a subsequent tx, i.e. we _always_ need to go look them up after adding to the MMR, and this makes the index a) more useful and b) worth the storage and maintenance costs.

**Comment by DavidBurkett** [comment]
Yea, full blocks don't really gain us anything for this. The more I think about it though, the mmr lookup should be quick for the 99% case. We should already have the kernel lock height, and the majority of the time, you probably only need to look at a few blocks worth of kernels in the kernel mmr until you find the one you're looking for. You would only really need to read more than a few dozen KB from disk in the rare cases where the transaction isn't finalized/broadcast until long after creation of the tx/slate.

**Comment by yeastplume** [comment]
Need to think about this more, but this may be desirable for wallet robustness and performance. Instead of having to look up each and every output as well as block heights on an update, an efficient TX kernel lookup to reconcile against a local index of associated outputs would be far faster.

Do we allow duplicate kernels? I'd think they'd be very unlikely to occur

**Comment by antiochp** [comment]
I believe duplicate kernel _commitments_ are - 
a) unlikely to occur naturally, but
b) trivially easy to make occur (you can choose an arbitrary kernel excess offset)

**Comment by DavidBurkett** [comment]
@yeastplume To the best of my knowledge, duplicate kernels are allowed. And if my understanding of transaction building is correct, it'd be easy to intentionally create 2 duplicate but valid kernels.

One thing we could do to make this more efficient is allow wallets to "subscribe" to notifications about a specific kernel. This would result in wallet logic leaking into the node code, though.

**Comment by DavidBurkett** [comment]
Looks like @antiochp beat me to it.

**Comment by antiochp** [comment]
So actually - @jaspervdm looking up a kernel would be insufficient to prove _anything_ - you're still going to need a signed msg or something from the tx.

**Comment by jaspervdm** [comment]
> I believe duplicate kernel commitments are -
b) trivially easy to make occur (you can choose an arbitrary kernel offset)

I don't think they are, the offsets are blinding factors. They are only replicatable if you use the exact same sum of blinding factors, which is hard to do for any tx with more than 1 party involved.

> So actually - @jaspervdm looking up a kernel would be insufficient to prove anything - you're still going to need a signed msg or something from the tx.

Right, with grinbox all users have a public key that they use. The slate is signed with their public key. This, in combination with the on-chain presence of the kernel proves that the receiver received the coins.
