### ISSUE TITLE
Add --mainnet as a flag?

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#2464]
For symmetry, would it be a good or bad idea to have a --mainnet flag?
Such a change would mean not showing `Found argument '--mainnet' which wasn't expected, or isn't valid in this context` to people who guess that --floonet --usernet and --mainnet are equals, and #2463

I guess this might quickly succumb to #bikeshedding

**Comment by kargakis** [comment]
I like the simplicity of not needing a flag for mainnet.

**Comment by yeastplume** [comment]
Totally unnecessary
