### ISSUE TITLE
how to access owner_api through ip，instead of 127.0.0.1

### ISSUE THREAD

**Issue by leezijie** [mimblewimble/grin#2477]
how to access owner_api through ip，instead of 127.0.0.1

**Comment by quentinlesceller** [comment]
Owner API is voluntarily statically binded to localhost for safety reasons. Closing.

**Comment by leezijie** [comment]
So if I need to call through program code, must I be on a machine?

**Comment by leezijie** [comment]
So if I need to call through program code, must I be on a machine?

**Comment by leezijie** [comment]
> Owner API is voluntarily statically binded to localhost for safety reasons. Closing.

So if I need to call through program code, must I be on a machine?

**Comment by quentinlesceller** [comment]
Yes, you must be on the same machine.

**Comment by leezijie** [comment]
> Yes, you must be on the same machine.

well,thanks

**Comment by leezijie** [comment]
> Yes, you must be on the same machine.

I have another question in mind. If set  owner_api_include_foreign = true， Can't the foreign_api also be accessed?

**Comment by mazamats** [comment]
This prevents people from running grin in more serious production environments.

These days, you don't run everything on the same machine, you isolate services to provide maximum reliability and scaleability.

Not allowing people to bind externally also prevents using grin inside a docker container.

**Comment by hashmap** [comment]
@mazamats it prevents people from exposing it by mistake, if you know what you are doing you still can expose it, for example with a side car proxy.
