### ISSUE TITLE
owner_api_listen_port missing field in grin-wallet.toml

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2482]
Related #2475.

A new config item was added in #2475 - 
```
owner_api_listen_port
```

We need to be able to safely handle the case where this is missing (i.e. all existing wallets).

Otherwise the wallet fails to startup successfully with a `missing field` error.

**Comment by antiochp** [comment]
Not sure if the solution here is to recreate the config file (and fill in any missing values), or to safely handle this value as optional.

@yeastplume What's the recommended fix here? I know you've worked on some reading/rewriting config files stuff.

**Comment by antiochp** [comment]
Note: workaround is to add it manually to `grin-wallet.toml` - 

```
owner_api_listen_port = 3416
```

**Comment by yeastplume** [comment]
for backwards compat it needs to be an Option in the internal struct, then have something set it to the default value if it’s missing when read
