### ISSUE TITLE
TxHashSet download speed not accurate

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2488]
My node was trying to sync the state with a peer that was uploading at 600 kB/s and got to 98% and then the peer stopped uploading (haven't investigated that yet). What I noticed though is that rather than download speed updating to 0 kB/s, it must be using the average over the entire timeframe, so the download speed slowly peters out (trust me, this is the technical term). Still, 5-10 minutes after the peer stopped uploading data, my node still says it's downloading at 200 kB/s.

Calculating this correctly could be a bit tricky, but even if we go with a less sophisticated approach, like updating every 5-10 seconds, it'd still be a whole lot better than what we do today.

**Comment by c410-f3r** [comment]
cc #2633 

I think this issue can be closed now.

**Comment by DavidBurkett** [comment]
I just experienced this exact same issue 2 days ago. I think it still needs some more work

**Comment by yeastplume** [comment]
Just going to close this for sake of housekeeping, if you still think it needs work by all means reopen
