### ISSUE TITLE
Provide pre-mined solutions for genesis blocks

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#249]
At the moment, the client mines a genesis block no matter what happens. This is fine for testing at cuckoo 16 and creating new blockchains all the time but in the real world this will obviously never happen. A new node should check peers first and try to sync before deciding it's in solo mode and attempting to mine a genesis block.

As an aside note, when running in cuckoo30 mode the code currently uses a pre-mined solution to quickly create a genesis block. This won't work if the header format changes during development and any attempts to start a cuckoo-30 network will be painful. We need to decide whether to keep the genesis block pre-mined or genuinely mine it to start the network.

**Comment by yeastplume** [comment]
Change based on conversations in gitter, just need to include pre-mined cuckoo solutions that work with the genesis block at the required cuckoo-sizes

**Comment by antiochp** [comment]
Cuckoo16/UserTesting resolved in #260.
There is a premined solution for cuckoo30 but I believe this is no longer correct.
