### ISSUE TITLE
big bug： cancel transation， but result success

### ISSUE THREAD

**Issue by BeyongSpringWater** [mimblewimble/grin#2490]
**Describe the bug**
grin mainnet bug

the sender status：
![image](https://user-images.githubusercontent.com/6032172/51959064-c411cb80-248d-11e9-8b9e-fea1b9fbc051.png)

but receiver status

![image](https://user-images.githubusercontent.com/6032172/51959117-ef94b600-248d-11e9-8c58-36c4c12b3783.png)

**Comment by quentinlesceller** [comment]
Could you explain how we can reproduce this?

**Comment by ignopeverell** [comment]
And any chance you had the same seed on multiple wallet instances?

**Comment by BeyongSpringWater** [comment]
> And any chance you had the same seed on multiple wallet instances?

no,only one wallet

**Comment by BeyongSpringWater** [comment]
> Could you explain how we can reproduce this?

when 2000 transations be send at same time,num_outputs is 10, grin server and api will high load. post transations get no response,  when cancel will be success.but transation will be pacaked

**Comment by garyyu** [comment]
> when 2000 transactions be send at same time, num_outputs is 10

Please paste your detail usage, before we can provide further investigations. Or you PM me at Gitter.

**Comment by BeyongSpringWater** [comment]
> > when 2000 transactions be send at same time, num_outputs is 10
> 
> Please paste your detail usage, before we can provide further investigations. Or you PM me at Gitter.

just beacause state mechine not actul state，is local state。 but beam coin is local state。maybe you need change the state mechine

**Comment by quentinlesceller** [comment]
Seems like a misunderstanding. Closing.
