### ISSUE TITLE
grin server config wrong port

### ISSUE THREAD

**Issue by TheRebelOfBabylon** [mimblewimble/grin#2498]
**Describe the bug**
In the grin-server.toml file, in the field for api_http_addr, the port 3413 is there by default when 3415 should be there by default.

**To Reproduce**
1. Install and Run Grin Node in ~/.grin
2. Initialize a wallet
3. Enter command "grin wallet info" receive an error message that it can't connect to the node
4. Check grin-server.toml and see wrong port

**Relevant Information**
Cannot read from a live chain, using local cache...

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.2

**Comment by TheRebelOfBabylon** [comment]
In grin-wallet.toml, I have 3415 but I don't remember if this is the default or not.

**Comment by antiochp** [comment]
You should have the following in `grin-wallet.toml` - 

```
api_listen_port = 3415
...
#where the wallet should find a running node
check_node_api_http_addr = "http://127.0.0.1:3413"
```

i.e. the wallet api will be listening on `3415` but the wallet will attempt to communicate with the node api on `3413`.
