### ISSUE TITLE
Wallet coin selection can build a tx that exceeds max_block_weight

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2510]
This was not really an issue until we allowed `max_block_weight` to be configured per `chain_type`.

`UserTesting` and `AutomatedTesting` now define an artificially low `max_block_weight` to make testing blocks and txs at the block weight limit more convenient.

The coin selection logic (and overall tx building logic) should take `max_block_weight` into consideration to ensure txs are below the max permissible weight.

Not a huge issue right now but it does mean the default coin selection strategy can build invalid txs on `UserTesting` (workaround is to specify `-s smallest`).

**Comment by i1skn** [comment]
I would like to work on this one

**Comment by ignopeverell** [comment]
Looks like this introduces some bona fide test compilation failures.
