### ISSUE TITLE
Can't cancel a received tx with the same Id twice

### ISSUE THREAD

**Issue by Onefox** [mimblewimble/grin#2514]
**Describe the bug**
If I receive a tx with ID 32222222-3222-4222-a222-322222222222 for example. Than I cancel that via `http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`

Now I receive another tx with that ID. 
I can't cancel the new one. When calling 
`http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`
I am getting 
`Transaction 32222222-3222-4222-a222-322222222222 doesn't exist`

1. Receive grin with ID `32222222-3222-4222-a222-322222222222`
2. Cancel that receive via `http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`
3. Receive the same tx again (for example with the listen api)
4. Try to Cancel that ID again...
5. See error `Transaction 32222222-3222-4222-a222-322222222222 doesn't exist`

Here is my txs wallet output:
![image](https://user-images.githubusercontent.com/1709259/52141706-d8ed8b00-2656-11e9-9736-347a8aeb178c.png)

 master tag V1.0.0

**Comment by mcdallas** [comment]
UUIDs are meant to be unique (universally **unique** identifier)

**Comment by Onefox** [comment]
Thats true, still the error message is not great and I don't see any problem why this should not work.

**Comment by quentinlesceller** [comment]
Indeed I think this is something we did not think of at when we implemented the `cancel by tx_id` function. Opened https://github.com/mimblewimble/grin-wallet/issues/27 in grin-wallet repo to track it.
