### ISSUE TITLE
Clarify terminology in intro.md

### ISSUE THREAD

**Issue by rsoltanzadeh** [mimblewimble/grin#2518]
There are some confusing things in [intro.md](https://github.com/mimblewimble/grin/blob/master/doc/intro.md). 

1) *G* and *H* are referred to as both points and curves throughout the document without any explanation, which is very confusing as a curve intuitively is a set of points. As I understand it, this is common sloppy ECC-lingo in the cryptography sphere, but it is confusing nonetheless.

2) This paragraph is extremely confusing.

    >But because `85*G` is a valid public key on the elliptic curve *G*, with private key *85*, for any *x* and *y*, only if `y = 0` is `x*G + y*H` a valid public key on *G*.

    Firstly, it is difficult to logically follow the sentence. How does the final part of *"...only if `y = 0`..."* logically follow *"Because `85*G` is a valid public key..."*? It seems like two sentences have forcefully merged into one. 

    Furthermore `x*G + y*H` **is** a valid public key for any *y*, because *G* and *H* are on the same curve group. The point is that no valid signature will be produced for that public key, which is why it only works if `y = 0`, but this needs to be mentioned.

3) There are inconsistencies such as both writing `r*G + v*H` and `r.G + v.H`, and using the two names of *"excess value"* and *"kernel excess"* for the same thing.

I would love to fix this myself, but my knowledge of ECC is far too low to mess with this and risk making things worse. Hopefully someone more suitable can improve the document.

**Comment by hashmap** [comment]
We fixed a few inconsistencies
