### ISSUE TITLE
Proposed wallet changes

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#2520]
Am thinking about making the following changes to the way the wallet handles outputs:

* Currently, when a wallet creates an output to receive funds, it creates the output as ‘unconfirmed’ and adds it to the wallet total (overall total, not spendable amount). I propose not adding it to any totals, instead displaying these amounts separately as ‘Awaiting Finalization’ or something that implies these outputs are now awaiting someone else’s actions before they will appear confirmed. This will also include change outputs.

* Outputs currently being displayed as ‘awaiting confirmation’ should only be outputs that have appeared on the chain, but have fewer than the default number of confirmations (currently 10 blocks). All others will be included in the ‘Awaiting finalization’ state described above

* ‘grin wallet check’ will no longer remove outputs/transactions that are in the ‘Awaiting finalization ’ by default. A flag can be added to remove them, or other options will be provided to clear them out (such as provide a command to return a list of all transactions associated with said outputs, making it easier to clear them
manually.

Putting this here for thought and discussion, would be grateful to hear suggestions from everyone, especially now we’ve all had a couple of weeks of real-world wallet use

**Comment by mably** [comment]
> ‘grin wallet check’ will no longer remove outputs/transactions that are in the ‘Awaiting confirmation’ by default. 

Why would you remove an output/tx that have already appeared on chain? 🤔

**Comment by yeastplume** [comment]
Meant ‘Awaiting finalization’, will change

**Comment by i1skn** [comment]
@yeastplume does that imply that we would have smth like`TxFinalized` added here?
https://github.com/mimblewimble/grin/blob/130675e0170daf682865c0afcbaaddc8592a1662/wallet/src/libwallet/types.rs#L559-L572
In this case `TxSent` would become `TxFinalized` after it appears on the chain.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin-wallet/pull/8.
