### ISSUE TITLE
In some cases Stratum server reads part of the message and ignores it

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#2524]
```
20190204 13:28:07.478 WARN grin_servers::mining::stratumserver - (Server ID: 0) Failed to parse JSONRpc: JSON error - [106, 115, 111, 110, 114, 112, 99, 34, 58, 34, 50, 46, 48, 34, 125, 10] 20190204 13:28:07.478 WARN grin_servers::mining::stratumserver - (Server ID: 0) Dropping worker: 6120
```
At this moment server reads `jsonrpc " : " 2 . 0 " }`. It drops the first part of the message here  https://github.com/mimblewimble/grin/blob/master/servers/src/mining/stratumserver.rs#L179
if read operation is about to block.

**Comment by bladedoyle** [comment]
Ah, the "appends" part is worth mentioning, yes and thank you.

But then your comment about the server read should be:

```At this moment server reads jsonrpc " : " 2 . 0 " }\n``` (with the newline) and then its clear.

Thanks again for the explanation.

**Comment by hashmap** [comment]
@bladedoyle you are right, as you can see it has `10` at the end

**Comment by bladedoyle** [comment]
:+1:
