### ISSUE TITLE
Event Callback Registration for Stratum Server

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2538]
**Is your feature request related to a problem? Please describe.**
Pools need to get information from the built-in stratum server - for example to know when a block is found.  The current options are:
1) parse the stratum server log message - This isnt a great option because when changes are made to the log message format, or the content of the messages it breaks things.
2) Use a modified version of the stratum server - This isnt a great option since it requires manual merge of code for each upstream change.

**Describe the solution you'd like**
I would like the built-in stratum server to support event hooks with callback registration api.  This will allow a pool operator to write custom code that is called when events they care about occur.

**Comment by hendi** [comment]
:+1: from grin-pool.org here (using 2. currently)

Events I'd like to see hooks for:

- miner submits a solution
- solution rejected, and why
- solution accepted
- block found
- new job
- new block
- block found

**Comment by hashmap** [comment]
For my education - I heard all pools have some proxies on top of grin stratum, can it intercept requests and gets most of this info (not sure how stratum is chatty about reasons etc)?

**Comment by hendi** [comment]
Yes, proxies can get most of the info. For the stuff they can't, we need to 

a) modify grin-server to send us the information we need

and

b) write some logic within the proxy to remove that info/to not pass it along to miners

**Comment by hashmap** [comment]
Sounds reasonable. Do you mean in-process API (Rust) or smth like websocket or both?

**Comment by bladedoyle** [comment]
I prefer in-process for performance.   I would like to be able to build my custom code into a shared library, and the grin-server would load that and call the methods I define.   The simplest (though not cleanest) way is for grin-server to include a "default implementation" (just empty functions) in an external shared library, which could be replaced by the custom library I write.

**Comment by kargakis** [comment]
Can this issue be closed now that we have webhooks? @bladedoyle @mcdallas

**Comment by hashmap** [comment]
Closing, feel free to reopen if needed
