### ISSUE TITLE
api for searching chain by commit

### ISSUE THREAD

**Issue by rentenmark** [mimblewimble/grin#2544]
**Is your feature request related to a problem? Please describe.**

We want to be able to search the mempool for a commit to determine if a user has broadcast our response tx 

**Describe the solution you'd like**

api endpoint on the node 

`/.../search_by_commit?commit=notehuntoehunetohueon`

return json

`{"block_height" : "mempool"}`

or 

`{"block_height" : 123456}`

or

`{"block_height" : null}` <-- for not found 

**Describe alternatives you've considered**

No real alternatives for mempool, need to talk to the node, for the others, we can scan blocks, which is what we're doing now.

**Additional context**

This improves UX in many apps.

**Comment by yeastplume** [comment]
Closing as there's been no follow up for about a year. If you feel this is still relevant please feel free to raise the suggestion again either in one of the wallet subteam channels

**Comment by lehnberg** [comment]
@rentenmark could you describe the rationale for why this is needed? Is it generally useful for all exchanges? If so in what way? And if you could expand a bit more on how it improves "UX in many apps", it would help making the feature request a bit better prioritized.

**Comment by rentenmark** [comment]
Bitcoin cash shows the 0 confirm thing off all the time. It is useful for fast, low threshold transactions with some small amounts of trust. UX is improved because if the sender is not a bad actor they can comfortably walk away from their side when they see 0 confirms but it is in the mempool on the receiver side.
