### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [mimblewimble/grin#2562]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We are glad to let you know about adding GRIN to our service. Now we provide our customers with the opportunity to exchange your currency at SimpleSwap exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks. We achieved high results and have a turnover of 50 BTС daily.
 
The main aim of our team is to simplify the cryptocurrency exchange service and make it clear and transparent for the users.
 
Let me know if you are interested in cooperation!

Best Regards, 
Nicolas
SimpleSwap team
https://simpleswap.io

**Comment by lehnberg** [comment]
Closed. Spam.

**Comment by antiochp** [comment]
@SimpleSwap https://www.grin-forum.org/ is probably a better place for announcements like this.
