### ISSUE TITLE
How? grin stratum switch from Cuckoo 31 to Cuckoo 29

### ISSUE THREAD

**Issue by goodthebest** [mimblewimble/grin#2566]
For grin built in stratum, it shows Cuckoo 31

How can we set POW algo to Cuckoo 29 in grin-stratum.toml or is there any command or work around?

![image](https://user-images.githubusercontent.com/1715740/52673896-68d6e300-2f3b-11e9-8679-40636ce1e742.png)

**Comment by goodthebest** [comment]
@casey @sesam @dpc @romanz attenton please

**Comment by ignopeverell** [comment]
This is a support question, not an issue. Ask on https://gitter.im/grin_community/support or grin-forum.org. And this is grin-miner, read the comments in grin-miner.toml.

**Comment by goodthebest** [comment]
Well, I'm not talking about client side miner but built-in stratum server, by default it comes with Cuckoo 31 and my question was how could stratum algo changed to Cuckoo 31 (of course not client side) but grin stratum server side. There is no option I could find in help to change it. Only you are developer can guide on it.

**Comment by bladedoyle** [comment]
@goodthebest The miner chooses which pow algorithm to use.  The grin built-in stratum server accepts all solution types.
