### ISSUE TITLE
Add header-first block propagation

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#257]
Right now we send the whole block all the time, which is very wasteful in terms of bandwidth. Switch to sending only the header and have peers request the rest if they need to.

**Comment by sesam** [comment]
Already implemented?

**Comment by ignopeverell** [comment]
No but will want for testnet2.

**Comment by antiochp** [comment]
Am I right in thinking "compact blocks" effectively supersedes this? 
i.e. we don't send a `BlockHeader` first but instead a `CompactBlock` (or whatever we name it?)

**Comment by ignopeverell** [comment]
Depends a lot on how compact it ends up being :-)

**Comment by sesam** [comment]
I tried to sync up on two different internet connections, failing both times and ending up with 490 Defunct peers. Trying to restart, grin server would first go through all block headers from 0 to 33k, which takes its merry time.
Also with CompactBlocks, maybe startup/catchup to figure out the best chain is still worthwhile? If nothing else, maybe it could make it harder to mess with nodes by forcing them through a lot of reorgs before finding the best chain.

**Comment by sesam** [comment]
Having read what else is being worked on here, as well as [bitcoins headers first PR](https://github.com/bitcoin/bitcoin/pull/4468), I think that headers first at this time is an unneccessary distraction :)

**Comment by antiochp** [comment]
@ignopeverell - fair point!

**Comment by ignopeverell** [comment]
Great synopsis, thank you. A few remarks:

* A node can propagate the header if it fully validated the compact block (I'm sure you've realized that, it's just the _full_ node terminology that's ambiguous).
* I don't think there's a good heuristic on requesting a full or compact block, so unless the full one is explictly specified, a node should likely always provide the compact.
* Agreed about incremental hydration being a future enhancement.
