### ISSUE TITLE
cancel_tx bug

### ISSUE THREAD

**Issue by leezijie** [mimblewimble/grin#2577]
**Describe the bug**
I normally created a transaction, and when I wanted to cancel it, I made the following mistake:
Transaction ce8b8c9d-225b-4269-8978-b2d211f45675 doesn't exist

**To Reproduce**
1.
curl -u grin:xxxxxxxx -X POST  http://127.0.0.1:3420/v1/wallet/owner/issue_send_tx --data '{"amount":1192000000,"minimum_confirmations":0,"method":"http","dest":"http://xxxxxx","max_outputs":5,"num_change_outputs":1,"selection_strategy_is_use_all":true,"fluff":false}'
return  ce8b8c9d-225b-4269-8978-b2d211f45675
2.
curl -u grin:xxxxxx -X POST http://127.0.0.1:3420/v1/wallet/owner/cancel_tx?tx_id=ce8b8c9d-225b-4269-8978-b2d211f45675
return Transaction ce8b8c9d-225b-4269-8978-b2d211f45675 doesn't exist

Who can answer it?

**Comment by garyyu** [comment]
Are you sure it indeed returned `ce8b8c9d-225b-4269-8978-b2d211f45675` in your 1st step?

On my terminal, the `--data 'xxx'` doesn't work, I need use `--data "xxx"`.

btw, the `"fluff":false` doesn't exist for this API. `fluff` only works for `post_tx` and `repost` APIs.

**Comment by leezijie** [comment]
> 你确定它确实`ce8b8c9d-225b-4269-8978-b2d211f45675`在你的第一步回来了吗？
> 
> 在我的终端上，`--data 'xxx'`不起作用，我需要使用`--data "xxx"`。
> 
> 顺便说一下`"fluff":false`，这个API不存在。`fluff`仅适用于`post_tx`和`repost`API。

thanks
