### ISSUE TITLE
upper limit on number of outputs being spent with default wallet send?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#258]
Right now we attempt to spend **all** outputs in the wallet.
Leaving a test miner running for a few hours can generate a lot of outputs (~1 every 60s).
So it is quite feasible to attempt to spend in excess of 1,000 outputs after 24 hours.

Not sure what the limit should be but a tx with 1,000 inputs is pretty big.
May we limit it to 100 or something?

**Comment by ignopeverell** [comment]
Agreed. Let's try to be a bit more aggressive to start with and go with 500. If that proves too much we can reduce it further later.

I think we need something at the consensus level to avoid attacks, I've added #261 to address this.
