### ISSUE TITLE
/v1/chain/validate Rest API incorrectly documented

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2587]
Running /v1/ states that /v1/chain/validate should be executed via a POST request:
![image](https://user-images.githubusercontent.com/24623306/52904429-38709c80-31fa-11e9-8571-2dde269750fa.png)

It is coded to only accept GET requests, though:
![image](https://user-images.githubusercontent.com/24623306/52905351-ff8af480-3206-11e9-8762-6c4b203449f0.png)
![image](https://user-images.githubusercontent.com/24623306/52905361-1cbfc300-3207-11e9-853b-7f9c8809d658.png)

**Comment by DavidBurkett** [comment]
Also "get chain/outputs" should really be something like "get chain/outputs/byheight?start_height=100&end_height=200" and "get chain/outputs/byids?id=xxx,yyy,zzz"

**Comment by pml10628** [comment]
1ede817398a84d4c8533f423444681cf

**Comment by hashmap** [comment]
Fixed
