### ISSUE TITLE
Grin server fails as daemon and cannot even be backgrounded

### ISSUE THREAD

**Issue by seibelj** [mimblewimble/grin#2589]
**Describe the bug**
Running Grin as a daemon fails, as has been described in other bug reports. However, it also cannot even be backgrounded. It is seemingly impossible to run Grin without a live, active terminal.

**To Reproduce**
Try to run as daemon (`./grin server start`) which exits immediately.

Alternatively, try to background it:
`./grin server run &`
Or
`./grin server run` then `ctrl + z` to suspend, then `bg` to background.

If you try to hit the node status API with `GET http://localhost:3413/v1/status` it will hang, but the moment grin is foregrounded (`fg`) the API stops hanging and loads instantly.

I'm trying to create a desktop GUI with the grin daemon bundled in, but it appears there is literally no way to run Grin except manually in a terminal ☹️ 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.0.1

**Comment by kargakis** [comment]
> It is seemingly impossible to run Grin without a live, active terminal.

FWIW, I am running [grin via systemd](https://github.com/mimblewimble/docs/wiki/Build-and-run-automation) successfully since mainnet launch.

**Comment by hashmap** [comment]
I got an impression that we are removing daemonization support, perhaps @yeastplume can tell more

**Comment by kargakis** [comment]
> I got an impression that we are removing daemonization support, perhaps @yeastplume can tell more

Daemonization support was removed in https://github.com/mimblewimble/grin/pull/2535

**Comment by quentinlesceller** [comment]
Closing.
