### ISSUE TITLE
node cpu usage

### ISSUE THREAD

**Issue by nikito7** [mimblewimble/grin#2594]
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
11061 user      20   0 10.760g  85924  62380 S 34.1  8.5   0:28.62 grin          

17:44:08 up 10:20,  1 user,  load average: 0.47, 0.55, 0.86

Constant high cpu usage, it's normal?

Default configs.

**Comment by DavidBurkett** [comment]
My mac node sits at ~20% CPU. I assume one of the thread sleep values is unnecessarily low, or one of the containers is really inefficient, but I haven't had a chance to track it down. Grin++ sits at <0.1%, so there's certainly nothing core to the protocol that requires constant high CPU usage.

**Comment by nikito7** [comment]
changed:

cat .grin/main/grin-server.toml | grep tui
run_tui = false

now <6% cpu usage

**Comment by nikito7** [comment]
Sooo,

no tui, <8 peers = < 10% cpu
no tui, >50 peers = > 70% cpu

And Grin++, 50 peers = < 5% cpu

**Comment by nikito7** [comment]
Bug or feature?

Grin never stop discovering new peers

There is a loop

**Comment by nikito7** [comment]
windows preview grin

with tui, 50 peers: 10% cpu
no tui, 50 peers: <1% cpu

**Comment by amazarache** [comment]
I have followed this thread, trying to achieve less CPU usage for grin node, but without luck :(
disabling tui doesn't lower the CPU usage in my case

processor usage stays between 30-50% load in both cases.

**Comment by nikito7** [comment]
peer_max_count = 8
peer_min_preferred_count = 4

**Comment by amazarache** [comment]
Whatever values I used for for peers, grin server loads processor to 40-50%

**Comment by nikito7** [comment]
Its normal at begin, peers discovery issues

**Comment by nikito7** [comment]
maybe fixed in
20190616 21:08:27.629 INFO grin - This is Grin version 1.1.1-beta.1 (git v1.1.0-3-gd03a81f), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).

**Comment by nikito7** [comment]
Current status:

Vps 2Ghz
50% cpu load
275 peers

**Comment by yeastplume** [comment]
Are there any actions to be taken here or can this be closed?

**Comment by DavidBurkett** [comment]
This was solved long ago. Should be good to close.
