### ISSUE TITLE
Please add function for building block header to grin-core

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2595]
**Is your feature request related to a problem? Please describe.**
I have pre-pow, nonce, edge_bits, and proof and want to verify that its valid.  Currently there is no way to do this without writing (and maintaining) custom code.   Pools (and probably other use cases) need this ability.

**Describe the solution you'd like**
Provide a function for building a block header.

**Describe alternatives you've considered**
Write and maintain it myself.

**Comment by bladedoyle** [comment]
This works, please add it to grin-core:

```
use failure::Error;
use grin_util::from_hex;
use grin_core::pow::Proof;
use grin_core::core::BlockHeader;
use grin_core::ser::{deserialize, ser_vec};


fn block_header(pre_pow: String, edge_bits: u8, nonce: u64, mut proof: Vec<u64>) -> Result<BlockHeader, Error> {
    let mut header_bytes = from_hex(pre_pow)?;
    let mut nonce_bytes = ser_vec(&nonce)?;
    header_bytes.append(&mut nonce_bytes);
    let mut proof = Proof::new(proof);
    proof.edge_bits = edge_bits;
    let mut proof_bytes = ser_vec(&proof)?;
    header_bytes.append(&mut proof_bytes);

    let header: BlockHeader = deserialize(&mut &header_bytes[..])?;
    Ok(header)
}
```

**Comment by yeastplume** [comment]
Suggest we review the related PR
