### ISSUE TITLE
Grin - Connected Peers < 5

### ISSUE THREAD

**Issue by alienninja** [mimblewimble/grin#2597]
**Describe the bug**
Was having issues with my Chain Height not increasing to the Header Chain Height.
I would have peers, but eventually they would go to 0.
I tried removing the chain_data/peer directory, but that did not change the behavior.
I then removed the entire chain_data directory, and it started to work, however after about 
2 hours, I'm still at 4 peers and Status "Preparing chain state for validation, step 3/4"  This was after restarting Grin because it hung on downloading the chain.

**To Reproduce**
1. Clean reboot of system
2. Run 'grin server start'
3. Run 'grin'

**Relevant Information**
grin_server.log attached.

**Desktop (please complete the following information):**
 - Version [e.g. 1.0.1]
Linux  4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Additional context**
Note I am also mining on this server with bminer

Also, should I be running both "grin" and "grin server start" ?  On reboot, I send "grin" to screen, and just run grin server start, then start my mining as well as start the wallet listener.

Thanks
[grin-server.log](https://github.com/mimblewimble/grin/files/2877991/grin-server.log)

**Comment by antiochp** [comment]
I believe `grin` by default runs `grin server run`.

So you should definitely _not_ be running `grin server start` alongside this as this will cause multiple grin processes to be potentially writing to the same backend db and files.

**Comment by hashmap** [comment]
Agree, it has nothing to with number of peers (4 is low but enough to get a node synced), you corrupt your chain data by running 2 instances of grin. It will be fixed  soon (by not allowing the second process to start)
Closing for now.
