### ISSUE TITLE
peers limit not working (git v1.0.1-35-g2df633b)

### ISSUE THREAD

**Issue by nikito7** [mimblewimble/grin#2616]
maybe since "peer:port db" change

(git v1.0.1-35-g2df633b), built for x86_64-unknown-linux-gnu by rustc 1.32.0 (9fda7c223 2019-01-16).
20190221 22:24:48.830 DEBUG grin - Built with profile "release", features "".
Grin Server Status

Protocol version: 1
User agent: MW/Grin 1.0.1
Connections: 50

peer_max_count = 30
peer_min_preferred_count = 20

**Comment by nikito7** [comment]
Ok i changed default port
With port=3414 its ok

**Comment by nikito7** [comment]
https://github.com/antiochp

port=9999

Protocol version: 1
User agent: MW/Grin 1.0.1
Connections: 30
Chain height: 54300

Protocol version: 1
User agent: MW/Grin 1.0.1
Connections: 49
Chain height: 54301

**Comment by nikito7** [comment]
I have static IP

20190222 12:21:32.956 DEBUG grin_servers::grin::seed - monitor_peers: on 0.0.0.0:9999, 53 connected (38 most_work). all 7905 = 254 healthy + 10 banned + 7641 defunct

funny 254 healthy

**Comment by antiochp** [comment]
> funny 254 healthy

This looks pretty reasonable to me right now based on stats from other nodes on the network.

> 20190222 12:26:16.263 DEBUG grin_servers::grin::seed - monitor_peers: on 0.0.0.0:3414, 67 connected (56 most_work). all 13321 = 120 healthy + 13 banned + 13188 defunct

The vast majority of nodes are behind NAT and do not have port forwarding so we have no way of connecting to them directly.

**Comment by nikito7** [comment]
monitor_peers: on 0.0.0.0:**9999**, 53 connected (38 most_work). 

monitor_peers: on 0.0.0.0:**3414**, 12 connected (11 most_work).

@antiochp understand?

**Comment by nikito7** [comment]
I have an old node (git v1.0.1-30-g23cb9e2), built for x86_64-unknown-linux-gnu by rustc 1.32.0 (9fda7c223 2019-01-16).

Don't have this issue

**Comment by antiochp** [comment]
> monitor_peers: on 0.0.0.0:**9999**, 53 connected (38 most_work).
> 
> monitor_peers: on 0.0.0.0:**3414**, 12 connected (11 most_work).
> 
> @antiochp understand?

I don't think this is enough to determine one way or the other, it takes time for peers to settle down given the large number of "defunct" peers you see.

I don't immediately see this being related to #2616.
Its also unrelated to the "peers limit" in the title of this issue.

**Comment by nikito7** [comment]
Ok

Deleted peer folder

peer_max_count = 8
peer_min_preferred_count = 4

Node1/vps:
monitor_peers: on 0.0.0.0:3009, 23 connected (17 most_work). all 2422 = 1857 healthy + 2 banned + 563 defunct

Node2/home:
monitor_peers: on 0.0.0.0:5555, 10 connected (7 most_work). all 2609 = 1954 healthy + 6 banned + 649 defunct

**Comment by nikito7** [comment]
Deleted peer folder and changed port to 3414

monitor_peers: on 0.0.0.0:3414, 8 connected (6 most_work). all 737 = 701 healthy + 0 banned + 36 defunct

@antiochp defunct are a counter or list?
If a list why we need keep it?
Have timeout?

**Comment by nikito7** [comment]
Closed

See https://github.com/mimblewimble/grin/issues/2618

**Comment by Funkyswing** [comment]
Hi, could I ask how could you change the defaut port to 3414?
(I know this question is stupid, but I've got no solution after searching. )

Thank you in advance.

**Comment by nikito7** [comment]
in grin-server.toml
