### ISSUE TITLE
Different mining difficulty on different ports

### ISSUE THREAD

**Issue by rlinxy** [mimblewimble/grin#2622]
Some pool stratum server such as nomp and open-eth-pool, we can set different POW difficulty on different ports, is it possible to implement this feature as well?
For example, in the server.toml, we can set the stratum server listen to
port 3333 with difficulty 1
port 4444 w/ difficulty 8
port 5555 w/ difficulty 16

So we can pick the port according to the rig's hash power. For now, nicehash requires minimum diff 4, but if set it to '4', it might be too hard for some rigs to submit a share in a short time. 

Also we need the log to be modified such as:
Got share at height xxxx, hash ***********, edge_bits 29, nonce *************, job_id ***, difficulty 14797/2383701130, submitted by *** with minimum difficulty ***

Thanks.

**Comment by oneevil** [comment]
+1

**Comment by quentinlesceller** [comment]
I don't think adding additional port/difficulty in Grin Stratum makes much sense. We want to keep the implementation as simple as possible and this is perfectly doable with a middleware.

**Comment by quentinlesceller** [comment]
Closing. Feel free to comment here if you feel like this issue should be tackled in grin core.
