### ISSUE TITLE
Stratum server does not adjust the minimum share difficulty as intended

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2629]
**Describe the bug**
 Question is asked: "Is the code here - https://github.com/mimblewimble/grin/blob/2df633b62291f615ae96ceae0494d12b99d95013/servers/src/mining/stratumserver.rs#L774 - comparing a scaled difficulty to an unscaled difficulty?"

@tromp answers:  "yes, that's comparing a scaled difficulty to an unscaled difficulty. of which i don't see the purpose"

**Relevant Information**
That code was written before we had 2 POW, I belive, and it was never updated with the "seconday_scaling" adjustment.

The original intent was that code was to allow a user to set a minimum share difficulty in the stratum server but if the setting is "too high" the stratum server would adjust it to the current blocks "target difficulty" rather than not submitting full solutions.

**Comment by tromp** [comment]
There is something to be said for simply setting

    self.minimum_share_difficulty = self.config.minimum_share_difficulty;

and assuming that the user knows what they're doing when changing the configuration.

**Comment by bladedoyle** [comment]
I guess thats an option.   Since we dont expect grin network difficulty to fall below what one would reasonably set as the stratum network difficulty Its probably fine
