### ISSUE TITLE
error segfault at 20 ip 00007fe6e727a0a8 sp 00007fe464d0cca0 error 4 in libncursesw.so.5.9[7fe6e7255000+2d000]

### ISSUE THREAD

**Issue by sicute** [mimblewimble/grin#2647]
**Describe the bug**
I'm install grin from binary using ubutu 16.04 X64 in aws with public ip .
i made grin.services script like in the web  : 

**To Reproduce**
1. Run sudo systemctl start grin 
2.ubuntu@ip-172-31-101-87:~$ sudo systemctl status grin.service
● grin.service - Grin node
   Loaded: loaded (/etc/systemd/system/grin.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Mon 2019-03-04 07:37:46 UTC; 3s ago
  Process: 6750 ExecStart=/usr/local/bin/grin server --config_file /mnt/grin/config/grin-server.toml run (code=killed, signal=SEGV)
 Main PID: 6750 (code=killed, signal=SEGV)

Mar 04 07:37:46 ip-172-31-101-87 systemd[1]: grin.service: Unit entered failed state.
Mar 04 07:37:46 ip-172-31-101-87 systemd[1]: grin.service: Failed with result 'signal'.
ubuntu@ip-172-31-101-87:~$
3. ubuntu@ip-172-31-101-87:~$ cat /etc/systemd/system/grin.service
'[Unit]
Description=Grin node
After=network.target

[Service]
WorkingDirectory=/mnt/grin/
User=ubuntu
Group=ubuntu
PrivateDevices=yes
Type=simple
ExecReload=/bin/kill -HUP $MAINPID
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=60
ExecStart=/usr/local/bin/grin server --config_file /mnt/grin/config/grin-server.toml run
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
Alias=grin.service
4. Mar  4 07:37:46 ip-172-31-101-87 systemd[1]: grin.service: Main process exited, code=killed, status=11/SEGV
Mar  4 07:37:46 ip-172-31-101-87 systemd[1]: grin.service: Unit entered failed state.
Mar  4 07:37:46 ip-172-31-101-87 systemd[1]: grin.service: Failed with result 'signal'.
Mar  4 07:38:16 ip-172-31-101-87 systemd[1]: grin.service: Service hold-off time over, scheduling restart.
Mar  4 07:38:16 ip-172-31-101-87 systemd[1]: Stopped Grin node.
Mar  4 07:38:16 ip-172-31-101-87 systemd[1]: Started Grin node.
Mar  4 07:38:16 ip-172-31-101-87 kernel: [ 1463.743750] ui[6797]: segfault at 20 ip 00007f9e75ae60a8 sp 00007f9befbfaca0 error 4 in libncursesw.so.5.9[7f9e75ac1000+2d000]
Mar  4 07:38:17 ip-172-31-101-87 systemd[1]: grin.service: Main process exited, code=killed, status=11/SEGV
Mar  4 07:38:17 ip-172-31-101-87 systemd[1]: grin.service: Unit entered failed state.
Mar  4 07:38:17 ip-172-31-101-87 systemd[1]: grin.service: Failed with result 'signal'.
'

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 x64

**Comment by quentinlesceller** [comment]
v1.x.x issue. Closing. Feel free to comment here if you feel like this issue is still relevant.
