### ISSUE TITLE
Dockerfile only builds version 1.0.1

### ISSUE THREAD

**Issue by deh8551** [mimblewimble/grin#2657]
Rebuilt grin in docker on Ubuntu 16 from the latest git version 7fd2970 and it build version 1.0.1 and not version 1.0.2

**Comment by rikur** [comment]
Docker build cache?

**Comment by deh8551** [comment]
Doesn’t appear to be.  I ran it with the —no-cache switch.  I also clear all the docker images.  It still builds version 1.0.1.

Thank you,

**Comment by deh8551** [comment]
I found the issue.  Apologizes for the trouble.
