### ISSUE TITLE
will grin support smart contract ?

### ISSUE THREAD

**Issue by kaidiren** [mimblewimble/grin#2661]
as title, thanks

**Comment by GandalfThePink** [comment]
in the current form this is not possible and as far as I know there are no plans or even ideas how to change this. 

What is possible are so called scriptless-scripts that offer some very limited functionality, somewhat below the bitcoin scripting language.

**Comment by kaidiren** [comment]
thanks

**Comment by garyyu** [comment]
https://gitter.im/grin_community/events?at=5c4aa8569bfa375aab57b188

>> Q: Is there an intention for Grin to support smart contracts, and if so, will the lightweight, un-programmable nature of Grin be a constraint? 

> A: The absence of scripting doesn't mean smart contracts are impossible. We already support multi-signature transactions, atomic swaps and should be able to develop a lightning network or confidential assets.
