### ISSUE TITLE
Wallet owner api interface is not accessible on 0.0.0.0

### ISSUE THREAD

**Issue by Jlonghi** [mimblewimble/grin#2663]
It is not possible to access the wallet owner api from outside of local host as it is hard coded. It would be better if this is a config value like the wallet listener api.

**Comment by hashmap** [comment]
It was done intentionally.

 Please check issues:
* https://github.com/mimblewimble/grin/issues/2477
* https://github.com/mimblewimble/grin/issues/1274

and PRs:
* https://github.com/mimblewimble/grin/pull/1867
* https://github.com/mimblewimble/grin/pull/2527

**Comment by mazamats** [comment]
I suggest another config toggle, `i_know_what_im_doing`; which will let us expose the owner api.

Otherwise, people are just going to keep opening GH issues.
