### ISSUE TITLE
Crash when mining with AMD (Mac Pro)

### ISSUE THREAD

**Issue by timetoseek** [mimblewimble/grin#2664]
**Describe the bug**

The "ocl_cuckaroo" plugin crashes immediately on my Mac Pro.  Here is the section of "grin-miner.toml" with applicable configurations:
plugin_name = "ocl_cuckaroo" 
[mining.miner_plugin_config.parameters]
platform = 0
device = 1

---

**To Reproduce**
1. Run in 3 terminal windows:  './grin', './grin wallet listen', './grin-miner'
2. Expect mining via the GPU
3. Switch to the "grin-miner" terminal window
3. See error

**Relevant Information**
![ocl_cuckaroo_crash_no_ui](https://user-images.githubusercontent.com/26972658/54051555-eedef600-4196-11e9-8fb4-18fa28612507.png "ocl_cuckaroo plugin crash, without the User Interface")

---

**Screenshots**
![ocl_cuckaroo_plugin_crash](https://user-images.githubusercontent.com/26972658/53980183-8b849380-40c4-11e9-9dcd-2c151eac81ab.png "Screen print of ocl_cuckaroo plugin crash")

---

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version: 10.14.3
 - Hardware: Mac Pro (2012) with 2 CPU's (12 cores total), 40 GB RAM, 
 - GPU: Sapphire AMD Radeon NITRO+ RX 580 8GB

![GPU_info](https://user-images.githubusercontent.com/26972658/54051652-2f3e7400-4197-11e9-97e0-a471098ee738.png "GPU Information")

---

**Additional context**
Please note that the "ocl_cuckatoo" plugin runs, but no shares are accepted,  The "cuckaroo_cpu_compat_29" plugin, works OK.  Screen prints are as follows:

![cuckaroo_cpu_compat_29_plugin_works](https://user-images.githubusercontent.com/26972658/53980224-ae16ac80-40c4-11e9-9e1e-b25e4470acf0.png "Screen print of cuckaroo_cpu_compat_29 plugin working OK")

![ocl_cuckatoo_plugin_works](https://user-images.githubusercontent.com/26972658/53980219-a9ea8f00-40c4-11e9-8647-e10324a6a2ac.png "Screen print of ocl_cuckatoo plugin working OK")

---

(I have also reported this crash in the "Grin-Miner" repository-- https://github.com/mimblewimble/grin-miner/issues/199#issue-418456383)

**Comment by hashmap** [comment]
No need to report also here
