### ISSUE TITLE
p2p support for LoadBalancer VIP

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2665]
**Is your feature request related to a problem? Please describe.**
Nodes living behind a loadbalancer VIP dont have a way to advertise their ingress IP address.

**Describe the solution you'd like**
Any method that allows nodes behind a loadbalancer to specify the address that peers can use to connect to them.

**Describe alternatives you've considered**
* Requesting that Igno add the address to DNS

**Additional context**
@garyyu How does grin server know what p2p address to advertise? My grin server runs behind NAT with mapped public IP address. Im pretty sure there isnt any way for the server itself to discover its own p2p address. I think it would need a config item for that. What do you think?
For my pool, Igno added its p2p address to some "well known servers" list, which is fine, but I dont think that solution scales well.
Im in the process of adding additional stratum endpoints and would like to make the p2p available for incoming connections

@DavidBurkett My nodes are on google cloud and they used a "mapped" address (I can do a little reading to learn the correct technical name for this if needed).
For example, my grin node has an "internal address" of 10.8.6.200, when it connects to the outside world it does that through address 35.197.37.206 (thats the address the peers know it by), but for ingress, the mapped ip address is 35.247.33.125. As far as I know, there isnt any way for my node, or its peers to know about the 35.247.33.125 address

```
root@grin-0:~# ifconfig | grep inet
        inet 10.8.6.200  netmask 255.255.255.0  broadcast 0.0.0.0
```
and
```
root@grin-0:~# curl wtfismyip.com/text
35.197.37.206
```
and
```
bdoyle@lucy:~$ host p2p.mwgrinpool.com
p2p.mwgrinpool.com has address 35.247.33.125
```

My guess is that a grin-server.toml config entry, would be be needed for me to specify the external loadbalancer/ingress address?

**Comment by garyyu** [comment]
@bladedoyle 
Why there's a "requirement" on p2p load balance? could you explain this? 
And I guess your real requirement is stratum load balance, not p2p. 


> How does grin server know what p2p address to advertise?

At current version, Grin server doesn't advertise its p2p address. The p2p client will draw the connected IP address and save into peer info, and distribute this peer info.

> Im pretty sure there isnt any way for the server itself to discover its own p2p address.

Similar to your `curl wtfismyip.com/text`, there're some ways to discover own p2p address. But we don't do it since there's no need to find own p2p address.

> I think it would need a config item for that. What do you think?

Only if we prove it's a true requirement. And need some detection to confirm the advertised one is the true one, but can be done by the nonce.

**Comment by garyyu** [comment]
```
Blade Doyle @bladedoyle 09:13
@garyyu I think im retracting my requirement....please ignore for a bit.

Gary Yu @garyyu 09:18
Okay, np :-)
```

@bladedoyle pls remember to close this issue if not needed anymore. thanks.

**Comment by bladedoyle** [comment]
Closing.  If I decide it really is necessary (unlikely) I'll reopen.
