### ISSUE TITLE
Invalid peer ban in 1.0.2

### ISSUE THREAD

**Issue by rentenmark** [mimblewimble/grin#2670]
**Describe the bug**

I am running a standard 1.0.2 node behind NAT and getting peer banned. If the standard client is getting banned this constitutes a bug if I understand banning correctly. I am not acting as an adversary. There are multiple nodes running behind this particular IP at times, but not all times when I am getting banned.

Note that this did not happen with 1.0.1

**To Reproduce**

It is not entirely clear to me to be quite honest. It seems to me that all you need to to is run a grin node on a mac behind NAT. This however seems like it may be too simple. Perhaps try sleeping the mac with the node running etc. 

**Relevant Information**

I unbanned myself from one peer and used that peer to bootstrap. I end up getting banned again. The full log in trace from the banned peer perspective [in this gist](https://gist.github.com/rentenmark/a9e493daa75f490ef4895a481aebf8ea)

**Desktop (please complete the following information):**
 - OS: Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G4015)
      Kernel Version: Darwin 17.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

 - Grin Version 1.0.2

**Additional context**

Chat log here https://gitter.im/grin_community/dev?at=5c8272890a6b915163f6dc08

**Comment by rentenmark** [comment]
Ultimately I think the root cause of this was actually antivirus software that didn't appreciate me connecting to a bunch of peers quickly, so when I went to one peer it resolved.

**Comment by DavidBurkett** [comment]
I still have the same issue, and it's not antivirus related.

**Comment by rentenmark** [comment]
I'll re-open to track

**Comment by ignopeverell** [comment]
@DavidBurkett any more details as to how it's occurring for you?

**Comment by DavidBurkett** [comment]
If you try to run multiple clients behind the same public IP address, even if on separate PCs. It's possible it's just not something worth supporting, but it's easy to reproduce in my experience.

**Comment by antiochp** [comment]
We are tacking these by ip address, ignoring the port. So if we _do_ see multiple peers from the same public ip address then we may be something dumb internally.

We should refuse the newer peer connection attempts as we limit it to one peer connection per ip address, but do we possibly end up banning it (by ip address), which bans the currently connected one also?

**Comment by ignopeverell** [comment]
Not that I know of but it's possible. It'd be great to get the ban reason...

**Comment by quentinlesceller** [comment]
v1.x.x issue. Closing. Feel free to comment here if you feel like this issue is still relevant.
