### ISSUE TITLE
Running the server looks broken

### ISSUE THREAD

**Issue by Giszmo** [mimblewimble/grin#2676]
I just updated to the latest master version 7678aceddfd3 and noticed that running

`$ target/release/grin server run`

resulted in a very messy display. Might this be due to my terminal not supporting something or what is this?

![Screenshot from 2019-03-13 20-10-46](https://user-images.githubusercontent.com/96378/54321009-e5f28800-45cd-11e9-9de1-e3ecaf908e98.png)

I run Ubuntu with genome terminal 3.28.2. Happy to provide more details.

**Comment by okkman** [comment]
I have encountered this on at least 4 different nodes, all since the update to 1.0.2  Can't tell you why it happens (though many point to missing info in 'locale' this made no difference on any of my machines) but I can tell you that it spontaneously goes away, or it doesn't.

**Comment by yeastplume** [comment]
I think something got slipped into 1.0.x that causes this. I get this on my machine in 1.0.3 but 1.1.0 branch works fine.

**Comment by quentinlesceller** [comment]
Isn't it a known issue related to ncurses and the locales used?

**Comment by hashmap** [comment]
It happens some time when locale is fine, users reported that the usual fix didn‘t work

**Comment by kargakis** [comment]
I have seen this a couple of times too - really difficult to pinpoint what is actually causing it

**Comment by da2ce7** [comment]
I have had the same problem on Fedora with both Gnome Terminal and Konsole. I have run the `git bisect` and have found 4c9984cf1158c21fed70b1bcca3b722e15038295 to be the culprit.

**Comment by kargakis** [comment]
Similar issue about grin-miner reported in the forum at https://www.grin-forum.org/t/grin-miner-looking-weird-in-terminal/4507

**Comment by mably** [comment]
Looks like it doesn't build on Windows anymore, at least on my machine:

```
cargo build --release
  Downloaded ncurses v5.99.0
   Compiling ncurses v5.99.0
   Compiling grin v1.0.2 (D:\dev\sources\cryptos\grin)
error: failed to run custom build command for `ncurses v5.99.0`
process didn't exit successfully: `[...]\grin\target\release\build\ncurses-d2fa83846fe76501\build-script-build` (exit code: 101)
```
