### ISSUE TITLE
Typo: introduction wiki page

### ISSUE THREAD

**Issue by jie85** [mimblewimble/grin#2689]
In [Introduction Wiki](https://github.com/mimblewimble/grin/blob/master/doc/intro.md)

> a transaction kernel, consisting of
> kernel excess (Pedersen commitment to zero)
> transaction signature (using kernel excess as public key)

The kernel excess should be used as the private key rather than the public key during the transaction signature.

**Comment by quentinlesceller** [comment]
Closing. There have been a lot of changes to this doc in the meantime.
