### ISSUE TITLE
Investigate alternatives to TravisCI 

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#2691]
As discussed in the last dev meeting. 

## Motivation
* See https://github.com/mimblewimble/grin/issues/2667
* Current windows build process are highly manual where you have to temporarily remove the github token from the project.
* [TravisCI was acquired by Ibera](https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/) end of Jan 2019.
* Ibera sent a wave of [termination letters to Travis CI employees](
https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/) end of Feb 2019. There is no mention of shutting down Travis CI, or shutting it down for Open Source projects, however the loss of experienced employees is unlikely to help stabilise the platform, or get bugs fixed. 

## Candidate discussions
* https://github.com/ligurio/awesome-ci
* https://internals.rust-lang.org/t/which-ci-platform-should-rust-use/9322/29

### Gitlab
We have access to https://gitlab.com/groups/mimblewimble

It seems it can be integrated with Github:
https://about.gitlab.com/solutions/github/

... And that this is free for open source projects:
> If you have a public, open source project on GitHub you can now take advantage of free CI/CD on GitLab.com. As part of our commitment to open source, we offer all public projects our highest tier features (Gold) for free. While other CI/CD vendors limit you to running a handful of concurrent jobs, GitLab.com gives open source projects hundreds of concurrent jobs with 50,000 free CI pipeline minutes.

### Microsoft Azure Pipelines
https://news.ycombinator.com/item?id=18983586

### [DroneCI](https://drone.io)

[Free cloud hosting](https://cloud.drone.io) for open source projects

### [Codefresh?](https://codefresh.io/)

---

## General questions

1. What's a sensible first step here?
1. How have other orgs done it? 
1. What are the workflows in practice?

**Comment by sesam** [comment]
> the owner of https://gitlab.com/groups/mimblewimble/-/group_members,
>
Who can I donate the project to?
Google knows the steps, once we have a user.

It's currently set up to do
cargo test --all

It triggers on merge to github master.


And it has been a bit wobbly, so might need more help. Or if the wobblyness
os gone after splitting grin into more parts and taking out the curl:ed
wallet angular site, maybe just enable and all is good.

**Comment by lehnberg** [comment]
@sesam thanks a lot! I'm https://gitlab.com/lehnberg, feel free to add me to the group and I can add the rest.

**Comment by quentinlesceller** [comment]
If you need a hand my handle is [@quentinlesceller](https://gitlab.com/quentinlesceller).

**Comment by sesam** [comment]
Both added as owners, the highest I could pick. 2FA is mandatory. The current CI integration is defined by master/.gitlab-ci.yml which was added in https://github.com/mimblewimble/grin/commit/731cde3710e5830d91eb15a8f14f55dff8864e82

**Comment by antiochp** [comment]
One thing to note: Its not clear from the gitlab website but it _does_ look like "CI for github" is not going to be a free product beyond end of the month, even for open-source projects.

https://about.gitlab.com/solutions/github/

> For GitLab.com users, GitLab CI/CD for GitHub will be available promotionally in our Free tier through March 22, 2019. (After March 22, 2019 it will move to the Silver tier and be available on Silver and Gold.)

**Comment by lehnberg** [comment]
Wow very nice.

**Comment by ignopeverell** [comment]
Perhaps we should look at [alternatives](https://github.com/ligurio/awesome-ci)?

**Comment by lehnberg** [comment]
Clarified issue title and updated the description

**Comment by lehnberg** [comment]
What seems to be a _highly_ relevant thread: https://internals.rust-lang.org/t/which-ci-platform-should-rust-use/9322

**Comment by rentenmark** [comment]
Circle CI worked quite well for me for windows builds on github

**Comment by quentinlesceller** [comment]
I just applied to get GitLab gold on https://gitlab.com/gitlab-com/marketing/community-relations/gitlab-oss/merge_requests/324. This would allows us to connect GitLab CI directly to GitHub (see https://about.gitlab.com/solutions/github/).

**Comment by quentinlesceller** [comment]
Just added `grin` and `grin-wallet` repository on GitLab https://gitlab.com/mimblewimble/. Looks like jobs are already running :) https://gitlab.com/mimblewimble/grin/pipelines. Next I need to adapt the CI to build for the corresponding OS.
