### ISSUE TITLE
croaring-rs dependency is out of date (needs updating to latest release)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2693]
Opened a PR against croaring-rs to update the git submodule to use the most recent unity build of croaring - https://github.com/saulius/croaring-rs/pull/46

Tracking it here so we don't forget about this.

**Comment by frostRed** [comment]
Can you update croaring to 0.4.1?
There will be problems when compiling with rdkafka at the same time. rakafa-sys depend higher version bindgen. But grin depend croaring-rs and lower bindgen. It cause a Clang static link problem.

**Comment by quentinlesceller** [comment]
It seems like updating to 0.4.1 is not exactly straightforward since [`croaring-rs 0.4.1`](https://github.com/saulius/croaring-rs/releases/tag/0.4.1)
> Bitmap#minimum, Bitmap#maximum, Treemap#minimum, Treemap#maximum now return an Option making them more Rusty.
