### ISSUE TITLE
Question about basic MimbleWimble Transactions

### ISSUE THREAD

**Issue by ariesunny** [mimblewimble/grin#2701]
Hi There, a question about basic MimbleWimble Transactions

Let's condsider A send a MW transaction to B
* A choose a UTXO like V\*H + R1\*G and A info the parameter V and R1 to B
* B build a output like V\*H + R2\*G and B info the parameter R2 to A.
* Outpur minus the Input as (V\*H + R2\*G) - (V\*H + R1\*G) = ( R2- R1)\*G, where (R2-R1) is the private key and  ( R2- R1)\*G is the public, Both A and B could sign the transaction with the private key and everyone else could verify by the public key.

The question is if A ---the sender aware the Receiver's key R2,  so A could spend the output UTXO again, is that true?

If A don't aware the R2, how could A sigh the transaction by the private key inside this transaction?

Thank you!

**Comment by GandalfThePink** [comment]
Sender and receiver never exchange their keys. Instead they use a Schnorr multi-signature to interactively create a valid signature to (R2 - R1)*G. When asked to sign a different message to the same public key they cannot do that, unless they interact with each other again. More info on Schnorr multisigs to be found here: https://blockstream.com/2018/01/23/musig-key-aggregation-schnorr-signatures/ . This nicely explains the basic concept, why it is not secure in the simplest implementation and if you are interested also how this can be made secure. 

But if sender somehow gets possession of R2, they they could spent the UTXO.

**Comment by ariesunny** [comment]
Hi @GandalfThePink, Thanks, I read basic concept of Schnorr multisig a few months ago. 
Is the following understanding right: Here R1\*G  and R2\*G works like the temporary public key in schnorr mult-signature and come out with a signature which can be verified by R1\*G  and R2\*G together?
Is Grin using Schnorr Multi-signature? 
And is there other solution of this question?
Thank you.

**Comment by ignopeverell** [comment]
The actual key exchange is documented here:

https://github.com/mimblewimble/grin/blob/master/doc/contracts.md#trustless-transactions
https://github.com/mimblewimble/grin/blob/master/doc/wallet/transaction/basic-transaction-wf.png

Perhaps we're missing some references to those docs.
