### ISSUE TITLE
Clarify /tmp use

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#2709]
Is it necessary to use /tmp for downloading txhashsets?

See https://www.grin-forum.org/t/chain-building-stuck-at-58/4553 for more info

**Comment by antiochp** [comment]
Related - https://github.com/mimblewimble/grin/pull/2685

There is no specific reason we went with `$TMPDIR` beyond using a standard location. But as mentioned in the forum we have some fairly specific disk space requirements so want to ensure we use a disk with sufficient space.

It sounds like we may want to consider using a grin specific `tmp` dir under `~/home/.grin/main` or something similar?

I do think we need to segregate the `sandbox_dir` and/or `tmpdir` from our mainnet/floonet `chain_data` or `chain_data/txhashset` dirs.

**Comment by kargakis** [comment]
At a minimum we should document this somewhere prominently.

**Comment by garyyu** [comment]
Interesting!
Agree to use a grin specific `tmp` dir under `~/.grin/main/tmp` for mainnet and `~/.grin/floo/tmp` for floonet.
Also a specific `sandbox` dir under `~/.grin/main/tmp/txhashset`.

It deserve a dedicated PR to fix all these `folder`  name / location issues. And let #2685 purely only for the sandbox fixing.

**Comment by kargakis** [comment]
Fixed by https://github.com/mimblewimble/grin/pull/2772
