### ISSUE TITLE
Request for owner_api configuration in confiuration file

### ISSUE THREAD

**Issue by Julia-Beavan** [mimblewimble/grin#2727]
Owner_api is listen in 127.0.0.1  . how can i access through ip .  All the rest of the server listen addresses are in the configuration except that one. It is for compatibility with docker/cloud. Because need to access the owner_api form different container.

**Comment by kargakis** [comment]
> Because need to access the owner_api form different container.

You should be able to expose the port of the container running the owner api and you get access to the wallet at the container network level. Then, you need an additional route that you should be able to setup via the loadbalancing method offered by the platform you use.

**Comment by hashmap** [comment]
See https://github.com/mimblewimble/grin/issues/2663 (and some others)
It's recurrent question, perhaps we need to address it somehow. However the wallet has been moved to https://github.com/mimblewimble/grin-wallet, I'm closing this issue, feel free to open a discussion there.
