### ISSUE TITLE
1.0.3 do not sync! Rolled back to 1.0.2

### ISSUE THREAD

**Issue by TheBudda** [mimblewimble/grin#2729]
**Describe the bug**
"10 hours later and still waiting for sync to finish"
I have two nodes running on my two OVH dedicated servers. I compiled 1.0.3 with no issues. I have never had any issues before syncing and getting the node and wallet running

Rolled back to 1.0.2 and ever thing works within 15-20 mins on both servers! Please see Pastebin below for grin_server_logs

**To Reproduce**
1. Run "sudo ./grin"
2. Expect "sync"
4. See error: sync do not complete

**Relevant Information**
An excerpt from the logs or a detailed error message.

https://pastebin.com/t3AjzC7e

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 
 - Version 18.04

**Additional context**

**Comment by kargakis** [comment]
Seems like you are hitting the same issue as https://github.com/mimblewimble/grin/pull/2715#issuecomment-478907126

cc @yeastplume @garyyu

**Comment by hashmap** [comment]
Agree with @kargakis:

> ERROR grin_chain::txhashset::txhashset - hashset_replace fail on txhashset. err: Invalid cross-device link (os error 18)

perhaps we need 1.0.4

@TheBudda Totally unrelated - I would recommend to just run `./grin`, why do you need sudo?

**Comment by TheBudda** [comment]
@hashmap  I tried running./grin with sudo, without sudo & root still got the same results

**Comment by hashmap** [comment]
@TheBudda sure, it was unrelated to this issue, it’s generally less secure

**Comment by kbs1** [comment]
@TheBudda this issue can be solved by running `TMPDIR=/normal/user/dir ./grin`, just tried it now, synced in minutes on 1.03. Grin uses this dir to store and extract txhashset.

**Comment by pedroapero** [comment]
> Agree with @kargakis:
> 
> > ERROR grin_chain::txhashset::txhashset - hashset_replace fail on txhashset. err: Invalid cross-device link (os error 18)
> 
> perhaps we need 1.0.4
> 
> @TheBudda Totally unrelated - I would recommend to just run `./grin`, why do you need sudo?

Got the same issue, I can't sync since 1.0.3 because I symlinked ~/.grin to another place.

**Comment by garyyu** [comment]
fixed by https://github.com/mimblewimble/grin/pull/2753
