### ISSUE TITLE
Outputs by id failed: Request error: Wrong response code: 414 URI Too Long 

### ISSUE THREAD

**Issue by rentenmark** [mimblewimble/grin#2746]
**Describe the bug**
during the refresh of the wallet balance, the node returns a 414 error code.

**To Reproduce**
It is definitely difficult to reproduce, for some reason it is transient. Re-building the wallet from seed "fixes" this problem for a while, probably until there are some number N of new incoming transactions.

I readily admit that I don't have full reproduction steps but it has something to do with the batching of outputs by id during the refresh. Thankfully, the logs that we added proved my theory that the url was too long.

**Relevant Information**

```
20190410 20:13:47.367 ERROR grin_wallet::node_clients::http - Outputs by id failed: Request error: Wrong response code: 414 URI Too Long with data Body
20190410 20:13:47.367 ERROR grin_wallet::libwallet::api - failed to refresh outputs for wallet with error : Error { inner:

Client Callback Error: Getting outputs by id: Request error: Wrong response code: 414 URI Too Long with data Body }
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.10 running inside docker 

**suggested fix**

Remove batching in get_outpts_by_id and add a POST parameter make the wallet POST the list of outputs to the get_outputs_by_id node endpoint.

**Comment by antiochp** [comment]
Oof.
