### ISSUE TITLE
If we have a minimum tx fee - what is incentive for spending all outputs in wallet?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#276]
Why would a wallet impl build a tx that spends the maximum number of outputs?
There will be a minimum number of outputs that minimizes the fee (based on inputs vs outputs).

So other than "keeping the UTXO set as small as possible is a good thing" - what's in it for a wallet to do more than this?

It may actually be beneficial fee wise to _not_ spend all the outputs so the wallet can then seek to spend many outputs in a later tx to minimize the fee there also?

i.e. I have 10 outputs. I can spend them all in a single tx (leaving a single change output). Or I can spend 5 (and minimize the fee) and then spend the other 5 in the next tx (and minimize the fee there also).

**Comment by ignopeverell** [comment]
Correct, that would be a perfectly sane way to do it. And that's still aligned with "keeping the UTXO set small" as long as creating outputs is a lot more expensive than destroying them.

**Comment by antiochp** [comment]
Ah ok - so the current wallet impl of "aggressively try and spend 500 outputs" is just a starting point.
The real wallet impl is likely to be smarter in terms of fee management.
