### ISSUE TITLE
all api requests will get stuck before the send transaction connection times out

### ISSUE THREAD

**Issue by wsnbbxy** [mimblewimble/grin#2777]
When sending a transaction via http, if the recipient does not respond, all other api requests will get stuck before the connection times out.
grin 1.0.1

> 09:49:49.886 DEBUG grin_wallet::libwallet::internal::selection - Building change outputs: total change: ******** (1 outputs)
09:49:49.964 DEBUG grin_core::libtx::build - Building output: **********, Commitment(*******************)
09:49:50.095 INFO grin_wallet::controller - Tx created: *** grin to http://g.bdeals.btcex.center:3415 (strategy 'false')
09:49:50.095 DEBUG grin_wallet::adapters::http - Posting transaction slate to http://g.bdeals.btcex.center:3415/v1/wallet/foreign/receive_tx
09:50:03.617 ERROR grin_wallet::adapters::http - Posting transaction slate (is recipient listening?): Request error: Cannot make request: an error occurred trying to connect: Connection timed out (os error 110)
09:50:03.617 ERROR grin_wallet::controller - Request Error: Error { inner: 
Client Callback Error: Posting transaction slate (is recipient listening?): Request error: Cannot make request: an error occurred trying to connect: Connection timed out (os error 110) }

**Comment by quentinlesceller** [comment]
v1.x.x issue. Closing. Feel free to comment here if you feel like this issue is still relevant.
