### ISSUE TITLE
Max peer count config option is ignored

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#2781]
Currently the max peer count is hardcoded in grin and the config option does not really work.
```
$ cat ~/.grin/main/grin-server.toml | grep -i peer_max_count
peer_max_count = 60
$ grin client status

Grin Server Status
--------------------------
Protocol version: 1
User agent: MW/Grin 1.1.0-beta.2
Connections: 79
Chain height: 146209
Last block hash: 0000158efd06b6f711ac45542eedfada96d04d14db39aca89a83754594e67074
Previous block hash: 0000056eccec597bd6b801f8f969ede6f9541b1faacdfb7998f8cb2233f41f37
Total difficulty: 442904519251186
```

**Comment by hashmap** [comment]
This option is not ignored, but we allow new peers even if the limit has been reached. We remove the excess (randomly selecting peers) every n seconds. As result we can see more peers from time to time for a short period of time.

**Comment by kargakis** [comment]
> This option is not ignored, but we allow new peers even if the limit has been reached. We remove the excess (randomly selecting peers) every n seconds. As result we can see more peers from time to time for a short period of time.

At the very least, this behavior should get documented. Though to be honest, it sounds counterintuitive to have a max field that can be exceeded. It certainly makes resource planning harder for the cloud.

I have been monitoring my GCP node and it never gets below 60 peers, ranges between 60+ to ~110.

**Comment by kargakis** [comment]
I set max_peer_count to 40 now, still seeing this weird behavior where peers drastically go up and down in a matter of seconds. Built from https://github.com/mimblewimble/grin/commit/304ae444ab993cbc5a37ec7b12161451fa140ec9. This is a node running on GCP, I don't see the same behavior in a node running on my laptop, so may be related to the GLB acting up? I wouldn't expect the ramp up to be related to it tbh.
[grin-server.log](https://github.com/mimblewimble/grin/files/3124906/grin-server.log)

![vokoscreen-2019-04-28_12-05-49](https://user-images.githubusercontent.com/3900799/56863498-b7c6dd00-69ae-11e9-8c60-b15b2bc20116.gif)

**Comment by kargakis** [comment]
seems my gcp node has mysteriously stabilized below 40 peers in the past two days (19 currently)

¯\\_(ツ)_/¯
<img width="778" alt="Screenshot 2019-05-09 at 13 57 55" src="https://user-images.githubusercontent.com/3900799/57455270-af9a5780-7262-11e9-9ae3-ba369ed69419.png">

**Comment by quentinlesceller** [comment]
@kargakis is this issue still relevant?

**Comment by antiochp** [comment]
We have had some changes recently that affect this.
Specifically https://github.com/mimblewimble/grin/pull/2985 and https://github.com/mimblewimble/grin/pull/2993

The config has changes as we now make more of clear distinction between _inbound_ and _outbound_ connections and configure these separately.

**Comment by kargakis** [comment]
I don't see this issue in 2.0 anymore, closing
