### ISSUE TITLE
Add block height to handshake

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2789]
Since our sync process has come to rely on knowing the height of our peers, and not just total difficulty, it would be beneficial to know this information when we first connect to a peer. This will help with initial sync, since we won't have to wait for ping/pong to determine network height. Closes https://github.com/mimblewimble/grin/issues/1779

**Comment by antiochp** [comment]
This is tagged as `consensus breaking` but its more that old and new peers will not necessarily be able to talk to each other during hand/shake is the msg format changes.

Maybe we can think about ways of doing this in a backward compatible way? So we are not limited to releasing this during as part of a HF?

**Comment by DavidBurkett** [comment]
Yep, it was marked consensus breaking just to draw attention to the fact that it could cause a network split if not implemented carefully.

I'll have to look how we do it, but as long as we don't fail when a peer sends us a 'hand' message larger than we're expecting, we could just add the field to the end and not cause any connection issues. It'd be really nice to get some kind of version added to the message sometime in the future though.

**Comment by quentinlesceller** [comment]
Is it still needed?

**Comment by quentinlesceller** [comment]
Closed for #3167.
