### ISSUE TITLE
got Wallet serialization error while send

### ISSUE THREAD

**Issue by alden-alvins** [mimblewimble/grin#2795]
I am facing  **Wallet store error: Serialization Error**. While i send amount from my wallet (floonet) . I face the following issue.

**ERROR grin_wallet::controller - Request Error: Error { inner:

Wallet store error: Serialization Error }**

It locks amount but some small amount in spendable . while i cancel txs i got the amount back. Now  i am not able to send money from that account. 

Other commands are working properly. This seralization error happens only at the time of send . Wallet restore and wallet check commands are not helpful

**Comment by bladedoyle** [comment]
I see that error when making a large tx that contains "too many" outputs. (Im not sure exactly how many is too many).

A workaround is to "consolidate wallet outputs" before creating the large tx.   You can do that by sending a number of smaller tx to yourself.   For example, run this command some number of times:

```grin wallet send -o 1 -d localhost -m self -s smallest 2000```

Im providing a workaround in case it helps somebody, not suggesting that this isnt a bug.   Clearly it should be possible to send a large tx without needing workarounds.

**Comment by quentinlesceller** [comment]
Closing since it's not related to `grin` repo. Feel free to reopen it on the `grin-wallet` repo.
