### ISSUE TITLE
Determine wallet import/export format

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#28]
One difficulty with MimbleWimble is that to find one's UTXOs, both the private key and the amounts must be known. There's plenty of solution for private key backup and exports, including HD, but amounts is a MW specific issue. Exporting a list of amounts is possible but ergonomically complicated, especially if we still want to support paper wallets.

Brute-forcing the value space is a possibility, but with 8 or 10 significant numbers could take a prohibitively long time. One improvement could be to have wallets restrict the ranges of amounts it handles and maybe enforcing it through the range proof. A better idea may be to combine a HD type root key with a small bloom filter (32 bytes for example) for values. Brute forcing the Bloom filter would be very fast, reducing drastically the space of values that have to be explored with each HD derivation.

**Comment by JohnnSebastian** [comment]
Can UTXO get pushed back on to the visible chain ? So the set you spend is actually the ECC of (STXO+ key) and a Previous (ECCkey+key), again one input of a (ECCkey+key) etc where the above ECCkey is a (Private key +  (ECCkey+key)), public UTXO could be used to cryptographically lock previous ECCkeys , where one 'key' is derived from the wallet's virtual keyboard and UTXO are pushed back on the visible chain to motivate the spend of older UTXO.  Coinbase transaction can create a data set of IN and OUT points, there uniqueness protected with block chain block nr and the mercle tree. Miners verify the singularity of a coin questioning validity of the public UTXO hash (Embedded is the ECC key) against - true number of IN en OUT created on time stamp / block chain nr / amount of ECCkeys in block + mercle root. So a UTXO pushed publicly is 1unit of account and hash signature with additional hash value ...  ? Coins would become 1 unit of account - again with the possibility to submerse some math ?   Does this solve the problem ?

**Comment by Niondir** [comment]
To get this clear: Let's assume I have my wallet A and a backup wallet B. Containing an address X (private key) with 2 coins.

Now I spend 1 coin using wallet A. I can no longer spend any coin from wallet B since it does not know the updated amount of address X?

**Comment by ignopeverell** [comment]
Correct. And forget the bloom filter idea from above, it doesn't make anything more compact.

However, using denominations, I believe it's possible from the information in wallet B to find wallet A again. Assuming you're using HD derivation, A would have X1 and you know B would be using X2. Denominations reduce the search space enough that brute forcing all possible amounts to find the output from X2 should be doable.

**Comment by apoelstra** [comment]
If you use a known key as the blinding factor for your final digit, in a base-4 rangeproof there are only four possibilities to grind through (and for the MSB it will usually be zero anyway, so no grinding at all). It's easy to recognize this and easy to encrypt the full value to yourself in that digit, in much the same way Elements has a message sidechannel in its rangeproofs.

**Comment by antiochp** [comment]
Could we extend the existing Output data to include the encrypted value (only readable by the owner of the output)?
The wallet would be responsible for managing the encryption key/keys (and include this in the wallet export).
Output could additionally include the pubkey used for the value encryption (would also help identify UTXOs as belonging to the wallet during recovery).

Apologies to @apoelstra - I don't fully follow what you are saying but maybe conceptually similar?

**Comment by yeastplume** [comment]
Since there are a lot of leeway in selecting the keys that make up a range proof, it's possible to use them to encode extra information if desired, I think elements turns this property into a 'channel' of sorts, but it would be possible to select a 'known' key or set of keys deterministically that you could then search range proofs for, which would mean that to search the UTXO set knowing only your keys but not values, in this scheme you'd have to grind through 4 values per range proof sitting on the chain to find all of them. 

Extending the output format is already suggested here:

https://lists.launchpad.net/mimblewimble/msg00165.html

Although this is more to do with future-proofing against quantum attacks, as a side-effect it makes it trivial to recognise one's own transactions on the chain.

No decision been taken yet as to whether this will be used.

**Comment by antiochp** [comment]
Thanks for the info - reading up on that thread later today - I see it mentions "switch commitments" which I saw you were working on recently. I've been meaning to investigate what these are.

**Comment by antiochp** [comment]
For reference - this is where the "sidechannel message" is set on a rangeproof in Elements - 
https://github.com/ElementsProject/elements/blob/8fed03f63ca2f46ea97e2f286a3bc46ce3087d6c/src/blind.cpp#L145

**Comment by antiochp** [comment]
We can now "rewind" range proofs as we use the original secret key used to generate the commitment as the nonce on the range proof (we pass in the `pubkey`) -

https://github.com/ignopeverell/grin/blob/3dd1dde00be73df764b2a4dcc7555d3f79b3edec/keychain/src/keychain.rs#L135

So if a wallet is able to identify which outputs belong to it (without needing to know the amounts) - we can rewind the attached range proofs and retrieve the amounts.

**Comment by sesam** [comment]
Minimal inputs for wallet recovery seem to be:

 * wallet.seed
 * password(s)
 * key iterations (`i`)

A wallet backup could contain a truncated hash(wallet.seed) and a padded list of passwords to partially hide how many different passwords have been in use by a wallet.seed owner.

During restore, the seed owner supplies the seed and the password(s).

[ ] Nice to have: Approximate min and max block heights to avoid reading the whole blockchain
[ ] Privacy: Not storing exact sums, heights or key ids (might appear in log files). Sums are recoverable from the block chain.

Do we need (want?) to store the key iteration integers?

If yes, The list of key iteration integers could be decrypted based on some combo of seed and passwords. To hide how many passwords have been in use, any `i` belonging to a password that was not fed into the recovery algorithm should be indistinguishable from padding to mitigate rubberhose attacks.

**Comment by antiochp** [comment]
Each `seed+password` is a separate "wallet". We may be able to allow multiple wallets to exist in a single `wallet.dat` but they are separate and I think it makes sense to restore each individually.

**Comment by sesam** [comment]
[dev chat discussed how to find a better wallet restore solution](https://gitter.im/grin_community/dev?at=5ab2d621c3c5f8b90d9c443f)
