### ISSUE TITLE
Cumulative difficulty should be based on network difficulty for each block, not hash

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#280]
Currently, difficulty is accumulated by using the block header hash as if it was the incremental difficulty to be added. This may cause issues as people can get very lucky with a solution. Adding the network difficulty calculated for that block is much more robust. Thanks to @tromp for pointing this out.

**Comment by yeastplume** [comment]
Agreed, it's easy to get something like a 9000 difficulty solution when all you need is 100 or something, will fix it shortly.

**Comment by ignopeverell** [comment]
Just make sure to only push it on `master` for now or it will hardfork `testnet1`.
