### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by notorious-clay** [mimblewimble/grin#2808]
**Documentation Bug**
In the Documentation **Introduction to MimbleWimble and Grin** at the part Ownership after the last example it says: _"But because 85*G is a valid public key on the elliptic curve G..."_

It should be on the elliptic curve C because G is the generator point.

**Comment by kargakis** [comment]
https://github.com/mimblewimble/grin/pull/2823 was just merged, this issue can be closed.
