### ISSUE TITLE
byteorder crate does not play nicely with our "non-blocking" IO

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2820]
Related #2819.

We jump through a lot of hoops with `read_exact` in our `util` crate to make sure we can safely and robustly read multiple bytes via non-blocking tcp streams.

But when we call the various low-level `byteorder` derived fns we skip this and go straight to the `read_exact` impl in `std::io::Read` -

https://docs.rs/byteorder/1.3.1/src/byteorder/io.rs.html#110-113

https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact

It seems like it is entirely possible for a u64 or other multi-byte value here to cause our non-blocking IO to fail on a partial read.
We can be in a situation where we read say 5 bytes of the 8 bytes of a u64 and return early with effectively corrupted data.

**Comment by ignopeverell** [comment]
Indeed, very good point.

**Comment by antiochp** [comment]
So there's actually a couple of layers of indirection going on here.

I think what is happening is the following - 

`p2p::msg::read_header` and `p2p::msg::read_body` both use our custom `read_exact`, reading off our non-blocking stream and writing the bytes (all the bytes) to a local vec of bytes.

https://github.com/mimblewimble/grin/blob/998824ecf3e0d8a53c26b93060cc8bba4f51a65d/p2p/src/msg.rs#L156-L160

We then read from this vec of bytes to actually deserialize the appropriate msg header or msg body.
This is when the `BinReader` comes into play.

And since we only start deserializing once we have a full vec of bytes we can safely make the assumption that we will never read partial bytes. We are not reading off a stream, we are reading from the intermediate vec of bytes which is filled before we begin.

Rust IO really is kind of janky as we do not get _any_ type safety here in terms of blocking/non-blocking behavior.
We pass a `Read` in but we don't know if `read_exact` will behave as expected or not as this is based on whether the `Read` is actually a `TcpStream` that has had `set_nonblocking()` called on it or not.

Q) In an ideal world would `BinReader` support a `Read` that is non-blocking?
This may be desirable in terms of "streaming" data, say reading a `BlockHeader` before deserializing the full `Block` etc.
