### ISSUE TITLE
grin wallet api slow when the number of txs become large

### ISSUE THREAD

**Issue by bitcodernull** [mimblewimble/grin#2828]
when my wallet have the hundreds of thousands txs， the  wallet api is becoming slower

how to optimization it？

thanks

**Comment by hashmap** [comment]
@bitcodernull from my experience one of the reasons is the refresh we do in the wallet, during a request we ask a node for a state of each output. This is reasonable when you don't have many outputs or you don't send too many requests to your wallet. For "pro" wallet I'd choose a different strategy - refresh the full state in background (eg every minute ask your node) and store the data on the wallet side. Then when a requests come you are ready to serve it immediately without consulting with the node. The downside of this approach is obvious, you need to implement and maintain a custom version of the wallet or extract this logic to a separate component. We did it in our payment processor.

**Comment by hashmap** [comment]
If it's still valid please open it in grin-wallet repo
