### ISSUE TITLE
Move keychain to grin-wallet repo

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin#2832]
In order to do this, we'll have to break libtx's dependence on keychain. In many cases, this will consist of passing in the calculated secret keys instead of the keychain. There are also a lot of tests across several libs that rely on keychain that we'll have to deal with.

**Comment by antiochp** [comment]
What's the rationale for doing this? I'm not that keen on passing secret keys around (which is why `keychain` originally came into existence).

**Comment by DavidBurkett** [comment]
There are 2 main rationales. 1) The keychain is not a part of the grin protocol, and therefore doesn't belong as part of the node. 2) Requiring a keychain for transaction building limits consumer's creativity to deal with keys, since they're required to provide a predefined API.

Passing secret keys is no different than passing a keychain. You could even argue it's safer, because the keychain gives you access to the root seed, whereas a calculated secret key may just be a specific derived child key. As long as you're passing by reference, and not cloning, you're certainly no worse off than you are today.

**Comment by jaspervdm** [comment]
How about moving it to a separate crate? For wallet713 we just managed to remove the grin-wallet dependency completely, it would be easier for us to import a crate for the keychain only, instead of a lot of code we don't really need.

**Comment by DavidBurkett** [comment]
@jaspervdm It already is a separate crate. I'm talking about moving the crate into the grin-wallet github repo, not the grin-wallet crate. Editing the issue name for clarity.

**Comment by antiochp** [comment]
> As long as you're passing by reference, and not cloning, you're certainly no worse off than you are today.

I'd argue that keeping private keys encapsulated behind the keychain api makes the code more flexible and less reliant explicitly on private keys being passed around. That was at least the direction we were moving in when we introduced the `keychain`.

The level of abstraction may be wrong with `keychain` but I don't think we should pass private keys around directly.

**Comment by quentinlesceller** [comment]
@antiochp argument makes sense. I will close this issue since there hasn't been any activity on it recently. Feel free to comment if you feel this is needed.
