### ISSUE TITLE
Grin hash rate calculation

### ISSUE THREAD

**Issue by RiyaKarthi** [mimblewimble/grin#2835]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. Expect '....'

**Relevant Information**
An excerpt from the logs or a detailed error message.

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 1.0.1]

**Additional context**

**Comment by RiyaKarthi** [comment]
What is the calculation for Total Estimated Hash Rate for AR29 and AT31

**Comment by bladedoyle** [comment]
@RiyaKarthi https://github.com/grin-pool/grin-pool/blob/d64c68b01ea1f72cb4263d6a30848c0316b560b2/grin-py/grinlib/grin.py#L85

**Comment by RiyaKarthi** [comment]
@bladedoyle Thanks. I got the gps.
