### ISSUE TITLE
Wallet Foreign RPC returning escaped JSON

### ISSUE THREAD

**Issue by jseibel-circle** [mimblewimble/grin#2840]
**Describe the bug**
This happens in the latest beta release, not the latest real release.

When you hit the `/v1/wallet/foreign/receive_tx` endpoint with a valid JSON body, you get back escaped JSON. Very weird

**To Reproduce**
1. Start foreign wallet RPC
2. POST to `/v1/wallet/foreign/receive_tx` with valid JSON transaction body
3. Receive escaped JSON rather than normal JSON

**Relevant Information**
```"{\"version_info\":{\"version\":2,\"orig_version\":2,\"min_compat_version\":0},\"num_participants\":2,\"id\":\"809703a1-ad95-42f8-96bc-1ebacaab21d5\",\"tx\":{\"offset\":\"8abb618bb0faa8feb3dd00ea4fff780b9dda67e800bbc6135a7fddcaf55656a6\",\"body\":{\"inputs\":[{\"features\":...``` received

**Screenshots**
![image](https://user-images.githubusercontent.com/43615265/58339929-a390c700-7e18-11e9-9ec0-74563f78b5f9.png)

**Additional context**
It's not an insurmountable problem but it's really weird

**Comment by kargakis** [comment]
@jseibel-circle please reopen this issue in [grin-wallet](https://github.com/mimblewimble/grin-wallet) even though I suspect that it won't be fixed at this point since the v1 api will be removed as part of the coming hard fork.

**Comment by mcdallas** [comment]
I beleive this is fixed in beta3 https://github.com/mimblewimble/grin-wallet/pull/114

**Comment by quentinlesceller** [comment]
Fixed closing.
