### ISSUE TITLE
endpoint to link all the other endpoints

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#286]
I have trouble remembering the exact format for all of the available endpoints and keep having to dig into the code to get them. Provide a single 'index' endpoint that displays all of the available endpoints. Can probably just serve up a simple html page from the disk, or if we want to get really fancy, probe all of the available endpoints from the router and build it up dynamically

**Comment by ignopeverell** [comment]
The REST purists always point out that all endpoints should be discoverable through links. So maybe automatically have `/v1` list all endpoints that have been added to hyper?

**Comment by antiochp** [comment]
Would be nice if the iron router allowed some kind of introspection to list the registered endpoints but it looks like all the routing internals are kept private.
Shouldn't be too much work to maintain our own state as we go through the routing initialization.
