### ISSUE TITLE
Documentation request: Upcoming hardfork user guide

### ISSUE THREAD

**Issue by casey** [mimblewimble/grin#2860]
I can't believe we're only ~6 weeks away from the first scheduled hard fork. Time does fly!

It might be nice to create some documentation/guidance for how different classes of users (miners, exchanges, individuals) should prepare for the fork, and what they'll need to upgrade and when.

One question that I have in particular is whether or not a pre-hardfork wallet will be able to talk to a post-hardfork node. I.e. will wallets need to be upgraded to transact post-hardfork?

Users might be more conservative with upgrades to software that touches private keys, so barring any vulnerabilities/security upgrades, it might be reasonable to avoid upgrading wallets, if they'll continue to work, and I'm curious if it will be safe to do so.

**Comment by bladedoyle** [comment]
Im also interested in being conservative with upgrades.   Im eager to update for bug and security fixes, but prefer not to risk for features.  Please retain backward compatability whenever possbile.

**Comment by casey** [comment]
This post by Quentin covers all the details:

https://www.grin-forum.org/t/grin-first-hard-fork-mid-july/5148

**Comment by casey** [comment]
To upgrade a wallet from v1 to v2, will it be necessary to restore it from the original seed phrase?

**Comment by lehnberg** [comment]
@casey no you replace the binary
