### ISSUE TITLE
Downloading Blocks 110%

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#2865]
(On **Floonet**) Now, my local Grin node is showing "Longest chain @141012 vs Us @155467",  "Downloading Blocks 110%, ..."

Happened several times in these days, and trying to understand the root cause. With the latest master branch source.

<img width="576" alt="Screen Shot 2019-05-30 at 4 21 05 PM" src="https://user-images.githubusercontent.com/1852227/58619538-ac413b80-82f7-11e9-951c-c91089ab3e4f.png">

<img width="1248" alt="Screen Shot 2019-05-30 at 4 20 56 PM" src="https://user-images.githubusercontent.com/1852227/58619573-b95e2a80-82f7-11e9-8f97-795369f7ead9.png">

**Comment by garyyu** [comment]
Check the peers, and find this `Longest Chain` peer:
```
{
"capabilities":{"bits":15},
"user_agent":"MW/Grin 1.0.3",
"version":1,
"addr":"54.148.113.184:13414",
"direction":"Inbound",
"total_difficulty":427388621917598,
"height":141012
}
```

It's quite strange why our banning mechanism doesn't work.  will look into the logs.

**Comment by antiochp** [comment]
Something weird going on with your peers there.

Looking here - 
https://grinscan.net/block/155466

total_diff: `470,779,341,967,660`

But your peer list is showing significantly lower total_diff values.

And here - https://grinscan.net/block/141012

total_diff: `427,388,621,917,598`

This looks correct.

According to your local peer data that one _is_ your most work peer.

**Comment by antiochp** [comment]
https://grinscan.net/block/141012

vs.

https://floonet.grinscan.net/block/155466

Somehow we have a `mainnet` node peering with your `floonet` node.

**Comment by garyyu** [comment]
Regarding why this peer hasn't been banned, I think the root cause is here:
```
		// Ban this fraud peer which claims a higher work but can't send us the real headers
		if now > *stalling_ts + Duration::seconds(120)
			&& highest_height == peer.info.height()
		{
			self.peers
				.ban_peer(peer.info.addr, ReasonForBan::FraudHeight);
			...
```

`highest_height == peer.info.height()` <-- this only handle the case of a peer with higher height than us, but in this issue, the peer `54.148.113.184` has a lower height but with much more work.

**Comment by garyyu** [comment]
And regarding the wrong peer (`mainnet` node peering with `floonet` node) , here is the log:
```
20190530 17:58:59.878 TRACE grin_p2p::serv - connect_peer: on 0.0.0.0:13414. connecting to 54.148.113.184:13414
20190530 17:58:59.880 TRACE grin_servers::grin::seed - monitor_peers: on 0.0.0.0:13414, queue to soon try 54.148.113.184:13414
20190530 17:59:01.888 DEBUG grin_servers::grin::seed - peer_connect: ignore a duplicate request to 54.148.113.184:13414. previous connecting time: 09:58:59.878
20190530 17:59:01.889 TRACE grin_servers::grin::seed - monitor_peers: on 0.0.0.0:13414, queue to soon try 54.148.113.184:13414
20190530 17:59:03.955 DEBUG grin_p2p::peer - accept: handshaking from Ok(V4(54.148.113.184:34744))
20190530 17:59:03.955 TRACE grin_p2p::handshake - Success handshake with 54.148.113.184:13414.
20190530 17:59:03.955 DEBUG grin_p2p::peers - Saving newly connected peer 54.148.113.184:13414.
20190530 17:59:03.955 DEBUG grin_p2p::store - save_peer: PeerAddr(V4(54.148.113.184:13414)) marked Healthy
20190530 17:59:09.882 TRACE grin_p2p::serv - connect_peer: on 0.0.0.0:13414. Could not connect to 54.148.113.184:13414: Custom { kind: TimedOut, error: StringError("connection timed out") }
20190530 17:59:11.130 DEBUG grin_servers::grin::sync::header_sync - sync: request_headers: asking 54.148.113.184:13414 for headers, [075497419619, 06f37000b920, 1ac16bbbfff7, 15be333c639d, 04e54bb68599, 21e2c6b20bfb, 20e87286d52f, 1cdb02b3c3ac, 152d0a26a97d, 0024efe83f87, 020e4004839f, 185b5a2d39fc, 3525936f496d, 0469a36334d1, 24b381ae757b, 005e4a602819, 00b051502578, edc758c1370d]
20190530 17:59:11.141 DEBUG grin_servers::grin::sync::header_sync - sync: request_headers: asking 54.148.113.184:13414 for headers, [075497419619, 06f37000b920, 1ac16bbbfff7, 15be333c639d, 04e54bb68599, 21e2c6b20bfb, 20e87286d52f, 1cdb02b3c3ac, 152d0a26a97d, 0024efe83f87, 020e4004839f, 185b5a2d39fc, 3525936f496d, 0469a36334d1, 24b381ae757b, 005e4a602819, 00b051502578, edc758c1370d]
20190530 17:59:21.143 DEBUG grin_servers::grin::sync::header_sync - sync: request_headers: asking 54.148.113.184:13414 for headers, [075497419619, 06f37000b920, 1ac16bbbfff7, 15be333c639d, 04e54bb68599, 21e2c6b20bfb, 20e87286d52f, 1cdb02b3c3ac, 152d0a26a97d, 0024efe83f87, 020e4004839f, 185b5a2d39fc, 3525936f496d, 0469a36334d1, 24b381ae757b, 005e4a602819, 00b051502578, edc758c1370d]

```

`handshake - Success handshake with 54.148.113.184:13414`. So I think it's that node's problem.
