### ISSUE TITLE
FlooNet chain fork and Orphans

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2870]
**Describe the bug**
Seeing frequent chain forks and orphans on floonet

**To Reproduce**
Mine on floonet

**Relevant Information**
As soon as grinmint added a floonet pool (meaning more than one miner running on floonet) we started to see chain forking resulting in orphaned blocks.

**Screenshots**
Yes, attached.   The arrow point at chunks of orphans, represented by dashed vertical lines on the graph.
See Also:  https://mwfloopool.com/

**Desktop (please complete the following information):**
```
root           8       1 24 May19 ?        2-22:40:01 grin --floonet server run
# grin --version
grin 1.0.3
```

**Comment by bladedoyle** [comment]
![floonetorphans](https://user-images.githubusercontent.com/7017666/58683673-d1b85e80-8364-11e9-9f3f-cafeb2c930d4.png)

**Comment by jaspervdm** [comment]
This is expected to happen if the hashrate suddenly increases by a lot. When the network difficulty hasn't caught up yet, blocks will be produced at a much higher rate, resulting in more orphans than usual. It should stop happening after the difficulty has caught up.

**Comment by bladedoyle** [comment]
The orphans occur at periods where the gps rate is not increasing.

![floonetorphans](https://user-images.githubusercontent.com/7017666/58716984-bb88bd80-83b9-11e9-9e0b-83123b2ce0ba.png)

**Comment by bladedoyle** [comment]
Large groups of orphans continue to occur.   This graph is the network graph rate from today - @jaspervdm  they occur during periods of stable graph rate, not as grapg rate is suddenly increasing.   

![image](https://user-images.githubusercontent.com/7017666/59080131-c28e5f00-88d6-11e9-937e-af4c230e9361.png)

**Comment by quentinlesceller** [comment]
@bladedoyle is it still happening?

**Comment by yeastplume** [comment]
Closing, not updated and outdated
