### ISSUE TITLE
transaction always unconfirmed, I am sender

### ISSUE THREAD

**Issue by ciaos** [mimblewimble/grin#2872]
**Describe the bug**
Transactions can't be confirmed. Can't send grins to anyone. 

**To Reproduce**
1. version 1.0.2
2. I can send to self.
3. I can't send to another(hotbit、gateio...) since the transaction always keeps unconfirmed.

Does the problem relates with the performance of machine？

**Comment by ciaos** [comment]
Does the problem relates with performance of machine？

**Comment by bladedoyle** [comment]
How do you perform the send?   Commandline or using the REST API?
You need to have a grin server node running and fully synced for the wallet to broadcast the tx to the blockchain.  If you stop your node before it has a chance to broadcast the tx it will never be confirmed.

**Comment by ciaos** [comment]
I send using REST API and there was no error log. I found my node always slower than main net explorer by 3~4 blocks.

**Comment by bladedoyle** [comment]
Ah, then you need to make an extra api call to post the transaction.
Yes, its very confusing that the commandline and API have different call flows.
Using the commandline, the "finalize" also posts the tx.
But using the REST API, "finalize" and "post" are two separate calls.

See:  https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#post-post-tx
