### ISSUE TITLE
no pending block request, asking more

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2885]
**Describe the bug**
floonet grin server node  entered a loop repeating the following message ~100 times per second.

```
20190609 23:23:02.345 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
20190609 23:23:02.346 DEBUG grin_chain::chain - body_sync: body_head - 14bc29539239, 169090, header_head - 14bc29539239, 169090, sync_head - 19edba70b195, 169079
```

It appears that mining continues to work.  Grepping out that message, the rest of the log seems normal.  

**Relevant Information**
```
# grin --version 
grin 1.0.3
```
Restarting the server process seems to have resolved the issue

**Comment by jaspervdm** [comment]
This happened to me on 1.0.3 as well, havent seen it yet on 1.1.0

**Comment by bladedoyle** [comment]
1.1.0 is too unstable to use

**Comment by bladedoyle** [comment]
Im starting on the v1.1.0 update process.   Should I stop reporting v1.0.x issues?   Is there any chance they will be looked at, or is the focus moved entirely to v2?

**Comment by jaspervdm** [comment]
It is worth reporting if the issues persist in v1.1

**Comment by bladedoyle** [comment]
re: "havent seen it yet on 1.1.0"

Probably safe to assume if you cant identify the commit that fixed it the problem most likely still exists.

**Comment by quentinlesceller** [comment]
Closing since it's a v1 related issue. Feel free to reopen if it happens on v2.
