### ISSUE TITLE
Can't Deserialize slate

### ISSUE THREAD

**Issue by litterGuy** [mimblewimble/grin#2887]
**Describe the bug**
When sending using the "/v1/wallet/owner/issue_send_tx" interface, the following error is returned.

> 20190610 06:39:09.955 INFO grin_wallet_controller::controller - Tx created: 2.551397380 grin to https://poloniex.com/public?currency=GRIN (strategy 'true')
20190610 06:39:09.955 DEBUG grin_wallet_impls::adapters::http - Posting transaction slate to https://poloniex.com/public?currency=GRIN/v1/wallet/foreign/receive_tx
20190610 06:39:10.260 ERROR grin_wallet_controller::controller - Request Error: Error { inner: 
Can't Deserialize slate }

**Desktop (please complete the following information):**
 - OS: linux ubuntu 16
 - Version ：grin wallet： v1.1.0

**Comment by mcdallas** [comment]
I think you need to add `"target_slate_version”:0` to the json because the api defaults to v2 slates and apparently poloniex use the old grin version that doesn't support them.

Also please use https://github.com/mimblewimble/grin-wallet for wallet issues

**Comment by DavidBurkett** [comment]
The last I tried, Poloniex doesn't work with any wallet newer than 1.0.2, regardless of target_slate_version. I submitted a ticket to their support team which  responded to 10 days later telling me they weren't going to dedicate resources to fixing it. :-)

**Comment by litterGuy** [comment]
The problem has moved here：https://github.com/mimblewimble/grin-wallet/issues/145
