### ISSUE TITLE
help - going back and forth between v1.1.0 and v1.0.3 server and wallets messed up my wallet, can't recover, check doesn't help

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin#2896]
I don't know if this is a grin or grin-wallet issue. I described it it depth here: https://github.com/mimblewimble/grin-wallet/issues/150 so I'm just linking here.

**Comment by bladedoyle** [comment]
You will have to restore it from seed.

**Comment by hashmap** [comment]
Sounds like wallet issue, closing for now
