### ISSUE TITLE
Grins, transactions, outputs lost after recover.

### ISSUE THREAD

**Issue by ciaos** [mimblewimble/grin#2904]
**Describe the bug**
I got some error when running check command. It seems like some bad block data. So I delete all files in /root/.grin directory. But I can't restore my grins using the same passphrase and seed file (I backed up wallet.seed and passphrase).

Neither "grin wallet check" nor "grin wallet restore" commands worked
grin wallet info show 0 balance (my node was fully synced)

**Comment by ciaos** [comment]
I found outputs and balance can be restored, but transaction history may not be recovered.

**Comment by antiochp** [comment]
> but transaction history may not be recovered.

Yes. By design - the transaction history is not recorded on-chain and there is nothing to recover.
