### ISSUE TITLE
libtinfo.so.5: no version information available 

### ISSUE THREAD

**Issue by jmliz** [mimblewimble/grin#2911]
**Describe the bug**

node sync stuck at step 2/4

console shows this:

./grin    
./grin: /lib64/libtinfo.so.5: no version information available (required by ./grin)
./grin: /lib64/libncursesw.so.5: no version information available (required by ./grin)
./grin: /lib64/libncursesw.so.5: no version information available (required by ./grin)

I am using Fedora workstation 30. Package ncurses-compat-libs-6.1-10.20180923.fc30.x86_64 is already installed.

**Comment by GHLover** [comment]
I can't help you, but I have had the same issue. I wish Grin would either statically build or remove the dependencies on those libraries.

Or, at a minimum, provide instructions on how to statically build grin in the build docs.

**Comment by quentinlesceller** [comment]
Related to #2977.

**Comment by quentinlesceller** [comment]
Fix is mentioned in #2977:

```
sudo dnf install ncurses-compat-libs
```
