### ISSUE TITLE
txhashset zip files and directories are never cleaned up

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2924]
**Describe the bug**
The grin server creates an endless number of "txhashset" zip files and directories and never cleans them up.  This results in wasted disk space, and possibly a full filesystem.  Grin sesrver disk use should *not* grow without bounds, or require constant cleanup effort.

**To Reproduce**
Run a grin server.

**Relevant Information**
```
...
...
drwxr-xr-x  5 root root      4096 Jun  9 04:34 txhashset_zip_935344
-rw-r--r--  1 root root 236080368 Jun  9 04:34 txhashset_snapshot_935344.zip
drwxr-xr-x  5 root root      4096 Jun  9 13:18 txhashset_zip_343629
-rw-r--r--  1 root root 236896057 Jun  9 13:18 txhashset_snapshot_343629.zip
drwxr-xr-x  5 root root      4096 Jun  9 13:48 txhashset_zip_812186
-rw-r--r--  1 root root 237036731 Jun  9 13:48 txhashset_snapshot_812186.zip
...
...
```
and
```
root@grin-0:/server# du -h .grin
...
26G	.grin
```

**Comment by garyyu** [comment]
This had been fixed since v1.1.0.
I guess you're looking an old version server.
See PR and related history: https://github.com/mimblewimble/grin/pull/2771

**Comment by antiochp** [comment]
v1.1.0 and later versions generate zip files with a block hash in the name (not a simple number) - 

```
txhashset_snapshot_003e45a7da97.zip
```

That dir listing definitely looks like an old version of the code.

**Comment by bladedoyle** [comment]
Yes, this is seen in 1.0.3.  I didnt find any resolved issues for this so I didnt realize it had been fixed.
Closing now.
