### ISSUE TITLE
txhashset archive save to file fail (connection closed)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2929]
Added some logging to the txhashset download so we can track progress via the log file (on the 2.x.x branch) - 

```
20190628 09:40:09.321 DEBUG grin_p2p::peer - Asking 67.207.70.122:3414 for txhashset archive at 231880 000018532638.
20190628 09:40:14.687 DEBUG grin_p2p::protocol - handle_payload: txhashset archive for 000018532638 at 231880. size=253592404
20190628 09:40:25.693 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 2976000/253592404
20190628 09:40:36.748 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 9072000/253592404
20190628 09:40:47.769 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 16944000/253592404
20190628 09:40:58.829 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 24384000/253592404
...
20190628 09:49:02.918 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 238656000/253592404
20190628 09:49:14.008 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 245472000/253592404
20190628 09:49:25.148 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 250128000/253592404
20190628 09:49:36.447 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 251232000/253592404
20190628 09:49:38.456 ERROR grin_p2p::protocol - handle_payload: txhashset archive save to file fail. err=Connection(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
```

I have seen the above scenario a few time now. We download what appears to be _almost_ all the bytes and then the connection is dropped.

Seems like too much of a coincidence that we get _so close_ to getting the whole file and then fail to save it with a "connection closed" (like 99% of the way there on multiple occasions).

I _suspect_ we actually have all the bytes and that the connection is getting closed on the sending side as soon as it has sent everything over (for whatever reason).
We must be able to do something smarter on the receiving side to handle this more robustly.

Related - #2639.

**Comment by antiochp** [comment]
Here's another instance of it happening - 

```
...
20190628 10:11:09.139 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 261024000/275364910
20190628 10:11:20.201 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 266400000/275364910
20190628 10:11:31.297 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 271008000/275364910
20190628 10:11:37.064 ERROR grin_p2p::protocol - handle_payload: txhashset archive save to file fail. err=Connection(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
```

We log the update msg every 10s so here again we got within 10s of completing the download and the connection mysteriously dropped on the other end.

I would bet "several minutes worth of Grin" that we actually received the full file and then our connection handling caused it to fail to save successfully.

**Comment by hashmap** [comment]
Can confirm, saw it recently. Will also check how we handle it.

**Comment by antiochp** [comment]
@hashmap My understanding of our current threading model is as follows (please correct me if this is wrong) - 

* bunch of peer threads _receiving_ msgs from our peers
* some arbitrary thread _sending_ data out to peers (broadcast of block or tx etc.

We do not use the individual peer threads to actually send data out to our peers.
But we may receive a tx from one peer and then use the thread corresponding to that peer to broadcast out to all our other peers.

But in the case of msgs that have a _response_, like the txhashset request we _do_ use the same thread to send data back to that peer.
So we receive a txhashset request on the thread corresponding to a particular peer and then we use that same thread to "reply" to that peer, effectively locking that thread up for an extended period of time (as you mention in #2930).

I wonder if we should consider spawning a separate thread for long running "replies" like the txhashset response?

**Comment by mmgen** [comment]
This is an issue primarily for high-latency connections. It's easily solved by increasing the constant IO_TIMEOUT (in p2p/src/conn.rs) to 10000 milliseconds.

**Comment by mmgen** [comment]
Still observing this with freshly-compiled client (master branch).  When remote peer is a v1 client, DL gets to 99% and then fails with "connection reset by peer":

        201911DD HH:MM:SS.nnn DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 484608000/489598372
        201911DD HH:MM:SS.nnn ERROR grin_p2p::protocol - handle_payload: txhashset archive save to file fail. err=Connection(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })

This appears to be a problem with v1 clients, so is obviously unfixable at this point, unless the fix is backported and users agree to upgrade.

When remote peer is v2, I'm observing even stranger behavior:  The download begins normally, but after 30 seconds or so the peer just stops sending data. The connection remains open, no error is reported, but the data flow just stops.

Both errors have been observed multiple (10x) times, and the behavior is always the same.

As a result, I'm unable to get past stage 2 of the IBD process.

**Comment by quentinlesceller** [comment]
@antiochp any update on that issue? Is this still relevant?

**Comment by mmgen** [comment]
> @antiochp any update on that issue? Is this still relevant?

Don't know. I haven't fired up a fresh Grin node in awhile. Perhaps I'll do so in the coming days.

**Comment by antiochp** [comment]
I'm going to close this for now. I believe this is fixed in `3.x.x`.
If we see this behavior or something similar we can reopen a new issue.
