### ISSUE TITLE
the foreign api needs basic auth when using owner_api

### ISSUE THREAD

**Issue by viteshan** [mimblewimble/grin#2941]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. Expect '....'

**Relevant Information**
An excerpt from the logs or a detailed error message.

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 1.0.1]

**Additional context**

**Comment by viteshan** [comment]
and this causes the send_tx_sync method to fail.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin-wallet/pull/218
