### ISSUE TITLE
Expose the `Basic Status > Current Status: Running` field in the Node API

### ISSUE THREAD

**Issue by nijynot** [mimblewimble/grin#2946]
**Is your feature request related to a problem? Please describe.**
Expose the `Basic Status > Current Status: Downloading headers.../Running/etc.` field in the Node API.

GUI wallets need to connect or sync to a node before actually being usable, so it'd be good UX wise to show something happening while syncing. Displaying the `Current Status` then makes sense.

**Describe the solution you'd like**
Add a `status`/`currentStatus` prop to the `v1/status` API call.

**Comment by antiochp** [comment]
We have access to the `sync_state` from the `server` itself should this should be relatively simple to expose via the api.

**Comment by quentinlesceller** [comment]
I think the issue is that the `servers` crate import the ` api` crate. Thus it's not possible to import the `SyncStatus` (cyclic import). Or I am missing something obvious?

**Comment by antiochp** [comment]
Ahh - I hadn't caught the issue here with circular dependencies.

We would need to rethink how to track the current status - maybe `chain` should be responsible for tracking this, rather than the top-level `server`.
