### ISSUE TITLE
Source archive file name

### ISSUE THREAD

**Issue by tomwijnroks** [mimblewimble/grin#2947]
**Problem:**
Source archives from grin and grin-wallet have the same file name: `v2.0.0.tar.gz`
```
https://github.com/mimblewimble/grin/archive/v2.0.0.tar.gz
https://github.com/mimblewimble/grin-wallet/archive/v2.0.0.tar.gz
```

**Solution:**
Prefix the source archive file name with grin and grin-wallet:
```
grin-v2.0.0.tar.gz
grin-wallet-v2.0.0.tar.gz
```

**Comment by quentinlesceller** [comment]
Hi @tomwijnroks. I understand that this URL comes from downloading directly the source as tar.gz from Github release. This URL is derived from the tag name directly (e.g. https://github.com/bitcoin/bitcoin/archive/v0.18.0.tar.gz fro Bitcoin). It's not possible to change it apart from changing the tag name which I don't think is judicious here. So I'm going to close this issue, feel free to comment if you see any other solution.
