### ISSUE TITLE
Wallet reconstruction feature

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#295]
Given that switch commits are in place, this should be fairly easy to do, (if a bit grindy) by checking all of the nodes in the utxo sumtree against possible key derivations from the seed. Some considerations:

-What happens if there's an outstanding partial-transaction that's been sent but not applied by the other party? This could easily result in double-spend attempts.

-How many key possibilities do you iterate through for each utxo? (Or is there anything more clever that can be done here)?

We may want a bit more design thought around this and the transaction workflow before blundering ahead and implementing. Related issue:

https://github.com/mimblewimble/grin/issues/287

**Comment by yeastplume** [comment]
I'm thinking about whether this should be be a 'grin server' function instead of a 'grin wallet' function. Firstly, it's much easier/faster to iterate through the current utxos with direct access to the store (it's just a linear read then). Secondly, you don't want to restore against a running node, in case of additions, re-orgs, etc. You basically want to attempt to run against a static dataset.

On the flip side, you're tying the wallet restore function to a local grin instance, which isn't very user-friendly long term. It will be a bit of an annoyance to hit a running node for each and every utxo in the set (which can change as you go along,) but ultimately, it probably has to be this way. Any thoughts?

**Comment by yeastplume** [comment]
Okay, I think the process is (roughly):

-Pull block-by-block from the node via the API (header+utxos)
-Compare each UTXO's commit hash against a (configurable) range limit of possible keys derived from the seed and password, store if there's a match.
-Compare each block's previous hash to the hash of the previous block read
-If it's different from what's expected, rewind backwards until finding a block that does match, removing outputs from the 'found' set
-Continue until at latest block height

**Comment by ignopeverell** [comment]
Perhaps a dedicated endpoint that returns just UTXO commit hashes for a range of blocks would help speed thins up?

**Comment by sesam** [comment]
Is the UTXO commit hashes related to the idea about [Periodif DIFFs](https://lists.launchpad.net/mimblewimble/msg00133.html)? Say, if maybe they compete for or share api endpoint folders or something.

**Comment by yeastplume** [comment]
Have the API endpoint in place, no problem there. As for amounts, for the purposes of restoring wallets from testnet failures, it’s probably a matter of taking an existing backed up version of the wallet.dat file, then directly taking the amount out of the matching output when one is found? Not all that robust, but no other way short of grinding though billions of possible amounts at present

**Comment by antiochp** [comment]
https://github.com/mimblewimble/grin/blob/caee282fcc7222f72b69ba49678c676e8d2dcc2d/core/src/core/transaction.rs#L530

**Comment by yeastplume** [comment]
Ahh... rewinding range proof... thanks, (very late)

**Comment by yeastplume** [comment]
This is in place now.. any issues can be reported individually.
