### ISSUE TITLE
Use HMAC verification in hook payloads

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#2955]
Nothing guarantees the [hook](https://github.com/mimblewimble/docs/wiki/Event-hooks) payload's integrity when it is received by a third-party service. Usually, that's fixed by using a HMAC secret that third-party services can verify to ensure the payload was not tampered in transit. TLS is an overkill because we don't really care to encrypt the payload, it's not secret.

**Comment by eupn** [comment]
How the HMAC secret should be exchanged between parties in this case?

**Comment by kargakis** [comment]
Different issue but fwiw usually the person deploying a third party integration is the same person owning the original instance ("instance" being an account in a service, eg. a github account, or the service itself, eg. a grin node) so sharing a HMAC secret is a non-issue.

-------- Original Message --------

**Comment by eupn** [comment]
Is it enough to specify a shared secret in the node's config file?

**Comment by mcdallas** [comment]
TLS is already supported for webhooks https://github.com/mimblewimble/grin/pull/2660 I agree it's overkill but there might be some service that only accepts https.

**Comment by kargakis** [comment]
@mcdallas I didn't know https was already supported, the TLS mention was in case it was proposed as an alternative. I think this issue can be closed.
