### ISSUE TITLE
Wallet error "503 Service Unavailable with data Body" when post two payments at the same time

### ISSUE THREAD

**Issue by xianggy** [mimblewimble/grin#2959]
**Describe the bug**
`grinrpc.js response err  {"id":"46768647-596c-42a8-a725-2240272b2b7c","jsonrpc":"2.0","result":{"Err":{"ClientCallback":"Posting transaction slate (is recipient listening?): Request error: Wrong response code: 503 Service Unavailable with data Body"}}}`

**To Reproduce**
post two payments with api `init_send_tx` at the same time.

**Relevant Information**
The first payment is fine, but the second get the 503 error.

**Desktop (please complete the following information):**
 - Version grin-2.0.0, grin-wallet-2.0.0

**Comment by quentinlesceller** [comment]
Transfered to https://github.com/mimblewimble/grin-wallet/issues/215.
