### ISSUE TITLE
[2.x.x] "C32 phase out on hold" included in 2.x.x?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#2967]
We "put phase outs of C32 and beyond on hold" in https://github.com/mimblewimble/grin/pull/2714

This was merged for `2.0.0` but I'm not sure we merged the corresponding changes to the `2.x.x` branch.

We should confirm either way and make the appropriate changes for `2.x.x` if necessary.

**Comment by quentinlesceller** [comment]
Indeed #2714 was NOT merged on `milestone/2.x.x`.
https://github.com/mimblewimble/grin/blob/milestone/2.x.x/core/src/consensus.rs#L187

Is there a quick way to see which commit from master are missing in milestone/2.x.x ?

Opening a PR from `master` -> `milestone/2.x.x` output the following:
<img width="1031" alt="Capture d’écran 2019-07-24 à 12 14 23" src="https://user-images.githubusercontent.com/11842328/61785985-1d3f3400-ae0d-11e9-924f-91cfe982b8e6.png">

**Comment by quentinlesceller** [comment]
Fixed via https://github.com/mimblewimble/grin/commit/441e846af6bc795fbe9d996851ca827e2807ca8b.
