### ISSUE TITLE
repetitive Debug message - Total solutions per second: 1000

### ISSUE THREAD

**Issue by pavoltravnik** [mimblewimble/grin#297]
trying to run it on MacAir and getting the same message again and again:

Nov 17 21:36:48.540 DEBG monitoring peers (7)
Nov 17 21:36:48.541 DEBG Got 43 more peers from db, trying to connect.
Nov 17 21:36:51.012 DEBG Mining: Plugin 0 - Device 0 (CPU): Last Graph time: 0.001s; Graphs per second: 1000.000 - Total Attempts: 876
Nov 17 21:36:51.013 DEBG Total solutions per second: 1000
Nov 17 21:36:54.062 DEBG Mining: Plugin 0 - Device 0 (CPU): Last Graph time: 0.001s; Graphs per second: 1000.000 - Total Attempts: 876
Nov 17 21:36:54.062 DEBG Total solutions per second: 1000
Nov 17 21:36:57.010 DEBG Mining: Plugin 0 - Device 0 (CPU): Last Graph time: 0.001s; Graphs per second: 1000.000 - Total Attempts: 876
Nov 17 21:36:57.010 DEBG Total solutions per second: 1000

**Comment by pavoltravnik** [comment]
I killed the process and tun it again. Everything works fine now.

**Comment by ignopeverell** [comment]
That actually is to be expected, each line is the miner looking for more solutions. But we should lower log level on the console. Tracking this under #281.
