### ISSUE TITLE
Provide statically built Grin for linux that an run on other distributions than Debian

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin#2977]
Grin is built for debian, so it does not work on other distributions well. It would be nice to provide a statically built version of grin so the dreaded ncurses problems disappear on other distributions.

Or provide how to compile a statically built version in the build docs. Running with the following fails to produce a static binary:

export RUSTFLAGS='-C target-feature=+crt-static'; cargo build --release

**Comment by quentinlesceller** [comment]
Could you try this release https://github.com/quentinlesceller/grin/releases/tag/v2.1.0 ? This is built with the above flag.

**Comment by GHLover** [comment]
It says the following in a default fedora 29 install:

./grin: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

**Comment by quentinlesceller** [comment]
Hi @GHLover did you install ncurses and libs?

**Comment by quentinlesceller** [comment]
The fix is:
```
sudo dnf install ncurses-compat-libs
```

since Fedora 29 and 30 comes with ncurses6.

**Comment by quentinlesceller** [comment]
Reopening since we really need statically built binaries.

**Comment by quentinlesceller** [comment]
Due to croaring and libncurses is not easy if even feasible to do it today. Closing for now. One day it might be feasible to move to crossterm backend and thus get rid of ncurses.
