### ISSUE TITLE
API improvements for better management

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin#2987]
Clients that are built around the API need some additional information to work effectively. This is the following:

1) Peer list API: show more information about connected peers including the block height / cumulative difficulty of the peer. Basically, so the API provides at least as much information as the server TUI does.

2) Status information: Similarly, the minimum amount of info the status should provide is the same amount of information displayed in the TUI. So, it should list the current state (downloading headers, etc) along with the network height so clients know the server is XX% done syncing / processing.

Not being able to know the network height via the API is probably the most frustrating issue with the API. Clients are basically blind in regards to how much of the chain has actually been synced. For example, if I leave the server offline for a while there is no way for me to know that I am 0% behind, 5% behind, 20% behind the network, etc.

**Comment by quentinlesceller** [comment]
2 is tackled by #2966.
1 is still not yet implemented.

**Comment by quentinlesceller** [comment]
Closing this. 1) would be nice to have a definitely not hard to implement.
