### ISSUE TITLE
grin node peers

### ISSUE THREAD

**Issue by xwen01** [mimblewimble/grin#2992]
![image](https://user-images.githubusercontent.com/3589998/63149704-76c70700-c037-11e9-9693-930a4d7e5424.png)

There are only a few connected peers for the grin node, as you can see in the screenshot. And only one incoming connection. Is this normal? How can I increase the number of connected peers?
What does the number in brackets "(7s)" indicate?

Thanks.

**Comment by antiochp** [comment]
`(7s)` is the time since we last saw a msg from this peer, likely a ping/pong that we send every `10s`.

**Comment by antiochp** [comment]
What values do you have for `peer_max_count` and `peer_min_preferred_count` in your config file? You may want to consider increasing those.

**Comment by xwen01** [comment]
> What values do you have for `peer_max_count` and `peer_min_preferred_count` in your config file? You may want to consider increasing those.

The two counts are not set in my config file (are commented out). The default are 25 and 8 respectively. Should I uncomment them and just use the default?

Will small peer number increase the latency of getting new jobs if I run the node as stratum server?

Thanks.

**Comment by antiochp** [comment]
The defaults for `2.0` are actually 125 and 8 I believe.

I don't believe the latency will be impacted excessively but it may have some impact. Its going to depend on the latency of the blocks arriving at your node, which may still be fast regardless of the number of connected peers.

**Comment by xwen01** [comment]
> The defaults for `2.0` are actually 125 and 8 I believe (they were revised as part of the `2.0` release).
> 
> I don't believe the latency will be impacted excessively but it may have some impact. Its going to depend on the latency of the blocks arriving at your node, which may still be fast regardless of the number of connected peers.

Thanks for your reply. Will try the defaults.
