### ISSUE TITLE
grin server crashes while sync'ing

### ISSUE THREAD

**Issue by robert-muncaster** [mimblewimble/grin#2995]
**Describe the bug**
My grin server crashes and is unable to sync. Dies with error:
"Illegal Instruction (core dumped)

**To Reproduce**
./grin server run

**Relevant Information**
Nothing relevant in logs.....except that the crash is non-deterministic in how long it takes to crash, but it always does.
20190821 12:30:54.111 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190821 12:30:54.111 INFO grin - Using configuration file at /home/abouchard/.grin/main/grin-server.toml
20190821 12:30:54.111 INFO grin - This is Grin version 2.0.0 (git v2.0.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190821 12:30:54.111 WARN grin::cmd::server - Starting GRIN in UI mode...
20190821 12:30:54.112 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190821 12:30:54.372 INFO grin_servers::grin::server - Starting rest apis at: 127.0.0.1:3413
20190821 12:30:54.372 INFO grin_api::handlers - Starting HTTP API server at 127.0.0.1:3413.
20190821 12:30:54.372 INFO grin_servers::grin::server - Starting dandelion monitor: 127.0.0.1:3413
20190821 12:30:54.372 WARN grin_servers::grin::server - Grin server started.
20190821 12:30:54.375 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: None
20190821 12:31:17.950 INFO grin_servers::common::adapters - Received 8 block headers from 85.187.253.59:49316
20190821 12:41:04.412 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: Some(PeerAddr(V4(157.230.156.251:3414)))

**Screenshots**
![grin](https://user-images.githubusercontent.com/45494952/63460236-5d490500-c413-11e9-90a6-7eedb5645ace.png)

**Desktop (please complete the following information):**
 uname -a
Linux  4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
./grin -V
grin 2.0.0

**Additional context**
Fresh download of release 2.0.0 - attempting to run/sync blockchain. I deleted my entire ~/.grin/main directory to rebuild from scratch and I still get a crash.

**Edit**
Just tried to run on another linux machine ( 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux) and equally crashed, though earlier

./grin server run
Illegal instruction (core dumped)

**Comment by hashmap** [comment]
Sounds like https://github.com/mimblewimble/grin/issues/2494

**Comment by jaberwoky83** [comment]
You aren't suggesting I need to recompile my kernel with AVX2 are you? That would just be crazy

**Comment by hashmap** [comment]
Not exactly, I assume you use the release binary. It was compiled with avx support, most likely your CPU doesn’t support it. The workaround is to build it on your machine from the source.

**Comment by marekyggdrasil** [comment]
I'm facing same problem on my server, I tried to check if my machine supports avx

```
$ cat /proc/cpuinfo | grep avx
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

each line corresponds to single core and `avx` figures in `flags`

**Comment by marekyggdrasil** [comment]
@jaberwoky83 did you use provided binaries or build yourself? I just build from the sources and `v2.0.0` synced correctly for the first time.

**Comment by galbotrix** [comment]
Same issue here with v3.0.0-beta2...binary 

20191221 11:16:07.316 INFO grin_servers::common::adapters - Received 32 block headers from 39.104.49.1:13414
20191221 11:16:08.218 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:09.169 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:09.973 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:10.854 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:10.977 ERROR grin_servers::grin::sync::syncer - unexpected error: "failed to obtain lock for try_header_head"
20191221 11:16:11.757 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:12.626 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:12.987 ERROR grin_servers::grin::sync::syncer - unexpected error: "failed to obtain lock for try_header_head"
20191221 11:16:13.501 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:14.299 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:15.168 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:16.014 INFO grin_servers::common::adapters - Received 32 block headers from 185.36.189.28:3414
20191221 11:16:16.829 INFO grin_servers::common::adapters - Received 24 block headers from 185.36.189.28:3414
20191221 11:17:31.882 INFO grin_util::zip - extract_files: "kernel/pmmr_data.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/kernel/pmmr_data.bin"
20191221 11:17:33.269 INFO grin_util::zip - extract_files: "kernel/pmmr_hash.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/kernel/pmmr_hash.bin"
20191221 11:17:35.958 INFO grin_util::zip - extract_files: "output/pmmr_data.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/output/pmmr_data.bin"
20191221 11:17:36.355 INFO grin_util::zip - extract_files: "output/pmmr_hash.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/output/pmmr_hash.bin"
20191221 11:17:36.382 INFO grin_util::zip - extract_files: "output/pmmr_prun.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/output/pmmr_prun.bin"
20191221 11:17:48.143 ERROR grin_servers::grin::sync::syncer - unexpected error: "failed to obtain lock for try_header_head"
20191221 11:17:50.154 ERROR grin_servers::grin::sync::syncer - unexpected error: "failed to obtain lock for try_header_head"
20191221 11:17:51.024 INFO grin_util::zip - extract_files: "rangeproof/pmmr_data.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/rangeproof/pmmr_data.bin"
20191221 11:17:52.614 INFO grin_util::zip - extract_files: "rangeproof/pmmr_hash.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/rangeproof/pmmr_hash.bin"
20191221 11:17:52.621 INFO grin_util::zip - extract_files: "rangeproof/pmmr_prun.bin" -> "/home/galbotrix/.grin/main/tmp/txhashset/rangeproof/pmmr_prun.bin"
20191221 11:17:52.634 INFO grin_util::zip - extract_files: "output/pmmr_leaf.bin.0000032e0696" -> "/home/galbotrix/.grin/main/tmp/txhashset/output/pmmr_leaf.bin.0000032e0696"
20191221 11:17:52.643 INFO grin_util::zip - extract_files: "rangeproof/pmmr_leaf.bin.0000032e0696" -> "/home/galbotrix/.grin/main/tmp/txhashset/rangeproof/pmmr_leaf.bin.0000032e0696"

**Comment by jaspervdm** [comment]
This should be fixed in v3.1.1 and onwards. If it re-appears, please open a new issue for it and we will investigate

**Comment by Pablo-LN** [comment]
![Скриншот 2020-05-27 12 53 11](https://user-images.githubusercontent.com/58917383/83006523-a2d5d680-a012-11ea-9fbe-289d770da407.png)

**Comment by Pablo-LN** [comment]
v3.1.1

**Comment by Pablo-LN** [comment]
can you help me with my grin node?
