### ISSUE TITLE
Grin V2 crashes at startup

### ISSUE THREAD

**Issue by mbay1971** [mimblewimble/grin#3006]
Hi,

i want to run grin on a VPS without TXGUI  but i get a crash with the following message:
20190829 10:24:25.460 WARN grin::cmd::server - Starting GRIN w/o UI...
20190829 10:24:25.610 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h4951788bd28f5e9e (0x55e8397341b1)
   1: rust_panic_with_hook (0x55e8398708d9)
             at src/libstd/panicking.rs:478
   2: continue_panic_fmt (0x55e839870372)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x55e839870256)
   4: panic_fmt (0x55e83988a26d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hc2a4998136cb4690 (0x55e83908b5d9)
   6: grin::cmd::server::start_server::h24519281179aa67c (0x55e83908cda9)
   7: grin::cmd::server::server_command::h5127c9bfa3ce033a (0x55e83908d863)
   8: grin::real_main::h0d5a305d062ab86b (0x55e8390c37c2)
   9: grin::main::h9882fdd29d1b551f (0x55e8390c23a6)
  10: std::rt::lang_start::{{closure}}::hfc5dddc69489901b (0x55e83909a1d3)
  11: {{closure}} (0x55e8398701f3)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic (0x55e83987615a)
             at src/libpanic_unwind/lib.rs:87
  13: try<i32,closure> (0x55e839870cfd)
             at src/libstd/panicking.rs:272
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  14: main (0x55e8390c6a52)
  15: __libc_start_main (0x7f05e5af1b97)
  16: _start (0x55e839079639)
  17: <unknown> (0x0)

Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })"
See /home/grin/grin/grin-server.log for further details.

any ideas how to fix this - thanks for your help.

**Comment by antiochp** [comment]
cross posting from the support channel in case you missed it - 

@mbay1971 that's pretty weird and looks suspiciously like your chain_data on disk got corrupted somehow. Can you clear out chain_data and try a sync from scratch?

**Comment by mbay1971** [comment]
i tried with the brand new V3.0 binaries but still the same ... any hints how to fix this ? - i would love to run a grin node on my VPS 

uname -a
Linux v22018025763061142 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

....the following happens:
1) i try to start grin

./grin server run
20200102 19:17:34.026 WARN grin::cmd::server - Starting GRIN w/o UI...
Illegal instruction (core dumped)

in the grin-server.log:

20200102 19:17:34.026 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20200102 19:17:34.026 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20200102 19:17:34.026 INFO grin - This is Grin version 3.0.0 (git v3.0.0), built for x86_64-unknown-linux-gnu by rustc 1.39.0 (4560ea788 2019-11-04).
20200102 19:17:34.026 WARN grin::cmd::server - Starting GRIN w/o UI...
20200102 19:17:34.027 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20200102 19:17:34.033 INFO grin_store::lmdb - Resized database from 1048576 to 134217728

2) i try to start once again i get this:
./grin server run
20200102 19:20:46.288 WARN grin::cmd::server - Starting GRIN w/o UI...
20200102 19:20:46.416 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:1165stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::hff21834a86023c70 (0x56182a1a4d21)
   1: std::panicking::rust_panic_with_hook::h825f041245da8739 (0x56182a2dc8ac)
             at src/libstd/panicking.rs:477
   2: std::panicking::continue_panic_fmt::hbe0378e33481e81b (0x56182a2dc362)
             at src/libstd/panicking.rs:380
   3: rust_begin_unwind (0x56182a2dc256)
             at src/libstd/panicking.rs:307
   4: core::panicking::panic_fmt::h527855ce0bc891f6 (0x56182a2fa19a)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::ha8b77e6004f0ba38 (0x56182a2fa297)
             at src/libcore/result.rs:1165
   6: grin::cmd::server::start_server_tui::h60bb15ef21638c5c (0x561829ace15d)
   7: grin::cmd::server::server_command::h489e4b6c04796d86 (0x561829acec80)
   8: grin::real_main::h4a47aac0e709af64 (0x561829af8d5f)
   9: grin::main::h8d53dbda0218ff7d (0x561829af7ae6)
  10: std::rt::lang_start::{{closure}}::h63635ad4e997182b (0x561829ac5c93)
  11: std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2 (0x56182a2dc1f3)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7c2a8488f72db90c
             at src/libstd/panicking.rs:292
  12: __rust_maybe_catch_panic (0x56182a2e1e1a)
             at src/libpanic_unwind/lib.rs:80
  13: std::panicking::try::hc3a9b5da4250385d (0x56182a2dccbd)
             at src/libstd/panicking.rs:271
      std::panic::catch_unwind::hf27600bf8c37809a
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h409d4f2fe51133b0
             at src/libstd/rt.rs:48
  14: main (0x561829af9ab2)
  15: __libc_start_main (0x7f426fb0d830)
  16: _start (0x561829a8fa39)
  17: <unknown> (0x0)

Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })"
See /root/.grin/main/grin-server.log for further details.

in the grin-server.log:

20200102 19:20:46.286 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20200102 19:20:46.287 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20200102 19:20:46.288 INFO grin - This is Grin version 3.0.0 (git v3.0.0), built for x86_64-unknown-linux-gnu by rustc 1.39.0 (4560ea788 2019-11-04).
20200102 19:20:46.288 WARN grin::cmd::server - Starting GRIN w/o UI...
20200102 19:20:46.289 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20200102 19:20:46.291 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20200102 19:20:46.419 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:1165stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::hff21834a86023c70 (0x56182a1a4d21)
   1: std::panicking::rust_panic_with_hook::h825f041245da8739 (0x56182a2dc8ac)
             at src/libstd/panicking.rs:477
   2: std::panicking::continue_panic_fmt::hbe0378e33481e81b (0x56182a2dc362)
             at src/libstd/panicking.rs:380
   3: rust_begin_unwind (0x56182a2dc256)
             at src/libstd/panicking.rs:307
   4: core::panicking::panic_fmt::h527855ce0bc891f6 (0x56182a2fa19a)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::ha8b77e6004f0ba38 (0x56182a2fa297)
             at src/libcore/result.rs:1165
   6: grin::cmd::server::start_server_tui::h60bb15ef21638c5c (0x561829ace15d)
   7: grin::cmd::server::server_command::h489e4b6c04796d86 (0x561829acec80)
   8: grin::real_main::h4a47aac0e709af64 (0x561829af8d5f)
   9: grin::main::h8d53dbda0218ff7d (0x561829af7ae6)
  10: std::rt::lang_start::{{closure}}::h63635ad4e997182b (0x561829ac5c93)
  11: std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2 (0x56182a2dc1f3)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7c2a8488f72db90c
             at src/libstd/panicking.rs:292
  12: __rust_maybe_catch_panic (0x56182a2e1e1a)
             at src/libpanic_unwind/lib.rs:80
  13: std::panicking::try::hc3a9b5da4250385d (0x56182a2dccbd)
             at src/libstd/panicking.rs:271
      std::panic::catch_unwind::hf27600bf8c37809a
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h409d4f2fe51133b0
             at src/libstd/rt.rs:48
  14: main (0x561829af9ab2)
  15: __libc_start_main (0x7f426fb0d830)
  16: _start (0x561829a8fa39)
  17: <unknown> (0x0)

which information do you need ?
Thanks for any help !

**Comment by mbay1971** [comment]
Probloem solved - i compiled it myself on my system and now it works - i guess it was the missing avx capability of my VPS ...

please close this call - THANKS
