### ISSUE TITLE
Binary: ncurses error on Ubuntu 19.04

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#3022]
Follow up of https://github.com/mimblewimble/grin/issues/2106.
It appears that it is currently not possible to run Grin binary on Ubuntu 19.04. 
The issue lies in the fact that Ubuntu 19.04 uses ncurses 6 and the binary is compiled for ncurses 5.

Fixes tried:
```
sudo apt install libncurses5-dev libncursesw5-dev
```

which results in:

```sh
error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory
```

```
cd /lib/x86_64-linux-gnu
ln -s libncursesw.so.6 libncursesw.so.5
ln -s libtinfo.so.6 libtinfo.so.5
```

which results in:

```sh
./grin: /lib/x86_64-linux-gnu/libtinfo.so.5: version NCURSES_TINFO_5.0.19991023' not found (required by ./grin)
./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: versionNCURSESW_5.6.20061217' not found (required by ./grin)
./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: version `NCURSESW_5.1.20000708' not found (required by ./grin)
```

**Comment by quentinlesceller** [comment]
FTR the current solution for 19.04 is to build from sources.

**Comment by quentinlesceller** [comment]
@FTLIan 

This can be fixed with the following command:
```
sudo apt-get install libncursesw5-dev
```

**Comment by FTLIan** [comment]
That I'd already done.  Trying it again results in:

libncursesw5-dev is already the newest version (6.1+20181013-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

Still getting these when running grin:
/grin$ ./grin
./grin: /lib/x86_64-linux-gnu/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by ./grin)
./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: version `NCURSESW_5.6.20061217' not found (required by ./grin)
./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: version `NCURSESW_5.1.20000708' not found (required by ./grin)


Thanks so much for the effort.  Or were you saying I need to build grin from the source code to get this running?  Man, all I wanted to do was get my grin off the exchange.  This has turned into quite a task!

**Comment by quentinlesceller** [comment]
You can either build from source or install the ncurses library. I tried several packages with ncurses5 and one of them worked (Not sure if that helps... You can take a look here https://packages.ubuntu.com/search?keywords=ncurses&searchon=names&suite=disco&section=all).

**Comment by FTLIan** [comment]
I installed libncurses5 and 6 and w and it's working now.  Thank you.
