### ISSUE TITLE
[Server] Thread panicked at 'attempt to multiply with overflow.'

### ISSUE THREAD

**Issue by xanather** [mimblewimble/grin#303]
Heres the log:

Nov 18 15:20:22.321 DEBG monitoring peers (8)
Nov 18 15:20:27.304 DEBG Received block f20426cd at 2334 from network, going to process.
Nov 18 15:20:27.305 INFO Starting validation pipeline for block f20426cd at 2334 with 0 inputs and 1 outputs.
Nov 18 15:20:27.305 DEBG Validating block with cuckoo size 16
Nov 18 15:20:27.307 DEBG Starting new sumtree extension.
Nov 18 15:20:27.376 DEBG Block at 2334 with hash f20426cd is valid, going to save and append.
Nov 18 15:20:27.377 INFO Updated head to f20426cd at 2334.
Nov 18 15:20:27.377 DEBG Committing sumtree extension.
Nov 18 15:20:27.379 DEBG Sumtree extension done.
Nov 18 15:20:27.381 DEBG Received block f20426cd at 2334 from network, going to process.
Nov 18 15:20:27.381 INFO Starting validation pipeline for block f20426cd at 2334 with 0 inputs and 1 outputs.
Nov 18 15:20:27.382 DEBG Block f20426cd at 2334 is unfit at this time: already known
Nov 18 15:20:27.382 DEBG Block f20426cd refused by chain: Unfit("already known")
Nov 18 15:20:27.383 DEBG Received block f20426cd at 2334 from network, going to process.
Nov 18 15:20:27.383 INFO Starting validation pipeline for block f20426cd at 2334 with 0 inputs and 1 outputs.
Nov 18 15:20:27.383 DEBG Block f20426cd at 2334 is unfit at this time: already known
Nov 18 15:20:thread '27main' panicked at 'attempt to multiply with overflow.', 383p2p/src/rate_limit.rs:152: 19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
DEBG Block f20426cd refused by chain: Unfit("already known")
xanather@xanather-grin:~/Downloads/grinserver$

**Comment by ignopeverell** [comment]
This is on a 32 bits platform. The `ThrottledWriter` uses a max bytes per second of 12M which gets credits when the connection hasn't been used for a bit. That multiplication of number of second passed time 12M can overflow on 32 bits when nothing has been sent for some time.
