### ISSUE TITLE
Is it possible to create two identical outputs on the Grin blockchain?

### ISSUE THREAD

**Issue by shannon1916** [mimblewimble/grin#3041]
If I create two outputs with the same values and blinding factors, will Grin accept both of them and keep them into the blockchain?

I notice there is a term "Occurrences" in the "output" page of the Grin explorer and it always is 1. Does "Occurrences" mean how many identical outputs are there on the blockchain?

**Comment by antiochp** [comment]
Output (commitments) _must_ be unique within the current UTXO set.
i.e. You cannot have multiple unspent outputs with the same commitment.

But duplicates can exist across the whole TXO set. You can spend an output and then subsequently reuse that output commitment.

There has been some discussion around relaxing this uniqueness constraint. Allowing duplicates to co-exist has some benefits, but at the cost of some additional flexibility.
There is nothing inherent in Grin/MW that requires this uniqueness.
