### ISSUE TITLE
txhashset download too many bytes

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3048]
Don't know what happened here but we appear to have got stuck downloading _too many_ bytes for the txhashset msg attachment...

```
20190918 16:49:51.384 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 359088000/383150878
20190918 16:50:02.403 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 367248000/383150878
20190918 16:50:13.450 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 375360000/383150878
20190918 16:50:36.329 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 383136000/383150878
20190918 16:50:47.355 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 383136000/383150878
```

Q1) How did this happen?
Q2) How can we prevent it (or recover from this situation)?

**Comment by DavidBurkett** [comment]
383136000 is less than 383150878. What am I missing?

**Comment by antiochp** [comment]
Oh wait up - maybe a false alarm. 

@DavidBurkett probably been staring at those logs for too long...

**Comment by antiochp** [comment]
False alarm - can't read, can't compare two numbers...
