### ISSUE TITLE
Domain name expired on 28-09

### ISSUE THREAD

**Issue by thomaseizinger** [mimblewimble/grin#3065]

**Comment by lehnberg** [comment]
Thank you for reporting, we're aware: https://www.grin-forum.org/t/grin-tech-org-domain-expiration/6153/5

**Comment by thomaseizinger** [comment]
Ah sorry about that, I am not following the grin-forum :)

**Comment by lehnberg** [comment]
Nothing to apologise for, we appreciated that you flagged it! :)
