### ISSUE TITLE
Wallet failure after printing a partial TX to stdout

### ISSUE THREAD

**Issue by AsrielBelacqua** [mimblewimble/grin#307]
Background: I printed a partial transaction to stdout not realizing I had no scrollback, and therefore locked most of my coins. Subsequently, @antonio-fr sent me a transaction in the usual manner, but my wallet receiver panicked:

```
Nov 18 11:21:45.600 DEBG Received txn and built output - Identifier(8280fcadc5688ecf782f), Identifier(1da8a162941509efcf2f), 631
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Error processing partial transaction: Node(Internal(\"Server error.\"))")', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Unfortunately, I was not running with RUST_BACKTRACE=1, but can try reproducing this if desired.

It also seems to have caused trouble somehow for @antonio-fr, but that may be unrelated. (He seems to have gained some extra coins somehow.. Fees? But I may have misread his wallet info output.)

**Comment by AsrielBelacqua** [comment]
I was running commit 04ab4d23a4. Unfortunately also my wallet log file is empty (I guess the wallet receiver writes to stderr? The server process seems to write to stdout, so that's what I redirected...)

**Comment by antonio-fr** [comment]
My wallet balance increased after sending :

```# ./grin wallet info Nov 18 12:20:58.553 INFO Using configuration file at: /root/grin/target/debug/grin.toml Nov 18 12:20:58.555 DEBG Using wallet seed file at: ./wallet.seed Nov 18 12:20:58.641 DEBG Refreshing wallet outputs Nov 18 12:20:59.134 INFO Acquiring wallet lock ...
Nov 18 12:20:59.139 DEBG Attempting to acquire wallet lock
Nov 18 12:20:59.141 INFO ... released wallet lock

Wallet Summary Info - Block Height: 2577
--------------------------
 Total                            | 200.255000000
 Awaiting Confirmation            | 0.000000000
 Confirmed but Still Locked       | 200.000000000
 Currently Spendable              | 0.255000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000


# ./grin wallet send 0.2 -d "http://51.15.194.8:13415"
Nov 18 12:21:44.635 INFO Using configuration file at: /root/grin/target/debug/grin.toml
Nov 18 12:21:44.637 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 12:21:44.695 DEBG Refreshing wallet outputs
Nov 18 12:21:44.713 INFO Acquiring wallet lock ...
Nov 18 12:21:44.713 DEBG Attempting to acquire wallet lock
Nov 18 12:21:44.716 INFO ... released wallet lock
Nov 18 12:21:44.720 INFO Acquiring wallet lock ...
Nov 18 12:21:44.720 DEBG Attempting to acquire wallet lock
Nov 18 12:21:44.723 INFO ... released wallet lock
Nov 18 12:21:44.850 DEBG Posting partial transaction to http://51.15.194.8:13415/v1/receive/transaction


# ./grin wallet info
Nov 18 12:21:49.263 INFO Using configuration file at: /root/grin/target/debug/grin.toml
Nov 18 12:21:49.265 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 12:21:49.326 DEBG Refreshing wallet outputs
Nov 18 12:21:49.343 INFO Acquiring wallet lock ...
Nov 18 12:21:49.343 DEBG Attempting to acquire wallet lock
Nov 18 12:21:49.346 INFO ... released wallet lock

Wallet Summary Info - Block Height: 2577
--------------------------
 Total                            | 200.310000000
 Awaiting Confirmation            | 0.055000000
 Confirmed but Still Locked       | 200.000000000
 Currently Spendable              | 0.255000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000


# ./grin wallet info
Nov 18 12:22:23.375 INFO Using configuration file at: /root/grin/target/debug/grin.toml
Nov 18 12:22:23.378 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 12:22:23.474 DEBG Refreshing wallet outputs
Nov 18 12:22:23.499 INFO Acquiring wallet lock ...
Nov 18 12:22:23.499 DEBG Attempting to acquire wallet lock
Nov 18 12:22:23.502 INFO ... released wallet lock

Wallet Summary Info - Block Height: 2577
--------------------------
 Total                            | 200.310000000
 Awaiting Confirmation            | 0.055000000
 Confirmed but Still Locked       | 200.000000000
 Currently Spendable              | 0.255000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000```


Here's my wallet.dat now : 
```
{
  "outputs": {
    "73a820e1bbfe64bfd97f": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "73a820e1bbfe64bfd97f",
      "n_child": 7,
      "value": 255000000,
      "status": "Unspent",
      "height": 2568,
      "lock_height": 0,
      "is_coinbase": false
    },
    "559f19a5fdedfd8d8c31": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "559f19a5fdedfd8d8c31",
      "n_child": 6,
      "value": 50000000000,
      "status": "Unconfirmed",
      "height": 0,
      "lock_height": 0,
      "is_coinbase": true
    },
    "feadc3a25d24ed5f95ad": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "feadc3a25d24ed5f95ad",
      "n_child": 3,
      "value": 50000000000,
      "status": "Unspent",
      "height": 2078,
      "lock_height": 3078,
      "is_coinbase": true
    },
    "ad47ccac137c0470870a": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "ad47ccac137c0470870a",
      "n_child": 4,
      "value": 50000000000,
      "status": "Unspent",
      "height": 2234,
      "lock_height": 3234,
      "is_coinbase": true
    },
    "0e19a528600e506f52be": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "0e19a528600e506f52be",
      "n_child": 1,
      "value": 50000000000,
      "status": "Unspent",
      "height": 1942,
      "lock_height": 2942,
      "is_coinbase": true
    },
    "31b3feb7d64575fab2b6": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "31b3feb7d64575fab2b6",
      "n_child": 8,
      "value": 55000000,
      "status": "Unconfirmed",
      "height": 0,
      "lock_height": 0,
      "is_coinbase": false
    },
    "175be7af44803e639838": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "175be7af44803e639838",
      "n_child": 5,
      "value": 50000000000,
      "status": "Unspent",
      "height": 2431,
      "lock_height": 3431,
      "is_coinbase": true
    },
    "08c992a81a24015bc681": {
      "root_key_id": "b92c5654f0ed7cd0f629",
      "key_id": "08c992a81a24015bc681",
      "n_child": 2,
      "value": 455000000,
      "status": "Spent",
      "height": 1916,
      "lock_height": 0,
      "is_coinbase": false
    }
  }
```

My server log keeps writing out: 
ERRO Failed to get coinbase via wallet API (will retry)...

Dunno why, will investigate

**Comment by antonio-fr** [comment]
OK coinbase wallet is nothing related and is fixed

**Comment by AsrielBelacqua** [comment]
Here is a receive failure involving a file:
`
$ RUST_BACKTRACE=1 ./grin wallet -p password receive -i tx2.json
Nov 18 14:28:01.029 INFO Using configuration file at: /home/toby/src/grin/target/release/grin.toml
Nov 18 14:28:01.035 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 14:28:01.081 INFO Acquiring wallet lock ...
Nov 18 14:28:01.081 DEBG Attempting to acquire wallet lock
Nov 18 14:28:01.189 INFO ... released wallet lock
Nov 18 14:28:01.720 DEBG Received txn and built output - Identifier(8280fcadc5688ecf782f), Identifier(16337fb1a9229e$
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Node(Internal("Server error."))', /checkout/$
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: grin::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  13: __libc_start_main
  14: _start
`

**Comment by AsrielBelacqua** [comment]
I have also just noticed that my node seems stuck since around the time of the failure earlier, so I don't know if they are related, or which came first. I have attached a log from the server, having restarted it to see if that makes any difference (it doesn't seem to..).

[grin-stuck.log](https://github.com/mimblewimble/grin/files/1484728/grin-stuck.log)

**Comment by ignopeverell** [comment]
I'm assuming this was fixed by some recent wallet improvements as well as the stabilization of testnet. Feel free to reopen if that's not the case.
