### ISSUE TITLE
300 Grin > 50 Grin

### ISSUE THREAD

**Issue by mass34** [mimblewimble/grin#308]
Hello. What have I done wrong? Strongly do not kick))
`Wallet Summary Info - Block Height: 2116
--------------------------                                                                                                                
 Total                            | 300.000000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 300.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 

root@zorg-GA-990XA-UD3:~/grin/target/debug# ./grin wallet -p pass -s send
Nov 18 15:17:15.877 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 15:17:15.880 DEBG Using wallet seed file at: ./wallet.seed
thread 'main' panicked at 'Amount to send required', /checkout/src/libcore/option.rs:819:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@zorg-GA-990XA-UD3:~/grin/target/debug# ./grin wallet -p pass -s send RUST_BACKTRACE=1
Nov 18 15:18:20.209 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 15:18:20.211 DEBG Using wallet seed file at: ./wallet.seed
thread 'main' panicked at 'Could not parse amount as a number with optional decimal point.: ParseFloatError { kind: Invalid }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@zorg-GA-990XA-UD3:~/grin/target/debug# ./grin wallet -p pass send
Nov 18 15:18:39.661 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 15:18:39.662 DEBG Using wallet seed file at: ./wallet.seed
thread 'main' panicked at 'Amount to send required', /checkout/src/libcore/option.rs:819:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@zorg-GA-990XA-UD3:~/grin/target/debug# ./grin wallet -p pass send RUST_BACKTRACE=1
Nov 18 15:18:46.545 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 15:18:46.545 DEBG Using wallet seed file at: ./wallet.seed
thread 'main' panicked at 'Could not parse amount as a number with optional decimal point.: ParseFloatError { kind: Invalid }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@zorg-GA-990XA-UD3:~/grin/target/debug# ./grin wallet -p pass info
Nov 18 15:18:58.330 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 15:18:58.331 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 15:18:58.441 DEBG Refreshing wallet outputs
Nov 18 15:18:59.147 INFO Acquiring wallet lock ...
Nov 18 15:18:59.147 DEBG Attempting to acquire wallet lock
Nov 18 15:18:59.159 INFO ... released wallet lock

Wallet Summary Info - Block Height: 2491
--------------------------
 Total                            | 50.000000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 50.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 
`

**Comment by ignopeverell** [comment]
You haven't done anything wrong, mined outputs are just locked for 1000 blocks before they can be spent. Please read:

https://github.com/mimblewimble/grin/blob/master/doc/FAQ.md
