### ISSUE TITLE
Can't compile grin 2.0.0

### ISSUE THREAD

**Issue by kbs1** [mimblewimble/grin#3091]
**Describe the bug**
Can't compile. Using latest rust from `rustup update`

**To Reproduce**
1. Clone `grin` repo
2. Checkout `current/2.0.x`
3. run `cargo build --release`

``` 
error: proc-macro derive panicked
  --> /home/kbs1/.cargo/registry/src/github.com-1ecc6299db9ec823/grin_secp256k1zkp-0.7.7/src/key.rs:32:10
   |
32 | #[derive(Zeroize)]
   |          ^^^^^^^
   |
   = help: message: unknown zeroize attribute: (drop)

error: aborting due to previous error

The following warnings were emitted during compilation:

warning: In file included from depend/secp256k1-zkp/src/secp256k1.c:14:0:
warning: depend/secp256k1-zkp/src/ecmult_impl.h:930:12: warning: ‘secp256k1_ecmult_pippenger_batch_single’ defined but not used [-Wunused-function]
warning:  static int secp256k1_ecmult_pippenger_batch_single(const secp256k1_ecmult_context *actx, secp256k1_scratch *scratch, secp256k1_gej *r, const secp256k1_scalar *inp_g_sc, secp256k1_ecmult_multi_callback cb, void *cbdata, size_t n) {
warning:             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Relevant Information**
Performed a clean installation of rustup, removed all grin data, started from scratch using `grin-wallet init -r`

**Desktop (please complete the following information):**
 - ubuntu 18.04

**Additional context**
must compile as release crashes with illegal instruction (SIGILL)

**Comment by quentinlesceller** [comment]
Only way to compile grin v2.0.0 is to update zeroize packages:
```
cargo update -p zeroize
cargo update -p zeroize_derive
```

**Comment by kbs1** [comment]
Thank you very much, it worked! :) Also grin-wallet compiled.

Regards,
kbs1 :)
