### ISSUE TITLE
Confirmed but Still Locked?

### ISSUE THREAD

**Issue by Fjodor42** [mimblewimble/grin#310]
I *may* have overlooked something somewhere in the docs, the reason for the locking might be that it's a testnet, or I may even just be overly impatient - in either case, I apologise for the noise if my question is just that, noise, but shouldn't funds, eventually, move to "Currently Spendable"?

```
sune@lyra:~/src/mining/grin/test/wallet$ grin wallet -p '<redacted>' info
Nov 18 14:40:02.406 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 14:40:02.518 DEBG Refreshing wallet outputs
Nov 18 14:40:02.576 INFO Acquiring wallet lock ...
Nov 18 14:40:02.576 DEBG Attempting to acquire wallet lock
Nov 18 14:40:02.581 INFO ... released wallet lock

Wallet Summary Info - Block Height: 2709
--------------------------
 Total                            | 650.000000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 650.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 

sune@lyra:~/src/mining/grin/test/wallet$
```

**Comment by photis** [comment]
Can you do a `grin wallet -p '<redacted>' -s outputs`? You'll see at what block height your coins will become spendable.

**Comment by mass34** [comment]
I'm sorry that.
Wallet Summary Info - Block Height: 2776
--------------------------
 Total                            | 50.000000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 50.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 
Wallet Outputs - Block Height: 2776
------------------------------------------------------------------------------------------------------------------
 Key Id                Block Height  Locked Until  Status       Is Coinbase?  Num. of Confirmations  Value 
==================================================================================================================
 324e1bb52a490460fba4  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 b3e68a1a54e4a2909ec8  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 af4cd6aea4871d46121c  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 a821ba75d7384776c04f  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 9ab1df4211b4cdbf9b6e  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 b44c6f5570884fb8c1e2  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 edc4fc55cb979d1f49f2  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 7a386555d0f75df840bd  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 592673fca388e1825c18  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 6e80deea5f3faf8c8062  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 ed3e3bc473ea75a1c49c  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 c79e016bb2c22c088a63  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 7c67d857528621bb7c06  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 aef85a99bbff55d07cb3  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 f69eed42fffff0ecd3aa  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 d95a65f6b269f4ffd5eb  2099          3099          Unspent      true          678                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 cd1e431843fc6eba8f17  2112          3112          Spent        true          665                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 21b7702842f463dbfac5  2113          3113          Spent        true          664                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 e63af0a501a0897aaf24  2114          3114          Spent        true          663                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 dc1bc08ee29b0bc775c9  2115          3115          Spent        true          662                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 142c4206205bc3b933bb  2116          3116          Spent        true          661                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 520a0ca08539bf5bae4b  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 be53e61c93923864cfc0  2663          3663          Spent        true          114                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 13099f029e391fc43c49  2664          3664          Spent        true          113                    50.000000000 
------------------------------------------------------------------------------------------------------------------
 317a817304b35cce1199  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------
 ea1a4cb484cf94627269  0             0             Unconfirmed  true          0                      50.000000000 
------------------------------------------------------------------------------------------------------------------

**Comment by Fjodor42** [comment]
Seems I was (mostly) just too impatient, as "Locked Until" is in the future (except for two - see below) - thank you.

I do note two curious outputs, though:

``` 25f787358568a779a18c  0             0             Unconfirmed  true          0                      50.000000000```
and
```4641adc016c4b6d58441  0             0             Unconfirmed  true          0                      50.000000000```

Whatever caused those *might* be covered by other issues, but if you need me to provide more info in order to ascertain a cause, please do let me know.

**Comment by ignopeverell** [comment]
Coinbase transactions will remain locked until they reach maturity (1000 blocks for now). Those unconfirmed are either server restarts, which cause a block that was mined with its own coinbase key to be abandoned, or orphans.
