### ISSUE TITLE
CPU usage 99% on Windows Server 2016

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#3114]
**Describe the bug**
CPU usage goes to 99%, as reported by @ChronosCrypto at https://www.grin-forum.org/t/cpu-usage-100-on-windows-server-2016/6477.

**To Reproduce**
The following on a clean image of Windows Server 2016:

* Download the latest Win x64 grin from https://github.com/mimblewimble/grin/releases.
* Install Visual C++ Redistributable for Visual Studio 2015 (required to run the .exe).
* Run grin.exe. CPU usage pegged at 99%, bandwidth usage very low, only download 14 days of headers in 6 hours.
* Close grin.exe by pressing Q. Re-open grin.exe, CPU usage down to 12%, download 14 days of headers in a minute.

**Comment by ChronosCrypto** [comment]
CPU spiked to 99% again after a couple days of running the node on this clean server. Grin v2.1.1.

**Comment by hashmap** [comment]
Most likely fixed by https://github.com/mimblewimble/grin/pull/3154

**Comment by quentinlesceller** [comment]
I'm closing this since it's a bit old now and likely fixed by #3154. Feel free to open another issue if this is still relevant.
