### ISSUE TITLE
Sync loops from 0 to 511, block height stuck at 2477

### ISSUE THREAD

**Issue by Sjors** [mimblewimble/grin#313]
I tried rebuilding from 63b0e60c (milestone/testnet1), but that didn't seem to help.

[grin.log.zip](https://github.com/mimblewimble/grin/files/1484826/grin.log.zip)

```
Nov 18 17:52:41.267 INFO Received unfit block header 4eea4198 at 509: already in store.
Nov 18 17:52:41.268 INFO Starting validation pipeline for block header 2676a458 at 510.
Nov 18 17:52:41.271 INFO Received unfit block header 2676a458 at 510: already in store.
Nov 18 17:52:41.271 INFO Starting validation pipeline for block header 7d54f41e at 511.
Nov 18 17:52:41.271 INFO Received unfit block header 7d54f41e at 511: already in store.
Nov 18 17:52:41.271 INFO Added 0 headers to the header chain.
Nov 18 17:52:41.458 DEBG Sync: peer 10894902 vs us 9455442
Nov 18 17:52:41.458 DEBG Sync: blocks to download 0, block downloading 0
Nov 18 17:52:41.458 DEBG Loc heights: [2477, 2475, 2473, 2469, 2461, 2445, 2413, 2349, 2221, 1965, 0]
Nov 18 17:52:41.586 DEBG Asking peer 192.241.168.77:13414 for more block headers, locator: [ceae176e, 545c6a2d, 1dbe4aba, 1a1098ca, 5c5de681, 12ff1181, b349a6dd, a1b9ff92, e719bd21, 5641a6be, e17ea64f]
Nov 18 17:52:42.628 INFO Received 511 block headers
Nov 18 17:52:42.628 INFO Starting validation pipeline for block header 254b265f at 1.
Nov 18 17:52:42.629 INFO Received unfit block header 254b265f at 1: already in store.
...
```

It seems to iterate block 0 to 511 and start again, every couple of seconds.

**Comment by ignopeverell** [comment]
It looks like you were stuck on a fairly long fork, so that the only common block in the locator was genesis. Your node kept sending that locator, other nodes replying with the 500 first block headers. But that didn't help as you had them already anyway. Looks like sync needs a way to figure out a better locator, I'll need to think about that for a bit. Thanks for the great bug report, very helpful!

**Comment by Sjors** [comment]
Should I just delete the chain data (how?) and try syncing again?

**Comment by ignopeverell** [comment]
Yes, for now that's the only workaround. Remove you `.grin` folder.

**Comment by antiochp** [comment]
@ignopeverell seems like if we only return 500 headers then the gaps between entries in the locator cannot be larger than that?

**Comment by ignopeverell** [comment]
For a long chain the locator would become prohibitively large I think. But it seems that sync could detect that all the headers are already known in the reply and hence insert the latest in the locator (at 500).

**Comment by ignopeverell** [comment]
We're trying to track most sync issues under doc/usage.md. Thanks for the testing!
