### ISSUE TITLE
latest grin 2.1.1 release for linux crashes on step 2 with ubuntu 16.04

### ISSUE THREAD

**Issue by pstavraetos** [mimblewimble/grin#3134]
Last day i tried to setup my first grin installation and after stage 2 of blockchain download it throws me unsupported instruction + core dump.

config: i5-3230M + ubuntu 16.04 (with latest updates) + binary grin 2.1.1 from release

Fortunately, only building from source solved the problem and now it's fine.

**Comment by hashmap** [comment]
Most likely https://github.com/mimblewimble/grin/issues/2494 or an a similar issue

**Comment by quentinlesceller** [comment]
Looks like it has been fixed. Closing.
