### ISSUE TITLE
ncurses error when running binary from grin.mw

### ISSUE THREAD

**Issue by slicken** [mimblewimble/grin#3141]
im using Ubuntu 19.10 and got newer version

slicken@slk:~/grin$ sudo apt install libncurses5-dev libncursesw5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncurses5-dev is already the newest version (6.1+20190803-1ubuntu1).
libncursesw5-dev is already the newest version (6.1+20190803-1ubuntu1).

slicken@slk:~/grin$ ./grin
./grin: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

slicken@slk:/lib/x86_64-linux-gnu$ sudo ln -s libncursesw.so.6 libncursesw.so.5
slicken@slk:/lib/x86_64-linux-gnu$ sudo ln -s libtinfo.so.6 libtinfo.so.5

slicken@slk:~/grin$ ./grin
./grin: /lib/x86_64-linux-gnu/libtinfo.so.5: version NCURSES_TINFO_5.0.19991023' not found (required by ./grin) ./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: version NCURSESW_5.6.20061217' not found (required by ./grin)
./grin: /lib/x86_64-linux-gnu/libncursesw.so.5: version `NCURSESW_5.1.20000708' not found (required by ./grin)

how do I solve this?

**Comment by JosephGoulden** [comment]
Can you try `sudo apt install libncurses5 libncursesw5`

Also grin is available in Snap on Ubuntu so you can do `snap install grin`. It should work without having to install the extra dependencies yourself.

**Comment by slicken** [comment]
Thanks! snap workes fine.!

just a note:
grin and grin-wallet installed by snap is not using the same main directory by default.

grin ~/snap/grin/current/.grin/main
grin-wallet ~/.grin/man

so you have to edit grin-wallet.toml and set right api secret path for it to work.

just a tought,
we want to make it simple for everyone to use :)

regards,

**Comment by JosephGoulden** [comment]
The snap command for the wallet is `grin.wallet`, then they should use the same directory. A bit odd I realise, potentially can get an alias of grin-wallet, but need to get it manually signed off by the snapcraft team, I will look into that.

**Comment by slicken** [comment]
hi.
Im now running stable from grin.mw website

slicken@slk:~$ grin -V
grin 2.1.1
slicken@slk:~$ grin.wallet -V
grin-wallet 2.1.0

lets try now.. i did a new widrawl request just now.


regards,

Den fre 29 nov. 2019 kl 18:19 skrev Joseph Goulden <notifications@github.com

**Comment by JosephGoulden** [comment]
Great, thanks for testing. I agree we need to make it very easy to use! Let me know if you see any other snap/linux issues.

**Comment by slicken** [comment]
thanks for info.
grin.wallet did use the same ~/snap/grin/current/main directory by default and it works fine!

a bit strange that the command is grin.wallet and not grin-wallet otherwise very good.
