### ISSUE TITLE
Overwritten output position height index in case of a fork

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#3143]
Found in https://github.com/gottstech/gotts/issues/24, I have forgotten cleaning the output position height index when an output is spent, (the original PR is here: https://github.com/mimblewimble/grin/pull/2903) but don't worry about that, the only side effect is just leaving a bit of garbage index in the database.

But before giving a fix to clean the output position height index for spent output (just need add 3 lines of code as in https://github.com/gottstech/gotts/pull/25/files), we need think a bit more about the usage of this index:

 When the chain accept a new block, we call `apply_block` and `apply_output` to store the block outputs into the pmmr, and in the same time, call the `batch.save_output_pos_height` to save the output position height info into the database as the output index.

https://github.com/mimblewimble/grin/blob/master/chain/src/txhashset/txhashset.rs#L933-L938

This index use output commitment as the unique key.

In case of a fork, according to current implementation, we will simply overwrite this index with the same output commitment, which is obviously not the right behaviour, because the forked block could have the different pmmr position and height on the same output. 

This could be a major problem when fork happen.

But the strange thing is why so far this behaviour didn't cause any problem on the production environment. I will write a new test case to simulate this and confirm whether this is a true bug or not.

(to be clear, this 'bug' is not imported by https://github.com/mimblewimble/grin/pull/2903, the mmr position index is built like that already for a very long time)

**Comment by garyyu** [comment]
sorry for the noise, the 'overwritten' is not a bug and actually it's not a 'overwritten' at all since it's on the batch, the test also shows the right result.

the problem is on the `delete` feature to be added, if I clean the spent output position index on the batch, the test `output_position_in_fork` will fail for `Invalid Block Proof` because the `apply_input` on the forked block will find that index of `tx1` output already deleted.
  
```Rust
		for input in b.inputs() {
			self.apply_input(&input)?;
			// Delete the (output_pos,height) index of the spent output.
			self.batch.delete_output_pos_height(&input.commitment())?;
		}
```

**Comment by antiochp** [comment]
👀

**Comment by antiochp** [comment]
> the only side effect is just leaving a bit of garbage index in the database

Was this an issue with the original `COMMIT_POS_PREFIX` index before we migrated across to the new `COMMIT_POS_HGT_PREFIX` index?

**Comment by garyyu** [comment]
I don't think so.
Both original `COMMIT_POS_PREFIX` and the new `COMMIT_POS_HGT_PREFIX` index has this issue: spent output will leave the garbage index in the database, because we never clean it.

**Comment by jdwldnqi837** [comment]
clean it when chain compaction?

**Comment by garyyu** [comment]
@jdwldnqi837 
can't. because compaction works on blocks (it is used to remove blocks which under the horizon), but here we need work on spent outputs instead of the blocks.

need to find out the root cause of this `delete` issue.

**Comment by antiochp** [comment]
This can only be done during compaction/pruning. This is block data (its the pos of inputs in the block) and cannot be safely deleted before the block itself is deleted.

We need to guarantee that a block can be "rewound" and this will cause previously spent outputs to become unspent, requiring these index entries to still exist.

When we delete a block during compaction we should also delete the index entries for associated spent outputs.

**Comment by garyyu** [comment]
> We need to guarantee that a block can be "rewound" and this will cause previously spent outputs to become unspent, requiring these index entries to still exist.

ah, a block "rewound" will not rebuild the output mmr?

**Comment by antiochp** [comment]
> ah, a block "rewound" will not rebuild the output mmr?

No. The rebuild of the output mmr happens we reapply subsequent blocks.
So the rewind itself needs to set the state back to what it was prior to those blocks being applied.

**Comment by garyyu** [comment]
Today, I take a look at this issue again.

Since the `compaction/pruning` is the only possible chance to clean these spent output index, there's nothing more needed here, because we already have a full clean-up there in `rebuild_height_pos_index`, which will be called in the `compact()` function:
```Rust
	/// Rebuild the index of block height & MMR positions to the corresponding UTXOs.
	/// This is a costly operation performed only when we receive a full new chain state.
	/// Note: only called by compact.
	pub fn rebuild_height_pos_index(
		&self,
		header_pmmr: &PMMRHandle<BlockHeader>,
		batch: &mut Batch<'_>,
	) -> Result<(), Error> {
		...
		// clear it before rebuilding
		batch.clear_output_pos_height();
```

```Rust
	/// Triggers chain compaction.
	///
	/// * compacts the txhashset based on current prune_list
	/// * removes historical blocks and associated data from the db (unless archive mode)
	///
	pub fn compact(&self) -> Result<(), Error> {
	...
		// Rebuild our output_pos index in the db based on current UTXO set.
		txhashset.rebuild_height_pos_index(&header_pmmr, &mut batch)?;
```

So, let's close this issue. Pls feel free to let me know if further questions on this.
