### ISSUE TITLE
Server does not mine when run as a daemon

### ISSUE THREAD

**Issue by andybellenie** [mimblewimble/grin#315]
`grin server -m start`

Server runs and chain syncs but no evidence of mining (CPU usage remains low)

Also, nothing is written to the log file

**Comment by andybellenie** [comment]
Problem solved - there was no wallet available for receiving coinbase coins, as soon as I ran a wallet in receive mode the miner fired up.

I think the server should stop with an error message if you have asked it to mine but there is no wallet available

**Comment by ignopeverell** [comment]
Stopping is its own can of worms, at least this way you can start the wallet and it picks it up again.

**Comment by sesam** [comment]
I think I recreated your situation, and it keeps complaining: 

Nov 18 19:26:42.965 ERRO Failed to get coinbase via wallet API (will retry)...
...
Nov 18 19:26:57.302 ERRO Failed to get coinbase via wallet API (will retry)...

and I don't see the miner stopping to "will retry" so there's a lot of output lines about that issue. If you have full stdout Debug log, it might still be buried and harder to notice. Maybe it's worth to make this message even BIGGER somehow.

Maybe add in a MINING INACTIVE in there in the message?

**Comment by andybellenie** [comment]
The issue was less obvious because I was running in background mode so there was no debug output. Running a server in mining mode that can't store blocks seems fatal to me.

**Comment by ignopeverell** [comment]
You have 30 servers running in a mining farm talking to the same wallet to credit coinbases. Wallet receiver crashes. Wouldn't you be annoyed if your 30 servers did as well?

**Comment by andybellenie** [comment]
Yes, I would... but not nearly as annoyed as I'd be if I didn't discover for several days that the receiver was down and all my mined coins were lost.

**Comment by andybellenie** [comment]
I think there's a distinction to be made between a wallet receiver going offline and one not being available at server startup. The second case is the one I'm concerned with here.

**Comment by ignopeverell** [comment]
Assumingly, if you can't detect your receiver is offline, you wouldn't detect the servers are down as well?

**Comment by andybellenie** [comment]
I take your point. Closing.
