### ISSUE TITLE
"txhashset save to file fail" with corresponding "sending on a full channel"

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3162]
I was trying to track down the deadlock issue we are still seeing with "step 6/7" getting locked up and came across this with a node configured to sync against a single peer.

This was on the end _sending_ the txhashet file - 

```
20191209 17:14:46.012 DEBUG grin_p2p::peers - Error pinging peer PeerAddr(V4(<redacted>:3414)): Send("sending on a full channel")
20191209 17:14:46.012 DEBUG grin_p2p::peer - Stopping peer PeerAddr(V4(<redacted>:3414))
20191209 17:14:46.864 DEBUG grin_p2p::conn - Shutting down reader connection with <redacted>:59172
```

Which caused the following on the _receiving_ end - 

```
20191209 17:14:31.605 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 330624000/506602362
20191209 17:14:42.793 DEBUG grin_p2p::protocol - handle_payload: txhashset archive: 337152000/506602362
20191209 17:14:47.812 ERROR grin_p2p::protocol - handle_payload: txhashset archive save to file fail. err=Connection(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
20191209 17:14:47.812 DEBUG grin_p2p::conn - try_break: exit the loop: Connection(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
20191209 17:14:47.812 DEBUG grin_p2p::conn - Shutting down reader connection with <redacted>:3414
```

So I think this explains at least one scenario where the receiving side sees a "txhashset save to file fail" and it is because the mpsc sync_sender (our internal per-peer outbound msg queue) is full and we aggressively shut the connection down even if we are in the middle of sending a txhashset.

If we are on a relatively slow connection and we are sending a txhashet to a peer then all subsequent msgs (to that peer) will be queued up behind it. 

We put a hard limit of 100 msgs on the per-peer msg queue - 
```
pub const SEND_CHANNEL_CAP: usize = 100;
```

The limit is probably fine under normal broadcast situations, but during a txhashet download this may not be correct behavior. We send regular pings and potentially other msgs if we are low on peers and looking for more.

Intuitively we may just want to simply drop msgs on the floor if we see a "sending on a full channel", but leave the connection intact. And only close the connection in the case where we actually encounter an error/exception around the connection itself (and not the msg queue).

**Comment by hashmap** [comment]
Right, we increased the size of the buffer to address this issue, but perhaps it’s better to drop a message. Also I wonder what happens if we don’t receive Pong from a receiver for a while.

**Comment by antiochp** [comment]
I don't think we have _any_ expectations around receiving a Pong after sending a Ping. I remember discussing this way back when but as far as I can tell from the code the only msg pair that has any expectations like this is Hand/Shake where these are expected to be sequential and a true request/response (and we close the connection if we anything other than a Shake immediately following a Hand).
Ping is effectively "fire and forget". And we just handle a Pong without any association or context related to the Ping we originally sent.

Other than the peer difficulty being updated, the only thing the Ping/Pong pair is used for is to keep the underlying TCP connection alive if everything else is quiet for a period of time.

**Comment by antiochp** [comment]
We use `try_send()` and the docs describe two failure cases. 

https://doc.rust-lang.org/std/sync/mpsc/struct.SyncSender.html#method.try_send

> This method differs from send by returning immediately if the channel's buffer is full or no receiver is waiting to acquire some data. Compared with send, this function has two failure cases instead of one (one for disconnection, one for a full buffer).

https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html

I'm going to play around with handling `Full` and `Disconnected` separately in our error handling code. On `Disconnected` we want to close the tcp stream, but on `Full` we drop messages.

So the msg queue gives us a buffer for outbound msgs but is not treated as catastrophic if the buffer fills up.
