### ISSUE TITLE
Receive works properly but doesn't add the claimed output to my wallet

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#317]
I got some coins from a file and this is what happened:

$ curl http://termbin.com/0ny5>tbin && grin wallet receive -i tbin && rm tbin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10785  100 10785    0     0  34282      0 --:--:-- --:--:-- --:--:-- 34347
Nov 18 20:46:48.386 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 20:46:48.603 INFO Acquiring wallet lock ...
Nov 18 20:46:48.603 DEBG Attempting to acquire wallet lock
Nov 18 20:46:48.613 INFO ... released wallet lock
Nov 18 20:46:48.613 DEBG Received txn and built output - Identifier(7e61030add7b8e9a395f), Identifier(810804256033efe4a6e6), 3

Immediately thereafter in the server log:

Nov 18 20:46:48.631 INFO Pushing transaction with 1 inputs and 2 outputs to pool.
Nov 18 20:46:49.490 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:49.633 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:49.634 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:49.742 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:49.743 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:49.849 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:49.850 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:49.956 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:49.957 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.063 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.064 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.170 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.171 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.278 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.279 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.385 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.386 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.492 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.493 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.599 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.600 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.707 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.708 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:50.815 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:50.949 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:51.094 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:53.350 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:53.494 ERRO Transaction rejected: AlreadyInPool
Nov 18 20:46:54.867 DEBG Received tx a047164f from ?.?.?.?, going to process.
Nov 18 20:46:55.014 ERRO Transaction rejected: AlreadyInPool

My wallet info before:

Wallet Summary Info - Block Height: 3031
--------------------------
 Total                            | 3181.668536870 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 200.003500000 
 Currently Spendable              | 2981.665036870 
 ---------                        | --------- 
 (Locked by previous transaction) | 1354.994000000

and after:

Wallet Summary Info - Block Height: 3038
--------------------------
 Total                            | 3181.668536870 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 200.003500000 
 Currently Spendable              | 2981.665036870 
 ---------                        | --------- 
 (Locked by previous transaction) | 1354.994000000

The sender of the coins reports he can't claim them back.

**Comment by ignopeverell** [comment]
I'm assuming this was fixed by some recent wallet improvements as well as the stabilization of testnet. Feel free to reopen if that's not the case.
