### ISSUE TITLE
error: failed to run custom build command for `croaring-sys v0.3.9`

### ISSUE THREAD

**Issue by zwfcz** [mimblewimble/grin#3171]
use ubuntu  what hapen?
error: failed to run custom build command for `croaring-sys v0.3.9`

Caused by:
  process didn't exit successfully: `/home/zwfcz/grin/target/release/build/croaring-sys-bac60d665cec2c77/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("i686-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = None
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = None
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = None
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = None
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m32" "-march=i686" "-Wall" "-Wextra" "-std=c11" "-march=native" "-O3" "-o" "/home/zwfcz/grin/target/release/build/croaring-sys-022238053ef77311/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
cargo:warning=In file included from CRoaring/roaring.c:2:0:
cargo:warning=CRoaring/roaring.h: In function ‘hamming’:
cargo:warning=CRoaring/roaring.h:244:18: warning: implicit declaration of function ‘_mm_popcnt_u64’ [-Wimplicit-function-declaration]
cargo:warning=     return (int) _mm_popcnt_u64(x);
cargo:warning=                  ^~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c: In function ‘intersect_vector16’:
cargo:warning=CRoaring/roaring.c:376:37: error: ‘__m128i’ undeclared (first use in this function); did you mean ‘__f128’?
cargo:warning=     const int vectorlength = sizeof(__m128i) / sizeof(uint16_t);
cargo:warning=                                     ^~~~~~~
cargo:warning=                                     __f128
cargo:warning=CRoaring/roaring.c:376:37: note: each undeclared identifier is reported only once for each function it appears in
cargo:warning=CRoaring/roaring.c:379:13: error: expected ‘;’ before ‘v_a’
cargo:warning=     __m128i v_a, v_b;
cargo:warning=             ^~~
cargo:warning=CRoaring/roaring.c:381:9: error: ‘v_a’ undeclared (first use in this function); did you mean ‘i_a’?
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=         ^~~
cargo:warning=         i_a
cargo:warning=CRoaring/roaring.c:381:15: warning: implicit declaration of function ‘_mm_lddqu_si128’ [-Wimplicit-function-declaration]
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=               ^~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:381:41: error: expected expression before ‘)’ token
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:382:9: error: ‘v_b’ undeclared (first use in this function); did you mean ‘v_a’?
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=         ^~~
cargo:warning=         v_a
cargo:warning=CRoaring/roaring.c:382:41: error: expected expression before ‘)’ token
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:384:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘res_v’
cargo:warning=             const __m128i res_v = _mm_cmpestrm(
cargo:warning=                           ^~~~~
cargo:warning=CRoaring/roaring.c:384:27: error: ‘res_v’ undeclared (first use in this function)
cargo:warning=CRoaring/roaring.c:384:35: warning: implicit declaration of function ‘_mm_cmpestrm’ [-Wimplicit-function-declaration]
cargo:warning=             const __m128i res_v = _mm_cmpestrm(
cargo:warning=                                   ^~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:386:17: error: ‘_SIDD_UWORD_OPS’ undeclared (first use in this function); did you mean ‘__UWORD_TYPE’?
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                 ^~~~~~~~~~~~~~~
cargo:warning=                 __UWORD_TYPE
cargo:warning=CRoaring/roaring.c:386:35: error: ‘_SIDD_CMP_EQUAL_ANY’ undeclared (first use in this function)
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                                   ^~~~~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:386:57: error: ‘_SIDD_BIT_MASK’ undeclared (first use in this function); did you mean ‘__FD_MASK’?
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                                                         ^~~~~~~~~~~~~~
cargo:warning=                                                         __FD_MASK
cargo:warning=CRoaring/roaring.c:387:27: warning: implicit declaration of function ‘_mm_extract_epi32’; did you mean ‘__chkp_extract_upper’? [-Wimplicit-function-declaration]
cargo:warning=             const int r = _mm_extract_epi32(res_v, 0);
cargo:warning=                           ^~~~~~~~~~~~~~~~~
cargo:warning=                           __chkp_extract_upper
cargo:warning=CRoaring/roaring.c:388:21: error: expected ‘;’ before ‘sm16’
cargo:warning=             __m128i sm16 = _mm_load_si128((const __m128i *)shuffle_mask16 + r);
cargo:warning=                     ^~~~
cargo:warning=CRoaring/roaring.c:389:21: error: expected ‘;’ before ‘p’
cargo:warning=             __m128i p = _mm_shuffle_epi8(v_a, sm16);
cargo:warning=                     ^
cargo:warning=CRoaring/roaring.c:390:13: warning: implicit declaration of function ‘_mm_storeu_si128’ [-Wimplicit-function-declaration]
cargo:warning=             _mm_storeu_si128((__m128i *)&C[count], p);  // can overflow
cargo:warning=             ^~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:390:40: error: expected expression before ‘)’ token
cargo:warning=             _mm_storeu_si128((__m128i *)&C[count], p);  // can overflow
cargo:warning=                                        ^
cargo:warning=CRoaring/roaring.c:391:22: warning: implicit declaration of function ‘_mm_popcnt_u32’ [-Wimplicit-function-declaration]
cargo:warning=             count += _mm_popcnt_u32(r);
cargo:warning=                      ^~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:397:49: error: expected expression before ‘)’ token
cargo:warning=                 v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:402:49: error: expected expression before ‘)’ token
cargo:warning=                 v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:407:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘res_v’
cargo:warning=                 const __m128i res_v = _mm_cmpistrm(
cargo:warning=                               ^~~~~
cargo:warning=CRoaring/roaring.c:407:39: warning: implicit declaration of function ‘_mm_cmpistrm’ [-Wimplicit-function-declaration]
cargo:warning=                 const __m128i res_v = _mm_cmpistrm(
cargo:warning=                                       ^~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:411:25: error: expected ‘;’ before ‘sm16’
cargo:warning=                 __m128i sm16 =
cargo:warning=                         ^~~~
cargo:warning=CRoaring/roaring.c:413:25: error: expected ‘;’ before ‘p’
cargo:warning=                 __m128i p = _mm_shuffle_epi8(v_a, sm16);
cargo:warning=                         ^
cargo:warning=CRoaring/roaring.c:414:44: error: expected expression before ‘)’ token
cargo:warning=                 _mm_storeu_si128((__m128i *)&C[count], p);  // can overflow
cargo:warning=                                            ^
cargo:warning=CRoaring/roaring.c:421:53: error: expected expression before ‘)’ token
cargo:warning=                     v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                                     ^
cargo:warning=CRoaring/roaring.c:426:53: error: expected expression before ‘)’ token
cargo:warning=                     v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                                     ^
cargo:warning=CRoaring/roaring.c: In function ‘intersect_vector16_cardinality’:
cargo:warning=CRoaring/roaring.c:454:37: error: ‘__m128i’ undeclared (first use in this function); did you mean ‘__f128’?
cargo:warning=     const int vectorlength = sizeof(__m128i) / sizeof(uint16_t);
cargo:warning=                                     ^~~~~~~
cargo:warning=                                     __f128
cargo:warning=CRoaring/roaring.c:457:13: error: expected ‘;’ before ‘v_a’
cargo:warning=     __m128i v_a, v_b;
cargo:warning=             ^~~
cargo:warning=CRoaring/roaring.c:459:9: error: ‘v_a’ undeclared (first use in this function); did you mean ‘i_a’?
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=         ^~~
cargo:warning=         i_a
cargo:warning=CRoaring/roaring.c:459:41: error: expected expression before ‘)’ token
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:460:9: error: ‘v_b’ undeclared (first use in this function); did you mean ‘v_a’?
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=         ^~~
cargo:warning=         v_a
cargo:warning=CRoaring/roaring.c:460:41: error: expected expression before ‘)’ token
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:462:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘res_v’
cargo:warning=             const __m128i res_v = _mm_cmpestrm(
cargo:warning=                           ^~~~~
cargo:warning=CRoaring/roaring.c:462:27: error: ‘res_v’ undeclared (first use in this function)
cargo:warning=CRoaring/roaring.c:464:17: error: ‘_SIDD_UWORD_OPS’ undeclared (first use in this function); did you mean ‘__UWORD_TYPE’?
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                 ^~~~~~~~~~~~~~~
cargo:warning=                 __UWORD_TYPE
cargo:warning=CRoaring/roaring.c:464:35: error: ‘_SIDD_CMP_EQUAL_ANY’ undeclared (first use in this function)
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                                   ^~~~~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:464:57: error: ‘_SIDD_BIT_MASK’ undeclared (first use in this function); did you mean ‘__FD_MASK’?
cargo:warning=                 _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY | _SIDD_BIT_MASK);
cargo:warning=                                                         ^~~~~~~~~~~~~~
cargo:warning=                                                         __FD_MASK
cargo:warning=CRoaring/roaring.c:472:49: error: expected expression before ‘)’ token
cargo:warning=                 v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:477:49: error: expected expression before ‘)’ token
cargo:warning=                 v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:482:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘res_v’
cargo:warning=                 const __m128i res_v = _mm_cmpistrm(
cargo:warning=                               ^~~~~
cargo:warning=CRoaring/roaring.c:492:53: error: expected expression before ‘)’ token
cargo:warning=                     v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                                     ^
cargo:warning=CRoaring/roaring.c:497:53: error: expected expression before ‘)’ token
cargo:warning=                     v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                                     ^
cargo:warning=CRoaring/roaring.c: In function ‘difference_vector16’:
cargo:warning=CRoaring/roaring.c:548:40: error: ‘__m128i’ undeclared (first use in this function); did you mean ‘__f128’?
cargo:warning=     const size_t vectorlength = sizeof(__m128i) / sizeof(uint16_t);
cargo:warning=                                        ^~~~~~~
cargo:warning=                                        __f128
cargo:warning=CRoaring/roaring.c:552:17: error: expected ‘;’ before ‘v_a’
cargo:warning=         __m128i v_a, v_b;                //, v_bmax;
cargo:warning=                 ^~~
cargo:warning=CRoaring/roaring.c:554:9: error: ‘v_a’ undeclared (first use in this function); did you mean ‘i_a’?
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=         ^~~
cargo:warning=         i_a
cargo:warning=CRoaring/roaring.c:554:41: error: expected expression before ‘)’ token
cargo:warning=         v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:555:9: error: ‘v_b’ undeclared (first use in this function); did you mean ‘v_a’?
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=         ^~~
cargo:warning=         v_a
cargo:warning=CRoaring/roaring.c:555:41: error: expected expression before ‘)’ token
cargo:warning=         v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                         ^
cargo:warning=CRoaring/roaring.c:558:17: error: expected ‘;’ before ‘runningmask_a_found_in_b’
cargo:warning=         __m128i runningmask_a_found_in_b = _mm_setzero_si128();
cargo:warning=                 ^~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:566:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘a_found_in_b’
cargo:warning=             const __m128i a_found_in_b =
cargo:warning=                           ^~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:566:27: error: ‘a_found_in_b’ undeclared (first use in this function)
cargo:warning=CRoaring/roaring.c:567:40: error: ‘_SIDD_UWORD_OPS’ undeclared (first use in this function); did you mean ‘__UWORD_TYPE’?
cargo:warning=                 _mm_cmpistrm(v_b, v_a, _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY |
cargo:warning=                                        ^~~~~~~~~~~~~~~
cargo:warning=                                        __UWORD_TYPE
cargo:warning=CRoaring/roaring.c:567:58: error: ‘_SIDD_CMP_EQUAL_ANY’ undeclared (first use in this function)
cargo:warning=                 _mm_cmpistrm(v_b, v_a, _SIDD_UWORD_OPS | _SIDD_CMP_EQUAL_ANY |
cargo:warning=                                                          ^~~~~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:568:44: error: ‘_SIDD_BIT_MASK’ undeclared (first use in this function); did you mean ‘__FD_MASK’?
cargo:warning=                                            _SIDD_BIT_MASK);
cargo:warning=                                            ^~~~~~~~~~~~~~
cargo:warning=                                            __FD_MASK
cargo:warning=CRoaring/roaring.c:569:13: error: ‘runningmask_a_found_in_b’ undeclared (first use in this function); did you mean ‘a_found_in_b’?
cargo:warning=             runningmask_a_found_in_b =
cargo:warning=             ^~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=             a_found_in_b
cargo:warning=CRoaring/roaring.c:570:17: warning: implicit declaration of function ‘_mm_or_si128’ [-Wimplicit-function-declaration]
cargo:warning=                 _mm_or_si128(runningmask_a_found_in_b, a_found_in_b);
cargo:warning=                 ^~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:581:25: error: expected ‘;’ before ‘sm16’
cargo:warning=                 __m128i sm16 = _mm_load_si128((const __m128i *)shuffle_mask16 +
cargo:warning=                         ^~~~
cargo:warning=CRoaring/roaring.c:583:25: error: expected ‘;’ before ‘p’
cargo:warning=                 __m128i p = _mm_shuffle_epi8(v_a, sm16);
cargo:warning=                         ^
cargo:warning=CRoaring/roaring.c:584:44: error: expected expression before ‘)’ token
cargo:warning=                 _mm_storeu_si128((__m128i *)&C[count], p);  // can overflow
cargo:warning=                                            ^
cargo:warning=CRoaring/roaring.c:590:44: warning: implicit declaration of function ‘_mm_setzero_si128’ [-Wimplicit-function-declaration]
cargo:warning=                 runningmask_a_found_in_b = _mm_setzero_si128();
cargo:warning=                                            ^~~~~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:591:49: error: expected expression before ‘)’ token
cargo:warning=                 v_a = _mm_lddqu_si128((__m128i *)&A[i_a]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:597:49: error: expected expression before ‘)’ token
cargo:warning=                 v_b = _mm_lddqu_si128((__m128i *)&B[i_b]);
cargo:warning=                                                 ^
cargo:warning=CRoaring/roaring.c:608:45: error: expected expression before ‘)’ token
cargo:warning=             v_b = _mm_lddqu_si128((__m128i *)buffer);
cargo:warning=                                             ^
cargo:warning=CRoaring/roaring.c:609:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘a_found_in_b’
cargo:warning=             const __m128i a_found_in_b =
cargo:warning=                           ^~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:616:21: error: expected ‘;’ before ‘sm16’
cargo:warning=             __m128i sm16 = _mm_load_si128((const __m128i *)shuffle_mask16 +
cargo:warning=                     ^~~~
cargo:warning=CRoaring/roaring.c:618:21: error: expected ‘;’ before ‘p’
cargo:warning=             __m128i p = _mm_shuffle_epi8(v_a, sm16);
cargo:warning=                     ^
cargo:warning=CRoaring/roaring.c:619:40: error: expected expression before ‘)’ token
cargo:warning=             _mm_storeu_si128((__m128i *)&C[count], p);  // can overflow
cargo:warning=                                        ^
cargo:warning=CRoaring/roaring.c: At top level:
cargo:warning=CRoaring/roaring.c:1149:36: error: unknown type name ‘__m128i’
cargo:warning= static inline void sse_merge(const __m128i *vInput1,
cargo:warning=                                    ^~~~~~~
cargo:warning=CRoaring/roaring.c:1150:36: error: unknown type name ‘__m128i’
cargo:warning=                              const __m128i *vInput2,              // input 1 & 2
cargo:warning=                                    ^~~~~~~
cargo:warning=CRoaring/roaring.c:1151:30: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=                              __m128i *vecMin, __m128i *vecMax) {  // output
cargo:warning=                              ^~~~~~~
cargo:warning=                              __f128
cargo:warning=CRoaring/roaring.c:1151:47: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=                              __m128i *vecMin, __m128i *vecMax) {  // output
cargo:warning=                                               ^~~~~~~
cargo:warning=                                               __f128
cargo:warning=CRoaring/roaring.c:1526:32: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning= static inline int store_unique(__m128i old, __m128i newval, uint16_t *output) {
cargo:warning=                                ^~~~~~~
cargo:warning=                                __f128
cargo:warning=CRoaring/roaring.c:1526:45: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning= static inline int store_unique(__m128i old, __m128i newval, uint16_t *output) {
cargo:warning=                                             ^~~~~~~
cargo:warning=                                             __f128
cargo:warning=CRoaring/roaring.c: In function ‘union_vector16’:
cargo:warning=CRoaring/roaring.c:1562:5: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=     __m128i vA, vB, V, vecMin, vecMax;
cargo:warning=     ^~~~~~~
cargo:warning=     __f128
cargo:warning=CRoaring/roaring.c:1563:5: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=     __m128i laststore;
cargo:warning=     ^~~~~~~
cargo:warning=     __f128
cargo:warning=CRoaring/roaring.c:1570:33: error: unknown type name ‘__m128i’
cargo:warning=     vA = _mm_lddqu_si128((const __m128i *)array1 + pos1);
cargo:warning=                                 ^~~~~~~
cargo:warning=CRoaring/roaring.c:1572:33: error: unknown type name ‘__m128i’
cargo:warning=     vB = _mm_lddqu_si128((const __m128i *)array2 + pos2);
cargo:warning=                                 ^~~~~~~
cargo:warning=CRoaring/roaring.c:1574:5: warning: implicit declaration of function ‘sse_merge’ [-Wimplicit-function-declaration]
cargo:warning=     sse_merge(&vA, &vB, &vecMin, &vecMax);
cargo:warning=     ^~~~~~~~~
cargo:warning=CRoaring/roaring.c:1575:17: warning: implicit declaration of function ‘_mm_set1_epi16’ [-Wimplicit-function-declaration]
cargo:warning=     laststore = _mm_set1_epi16(-1);
cargo:warning=                 ^~~~~~~~~~~~~~
cargo:warning=CRoaring/roaring.c:1576:15: warning: implicit declaration of function ‘store_unique’; did you mean ‘unique’? [-Wimplicit-function-declaration]
cargo:warning=     output += store_unique(laststore, vecMin, output);
cargo:warning=               ^~~~~~~~~~~~
cargo:warning=               unique
cargo:warning=CRoaring/roaring.c:1584:44: error: unknown type name ‘__m128i’
cargo:warning=                 V = _mm_lddqu_si128((const __m128i *)array1 + pos1);
cargo:warning=                                            ^~~~~~~
cargo:warning=CRoaring/roaring.c:1592:44: error: unknown type name ‘__m128i’
cargo:warning=                 V = _mm_lddqu_si128((const __m128i *)array2 + pos2);
cargo:warning=                                            ^~~~~~~
cargo:warning=CRoaring/roaring.c: At top level:
cargo:warning=CRoaring/roaring.c:1647:36: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning= static inline int store_unique_xor(__m128i old, __m128i newval,
cargo:warning=                                    ^~~~~~~
cargo:warning=                                    __f128
cargo:warning=CRoaring/roaring.c:1647:49: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning= static inline int store_unique_xor(__m128i old, __m128i newval,
cargo:warning=                                                 ^~~~~~~
cargo:warning=                                                 __f128
cargo:warning=CRoaring/roaring.c: In function ‘xor_vector16’:
cargo:warning=CRoaring/roaring.c:1683:5: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=     __m128i vA, vB, V, vecMin, vecMax;
cargo:warning=     ^~~~~~~
cargo:warning=     __f128
cargo:warning=CRoaring/roaring.c:1684:5: error: unknown type name ‘__m128i’; did you mean ‘__f128’?
cargo:warning=     __m128i laststore;
cargo:warning=     ^~~~~~~
cargo:warning=     __f128
cargo:warning=CRoaring/roaring.c:1691:33: error: unknown type name ‘__m128i’
cargo:warning=     vA = _mm_lddqu_si128((const __m128i *)array1 + pos1);
cargo:warning=                                 ^~~~~~~
cargo:warning=CRoaring/roaring.c:1693:33: error: unknown type name ‘__m128i’
cargo:warning=     vB = _mm_lddqu_si128((const __m128i *)array2 + pos2);
cargo:warning=                                 ^~~~~~~
cargo:warning=CRoaring/roaring.c:1698:15: warning: implicit declaration of function ‘store_unique_xor’; did you mean ‘unique_xor’? [-Wimplicit-function-declaration]
cargo:warning=     output += store_unique_xor(laststore, vecMin, output);
cargo:warning=               ^~~~~~~~~~~~~~~~
cargo:warning=               unique_xor
cargo:warning=CRoaring/roaring.c:1707:44: error: unknown type name ‘__m128i’
cargo:warning=                 V = _mm_lddqu_si128((const __m128i *)array1 + pos1);
cargo:warning=                                            ^~~~~~~
cargo:warning=CRoaring/roaring.c:1715:44: error: unknown type name ‘__m128i’
cargo:warning=                 V = _mm_lddqu_si128((const __m128i *)array2 + pos2);
cargo:warning=                                            ^~~~~~~
cargo:warning=CRoaring/roaring.c:1745:21: warning: implicit declaration of function ‘_mm_extract_epi16’; did you mean ‘__chkp_extract_upper’? [-Wimplicit-function-declaration]
cargo:warning=     uint16_t vec7 = _mm_extract_epi16(vecMax, 7);
cargo:warning=                     ^~~~~~~~~~~~~~~~~
cargo:warning=                     __chkp_extract_upper
cargo:warning=At top level:
cargo:warning=CRoaring/roaring.c:1180:16: warning: ‘uniqshuf’ defined but not used [-Wunused-variable]
cargo:warning= static uint8_t uniqshuf[] = {
cargo:warning=                ^~~~~~~~
cargo:warning=CRoaring/roaring.c:23:22: warning: ‘shuffle_mask16’ defined but not used [-Wunused-const-variable=]
cargo:warning= static const uint8_t shuffle_mask16[] = {
cargo:warning=                      ^~~~~~~~~~~~~~
exit code: 1

--- stderr

error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m32" "-march=i686" "-Wall" "-Wextra" "-std=c11" "-march=native" "-O3" "-o" "/home/zwfcz/grin/target/release/build/croaring-sys-022238053ef77311/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c" with args "cc" did not execute successfully (status code exit code: 1).

**Comment by de1acr0ix** [comment]
Looking through CRoaring codes it seems that you need to explicitly define `DISABLE_X64` for C compiler to make build work under a 32 bit environment. Can you try running `cargo` with environment variable `CFLAGS` set to `-DDISABLE_X64`?

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if you feel this is still relevant.
