### ISSUE TITLE
Suggestion: change wallet 'receive' to wallet 'listen'

### ISSUE THREAD

**Issue by andybellenie** [mimblewimble/grin#318]
'Receive' is an action whereas 'listen' is passive so more accurately describes the wallet state. This also makes 'receive' available for reverse transactions that are initiated by the receiving wallet (if such a thing is possible)

**Comment by dougyoung** [comment]
Hey all, I submitted a PR for this: https://github.com/mimblewimble/grin/pull/322

**Comment by andybellenie** [comment]
LOL #323

**Comment by dougyoung** [comment]
Ha, I see that too! Sorry if I'm stepping on your toes! Reviewing that one now.

**Comment by sesam** [comment]
Looks like a good idea. "Listener" is the traditional name for a TCP listening service.

This change looks like it's a deprecation. There are some standards around how deprecations are usually done, to minimise confusion and "customer support" issues.

Nice-to-haves:
- add a warning! whenever the old key is found, or the new key is missing. To inform and help users to fix this. See config.rs, maybe right after `let decoded: ...` (around line 130).

- make it work also with the old key, for a while (typical deprecation behaviour, that old keys/api:s are available for the next ~2 minor version upgrades, so likely only inside Testnet1 milestone. So the old config would be accepted if the new is missing. But maybe not the command line thing, to keep it simple. Save some time for users, and some time for you @dougyoung and/or @andybellenie

**Comment by andybellenie** [comment]
@sesam added to PR

**Comment by antonio-fr** [comment]
Better to put `Arg::with_name("input")` back in receive, so handling a received file would be done in 'received', as before, not as 'listen'. 'wallet listen -i FILE' might be very confusing.
Also this requires change in the relevant documentation part.

**Comment by andybellenie** [comment]
@antonio-fr see https://github.com/mimblewimble/grin/pull/337

**Comment by antonio-fr** [comment]
Great, so it will be 'wallet file -f FILE' ?

**Comment by andybellenie** [comment]
yes
