### ISSUE TITLE
cleanup accidental file checked in

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3188]
Looks like a garbage file was checked in accidentally as part of https://github.com/mimblewimble/grin/pull/1565

```
api/tests/localhost+1.p12
```

See https://www.grin-forum.org/t/tls-support-localhost-1-p12/6907.

**Comment by hashmap** [comment]
It wasn't garbage at that time, it was required to compile tests, but since that tls code was changed a bit so now it's not needed
