### ISSUE TITLE
Include genesis hash in handshake and compare with local

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#319]
As we deploy more testnets, people will try to connect with wrong configurations, some will configure closed chains badly, more peers are bound to try to connect even though they don't share the same genesis. Included the genesis hash in the handshake and disconnect when they don't match.

**Comment by antiochp** [comment]
If we add a field to the `Hand` that gets sent across as part of the handshake, does this need to be backward compatible?
We're going to change the ser/deser format with this.

**Comment by ignopeverell** [comment]
I don't think we should worry too much about backward compatibility yet, I don't want to clutter the code foe `testnet1`. So only if backward compatibility is _extremely_ easy.

**Comment by antiochp** [comment]
PR up here - #327 (still wip).

**Comment by sesam** [comment]
PR#327 is merged, debate looks concluded. Close this?
