### ISSUE TITLE
many errors latest grin server

### ISSUE THREAD

**Issue by githubusrR** [mimblewimble/grin#3194]
Ubuntu 18.04

Grin Version 3.0.0 (proto: 2)

solo mining gminer 1.93

after the hard fork, a lot of rejects appeared(they were not there before), and errors

![grin stratum](https://user-images.githubusercontent.com/46305976/72588055-e90a8300-3918-11ea-9c34-2e7cf2d89062.jpg)

How can I fix this?

**Comment by githubusrR** [comment]
![2](https://user-images.githubusercontent.com/46305976/72597681-0ac33480-3930-11ea-8617-82da0f417097.jpg)

**Comment by hashmap** [comment]
Have you updated your miner as well?

**Comment by githubusrR** [comment]
yes gminer 1.93

**Comment by githubusrR** [comment]
this happened after the hard fork

**Comment by quentinlesceller** [comment]
We are going to need more context here such as log file and config file. Overall it looks like miner is sending invalid shares.

**Comment by githubusrR** [comment]
about an hour ago a new gminer was released 1.95
I upgraded but the error remained
![1](https://user-images.githubusercontent.com/46305976/72627382-3a912d00-396e-11ea-92b3-97f2b98b5188.jpg)

**Comment by githubusrR** [comment]
20200117 21:13:30.049 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 108c809f2abc, edge_bits 29, nonce 14373568394953799754, job_id 2, difficulty 39972/2
20200117 21:13:30.416 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1e3c6d40321e, edge_bits 29, nonce 2278739132761028887, job_id 2, difficulty 21877/20
20200117 21:13:30.562 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0346047a122e, edge_bits 29, nonce 8602198085134759938, job_id 2, difficulty 202078/2
20200117 21:13:31.446 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 02180ee24a51, edge_bits 29, nonce 9098102946230483122, job_id 2, difficulty 315907/2
20200117 21:13:31.767 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 07675b9e7d5f, edge_bits 29, nonce 6857611184435149036, job_id 2, difficulty 89347/20
20200117 21:13:32.272 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 01b87532967d, edge_bits 29, nonce 15862346566762281981, job_id 2, difficulty 384475/
20200117 21:13:33.929 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1f50e4597d2b, edge_bits 29, nonce 4146665287904704342, job_id 2, difficulty 21123/20
20200117 21:13:34.101 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 12f64865c746, edge_bits 29, nonce 8602198085134760037, job_id 2, difficulty 34885/20
20200117 21:13:34.369 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1ce1042b201e, edge_bits 29, nonce 3157564899803053449, job_id 2, difficulty 22906/20
20200117 21:13:35.461 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0c71bae15f32, edge_bits 29, nonce 3567964727336287308, job_id 2, difficulty 53157/20
20200117 21:13:35.684 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1336321face5, edge_bits 29, nonce 14373568394953799899, job_id 2, difficulty 34432/2
20200117 21:13:36.153 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 154f2d463c65, edge_bits 29, nonce 4146665287904704401, job_id 2, difficulty 31042/20
20200117 21:13:36.562 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 12285db4b8b4, edge_bits 29, nonce 16297274694824933659, job_id 2, difficulty 36431/2
20200117 21:13:37.809 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0167c9f0a3d1, edge_bits 29, nonce 2892133056167065949, job_id 2, difficulty 470678/2
20200117 21:13:40.694 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1bc7f875b963, edge_bits 29, nonce 3038096527584181453, job_id 2, difficulty 23811/20
20200117 21:13:41.033 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1caf253d0ddc, edge_bits 29, nonce 14252049905995528748, job_id 2, difficulty 23061/2
20200117 21:13:44.568 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0d6c9b5136cb, edge_bits 29, nonce 10367573855907658251, job_id 3, difficulty 49276/2
20200117 21:13:44.665 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 09d3e0b667a7, edge_bits 29, nonce 6255896557007190382, job_id 3, difficulty 67310/20
20200117 21:13:45.317 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0be72e1e7eac, edge_bits 29, nonce 17517144435949878602, job_id 3, difficulty 55574/2
20200117 21:13:45.793 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 167c0a051082, edge_bits 29, nonce 17759254628643420760, job_id 3, difficulty 29420/2
20200117 21:13:46.155 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 03496aa306bc, edge_bits 29, nonce 5049182025831972861, job_id 3, difficulty 201261/2
20200117 21:13:46.461 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 07d2c264c049, edge_bits 29, nonce 10473574490586511904, job_id 3, difficulty 84555/2
20200117 21:13:46.692 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 062ac8e546d3, edge_bits 29, nonce 6638356243595442877, job_id 3, difficulty 107262/2
20200117 21:13:47.366 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 199737b275c8, edge_bits 29, nonce 10367573855907658326, job_id 3, difficulty 25849/2
20200117 21:13:48.081 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1c4eaa6407b8, edge_bits 29, nonce 8928855602403260612, job_id 3, difficulty 23368/20
20200117 21:13:48.555 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 1a09fc4b9a35, edge_bits 29, nonce 6638356243595442925, job_id 3, difficulty 25404/20
20200117 21:13:49.657 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 06468d9aa2d0, edge_bits 29, nonce 12684818276715379246, job_id 3, difficulty 105408/
20200117 21:13:49.805 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 17ee6f934de6, edge_bits 29, nonce 13948671996234611434, job_id 3, difficulty 27641/2
20200117 21:13:51.370 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0353d377c5fe, edge_bits 29, nonce 8928855602403260695, job_id 3, difficulty 198802/2
20200117 21:13:51.915 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 127d0554cd55, edge_bits 29, nonce 17517144435949878772, job_id 3, difficulty 35779/2
20200117 21:13:53.341 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 19b2fbaa9dd9, edge_bits 29, nonce 3395047522933193172, job_id 3, difficulty 25740/20
20200117 21:13:54.746 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 00e9a3b81350, edge_bits 29, nonce 17759254628643420992, job_id 3, difficulty 724813/
20200117 21:13:54.878 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 526314, hash 0d4a1b5a4bb8, edge_bits 29, nonce 8928855602403260786, job_id 3, difficulty 49776/20
20200117 21:13:55.872 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Failed to validate share at height 526314, hash 12ce57bcf5da, edge_bits 29, nonce 1066847959108336707, job_id 3. Err

Verification Error: endpoints don't match up })

**Comment by githubusrR** [comment]
grin-server.toml  do you need it?

**Comment by quentinlesceller** [comment]
This seems perfectly normal, some of the time mining software can send invalid shares. Seems like a non-issue.

**Comment by githubusrR** [comment]
I didn't have any rejects before the hard fork

**Comment by githubusrR** [comment]
![1](https://user-images.githubusercontent.com/46305976/72629954-256acd00-3973-11ea-921f-14bc9716788b.jpg)

**Comment by githubusrR** [comment]
before the hard fork, there were no rejects during the day, now there are a lot of them

**Comment by quentinlesceller** [comment]
Very likely a mining software related issue.

**Comment by githubusrR** [comment]
can you check it out?

**Comment by quentinlesceller** [comment]
What do you mean by "check it out"? I suggest you to contact gminer and see if it's related or not. Thanks!

**Comment by 1t3** [comment]
yo tengo el mismo, problema.

si alguien consigue la solucion q comparta.
Saludos

**Comment by quentinlesceller** [comment]
Closing this issue. Please see with gminer directly.
