### ISSUE TITLE
Running node on Win10: automatic shutdown

### ISSUE THREAD

**Issue by Funkyswing** [mimblewimble/grin#3198]
Hello,

I am running Grin 3.0 on win10. The node keeps shutting down automatically while synchronizing chain state.

What causes the problem?

Thanks.

**Comment by lich666dead** [comment]
try install ubuntu wrapper.

**Comment by Funkyswing** [comment]
> 
> 
> try install ubuntu wrapper.

Hi, thanks for answering. 

I find it is caused by running in wrong way.
