### ISSUE TITLE
running grin-wallet check against grin >= 3.0.0 using older versions of grin-wallet results in infinite loops

### ISSUE THREAD

**Issue by cgilliard** [mimblewimble/grin#3199]
**Describe the bug**
When using older versions of the grin-wallet or wallet713 against grin 3.0.0, 'check' command fails. The API is supposed to return highest_index and last_retrieved_index, but appears to return a different value. This is related to a change in txhashset.rs. Making this change fixes the issue:

        /// highest output insertion index available
        pub fn highest_output_insertion_index(&self) -> u64 {
-                pmmr::n_leaves(self.output_pmmr_h.last_pos)
+                //pmmr::n_leaves(self.output_pmmr_h.last_pos)
+                 // API expected the max vali in mmr_index units that are sparce
+                self.output_pmmr_h.last_pos
        }

Not only does this error produce issues with running older wallets that rely on 'highest_index', but also the API is inaccurate.

**To Reproduce**
1. Run '...' using grin-wallet < 3.0
grin-wallet check
The result is an infinite loop.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin/pull/3200 closing.
