### ISSUE TITLE
Reinstallation. wallet.dat/wallet.seed

### ISSUE THREAD

**Issue by mass34** [mimblewimble/grin#320]
Reinstall with replacement wallet.dat/wallet.seed

Nov 18 23:10:32.133 INFO Starting validation pipeline for block header 2676a458 at 510.
 Nov 18 23:10:32.133 INFO Invalid block header 2676a458: Orphan.
 Nov 18 23:10:32.134 INFO Starting validation pipeline for block header 7d54f41e at 511.
 Nov 18 23:10:32.134 INFO Invalid block header 7d54f41e: Orphan.
 Nov 18 23:10:32.134 INFO Added 0 headers to the header chain.
 Nov 18 23:10:33.245 DEBG Sync: peer 11537636 vs us 1
Nov 18 23:10:33.245 DEBG Sync: blocks to download 0, block downloading 0
Nov 18 23:10:33.245 DEBG Loc heights: [0, 0]
Nov 18 23:10:33.246 DEBG Asking peer 51.255.202.83:13414 for more block headers, locator:                                                           [e17ea64f, e17ea64f]                                                                                                                                                    
Nov 18 23:10:33.932 INFO Received 511 block headers
Nov 18 23:10:33.933 INFO Starting validation pipeline for block header 254b265f at 1.
Nov 18 23:10:33.933 DEBG Validating block with cuckoo size 30
Nov 18 23:10:33.934 INFO Invalid block header 254b265f: InvalidPow.

Loop on block 511

`# ./grin wallet -p pass -s outputs
Nov 18 23:33:09.833 INFO Using configuration file at: ~/grin/target/debug/grin.toml
Nov 18 23:33:09.835 DEBG Using wallet seed file at: ./wallet.seed
Nov 18 23:33:09.947 DEBG Refreshing wallet outputs
Nov 18 23:33:09.996 INFO Acquiring wallet lock ...
Nov 18 23:33:09.996 DEBG Attempting to acquire wallet lock
Nov 18 23:33:10.011 INFO ... released wallet lock

Wallet Outputs - Block Height: 0
thread 'main' panicked at 'attempt to subtract with overflow', wallet/src/types.rs:252:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

**Comment by mass34** [comment]
Hi.
./grin server -m run
Nov 21 02:37:48.471 WARN P2P server started on 0.0.0.0:13414
Nov 21 02:37:48.474 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block e9e0a597', grin/src/sync.rs:192:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

and could not load the block

**Comment by mass34** [comment]
How it turned out is unknown, but it worked.
1.files `wallet.dat` and `wallet.seed` have successfully earned.
2. chain of blocks loaded before 7401
3. new [problem](https://github.com/mimblewimble/grin/issues/372)

**Comment by ignopeverell** [comment]
This should be fixed now. Please update and rebuild.
