### ISSUE TITLE
error EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by githubusrR** [mimblewimble/grin#3202]
Unknown error

error EOF while parsing a value at line 1 column 0

Grin Version 3.0.0 (proto: 2)

![1](https://user-images.githubusercontent.com/46305976/72784750-4d944d80-3c4b-11ea-8b38-9732e0fcc638.jpg)

**Comment by quentinlesceller** [comment]
Can you copy paste the logs here?

**Comment by githubusrR** [comment]
20200121 10:07:59.831 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash c3c976e9586c, edge_bits 29, nonce 2361583661718363076, job_id 4, difficulty 2927/2022
20200121 10:08:01.004 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 7a8fa9c03154, edge_bits 29, nonce 7917663478785432546, job_id 5, difficulty 4676/2022
20200121 10:08:02.242 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 4c15659694d5, edge_bits 29, nonce 7917663478785432578, job_id 5, difficulty 7533/2022
20200121 10:08:02.305 INFO grin_servers::mining::stratumserver - Worker 1 connected
20200121 10:08:02.306 ERROR grin_servers::mining::stratumserver - error EOF while parsing a value at line 1 column 0
20200121 10:08:02.306 INFO grin_servers::mining::stratumserver - Worker 1 disconnected
20200121 10:08:02.635 INFO grin_servers::mining::stratumserver - Worker 2 connected
20200121 10:08:02.663 ERROR grin_servers::mining::stratumserver - error expected value at line 1 column 1
20200121 10:08:02.663 INFO grin_servers::mining::stratumserver - Worker 2 disconnected
20200121 10:08:03.053 INFO grin_servers::mining::stratumserver - Worker 3 connected
20200121 10:08:03.081 ERROR grin_servers::mining::stratumserver - error stream did not contain valid UTF-8
20200121 10:08:03.081 INFO grin_servers::mining::stratumserver - Worker 3 disconnected
20200121 10:08:03.799 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 3ae07242517b, edge_bits 29, nonce 7917663478785432617, job_id 5, difficulty 9735/2022
20200121 10:08:07.366 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash c71d8024b3b5, edge_bits 29, nonce 7917663478785432712, job_id 5, difficulty 2878/2022
20200121 10:08:08.763 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 5cd407a09475, edge_bits 29, nonce 7917663478785432747, job_id 5, difficulty 6174/2022
20200121 10:08:11.273 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash c171b3953cc8, edge_bits 29, nonce 7917663478785432811, job_id 5, difficulty 2963/2022
20200121 10:08:13.378 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 38683cac63df, edge_bits 29, nonce 7917663478785432866, job_id 5, difficulty 10161/202
20200121 10:08:14.506 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 1d683b78d0a8, edge_bits 29, nonce 7917663478785432893, job_id 5, difficulty 19491/202
20200121 10:08:15.018 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 6159309f3d4a, edge_bits 29, nonce 7917663478785432913, job_id 5, difficulty 5887/2022
20200121 10:08:15.312 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 058315f7bc62, edge_bits 29, nonce 7021155898321460564, job_id 6, difficulty 103987/20
20200121 10:08:15.730 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 531386, hash 62f34faa90b5, edge_bits 29, nonce 7021155898321460574, job_id 6, difficulty 5792/2022

**Comment by githubusrR** [comment]
most often this happens on 31 algorithms

**Comment by AlexSpain** [comment]
20200130 09:47:30.554 ERROR grin_servers::mining::stratumserver - error invalid type: integer `0`, expected a string at line 1 column 7

**Comment by githubusrR** [comment]
Ubuntu 18.04
Grin Version 3.0.0 (proto: 2)
grin 31

If this error disables the worker, what caused this problem?





20200215 03:48:41.574 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 566816, hash 3eb403ca6590, edge_bits 31, nonce 2228353539971835569, job_id 9, difficulty 27174/1249708458, submitted by rig2
20200215 03:48:41.971 INFO grin_servers::mining::stratumserver - Worker 19 connected
20200215 03:48:41.975 ERROR grin_servers::mining::stratumserver - error stream did not contain valid UTF-8
20200215 03:48:41.975 INFO grin_servers::mining::stratumserver - Worker 19 disconnected

**Comment by githubusrR** [comment]
Ubuntu 18.04
Grin Version 3.0.0 (proto: 2)
grin 31

0200219 18:19:35.847 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 03b1fa9268a8, edge_bits 31, nonce 14228029743047582092, job_id 0, difficulty 461117/1395472850, submitted by rig14
20200219 18:19:43.951 INFO grin_servers::mining::stratumserver - Worker 21 connected
20200219 18:19:44.201 ERROR grin_servers::mining::stratumserver - error EOF while parsing a value at line 1 column 0
20200219 18:19:44.201 INFO grin_servers::mining::stratumserver - Worker 21 disconnected
20200219 18:19:44.601 INFO grin_servers::mining::stratumserver - Worker 22 connected
20200219 18:19:44.703 ERROR grin_servers::mining::stratumserver - error expected value at line 1 column 1
20200219 18:19:44.703 INFO grin_servers::mining::stratumserver - Worker 22 disconnected
20200219 18:19:45.357 INFO grin_servers::mining::stratumserver - Worker 23 connected
20200219 18:19:45.462 ERROR grin_servers::mining::stratumserver - error stream did not contain valid UTF-8
20200219 18:19:45.462 INFO grin_servers::mining::stratumserver - Worker 23 disconnected
20200219 18:19:48.875 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 046f699f1d95, edge_bits 31, nonce 2949219193075739915, job_id 0, difficulty 384184/1395472850, submitted by rig6
20200219 18:20:08.116 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 002672a12352, edge_bits 31, nonce 12519647621356924234, job_id 0, difficulty 11345459/1395472850, submitted by rig8
20200219 18:20:11.509 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 06816647ee37, edge_bits 31, nonce 10136216869754580141, job_id 0, difficulty 261923/1395472850, submitted by rig5
20200219 18:20:13.511 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 03a4921bcbfd, edge_bits 31, nonce 9428399804037933856, job_id 0, difficulty 467747/1395472850, submitted by rig11
20200219 18:20:23.367 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 0704956514ed, edge_bits 31, nonce 5926383608042037261, job_id 0, difficulty 242798/1395472850, submitted by rig10
20200219 18:20:46.619 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 0155809b7c75, edge_bits 31, nonce 2845110216612849540, job_id 0, difficulty 1277319/1395472850, submitted by rig13
20200219 18:20:51.673 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 07327f818b8c, edge_bits 31, nonce 5926383608042037513, job_id 0, difficulty 236747/1395472850, submitted by rig10
20200219 18:21:18.791 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 061dc60e65a4, edge_bits 31, nonce 2845110216612849826, job_id 0, difficulty 278589/1395472850, submitted by rig13
20200219 18:21:32.189 INFO grin_servers::mining::stratumserver - Worker 24 connected

**Comment by githubusrR** [comment]
Ubuntu 18.04
Grin Version 3.0.0 (proto: 2)
grin 31

0200219 18:19:35.847 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 03b1fa9268a8, edge_bits 31, nonce 14228029743047582092, job_id 0, difficulty 461117/1395472850, submitted by rig14
20200219 18:19:43.951 INFO grin_servers::mining::stratumserver - Worker 21 connected
20200219 18:19:44.201 ERROR grin_servers::mining::stratumserver - error EOF while parsing a value at line 1 column 0
20200219 18:19:44.201 INFO grin_servers::mining::stratumserver - Worker 21 disconnected
20200219 18:19:44.601 INFO grin_servers::mining::stratumserver - Worker 22 connected
20200219 18:19:44.703 ERROR grin_servers::mining::stratumserver - error expected value at line 1 column 1
20200219 18:19:44.703 INFO grin_servers::mining::stratumserver - Worker 22 disconnected
20200219 18:19:45.357 INFO grin_servers::mining::stratumserver - Worker 23 connected
20200219 18:19:45.462 ERROR grin_servers::mining::stratumserver - error stream did not contain valid UTF-8
20200219 18:19:45.462 INFO grin_servers::mining::stratumserver - Worker 23 disconnected
20200219 18:19:48.875 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 046f699f1d95, edge_bits 31, nonce 2949219193075739915, job_id 0, difficulty 384184/1395472850, submitted by rig6
20200219 18:20:08.116 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 002672a12352, edge_bits 31, nonce 12519647621356924234, job_id 0, difficulty 11345459/1395472850, submitted by rig8
20200219 18:20:11.509 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 06816647ee37, edge_bits 31, nonce 10136216869754580141, job_id 0, difficulty 261923/1395472850, submitted by rig5
20200219 18:20:13.511 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 03a4921bcbfd, edge_bits 31, nonce 9428399804037933856, job_id 0, difficulty 467747/1395472850, submitted by rig11
20200219 18:20:23.367 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 0704956514ed, edge_bits 31, nonce 5926383608042037261, job_id 0, difficulty 242798/1395472850, submitted by rig10
20200219 18:20:46.619 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 0155809b7c75, edge_bits 31, nonce 2845110216612849540, job_id 0, difficulty 1277319/1395472850, submitted by rig13
20200219 18:20:51.673 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 07327f818b8c, edge_bits 31, nonce 5926383608042037513, job_id 0, difficulty 236747/1395472850, submitted by rig10
20200219 18:21:18.791 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 573434, hash 061dc60e65a4, edge_bits 31, nonce 2845110216612849826, job_id 0, difficulty 278589/1395472850, submitted by rig13
20200219 18:21:32.189 INFO grin_servers::mining::stratumserver - Worker 24 connected

**Comment by quentinlesceller** [comment]
Closing. Feel free to open another one if this is happening again.
