### ISSUE TITLE
The grin freezes server

### ISSUE THREAD

**Issue by githubusrR** [mimblewimble/grin#3218]
ubuntu 18.04
Grin Version 3.0.0 (proto: 2)  
solo mining
gminer 1.96

The grin freezes server, at this point, the rigs are disconnected from the server

20200202 19:07:58.903 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/kernel/pmmr_data.bin" -> "kernel/pmmr_data.bin"
20200202 19:07:59.013 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/kernel/pmmr_hash.bin" -> "kernel/pmmr_hash.bin"
20200202 19:07:59.073 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/output/pmmr_data.bin" -> "output/pmmr_data.bin"
20200202 19:07:59.078 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/output/pmmr_hash.bin" -> "output/pmmr_hash.bin"
20200202 19:07:59.097 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/output/pmmr_prun.bin" -> "output/pmmr_prun.bin"
20200202 19:07:59.097 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/rangeproof/pmmr_data.bin" -> "rangeproof/pmmr_data.bin"
20200202 19:07:59.203 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/rangeproof/pmmr_hash.bin" -> "rangeproof/pmmr_hash.bin"
20200202 19:07:59.221 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/rangeproof/pmmr_prun.bin" -> "rangeproof/pmmr_prun.bin"
20200202 19:07:59.221 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/output/pmmr_leaf.bin.000028029f31" -> "output/pmmr_leaf.bin.000028029f31"
20200202 19:07:59.222 INFO grin_util::zip - compress: "/home/grin/chain_data/txhashset_zip_000028029f31/rangeproof/pmmr_leaf.bin.000028029f31" -> "rangeproof/pmmr_leaf.bin.000028029f31"

INFO grin_servers::mining::stratumserver - Worker 12 disconnected

Can I disable this backup?

**Comment by antiochp** [comment]
Ahh - this is not a "backup" its actually your node acting as a good citizen and providing a copy fo the txhashset (the chain state) to another peer who joined the network and is syncing from you.

If I understand you problem it appears your node is then actually dropping stratum connections, which are not reconnecting?

**Comment by githubusrR** [comment]
Connections are restored after a while, but at this time there may be a block and I will lose it

**Comment by githubusrR** [comment]
How do I disable this?

**Comment by quentinlesceller** [comment]
Closed for #3247.
