### ISSUE TITLE
List GrinTest tool

### ISSUE THREAD

**Issue by antonio-fr** [mimblewimble/grin#325]
As you asked for an issue as a remainder, please list grintest.net web site service on grin-tech.org and eventually in some relevant documentation.
This is a web service that gives real-time information about the Grin chain. 

Would you add the current difficulty in the node API? That would be very helpful.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin/pull/390 ?
Also you can get the current difficulty by querying ```/v1/chain```or ```v1/status```.
