### ISSUE TITLE
Errors in the server log

### ISSUE THREAD

**Issue by githubusrR** [mimblewimble/grin#3259]
ubuntu 18.04
Grin Version 3.1.0-beta.1 (proto: 2)

In the server log, I encounter errors that I don't understand:

20200302 08:45:34.199 ERROR grin_servers::mining::stratumserver - (Server ID: 0) Failed to validate share at height 590063, hash b4bc024e0101, edge_bits 31, nonce 13070120054834367379, job_id 0. Err(Error { inner: Verification Error: edge too big })

20200302 01:49:21.647 INFO grin_servers::mining::stratumserver - Worker 29 connected
20200302 01:49:23.608 ERROR grin_servers::mining::stratumserver - error reading line: Unable to decode input as UTF8
20200302 01:49:23.608 INFO grin_servers::mining::stratumserver - Worker 29 disconnected

**Comment by githubusrR** [comment]
20200305 00:30:22.363 INFO grin_servers::mining::stratumserver - Worker 5 connected
20200305 00:30:22.651 ERROR grin_servers::mining::stratumserver - error serializing line: EOF while parsing a value at line 1 column 0
20200305 00:30:22.651 INFO grin_servers::mining::stratumserver - Worker 5 disconnected
20200305 00:30:23.032 INFO grin_servers::mining::stratumserver - Worker 5 connected
20200305 00:30:23.072 ERROR grin_servers::mining::stratumserver - error serializing line: expected value at line 1 column 1
20200305 00:30:23.072 INFO grin_servers::mining::stratumserver - Worker 5 disconnected

**Comment by jaspervdm** [comment]
Errors like "error serializing line: EOF while parsing a value at line 1 column 0" happen when the miner disconnects (for whatever reason) in the middle of sending a message. Unless they happen all the time, I don't think there's an issue here

**Comment by quentinlesceller** [comment]
Closing then.
