### ISSUE TITLE
Basic-Auth behavior 

### ISSUE THREAD

**Issue by MCM-Mike** [mimblewimble/grin#3272]
**Describe the bug**
Tested with v3.1.x if basic auth is disabled on a Grin-Node it still accepts request with a random basic-auth password. 

**To Reproduce**
1. Run GRIN-Node without API basic auth
2. connect from your grin wallet and send API request including any (ramdom) basic-auth password. 

**Additional context**
Will this behavior change in the near future ?
Ar you planning to block request to a Node (without basic auth) when a wallet sends a basic auth API request ?

**Comment by antiochp** [comment]
The `Authorization` header will simply be ignored if the server is not expecting it (auth is disabled).
I believe this is expected behavior in this situation.

**Comment by MCM-Mike** [comment]
> The `Authorization` header will simply be ignored if the server is not expecting it (auth is disabled).
> I believe this is expected behavior in this situation.

as long as its not changing this behavior, you can close this issue. 

_Background info: One of the Mobile-Wallet developer is allowing the user to choose between his own GRIN-Node and the public Grinnode.live wallet-API which has basic auth disabled._
