### ISSUE TITLE
Grin max supply

### ISSUE THREAD

**Issue by HatemAMA** [mimblewimble/grin#3290]
Max supply of Grin subjected to yearly emission and it is no limited so at long term there will be more and more so the value of Grin will be lower and lower by time on the other hands Bitcoin have max 21 millions , i have a suggestion to make a new model consist of max supply and do what makes miners reach it long term , thanks

**Comment by antiochp** [comment]
Yeah. No.

**Comment by antiochp** [comment]
This was one of the original ideas around Grin and _very_ unlikely to change.

Constant supply with a known set of very simple rules defining that supply (1 per second).
