### ISSUE TITLE
Miner out of sync with network

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#330]
Had another case of the miner getting out of sync with the network. Narrowed down the window of this happening a bit. At around 23:40 UTC I receive my last valid block from the network (f8773e56 at height 3330). My miner then mines a block (dd6932bf at height 3331) on top of that and updates the head on the local chain accordingly, at 23:58 UTC. In the mean time no blocks are being received from the network till around 00:15 UTC. Until 00:13 UTC I was connected to 15 peers, at which time the connections start to drop rapidly to 8 after which I start making new connections again. Until at 00:15 UTC I receive my first new block from the network again (dc30f0a8 at height 3362) all the while my miner has been mining on top of block dd6932bf at height 3331 and declares all subsequent incoming blocks as Orphans.

Details in log file (20MB uncompressed)
[grin.log.gz](https://github.com/mimblewimble/grin/files/1485348/grin.log.gz)

**Comment by ignopeverell** [comment]
You should have received a 3331 block from the network around 23:43 UTC but obviously didn't. Your miner just does its job but it looks like you got isolated from the network for some reason.

**Comment by photis** [comment]
Yes, that was my assumption too. My connection here is pretty flaky, that'll improve massively in a month's time.

**Comment by ignopeverell** [comment]
That's good to know, so my main hunch now that we're not detecting TCP connections close properly. We do have proper handling of close but it doesn't look like we get the notification from the TCP stack, or the default timeout is way too long.

**Comment by ignopeverell** [comment]
We're trying to track most sync issues under doc/usage.md. Thanks for the testing!
