### ISSUE TITLE
getjobtemplate    or job   return   error  difficulty

### ISSUE THREAD

**Issue by EWIT521** [mimblewimble/grin#3322]
{"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":1,"height":690789,"job_id":1,"pre_pow":"000300000000000a8a65000000005eb9268c0001a5f4d5aa76de3de80fa757f613316a3c89ad59931408c56c18f2f16dac91bad504737fd1fa12d80d283205241f800acf224dd11c8432e3dafbf79219d87cdd3056855f2dc1ea1d58eee7dfba7505a3a39c1720069324022ae04569c7a203a4313b97e6f92637b76b0c6a6b6791b667d3b5e23a5339634740fce871e354ed4e259a677a1ed1fba385ced30b20503457d6f10d6903fa25ed20fac77a3f00feecb6592922b91f4e01f0395ef5a4f90bcada0ab658bc4ed4ff5b4849b5ad222000000000006c146000000000003c12210005c7f218be686c00000447"}}

The network difficulty returned by the node is always 1
Who can answer this question???

**Comment by quentinlesceller** [comment]
This is the minimum share difficulty and you can configure it in grin-miner.toml.
