### ISSUE TITLE
[code hygiene] tests in config folder fail

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#333]
fields server and miner are not properly set up for testing

Repro: cd server; cargo test

**Comment by ignopeverell** [comment]
Can you elaborate? I don't have a `server` folder in my source tree :-)

**Comment by sesam** [comment]
Oh, I misread, 'tis in the config folder.

```
$ cargo test --all
[...]
error[E0609]: no field `server` on type `types::GlobalConfig`
   --> config/src/config.rs:216:10
216 | 	decoded.server.[....]

error[E0609]: no field `mining` on type `types::GlobalConfig`
   --> config/src/config.rs:216:59
216 | 	decoded.server.[...]

error[E0609]: no field `server` on type `types::GlobalConfig`
   --> config/src/config.rs:217:43
decoded.server. ....
error[E0609]: no field `wallet` on type `types::GlobalConfig`
   --> config/src/config.rs:218:43
decoded.wallet. ....

```


Same 4 errors, both on master and on milestone/testnet1

Quick guess: configuration for for config/src -tests needs to be updated, or defaults for server/miner/wallet need to be added.
