### ISSUE TITLE
[req] How to track what tests need to be re-run to keep all tests green?

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#335]
Opening an issue to collect ideas/opinions on how to make testing easy and fast.

If I understand right, "cargo test" only looks under src/ from current working directory when it runs tests. No command line switches etc, and not all folders are test-folders, so there surely exists some tool that handles this?

I'm now experimenting with cargo-watch to get tests to run automatically.

A quick stopgap solution is to make an alias and manually list all folders:
   `alias grin_fulltest="(cd api; cargo test); (cd chain; cargo test); (cd config; cargo test); (cd core; cargo test); (cd doc; cargo test); (cd grin; cargo test); (cd keychain; cargo test); (cd p2p; cargo test); (cd pool; cargo test); (cd pow; cargo test); (cd store; cargo test); (cd util; cargo test); (cd wallet; cargo test)"`

**Comment by ignopeverell** [comment]
`cargo test --all` under the root directory will run test on all sub-crates.

**Comment by sesam** [comment]
Nice! I'm sure I tried that earlier. I'll add it in CONTRIBUTING.md more visibly, maybe in a step by step what to do and how to push a branch. Thanks
