### ISSUE TITLE
Mining on a multi core Xeon [[mining.cuckoo_miner_plugin_config]]

### ISSUE THREAD

**Issue by HuskarK** [mimblewimble/grin#336]
My configuration is an Intel Xeon E5-2620v4 CPU with 16 gb of ram running Ubuntu x64 17.04.

In my grin.toml I've set threads to 14:
```
[[mining.cuckoo_miner_plugin_config]]
type_filter = "mean_cpu"
parameter_list = {NUM_THREADS=14, NUM_TRIMS=68}
```

The result is still ~10% CPU load:

```
Nov 19 20:00:20.496 DEBG monitoring peers (11)
Nov 19 20:00:21.003 DEBG Plugin 0 - Device 0 (CPU) - Last Graph time: 0.01; Graphs per second: 100.000
Nov 19 20:00:24.002 DEBG Plugin 0 - Device 0 (CPU) - Last Graph time: 0.003; Graphs per second: 333.333
Nov 19 20:00:27.002 DEBG Plugin 0 - Device 0 (CPU) - Last Graph time: 0.003; Graphs per second: 333.333
Nov 19 20:00:30.003 DEBG Plugin 0 - Device 0 (CPU) - Last Graph time: 0.002; Graphs per second: 500.000
Nov 19 20:00:30.496 DEBG monitoring peers (11)
```

Changing NUM_THREADS seems have no effect.

**Comment by photis** [comment]
Fwiw my Intel Kaby Lake i7 7700K with 8 cores and 32GB ram hovers around 20% utilisation for all cores (mean_cpu, threads=8). I assumed that was normal in this phase, never brought it up for that reason.
Graphs per second is usually 1000, sometimes inf
Memory utilisation (in total) is below 6 GB (18%)

Grin is the only process running on this machine and all 8 cores are at this 20% utilisation. They immediately drop to next to nothing when I stop Grin.
Running Ubuntu 16.04

**Comment by OleAd** [comment]
I'm running Ubuntu 17.10 in Virtualbox, on an i5-5300u with 2 cores dedicated to the Virtualbox, and I'm getting between 333 and 500 graphs per second.

**Comment by yeastplume** [comment]
I'm going to try a few optimisations to the cuckoo miner over the next few days, namely try and avoid a few memory allocations, and possibly try to allow running many instances of the solver in parallel. I'll also try and update the timing outputs to be a little more precise.

However, I wouldn't consider this an issue worth spending a lot of time resolving at the moment, as testnet1 is running at a vastly reduced cuckoo graph size (cuckoo 16) from what's intended in production (cuckoo 30), which takes longer and usesfar more RAM. This is what top looks like when running full cuckoo 30 on an i7 4790k with 4 threads:

```
%Cpu0  :  94.7/0.0    95[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||     ]
%Cpu1  :   0.0/0.0     0[                                                                                                    ]
%Cpu2  :  95.3/0.0    95[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||     ]
%Cpu3  :  94.7/0.0    95[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||     ]
%Cpu4  :   0.0/0.0     0[                                                                                                    ]
%Cpu5  :  89.4/0.0    89[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||           ]
%Cpu6  :   0.0/0.0     0[                                                                                                    ]
%Cpu7  :   0.7/0.0     1[|                                                                                                   ]
```

With memory usage up to 4GB for the solver. Testnet1 is just set up that so any machine can mine successfully, and there's very little focus on the efficiency of the miners themselves (especially at cuckoo 16). This will come after further testnets and mainnet.
