### ISSUE TITLE
Revisit fee structure

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#3369]
The current minimum relay fee rules use

  accept_fee_base = 1000000

as set in the default grin-server.toml.
Since this is in units of nanogrin, it expresses a base cost of 1 milli-grin.
This is what you pay for each unit of a transaction weight, which is defined in

https://github.com/mimblewimble/grin/blob/20e5c1910bcc1afa317a7847b398488ac08b0ca7/core/src/core/transaction.rs#L847-L856

as the linear combination 4 * #outputs + 1 * #kernels + (-1) * #inputs, with a minimum of 1.
This means that a typical tx with 2 outputs, 1 input and 1 kernel requires a relay fee of 8 milligrin,
currently worth about 1/3 cent.

We should revisit this base fee and tx weight coefficients to provide a good long term balance
between spam resistance and tx affordability. It would also be nice to make the  tx weight coefficients seem less arbitrary.

**Comment by lehnberg** [comment]
Is there some fee structure that could promote privacy preserving output selection? Recall the discussion in https://github.com/mimblewimble/grin/pull/2186 for instance.

For example, what if we could inceltivize 'balanced' transactions? (two inputs spend to two outputs), or some other structure that makes the tx graph better obfuscated.

**Comment by tromp** [comment]
Yes, we should consider incentivizing privacy enhancing transactions.
A tx with 2 inputs and 2 outputs should not necessarily cost more in fees than a tx with only 1 input and 2 outputs. That means we need to look beyond just linear combinations.

**Comment by lehnberg** [comment]
https://github.com/mimblewimble/grin/pull/3481

**Comment by antiochp** [comment]
Closing - included as part of `5.0.0`.
