### ISSUE TITLE
Spent output cannot be found

### ISSUE THREAD

**Issue by xuyulinnn** [mimblewimble/grin#3388]
08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66
![image](https://user-images.githubusercontent.com/24400773/86893047-a3927a00-c133-11ea-8a1d-2595200a7e00.png)
![image](https://user-images.githubusercontent.com/24400773/86893073-abeab500-c133-11ea-945f-80747973e73e.png)

**Comment by antiochp** [comment]
Just so I understand the issue correctly - 

* We are searching for `08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66` via the api.
* This output is spent so we cannot necessarily expect to find it (it is likely be pruned).
* The api is returning unrelated results? 
  * Output `08b7e57c448db5ef25aa119dde2312c64d7ff1b890c416c6dda5ec73cbfed2edea ` appears unrelated to search?
  * @quentinlesceller api request appears to return this spurious result _twice_?

**Comment by antiochp** [comment]
This is what I see on my node - 

```
curl --location --request POST 'http://localhost:3413/v2/foreign' --header 'Content-Type: application/json' --data-raw '{
        "jsonrpc": "2.0",
        "method": "get_outputs",
        "params": [
                [
                        "08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66"
                ],
                0,
                0,
                null,
                null
        ],
        "id": 1
}'
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": []
  }
}
```


And for completeness (searching for `08b7e57c...`) -

```
curl --location --request POST 'http://localhost:3413/v2/foreign' --header 'Content-Type: application/json' --data-raw '{
        "jsonrpc": "2.0",
        "method": "get_outputs",
        "params": [
                [
                        "08b7e57c448db5ef25aa119dde2312c64d7ff1b890c416c6dda5ec73cbfed2edea"
                ],
                0,
                0,
                null,
                null
        ],
        "id": 1
}'
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": [
      {
        "block_height": 0,
        "commit": "08b7e57c448db5ef25aa119dde2312c64d7ff1b890c416c6dda5ec73cbfed2edea",
        "merkle_proof": null,
        "mmr_index": 1,
        "output_type": "Coinbase",
        "proof": null,
        "proof_hash": "6c301688d9186c3a99444f827bdfe3b858fe87fc314737a4dc1155d9884491d2",
        "spent": false
      }
    ]
  }
}
```

**Comment by antiochp** [comment]
`get_outputs_v2()` appears to be doing some dubious stuff with `concat()` and looking for outputs in two different ways.

I'm not sure the logic in there is actually correct.

**Comment by antiochp** [comment]
@xuyulinnn Can you try this again, but passing in `null` for both `start_height` and `end_height`?

```
curl --location --request POST 'http://localhost:3413/v2/foreign' --header 'Content-Type: application/json' --data-raw '{
        "jsonrpc": "2.0",
        "method": "get_outputs",
        "params": [
                [
                        "08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66"
                ],
                null,
                null,
                null,
                null
        ],
        "id": 1
}'
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": []
  }
}
```

This endpoint is being used for a couple of different purposes and I don't think you want to specify `start_height` and `end_height` if you are actually searching for a known output commitment.

**Comment by xuyulinnn** [comment]
> @xuyulinnn Can you try this again, but passing in `null` for both `start_height` and `end_height`?
> 
> ```
> curl --location --request POST 'http://localhost:3413/v2/foreign' --header 'Content-Type: application/json' --data-raw '{
>         "jsonrpc": "2.0",
>         "method": "get_outputs",
>         "params": [
>                 [
>                         "08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66"
>                 ],
>                 null,
>                 null,
>                 null,
>                 null
>         ],
>         "id": 1
> }'
> {
>   "id": 1,
>   "jsonrpc": "2.0",
>   "result": {
>     "Ok": []
>   }
> }
> ```
> 
> This endpoint is being used for a couple of different purposes and I don't think you want to specify `start_height` and `end_height` if you are actually searching for a known output commitment.
> 
> By specifying `start_height=0` and `end_height=0` you are actually returning the search results _and_ additionally any outputs at height 0 (the genesis block). This is obviously not correct behavior, but I think explains what you are seeing.
> 
> @quentinlesceller You are seeing a duplicate result in your api response because you are searching for that output explicitly _and_ also getting it back as it falls in height=0. This endpoint is doing _two_searches given this combination of params and concatenating the results in the response...
> 
> I don't see any results because my node is not a full archival node and I do not have the full block at height 0 in the db.
> I also don't see the actual output being searched for as it is spent and pruned.
you can search it(08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66) on explore,it actually exsist
my node is full archival node, but return also is empty.

**Comment by xuyulinnn** [comment]
@antiochp 
you can search it(08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66) on explore,it actually exsist
my node is full archival node, but return also is empty.

**Comment by antiochp** [comment]
The spent output is pruned and no longer available on the node.
It might exist in the explorer database, but that is an implementation detail on the explorer itself.

**Comment by quentinlesceller** [comment]
Indeed @antiochp I mixed up the outputs.
This is what I have one my 4.0.0 node:
```
curl --location --request POST 'http://localhost:3413/v2/foreign' --header 'Content-Type: application/json' --data-raw '{
	"jsonrpc": "2.0",
	"method": "get_outputs",
	"params": [
		[
			"08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66"
		],
		0,
		0,
		null,
		null
	],
	"
```
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": [
      {
        "block_height": 0,
        "commit": "08b7e57c448db5ef25aa119dde2312c64d7ff1b890c416c6dda5ec73cbfed2edea",
        "merkle_proof": null,
        "mmr_index": 1,
        "output_type": "Coinbase",
        "proof": null,
        "proof_hash": "6c301688d9186c3a99444f827bdfe3b858fe87fc314737a4dc1155d9884491d2",
        "spent": false
      }
    ]
  }
}
```

**Comment by antiochp** [comment]
@quentinlesceller ok yeah that makes sense. Your archive node has full block at height 0. So what gets returned is not (just) the output searched for, but all outputs in that block.

This is definitely confusing and inconsistent behavior depending on what params are passed in.

**Comment by quentinlesceller** [comment]
After some thoughts this is actually not a bug but you are trying to do two things here @xuyulinnn:

- Retrieves output `08bcea82f4c216d2c8bb95fdd486adab9c5248458c22fae367e614f820f8ad6b66`. Which is spent so pruned from the MMR and as such cannot be retrieved.
- Retrieves output at block 0 which is `08b7e57c448db5ef25aa119dde2312c64d7ff1b890c416c6dda5ec73cbfed2edea`.

So the current behaviour is normal.
