### ISSUE TITLE
always get stuck at 99% of Downloading blocks

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#3417]
Log file at https://tromp.github.io/grin-server.log
TUI screen:

![Screen Shot 2020-08-08 at 12 01 51 AM](https://user-images.githubusercontent.com/2347227/89691974-a89d4180-d90a-11ea-9506-e4e487d54767.png)

**Comment by antiochp** [comment]
First few lines of the logs for reference, then it just basically repeats the same stuff - 

```
20200806 13:51:20.803 DEBUG grin_servers::grin::sync::body_sync - block_sync: 812160/815579 requesting blocks [00021d0295bd, 0002738cea28] from 8 peers
20200806 13:51:20.803 DEBUG grin_p2p::peer - Requesting block 00021d0295bd from peer 47.111.191.20:13414.
20200806 13:51:20.803 DEBUG grin_servers::common::adapters - Received block 00021d0295bd at 812360 from 47.111.191.20:13414 [in/out/kern: 0/1/1] going to process.
20200806 13:51:20.803 DEBUG grin_chain::chain - is_orphan: 00021d0295bd, # orphans 200, # evicted 20159
20200806 13:51:20.803 DEBUG grin_p2p::protocol - handle_payload: received block: msg_len: 3545
20200806 13:51:20.803 DEBUG grin_p2p::peer - Requesting block 0002738cea28 from peer 35.181.35.93:3414.
20200806 13:51:20.803 DEBUG grin_chain::chain - is_orphan: 00021d0295bd, # orphans 200, # evicted 20159
20200806 13:51:20.803 DEBUG grin_servers::common::adapters - Received block 0002738cea28 at 812361 from 18.204.166.78:3414 [in/out/kern: 1/4/2] going to process.
20200806 13:51:20.803 DEBUG grin_chain::chain - is_orphan: 0002738cea28, # orphans 199, # evicted 20161
20200806 13:51:20.816 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
20200806 13:51:20.816 DEBUG grin_chain::chain - body_sync: body_head - 0001f59f4086, 812160, header_head - 000074409e25, 815579, sync_head - 00031f5714bd, 815564
20200806 13:51:20.846 DEBUG grin_p2p::protocol - handle_payload: received block: msg_len: 3545
20200806 13:51:20.847 DEBUG grin_servers::common::adapters - Received block 0002738cea28 at 812361 from 35.181.35.93:3414 [in/out/kern: 1/4/2] going to process.
20200806 13:51:20.847 DEBUG grin_chain::chain - is_orphan: 0002738cea28, # orphans 200, # evicted 20161
```

**Comment by tromp** [comment]
I still find it annoying that when you see
requesting blocks [00021d0295bd, 0002738cea28] from 8 peers
it doesn't tell you what heights those correspond to....

**Comment by tromp** [comment]
If I have a chain of headers going all the way from 0  to 815564, and request some blocks around height 812160 or 812360, then how could they be orphans? Orphans don't have thousands of block on top of them!

**Comment by antiochp** [comment]
We also see some other block requests occasionally. The logs are not always repeating the exact same pair of block hashes.

```
requesting blocks [0000ae23edd4, 0002738cea28]
```

```
requesting blocks [000070012df2, 00020483df0c]
```

```
requesting blocks [00015172cbf8, 0000c9e415c7, 00006ceecb0a, 0002baf49e10, 0000a20f4c34, 000075cd15df, 0000b3c51cd4, 000009e25404, 0001b45fb11f, 00003d2f716e, 000140bd9eec, 000039a878fc, 00030153531d, 0001f207bed3, 0001c80bc101, 00001a53af65, 00028df7fc99, 0000aac70c82, 000291b12c14, 00019eb1b822, 00003f169b73, 000078cc209f, 0001442fd879, 0000e9d60bae, 0002738cea28]
```

**Comment by antiochp** [comment]
> If I have a chain of headers going all the way from 0 to 815564, and request some blocks around height 812160 or 812360, then how could they be orphans? Orphans don't have thousands of block on top of them!

I think we are using the term "orphan" here incorrectly. An "orphan" is this context is a _full_ block where we do not have the _previous_ full block, regardless of headers themselves.

**Comment by antiochp** [comment]
> We also see some other block requests occasionally. The logs are not always repeating the exact same pair of block hashes.
> 
> ```
> requesting blocks [0000ae23edd4, 0002738cea28]
> ...
> Received block 0000ae23edd4 at 812287
> ```
> 
> ```
> requesting blocks [000070012df2, 00020483df0c]
> ...
> Received block 000070012df2 at 812302
> ```
> 
> ```
> requesting blocks [00015172cbf8, 0000c9e415c7, 00006ceecb0a, 0002baf49e10, 0000a20f4c34, 000075cd15df, 0000b3c51cd4, 000009e25404, 0001b45fb11f, 00003d2f716e, 000140bd9eec, 000039a878fc, 00030153531d, 0001f207bed3, 0001c80bc101, 00001a53af65, 00028df7fc99, 0000aac70c82, 000291b12c14, 00019eb1b822, 00003f169b73, 000078cc209f, 0001442fd879, 0000e9d60bae, 0002738cea28]
> ...
> Received block 00015172cbf8 at 812231
> ```

For whatever reason we are not successfully calculating a set of missing block hashes to go request from peers. It is still not obvious _why_ this is happening.

**Comment by antiochp** [comment]
We determine the set of missing block hashes in `body_sync()` but there is some really obfuscated code in there...
We call `check_txhashset_needed()` and this populates missing `hashes`.

**Comment by antiochp** [comment]
@tromp Can you clear your logs out, restart the node, let it run for a couple minutes and then post your logs here?
It would be useful to see exactly what the node is doing when it first enters block sync, and what blocks it initially tries to request.

**Comment by antiochp** [comment]
This is in the logs -

```
block_sync: 812160/815581 requesting blocks [0001249518c3, 00026ac8fee8, 0002df6e09ee, 0002738cea28] from 8 peers
...
Received block 0001249518c3 at 812161 from 78.47.206.120:3414 [in/out/kern: 10/9/5] going to process.
is_orphan: 0001249518c3
```

**Comment by antiochp** [comment]
I have a sneaking suspicion this is not some weird edge case and that we have actually broken IBD recently (probably one of the recent "refactoring" PRs).
Running a full sync locally to confirm.

**Comment by tromp** [comment]
New log at https://tromp.github.io/grin-server.log.20200808

**Comment by antiochp** [comment]
> New log at https://tromp.github.io/grin-server.log.20200808

Ok yeah I think that probably confirms my suspicions... It requests (correctly) the first missing block at height 812161 but immediately identifies it as an orphan when it receives it.

Working on fixing this.

**Comment by tromp** [comment]
Hard to believe that I'm the first to complain about a failing week+ sync...

**Comment by tromp** [comment]
A sync from scratch should be one of the prime tests to run for any nontrivial PR...

**Comment by antiochp** [comment]
Yeah I was sure I had tested this, but apparently not.

**Comment by antiochp** [comment]
I have a fix. Just confirming I can reproduce the issue locally first (fast sync of all those headers is _slow_).
