### ISSUE TITLE
Spent outputs don't appear to be removed from sumtrees

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#342]
There appears to be something odd going on with removing spent utxos from the sumtree (I'm assuming this should be working), which means that client wallets are actually keeping better track of which outputs can actually spent. Wallet recovery isn't working because of an apparent issue here.. it may be something I'm missing, but I'll present the evidence:

I successfully sent 350 from this wallet to another receiver, source wallet starting out looking like this:
```
Wallet Summary Info - Block Height: 5344
--------------------------
 Total                            | 5350.000000000
 Awaiting Confirmation            | 0.000000000
 Confirmed but Still Locked       | 0.000000000
 Currently Spendable              | 5350.000000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000
```
I've lost the what the wallet state looked like just after the send, but it appeared as expected, with 5000 total, and freed up after a few confirmations.

After deleting and restoring the wallet, the result is as follows:
```
Wallet Summary Info - Block Height: 5344
--------------------------
 Total                            | 10350.000000000
 Awaiting Confirmation            | 0.000000000
 Confirmed but Still Locked       | 0.000000000
 Currently Spendable              | 10350.000000000
 ---------                        | ---------
 (Locked by previous transaction) | 0.000000000
```

So what appears to have happened is the the wallet locked 5350 worth of outputs, which should spend 5350 worth of unspent coinbase outputs, send 350, and create a 5000 change transaction. This appears to have happened, however all 10350 worth of transactions appear upon recovery, which would indicate that transactions that were supposedly spent aren't being removed from the sum tree, and the wallet is keeping track of which outputs have been spent locally.

The function that returns the UTXOs for each block during wallet recovery includes a filter on unspent UTXOs:

https://github.com/mimblewimble/grin/blob/315f224cd903984d61909590fd63b4a6008042af/api/src/handlers.rs#L121
```
	fn utxos_at_height(&self, block_height: u64) -> BlockOutputs {
		let header = self.chain
			.clone()
			.get_header_by_height(block_height)
			.unwrap();
		let block = self.chain.clone().get_block(&header.hash()).unwrap();
		let outputs = block
			.outputs
			.iter()
			.filter(|c|self.chain.is_unspent(&c.commit).unwrap())
			.map(|k|OutputSwitch::from_output(k, &header))
			.collect();
		BlockOutputs {
			header: BlockHeaderInfo::from_header(&header),
			outputs: outputs,
		}
	}
```
Which goes here:
https://github.com/mimblewimble/grin/blob/315f224cd903984d61909590fd63b4a6008042af/chain/src/chain.rs#L243
```
	pub fn is_unspent(&self, output_ref: &Commitment) -> Result<bool, Error> {
		let sumtrees = self.sumtrees.read().unwrap();
		sumtrees.is_unspent(output_ref)
	}
```

And to check whether it's in the sumtree here:
https://github.com/mimblewimble/grin/blob/315f224cd903984d61909590fd63b4a6008042af/chain/src/sumtree.rs#L93
```
	pub fn is_unspent(&self, commit: &Commitment) -> Result<bool, Error> {
		let rpos = self.commit_index.get_output_pos(commit);
		match rpos {
			Ok(pos) => Ok(self.output_pmmr_h.backend.get(pos).is_some()),
			Err(grin_store::Error::NotFoundErr) => Ok(false),
			Err(e) => Err(Error::StoreErr(e, "sumtree unspent check".to_owned())),
		}
	}
```

This suggests that spent commitments aren't being properly removed from the sumtree. I'll try and reproduce on a smaller, local chain and see if I get consistent results.

**Comment by yeastplume** [comment]
I've done this on a new local chain, and everything (including the wallet restore command) works as expected. Those outputs having the issues here are from the first mined transactions after a failed transaction, so I'm wondering if something else has corrupted their state on the testnet chain.

**Comment by yeastplume** [comment]
Getting a lot of these when trying to use those 'not really unspent' outputs pulled from the chain:
```
Nov 20 12:36:45.855 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:36:46.041 INFO Rejected block bbf48fb2 at 5296: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:36:50.020 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:36:51.390 INFO Client 165.227.63.166:13414 connection lost: Timeout
Nov 20 12:36:55.874 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:36:56.057 INFO Rejected block bbf48fb2 at 5296: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:36:56.080 INFO Client 89.73.139.160:13414 connection lost: Timeout
Nov 20 12:36:59.985 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:37:00.173 INFO Rejected block bbf48fb2 at 5296: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:37:05.860 INFO Rejected block bbf48fb2 at 5296: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:37:06.051 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:37:10.365 INFO Rejected block bbf48fb2 at 5296: StoreErr(NotFoundErr, "wrapped")
Nov 20 12:37:10.370 INFO Received 1 block headers
Nov 20 12:37:10.374 INFO Updated block header head to bdc5a1dd at 5432.
Nov 20 12:37:10.374 INFO Added 1 headers to the header chain.
Nov 20 12:37:10.552 INFO Rejected block c753e050 at 5295: StoreErr(NotFoundErr, "wrapped")
```

**Comment by yeastplume** [comment]
Okay, I may have somehow bcashed myself off from the main chain.. at any rate this looks like it was a sync issue.. I removed and resynched all of my nodes, and transactions pulled from the chain via the wallet restore command seem to work.. closing.

**Comment by andybellenie** [comment]
I'm not sure this is a sync issue as I just had what appears to be the same problem restoring onto a freshly synced node
