### ISSUE TITLE
Consider: rename floonet -> testnet

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3429]
`floonet` is a great name.

Its just not _necessarily_ a great name for `testnet` and it would amazing if we could repurpose the name for something more related to communication channels.

Right now `floonet` and `testnet` are synonymous and effectively interchangeable (and confusing).

Its going to take a little bit of investigation to understand what the fallout and impact would be around a name change like this in terms of how invasive it would be to the codebase, config files etc.

**Comment by quentinlesceller** [comment]
I agree with that. I think it'd be clearer to have `testnet` everywhere. So :+1: and yeah let's investigate if this is going to break anything.
Considering it's also testnet, I think I'd probably be okay to not have the extra complexity of some kind of "migration helper" in the code.
