### ISSUE TITLE
Clarify wallet api commands

### ISSUE THREAD

**Issue by andybellenie** [mimblewimble/grin#343]
I've done some work in #337 but there's still ambiguity. Based on my current PR I have:

`wallet receive` depreciated
`wallet listen` operates in listening mode
`wallet send` creates a partial transaction and writes to stdout (unchanged)
`wallet send -d` creates a partial transaction and transmits to a potential recipient (unchanged)
`wallet file` takes a partial transaction and completes it
`wallet request` reserved for transactions originating at the recipient

The confusion here is that `send` doesn't necessarily send anything and `file` doesn't imply directionality

Perhaps there was no need for a new 'file' command and 'receive' should be kept as it originally was for file-based transaction competion. What do people think?

**Comment by antiochp** [comment]
I actually like `receive` for reading in from a file - think it fits with what is happening pretty nicely.

**Comment by andybellenie** [comment]
PR updated

**Comment by ignopeverell** [comment]
Fixed in #337
