### ISSUE TITLE
Problem with cargo build and croaring-sys-mw v0.4.5

### ISSUE THREAD

**Issue by Nico-GS** [mimblewimble/grin#3441]
**Describe the bug**

When I run the build I end up with this error:

error: failed to run custom build command for `croaring-sys-mw v0.4.5`

**To Reproduce**
1. Run 'sudo cargo build --release'

**Relevant Information**

`   Compiling cargo-lock v4.0.1
   Compiling log4rs v0.12.0
   Compiling jsonrpc-core v10.1.0
   Compiling mio-uds v0.6.8
   Compiling rustls-native-certs v0.3.0
   Compiling built v0.4.3
   Compiling cursive v0.15.0
   Compiling grin_util v4.1.0-alpha.1 (/home/lorn/Téléchargements/grin/util)
warning: use of deprecated item 'zip::ZipWriter::<W>::start_file_from_path': by stripping `..`s from the path, the meaning of paths can change. Use `start_file` instead.
  --> util/src/zip.rs:40:21
   |
40 |             writer.get_mut().start_file_from_path(x, options)?;
   |                              ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'zip::read::ZipFile::<'a>::sanitized_name': by stripping `..`s from the path, the meaning of paths can change.
                You must use a sanitization strategy that's appropriate for your input
  --> util/src/zip.rs:60:31
   |
60 |                 let path = dest.join(file.sanitized_name());
   |                                           ^^^^^^^^^^^^^^

   Compiling easy-jsonrpc-mw v0.5.4
   Compiling tokio v0.2.22
   Compiling grin_keychain v4.1.0-alpha.1 (/home/lorn/Téléchargements/grin/keychain)
warning: 2 warnings emitted

   Compiling grin v4.1.0-alpha.1 (/home/lorn/Téléchargements/grin)
   Compiling tokio-util v0.3.1
   Compiling tokio-io-timeout v0.4.0
   Compiling tokio-rustls v0.13.1
   Compiling tokio-util v0.2.0
   Compiling h2 v0.2.6
   Compiling hyper v0.13.7
   Compiling croaring-sys-mw v0.4.5
   Compiling hyper-rustls v0.20.0
   Compiling hyper-timeout v0.3.1
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

error: failed to run custom build command for `croaring-sys-mw v0.4.5`

Caused by:
  process didn't exit successfully: `/home/lorn/Téléchargements/grin/target/release/build/croaring-sys-mw-8037ed37f582a249/build-script-build` (exit code: 101)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-std=c11" "-O3" "-DDISABLEAVX=1" "-o" "/home/lorn/T\xc3\xa9l\xc3\xa9chargements/grin/target/release/build/croaring-sys-mw-3123aa789ca0c9ae/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
  exit code: 0
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "crs" "/home/lorn/T\xc3\xa9l\xc3\xa9chargements/grin/target/release/build/croaring-sys-mw-3123aa789ca0c9ae/out/libroaring.a" "/home/lorn/T\xc3\xa9l\xc3\xa9chargements/grin/target/release/build/croaring-sys-mw-3123aa789ca0c9ae/out/CRoaring/roaring.o"
  exit code: 0
  cargo:rustc-link-lib=static=roaring
  cargo:rustc-link-search=native=/home/lorn/Téléchargements/grin/target/release/build/croaring-sys-mw-3123aa789ca0c9ae/out
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.52.0/src/lib.rs:1895:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro XFCE
 - Version 20.1

Thanks

**Comment by antiochp** [comment]
This looks to be `clang` related - 

```
thread 'main' panicked at 'Unable to find libclang: 
"couldn't find any valid shared libraries matching: 
['libclang.so', 'libclang-.so', 'libclang.so.']
```

We specify the system dependencies here - 
https://github.com/mimblewimble/grin/blob/master/doc/build.md

**Comment by antiochp** [comment]
:+1:
That's just a deprecation warning and can be safely ignored (not an error).
