### ISSUE TITLE
MDB_MAP_FULL: Environment mapsize limit reached (4.0.1 -> 4.1.0)

### ISSUE THREAD

**Issue by shrikus** [mimblewimble/grin#3448]
Tried to upgrade node from 4.0.1 to 4.1.0 (linux release binaries) and got error:

```
20200919 15:28:35.797 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: LmdbErr(Error::Code(-30792, 'MDB_MAP_FULL: Environment mapsize limit reached'))

Store Error: LmdbErr(Error::Code(-30792, 'MDB_MAP_FULL: Environment mapsize limit reached')), reason: LMDB error: MDB_MAP_FULL: Environment mapsize limit reached  })': src/bin/cmd/server.rs:78   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   4: core::option::expect_none_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1269
   5: grin::cmd::server::start_server_tui
   6: grin::cmd::server::server_command
   7: grin::real_main
   8: grin::main
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51
  11: main
  12: __libc_start_main
  13: _start
```

it can be same as #3099 but there is still no solution.

**Comment by oneevil** [comment]
+1 I have the same trouble

**Comment by antiochp** [comment]
Is this only happening on `4.1.0` or does this continue to happen if you revert to `4.0.1`.
We have some logic in there around resizing the lmdb database files but I don't think anything changed in `4.1.0`.

Let me dig around a bit - maybe there is a code path that uses lmdb without checking if it need to be resized somewhere.

**Comment by antiochp** [comment]
Just re-acquainting myself with #3099 and yes it does look like this is (still) the likely culprit. :+1:

**Comment by oneevil** [comment]
when i go back to 4.0.1 - everything works

**Comment by antiochp** [comment]
> when i go back to 4.0.1 - everything works

Ok that makes sense and indicates this is indeed related to the block migration during init. We migrate all recent blocks in the db and if we require a db resize to handle this then we will potentially see the error above.

**Comment by antiochp** [comment]
@shrikus @oneevil 
We have a potential fix in #3449 if you can build from source and interested in helping test this out?

**Comment by antiochp** [comment]
@shrikus @oneevil 
Q) Are you running a full archival node (`archive_mode = true`)?

**Comment by oneevil** [comment]
archive_mode = true
unfortunately I can't check it anymore, I resynchronized from 0

**Comment by antiochp** [comment]
> archive_mode = true

Thanks for this. This is useful info. :+1:
