### ISSUE TITLE
More robust fee mechanism

### ISSUE THREAD

**Issue by michaendr** [mimblewimble/grin#3459]
Based on a quick read, it seems to me that Grin rewards the miner by simply adding the fees.
In the literature [0] it has been suggested that this is suboptimal from an incentive point of view, as it results in more complex bidding strategies and a bad user experience.

I suspect it's non-trivial to adapt the suggested changes for Bitcoin to Grin, but haven't so far seen it mentioned anywhere, so thought I'd put it on the radar.

[0] https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3318327

**Comment by lehnberg** [comment]
Hi, thanks for making the suggestion. :+1:  

Grin's fee structure is actually actively being revised at the moment, see details in this RFC that is in Final Comment Period: https://github.com/mimblewimble/grin-rfcs/pull/63

And there's also this tracking issue: https://github.com/mimblewimble/grin/issues/3369

If you have concrete suggestions on how the current RFC proposal could be improved, please [raise them in the RFC pull request](https://github.com/mimblewimble/grin-rfcs/pull/63) **ASAP** as it is about to be finalised soon and development will commence to target v5.0.0. 

In the meanwhile, I'm closing this ticket as a duplicate.
