### ISSUE TITLE
Lower COINBASE_MATURITY on testnet

### ISSUE THREAD

**Issue by Sjors** [mimblewimble/grin#347]
I think 3-10 (instead of [1000](https://github.com/mimblewimble/grin/blob/milestone/testnet1/core/src/consensus.rs#L46)) should be enough to test the behavior, while not having to wait forever to get started spending coins.

**Comment by antiochp** [comment]
Right now the default confirmations for spending from the wallet is `1` (for regular non-coinbase outputs).
This should probably be increased to `6` to be more realistic.
The coinbase maturity should be at _least_ this, even in testnet.

Maybe splitting the difference and using `100` for coinbase outputs might make sense in testnet (then you only have to wait for a couple of hours for spendable coins)?

**Comment by ignopeverell** [comment]
The point of testnet is to test in preparation to mainnet. We're all happy to send you non-coinbase test coins if you want some.
