### ISSUE TITLE
Mining "stops" after a while

### ISSUE THREAD

**Issue by Fjodor42** [mimblewimble/grin#348]
I'm a bit unsure if this is coincidence and, if not, what to look for. Anyway:

It would seem a bit as if, after a while, my running miner ceases to find any new graphs, identifiable by the fact that no new funds seem to be added to the corresponding wallet (or, at least, the frequency of finding graphs fall to a level that resembles a situation where no new graphs are found).

Restarting the miner seems to rectify the situation, but since the "stop" or "slow-down" seems to happen after such a while that I only notice several hours later (this morning, for instance), I am unsure of what to look for in the terminal output, and would be grateful if someone has an idea as to what could cause this and, hence, what to look for.

**Comment by sesam** [comment]
@Fjodor42 please look in grin.log around the time of the last new output (fund) is added. Or make a .zip of grin.log and add here.

**Comment by ignopeverell** [comment]
We're trying to track most sync issues under doc/usage.md. Thanks for the testing!
