### ISSUE TITLE
Advanced example - node 1 error

### ISSUE THREAD

**Issue by PanosChtz** [mimblewimble/grin#349]
After following [https://github.com/mimblewimble/grin/blob/master/doc/local_net.md](url)

```
~/grin/node1$ grin wallet -p "password" -a "http://127.0.0.1:10001" -r 15000 receive
error: Found argument '-r' which wasn't expected, or isn't valid in this context

USAGE:
    grin wallet --api_server_address <api_server_address> --pass <pass>

For more information try --help
```

Also in grin wallet --help there's no -r flag or option...

**Comment by dewdeded** [comment]
Try: grin wallet -p password -a http://127.0.0.1:10001 listen --port 15000

**Comment by antiochp** [comment]
Yeah - used to be `receive`, but renamed to `listen`.
