### ISSUE TITLE
v5.0.0 Release Notes

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3506]
* Release: https://github.com/mimblewimble/grin/releases/tag/v5.0.0

### Hardfork 4

* HardFork4 (#3478)

### DAA

RFC: https://github.com/mimblewimble/grin-rfcs/blob/master/text/0018-fix-daa.md

* fixDAA; implement wtema (#3477)
* make min_wtema difficulty chain type dependent (#3502)
* fix calls to next_diff() in tests to use next height correctly (#3501)

### Fees

RFC: https://github.com/mimblewimble/grin-rfcs/blob/master/text/0017-fix-fees.md

* Fixfees (#3481)

### PIBD

RFC [WIP]: https://github.com/jaspervdm/grin-rfcs/blob/pibd_messages/text/0000-pibd-messages.md 

* enable PIBD_HIST capability by default (#3500)
* PIBD segment p2p messages (#3496)
* More efficient serialization for bitmap segments (#3492)
* add segmenter for generating segments from txhashset with consistent rewind (#3482)
* PMMR segment creation and validation (#3453)

### Build/CI

* bump 5.0.0-beta.2 after fixing windows release script (#3508)
* refreshenv as part of windows release script (#3507)
* Bump version to 5.0.0-beta.1 (#3505)
* we have no patch file and nothing to patch (#3499)
* call refreshenv before running tests on windows (#3498)
* CI: no directories in checksum file (#3460)

### Refactor/Cleanup/Code Quality

* use extend_from_slice when appending multiple hashes to hash file (#3497)
* Disable merkle proofs for v2 get_block (#3487)
* default capabilities cleanup (#3484)
* on_block_accepted logging and webhooks all the time (#3486)
* Flexible peer filtering (#3458)
* fix v2 conversion to ensure we provide blocks in correct format (#3465)
* Rename Floonet to Testnet (#3431)
* Define get_data_from_file function on ReadablePMMR trait (#3464)
* migrate blocks in batches (rework db iterator impl) (#3450)
* Cleanup usage of legacy bitmaps. (#3455)
* use choose_multiple to clean get_peers() up (#3457)
* cleanup validate() no need to return kernel sums (#3456)
* Refactor PMMR read methods into trait (#3454)
* Refactor p2p reader (#3433)
* add test coverage around existing behavior for exists() and iter() (#3452)
* refactor get_ser to use get_with internally (#3451)

### Misc.
 
* Disable API v1 (#3503)
* fix, no more FULL_NODE (#3504)
* reorg cache fix (#3495)
* add peer capabilities to tui peers screen (#3490)
* cleanup mining stats (#3439)
* prefer outbound peers when syncing (consistently) (#3527)
* Update Client to v2 API (#3524)
* Update grin-secp256k1zkp to 0.7.10 (#3520)
* Update tokio, hyper versions (#3514)
* Block migration flag (#3513)

**Comment by chenrui333** [comment]
👋  looks like grin 5.0.0 [failed to build](https://github.com/Homebrew/homebrew-core/pull/68336) on big_sur.

```
  --- stderr
  CRoaring/roaring.h:39:10: fatal error: 'stdlib.h' file not found
  CRoaring/roaring.h:39:10: fatal error: 'stdlib.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/croaring-sys-mw-0.4.5/build.rs:29:10
```
