### ISSUE TITLE
Block migration check during node init unacceptably slow for full archive node

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3511]
Block migration (v2 -> v3) results in really slow startup for full archive nodes.
This is due to our naive handling of "do we need to migrate this block, or not" for _every_ block in the db (and this is a lot of blocks for a full archive node). We iterate over the full set of blocks in the db and check each one individually. This happens every time the node starts/restarts.

Thanks to @bladedoyle for investigating and discovering this - 

```
20201204 17:22:06.772 INFO grin - This is Grin version 5.0.0-beta.2 (git v5.0.0-beta.2), built for x86_64-unknown-linux-gnu by rustc 1.48.0 (7eac88abb 2020-11-16).
20201204 17:22:06.772 DEBUG grin - Built with profile "debug", features "".
20201204 17:22:06.772 INFO grin - Chain: Mainnet
20201204 17:22:06.773 INFO grin - Accept Fee Base: 1000000
20201204 17:22:06.773 INFO grin - Future Time Limit: 300
20201204 17:22:06.773 INFO grin - Feature: NRD kernel enabled: false
20201204 17:22:06.773 WARN grin::cmd::server - Starting GRIN in UI mode...
20201204 17:22:06.775 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20201204 17:22:06.775 DEBUG grin_store::lmdb - DB Mapsize for /home/grin/.grin/main/chain_data/lmdb is 549755813888
20201204 17:54:37.242 DEBUG grin_chain::chain - migrate_db_v2_v3: 0 blocks to migrate
```

Related #3450

In #3450 we reworked the migration process to migrate blocks in smaller batches. But we still check _every_ block, every time.

Proposed solution: Introduce a simple flag in the db that we set on successful migration of all blocks. Then we can simply check this flag and skip the entire migration process.

The initial migration will still be slow but this would only occur once on first migration.

To investigate: Even with a full archive node worth of blocks, the simple iteration over all blocks in the db should still not take 30 minutes (at least intuitively). Even with deserialization of all that data. Is there contention here as well? Or something else going on?

**Comment by bladedoyle** [comment]
Tested, Verified, Looks good, thanks @antiochp
