### ISSUE TITLE
Testnet block 4689 (f697a877) fails with AlreadySpent on sync

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#352]
This happened twice in a row so I'm assuming it'd keep happening. After a restart the same block is accepted without any issue.

**Comment by CodeSlip** [comment]
That worked, moved on to 4705+

**Comment by ignopeverell** [comment]
Had it occur at 10088 as well. Will instrument a node and try to reproduce.

**Comment by ignopeverell** [comment]
Those were actual double spends that weren't detected due to a remove log saving bug. Fixed in 2c6c8ed.

**Comment by antiochp** [comment]
💃
