### ISSUE TITLE
Client use v1 API 

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#3522]
The current `grin client` uses the V1 API which is now removed.
Convert it to v2. https://github.com/mimblewimble/grin/blob/v5.0.0-beta.2/src/bin/cmd/client.rs#L159v

**Comment by saurabhhere** [comment]
Hi @quentinlesceller, do I have to make any changes other than converting v1 to v2 on the line you mentioned.
Thanks

**Comment by quentinlesceller** [comment]
Hi @saurabhhere :). The v2 API uses JSON-RPC instead of the classic REST. This PR should be similar to https://github.com/mimblewimble/grin-wallet/pull/329. The doc of the API is here https://docs.rs/grin_api/4.1.1/grin_api/trait.OwnerRpc.html.

**Comment by saurabhhere** [comment]
Thanks, @quentinlesceller. 
I am not picking this issue so if anyone wants to pick this issue up can freely work on it.

**Comment by quentinlesceller** [comment]
Fixed by https://github.com/mimblewimble/grin/pull/3524
