### ISSUE TITLE
Orphaned blocks aren't reported as received to sync

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#353]
Sync maintains a list of blocks to download. Once peers send them, they're processed and reported as done so they're not requested again. However they often arrive out of order and are orphaned. This isn't a problem because the orphan is usually processed soon after when the right block arrives. But processing as the orphan isn't reported back to sync, so the block will be requested again.

This results in tons of `Unfit` errors, slows down sync and likely increases network traffic quite a bit.

**Comment by sesam** [comment]
Close this? The commit above says to.
