### ISSUE TITLE
grin build failing on big_sur

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3538]
https://github.com/mimblewimble/grin/issues/3506#issuecomment-754791166

https://github.com/Homebrew/homebrew-core/pull/68336

**Comment by chenrui333** [comment]
trying v5.0.1 release now. https://github.com/Homebrew/homebrew-core/pull/68336/commits/8831391c24615cdd9d72dedc562b96db3a241266

**Comment by quentinlesceller** [comment]
Fixed with 5.0.1

**Comment by chenrui333** [comment]
Thanks @quentinlesceller!
