### ISSUE TITLE
restore as unspent

### ISSUE THREAD

**Issue by antonio-fr** [mimblewimble/grin#354]
Even after full resync of the chain, spent outputs are recovered as unspent txs with restore. So they need to be manually deleted in wallet.dat.

**Comment by yeastplume** [comment]
All transactions pulled from the restore are pulled directly from the UTXO set at whatever height the node you're running against is on, so anything that shows up after a restore is unspent as far as the chain state is concerned. There's been a lot of funny business going on chains accidentally forking, so it's possible they were spent on one fork and then show up as unspent on the other. I'd wait until some of the larger sync issues are dealt with, then try this again.

**Comment by antonio-fr** [comment]
Well I did some transfer around block 5600. A single node sync on freshly sync testnet is reporting unspent for what appears as a new output for the other wallet (real unpent). If I try to spend these unspent which were moved, I got an error. So I really feel restore see everything as unspent if we delete the chain history. This is also the case for the old change I got on one wallet. It is like all my outputs are recovered as unspent.

**Comment by yeastplume** [comment]
Noted, but please understand it's not possible to pull a 'spent' output out of an up-to-date UTXO set.. it simply doesn't exist. If you're seeing transactions being restored that were spent, it could only be the result of restoring from a lower height than the current, or from a forked chain. I'm trying to do 2 full restores on 2 different nodes at the moment, and they're both forking off in different ways. I do think this all comes down to sync issues at the moment, and unfortunately the uncertainty around it makes it very difficult to investigate further. We'll have to wait until the sync/fork issues are dealt with and see if this kind of behaviour is still occurring.

**Comment by yeastplume** [comment]
If this was occuring before, it might have been explained by https://github.com/mimblewimble/grin/issues/361, which is now fixed. I'm closing this for now as I think this is dealt with, but please feel free to re-open if you see it again, particularly after the sync issues have been dealt with.
