### ISSUE TITLE
Need support for rewriting grin-server.toml file

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#3540]
The fixfees RFC lowered the accept_fee_base default from 1_000_000 to 500_000, but most nodes
have the 1_000_000 setting in the grin-server.toml configuration file, which would incorrectly override the new 500_000 default.

This resulted in the ugly fight-override fix at https://github.com/mimblewimble/grin/pull/3539

To get rid of that exception code, we would like to be able to rewrite the grin-server.toml file
in order to update obsolete defaults.

**Comment by trevyn** [comment]
For reference, I started working on this over at [trevyn/grin/commits/trevyn-fix-accept-fee-base](https://github.com/trevyn/grin/commits/trevyn-fix-accept-fee-base). I'm not entirely happy with the approach, but I did get it working. I've put this on the back burner and may pick it up again, but until then, I wanted to inform anyone who might find this information to be useful. :)
