### ISSUE TITLE
Check URL availability

### ISSUE THREAD

**Issue by antonio-fr** [mimblewimble/grin#356]
Checking the destination URL availability before doing anything such as make the begninng of the tx would be safer and considerably improve UX.
When performing a send -d "xx", the Grin should check the availability of the endpoint (at least 404 for GET /), before building the tx. If the endpoint is not available, the change of the tx would appear as a new output. This requires manual editing of wallet.dat or delete/restore. The restore doesn't help so much because the #354 issue (still need manual edit).
I'm doing this sanity check manually to see if the endpoint is available, saving recovery effort afterwards. So this could be a good UX improvement to do it automatically in the software. We discuss many time the wallet should perform anything before reaching successfully the destination listener, so this additional check before hand would stick to this expected behavior.

**Comment by ignopeverell** [comment]
I believe this has been fixed by @yeastplume. Feel free to reopen if I'm mistaken.
