### ISSUE TITLE
Panic in `cursive` dependency

### ISSUE THREAD

**Issue by trevyn** [mimblewimble/grin#3595]
Reported at: https://forum.grin.mw/t/failed-to-start-a-new-grin-node/8413

I filed https://github.com/gyscos/cursive/pull/565 (xposted below) and will move this forward when that gets merged and published.

>Hi! We [received a report](https://forum.grin.mw/t/failed-to-start-a-new-grin-node/8413) of a panic in `cursive`:
>
>`thread ‘main’ panicked at ‘attempt to calculate the remainder with a divisor of zero’: /home/cephd/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cursive-0.15.0/src/backends/curses/mod.rs:93`
>
>It looks like it's due to this line:
>
>```rust
>Color::Light(BaseColor::Black) => 8 % max_colors,
>```
>
>It appears that the `max_colors` value is being sourced from `ncurses::COLORS()`, which I can only assume is returning `0` for whatever reason.
>
>Since the rest of the code looks as though it is written to assume at least 8 colors, this PR puts a lower bound of `8` on `max_colors` to prevent this panic.
>
>Also happy to implement a different solution if you prefer!

**Comment by quentinlesceller** [comment]
Nice catch @trevyn !

**Comment by quentinlesceller** [comment]
Looks like it is now merge. Closing.
