### ISSUE TITLE
Locking boot blocks

### ISSUE THREAD

**Issue by mass34** [mimblewimble/grin#360]
Nov 22 00:43:22.057 INFO Starting the Grin server...
Nov 22 00:43:23.042 WARN P2P server started on 0.0.0.0:13414
Nov 22 00:43:23.043 INFO Sync: starting sync
Nov 22 00:43:23.045 INFO Starting rest apis at: 127.0.0.1:13413
Nov 22 00:43:23.050 WARN Grin server started.
Nov 22 00:43:23.053 INFO Starting HTTP API server at 127.0.0.1:13413.
Nov 22 00:43:23.080 DEBG Retrieving seed nodes from http://grin-tech.org/seeds.txt
Nov 22 00:43:23.637 DEBG Retrieved seed addresses: [V4(192.241.168.77:13414), V4(109.74.202.16:13414), V4(174.138.116.153:13414)]
Nov 22 00:43:23.637 DEBG Connecting to seed: 192.241.168.77:13414.
Nov 22 00:43:23.637 DEBG Connecting to seed: 109.74.202.16:13414.
Nov 22 00:43:23.637 DEBG Connecting to seed: 174.138.116.153:13414.
Nov 22 00:43:23.637 DEBG New peer address to connect to: 192.241.168.77:13414.
Nov 22 00:43:23.638 DEBG 0.0.0.0:13414 connecting to 192.241.168.77:13414
Nov 22 00:43:23.638 DEBG New peer address to connect to: 109.74.202.16:13414.
Nov 22 00:43:23.638 DEBG 0.0.0.0:13414 connecting to 109.74.202.16:13414
Nov 22 00:43:23.640 DEBG New peer address to connect to: 174.138.116.153:13414.
Nov 22 00:43:23.640 DEBG 0.0.0.0:13414 connecting to 174.138.116.153:13414
Nov 22 00:43:23.759 DEBG saving peer to store PeerData { addr: V4(109.74.202.16:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Defunct }
Nov 22 00:43:23.821 DEBG handshake connect with nonce - 16697409489810311339, sender - V4(0.0.0.0:13414), receiver - V4(192.241.168.77:13414)
Nov 22 00:43:23.836 DEBG handshake connect with nonce - 4844163783727542794, sender - V4(0.0.0.0:13414), receiver - V4(174.138.116.153:13414)
Nov 22 00:43:24.418 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(192.241.168.77:13414), total_difficulty: Difficulty { num: 28045837 } }
Nov 22 00:43:24.418 DEBG Saving newly connected peer 192.241.168.77:13414.
Nov 22 00:43:24.418 DEBG saving peer to store PeerData { addr: V4(192.241.168.77:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 22 00:43:24.420 DEBG Asking 192.241.168.77:13414 for more peers.
Nov 22 00:43:24.420 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(174.138.116.153:13414), total_difficulty: Difficulty { num: 28881590 } }
Nov 22 00:43:24.420 DEBG Saving newly connected peer 174.138.116.153:13414.
Nov 22 00:43:24.420 DEBG saving peer to store PeerData { addr: V4(174.138.116.153:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 22 00:43:24.422 DEBG Asking 174.138.116.153:13414 for more peers.
Nov 22 00:43:24.620 DEBG Received 167 peer addrs, saving.
Nov 22 00:43:24.626 DEBG Received 128 peer addrs, saving.
Nov 22 00:43:33.033 DEBG monitoring peers (2)
Nov 22 00:43:34.059 DEBG Added 4382 full block hashes to download.
Nov 22 00:43:34.060 INFO Starting sync loop.
Nov 22 00:43:34.060 DEBG Sync: peer 28881590 vs us 28872857
Nov 22 00:43:34.060 DEBG Sync: blocks to download 4382, block downloading 0
Nov 22 00:43:34.060 DEBG Loc heights: [7355, 7353, 7351, 7347, 7339, 7323, 7291, 7227, 7099, 6843, 0]
Nov 22 00:43:34.888 DEBG Asking peer 174.138.116.153:13414 for more block headers, locator: [e4b4cd15, 758fc5a1, df1c72c4, 09042b96, 602a7f1e, 6fb5962d, 7132bb8e, 2a0799b2, b4eb6231, 6b581474, e17ea64f]
Nov 22 00:43:34.888 DEBG Requesting block b5dd7d98 from peer 174.138.116.153:13414.
Nov 22 00:43:34.889 DEBG Requesting block 980cc345 from peer 174.138.116.153:13414.
Nov 22 00:43:34.889 DEBG Requesting block 8bc9c4b6 from peer 192.241.168.77:13414.
Nov 22 00:43:34.889 DEBG Requesting block 032175ec from peer 192.241.168.77:13414.
Nov 22 00:43:34.889 DEBG Requesting block 104bb231 from peer 192.241.168.77:13414.
Nov 22 00:43:34.889 DEBG Requesting block b83ca9cc from peer 192.241.168.77:13414.
Nov 22 00:43:34.889 DEBG Requesting block 32073208 from peer 192.241.168.77:13414.
Nov 22 00:43:34.889 DEBG Requesting block 1ba85a40 from peer 192.241.168.77:13414.
Nov 22 00:43:34.890 DEBG Requested 8 full blocks to download, total left: 4374. Current list: [BlockDownload { hash: b5dd7d98, start_time: Instant { tv_sec: 469531, tv_nsec: 47351322 }, retries: 0 }, BlockDownload { hash: 980cc345, start_time: Instant { tv_sec: 469531, tv_nsec: 47397484 }, retries: 0 }, BlockDownload { hash: 8bc9c4b6, start_time: Instant { tv_sec: 469531, tv_nsec: 47440445 }, retries: 0 }, BlockDownload { hash: 032175ec, start_time: Instant { tv_sec: 469531, tv_nsec: 47479809 }, retries: 0 }, BlockDownload { hash: 104bb231, start_time: Instant { tv_sec: 469531, tv_nsec: 47525749 }, retries: 0 }, BlockDownload { hash: b83ca9cc, start_time: Instant { tv_sec: 469531, tv_nsec: 47575032 }, retries: 0 }, BlockDownload { hash: 32073208, start_time: Instant { tv_sec: 469531, tv_nsec: 47622525 }, retries: 0 }, BlockDownload { hash: 1ba85a40, start_time: Instant { tv_sec: 469531, tv_nsec: 47661927 }, retries: 0 }].
Nov 22 00:43:35.091 INFO Received 0 block headers
Nov 22 00:43:35.091 INFO Added 0 headers to the header chain.
Nov 22 00:43:35.132 DEBG Received block 8bc9c4b6 at 2976 from network, going to process.
Nov 22 00:43:35.132 DEBG Processing block 8bc9c4b6 at 2976 with 0 inputs and 1 outputs.
Nov 22 00:43:35.133 DEBG Block 8bc9c4b6 refused by chain: Orphan
Nov 22 00:43:35.313 DEBG Received block b5dd7d98 at 2974 from network, going to process.
Nov 22 00:43:35.313 DEBG Processing block b5dd7d98 at 2974 with 0 inputs and 1 outputs.
Nov 22 00:43:35.314 DEBG Validating block with cuckoo size 16
Nov 22 00:43:35.320 DEBG Starting new sumtree extension.
Nov 22 00:43:35.525 TRCE Hashing with additional data
Nov 22 00:43:35.531 DEBG Block at 2974 with hash b5dd7d98 is valid, going to save and append.
Nov 22 00:43:35.535 INFO Updated head to b5dd7d98 at 2974.
Nov 22 00:43:35.535 DEBG Committing sumtree extension.
Nov 22 00:43:35.639 DEBG Sumtree extension done.
Nov 22 00:43:35.640 DEBG Processing block 8bc9c4b6 at 2976 with 0 inputs and 1 outputs.
Nov 22 00:43:35.642 DEBG Received block 980cc345 at 2975 from network, going to process.
Nov 22 00:43:35.642 DEBG Processing block 980cc345 at 2975 with 0 inputs and 1 outputs.
Nov 22 00:43:35.643 DEBG Validating block with cuckoo size 16
Nov 22 00:43:35.647 DEBG Starting new sumtree extension.
Nov 22 00:43:35.738 TRCE Hashing with additional data
Nov 22 00:43:35.745 DEBG Block at 2975 with hash 980cc345 is valid, going to save and append.
Nov 22 00:43:35.746 INFO Updated head to 980cc345 at 2975.
Nov 22 00:43:35.746 DEBG Committing sumtree extension.
Nov 22 00:43:35.841 DEBG Sumtree extension done.
Nov 22 00:43:35.842 DEBG Processing block 8bc9c4b6 at 2976 with 0 inputs and 1 outputs.
Nov 22 00:43:35.842 DEBG Validating block with cuckoo size 16
Nov 22 00:43:35.850 DEBG Starting new sumtree extension.
Nov 22 00:43:35.942 TRCE Hashing with additional data
Nov 22 00:43:35.948 DEBG Block at 2976 with hash 8bc9c4b6 is valid, going to save and append.
Nov 22 00:43:35.949 INFO Updated head to 8bc9c4b6 at 2976.
Nov 22 00:43:35.949 DEBG Committing sumtree extension.
Nov 22 00:43:36.053 DEBG Sumtree extension done.
Nov 22 00:43:36.058 DEBG Received block 032175ec at 2977 from network, going to process.
Nov 22 00:43:36.058 DEBG Processing block 032175ec at 2977 with 1 inputs and 3 outputs.
Nov 22 00:43:36.058 DEBG Validating block with cuckoo size 16
Nov 22 00:43:36.063 DEBG Starting new sumtree extension.
Nov 22 00:43:36.322 TRCE Hashing with additional data
Nov 22 00:43:36.326 TRCE Hashing with additional data
Nov 22 00:43:36.327 TRCE Hashing with additional data
Nov 22 00:43:36.338 DEBG Block at 2977 with hash 032175ec is valid, going to save and append.
Nov 22 00:43:36.340 INFO Updated head to 032175ec at 2977.
Nov 22 00:43:36.340 DEBG Committing sumtree extension.
Nov 22 00:43:36.456 DEBG Sumtree extension done.
Nov 22 00:43:36.460 DEBG Received block 104bb231 at 2978 from network, going to process.
Nov 22 00:43:36.460 DEBG Processing block 104bb231 at 2978 with 0 inputs and 1 outputs.
Nov 22 00:43:36.461 DEBG Validating block with cuckoo size 16
Nov 22 00:43:36.466 DEBG Starting new sumtree extension.
Nov 22 00:43:36.556 TRCE Hashing with additional data
Nov 22 00:43:36.562 DEBG Block at 2978 with hash 104bb231 is valid, going to save and append.
Nov 22 00:43:36.564 INFO Updated head to 104bb231 at 2978.
Nov 22 00:43:36.564 DEBG Committing sumtree extension.
Nov 22 00:43:36.667 DEBG Sumtree extension done.
Nov 22 00:43:36.669 DEBG Received block b83ca9cc at 2979 from network, going to process.
Nov 22 00:43:36.669 DEBG Processing block b83ca9cc at 2979 with 0 inputs and 1 outputs.
Nov 22 00:43:36.670 DEBG Validating block with cuckoo size 16
Nov 22 00:43:36.675 DEBG Starting new sumtree extension.
Nov 22 00:43:36.766 TRCE Hashing with additional data
Nov 22 00:43:36.774 DEBG Block at 2979 with hash b83ca9cc is valid, going to save and append.
Nov 22 00:43:36.775 INFO Updated head to b83ca9cc at 2979.
Nov 22 00:43:36.775 DEBG Committing sumtree extension.
Nov 22 00:43:36.876 DEBG Sumtree extension done.
Nov 22 00:43:36.879 DEBG Received block 32073208 at 2980 from network, going to process.
Nov 22 00:43:36.879 DEBG Processing block 32073208 at 2980 with 0 inputs and 1 outputs.
Nov 22 00:43:36.880 DEBG Validating block with cuckoo size 16
Nov 22 00:43:36.885 DEBG Starting new sumtree extension.
Nov 22 00:43:36.889 DEBG Sync: peer 28881590 vs us 28872857
Nov 22 00:43:36.889 DEBG Sync: blocks to download 4374, block downloading 2
Nov 22 00:43:36.889 DEBG Loc heights: [7355, 7353, 7351, 7347, 7339, 7323, 7291, 7227, 7099, 6843, 0]
Nov 22 00:43:36.975 TRCE Hashing with additional data
Nov 22 00:43:36.981 DEBG Block at 2980 with hash 32073208 is valid, going to save and append.
Nov 22 00:43:36.982 INFO Updated head to 32073208 at 2980.
Nov 22 00:43:36.982 DEBG Committing sumtree extension.
Nov 22 00:43:37.121 DEBG Sumtree extension done.
Nov 22 00:43:37.123 DEBG Received block 1ba85a40 at 2981 from network, going to process.
Nov 22 00:43:37.123 DEBG Processing block 1ba85a40 at 2981 with 0 inputs and 1 outputs.
Nov 22 00:43:37.123 DEBG Validating block with cuckoo size 16
Nov 22 00:43:37.129 DEBG Starting new sumtree extension.
Nov 22 00:43:37.222 TRCE Hashing with additional data
Nov 22 00:43:37.229 DEBG Block at 2981 with hash 1ba85a40 is valid, going to save and append.
Nov 22 00:43:37.230 INFO Updated head to 1ba85a40 at 2981.
Nov 22 00:43:37.230 DEBG Committing sumtree extension.
Nov 22 00:43:37.330 DEBG Sumtree extension done.
Nov 22 00:43:37.754 DEBG Asking peer 174.138.116.153:13414 for more block headers, locator: [e4b4cd15, 758fc5a1, df1c72c4, 09042b96, 602a7f1e, 6fb5962d, 7132bb8e, 2a0799b2, b4eb6231, 6b581474, e17ea64f]
Nov 22 00:43:37.754 DEBG Requesting block 04bcf28f from peer 192.241.168.77:13414.
Nov 22 00:43:37.754 DEBG Requesting block 922de00f from peer 192.241.168.77:13414.
Nov 22 00:43:37.754 DEBG Requesting block 29cb22e4 from peer 174.138.116.153:13414.
Nov 22 00:43:37.755 DEBG Requesting block cc87bcf5 from peer 192.241.168.77:13414.
Nov 22 00:43:37.755 DEBG Requesting block c796e07b from peer 192.241.168.77:13414.
Nov 22 00:43:37.755 DEBG Requesting block f1634a14 from peer 174.138.116.153:13414.
Nov 22 00:43:37.755 DEBG Requesting block fae41490 from peer 192.241.168.77:13414.
Nov 22 00:43:37.755 DEBG Requesting block 81ef2dd3 from peer 192.241.168.77:13414.
Nov 22 00:43:37.755 DEBG Requested 8 full blocks to download, total left: 4366. Current list: [BlockDownload { hash: 04bcf28f, start_time: Instant { tv_sec: 469533, tv_nsec: 912982174 }, retries: 0 }, BlockDownload { hash: 922de00f, start_time: Instant { tv_sec: 469533, tv_nsec: 913025953 }, retries: 0 }, BlockDownload { hash: 29cb22e4, start_time: Instant { tv_sec: 469533, tv_nsec: 913070576 }, retries: 0 }, BlockDownload { hash: cc87bcf5, start_time: Instant { tv_sec: 469533, tv_nsec: 913111615 }, retries: 0 }, BlockDownload { hash: c796e07b, start_time: Instant { tv_sec: 469533, tv_nsec: 913152794 }, retries: 0 }, BlockDownload { hash: f1634a14, start_time: Instant { tv_sec: 469533, tv_nsec: 913194160 }, retries: 0 }, BlockDownload { hash: fae41490, start_time: Instant { tv_sec: 469533, tv_nsec: 913237398 }, retries: 0 }, BlockDownload { hash: 81ef2dd3, start_time: Instant { tv_sec: 469533, tv_nsec: 913278435 }, retries: 0 }].
Nov 22 00:43:37.958 INFO Received 0 block headers
Nov 22 00:43:37.958 INFO Added 0 headers to the header chain.
Nov 22 00:43:37.983 DEBG Received block 04bcf28f at 2982 from network, going to process.
Nov 22 00:43:37.984 DEBG Processing block 04bcf28f at 2982 with 0 inputs and 1 outputs.
Nov 22 00:43:37.984 DEBG Validating block with cuckoo size 16
Nov 22 00:43:37.989 DEBG Starting new sumtree extension.
Nov 22 00:43:38.079 TRCE Hashing with additional data
Nov 22 00:43:38.085 DEBG Block at 2982 with hash 04bcf28f is valid, going to save and append.
Nov 22 00:43:38.086 INFO Updated head to 04bcf28f at 2982.
Nov 22 00:43:38.086 DEBG Committing sumtree extension.
Nov 22 00:43:38.192 DEBG Sumtree extension done.
Nov 22 00:43:38.195 DEBG Received block 922de00f at 2983 from network, going to process.
Nov 22 00:43:38.195 DEBG Processing block 922de00f at 2983 with 0 inputs and 1 outputs.
Nov 22 00:43:38.196 DEBG Validating block with cuckoo size 16
Nov 22 00:43:38.203 DEBG Starting new sumtree extension.
Nov 22 00:43:38.292 TRCE Hashing with additional data
Nov 22 00:43:38.299 DEBG Block at 2983 with hash 922de00f is valid, going to save and append.
Nov 22 00:43:38.300 INFO Updated head to 922de00f at 2983.
Nov 22 00:43:38.300 DEBG Committing sumtree extension.
Nov 22 00:43:38.401 DEBG Sumtree extension done.
Nov 22 00:43:38.405 DEBG Received block cc87bcf5 at 2985 from network, going to process.
Nov 22 00:43:38.406 DEBG Processing block cc87bcf5 at 2985 with 0 inputs and 1 outputs.
Nov 22 00:43:38.406 DEBG Block cc87bcf5 refused by chain: Orphan
Nov 22 00:43:38.409 DEBG Received block c796e07b at 2986 from network, going to process.
Nov 22 00:43:38.409 DEBG Processing block c796e07b at 2986 with 0 inputs and 1 outputs.
Nov 22 00:43:38.410 DEBG Block c796e07b refused by chain: Orphan
Nov 22 00:43:38.413 DEBG Received block 29cb22e4 at 2984 from network, going to process.
Nov 22 00:43:38.413 DEBG Processing block 29cb22e4 at 2984 with 0 inputs and 1 outputs.
Nov 22 00:43:38.414 DEBG Validating block with cuckoo size 16
Nov 22 00:43:38.420 DEBG Starting new sumtree extension.
Nov 22 00:43:38.509 TRCE Hashing with additional data
Nov 22 00:43:38.515 DEBG Block at 2984 with hash 29cb22e4 is valid, going to save and append.
Nov 22 00:43:38.516 INFO Updated head to 29cb22e4 at 2984.
Nov 22 00:43:38.516 DEBG Committing sumtree extension.
Nov 22 00:43:38.612 DEBG Sumtree extension done.
Nov 22 00:43:38.613 DEBG Processing block cc87bcf5 at 2985 with 0 inputs and 1 outputs.
Nov 22 00:43:38.613 DEBG Validating block with cuckoo size 16
Nov 22 00:43:38.621 DEBG Starting new sumtree extension.
Nov 22 00:43:38.711 TRCE Hashing with additional data
Nov 22 00:43:38.718 DEBG Block at 2985 with hash cc87bcf5 is valid, going to save and append.
Nov 22 00:43:38.719 INFO Updated head to cc87bcf5 at 2985.
Nov 22 00:43:38.719 DEBG Committing sumtree extension.
Nov 22 00:43:38.823 DEBG Sumtree extension done.
Nov 22 00:43:38.824 DEBG Processing block c796e07b at 2986 with 0 inputs and 1 outputs.
Nov 22 00:43:38.824 DEBG Validating block with cuckoo size 16
Nov 22 00:43:38.831 DEBG Starting new sumtree extension.
Nov 22 00:43:38.925 TRCE Hashing with additional data
Nov 22 00:43:38.933 DEBG Block at 2986 with hash c796e07b is valid, going to save and append.
Nov 22 00:43:38.935 INFO Updated head to c796e07b at 2986.
Nov 22 00:43:38.935 DEBG Committing sumtree extension.
Nov 22 00:43:39.042 DEBG Sumtree extension done.
Nov 22 00:43:39.044 DEBG Received block f1634a14 at 2987 from network, going to process.
Nov 22 00:43:39.044 DEBG Processing block f1634a14 at 2987 with 0 inputs and 1 outputs.
Nov 22 00:43:39.045 DEBG Validating block with cuckoo size 16
Nov 22 00:43:39.049 DEBG Starting new sumtree extension.
Nov 22 00:43:39.138 TRCE Hashing with additional data
Nov 22 00:43:39.146 DEBG Block at 2987 with hash f1634a14 is valid, going to save and append.
Nov 22 00:43:39.147 INFO Updated head to f1634a14 at 2987.
Nov 22 00:43:39.147 DEBG Committing sumtree extension.
Nov 22 00:43:39.247 DEBG Sumtree extension done.
Nov 22 00:43:39.250 DEBG Received block fae41490 at 2988 from network, going to process.
Nov 22 00:43:39.250 DEBG Processing block fae41490 at 2988 with 0 inputs and 1 outputs.
Nov 22 00:43:39.251 DEBG Validating block with cuckoo size 16
Nov 22 00:43:39.258 DEBG Starting new sumtree extension.
Nov 22 00:43:39.349 TRCE Hashing with additional data
Nov 22 00:43:39.355 DEBG Block at 2988 with hash fae41490 is valid, going to save and append.
Nov 22 00:43:39.356 INFO Updated head to fae41490 at 2988.
Nov 22 00:43:39.356 DEBG Committing sumtree extension.
Nov 22 00:43:39.457 DEBG Sumtree extension done.
Nov 22 00:43:39.460 DEBG Received block 81ef2dd3 at 2989 from network, going to process.
Nov 22 00:43:39.460 DEBG Processing block 81ef2dd3 at 2989 with 0 inputs and 1 outputs.
Nov 22 00:43:39.461 DEBG Validating block with cuckoo size 16
Nov 22 00:43:39.467 DEBG Starting new sumtree extension.
Nov 22 00:43:39.562 TRCE Hashing with additional data
Nov 22 00:43:39.569 DEBG Block at 2989 with hash 81ef2dd3 is valid, going to save and append.
Nov 22 00:43:39.570 INFO Updated head to 81ef2dd3 at 2989.
Nov 22 00:43:39.570 DEBG Committing sumtree extension.
Nov 22 00:43:39.676 DEBG Sumtree extension done.
Nov 22 00:43:39.755 DEBG Sync: peer 28881590 vs us 28872857
Nov 22 00:43:39.755 DEBG Sync: blocks to download 4366, block downloading 1
Nov 22 00:43:39.755 DEBG Loc heights: [7355, 7353, 7351, 7347, 7339, 7323, 7291, 7227, 7099, 6843, 0]
Nov 22 00:43:40.443 DEBG peer total_diff (ping/pong): 174.138.116.153:13414, 28881590 vs us 11308294
Nov 22 00:43:40.624 DEBG Asking peer 174.138.116.153:13414 for more block headers, locator: [e4b4cd15, 758fc5a1, df1c72c4, 09042b96, 602a7f1e, 6fb5962d, 7132bb8e, 2a0799b2, b4eb6231, 6b581474, e17ea64f]
#

**Comment by ignopeverell** [comment]
Logs look fine. Please update and recompile, hopefully whatever was your issue has been fixed. If not, please file something with a more descriptive explanation of your problem.
