### ISSUE TITLE
grin cannot run in a constrained environment

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#362]
I tried to run `grin` in a container inside an Openshift cluster and failed:
```
Nov 22 01:41:07.078 INFO Starting the Grin server...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RocksDbErr("Failed to create RocksDBdirectory: `Error { repr: Os { code: 13, message: \"Permission denied\" } }`.")', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /builddir/build/BUILD/rustc-1.21.0-src/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /builddir/build/BUILD/rustc-1.21.0-src/src/libcore/result.rs:772
  11: grin_chain::chain::Chain::chain_exists
             at chain/src/chain.rs:61
  12: grin_grin::server::Server::future
             at grin/src/server.rs:93
  13: grin_grin::server::Server::start
             at grin/src/server.rs:63
  14: grin::server_command
             at src/bin/grin.rs:331
  15: grin::main
             at src/bin/grin.rs:260
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start
  18: main
  19: __libc_start_main
  20: _start
```
A bunch of capabilities are dropped by default from containers inside Openshift (I can come back to this later with the whole list of them) and `grin` doesn't seem to like it. I will likely run the container with elevated permissions on a different cluster for now.

**Comment by kargakis** [comment]
This also may be a misconfiguration on my side - will have another look tomorrow.

**Comment by kargakis** [comment]
Yeah, that was a misconfiguration but this still fails on a permission error
```
Nov 22 01:41:07.078 INFO Starting the Grin server...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RocksDbErr("Failed to create RocksDBdirectory: `Error { repr: Os { code: 13, message: \"Permission denied\" } }`.")', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /builddir/build/BUILD/rustc-1.21.0-src/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /builddir/build/BUILD/rustc-1.21.0-src/src/libcore/result.rs:772
  11: grin_chain::chain::Chain::chain_exists
             at chain/src/chain.rs:61
  12: grin_grin::server::Server::future
             at grin/src/server.rs:93
  13: grin_grin::server::Server::start
             at grin/src/server.rs:63
  14: grin::server_command
             at src/bin/grin.rs:331
  15: grin::main
             at src/bin/grin.rs:260
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start
  18: main
  19: __libc_start_main
  20: _start
```
Likely will run the container with elevated permissions on a different cluster for now.

**Comment by yeastplume** [comment]
Hi @kargakis 

Unfortunately, there doesn't seem much point in leaving this issue open for the time being, as this is most probably an environmental issue on the target machine that we don't have any visibility on. If you come across more specific problems and can give us some detail, please feel free to open another issue.

**Comment by kargakis** [comment]
FWIW my goal with this issue was ensuring `grin` can run on the free tier of public clouds like Openshift Online. I hope to find some time to investigate this more in the future.

**Comment by sesam** [comment]
@kargakis grin doesn't yet do pruning. Eith a mostly empty chain, it grows with ~150MB/week. A NAT:ed peer, so mostly downloadning, not uploading to other nodes, eats about ~25kB/s bandwidth. The compiling step probably needs 2GB memory. Mining will require GPUs to be any point. So I'm thinking that any free tier plans are not realistically useable to benefit the grin network, or to be "milked" for free coins.

@kargakis Though if you're still interested, PM me to cooperate on creating documentation about troubleshooting grin also on strange platforms. Eventually we'll want to run pruning grin nodes on very limited VM:s to increase the anonymity set. Thanks, and have a nice day.

**Comment by kargakis** [comment]
> The compiling step probably needs 2GB memory. Mining will require GPUs to be any point. So I'm thinking that any free tier plans are not realistically useable to benefit the grin network, or to be "milked" for free coins.

Compiling can be handled out of the platform. Mining is out of question, I am interested in public-facing validating nodes. I need to look into Source IP preservation in the env I was trying to run, it may be an issue.
