### ISSUE TITLE
Failed to acquire wallet lock file (multiple retries)

### ISSUE THREAD

**Issue by kallewoof** [mimblewimble/grin#365]
I started getting these all of a sudden. I pulled and built the latest version and now the server stops syncing after a few moments, and the error appears whenever I try the wallet info command.

`grin wallet info` results in a bunch of derivations and utxo gets, then:
```
Nov 22 18:31:21.393 INFO Acquiring wallet lock ...
Nov 22 18:31:21.393 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.406 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.417 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.440 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.476 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.528 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.609 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.740 DEBG Attempting to acquire wallet lock
Nov 22 18:31:21.951 DEBG Attempting to acquire wallet lock
Nov 22 18:31:22.295 DEBG Attempting to acquire wallet lock
Nov 22 18:31:22.846 DEBG Attempting to acquire wallet lock
Nov 22 18:31:22.847 ERRO Failed to acquire wallet lock file (multiple retries)
```
and the output is stuck at the same block, with a message at the bottom that goes
```
WARNING - Showing local data only - Wallet was unable to contact a node to update and verify the info shown here.
```

**Comment by antiochp** [comment]
The wallet listener (and other wallet commands) create a lock file - `wallet.lock` in the same dir as you run the wallet from.

1) make sure no wallet processes are running
2) `rm wallet.lock`
3) start the wallet listener

The wallet is not particularly robust and there are situations where the lock file ends up getting left behind.

**Comment by kallewoof** [comment]
Deleting `wallet.lock` solved the errors, but the server still gets stuck after a few blocks and is unable to finish syncing.
