### ISSUE TITLE
suspect MAX_LOCATORS is too small to be effective

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#366]
```
Nov 22 12:12:37.228 DEBG Loc heights: 
[7355, 7353, 7351, 7347, 7339, 7323, 7291, 7227, 7099, 6843, 0]
```

Here we start a node which attempts to sync with the chain by requesting headers with a locator.
Starting at height `7355` we ask for heights with increasing gaps - 
2<sup>1</sup>, 2<sup>2</sup>, 2<sup>3</sup>, 2<sup>4</sup>, etc.

But for `MAX_LOCATORS = 10` and a starting point of `block height 7355` we only go back to `block height 6843` before falling back to 0.

i.e. approx 512 block headers - 

2 + 4 + 8 + 16 + 32 + 64 + 128 + 256

512 feels like a pretty small cliff here - we either return __512__ (or less) or we need the full chain of __7355__ headers.

Even if we limit the # block headers we ever return - 
`pub const MAX_BLOCK_HEADERS: u32 = 512;`

I think it may still make sense to have the locator at least attempt to go all the way back to the genesis block, doubling the gap each time.
In this particular case we'd only need a few more locator entries before we hit 0.

**Comment by ignopeverell** [comment]
You're right, we should account for at least 2 days' worth of forking.
