### ISSUE TITLE
It should be possible to recover a wallet by passing the recovery phrase as an argument

### ISSUE THREAD

**Issue by boorishpea** [mimblewimble/grin#3661]
It should be possible to recover a wallet by passing the recovery phrase as an argument

**Comment by boorishpea** [comment]
it should also be possible to do all functions without using expect or pexpect. it would also be nice if you could turn color off so that you dont get ansi escape sequences in the output returned from stdout. you could even have a json argument so the result is output in json. i'm new to rust but if someone wants to help me make these changes i will happily devote time to it.

**Comment by boorishpea** [comment]
in grin cc meeting 2021/11/23 it was stated that grin was programmed this way to force user input. the discussion should continue to take place here. another suggestion was that a dev mode could be enabled to allow this.

**Comment by boorishpea** [comment]
it has also been said that the api can be used, please share the link to the api documentation

**Comment by yeastplume** [comment]
Please feel free to reopen, but please provide more specific detail as outlined in the 'Feature Request' template when creating the issue.
