### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by maogo** [mimblewimble/grin#3664]
Unable to connect to enough nodes and  stuck here all the time .

![2021-11-12_18-52](https://user-images.githubusercontent.com/20197997/141455750-e7df922e-96d6-460a-91f1-398d5a09be0a.png)

tried restart and rise  peer_max_outbound_count = 100 but still this issue,any idea?

**Comment by phyro** [comment]
Does the problem persist if you quit by pressing `d` and then launching grin again to get new peers?

**Comment by maogo** [comment]
quit by pressing Q and then launching grin again , I can see 11 out peers  but only one after ~2 minutes :
![22211-12_20-44_1](https://user-images.githubusercontent.com/20197997/141469343-8236c470-31fe-4b19-bb28-158fb832a751.png)

a lot of error in log like:
![error](https://user-images.githubusercontent.com/20197997/141469774-81f38b1a-b242-4474-8386-b27116e8e8b2.png)

**Comment by phyro** [comment]
Sorry, yeah, I meant `q`. Hmm, I did hear that the header sync takes the longest time to process so hopefully just bad peers.

**Comment by maogo** [comment]
I deleted the .Grin folder and then start again,I am now synchronized. 
during the sync, At the beginning of the 2/7 step is stuck(status:waiting remote peer to start:29950s).Sync does not move  Even I have many peers. restarting the grin sync started moving.
