### ISSUE TITLE
1 seed 2 wallets 2 balances

### ISSUE THREAD

**Issue by boorishpea** [mimblewimble/grin#3669]
i have used the same seed to restore a wallet twice
one has a higher balance than it should, the other has a lower balance than it should
one wallet has an outgoing transaction the other doesnt and the other has an incoming transaction the other doesnt
scan does not fix this.
now i have 2 broken wallets that will fail to work if i use the wrong values when sending.
what am i supposed to do with my 2 broken wallets?

**Comment by boorishpea** [comment]
i restored the wallet a third time and now it has half the balance it should

**Comment by boorishpea** [comment]
wtf has gone wrong here?

**Comment by boorishpea** [comment]
there were no locked transactions on any of them

**Comment by boorishpea** [comment]
@yeastplume can i give you my wallets to figure out whats gone wrong with them?

**Comment by yeastplume** [comment]
have you tried running `grin-wallet scan -d` on both of them?

**Comment by boorishpea** [comment]
yes, nothing changed.
