### ISSUE TITLE
Please lol

### ISSUE THREAD

**Issue by Mjazoulii** [mimblewimble/grin#3693]
![Screenshot_2022-02-16-00-17-58-091_com termux](https://user-images.githubusercontent.com/97406273/154166188-b505b339-df25-46dc-af54-c66423730559.jpg)
Guys ho
![Screenshot_2022-02-16-00-18-02-397_com termux](https://user-images.githubusercontent.com/97406273/154166197-882d15da-694f-4494-ae01-aa0292b49729.jpg)
Guys how can i get my wallet running with my node , i got to this point now i don't know what to do next !? I need to know how to get the wallet running so i can connect my miner to it !?

**Comment by JulsKawa** [comment]
you can use this [https://play.google.com/store/apps/details?id=com.grinplusplus.mobile](url) on android
