### ISSUE TITLE
grin no such command

### ISSUE THREAD

**Issue by roberto68** [mimblewimble/grin#370]
so exported path as described sourced .bashrc 
`
export PATH="/home/roberto/bin/grin/target/debug":$PATH"
`
but I am getting command not found, build was successful I only got a warning 
`
 Compiling gcc v0.3.54
 Compiling chrono v0.4.0
 Compiling secp256k1zkp v0.7.1 (https://github.com/mimblewimble/rust-secp256k1-zkp?
 tag=grin_integration_1#a3257cee)
 Compiling slog-term v2.3.0
 Compiling grin_util v0.1.0 (file:///home/roberto/bin/grin/util)
 Compiling grin_keychain v0.1.0 (file:///home/roberto/bin/grin/keychain)
 warning: unused `#[macro_use]` import
 --> /home/roberto/bin/grin/keychain/src/lib.rs:22:1
   |
  22 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
   Compiling grin_core v0.1.0 (file:///home/roberto/bin/grin/core)
    Finished dev [unoptimized + debuginfo] target(s) in 13.58 secs
`
and this is output of ls command of target/debug  
`
build  deps  examples  incremental  libgrin_core.d  libgrin_core.rlib  libgrin_keychain.rlib  libgrin_pow.d  libgrin_pow.rlib  libgrin_util.rlib  native  plugins
`

**Comment by ignopeverell** [comment]
This looks like you compiled inside the `core` subdirectory instead of at the root of the grin repository.
