### ISSUE TITLE
[no mining] mining successfully/The former files (wallet.dat/wallet.seed)do not work

### ISSUE THREAD

**Issue by mass34** [mimblewimble/grin#372]
./grin server --mine run
Nov 22 22:00:43.873 WARN P2P server started on 192.168.0.100:13414
Nov 22 22:00:43.875 WARN Grin server started.
thread 'syncer' panicked at 'No peers available for sync.', /checkout/src/libcore/option.rs:819:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by mass34** [comment]
Updated and recompiled

./grin server -m run
Nov 23 01:25:47.317 WARN P2P server started on 192.168.0.100:13414
Nov 23 01:25:47.321 WARN Grin server started.
thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.

./grin server -m run
Nov 23 01:32:05.195 WARN P2P server started on 192.168.0.100:13414
Nov 23 01:32:05.198 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block f697a877', grin/src/sync.rs:193:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

 ./grin server -m run
Nov 23 02:12:47.968 WARN P2P server started on 192.168.0.100:13414
Nov 23 02:12:47.970 WARN Grin server started.
thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'already borrowed: BorrowMutError', /checkout/src/libcore/result.rs:906:4


 ./grin server -m run
Nov 23 02:33:14.208 WARN P2P server started on 192.168.0.100:13414
Nov 23 02:33:14.211 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block 6ecd2315', grin/src/sync.rs:193:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

./grin server -m run
Nov 23 02:50:48.111 WARN P2P server started on 192.168.0.100:13414
Nov 23 02:50:48.111 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block 2ee9d8a1', grin/src/sync.rs:193:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

./grin server -m run
Nov 23 03:10:45.130 WARN P2P server started on 192.168.0.100:13414
Nov 23 03:10:45.133 WARN Grin server started.
thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:906:4
 ./grin server -m run
Nov 23 03:13:55.066 WARN P2P server started on 192.168.0.100:13414
Nov 23 03:13:55.069 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block 0f5b01a9', grin/src/sync.rs:193:4                                          
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                                                        
                                                                                                                                                                                                                               

 ./grin server -m run                                                                          
Nov 23 04:00:37.369 WARN P2P server started on 192.168.0.100:13414                                                                        
Nov 23 04:00:37.371 WARN Grin server started.                                                                                             
thread 'syncer' panicked at 'Failed to download required block 89e95138', grin/src/sync.rs:193:4                                          
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                                                        
                                                                                                                                      
./grin server -m run
Nov 23 04:03:02.793 WARN P2P server started on 192.168.0.100:13414
Nov 23 04:03:02.796 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block 0f34b90e', grin/src/sync.rs:193:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

./grin server -m run
Nov 23 04:05:58.130 WARN P2P server started on 192.168.0.100:13414
Nov 23 04:05:58.135 WARN Grin server started.
thread 'syncer' panicked at 'Failed to download required block d596900d', grin/src/sync.rs:193:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by mass34** [comment]
Mining has earned!))))
The problem is this. Default only wallet.dat|wallet.seed. 
Replacement of files gives an error
./grin server -m run
Nov 23 21:24:50.933 WARN P2P server started on 192.168.0.100:13414
Nov 23 21:24:50.938 WARN Grin server started.
Nov 23 21:25:07.056 ERRO Failed to get coinbase via wallet API (will retry)...
Nov 23 21:25:07.157 ERRO Failed to get coinbase via wallet API (will retry)...
Nov 23 21:25:07.259 ERRO Failed to get coinbase via wallet API (will retry)...
Nov 23 21:25:07.461 ERRO Failed to get coinbase via wallet API (will retry)...
Nov 23 21:25:07.763 ERRO Failed to get coinbase via wallet API (will retry)...
Nov 23 21:25:08.265 ERRO Failed to get coinbase via wallet API (will retry)...
and
./grin wallet -p MYpass listen
Nov 23 21:24:45.249 DEBG Using wallet seed file at: ./wallet.seed
Nov 23 21:24:45.360 INFO Starting the Grin wallet receiving daemon at 127.0.0.1:13415...
Nov 23 21:25:05.967 INFO Acquiring wallet lock ...
Nov 23 21:25:05.967 DEBG Attempting to acquire wallet lock
Nov 23 21:25:05.978 DEBG Attempting to acquire wallet lock
Nov 23 21:25:05.988 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.008 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.039 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.089 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.169 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.300 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.510 DEBG Attempting to acquire wallet lock
Nov 23 21:25:06.851 DEBG Attempting to acquire wallet lock


Removal wallet.lock does not help

**Comment by yeastplume** [comment]
This doesn't appear to be a grin issue, you probably have another grin process running that's taking the lock. Happy to help further on https://gitter.im/grin_community/dev
