### ISSUE TITLE
request block from random peer (consider random with minimum difficulty?)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#376]
When we request blocks we request them from a random peer.

The testnet1 is in a degenerate state right now where many different peers are stuck on various heights/difficulties.

Would it make sense to target peers that have a higher likelihood of having the requested block rather than simply randomly choosing a connected one?

**Comment by sesam** [comment]
Hey, so many issues about sync. Maybe move this question into #384? And we can close users' sync issues with a quick status explanation, and maybe add something in README.md so users can see network status. CC @yeastplume

**Comment by antiochp** [comment]
Resolved in #379
