### ISSUE TITLE
grin 5.1.2 failed to build against rust 1.71.0

### ISSUE THREAD

**Issue by chenrui333** [mimblewimble/grin#3764]
While [upgrading rust to 1.71.0](https://github.com/Homebrew/homebrew-core/pull/136514), we found that grin has some build issue with it, see the following build failure

```
   Compiling grin_servers v5.1.2 (/private/tmp/grin-20230719-64749-1pu5gsf/grin-5.1.2/servers)
error: variable does not need to be mutable
   --> servers/src/mining/stratumserver.rs:733:7
    |
733 |         let mut worker = wl
    |             ----^^^^^^
    |             |
    |             help: remove this `mut`
    |
note: the lint level is defined here
   --> servers/src/lib.rs:21:9
    |
21  | #![deny(unused_mut)]
    |         ^^^^^^^^^^

error: could not compile `grin_servers` (lib) due to previous error
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5594719599/job/15158499681?pr=136514

**Comment by yeastplume** [comment]
Thanks for the report, the fix was included here, and should be in the next 5.2.0 beta release

**Comment by chenrui333** [comment]
@yeastplume that patch works for me, can you also take a look at this issue, https://github.com/mimblewimble/grin-wallet/issues/683?

**Comment by chenrui333** [comment]
closed via https://github.com/Homebrew/homebrew-core/pull/137419
