### ISSUE TITLE
Question: Why secp256k1 is used instead of Ed25519?

### ISSUE THREAD

**Issue by prusnak** [mimblewimble/grin#377]
Ed25519 has much better properties than ECDSA with secp256k1. Also, there is an excellent native Ed25519 implementation written in Rust: https://github.com/isislovecruft/ed25519-dalek

Why is secp256k1 used rather than Ed25519?

**Comment by JollyMort** [comment]
Ibwas curuous about that too, see here: https://www.reddit.com/r/Mimblewimble/comments/60hukc/mimblewimble_intro_doc/df6luh0/

**Comment by apoelstra** [comment]
See also https://www.reddit.com/r/Bitcoin/comments/7dabe3/why_does_bitcoin_use_ecsda_instead_of_ed25519/dpwauak/

Pure Rust is not an advantage for crypto libraries at this level. There is almost no memory management required (libsecp256k1 uses no allocations whatsoever except during initialization) and constant-timeness is critical.

**Comment by prusnak** [comment]
Thank you, Jolly and Andrew. Closing this issue.
