### ISSUE TITLE
When run_tui is set to false it does not return to the cmd line once started

### ISSUE THREAD

**Issue by Nonia-GrinMW** [mimblewimble/grin#3784]
**Describe the bug**
When you set the "run_tui" option to false in grin-server.toml it runs and displays lines of info but does not return back to the prompt so it's not fully running in the background.

**To Reproduce**
1. Open editor with grin-server.toml and change run_tui value to run_tui = false
2. Expect the process to go in to the background when run
3. Execute command grin server run
4. The process fails to return to prompt and stays in foreground

**Relevant Information**
20240404 02:55:24.763 WARN grin::cmd::server - Starting GRIN w/o UI...

There is no mention of errors or being run as daemon past that line.

**Screenshots**
![Screenshot from 2024-04-04 02-57-50](https://github.com/mimblewimble/grin/assets/165659657/242f2c32-cf67-4a8d-935d-8a9d45954f0f)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version 5,2.1

**Comment by Nonia-GrinMW** [comment]
So I found this article which explains you have to manually install grin to /usr/local/bin,  create a grin.service file, and reload systemctl. Seems like every other wallet doesn't require all that and is able to do it in a few seconds without intervention.

https://privatepayments1.medium.com/grin-full-node-and-wallet-installation-linux-9025684802fa

**Comment by aglkm** [comment]
run_tui option has nothing to do with running grin node in background, as comment states:
#whether to run the ncurses TUI (Ncurses must be installed)

Simple command to run the node in background:
nohup ./grin &
