### ISSUE TITLE
error: Could not compile `tokio-retry`

### ISSUE THREAD

**Issue by roberto68** [mimblewimble/grin#383]
compiling I got following errors
`
error: non-capturing closure to fn coercion is experimental (see issue #39817)
  --> /home/roberto/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.1.1/src/future.rs:85:64
   |
85 |             retry_if: RetryIf::spawn(handle, strategy, action, (|_| true) as fn(&A::Error) -> bool)
   |                                                                ^^^^^^^^^^
`      
`
error: non-scalar cast: [closure@/home/roberto/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.1.1/src/future.rs:85:64: 85:74]` as `fn(&<A as action::Action>::Error) -> bool
  --> /home/roberto/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.1.1/src/future.rs:85:64
   |
85 |             retry_if: RetryIf::spawn(handle, strategy, action, (|_| true) as fn(&A::Error) -> bool)
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`
`
error: aborting due to 2 previous errors
error: Could not compile tokio-retry.
Build failed, waiting for other jobs to finish...
`

**Comment by aelr** [comment]
Can you report what you get from `cargo --version`?  I think I ran into this issue when building, and I had an outdated version of cargo (I hadn't used rustup for installation).

**Comment by antiochp** [comment]
Yeah - almost certainly either cargo or rust itself being an old version.

**Comment by roberto68** [comment]
now I installed rust via rsvm (rust version manager) and I get 
`
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
info: caused by: not a directory: '/home/roberto/.rsvm/current/rustup/toolchains/nightly-x86_64-unknown-linux-gnu'
` 
but that's not problem of a grin I know

**Comment by yeastplume** [comment]
HI @roberto68 

If you want to stop by https://gitter.im/grin_community/dev with your latest errors, we'll all be happy to help. I'm just going to close because it's not a grin issue and we need to start reducing the number of open issues we have. Thanks!
