### ISSUE TITLE
Re-sync should ban peers and continue until correct chain is found

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#394]
Observed after one node fell slightly behind, in a state where most chains on the network are wrong:

```
Nov 28 15:58:57.900 INFO Rejected block f697a877 at 4689: AlreadySpent
Nov 28 15:58:57.967 INFO Rejected block 68cf8f3d at 4690: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.043 INFO Rejected block d07e778b at 4691: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.126 INFO Rejected block 27c99cbf at 4692: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.195 INFO Rejected block 7ce28877 at 4693: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.265 INFO Rejected block 7709ca28 at 4694: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.336 INFO Rejected block 3a334b68 at 4695: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.408 INFO Rejected block 6572f4db at 4696: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.479 INFO Rejected block 8d34e50f at 4697: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:58:58.551 INFO Rejected block 0f4c19f4 at 4698: StoreErr(NotFoundErr, "wrapped")
Nov 28 15:59:05.133 INFO Client 47.218.248.206:13414 disconnected.
Nov 28 15:59:08.213 INFO sync: caught up on the most worked chain, disabling sync
Nov 28 15:59:15.946 INFO (Server ID: Port 13414) Found valid proof of work, adding block 06eb6077.
```

The re-sync is just blindly trying to get headers from the first peer it sees, and not marking it as invalid if it turns out to have an invalid block. In this situation, it should probably retry other peers.

**Comment by ignopeverell** [comment]
So getting headers isn't necessarily an issue if it's on new peers. Wasn't the peer that sent you the bad block banned?

**Comment by yeastplume** [comment]
No, they don't appear to be getting banned after re-sync is triggered, I think that's the issue.

**Comment by ignopeverell** [comment]
What do you mean by "re-sync"? After a restart? There's a list of bannable errors, and AlreadySpent is one of them, but if another error occurs (like a NotFound) it's possible it's not being banned when it should. Maybe that error isn't specific enough?

**Comment by yeastplume** [comment]
I meant not when you restart grin, but when the syncer detects a chain of work that's well ahead of yours and starts the sync process again... I can verify it in the logs now:

```
Nov 28 16:34:36.873 DEBG Sync: Asking peer 24.7.36.144:13414 for more block headers, locator: 
.
Nov 28 16:35:07.365 DEBG Sync: Asking peer 24.7.36.144:13414 for more block headers, locator:
```

Whereas it should have banned this peer the first time.

**Comment by ignopeverell** [comment]
Mmmh wonder if there's something that would update the peer record as unbanned... Do you have something like that in your logs?

```
DEBG Block f697a877 refused by chain: AlreadySpent
DEBG saving peer to store PeerData { addr: V4(109.74.202.16:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Banned }
DEBG Banning peer 109.74.202.16:13414
DEBG Reset header head to 79db244c at 4688
```

**Comment by ignopeverell** [comment]
Seems to be behaving properly now.
