### ISSUE TITLE
[wallet] thread '<unnamed>' panicked at 'should never happen', /home/stelmaria/src/grin/wallet/src/receiver.rs:102:2

### ISSUE THREAD

**Issue by AsrielBelacqua** [mimblewimble/grin#395]
Please see wallet listener log at http://termbin.com/sx7v

~~~I initially tried a wallet restore (though I accidentally omitted my password) to clear up some locked outputs, and restarted the listener with my usual password and the empty wallet.dat file.~~~ (**The preceding sentence doesn't seem to relate to the cause of this issue; see below.**)

I have attached both wallet.dat files and can supply the wallet.seed file if necessary.

Locked wallet.dat: http://termbin.com/uqxs
Empty generated wallet.dat: http://termbin.com/j14m


NB Comment 347700796 below: "So it seems this may not be related to the restore at all: it now seems to restart reliably if I restart the wallet listener while a miner is running, without stopping the miner before restarting the listener."

**Comment by AsrielBelacqua** [comment]
Restored wallet.dat: http://termbin.com/w7xo

Having restored with the correct password, I have not seen the panic again, and my UTXOs look decent.

**Comment by AsrielBelacqua** [comment]
Actually, I take that back, the panic recurred when I ran `info` after `recover` even with the correct password.

**Comment by AsrielBelacqua** [comment]
It now looks like the panic occurs every time my miner produces a new coinbase..

**Comment by AsrielBelacqua** [comment]
But, reverting to the old wallet.dat (termbin uqxs above), the panic goes away.

**Comment by AsrielBelacqua** [comment]
Also, restarting my nodes seems to have vanquished this (emphasis on 'seems to', of course).

**Comment by AsrielBelacqua** [comment]
So it seems this may not be related to the `restore` at all: it now seems to restart reliably if I restart the wallet listener while a miner is running, without stopping the miner before restarting the listener.

**Comment by AsrielBelacqua** [comment]
And, indeed, it does not occur if I restart the listener while the miner is stopped, then start the miner again.

**Comment by yeastplume** [comment]
Ancient T1 issue, no longer relevant.
