### ISSUE TITLE
API endpoints to browse blocks

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#397]
Allow retrieving block data by full hash or by height. Something like:
```
// block at height 10
/v1/blocks/10

// block with hash d3c2bc...
/v1/blocks/d3c2bc65eb58c94c8f5c048283e907afbe37d53959a6add37f8a7757542ab75e
```

Data returned should at least include everything that's in the block header and idea the list of input and ouput commitments (no range proof though, that's too big for an API).

**Comment by jgannonjr** [comment]
I'll take a stab at this :)

**Comment by ignopeverell** [comment]
That's great! Don't hesitate to ask here or on Gitter if you need help.

**Comment by jgannonjr** [comment]
Thanks!  Just submitted a PR and left a comment there.
