### ISSUE TITLE
Block explorer to visualize and browse the chain from a web browser

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#398]
Can directly rely on the node JSON/HTTP APIs.

Depends on #397. Should likely be its own separate project.

**Comment by auldsyababua** [comment]
Do you have any feedback on how you'd like the view to look, what extra features you'd like it to have, etc?

**Comment by ignopeverell** [comment]
There are many block explorers out there for other chains (bitcoin, ethereum, monero, zcash, etc) so there's no reason to fully reinvent the wheel. Maybe just pick a clean one you like? I wouldn't spend too much time on visuals at the point (i.e. colors, fonts, etc) as we don't have anything set yet.

You can run a testnet1 node, get the chain and start checking the APIs (it's all JSON/HTTP).

**Comment by auldsyababua** [comment]
awesome sounds good. Will do

**Comment by antiochp** [comment]
Personally I'd find the following really useful (really minimal tabular data UI) - 

```
* list of latest blocks
  * height
  * hash
  * age (if we have timestamps via api?)
  * # tx kernels
* drilldown into single block (via height or hash)
  * height
  * hash
  * age
  * block reward (even if its just 50 everytime)
  * fees
  * # tx kernels
  * # inputs
  * # outputs
```

**Comment by auldsyababua** [comment]
@ignopeverell I have created a repo with my react boilerplate for this project here:
https://github.com/auldsyababua/grin_block_explorer

Would you just like me to make regular updates on progress in this thread?

**Comment by ignopeverell** [comment]
That would be great!

**Comment by hendi** [comment]
I've pushed the code powering [grinexplorer.net](https://grinexplorer.net) to [mimblewimble/grin-explorer](https://github.com/mimblewimble/grin-explorer).

**Comment by ignopeverell** [comment]
Sweet, thanks!
