### ISSUE TITLE
Better test to re-trigger sync

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#401]
We will get back into sync mode only if we find a peer with a head at a 1000 higher difficulty than ours:

https://github.com/mimblewimble/grin/blob/c265e937e9d6f95461d7499f5368750d52fad97b/grin/src/adapters.rs#L293

This constant is likely to be wrong and should vary with current network difficulty. The sum of the difficulty in the last 5 blocks may be a better test?

**Comment by antiochp** [comment]
Just for clarification - the sum of the difficulty in the last 5 blocks gives us a threshold that we then use to compare total_difficulty of our peers to?
i.e. this roughly approximates a peer that is 5 blocks ahead?

**Comment by yeastplume** [comment]
Yes, roughly 5 minutes out of sync... theoretically this should only be a fallback in extreme cases; the gossip should definitely be catching everyone up within a 5 minute interval or something is seriously wrong.

**Comment by ignopeverell** [comment]
Yeah, or one of those cases of selfish mining. Or we lost internet connectivity for 10 min without a restart. Things can go wrong in so many ways...
