### ISSUE TITLE
MW scaling: full pruning

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#404]
Current node model is one of a full archival node. To realize the scaling benefits of a MimbleWimble type chain we need 2 additional features:

* Pruning of chain data when it's not relevant to the UTXO set or the recent chain state.
* Sync only based on the header chain, the MMR sumtrees (tracked in #403).

This issue is for the former.

Currently until MMR sumtree data is pruned to account for outputs spending, however all block data remains. As outputs are spent, we can also get rid of all related data, like commitments and most importantly range proofs.

**Comment by antiochp** [comment]
The `.grin/chain` is actually growing pretty quickly (did not realize it was growing _this_ fast) - 

```
du -h .
4.0K	./plugins/plugins
528K	./plugins
224K	./.grin/peers
538M	./.grin/chain
2.2M	./.grin/sumtrees/kernel
31M	./.grin/sumtrees/rangeproof
33M	./.grin/sumtrees/utxo
66M	./.grin/sumtrees
604M	./.grin
624M	.
```

**Comment by ignopeverell** [comment]
Yup. Liking them large rangeproofs? :-)
