### ISSUE TITLE
node receives a orphan block (via gossip) with more work than current chain head

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#411]
In this situation it appears we just saw a block on the network that is part of a chain further ahead than we are.
Can we ask for the "previous" block in this case (and do this recursively as we receive still-orphaned blocks).
Is there any reason not to want to start trying to de-orphan-ize it?
Regardless of what the sync will do when it kicks off it seems likely we will want to retrieve these intermediate blocks?

One thing I can think of is the case where we have multiple forks that are all ahead of us - ideally we're just focused on catching up with the one single "true" chain.
Everything else is just wasted effort.

**Comment by ignopeverell** [comment]
Wouldn't we always have a higher difficulty from that peer in the first place though? And so be trying to sync already?

**Comment by antiochp** [comment]
I _think_ so yeah. Closing this.
I believe what I was seeing when I started thinking about this is described in #412 when it appeared we were seeing a peer with more work but not syncing correctly with it.
