### ISSUE TITLE
Failed to run on ARMv7 (raspberry pi 3)

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#417]
I managed to cross-compile `grin` minus the mining plugins with [rust-on-raspberry-docker](https://github.com/Ragnaroek/rust-on-raspberry-docker) but I can't seem to be able to actually run the server.
```console
$ RUST_BACKTRACE=1 ./grin server run 
Dec 03 02:58:00.125 INFO Starting the Grin server...
thread 'main' panicked at 'Pre-set', Deccore/src/global.rs :1500:37 
02:58:00.174 INFO Genesis block not found, initializing...
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: grin_core::global::get_genesis_nonce
   7: grin_core::genesis::genesis_dev
   8: grin_pow::mine_genesis_block
   9: grin_grin::server::Server::future
  10: grin_grin::server::Server::start
  11: grin::main
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  14: __libc_start_main
```

**Comment by sesam** [comment]
can you confirm which branch / commit you used, and which rust version?

**Comment by ignopeverell** [comment]
Yeah, you'll want to use the `testnet1` branch. On main, the genesis block is mined on the spot to initiate a dev chain, looks like that's what's failing (assumingly because you deactivated mining plugins).

**Comment by kargakis** [comment]
> Yeah, you'll want to use the testnet1 branch. On main, the genesis block is mined on the spot to initiate a dev chain, looks like that's what's failing (assumingly because you deactivated mining plugins).

That was the issue, thanks!

**Comment by ignopeverell** [comment]
How about a little PR on the build docs to add some footnotes or troubleshooting at the bottom for ARM builds?

**Comment by kargakis** [comment]
I'll try to write something up latter this week.

**Comment by ignopeverell** [comment]
That would be great, thanks!

**Comment by kargakis** [comment]
Opened https://github.com/mimblewimble/grin/pull/457
