### ISSUE TITLE
Node crashes with BorrowError

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#421]
Backtrace:

```
root@seed1:~/server# RUST_BACKTRACE=1 ~/grin/target/debug/grin server run           
Dec 02 17:41:09.812 WARN P2P server started on 0.0.0.0:13414                                                  
Dec 02 17:41:09.815 WARN Grin server started.                                     
thread 'main' panicked at 'already mutably borrowed: BorrowError', /checkout/src/libcore/result.rs:906:4     
stack backtrace:                                             
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace                                                
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print                                                                 
             at /checkout/src/libstd/sys_common/backtrace.rs:71               
   2: std::panicking::default_hook::{{closure}}                                                               
             at /checkout/src/libstd/sys_common/backtrace.rs:60         
             at /checkout/src/libstd/panicking.rs:381                                                         
   3: std::panicking::default_hook                                             
             at /checkout/src/libstd/panicking.rs:397                                                         
   4: std::panicking::rust_panic_with_hook                                    
             at /checkout/src/libstd/panicking.rs:611                                                         
   5: std::panicking::begin_panic                                       
             at /checkout/src/libstd/panicking.rs:572                                                    
   6: std::panicking::begin_panic_fmt                                          
             at /checkout/src/libstd/panicking.rs:522                                                        
   7: rust_begin_unwind                                      
             at /checkout/src/libstd/panicking.rs:498                                                     
   8: core::panicking::panic_fmt                                              
             at /checkout/src/libcore/panicking.rs:71                                                       
   9: core::result::unwrap_failed                                       
             at /checkout/src/libcore/macros.rs:41                                                       
  10: <core::result::Result<T, E>>::expect                                     
             at /checkout/src/libcore/result.rs:799                                                          
  11: <core::cell::RefCell<T>>::borrow                       
             at /checkout/src/libcore/cell.rs:669                                                         
  12: <grin_util::OneTime<T>>::borrow               
             at /root/grin/util/src/lib.rs:98                                                              
  13: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::peer_difficulty
             at grin/src/adapters.rs:267
  14: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::peer_difficulty
             at p2p/src/peer.rs:268
  15: grin_p2p::protocol::handle_payload
             at p2p/src/protocol.rs:145
  16: <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}
             at p2p/src/protocol.rs:55
  17: <F as grin_p2p::conn::Handler>::handle
             at p2p/src/conn.rs:66
  18: grin_p2p::conn::TimeoutConnection::listen::{{closure}}
             at p2p/src/conn.rs:275
  19: <F as grin_p2p::conn::Handler>::handle
             at p2p/src/conn.rs:66
  20: grin_p2p::conn::Connection::read_msg::{{closure}}::{{closure}}
             at p2p/src/conn.rs:215
  21: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:34
  22: <core::result::Result<T, E>>::map
             at /checkout/src/libcore/result.rs:468
  23: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:33
```

**Comment by ignopeverell** [comment]
Fixed in a5acd12

**Comment by kingsley-shacklebolt** [comment]
I have been playing with Rust over the last few years, but I don't have a deep understanding yet. So if you have a minute, I would love to ask for some help understanding this problem, and the fix you committed.

It was my understanding that Rust could often prevent against runtime crashes and panics, so I'm curious to know how this happened. Why did the compiler allow you to borrow without checking? Is there a safer way to write the code so that a runtime crash is always impossible? (Maybe some different compiler flags to turn on "strict" mode?)

No problem if you're too busy, but I would love to learn more about Rust, and eventually contribute some code!

**Comment by sesam** [comment]
@kingsley-shacklebolt oops - the two are not actually related, my bad. So we better discuss the new bug in its own issue.

Rubberduck is too low level I think. See thebacktrace above? This part:
>   12: <grin_util::OneTime<T>>::borrow               
>              at /root/grin/util/src/lib.rs:98                                                              
>   13: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::peer_difficulty
>              at grin/src/adapters.rs:267
>   14: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::peer_difficulty
>              at p2p/src/peer.rs:268
>   15: grin_p2p::protocol::handle_payload
>              at p2p/src/protocol.rs:145
>   16: <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}
>              at p2p/src/protocol.rs:55

So it's about peer_difficulty() being called too early.
And the problem avoided by not doing it too early :)

> Is there a safer way to write the code 

Maybe :). We could use more rust-native futures and timeouts, but doing that might also make the code harder to understand for contributors.

> so that a runtime crash is always impossible?

Nope, sorry :)

If you @kingsley-shacklebolt want more on borrowing, see: https://doc.rust-lang.org/book/first-edition/references-and-borrowing.html  and maybe ask on gitter, to keep issues more focused on bugs and features, and gitter might be better for debating. Have a nice day!

**Comment by Kixunil** [comment]
@kingsley-shacklebolt short answer to your question is: Rust prevents you writing bad code to the point it exceptionally rejects code, that is actually correct. To work around this you have to redesign the code or explicitly tell the compiler to move checking into run-time. This is the case of run-time check.

It's very similar to mutexes, just in single thread and kills the program instead of blocking (cause blocking would cause deadlock).
