### ISSUE TITLE
panic "index out of bounds" in sumtree extension

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#423]
My seed crashed with a panic overnight. Got a backtrace this time (finally worked out how to scrollback in tmux...) 

1) we entered sync mode as a peer advertised larger `total_difficulty`
2) pulled the new headers successfully
3) started requesting and processing new blocks
4) fork encountered at height `13022`, hash `fc66d096`
5) rewound sumtrees to `output pos: 28286, kernel pos: 27189`
6) panic - `index out of bounds: the len is 34 but the index is 28316`

```
    10: grin_chain::sumtree::Extension::apply_block
    11: grin_chain::pipe::process_block
    12: grin_chain::chain::Chain::process_block
```

Full backtrace below - 

```
Dec 04 05:49:17.384 DEBG Received block dbaa69d3 at 13024 from network, going to process.
Dec 04 05:49:17.384 DEBG pipe: process_block dbaa69d3 at 13024 with 16 inputs and 21 outputs.
Dec 04 05:49:17.384 DEBG pipe: validate_header cuckoo size 16
Dec 04 05:49:17.384 DEBG Starting new sumtree extension.
Dec 04 05:49:18.152 DEBG validate_block: forked_block: fc66d096 at 13022
Dec 04 05:49:18.152 DEBG Rewind sumtrees to header fc66d096 at 13022
Dec 04 05:49:18.152 DEBG Rewind sumtrees to output pos: 28286, kernel pos: 27189
Dec 04 05:49:18.158 DEBG -- outputs --
Dec 04 05:49:18.159 DEBG    28273    28274    28275    28276    28277    28278    28279    28280 
Dec 04 05:49:18.159 DEBG 62f85298 6e4e53a1 d738c2ae f7142b6a d9162a1e 29e41b6c a697d093 6cd3b67a 
Dec 04 05:49:18.159 DEBG    28281    28282    28283    28284    28285    28286 
Dec 04 05:49:18.160 DEBG 5ecca4a0 734a61ad 23717b0c 2bc49b69 00b90d0a 04b1c222 
thread 'main' panicked at 'index out of bounds: the len is 34 but the index is 28316', /checkout/src/liballoc/vec.rs:1564:14
Dec 04 05:49:18.187 DEBG block_sync: requesting blocks (13106/13117), [dbaa69d3, 7c46e452, 71efbebc, 32bf6f03, ad82dc3a, c9f53ee5, c89ed647, a
04b1e08, ca42922c, 4b85b79b]
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: grin_chain::sumtree::Extension::apply_block
  11: grin_chain::pipe::process_block
  12: grin_chain::chain::Chain::process_block
  13: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received
  14: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received
  15: <futures::future::chain::Chain<A, B, C>>::poll
  16: <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll
  17: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  18: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  19: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  20: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  21: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  22: tokio_core::reactor::Core::poll
  23: grin_grin::server::Server::start
  24: grin::main
  25: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  26: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  27: __libc_start_main
  28: _start
```

@ignopeverell @yeastplume

**Comment by antiochp** [comment]
This is also happening on restart so something looks like it is corrupted.
I'll zip my .grin dir up and post it here.

**Comment by antiochp** [comment]
Just realized I don't have the latest fixes for DuplicateCommitment etc. 
So wondering if this is maybe fixed already? Or if this is something different?

**Comment by ignopeverell** [comment]
Got the same on one of my nodes, with line numbers:

thread 'main' panicked at 'index out of bounds: the len is 34 but the index is 28314', /checkout/src/liballoc/vec.rs:1561:14                                                                              [100/758]
stack backtrace:                                    
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace                                                                                                                                                     
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                              
   1: std::sys_common::backtrace::_print                                                                                                                                                                           
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}                                                                                                                                                                    
             at /checkout/src/libstd/sys_common/backtrace.rs:58                                                     
             at /checkout/src/libstd/panicking.rs:381                                                                                                                                                              
   3: std::panicking::default_hook                                                                       
             at /checkout/src/libstd/panicking.rs:397                                                                                                                                                              
   4: std::panicking::rust_panic_with_hook                                                                          
             at /checkout/src/libstd/panicking.rs:577                                                                                                                                                              
   5: std::panicking::begin_panic                                                                                
             at /checkout/src/libstd/panicking.rs:538                                                                                                                                                              
   6: std::panicking::begin_panic_fmt                                                                               
             at /checkout/src/libstd/panicking.rs:522                                                                                                                                                              
   7: rust_begin_unwind                                                                                         
             at /checkout/src/libstd/panicking.rs:498                                                                                                                                                              
   8: core::panicking::panic_fmt                                                                                
             at /checkout/src/libcore/panicking.rs:71                                                                                                                                                              
   9: core::panicking::panic_bounds_check                                                                      
             at /checkout/src/libcore/panicking.rs:58                                                                                                                                                              
  10: <alloc::vec::Vec<T> as core::ops::index::IndexMut<usize>>::index_mut                                        
             at /checkout/src/liballoc/vec.rs:1561                                                                                                                                                                 
  11: <grin_core::core::pmmr::VecBackend<T> as grin_core::core::pmmr::Backend<T>>::remove                      
             at ./core/src/core/pmmr.rs:448                                                                                                                                                                        
  12: <grin_store::sumtree::PMMRBackend<T> as grin_core::core::pmmr::Backend<T>>::remove                           
             at ./store/src/sumtree.rs:369                                                                                                                                                                         
  13: <grin_core::core::pmmr::PMMR<'a, T, B>>::prune                                                              
             at ./core/src/core/pmmr.rs:343                                                                                                                                                                        
  14: grin_chain::sumtree::Extension::apply_block                                                              
             at chain/src/sumtree.rs:248                                                                                                                                                                           
  15: grin_chain::pipe::validate_block                                                                             
             at chain/src/pipe.rs:285                        
  16: grin_chain::pipe::process_block::{{closure}}                                                              
             at chain/src/pipe.rs:93                                          
  17: grin_chain::sumtree::extending                                                                              
             at chain/src/sumtree.rs:160                                
  18: grin_chain::pipe::process_block                                                                          
             at chain/src/pipe.rs:92                                                                     
  19: grin_chain::chain::Chain::process_block                                                                      
             at chain/src/chain.rs:150                                                                   
  20: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received                   
             at grin/src/adapters.rs:78             
  21: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received                           
             at p2p/src/peer.rs:240                                          
  22: grin_p2p::protocol::handle_payload                                                                        
             at p2p/src/protocol.rs:188                      
  23: <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}
             at p2p/src/protocol.rs:55
  24: <F as grin_p2p::conn::Handler>::handle
             at p2p/src/conn.rs:66
