### ISSUE TITLE
thread 'syncer' panicked at 'called `Result::unwrap()` on an `Err` value: StoreErr

### ISSUE THREAD

**Issue by roberto68** [mimblewimble/grin#424]
after update, started the server, got this error
`
thread 'syncer' panicked at 'called ``Result::unwrap()`` on an ``Err`` value: StoreErr(NotFoundErr, "chain get header by height")', /checkout/src/libcore/result.rs:906:4
`
stack backtrace: 
`
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: grin_grin::sync::Syncer::get_locator::{{closure}}
             at grin/src/sync.rs:287
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  13: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  14: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1123
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1822
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1805
  17: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1692
  18: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1298
  19: grin_grin::sync::Syncer::get_locator
             at grin/src/sync.rs:284
  20: grin_grin::sync::Syncer::request_headers
             at grin/src/sync.rs:247
  21: grin_grin::sync::Syncer::run
             at grin/src/sync.rs:134
  22: grin_grin::adapters::NetToChainAdapter::start_sync::{{closure}}
             at grin/src/adapters.rs:294
`
my rust version is the newest - 1.22.1

**Comment by ignopeverell** [comment]
Looks like you're running older code (`sync.rs` hasn't had a line 287 for some time), please update as this is likely fixed now.

**Comment by roberto68** [comment]
I did git fetch than cargo build

**Comment by roberto68** [comment]
ok I 've to do git pull now it seems ok
