### ISSUE TITLE
Macbook Pro mid 2009 has trouble to start up the server

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#429]
Macbook Pro mid 2009, 2.53 GHz Intel Core Duo
Had fresh install.

Command executed: grin server -m run

terminated with the following stdout.
Dec 03 09:42:16.350 WARN P2P server started on 0.0.0.0:13414
Dec 03 09:42:16.352 WARN Grin server started.
Illegal instruction: 4

**Comment by kargakis** [comment]
Can you post the output of `RUST_BACKTRACE=1 grin server -m run`?

**Comment by heunglee** [comment]
I tried to start the server with RUST_BACKTRACE=1 option. But no error was displayed in stdout and log file. It just died silently. Only illegal instruction: 4. I googled the error message in stackoverflow and found the following Q and A. 
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

As mentioned above, my macbook pro is a model of mid 2009 and upgraded to mac os 10.12.x. My macbook pro is however not allowed to upgrade to High Sierra. The CPU is Intel Core Duo which might be x86 compatible based on an online source. But the cuckoo cycle miner with grin compilation features seems not compatible with the CPU. I did not try the internal miner.

In my opinion, the error just resulted from incompatible hardware for binary of cuckoo cycle miner.

**Comment by heunglee** [comment]
Apple does not allow Macbook pro mid 2009 to upgrade to latest version of OS (High Sierra). So the model is fading away! or already faded out?. Under the circumstance, it is not good idea grin dev needs take efforts on this issue. It seems to me Macbook pro mid 2009 does not fulfill the hardware requirement of grin. Just my thought...

**Comment by sesam** [comment]
No worries. Can you check you're on the latest code with git pull and the
testnet1 branch? Then disable the miner in gein.toml and try again. Maybe
check build.md for any extras how to avoid mining plugins. Mining plugins
will be for GPU and not for Intel CPU processors soon anyway, so don't
worry about mining. You can participate in building up grin anyway! ;)

**Comment by heunglee** [comment]
The server starts and syncs without miner. And having other issues during syncing. So my server has not been able to sync completely yet. But I kind of verified that macbook pro mid 2009 is limited to run the server node fully so far :-)

**Comment by heunglee** [comment]
This issue was not reproduced in iMac late 2013. So this issue was very specific to old mackbook pro like mid 2009. So it is recommended to avoid macbook pro late 2009 for grin servers.
