### ISSUE TITLE
defunct peers are are never tried again

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#437]
Scenario -

1) node running on laptop, mix of healthy and defunct peers -
```
Dec 06 09:44:19.198 DEBG monitoring_peers: 4 / 8 / 279
Dec 06 09:44:19.200 DEBG monitoring_peers: all - 279, healthy - 144, banned - 0, defunct - 135
```

2) kill wifi connection, start seeing timeouts, peers flagged as defunct - 
```
...
Dec 06 09:46:59.198 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:46:59.200 DEBG monitoring_peers: all - 279, healthy - 32, banned - 0, defunct - 247
Dec 06 09:47:09.197 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:47:09.199 DEBG monitoring_peers: all - 279, healthy - 24, banned - 0, defunct - 255
Dec 06 09:47:19.197 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:47:19.199 DEBG monitoring_peers: all - 279, healthy - 16, banned - 0, defunct - 263
Dec 06 09:47:29.197 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:47:29.199 DEBG monitoring_peers: all - 279, healthy - 8, banned - 0, defunct - 271
Dec 06 09:47:39.200 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:47:39.202 DEBG monitoring_peers: all - 279, healthy - 0, banned - 0, defunct - 279
Dec 06 09:47:49.202 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:47:49.205 DEBG monitoring_peers: all - 279, healthy - 0, banned - 0, defunct - 279
```

3) turn wifi back on, node does not try to connect to any defunct peers - 
```
Dec 06 09:50:29.198 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:50:29.201 DEBG monitoring_peers: all - 279, healthy - 0, banned - 0, defunct - 279
Dec 06 09:50:39.197 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:50:39.199 DEBG monitoring_peers: all - 279, healthy - 0, banned - 0, defunct - 279
Dec 06 09:50:49.197 DEBG monitoring_peers: 0 / 0 / 279
Dec 06 09:50:49.198 DEBG monitoring_peers: all - 279, healthy - 0, banned - 0, defunct - 279
```

4) restart grin, node attempts to connect to *some* defunct peers - 
```
Dec 06 09:54:17.336 DEBG monitoring_peers: 3 / 3 / 279
Dec 06 09:54:17.338 DEBG monitoring_peers: all - 279, healthy - 3, banned - 0, defunct - 276
Dec 06 09:54:27.335 DEBG monitoring_peers: 3 / 3 / 279
Dec 06 09:54:27.336 DEBG monitoring_peers: all - 279, healthy - 3, banned - 0, defunct - 276
Dec 06 09:54:37.336 DEBG monitoring_peers: 3 / 3 / 279
Dec 06 09:54:37.338 DEBG monitoring_peers: all - 279, healthy - 3, banned - 0, defunct - 276
```

But we are below the desired number of connected peers (8).
And for some reason we are not attempting to (re)connect to enough peers in this state.
We stay stuck with 3 connected peers, those 3 are marked healthy, but all other peers are still defunct (and will not be tried).

**Comment by antiochp** [comment]
Related - we store peers in the db as healthy/banned/defunct.
But we have no way of knowing if a "healthy" peer is actually accessible if we were to initiate a connection. 
It could be healthy but behind a NAT.
So on restart we find some healthy peers and try and make connections - but it is very likely that some (if not the majority) of our healthy nodes are not actually accessible.
And conversely - when we restarted the peers dropped the connections and flagged us as `defunct`. So they won't ever try reconnecting...

I wonder if we need to store some additional info to indicate if a peer is accessible or not.
And use a combination of healthy and accessible flags when attempting to peer with them?

**Comment by ignopeverell** [comment]
I don't think we can make a difference between a peer that's healthy and accessible. First time the peer connects to us, marking it as healthy is fine. Second if we try to connect, who knows if it's offline or behind NAT? And how knows whether port forwarding will get configured eventually or not?

But I do think that we should give peers more than one chance, especially when we're running short. Maybe have some unreachable counter of some sort? And try again as long as the counter is low enough?

**Comment by ignopeverell** [comment]
Also filed #439 while I was thinking about it. And we may want a "last issue" timestamp for both issues.

**Comment by antiochp** [comment]
Yeah I'm still trying to get my head around this...
A concern here is we try connecting to 8 peers at a time, each with a 5s timeout.
For approx 250 peers this is going to take around 2.5 mins just to try them all.

**Comment by antiochp** [comment]
Then if we add a counter (say 3 attempts) then we're heading toward 10 mins to connect to some peers.

**Comment by antiochp** [comment]
What would be the downside to optimistically trying to "over connect" to too many peers? And if we end up with more than 8 successful peer connections closing some of them?
Is there an upper bound on the number of tcp connections we can/should be making?

**Comment by ignopeverell** [comment]
As the network grows, we'll quickly end up with thousands of defunct peers. Trying each one every time before finding some of the "better" ones will take quite some time...

**Comment by heunglee** [comment]
Is it a possible way to add a plugin periodically trying reconnect some defunct peers in db based on the number of attempts?. Less attempts are likely more stable peer. (I am not sure this is valid statement though.) Picking few (like 10) defunct peers at a time based on least attempted, and try to reconnect. If connected, connected peers removed from defunct db.

**Comment by antiochp** [comment]
I think @ignopeverell suggested something along those lines on gitter (in terms of bucketing different "categories" of peers) - there's a lot of complexity buried in there.

**Comment by antiochp** [comment]
See #445 for some investigation and some possible avenues to experiment further.
