### ISSUE TITLE
Compile issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by timtt** [mimblewimble/grin#443]
I followed all instructions and the two potential workaround which both did not fix this compile error:

`Compiling bitflags v1.0.1
error: expected ident, found #
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                             #[allow(deprecated)]
    |                             ^
    | 
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | bitflags! {
    | - in this macro invocation

error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
error: build failed`

**Comment by ignopeverell** [comment]
Did you install Rust through rustup or aptitude? We need a more recent version of Rust than what's distributed with Ubuntu.

**Comment by kallewoof** [comment]
Different user, same issue (lubuntu 17.04 though).

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
$ rustc --version
rustc 1.17.0
$ cargo --version
cargo 0.18.0
```

**Comment by ignopeverell** [comment]
Yes, uninstall the package and use [rustup](http://rustup.rs)

**Comment by sesam** [comment]
ping @timtt please check if your `rustc --version` is [at least 1.21, and cmake at least ...](docs/build.md)

**Comment by timtt** [comment]
@sesam Sorry for slow reply. Yup, that was it. Node running ok now. Thanks.
