### ISSUE TITLE
1s interval is too fast for body_sync

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#447]
We are not waiting long enough to allow time for peers to respond and us to actually process the blocks before going off and (re)requesting a new set of blocks.

We should increase the time we sleep between iterations (5s or 10s)?
But - we should ask for more blocks at a time (50 at a time, more?)
And - we should increase the orphan limit (increase from 20 to 50?)

So proposal - we request 50 blocks every 5s (currently 10 blocks every 1s).
And an orphan limit of 50 should cover any out of order block responses.

**Comment by ignopeverell** [comment]
Sounds good to me.

As a side note, picking constants is such a pain. I wish we could rely on a genetic algorithm to select the best ranges over thousands of runs. But the current network is just to small and fickle to allow this. Just something to keep in mind when we have a larger network.
