### ISSUE TITLE
consider calling broadcast_block for orphans

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#452]
Currently we only call `broadcast_block` if we successfully accept a block.

If the network is poorly connected I wonder if suppressing broadcast for apparent orphans ends up being a bottleneck.
Having a hard time actually describing this - but if only 1 or 2 nodes handle blocks successfully and other nodes see them as orphans the 2 nodes end up being a bottleneck and everything else has to wait to (re)sync.

**Comment by antiochp** [comment]
I guess when a node does manage to process the ex-orphan after `check_orphans()` then _all_ blocks that just got processed get broadcast out.
So maybe this is less of an issue than I'm thinking.

**Comment by ignopeverell** [comment]
Yes. And we have more to lose by doing so, because we can only partially validate orphans. So this would open us to amplification attacks when feeding us one orphan, which wouldn't need to be fully valid and therefore would be cheaper to build, leads us to sending to all our peers.

**Comment by antiochp** [comment]
Closing - good reasons not to do this.
