### ISSUE TITLE
ERRO slog-async: logger dropped messages due to channel overflow, count: 7

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#458]
Soon after starting grin server run, I got ~90 seconds worth of logger errors, like the one in this issue's title.
This could be avoided by having less verbose (bytes) log lines and/or less of them.

It looks like this was triggered after increasing the aggressiveness in connecting to peers. I'll try to make related log calls less verbose. Candidates:

> DEBG connect_and_req: err - Connection(Error { repr: Custom(Custom { kind: TimedOut, error: StringError("the future timed out") }) }), 83.162.208.57:13414, flagging as defunct
> DEBG saving peer to store PeerData { addr: V4(83.162.208.57:13414), capabilities: , user_agent: "", flags: Defunct }
> DEBG with_timeout: ok but nested - () (treating this as timeout)

**Comment by kargakis** [comment]
Seeing this too

**Comment by antiochp** [comment]
Not sure this in itself is necessarily a problem?
Shorter log messagea are probably desirable - but right now I'd argue we want to be logging as much as possible to track down the sync issues.
That said - logs are not hugely useful if slog is dropping them...
