### ISSUE TITLE
Wish: some IPv6 seed node, to be included in the list of initial seeds

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#461]
Maybe there would be more nodes reachable seemingly without being NATed if they were announcing their IPv6 addresses, for those that have one. One can always hope.

**Comment by ignopeverell** [comment]
Would that help? Even with IPv6 devices behind a home/office router still won't have a publicly routable IP.

**Comment by sesam** [comment]
Short: Probably easily tested, since grin seems to be IPv6 compatible.

Long: Probably. When torrent users complained to ISPs about being NATed up to 30 users behind one IPv4 and ran out of ports to open (and no error messages or possible workarounds), ISPs gave users free IPv6 that are transparently NATed and for all purposes function as open to internet adresses, just with a fair bit more latency. Also https://en.wikipedia.org/wiki/IPv4_address_exhaustion

I don't have any IPv6 capable server available.
Existing seeds probably already have IPv6 adresses (ipconfig) 
Or if <1GB RAM + some swap is ok, I could get a VPS with IPv6 preconfigured for $15-20/year
- https://lowendbox.com/blog/ionswitch-ssd-kvm-from-15year-seattle-wa/ 
- https://lowendbox.com/blog/hostus-new-ams-location-exclusive-kvm-promotion/

**Comment by yeastplume** [comment]
Don't see a pressing need for this, can re-open if it comes up later.
