### ISSUE TITLE
Error validating mined block - InvalidBlockTime

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#462]
iMac late 2013

Had error 3 times.

The trace is:
Dec 10 19:51:05.682 INFO (Server ID: Port 13414) Found valid proof of work, adding block ab3c4c00.
Dec 10 19:51:05.682 DEBG pipe: process_block ab3c4c00 at 21416 with 0 inputs and 1 outputs.
Dec 10 19:51:05.683 DEBG pipe: validate_header cuckoo size 16
Dec 10 19:51:05.683 INFO Rejected block ab3c4c00 at 21416: InvalidBlockTime
Dec 10 19:51:05.683 ERRO (Server ID: Port 13414) Error validating mined block: InvalidBlockTime

Block segment of trouble is:
Dec 10 19:49:51.256 TRCE Block: Block { header: BlockHeader { version: 1, height: 21416, previous: da403c93, timestamp: Tm { tm_sec: 49, tm_min: 49, tm_hour: 3, tm_mday: 11, tm_mon: 11, tm_year: 117, tm_wday: 1, tm_yday: 344, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 }, utxo_root: 00000000, range_proof_root: 00000000, kernel_root: 00000000, nonce: 9673201435111735137, pow: Cuckoo(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0), difficulty: Difficulty { num: 272 }, total_difficulty: Difficulty { num: 141858625 } },

**Comment by jaspervdm** [comment]
I have a mid 2014 macbook pro running el capitan, and I managed to mine a valid block
```
Dec 17 15:32:25.400 INFO (Server ID: Port 13414) Found valid proof of work, adding block 8116c22e.
Dec 17 15:32:25.400 DEBG pipe: process_block 8116c22e at 21374 with 0 inputs and 1 outputs.
Dec 17 15:32:25.401 DEBG pipe: validate_header cuckoo size 16
Dec 17 15:32:25.405 DEBG Starting new sumtree extension.
Dec 17 15:32:25.466 DEBG pipe: proces_block 8116c22e at 21374 is valid, save and append.
Dec 17 15:32:25.468 INFO Updated head to 8116c22e at 21374.
```

**Comment by ignopeverell** [comment]
This would arise with a clock issue. Did the time printed look correct? Does that happen systematically?

**Comment by heunglee** [comment]
The time printed is correct. I checked the system clock at the time. The system clock (local time and timezone) was correct compared with my smartphone. I am not sure what you mean by "systematically."

As seen in log, 

Dec 10 19:49:51.256 TRCE Block: Block { header: BlockHeader { version: 1, height: 21416, previous: da403c93, timestamp: Tm { tm_sec: 49, tm_min: 49, tm_hour: 3, tm_mday: 11, tm_mon: 11, tm_year: 117, tm_wday: 1, tm_yday: 344, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 },

Log date and time is 12/10/17 at 19:49:51 PST which is 12/11/17 at 03:49:49 UTC. So the timestamps of log and block header almost the same.

Based on the code segment, if time lapse is within duration of the following 12 blocks, the block header is valid in terms of time lapse.

	if header.timestamp
		> time::now_utc() + time::Duration::seconds(12 * (consensus::BLOCK_TIME_SEC as i64))
	{
		// refuse blocks more than 12 blocks intervals in future (as in bitcoin)
		// TODO add warning in p2p code if local time is too different from peers
		return Err(Error::InvalidBlockTime);
	}

The time lapse between creating a block and finding cuckoo solution was less than 2 mins. So the condition check in if statement should be true. But for some reason, it was false.

I have not reproduced this issue with the same computer since then.

**Comment by heunglee** [comment]
@dbancajas encountered:

Jan 18 17:17:33.445 ERRO (Server ID: Port 13414) Error validating mined block: InvalidBlockTime
thread 'miner' panicked at 'called Result::unwrap() on an Err value: StatsError("Error retrieving stats from plugin: ErrorImpl { code: Message(\"invalid value: integer -1581233150, expected u64\"), line: 1, column: 144 }")', /checkout/src/libcore/result.rs:906:4
note: Run with RUST_BACKTRACE=1 for a backtrace.

Jan 18 17:17:33.445 ERRO (Server ID: Port 13414) Error validating mined block: InvalidBlockTime
Jan 18 17:17:33.445 DEBG resetting key_id in miner to None
Jan 18 17:17:33.445 DEBG in miner loop...
Jan 18 17:17:33.445 TRCE key_id: None
Jan 18 17:17:33.540 DEBG block_fees here: BlockFees { fees: 0, height: 34541, key_id: Some(Identifier(3cd7894b91dc07ec0608)) }
Jan 18 17:17:33.540 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 482
Jan 18 17:17:33.564 TRCE Block: Block { header: BlockHeader { version: 1, height: 34541, previous: 04bfc207, timestamp: Tm { tm_sec: 33, tm_min: 17, tm_hour: 0, tm_mday: 19, tm_mon: 0, tm_year: 118, tm_wday: 5, tm_yday: 18, tm_isdst: 0,
Jan 18 17:17:33.564 DEBG Starting new sumtree extension.
Jan 18 17:17:33.564 DEBG chain_store: get_output_pos: Commitment(09d3798b340ad83ea8df7de85b9be7c343fade2a35f347dd11bfa088d0780296f4), Err(NotFoundErr)
Jan 18 17:17:33.564 DEBG sumtree: get_output_pos (idx): Commitment(09d3798b340ad83ea8df7de85b9be7c343fade2a35f347dd11bfa088d0780296f4), Err(NotFoundErr)
Jan 18 17:17:33.564 TRCE Hashing with additional data
Jan 18 17:17:33.564 DEBG chain_store: get_kernel_pos: Commitment(090f4143ad78389773275c1ff6d944d05cc7a6dac81137f449a14801f8139e5f37), Err(NotFoundErr)
Jan 18 17:17:33.564 DEBG sumtree: get_kernel_pos (idx): Commitment(090f4143ad78389773275c1ff6d944d05cc7a6dac81137f449a14801f8139e5f37), Err(NotFoundErr)
Jan 18 17:17:33.566 DEBG Rollbacking sumtree extension.
Jan 18 17:17:33.566 DEBG Sumtree extension done.

**Comment by yeastplume** [comment]
Ancient T1 code, likely no longer relevant.
