### ISSUE TITLE
grin commands could be started by a small daemon program that restarts the process after a crash

### ISSUE THREAD

**Issue by kingsley-shacklebolt** [mimblewimble/grin#463]
I've just been thinking about the crash I experienced here: #456. I was a little disappointed when I looked at my terminal and realized that the server hadn't been running for a couple of hours. When the mainnet is launched, I would be *really* disappointed if I checked a miner and realized that it had crashed 2 weeks ago.

I think it would be a good idea to include a small daemon program that monitors the `grin wallet` and `grin server` commands, and restarts the processes if they ever crash. The daemon would also
handle `^C` and stop the process. I know that most operating systems already have ways to set this up, but it would be great if this could happen out of the box with zero configuration. And it should only be a few lines of code in Rust. 

It might even be easy to write a formal proof with Coq that proves that the daemon will never crash, it will always restart a crashed process, and that `^C` will stop the process and the daemon. I've been wanting to play with Coq for a while. (Double entendre was not intentional.)

**Comment by kargakis** [comment]
Not sure whether this is an issue with `grin`. Maybe start a discussion in the mailing list?

**Comment by yeastplume** [comment]
This is definitely better left as an exercise for the user, and is trivially easy to set up in bash if desired. If something is crashing within grin then we need to address the cause of the crash. I would fear that providing something like this would just paper over issues and make users less likely to report them.

**Comment by sesam** [comment]
I'd vote for PRs welcome for a feature that would capture the grin.log of a crash and send to (configuration.admin_email), then restart server and wallet. Maybe opt-in to crashlytics that helps with debugging. We'll never have a fully bugfree grin, and capturing bugs in a more automatic manner could be good for the project, as well as for community happiness.

**Comment by kingsley-shacklebolt** [comment]
Oh yeah, crash report emails or an error reporting service would be great.

I'm going off on a tangent here, but a bug-free grin would be awesome! Formal verification could be used for the critical code paths. I've always been fascinated with the idea of "perfect code". I know it's very difficult, but it would definitely be worthwhile for a digital currency. Especially an anonymous one where no-one would even know that there was a bug. The proofs could be completely bullet-proof, but that doesn't mean anything if there's a bug in server that messes up the verification.

Anyway, closing this for now. Will move all future discussions to the mailing list.
