### ISSUE TITLE
After entering   ~ / grin $ grin help    write command not found

### ISSUE THREAD

**Issue by gandalf12345** [mimblewimble/grin#469]
After command cargo build write warning: method is never used: `delete_peer`
   --> p2p/src/store.rs:112:2
    |
112 |  pub fn delete_peer(&self, peer_addr: SocketAddr) -> Result<(), Error> {
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

   Compiling grin_pool v0.1.0 (file:///home/ivan/grin/pool)
warning: struct is never used: `NoopAdapter`
   --> pool/src/types.rs:181:1
    |
181 | pub struct NoopAdapter {}
    | ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default 
Compiling grin_api v0.1.0 (file:///home/ivan/grin/api)
   Compiling grin_wallet v0.1.0 (file:///home/ivan/grin/wallet)
   Compiling grin_grin v0.1.0 (file:///home/ivan/grin/grin)
   Compiling grin_config v0.1.0 (file:///home/ivan/grin/config)
   Compiling grin v0.1.0 (file:///home/ivan/grin)
warning: unused import: `wallet::WalletConfig`
  --> src/bin/grin.rs:43:5
   |
43 | use wallet::WalletConfig;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 556.28 secs

After entering   ~ / grin $ grin help    write command not found
Help me, please

**Comment by jaspervdm** [comment]
Did you add `grin/target/debug` to your `PATH`?

**Comment by gandalf12345** [comment]
I entered the command    export PATH  = / path / to / grin / dir / target / debug: $ PATH , as written in "Grin - Build, Configuration, and Running"

**Comment by sesam** [comment]
@gandalf12345 you need less spaces in there. Please come to https://gitter.im/grin_community/Lobby and we can help you faster - more people are there and able to help than in here.
