### ISSUE TITLE
standardise how we print hashes, diff@height, currency unit, etc

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#492]
General tracking bug for making grin outputs easier to understand. Avoid conflicting with any [multihash](https://github.com/multiformats/multihash)

 - blocks
   - [ ] show a block's hash as 𝓑ece5caad
   - [ ] show height as 17389𝓗
 - difficulty
   - [ ] total difficulty 142700388𝕯 and let numbers be in front of symbol, so parse (parseInt/to_int) might work also on such formatted strings.
   - [ ] diff delta for a block 401≜ or 401⍙ [delta symbols](https://unicode-search.net/unicode-namesearch.pl?term=DELTA) or maybe just anything distinct enough without a specific meaning, like Ͱ ψ ϟ ϡ ф 
 - outputs
   - [ ] show an output hash as Ⓞ ece5caadb10627f9f3d0d580013b7de8c105714ab9d14f8150288b00d0932306
   - [ ] online we can squish the middle part of long hashes like many block explorers do with css colored rectangles

 - Make a select few clickable
   (echo in front so you can easily copy&paste in a terminal and verify that it becomes a clickable link -- all below seem ok for iTerm@MacOS)
   - [ ] echo http://0:13413?𝕯142700388
   - [ ] echo http://0:13413?𝓑ece5caad
   - [ ] echo http://0:13413?𝓗17389
   - [ ] echo http://0:13413?Ⓞece5caadb10627f9f3d0d580013b7de8c105714ab9d14f8150288b00d0932306
 - grin currency unit? 
   - I like 𝔾 𝒢 Ġ, 😁  or [other G:s] (https://www.compart.com/en/unicode/based/U+0047)
   - or 😬  for still locked grins 😁   for Unspent
   - or 𝔾50 for a still locked; and Unspent as 𝐆50 𝙂50 G50 Ｇ50 𝒢50 Ḡ50 𝓖50

**Comment by yeastplume** [comment]
don't think this is necessary at present.
