### ISSUE TITLE
Add INFO logging for Connection Lost and Connection Re-established to wallet server

### ISSUE THREAD

**Issue by lukevmorris** [mimblewimble/grin#493]
Steps:
1. `grin wallet -e listen`
1. `grin server -m run`
1. Ctrl-C wallet process
1. Eventually see the following in the server log:

```
Dec 14 13:25:34.759 ERRO Failed to get coinbase via wallet API (will retry)...
```

5. `grin wallet -e listen`

You can tell that the connection is reestablished by a lack of the above error output. But it might be good to log a confirmation that the server was able to reestablish a connection with the wallet server. Additionally it might be useful to see log output for the connection being lost.

**Comment by pjoz** [comment]
Raised PR https://github.com/mimblewimble/grin/pull/538 as a candidate to address this.

**Comment by dbancajas** [comment]
What's the status of this? Just studied some rust material and am looking for something easy.

**Comment by sesam** [comment]
@dbancajas See the comments in #538? Please go ahead and make another PR, and in your PR add on a separate line: Closes #538

@pjoz If you find time for grin again we'd be happy to have you back - just ask me or anyone on the gitter chat to find something nice to work on :). Have a nice day!

**Comment by dbancajas** [comment]
@sesam  I had a question over on #538

**Comment by dbancajas** [comment]
made a PR #662 for this issue.
