### ISSUE TITLE
Mining Loop should automatically restart after waking computer

### ISSUE THREAD

**Issue by lukevmorris** [mimblewimble/grin#494]
I noticed the following behavior this morning:

• was mining all day yesterday, generated 6200 grin
• closed my laptop with wallet and server processes still running
• opened laptop this morning and verified both processes still running
• watched as the server process automatically synced to the most recent block (verified with grinscan)
• no mining rewards for the next 3 hours
• restarted server process and 2 blocks found in first 5 min, with no change in difficulty

When I restarted the server, I noticed in the log that the mining loop was explicitly started. Perhaps when I closed my laptop last night the mining loop was interrupted and it never restarted?

It was also mentioned in gitter that this may be due to the following:

it's possible some sockets between wallet and server got timed out and closed but are in some try-catch block where it doesn't terminate the process but instead stops mining rewards?

Let me know if I can provide any more information.

**Comment by nick-f925** [comment]
I have a similar issue, but with a desktop and it did not hibernate or sleep or anything like that.  I left the wallet and grin running, and it would successfully mine a block approx. every 20-30 minutes, then stopped finding proofs for ~4 hours even though difficult in that time lowered from 620 to 420, and "in miner loop.." and "Graphs per second" kept getting logged.

**Comment by yeastplume** [comment]
All of this logic has been moved to grin-miner, so please feel free to report this there if this is still an issue.
