### ISSUE TITLE
make grin (the community) more accessible to new users

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#496]
Ideas:
 - Add other chat functionality than the current gitter chat that requires a github login
  - XMPP chats like [prosody-webclient](https://github.com/sesam/prosody-webclient) - easy to integrate on grin-tech.net etc. But prosody is lua-lang. If there's a rust-based chat system, we could pick that instead to try to lure in ⛳️  more rust hackers into grin
 - blogs
 - podcasts
 - non-technical mailing list?
 - facebook group
 - once there's more people to keep things alive, maybe riseup or similar community / forum. The discourse software is very friendly and invites people to become part, see "Looks like you're enjoying this place, come on in" (paraphrased) if you [scroll down a little bit over here](https://forum.queal.com/t/welcome-to-queal/8)

**Comment by 0xb100d** [comment]
no, why?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by kargakis** [comment]
* make the mailing list more accessible (expectation is that I just use my email to subscribe)

**Comment by sesam** [comment]
@kargakis I feel your pain. There might be points about infrastructure costs, anonymity support etc. Not sure if Ubuntu/Launchpad is better or worse on those points than just any other mail list system. Having it hosted and spam-checked by some 3rd party has advantages, but if you know of a good replacement, it's better to make such a migration earlier than later. 

<rant>I'm not much of a maillist guy - the few lists I manage are basically just nagging me with daily "pls moderate this message" and on a quick glance I see it's badly spelled phishing attempts aimed at older non english speakers, maybe to nab some of their pension money.</rant>

**Comment by sesam** [comment]
An attempt at a more user friendly format than the current grin-tech website: https://sesam.github.io/grin-pages/
Note that the imagined ~~`grin welcome`~~ command do not yet exist. Ideas welcome here: https://etherpad.wikimedia.org/p/grin-welcome

**Comment by kargakis** [comment]
@sesam looks good (!) although I would prefer the header typeface (font family of "Get grin", "Create a grin miner", etc) to be something more minimal than the current one.

**Comment by sesam** [comment]
Now that we have a forum, and we've succeeded to mainly gather a testnet-aware crowd, the points suggested have the wrong timing, and some other issues are tracking specific things.

Any changes on how the maillist works might be more relevant on the maillist + with anyone who had trouble getting signed up to the maillist.
