### ISSUE TITLE
grin restarts can corrupt disk data

### ISSUE THREAD

**Issue by nick-f925** [mimblewimble/grin#502]
Empirically, I've seen about a 1/7 chance that the local disk data is corrupted when restarting grin during syncs.  (I've been doing that to make backups while doing the sync process, essentially ctrl+C grin, then cp .grin directory, then restart grin).  Out of 21 restarts, 3 led to "InvalidRoot" errors when fetching the next block from the network, presumably because the head block on local disk was only partially written or otherwise corrupted.

Can grin have a SIGINT/SIGTERM handler to gracefully shutdown and not leave partially written data?  ('grin server stop' can tie into this by fetching the pid from an API call (new function), and sending a SIGTERM signal to that pid).

Additionally, can some checkpointing size be written?  It can be fairly simple, like after writing the complete block, then update some counter that points to this newly completed block.  Upon restart, if the counter is not pointing to the end, truncate the file down to what the counter points at.

**Comment by ignopeverell** [comment]
Tracking this under #536
