### ISSUE TITLE
Unspendable funds

### ISSUE THREAD

**Issue by beniamino38** [mimblewimble/grin#504]
I have funds in wallet which can't be spent because they produce a panic in the receiving wallet. Steps to reproduce:
```
$ echo -n 98a3e80be5fa9f54fbbbb7a978ad611cf975e431e0c8218c40122edb8925ba45 > wallet.seed
$ grin wallet restore
$ grin wallet info
Dec 16 11:29:51.626 DEBG Using wallet seed file at: ./wallet.seed
Dec 16 11:29:51.689 DEBG Refreshing wallet outputs
Dec 16 11:29:51.733 INFO Acquiring wallet lock ...
Dec 16 11:29:51.734 DEBG Attempting to acquire wallet lock
Dec 16 11:29:51.740 INFO ... released wallet lock

Wallet Summary Info - Block Height: 19759
--------------------------
 Total                            | 297.000000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 100.000000000 
 Currently Spendable              | 197.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 

$ grin wallet send 1 -d "http://$DEST:13415"
```
In the receiving wallet, this produces:
```
[ubuntu@hivefaucet wallet] $ RUST_BACKTRACE=1 ../target/debug/grin wallet -e listen
Dec 16 08:30:17.596 DEBG Using wallet seed file at: ./wallet.seed
Dec 16 08:30:17.683 INFO Starting the Grin wallet receiving daemon at 0.0.0.0:13415...
Dec 16 08:30:21.473 INFO Acquiring wallet lock ...
Dec 16 08:30:21.474 DEBG Attempting to acquire wallet lock
Dec 16 08:30:21.488 INFO ... released wallet lock
Dec 16 08:30:21.984 DEBG Received txn and built output - Identifier(d6119647e39ae96c259a), Identifier(0eaa9be667321b9941af), 53
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Error processing partial transaction: Node(Internal(\"Server error.\"))")', /checkout/src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: <grin_wallet::receiver::WalletReceiver as iron::middleware::Handler>::handle
             at wallet/src/receiver.rs:80
  12: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  13: router::router::Router::handle_method
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:199
  14: <router::router::Router as iron::middleware::Handler>::handle
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:212
  15: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  16: <mount::mount::Mount as iron::middleware::Handler>::handle
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/mount-0.3.0/src/mount.rs:122
  17: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
  18: <hyper::server::Worker<H>>::keep_alive_loop
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:337
  19: <hyper::server::Worker<H>>::handle_connection
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:283
  20: hyper::server::handle::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:242
  21: hyper::server::listener::spawn_with::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/listener.rs:50
```

**Comment by beniamino38** [comment]
More backtrace at https://pastebin.com/As5z3x8M

**Comment by beniamino38** [comment]
This seems to be one of the problematic outputs:
```
    "7de5fe0e935336fd092a": {
      "root_key_id": "ec8d8f1cdcbd2ea70dcb",
      "key_id": "7de5fe0e935336fd092a",
      "n_child": 223,
      "value": 49000000000,
      "status": "Unspent",
      "height": 17435,
      "lock_height": 0,
      "is_coinbase": false
    }
```

**Comment by sesam** [comment]
Also thank you for the output from https://pastebin.com/As5z3x8M

ERRO Problematic partial tx, looks like this: PartialTx { amount: 1000000000, blind_sum: "1395285ca7fbd81caed3be219cfac2eba167bec2e0c8985f5853b290e2a04e98", tx: "00000000000f42400000000000004daf00000000000000473045022100e5f92efdab3fabc0ffec3f3c8b5e131bf4c57b1bce9e4ce294f2f94c5bc13b8c02205a348da54a20e6d249334dffa531e084589fe61f68a08f47f998af033c5fc055000000000000000e000000000000000108799b48af15b253d4f33f502ec84d8e3a1f9e84c3f7e4b230171dc58cf38fc8d508081f4836d564c9d1af79fa4a41f4b7c52a0fc05f4bc60f848dffcbc727a37c8808edc452d5ee4ab62280684dc55154737e9733605a6f139ff1ea47ffea9bab1446084efcd5b3b9a513b04073d6e4caaf94b3d87be144b5d017c790acf01dcbb532aa08dd6ec1a02bb6f4e8ff0eaf340ca182514d9202cced93794f073741826a6de7580865bccc91f8aca2984f86b56cf5ac86d90a0a91c17380b031c93dc48596f9aeaf083d590a81cee77ba2a566f1d6d0797b9356af0774aa676df087137220305a1a65091609ada4143897bbe4f96f9514b5a71116c85cc23fe1c581f6011d99623fec3608400c269bcbf1717aa0867381ae468b0b76104336cbf7cd0c073bafee3454dc7609bf21172105d52811f5747331c5d657fabdd7571961706815c3f560a0bc3ab5ad09e9455f35f8d5a057655ba5ef04e9248771848e3d70168d5e0562a1d975337e9a09f060b5c316ba86342abe2902f58d94a8a171f12566b0044fc50a974705044b210904bfbd464fc51ee55a09ad4a12810dc0f6d168181f17e96ef6f264f91ee7301d0991cfdc5e157b99d86f1ad1c5d297c04f9dece61fc7444f6d4f6ddb188d0479b10008fbf003fbcfdab73a5c18e8988aaba1e15bd7e96545e9382a26c12972f72face1ef7ed50e1447ef8f40cea62f32ed23c0042a85e00000000000001406403f61fda517e8348cec8a9c98494c840ff7d2b9e0e1cb50651ddf6bdff4569797bd663216185fa8416caa66f53fdc4dc7587f3e139fc708149e81eeca083d5c8ca556ec7b995d6329971c10143925c8a53f43063ae818f6dc4b7e00b2c5301620b7c46b52feb9044545a22bd0d57c3cd4f7565e5336d43b725d7cc88c1a64bbe4dc5b8d5810c512b543fda2ca86094940d94ca1709abfa8dc56557e1bd722e5a39359218024a8a1767048c8e7343822d7ff1c8cfda7f9b386cbff489e0ed4db5b9d34a94ddaa447910ea63e3fde9eaf20c168c5df7ec17f974a64493a2718cd26ccf55ee7a331a87d0d20d74cbfd5cd6aa615c98eaa38338fff8ab513751b5d32819b2104b336b02cb0c6a39c96e19540ce307f57898c9bfd897989e69f72a6b3a8c0bb49880b5a1476254ba7a14b614be30dd8c8093f90784dfa96d79e0744ba41c2e062485a34fc910d3ca1e206cea853890babeff9dc9269d53f7ff40354a193a17ef9918e84f31436242844b32eae20043476b9513c64f8a32adaee123bffef24d4d37dd774affc25d47294851b2ac3e6ca0ce0531f3d0fcd05e5e9c74cef4ddd59e4d3d0bafa40e53012c9060dd7c68bcd5fe9bbf96ac0064145f1f5482d5e2f0b88678266c965439ef0c02f737fec6e4ff8031e4d7425944b0982cb9309d8b4437fe85336daa9d1eb06c2db4e41b15defd53161685be4f10d115b28bf8d9641e4876e82afb081d49e0b502a615709e35f46112aa3750a30addecfdca689ec346050d83791768ea90ff92779ba683aec45f4dcba0369e9b3ba12e5cf930eabe1898f703b745b1495eedf54294b40ccdc864bd6add4e5b5884a5ac1af3b700d55ee48082d1f8ab1305efa47ed615c00a98bd9dc03e62f1f1f3421c0592084e11ddcb41eee46c53feb64f6eb8695ac20dec84222e362fa119db58a0c243854fc7cc4147936f0eef4c16bc9581351344730c4590d4160aa4631fc9c68db39059256c433ae3f2b8827e9168c3e87f9e35a835ec4cf6e11192ebe51957ae8aa43ddbcbf3eb8792da7c3f9b9254dff8eb97bbe6ae440f308823ef2007c51d5c4d39d71b3f7fcfd07fa6be53bd941b8dad3b42fe8b0f877941ced0013016c60b98f2259f52bd07325dff7eedf993b76613ba741e96ed284cc5235a10ed2ec8cadd58f70a58c08c25aae12f6287e61d66b0eb85f4f5951b96d95885abbc66a1ded0347aa2abbc2fe6cef634a862867282593eee720f3c07b8150bec4ce2a95eaa94b4dbf12692c4a8baaf1addc27dc885adf36bc4de8ff16ab1e4532c1e257c8ce8470dbbe0a69f1b0841579dcdc569c1a11ddb03b2be6e4e565ad06fc66bfcba6cfa0aa54194d684d8a3729c7413c9afe89c42dca342e26de8251c51b6b243ba2ef08ce302b8c92d83cc96bb5aef9b7f6beb84c99569752823067553c080a298ce3d1782143933abda216f4a78c116f562fe773dc80574bc10c2c0d0de59255b9e37492b793569f53bb261eaf338e0fc1501b76b64241591c89488faa4bef246e0a7eba4960f6f737eece16d6407cc017802176d9be84b2fbef8a6a96011638f9685180ca8a7600c5e491db19e8e74354509d74c1fca53023c373e13dc8e60c396f82570ec80168ad195226592d80b8ea3bf85424c3002e1256fe0277f53a29be15bd968e9aa8b6c9c2d877927cf89a3641127cdf92b7bdacc813d9e20831c898a06eb942b7f26470aa8309e48d3eefd39029fd0b3aa9b33de0866741c999bf0babd6baa6ef61595ca40ea88854ee9c860da02d6307d93a26b8f85118c8e176700175c9fb2472999fcdbe98e71d2fa7a29ca41b0c564e138e550053276f84d5c24ee23008671f404dbde3343c22fbc53771425ea951f8b4b1960103e1d7949aa92dc4b42ab698570de14c1d3f8d038dde5256eda55890463c0c4614ff2cb518c81ab5d453d733a0d0808ea19b960cce5c59de60e1e78066e9994c57d2bd7c1d78942ec7150aef37dfeafa4ea4695214dbf84ffe4bd561221ef5324e2fae58f92b4f68f67f0d4e977dac77349a538255776bcad7703694f4497aeaa7780ff8640b0309f360ad5a9cfb1f0472b14deb5d5a4796dddcdd6cfe6c79b00462838457a77b38b9a4898b6dddc2f85a9326f39134dcb2f316267730c72eeb5598dc9ebd13c2992f54be12ee3123f36cc301ac6be3d75ad38166d7f8bdc65cdaa841c88a06cb53fd8e8ddb5c9417728a883ff02f038124f3068e5cb556aa9c8691fdbbf507a052d4a7b4344dee9e0692b89b109eee88411deaa21fd3d4e6e584e5283e06d3c95d4dcfd8880d58fa38c74b2a378c2a6b439b60f61c7cce33fe303e8944239cbe800a6959ee48dd47ff4a143508359390c4c8e426817ed52049e5ff41f63e6fa3f40b23efb89cf1242a911b32ffb999ae1b095723e2142e837f7c1f53fa4fecedfdd4eff331e14b52f9c5686efe566701a54366620d58e6254b90b5a65a977116a927f8203d9ef2622605149e565f99d4d1f326c24673d17305b72b3edfa6488a3ed7cc939746c0692284e95435b0d9569dd4b94978720d93c0b6d083ba3c195384ba7766a1f1982ec14d6604ad3f7644b7536dc6b60d06b2783c06a164aae5dd201d00fff596436adf53736e765ea03123ab76467aae1dd6e9f615d7ab89b8692cd2b47c09cea4f53ba5b666e8f20e698d3c84efa7276f8cf195b718e136c65f14795f129b73e0edc02468786c6e572afb0c6540dca496600433cb51184cb5ad75aa8d0699c8ab2633975e04832526e04616cc74bf3dd0649da219a9f13732b6ae0be027e83f7bf25e4511f6f5755234430044beb9ccfb5fc25a01b55df98d3540df45e10302bf4aca372cb23c6e9b2b392c39e742950fdec9d25683300edd585a915de4a3cf12acb0b77eee9c93c3fb4d7b401d3bf2f260e245e6d9ab0b72bfa89e577711b378a3c16515b285c3afbbdc6bf32f857a086bc407a2995cde129d6c011da4544951154f82099b2a11f933df1f8b8d08cf9e8e688596750338f042c70e06583609dc325778099356c72c69cca1616ed3ef8c91d22928f2bd2f1594456d27a2789d8a569ba3c123017b7e5c93cf0ac703d71c803197227fddf5e15d1494169d55f3683ea405a58713f8b94c6ade0c56f9dfef0d23e663dd6eea7e9f917372718a985e2da8278fc291d52dc18db03110a69cf2553b8539e859789b0c3916ea40101da123cbeedb11e074f0357b8cf47dd41c201bf593ae09746c9ab45f12e615284e860bac11b93e9b4fd436a0a2d20a7f68586291acb71116f95b340406a4b450730bb67a4c2c6f5dbae9fe27bfe695a0684ef41a85b75d9bf52bb3f0ae0272aaedbe41618dba0f7eab1ea802f2dd5d75309927de79667b780bd49460254ba428a524d74dd32d9baf6768495bc8320ad521b1fa95b8c4b186b2362700e66d67eb69178d869a30ed8e2954072e94c012f82fdaaf1a760941c9ec25d834f1cc952b1609615c67edf5afcbfcbce6c3c26436ea13bb52c523d5c57c20a9dfc5c777f6c7c46586c58a0faecaef38fe2dd5912da88836fba390c181225f97468d47e21a919ef7c9a056f1c2e344eddd8988e0fe44fdf1ddfe69b2617daa91ea91d7229dd0cc24ab1a9b67ea7071de50d06381e68159feda69d50b85e343ce7e11ae4e039f2a9f4643565a0b123c9fcace1bba923a0fd6b294c587d2e185a3f3d39a40444a40c7ed3f564e3ca642cd3d549baef3606c257c339e8023f87cfaab4e3ca2f1312fa4f5db0f303e0142cd44a342c27a6a8c1887dd2c2c4629e0326664a2b00bc81a45315029fd177c4d3178cba6496211986acd5b23151de1e25d8792a00308a5506f2c41b89c413d5c95a4adcabb41cef5f9010347440627cefe17e1b25adc47b37b82d365611d4acd4107361dd27b49f9df38f0b2849daaf5cd371455a6410cf98374d327d3ddbd23878e2984a7ed48d4f28484bd0fe24a10b3a6b29ad3eb822819128c2b9acbb7abe71405468e1e70978d3ea0f743453738fda74985eec9bcd6c6a55b3b29e5e70ecf58991424dedd0211f38e5b4d39f78db2f0c7320bbe01323db56bafc9b335f262ed15beb10e1d05bd6e5cef186ac3980c94a5a67fae2fae3f4dbd61ded7e72c8b73b147071283edefe451a46e1db283ba4d3631cca6b0de3a1a48c1aae49a127c807feb847be20c0ca8d1d57f56d9bbb3a084f936ef491f5352794c3008215a727bf908bf73e4434b1be5cf5787668bacba90a112647578b5995d13fb9acf83134fa30ca2979660043ebc78f028101eb0fab99d7adf27cafa3d1f217fb34e1c1ddabc58708061d42ad484d679aa6f30f35d695a60daf0b8446168e1f8ebc235517f7f199e89523f75e7ccddb7857db69f8bb92703d0a44ed59bc8c3d283d7190746d2bb0bfcffd8730973b7d2d50fecbb6b8d8510f60d30e1f52e8d3df5ce00d8969bc73458da9762f74f548b7acefcbc846e80ffacdfc784437976a35c4869a98dcceb4db29252ffa0afa947bd7c7f9e469bcae907008760d32e633f78fca78630125d31f06b3a628501d7640391d9fc88ae1d187c3ba2ae572a067e4e5fcc22e1b187f8e8b70ec2195aa8bcf53676f493f69e6b1c593fbffd26b34d547f88f165313d8b65975a38daf25f2f186012a02219879ade2048b8c88ae4b7efbf7df1b39f48ad2dbfc9ff0bac5f7c175db06bfc5cf4ff356d4cdddd0db494f35e8d71d7479be976e0e328632d4c9fd2cf140b394ca8b2c37feb322ad93ba765fb917355a56a3dab75827b20f7b9ab01a78eccb6064469d47a39b8bc272dec10390574c07909c63d786ec1d3a2728e8891979d5402e0800e8c75c2329848bbd31f5f95959203e49a5e088d220fcce212d0a50090a09867adc0f7c1aa69e95164380fb03b0bd6c06fc806691e51b841ed4b2b7237641cb6d63d824c9a65a73aabccf9b5b17a83fc659e4da6e68edd920d3c4d7e2609ff1ced0391a267569b840dbd474dc47bbab4d5627ba2133c0890d30cde1d76adabcc06466487c58dc49fce49300b29ae903889e0e7690836fd4c4a809c4acb44bc8be37782bdd913fb5679a94a86f1cc8d716f116bcef27e172f50b2110bd29557280ab79efd1a8686ffac7a513311ec7947412cb9c947897e67e0d74c61011e16128d33a7e76ee5316552be98fa69fdf6a6bf2e61d6fdac4eaeed9a9f1bd8460d3d5e25f1c58c0c6ff8caa5ffdaa2135d745a95e795d1954c88e841194f0bc7a2df9f02dada18822c69b6ec94ebc8831f5a880f7cb46cbbbf53b970fa87e2a5286f97c4bfc402a4267cafffc88d59819962251b1e79269cc3a2c06072f1953429652f1b8e38574bd80a1d458b327e282aa8ac42e232e241da454b0f41fbcf6844c39da86ff54819df3115dae8a5a2c4377c4df6f73495bcacd6646f7e814cf5ac07a7f83becfa1c0f8cd53959ec3b0e0e6204754e61430e3a87e6c3bda98423977e7d0b2baa9c0d06fec9611936a055e47af075757cb2ad84a8c51c08ca41b2525a3c24ca34ebb0b6f9836ae8170dcd721fe597bc012149b65c5af2137629fcea437a6ad9fc9c68764010936a465ae3f02eae5946ae4d680aeae17c5d7a29d044966263e6b27a15e3d1c0e2b469ba68d69e532dcbf35dec68cc071d5ab220dafae4049ad9301db7c13ef71103ba70617dbc156e606f1562625b6b8f1a11f34007d35fd0c17c2cd29a6881796bf515778c72faaf709c8c931b1a99d88e96e73a7749ffc575a4b5dc8acfb249e90941fadef6f6792a2e2448a77cb5850f45e8693e88ec192334d25fe8820f4ae526b72f01c88d09177db9e8cf639da6d3103867bde1bb64afafb6294ca47a8764daaf3978023c9a6e727abe9a822e4e1ee171ad8f994a4c255e605d083c510967cc4032527dee7047d75280e83b7690e0625935062d41c7a6cd0115b0e62ca5692c1bd911afb6f46e0963260861f8aa83287d00d2259c52ae76a96ebd306e51392be24cdef792ddc9dbd59392ea4659693f55a9160d20f5f4ea387b5e070a924ceff78442f806d12d6d8b78f28fe965a12663cea1528ccaebd48e5a3c776301a4efe60ada636d65907b83e11ef3b09002537f2cad03f2ca6df9bbd8b274380ca5b951f20a850f4451ecb1fc17c82cbaf16d47e3a523701dc4f18e47b5364ed43a38bdc1c67e3cb697f91a029db1facf8bb7223628fe59d4f2c741e9756fc8711a91cbf34a0d67949bb9306f0185bcdec6d16f79814aa3657b6f250bd65b6b39010780670f3b4e14a3eba0519ac048252ada8beb9c67499fdf3af2657eb57ba762de764505a63cf5b9b2ac3e9177966284c54ac0efc88585cf1a4530c11218b039595a37ecc4ddf164a2ef7ba5e1d6abec6f5f2697ea012f996506b34dd3e8c89a4488dd95c5968ff5fcdf396753a3081c64f87f55b7ad45cca82c9038a7efc9e2faf54e473ce644c71a22cf336a1e62a7e7587ea481dc4e402e3df57a474d40fe0b625892af135dec7ebcc438b02f1650278a550be4894a4924ef2ecb6780b69d677a18706488ff06f8d98552941206f1bd0791c0bab6d90016b032085e7b3dcb61e01f33c194407e323ac58068adbb2a20af59d93d45554b0387882eee1d9ec51ab6ecc02f93ce51c087c99d0cbf164644f2ec469e02603926b9594df4d46d74e8621fdb29b91a3dc40ecf1bdab41ba19bfa78619587c43da211da7eae9bb25e66ba089bf6dc817dff76ea6c6ed2240e18118fbc7acb44d0f769b7665fa47d85bbc0144898bb90438071fcfdba29d0077c2323f7434f9009530e0f39ec1cabb7c87ea2c72ed38fa06cd1f9d1a7e17da885b9224389d77b7457dfff574eade35ab74daf364b4b89ede10a97cc7d07955658152c962c9e8a0fcdb901c051dc5021c6a05cc56c901bdc2c6db0f6a9f85b54a61dad220a1b1d209a4494ee54be7dc3d8fe93d5174834786c43047437e7d244e496efaec1d46d8a24f5fa663edfc425bd131887ac5621d0fb3a03b0af4724c58f81b958cedc84169b631cd0e7bac4326aa64113a71cea59afa1e279efebd37a14a299bc5e93e88efcdc1ec373b6e5477922e2640f04fadfc3e7e638de4938d59a2254af079c5ed7460610c9fb597f0417050ee01617315500eaad092ccb6327b468621f042c0cd78e409ad37a00e8778b43d92d02d5897dfb4efaf73675bfa17fc07c281af8ebdbc9f4f5a9a4b42a4e1a0e4ef2063a65bc8dc49ac6811b8fa94ba36a0e8345" }

**Comment by beniamino38** [comment]
I was convinced this was a problem with the sending wallet because transactions failed to two different receiving wallets (which both communicating with the same server). However, in fact, the problem was with the receiving server. Deleting .grin on that server and resyncing from scratch fixed the problem. I don't know how that server's .grin got corrupted -- it seemed to be running fine.

**Comment by jaspervdm** [comment]
I just experienced the same error. To add another datapoint:
```
Dec 20 00:25:22.915 DEBG Received txn and built output - Identifier(667d85a3692621a668c3), Identifier(8609a35190bb15be1ab5), 3
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal("Error processing partial transaction: Node(Internal(\"Server error.\"))")', /checkout/src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: <grin_wallet::receiver::WalletReceiver as iron::middleware::Handler>::handle
             at wallet/src/receiver.rs:80
  12: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  13: router::router::Router::handle_method
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:199
  14: <router::router::Router as iron::middleware::Handler>::handle
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:212
  15: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  16: <mount::mount::Mount as iron::middleware::Handler>::handle
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/mount-0.3.0/src/mount.rs:122
  17: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
  18: <hyper::server::Worker<H>>::keep_alive_loop
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:337
  19: <hyper::server::Worker<H>>::handle_connection
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:283
  20: hyper::server::handle::{{closure}}
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:242
  21: hyper::server::listener::spawn_with::{{closure}}
             at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/listener.rs:50
```

If more information is required I would be happy to provide it.

**Comment by Makadu59** [comment]
I had the same error from the wallet.

The steps : 
- i have get a .json file named mimbelus.json and run the following command :  
`grin wallet -p password receive --input mimbelus.json`
- the tx was mined on block 17261
- I runned the same command on an other node with the same mimbelous.json
- I get the following panic [https://pastebin.com/E7HNwkUn](https://pastebin.com/E7HNwkUn)

**Comment by ignopeverell** [comment]
In this case it sounds like something going wring is normal, you're trying to spend twice the same inputs, if I'm understanding correctly. Is that right?

However a crash is definitely not the best way to handle this, we should report it with a more user-friendly message like "funds already spent".

**Comment by Makadu59** [comment]
Yes that's right, i tryed to spend twice the same input to see what happened in that case. I share your conclusion about the fact the handle of this event may be improved.

**Comment by ignopeverell** [comment]
Okay great, would you mind filing this as a different issue? Something like "Double spend shouldn't result in panic"? And thanks a lot for the continued testing!

**Comment by Makadu59** [comment]
ok i'm going to fil a different issue
