### ISSUE TITLE
test fail if port already in use: cargo test --all peer_handshake

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#506]
sometimes ports can get locked up longer time by uncleanly closed processes. And sometimes you just forget one "grin server" running somewhere in another window, and then trying

cargo test --all

and it crashes on peer_handshake.

Minimal repro: 
cargo test --all peer_handshake

Workaround: close all grin server processes before running tests. And make sure (`netstat`) no other straggling processes happen to have stolen the port that the test wants.

Suggestion: make the test have a range of available ports to use, or as a first step, use a different default port for tests as for normal usage.

**Comment by mslipper** [comment]
I can make a PR that uses a random port. Would this be useful?

**Comment by ignopeverell** [comment]
Yes, it would be very useful to make that particular test still work in those conditions.

**Comment by mslipper** [comment]
Cool. I'm on it.
