### ISSUE TITLE
during a fork 2nd block with same difficulty is not broadcast

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#512]
In a situation where we have 2 blocks mined at the same time, both with the same total_difficulty, 
nodes do not broadcast out the 2nd block they see.

https://grinexplorer.net/block/21805

<img width="1139" alt="screen shot 2017-12-18 at 10 31 34 am" src="https://user-images.githubusercontent.com/30642645/34113743-afa136ea-e3de-11e7-8cc0-c53bc601a25f.png">

`pipe.process_block()` only return the new chain tip if it gets updated
`chain.process_block()` only broadcasts the block out if we have a new chain tip

I _think_ this explains how/why we see forks that do not quickly get resolved.
The 2nd block will get suppressed, causing it to propagate across the network poorly.
If this then turns out to be the winning fork then everyone sees orphaned blocks later than this and they have no way to retrieve the missing suppressed block.

In `pipe::update_head()` we only update the head if total_difficulty is strictly greater.

~I propose we relax this slightly to allow for equal `total_difficulty` and "last one wins" semantics to ensure this new block gets broadcast out.~

~Edit: I think we want to maintain the current "strictly increasing" semantics. There's a risk we flip-flop between forks like this. And I think its more correct for a node to see the first block at a given total_difficulty as the correct one at that time.~

Edit: Initial attempt is going to keep this as simple as possible and treat both blocks as if they were now the winning chain tip (i.e. "last one wins"). Otherwise we're adding a lot of complexity here to cover this edge case with some special handling.

PR coming shortly.

**Comment by ignopeverell** [comment]
Sorry to come in late but we should default on first-one-win, otherwise you create a lot of incentives to keep forking.

**Comment by antiochp** [comment]
Discussed on gitter. Reworking the PR to make this more generic for "broadcast all valid blocks".
