### ISSUE TITLE
Error setting sumtree root to build a block: DuplicateKernel(Commitment...

### ISSUE THREAD

**Issue by Makadu59** [mimblewimble/grin#513]
Here is what i see on the server console : https://pastebin.com/gd6VQFvh

[Here is the grin.log](https://makadu.ftopia.io/share/d-soIYVwVLy9DtAnYJ3a7g)

[Here is the zipped .grin directory](https://makadu.ftopia.io/share/MGUoyoRqoGwyfN-BVSFUWQ)

Those two last links are available for one month.

**Comment by ignopeverell** [comment]
Looks the same as #507? If so I'll close the other issue, yours has more details.

**Comment by Makadu59** [comment]
yes it looks the same. Sorry for the duplication i didn't realize.

**Comment by ignopeverell** [comment]
Will track this under #507.
