### ISSUE TITLE
My node was forked off the main chain at block height 26208 with InvalidRoot error

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin#535]
Here are the logs from grin.log going back 10 blocks:

https://gist.github.com/mably/294f7e7cf9e31374aaaad74414d1ae27

The zipped sumtrees folder is attached below:

[sumtrees.zip](https://github.com/mimblewimble/grin/files/1580452/sumtrees.zip)

**Comment by ignopeverell** [comment]
Was overthinking that one. Your server was stopped right as it was saving a block, corrupting the sumtree store. This is a general issue with restarts at the wrong time, I'll file something more specific for it.
