### ISSUE TITLE
AlreadySpent error and miner panic occur when inserting a received block, mined by a peer, at a height in the middle of miner building a block for the same height

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#539]
The issue is the case like: the miner is working for a height (lets say 100) and the server receives a block for height 100. The server receives a block mined by a peer on the same blockchain and insert it at the tip (saying height 100) of blockchain while the miner is in the middle of building a block for height 100 without knowing a block inserted. Then the miner gets AlreadySpent error and gets into panic.

[codes related]
grin/miner.rs - run_loop -> build_block -> chain.set_sumtree_roots(&mut b) {

   let roots = sumtree::extending(&mut sumtrees, |extension| {
      // apply the block on the sumtrees and check the resulting root
      extension.apply_block(b)?;
      extension.force_rollback();
      Ok(extension.roots())
   })?;
   ...
}

The apply_block part throws AlreadySpent error and the miner gets into panic.

apply_block {
...
		for input in &b.inputs {
			let commit = input.commitment();
			let pos_res = self.commit_index.get_output_pos(&commit);

			// TODO - Assume this hash specific debug can be cleaned up?
			if b.hash().to_string() == "f697a877" {
				debug!(LOGGER, "input pos: {:?}, commit: {} {:?}",
							 pos_res, input.commitment().hash(), commit);
			}

			if let Ok(pos) = pos_res {
				match **self.output_pmmr.prune(pos**, b.header.height as u32) {
					Ok(true) => {
						self.rproof_pmmr
							.prune(pos, b.header.height as u32)
							.map_err(|s| Error::SumTreeErr(s))?;
					}
					Ok(false) => return Err(Error::AlreadySpent(commit)),
					Err(s) => return Err(Error::SumTreeErr(s)),
				}
			} else {
				return Err(Error::AlreadySpent(commit));
			}
		}

 ...
}

**In apply_block, there is no unspent output at output_pos from commit_index because it was already spent by block received. Then the miner gets AlreadySpent error and gets in panic.**

[Trace of log file]
Dec. 21 06:59:24 - the server received a block for 25654.
Dec 21 06:59:24.478 DEBG pipe: proces_block 7df1f690 at 25645 is valid, save and append.
Dec 21 06:59:24.480 INFO pipe: update_head: 7df1f690, 179380639 at 25645

Then the miner built a block at Dec. 21 06:59.24.
Dec 21 06:59:24.968 DEBG (Server ID: Port 13414) Built new block with 2 inputs and 5 outputs, difficulty: 34

Here's part of new block 25654 created by miner.
Dec 21 06:59:25.221 TRCE Block: Block { header: BlockHeader { version: 1, height: 25645, previous: 09250030, timestamp: Tm { tm_sec: 24, tm_min: 59, tm_hour: 6, tm_mday: 21, tm_mon: 11, tm_year: 117, tm_wday: 4, tm_yday: 354, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 0 }, utxo_root: 00000000, range_proof_root: 00000000, kernel_root: 00000000, nonce: 1

And then AlreadySpent error takes place.
   Dec 21 06:59:25.221 DEBG Starting new sumtree extension.
   Dec 21 06:59:25.221 DEBG Error returned, discarding sumtree extension.
   Dec 21 06:59:25.221 ERRO Error setting sumtree root to build a block:    AlreadySpent(Commitment(0926a077d31bc93de0fce950fa9c271762f2a5da64393924a546cd8520a5d451e9))

Now the miner panic and the server needs to restart to make the miner operational.

**Comment by heunglee** [comment]
When it processes a received block, the server checks the validity of header, and in-memory and store to see if the block is being or has processed. However, when it builds a block, the miner does not check if a block was received, and being (or has) processed at the working height. The miner tries to set sumtree root without checking and encounters a situation of AlreadySpent error. The miner also needs to check in-memory and store to see if a block was received, and being (or has) processed  at the working height to avoid AlreadySpent error and panic.

**Comment by heunglee** [comment]
An interim solution to avoid miner panic can be not to panic when AlreadySpent error returns. Just discard the block in building.

**Comment by heunglee** [comment]
I looked into impact of this issue. The interim solution is going to create more problems. I believe there is currency issue between p2p and miner. When a received block is processed, the rest of services are notified of it. However, the miner is out of loop. So the miner does not know if a received block at the same height is being processed. It seems to me it needs consider a single channel (mutex?) of processing blocks for both of p2p and miner. I still need to look into that this situation creates fork outbreak , bad block or something. Core team members can have better clue.

**Comment by ignopeverell** [comment]
Looking at this right now. Interrupting the miner isn't trivial right now as it goes into the plugins and there are all sorts of possible race conditions with the network. So I'm going for the easiest path: bail on error and retry building the block. It's less optimal so down the road there will likely be additional optimizations but for the time being, that seems like the best solution.

**Comment by heunglee** [comment]
The easiest path is the simple, sound and clear solution like homerun. I need learn more on grin to get to the level of simple but powerful solution :-)
