### ISSUE TITLE
Triage p2p module

### ISSUE THREAD

**Issue by Latrasis** [mimblewimble/grin#54]
Currently we have a have a couple things on the table for `p2p`:

 * DoS Protection
 * Deciding on tokio Integration
 * Documenting p2p behavior
 * Additional Unit and Integration Tests

We need to triage and setup a roadmap for this list and more.

**Comment by ignopeverell** [comment]
For DoS protection the first rule should be rate limiting based. No peer should send us more than X MB per second and we shouldn't send more (assuming it was all requested) than Y MB per second to any peer either. We can start with X=200 and Y=100. That should be measurable at the protocol or connection level easily.

Another measure that all implementations have (Bitcoin Core, Ethereum, etc.) is banning. For example, a peer sending us a block with an invalid proof of work should immediately be disconnected and banned. There's a whole set of egregious behavior like this that can easily be detected. That's likely best implemented as a specific error type coming from the chain or pool implementations and fed back to the p2p module (through the adapters).

**Comment by JollyMort** [comment]
Did you think about adding some PoW challenge for initiating connections? Cuckoo Cycle seems perfect fit for this considering the asymmetry between producing the PoW and verifying it.

**Comment by ignopeverell** [comment]
Interesting idea, but I don't think connections with sybil IPs is a very low hanging fruit for an attacker (at least compared to saturation with single connection). The logistics involved in that are probably as costly as the PoW we'd force on connection. Maybe a nice enhancement, just trying to get the holes that are the cheapest to attack plugged first. Wouldn't refuse a pull request with that option though :-)

**Comment by JollyMort** [comment]
Not really my idea, [folks over at Monero were talking about it](https://www.reddit.com/r/Monero/comments/59mszr/attention_miners_if_proof_of_work_was_changed/d9a4evy/).

>Wouldn't refuse a pull request with that option though :-)

Wish I could make one, but not really my competence. Just trying to pass on an idea I see as useful.

**Comment by Latrasis** [comment]
@ignopeverell: I'm still having trouble understanding the  `Protocol` trait, other than different message types, what other conflicts could be present in different versions?

**Comment by ignopeverell** [comment]
Messages with different properties, additional messages (for SPV for example), changes in the handshake, etc. The protocol was mostly introduced to isolate the handling of multiple messages and request/response type interactions. Does that make sense?

**Comment by Latrasis** [comment]
Hi @ignopeverell, since you mentioned additional messages, how would handling two different message protocols work if the `Protocol` trait only has one type of message format?

I guess what I asking for is some sort of example to understand better. 

You mentioned also that the handshake might change, but currently the handshake is used to initialize the version, which means changing handshake wouldn't work currently.

**Comment by ignopeverell** [comment]
@Latrasis the idea is we'd have different Protocol implementations (ProtocolV1, ProtocolV2, etc.) that would get picked depending on the version chosen during the handshake. Forget about my handshake changing example, it was just a confusing one.
