### ISSUE TITLE
Implement Peer Banning

### ISSUE THREAD

**Issue by Latrasis** [mimblewimble/grin#56]
From #54:
> Another measure that all implementations have (Bitcoin Core, Ethereum, etc.) is banning. For example, a peer sending us a block with an invalid proof of work should immediately be disconnected and banned. There's a whole set of egregious behavior like this that can easily be detected. That's likely best implemented as a specific error type coming from the chain or pool implementations and fed back to the p2p module (through the adapters).

This involves:
* [x] Discuss and define all egregious behaviors that must result in a ban
* [ ] Define an error for each possible behavior
* [ ] Setup testing for each behavior

**Comment by ignopeverell** [comment]
Regarding the first, it's going to be hard to be fully exhaustive right away but looking at all the reasons bitcoin core bans may be a good first list. You can grep for "state.DoS" in the source to get quite a few. 

Not all will be valid errors for us (we have no scripts for example) and we will have additional ones (a block with an invalid UTXO root, or invalid block kernel sum) but it's still a good base to start from and catch all the basic stuff (no input or no output tx, block with no output or no kernel, too many orphans, too much data in bytes, etc.).

**Comment by Latrasis** [comment]
Here is what I have quickly written up: 
https://gist.github.com/Latrasis/02fecd42c5eb0bb4b0a9d11b044cd1fc

**Comment by Latrasis** [comment]
Hi @ignopeverell, here's some questions for (finally) moving forward:

1. Looking through block validation at [`pipe.rs`](https://github.com/ignopeverell/grin/blob/master/chain/src/pipe.rs#L57), would most errors be applicable for banning?
1. Are there different types of Bans? If so what are they?
1. Are there any rules on expiring bans?
1. What are the policies/repercussions of a ban?

**Comment by ignopeverell** [comment]
Hey there!

1. Correct. There are a few exceptions like an internal error (db issue) or orphans. But most other errors should get a peer banned (like an invalid PoW).
2. I don't think so. Bitcoin Core gives a ban score that's a counter and when it exceeds a certain value, the ban actually happens. Most errors get reported with a score that bans the peer outright though so I'm not convinced we need that for now.
3. Nothing set, but we can make or own policy. Maybe 24h or something like that?
4. Outstanding connection is closed, we don't initiate connections to that peer anymore and refuse any inbound connection from that peer as well.

**Comment by yeastplume** [comment]
Just a thought here, might want a method of relaxing some of these rules somewhat, at least on devnet. For instance, it's entirely feasible that a developer might accidentally create invalid POWs, especially when playing around with cuckoo sizes.

**Comment by ignopeverell** [comment]
Good point, maybe a configuration for the p2p server to ignore bans or something like that?

**Comment by Latrasis** [comment]
@ignopeverell : Based on the current implementation, we can configure banning either through a protocol instance or hoisting a configuration on each peer from the `Server`.
