### ISSUE TITLE
thread 'miner' panicked at 'called `Result::unwrap()` 

### ISSUE THREAD

**Issue by Jiloc** [mimblewimble/grin#578]
Ubuntu 17.10, branch testnet1. 
I just received an error following the [Running a Node tutorial](https://github.com/mimblewimble/grin/blob/master/doc/build.md#running-a-node) while the server was syncing.

`thread 'miner' panicked at 'called 'Result::unwrap()' on an 'Err' value: StatsError("Error retrieving stats from plugin: ErrorImpl { code: Message(\"invalid value: integer '-1526891643', expected u64\"), line: 1, column: 144 }")', /checkout/src/libcore/result.rs:906:4
`

Now I am running with `RUST_BACKTRACE=1` to get new info if it happens again.

**Comment by ignopeverell** [comment]
Thanks for the report! We're already tracking this with #539, will hopefully be fixed soon.
