### ISSUE TITLE
[Pool] Outstanding: Recover Previously Invalidated Transactions During a Reorg

### ISSUE THREAD

**Issue by MoaningMyrtle** [mimblewimble/grin#58]
This is more of a longer-term project, as it's not necessary for basic operation of the system. However, in order for transaction pools to operate reliably, I believe there will need to be a system to return transactions invalidated on a fork that was previously head to the pool, so that any transactions that conflict between the fork and new head are not lost forever. This requires a bit more machinery than in most existing blockchains because recovering the transaction from the block itself is not possible.

Conceptually, I was thinking that the pool should retain recently invalidated transactions in their entirety for a period of time (some acceptable reorg depth), which can be much less than the cut-through reorg depth because this property is not necessary for correctness, only usability. Even in the worst case, some miners (those who built the blocks that constitute the new head) should have a consistent view of the transaction pool without any loss. Any thoughts?

**Comment by antiochp** [comment]
We are _definitely_ seeing this right now in `testnet1` and I think this is causing a lot of unintuitive issues with user wallets.

Everytime we see a fork (and we're seeing a bunch) and we finally get back to a stable state some set of users discover their coins are missing - and I suspect most of these issues are explained by txs being invalidated/disappearing due to a re-org.

**Comment by antiochp** [comment]
I think there are also several different cases here that we would want to take into consideration - 

`Chain A` re-orgs to become `Chain B`, rewinding to some common block A<sub>n</sub> == B<sub>n</sub> and building the new chain from there.
Where block A<sub>n+1</sub> is on chain A but not on chain B.
And block B<sub>n+1</sub> is on chain B but not on chain A.

* Tx1 was valid on chain A but no longer valid on chain B (spends an output from block A<sub>n+1</sub>)
* Tx2 was not valid on chain A but is now valid on chain B (spends an output from block B<sub>n+1</sub>)
* Tx3<sub>A</sub> and Tx3<sub>B</sub> are valid on chain A _and_ chain B respectively (a common output is spent from block A<sub>n</sub>|B<sub>n</sub>)

That third one is basically a combination of the previous two but we would need to be able to handle the case where we have multiple txs in there "reusing" outputs.
Where it is invalid to reuse an output on the same chain (double spend), but potentially valid to reuse an output on a different chain (also technically a double spend?, just a successful one?).

**Comment by sesam** [comment]
Any pool of outstanding transactions that should be mined again after a reorg would tie into the stem pool. Should we fold this issue into the dandelion impl. #719 and close this bug?

**Comment by ignopeverell** [comment]
No, this isn't a network thing, it's purely internal to a node. A transaction gets evicted from the mempool when a block including it gets accepted. But if that blocks gets invalidated, the transaction needs to make it back in the mempool. There's no dandelion interaction.

**Comment by ignopeverell** [comment]
We could try to keep transactions around during restarts too but I wouldn't make that an important requirement.

**Comment by quentinlesceller** [comment]
Also there might be some edge cases where we have to revert to previous transaction state with Dandelion aggregation see https://github.com/mimblewimble/grin/blob/master/doc/dandelion/simulation.md

**Comment by ignopeverell** [comment]
I've given this some thoughts but I'm not sure I'll have time to tackle it soon enough, given everything that's happening. So I'll just write this down for now.

The best entry point seems to be `Pool.reconcile_block` and more specifically `remaining_transactions`. The `Vec` of transaction entries getting evicted could be kept to the side with the block hash the evicted them. When the block is orphaned, corresponding entries could be re-added.

From a design standpoint, this would have to be fairly close to both the chain and the pool and I'm not sure it belongs to either. So the coordination may be better implemented in the `servers` crate as some sort of adapter. The actual cache could be mantained there or in the pool. It should also keep a bounded number of entries (perhaps just enough for the last 10 blocks).

**Comment by antiochp** [comment]
Agreed on not coupling this _too_ closely to the pool itself. We still evict them from the pool, they just get maintained elsewhere for a bounded period of time (and some bounded storage) before we actually forget about them permanently.

I'd like to keep the pool impl as simple as possible - rentry into the pool adds some unavoidable complexity but it can be external to the pool proper.

**Comment by ignopeverell** [comment]
@hashmap still planning to work on this?

**Comment by hashmap** [comment]
@ignopeverell  If someone has capacity to start now I don't mind, if not I'll take another attempt in couple weeks or earlier

**Comment by hashmap** [comment]
ready to tackle it if @antiochp hasn't done it already:)

**Comment by antiochp** [comment]
#1829 attempts to fix this in the simplest way possible.

* Every time we add a tx to the txpool (after we have successfully validated it) -
  * add it to a `reorg_cache` (ringbuffer of recent txs).
* Then every time we see a new block and call reconcile_block() on the txpool -
  * iterate over the `reorg_cache` and reapply each tx to the txpool

This leverages the existing txpool validation logic to ensure txs are valid (and if they are valid they can safely be added to the pool).
