### ISSUE TITLE
Double spend shouldn't result in panic

### ISSUE THREAD

**Issue by Makadu59** [mimblewimble/grin#585]
following the discussion on [504](https://github.com/mimblewimble/grin/issues/504), we fil a new issue

The steps : 
- i have get a .json file named mimbelus.json and run the following command :  
`grin wallet -p password receive --input mimbelus.json`
- the tx was mined on block 17261
- I runned the same command on an other node with the same mimbelous.json
- I get the following panic [https://pastebin.com/E7HNwkUn](https://pastebin.com/E7HNwkUn)

@ignopeverell answers : 
"In this case it sounds like something going wring is normal, you're trying to spend twice the same inputs, if I'm understanding correctly. Is that right?

However a crash is definitely not the best way to handle this, we should report it with a more user-friendly message like "funds already spent"."

**Comment by ignopeverell** [comment]
This should be trivial to fix but ties up to the API not returning great errors (ends up as a `500`).

**Comment by Makadu59** [comment]
It was fast !! 🥇 
:)

**Comment by mably** [comment]
It looks like the rejected output is still added to the wallet, after a few double spend attempts on my side.

**Comment by ignopeverell** [comment]
That's a different fix :-) Going to look at that next.

**Comment by ignopeverell** [comment]
Should be fixed as well now.

**Comment by mably** [comment]
Things are improving fast, thanks @ignopeverell  😄
