### ISSUE TITLE
Restoring a wallet while mining causes some kind of wallet deadlock

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin#587]
After a few mintues, both wallet listener and restoring processes can't seem to get proper access to the wallet lock.

It works perfectly fine once mining is disabled.

**Comment by yeastplume** [comment]
This is to be expected, in this case two processes are trying to access the wallet at the same time. We'll add clearer instructions that you shouldn't be mining and trying to restore a wallet at the same time.
