### ISSUE TITLE
how to multiply the mimbelous on your wallet ;) - "multiplication of the loaves" :D

### ISSUE THREAD

**Issue by Makadu59** [mimblewimble/grin#589]
Steps : 
- i sent 10 mimbelous on my node number 2 from my node number 1
-  `grin wallet -p password info`   on my node number 1 showed me a number multiplyed by two of the number of mimbelous i had on the "currently spendable" sum minus 10.

[see the screenshot here](https://imgur.com/a/30VQO)
[here are the outputs after the tx confirmation](https://imgur.com/a/ZIFYe)

after a ` grin wallet -p password restore ` 
[the state of the wallet](https://imgur.com/a/LOi9B)

**Comment by Makadu59** [comment]
Actually, I can repeat the issue only just [after a panic due to the following command](https://pastebin.com/Q0NdCRxq) : 
`grin wallet -p password send -c 1 -d "51.15.77.170:13415" 1.0`
forgetting `http://`

Otherwise i can't repeat the issue.

**Comment by sesam** [comment]
Fixed by #530 in commit 1199ed2c
