### ISSUE TITLE
Wallet security model

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#591]
Because parts of our wallets may need to be online, we need to specify in a lot more details how sensitive data, particularly the seed and passphrase, are secured and isolated. We would benefit from designing this early instead of growing it organically.

Some points and ideas to think about:

* A wallet receiver may need to be online. There may be solutions that don't require it to have full access to the seed and passphrase but we should architect it so it's secure enough regardless.
* There may be additional APIs exposed to send money, query the wallet state, etc. How do we secure those? Exposing them locally only can be a first but non-sufficient step.
* We have full control over the server and some control over the clients. So we could enforce TLS 1.2 with a well-chosen subset of ciphers.
* Process isolation is likely required. Maybe a dedicated key server seggregated from the rest just for the purpose of manipulating keys exposing a very limited set of operations and with restrictions?

**Comment by camalolo** [comment]
Regarding TLS 1.2, what do you think about this library ? https://docs.rs/rustls/0.12.0/rustls/

**Comment by ignopeverell** [comment]
Looks promising.

**Comment by camalolo** [comment]
Regarding your second point (wallet operations extenal api) : what do you think about having a TLS encrypted rpc server that would also require http authentication ? The rpc user and password would be configured in the config file or command line parameters. Would that offer enough security ?

**Comment by vjeranc** [comment]
Would tricks from [BIP-0032](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) be useful?

**Comment by yeastplume** [comment]
I might add DoS protection as well to the list of considerations, especially needed for larger (i.e. exchange) wallets. Fun!

**Comment by camalolo** [comment]
@yeastplume this could be possible for example to delay reply to clients that made too many requests in the last n seconds ? Real DoS protection might be easier to do via IPTables and other dedicated solutions though, especially for an exchange that requires near perfect uptime.

**Comment by ignopeverell** [comment]
@camalolo want to take a stab at this issue by writing some design doc?

**Comment by camalolo** [comment]
@ignopeverell I can try ! Should the document look like a BIP for example ? Or is there an existing document in the grin repository that could be my starting template ? Cheers !

**Comment by camalolo** [comment]
Do you think this is a good start ? It's mostly empty but if the direction is right I can try and write more.

https://docs.google.com/document/d/1OXFIiMvNeQeZQuFGZYpUnE9cLhH40MpTrlaf4D8sJLg/edit?usp=sharing

**Comment by yeastplume** [comment]
@camalolo you're right with regards to DoS protection, I think we do need something included out-of-the-box but more complicated solutions belong further down the stack. I guess it's just a matter of how much of the stack we provide ourselves in a default configuration. There's been talk of providing docker images, having wallet hosting services for less-technical people, etc, so that was more what I'm getting at.

The doc looks very good, but far more formal than anything we've done to date, and at this stage in the project where everything is in flux I think it's more important to focus on getting the information down rather than make it look formal (that can come later when things are more settled down). It's perfectly okay to put a proposed spec into a markdown document that we'd put here: https://github.com/mimblewimble/grin/tree/master/doc

**Comment by camalolo** [comment]
@yeastplume ah ! got it ! I will try to complete it as much as I can and put it in the doc directory as a .md file so everyone can update it

**Comment by heunglee** [comment]
For authentication of wallet receivers, 2FA can be utilized. It seems google authenticator can be considered as a tool of 2FA. 

Also it may be necessary to define what data (or attributes) of transfer activities must be kept as activity log (ie. to resolve disputes) and for the compliance with grin privacy guidelines, and data storage for security.

Re: TLS
In my understanding to use TLS, certificates are issued by (non-)commercial trusted third party certificate authorities such as symantec and netcraft. However, there is open certificate authority: https://letsencrypt.org/ for node maintainer's convenience. So TLS is a viable, cost effective solution for grin nodes and clients.

**Comment by ignopeverell** [comment]
There's the wiki too, which may make it easier for others to help out:

https://github.com/mimblewimble/docs/wiki

**Comment by camalolo** [comment]
I pushed a draft, please see #600
