### ISSUE TITLE
Tests for network data corruption

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#592]
We need tests to cover corruption of important data that goes over the network, either intentional or malicious. The tests should start from a valid transaction or block, try to change every possible included field (like an output commitment or a kernel pubkey) and check that the change invalidates the transaction or block.

Some things should fairly obviously fail (i.e. commitment) but others are less obvious (switch commitment, output feature field, etc).

**Comment by sesam** [comment]
Leaving some links:
 * https://github.com/rust-fuzz
 * https://www.reddit.com/r/rust/comments/5va0mi/cargofuzz_an_easy_way_to_fuzz_your_crates/
 *  https://github.com/steveklabnik/quickcheck can be used to create cargo test fuzzing tests = feed in random inputs and find a small, maybe minimal, example where the function fails. We should use this.

**Comment by alexanderbez** [comment]
I'll be happy to help out on this issue 👍

**Comment by ignopeverell** [comment]
That would be great!

**Comment by hashmap** [comment]
Actually approach suggested by @ignopeverell is not pure fuzzing, it's closer to regular unit tests. However I tried fuzzing, I mean feeding some random data into implementation of `Readable` for `Transaction` as a starting point. The code panics pretty quickly in various places when memory allocation happens, usually in vector code. The common pattern is the following:
``` 
impl Readable for MerkleProof {
	fn read(reader: &mut Reader) -> Result<MerkleProof, ser::Error> {
                ....
		let (peaks_len, path_len) = ser_multiread!(reader, read_u64, read_u64);
		let mut peaks = Vec::with_capacity(peaks_len as usize);
```  

of course fuzzer puts some max u64 values into the blob, vector code has to multiply this value by item size, gets overflow. It's easy fixable by

 ``` 
         let hash_size = mem::size_of::<Hash>() as u64;
		if peaks_len.checked_mul(hash_size).is_none() ||
	   	   path_len.checked_mul(hash_size).is_none() {
			return Err(ser::Error::TooLargeReadErr);
		}
```

However after allocating a few huge vectors without overflow we still fail with OOM:

```
==15236==WARNING: AddressSanitizer failed to allocate 0x5e0000000000000 bytes
==15236==AddressSanitizer's allocator is terminating the process instead of returning 0
```
I suppose we need set some reasonable limits for size of dynamically allocated fields like number of input/outputs, number of peaks etc. Perhaps we have them already?

**Comment by ignopeverell** [comment]
We should have standard limits for everything yes. For transactions, 500 inputs and 100 outputs seems reasonable. What do you mean by peaks?

**Comment by hashmap** [comment]
Sounds good. Peaks are from PMMR - we also read it from network and then allocate a vector

**Comment by ignopeverell** [comment]
Oh you mean the roots in block headers? Or the whole thing in fast sync? Guessing the former, that's always 32 bytes (it's a hash).

**Comment by ignopeverell** [comment]
Checked your changeset, you meant the path in the Merkle proof. 100 should be more than enough, no one would have enough available memory to hold a 2^100 sized tree.
