### ISSUE TITLE
Aggsig error handling

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#594]
The error cases around aggsig transactions https://github.com/mimblewimble/grin/pull/530 need to be handled better than they currently are, ensuring that all detected failures don't corrupt the wallet state.

One design issue that needs to be considered is that if we're on the receiving end, how long do we wait before we consider that the next phase of the transaction isn't coming? Something needs to spin up when a transaction begins, then time out and remove the generated ouput(s) from the wallet if it isn't completed within a certain interval.

**Comment by ignopeverell** [comment]
Closing for now. May need a more specific issue(s) soonish when testing and giving the wallet some love.

**Comment by yeastplume** [comment]
Will close in and open more specific issues during testing
