### ISSUE TITLE
Grin Wallet has become inoperable after weeks of mining

### ISSUE THREAD

**Issue by gastonxpander** [mimblewimble/grin#598]
After successfully mining with my centos7 linux server for weeks and mining thousands of coins, I noticed the server stopped producing any coins for a longer period than I had seen. I had previously submitted issue #557 which turned out to be duplicate. Issue #557 crashed my server 2 or 3 times, so I am well versed in restarting the server and wallet as after each crash I continued mining plenty more coins. This time it is different. I noticed my server was not producing coins, but it had not crashed or shown an error in the CLI of any thread panic. So I attempted to restart the wallet and server to be safe. Now, I cannot restart the server because at the 60 second mark of running the server tries to hit the wallet and throws errors related to the wallet lock and being unable to connect to the wallet. 

After seeing this, I deleted grin and re-built from the git branch. I am now running Grin 0.1 with the latest versions of clang and the facebook rocksdb which required me to update clang to 3.9+. After going through the rebuild process, restarting the server, and deleting the .lock file from the custom wallet directory, there is absolutely no change in behavior. I cannot run my server and it appears to be the fault of the wallet. 

Lastly, when I run the grin wallet info command for the wallet, it no longer shows me the little table with unit coin counts at all. Previously I had noticed that even if my server had crashed the wallet info would still show the table with the coin units stating it was in local cache. Here is what I see now whenever I run wallet info (no matter if the server is running or not):
````
[root@grim-ofc-01 wallet]# grin wallet -p PASSWORD info
Jan 10 21:08:34.423 DEBG Using wallet seed file at: ./wallet.seed
Jan 10 21:08:34.534 DEBG Refreshing wallet outputs

WARNING: Wallet failed to verify data. The above is from local cache and possibly invalid! (is your `grin server` offline or broken?)
````

I have attached the grin.log, as well as the live outputs of both the server and wallet CLIs. This has brought me to a dead halt and I was running very well before mining thousands of coins. Please advise as to next steps or required info. If you'd like to chat anytime please let me know, thank you.
[grin.log.txt](https://github.com/mimblewimble/grin/files/1620988/grin.log.txt)
[grin-server-cli.txt](https://github.com/mimblewimble/grin/files/1620989/grin-server-cli.txt)
[grin-wallet-cli.txt](https://github.com/mimblewimble/grin/files/1620990/grin-wallet-cli.txt)

**Comment by ignopeverell** [comment]
Closing this in preparation for Testnet2. Likely fixed or very different now.
