### ISSUE TITLE
unwrap() on Err: Internal("Error processing partial transaction: Node(Argument(\"Argument error: \"))")', src/libcore/result.rs:906:4

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#616]
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: Internal("Error processing partial transaction: Node(Argument(\"Argument error: \"))")', src/libcore/result.rs:906:4
So maybe the error message needs changed to be clearer for user.

> What kind of error is it? It seems the tx went through fine.

CC @heunglee Did you find out anything more on this, or what would be a better
error message?

**Comment by heunglee** [comment]
I have not looked into the primary cause of it. The error message is displayed in stdout of receiver's wallet. The sender gets 500 internal server error. So it would be nice to elaborate the error message for the sender. The current message can mislead the sender in such way that the sender's wallet had an error even if the error took place in the receiver's wallet or that the sender cannot understand what is going on with his or here wallet. When I find out the primary cause, I will post it here.

**Comment by sesam** [comment]
Closing this in preparation for Testnet2 that will soon open
