### ISSUE TITLE
Error building testnet1 branch on OSX - Compiling librocksdb-sys v5.7.1

### ISSUE THREAD

**Issue by rstmsn** [mimblewimble/grin#621]
mbp:code dt$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/mimblewimble/rust-secp256k1-zkp`
    Updating git repository `https://github.com/danburkert/memmap-rs`           
    Updating git repository `https://github.com/mimblewimble/cuckoo-miner`      
    Updating git repository `https://github.com/mimblewimble/rust-secp256k1-zkp`
   Compiling itoa v0.1.1                                                        
   Compiling lazy_static v0.2.11
   Compiling term v0.4.6
   Compiling utf8-ranges v0.1.3
   Compiling vec_map v0.8.0
   Compiling serde v0.8.23
   Compiling slab v0.3.0
   Compiling odds v0.2.26
   Compiling itoa v0.3.4
   Compiling modifier v0.1.0
   Compiling slog v2.1.1
   Compiling bitflags v1.0.1
   Compiling libloading v0.4.3
   Compiling winapi v0.2.8
   Compiling byteorder v1.2.1
   Compiling constant_time_eq v0.1.3
   Compiling bitflags v0.7.0
   Compiling fs_extra v1.1.0
   Compiling lazycell v0.6.0
   Compiling void v1.0.2
   Compiling version_check v0.1.3
   Compiling quote v0.3.15
   Compiling take v0.1.0
   Compiling scoped-tls v0.1.0
   Compiling rayon-core v1.3.0
   Compiling unicode-xid v0.0.4
   Compiling smallvec v0.2.1
   Compiling route-recognizer v0.1.12
   Compiling strsim v0.6.0
   Compiling typeable v0.1.2
   Compiling unicode-normalization v0.1.5
   Compiling slab v0.4.0
   Compiling take_mut v0.2.0
   Compiling sequence_trie v0.2.1
   Compiling nodrop v0.1.12
   Compiling make-cmd v0.1.0
   Compiling matches v0.1.6
   Compiling unicode-width v0.1.4
   Compiling regex-syntax v0.4.2
   Compiling scopeguard v0.3.3
   Compiling lazy_static v1.0.0
   Compiling cfg-if v0.1.2
   Compiling bitflags v0.8.2
   Compiling dtoa v0.4.2
   Compiling futures v0.1.17
   Compiling serde v1.0.27
   Compiling gcc v0.3.54
   Compiling traitobject v0.1.0
   Compiling percent-encoding v1.0.1
   Compiling peeking_take_while v0.1.2
   Compiling byteorder v0.5.3
   Compiling rustc-serialize v0.3.24
   Compiling utf8-ranges v1.0.0
   Compiling httparse v1.2.3
   Compiling language-tags v0.2.2
   Compiling regex-syntax v0.3.9
   Compiling dtoa v0.2.2
   Compiling winapi-build v0.1.1
   Compiling ansi_term v0.10.2
   Compiling num-traits v0.1.41
   Compiling encode_unicode v0.3.1
   Compiling glob v0.2.11
   Compiling safemem v0.2.0
   Compiling libc v0.2.36
   Compiling either v1.4.0
   Compiling unreachable v1.0.0
   Compiling unicase v2.1.0
   Compiling unicase v1.4.2
   Compiling synom v0.11.3
   Compiling arrayvec v0.3.24
   Compiling arrayvec v0.4.6
   Compiling textwrap v0.9.0
   Compiling unicode-bidi v0.3.4
   Compiling log v0.4.1
   Compiling secp256k1zkp v0.7.1 (https://github.com/mimblewimble/rust-secp256k1-zkp?tag=grin_integration_2#0a8b33e5)
   Compiling secp256k1zkp v0.7.1 (https://github.com/mimblewimble/rust-secp256k1-zkp#3b2fd9f1)
   Compiling rust-crypto v0.2.36
   Compiling unsafe-any v0.4.2
   Compiling error v0.1.9
   Compiling tokio-service v0.1.0
   Compiling relay v0.1.0
   Compiling tokio-timer v0.1.2
   Compiling kernel32-sys v0.2.2
   Compiling toml v0.4.5
   Compiling syntex_pos v0.58.1
   Compiling conduit-mime-types v0.7.3
   Compiling serde_json v1.0.9
   Compiling serde_json v0.8.6
   Compiling num-complex v0.1.41
   Compiling num-integer v0.1.35
   Compiling enum_primitive v0.1.1
   Compiling base64 v0.6.0
   Compiling base64 v0.9.0
   Compiling thread_local v0.3.5
   Compiling coco v0.1.1
   Compiling itertools v0.6.5
   Compiling clang-sys v0.21.1
   Compiling memchr v2.0.1
   Compiling daemonize v0.2.3
   Compiling num_cpus v1.8.0
   Compiling memchr v1.0.2
   Compiling memmap v0.6.0 (https://github.com/danburkert/memmap-rs?tag=0.6.0#59ce48b8)
   Compiling atty v0.2.6
   Compiling rand v0.3.20
   Compiling net2 v0.2.31
   Compiling isatty v0.1.6
   Compiling iovec v0.1.1
   Compiling time v0.1.39
   Compiling memchr v0.1.11
   Compiling syn v0.11.11
   Compiling blake2-rfc v0.2.18
   Compiling log v0.3.9
   Compiling typemap v0.3.3
   Compiling idna v0.1.4
   Compiling syntex_errors v0.58.1
   Compiling num-iter v0.1.34
   Compiling slog-async v2.2.0
   Compiling aho-corasick v0.6.4
   Compiling futures-cpupool v0.1.8
   Compiling csv v0.15.0
   Compiling nom v3.2.1
   Compiling clap v2.29.2
   Compiling bytes v0.4.6
   Compiling aho-corasick v0.5.3
   Compiling num-bigint v0.1.41
   Compiling mime v0.2.6
   Compiling mio v0.6.12
   Compiling serde_derive_internals v0.19.0
   Compiling plugin v0.2.6
   Compiling regex v0.2.5
   Compiling url v1.6.0
   Compiling prettytable-rs v0.6.7
   Compiling syntex_syntax v0.58.1
   Compiling tokio-io v0.1.4
   Compiling mime v0.3.5
   Compiling rayon v0.9.0
   Compiling cexpr v0.2.2
   Compiling num-rational v0.1.40
   Compiling serde_derive v1.0.27
   Compiling thread-id v2.0.0
   Compiling hyper v0.10.13
   Compiling env_logger v0.4.3
   Compiling tokio-core v0.1.12
   Compiling cc v1.0.4
   Compiling num v0.1.41
   Compiling thread_local v0.2.7
   Compiling iron v0.5.1
   Compiling tokio-proto v0.1.1
   Compiling tokio-retry v0.1.1
   Compiling cmake v0.1.29
   Compiling regex v0.1.80
   Compiling chrono v0.4.0
   Compiling router v0.5.1
   Compiling mount v0.3.0
   Compiling persistent v0.3.0
   Compiling hyper v0.11.13
   Compiling cuckoo_miner v0.1.0 (https://github.com/mimblewimble/cuckoo-miner?tag=grin_integration_16#5cc4f56d)
   Compiling aster v0.41.0
   Compiling quasi v0.32.0
   Compiling syntex v0.58.1
   Compiling bodyparser v0.5.0
   Compiling bodyparser v0.7.0
   Compiling slog-term v2.3.0
   Compiling env_logger v0.3.5
   Compiling urlencoded v0.5.0
   Compiling quasi_codegen v0.32.0
   Compiling grin_util v0.1.0 (file:///Users/dt/Desktop/code/util)
   Compiling bindgen v0.29.1
   Compiling grin_keychain v0.1.0 (file:///Users/dt/Desktop/code/keychain)
warning: unused `#[macro_use]` import
  --> keychain/src/lib.rs:22:1
   |
22 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

   Compiling grin_core v0.1.0 (file:///Users/dt/Desktop/code/core)
   Compiling grin_pow v0.1.0 (file:///Users/dt/Desktop/code/pow)
   Compiling librocksdb-sys v5.7.1
error: failed to run custom build command for `librocksdb-sys v5.7.1`
process didn't exit successfully: `/Users/dt/Desktop/code/target/debug/build/librocksdb-sys-6e9a288e8f0171b2/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
rocksdb/include/rocksdb/c.h:48:9: warning: #pragma once in main file, err: false

--- stderr
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', /Users/dt/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.21.1/src/lib.rs:1456:0
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by ignopeverell** [comment]
Do you have clang installed?

**Comment by rstmsn** [comment]
clang is installed. could versioning be an issue?

$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by quentinlesceller** [comment]
I have no compilation problem on my MBP
```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by rstmsn** [comment]
@quentinlesceller is that running Sierra/High Sierra? 

I tried to uninstall the Xcode instance of clang and replace it with a more recent built using homebrew. Homebrew tells me OS X 10.10 is out of date and no longer supported. I might bite the bullet and upgrade the OS.

**Comment by quentinlesceller** [comment]
Yes I'm on 10.13.2.

**Comment by rstmsn** [comment]
Upgraded to 10.13.2, clang -v returned Apple LLVM version 9.0.0 (clang-900.0.39.2), compile still failed on librocksdb-sys v5.7.1. 

After updating XCode via the appstore, I'm now able to build successfully.

**Comment by freehere107** [comment]
@rstmsn i upgrade  XCode with my mac os 10.14.3,it's still install not success

**Comment by freehere107** [comment]
@rstmsn i upgrade  XCode with my mac os 10.14.3,it's still install not success

**Comment by rascal-3** [comment]
@freehere107 

How about following?

$ brew install llvm
$ echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
$ source ~/.bash_profile
and re-run

Cheers,

**Comment by Michshelle** [comment]
> @freehere107
> 
> How about following?
> 
> $ brew install llvm
> $ echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
> $ source ~/.bash_profile
> and re-run
> 
> Cheers,

This works for me.  However, it should be to input it in zsh for osx nowadays...   :)
