### ISSUE TITLE
While mining on testnet1, solutions generated consistently cause an InvalidPow error

### ISSUE THREAD

**Issue by porpentina** [mimblewimble/grin#624]
I have successfully mined on testnet1 with a default grin.toml. I edited the settings to allow for parallel mining on multiple CPU miners using async mode. Since doing so, even if I switch back to a single miner, each generated solution generates an InvalidPow error and is rejected.

[server.tar.gz](https://github.com/mimblewimble/grin/files/1638092/server.tar.gz)

**Comment by kargakis** [comment]
I have seen this error even without mining.

**Comment by heunglee** [comment]
As we discussed in gitter, the error occurs when validating the header of mined block. The conditions failed were:
1. the target difficulty of the mined block is less than the evolving network difficulty and/or
2. invalid cuckoo solution

It is hard to reproduce the error in the controlled environment. So it would need  logging of cuckoo solution and the target difficulty for blocks to trace. I will put logging of them in my node and see.

**Comment by heunglee** [comment]
I can not reproduce the error in my server with default grin.toml. So will see with async mode with multiple threaded miners.

**Comment by yeastplume** [comment]
This is fixed in master via : https://github.com/mimblewimble/grin/pull/639. Not sure I'm going to fix it on testnet, so please just use sync mode on testnet in the meantime.
