### ISSUE TITLE
Suggestion: move p2p out of grin

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#636]
The primary goal should be a stable, low latency p2p to propagate mined blocks.
Discovery can always be bolted on afterwards. Reliability is the hard part.

Maybe get NAT-traversal and large anonymity set "for free" by using some existing popular network protocol as a base.

WebRTC could be interesting, and maybe make it easier to create web wallets.

Moving p2p out into its own "service" allows `grin server` to use that service as a caching layer, and possibly one p2p service with high bandwidth could be used by several mobile/embedded validating grin servers.
Interfacing could happen through grin API endpoints.

__What endpoints would then need to be added?__

Rationale:
- no devs are comfy with existing p2p built on futures
- still lots to do on p2p
- there's no mature rust p2p code to lean on
  (in rust, the only p2p crate I've found is named crust and is missing features and having bugs that makes it a no-go for grin for the next few months at least)
- enables reuse, to get NAT-traversal, web browser compat, mature p2p base

Cons:
 - current code mostly works for non NAT:ed users
 - already have a test: peer_handshake
 - force-adds API-endpoints
 - cutting grin into smaller pieces

Pros:
 - cutting down grin into smaller pieces
 - more layers between grin and the scary internet
 - "grin server" might become very stable if it only does one thing, good
 - grin could realistically be single-threaded
 - less context switching
 - protects grin/mining processes from some network-based attacks
 - TravisCI might be faster if we move out the p2p part
 

Riding on existing libs would save a lot of time. Maybe even an easy path to GUI wallets.

* https://ws-rs.org/
  - Event-driven WebSockets for rust
  - Likely the most performant. (Also most stable?)
  - Maybe allows reusing existing code the best, f we don't want to move the p2p part out into a separate service just yet.
  - still rust, so possibly missing out on a chance to attract non-rust programmers to work on grin

* https://github.com/bitpay
  - maybe doable to only patch in grin's data formats?
  - bitcore-p2p
	- CoPay wallet (often used by alts)

* https://socket.io/blog/socket-io-p2p/
	- WebRTC, nodejs
	- [C++11](https://github.com/socketio/socket.io-client-cpp), [Swift](https://github.com/socketio/socket.io-client-swift)
	- mature

* http://www.freedomjs.org/
	- multiple p2p backends: WebRTC, XMPP, community provided
	- js. allows code reuse between platforms: nodejs, browsers, Cordova (Android/iPhone/...)

* Something else?
[The awesome p2p list](https://github.com/kgryte/awesome-peer-to-peer)
has a lot to wade through, also things usable for peer discovery:
mDNS local discovery, DHT, service discovery solutions, WebRTC swarm over BLE
that can allow two Android phones to create a transaction locally before either
sends it to a grin miner or cut-through aggregator.

**Comment by kargakis** [comment]
+1 on making it stupid-easy to work for NATed users.

Dropping a link to the crust crate @sesam already mentioned: https://github.com/maidsafe/crust

Also, related: https://github.com/bitcoin/bitcoin/issues/11902

**Comment by sesam** [comment]
About crust -- I've emailed with Spandan of MAIDSAFE and they're in the process of switching over from the master branch code (TCP only) to the dev branch (tokio & futures) but it's WIP, so we'd still have futures. crust is based on https://github.com/ustulation/p2p which is also WIP, but does NAT traversal etc.

Since we're not (yet?) married to tokio and futures, I'm still thinking there is some proven and working solution out there to take and run with.

Maybe the first question should be; how much performance / max latency do we need?
Global blok propagation in < 1 minute might be a very high target to hit, when some users are behind so many layers of NAT and proxys and application firewalls and things that their ping can be in the order of seconds.

Bitcoin with maybe 6-9 minutes to spare from block generation to propagation had to create a centralised high speed network to get around the limitations of p2p.

Maybe we can target a network graph with some seriously strong nodes that are star-shape-interconnected (dark reds in the center) and they can then scale-out the gossiping to an outer layer of (only) opportunistic p2p nodes that ensure peer discoverability, and the petals are covering most of the last mile to reach mobile wallets etc.
![image](https://user-images.githubusercontent.com/8921/35159828-c8f7458c-fd3b-11e7-9389-43875cf0f1d6.png)

**Comment by ignopeverell** [comment]
I was trying to unboil the ocean by dropping futures/tokio, not boil it some more :-) So I'd advocate for:

1. Simple
2. NAT support (maybe with ustulation/p2p)
3. Possibly relay networks if needed after compact blocks and depending on the sizes of our blocks.

**Comment by heunglee** [comment]
In consideration of separation of p2p out of grin, it would be better to consider if graceful shutdown of p2p part is coordinated with server as useful feature. That may bring in more value of grin network in terms of maintenance efficiency in trading parties.

**Comment by yeastplume** [comment]
Think we can close this for now.

**Comment by kargakis** [comment]
Opened https://github.com/mimblewimble/grin/issues/1205 for NAT traversal support since that discussion is not tracked anywhere else.
