### ISSUE TITLE
Setup and test first seed

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#64]
Setup the first seed server that other peers will connect to first on startup.

**Comment by gazhayes** [comment]
Is there any progress on the implementation of this?

**Comment by ignopeverell** [comment]
Coming soon...

**Comment by ignopeverell** [comment]
Had to add support for orphans in 3c3b12b to avoid stalled sync on first startup. Next step is more testing.

**Comment by jklepatch** [comment]
Need help to setup the server ?

**Comment by ignopeverell** [comment]
Setting up a server isn't really the issue, I would just like to have our sumtree implementation complete before that. Once that's done, the infrastructure part shouldn't be too long.

**Comment by sesam** [comment]
ping @ignopeverell close this?

**Comment by ignopeverell** [comment]
Closed it should be.
