### ISSUE TITLE
transaction received a 2nd time

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#640]
Steps to reproduce:  
* Wallet 1:  Create a send transaction into JSON file
* Wallet 2: Receive that transaction
(so far so good, the wallet2 transaction list shows the new coins in the balance, and correctly lists the Received transaction)
* Wallet 2: Receive that transaction a second time

Issues:
Although the second receive attempt reports an error and the coins are not received a second time:
1) The error message does not describe the actual problem and could be confusing.  I would expect a message like "Transaction already received" the message currently reported is:
```
Error receiving transaction, the most likely reasons are:
 * the transaction has already been sent
 * your node isn't running or can't be reached
```

2) The Transfer history list shown by "grin wallet info" incorrectly shows the duplicate receive without any indication that it had failed.  This is an example of receiving the same transaction 3 times:

```
Wallet Summary Info - Block Height: 35766
--------------------------
 Total                            | 5.492000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 0.000000000 
 Currently Spendable              | 5.492000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 


Grin Coin Transfer List - Total Transfers: 3
Please note that 'sent or received at' indicates the date & time
 your wallet sent or received grin coins at.
+----------+-------------+-------------------------------+--------------------------+
| Transfer | Amount      | Sent or Received at           | Receiving Wallet Address |
+----------+-------------+-------------------------------+--------------------------+
| Received | 5.500000000 | Fri, 19 Jan 2018 20:27:27 GMT | localhost:13415          |
+----------+-------------+-------------------------------+--------------------------+
| Received | 5.500000000 | Fri, 19 Jan 2018 20:26:41 GMT | localhost:13415          |
+----------+-------------+-------------------------------+--------------------------+
| Received | 5.500000000 | Fri, 19 Jan 2018 20:19:54 GMT | localhost:13415          |
+----------+-------------+-------------------------------+--------------------------+
```

**Comment by heunglee** [comment]
The transfer activity log is created before a transaction data corresponding to the transfer is submitted to the server. After it receives the transaction data, the server can verify if the transfer is duplicate. So the activity log needs to be put when the transaction data is successfully processed in the server end. will fix it.

Also the error message will be changed as requested.

**Comment by heunglee** [comment]
I opened an issue for inconsistency in error handling between the wallet and the server. So I will not include fix of handling of error message.

**Comment by yeastplume** [comment]
Ancient T1
