### ISSUE TITLE
max number of coinbase outputs/kernels in a block?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#644]
Currently every block contains a single coinbase output and a single coinbase kernel.
But there is nothing (that I am aware of that limits Grin/MW to a single output/kernel).

It would be possible to merge 2 blocks together to produce a combined block with 2 coinbase outputs and 2 coinbase kernels and the block would still validate.
It would also be possible (I believe) to modify the miner/block creation code to split the miner rewards up into multiple outputs.

Thinking through "Compact Blocks" in #522 - 
Coinbase outputs and kernels cannot be represented as `short_ids`, we always want to include them as full outputs/kernels as there is no standalone tx broadcast for them.

The more full outputs and kernels the larger a compact block and the less benefit we get.
If it was possible for miners to generate necessarily huge compact blocks then we're kind of defeating the purpose of them (or at least making them less useful).

So do we want to limit the number of coinbase outputs or coinbase kernels that can exist in a valid block (via a consensus rule)?
And should this number be __1__ initially?

pinging @ignopeverell

**Comment by ignopeverell** [comment]
That may be a sensible default to start with.

**Comment by antiochp** [comment]
Resolved in #647.
For a block to validate - 
* max 1 coinbase output
* max 1 coinbase kernel

**Comment by ignopeverell** [comment]
In hindisght, I wonder if that was really necessary given that:
* it's in miners' best interest to have small blocks (lower chances of orphaning)
* we can't prevent miners from bloating blocks anyway (they can include all the regular transaction outputs they want without paying fees)

**Comment by antiochp** [comment]
Opened #689 to "fix" this.
As @tromp said - "nice case of premature optimization"...
