### ISSUE TITLE
ExtendedKey derivation cleanup

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#649]
From gitter (@ignopeverell ) - 

> sorry was looking at our derivation again, I think the current derive function on ExtendedKey is a little confusing because all our keys are "hardened" and so:
root_key.derive(2) != root_key.derive(1).derive(2)

> it's an HMAC-512 between each, which we kind of replaced with blake2, the one weakeness in BIP32 is in the derivation of non-hardened key, if you lose a non-hardened private key you can use a parent pubkey previously revealed to get the parent private

> that's due to the composition on both the public and private keys which need to be equivalent, we don't have that issue, we cant derive pubkeys
(if you don't know the seed or the corresponding private key)

> is it me or our derive is kinda weird?
do we actually ever derive from n-1 to find n?
doesn't look like it so I think derive should return a different DerivedKey structure, the chaincode of a child is never used
right?

We use the wallet seed to derive an initial extended key.
We then use this initial extended key to derive all other keys (based on n).

We do not use key `n-1` to derive key `n`.

The `chaincode` is only useful on the "master" key, we do not need to actually use and maintain state on every derived key.

Proposal - 

* `ExtKey` is an extended key (with additional 32 byte chain code)
* `ChildKey` is the thing we derive from an ExtKey 
  * chain code from `ExtKey` required to derive a `ChildKey`
  * no chain code on `ChildKey` itself

See https://bitcoin.org/en/glossary/extended-key and https://bitcoin.org/en/glossary/child-key for related terminology in bitcoin.

Related - #590.

**Comment by antiochp** [comment]
We also have `depth` in ExtKey currently. This is not currently used for anything but the intent _appears_ to be related to the idea of having multiple "wallets" (ExtKeys), each with their own derived set of ChildKeys.

**Comment by ignopeverell** [comment]
Looks to me like this was trying to do something like BIP32 but ended up half-assed. Would we actually use your 2nd bullet point?

**Comment by antiochp** [comment]
Probably little value in it today.
I could see it potentially being useful in the future (but we can add this functionality back in if needed in the future).
