### ISSUE TITLE
store sumtree tests failing randomly

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#658]
Just saw the following pass 15 times in a row -
`cargo test -p grin_store sumtree`

Then it failed randomly on the next run - 

```
running 4 tests
test sumtree_append ... ok
test sumtree_prune_compact ... FAILED
test sumtree_reload ... FAILED
test sumtree_rewind ... ok

failures:

---- sumtree_prune_compact stdout ----
	thread 'sumtree_prune_compact' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- sumtree_reload stdout ----
	thread 'sumtree_reload' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `16`', store/tests/sumtree.rs:132:4


failures:
    sumtree_prune_compact
    sumtree_reload

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

Thanks @mfronczyk for originally reporting this in gitter.

**Comment by antiochp** [comment]
And its not always the same test that fails when we see a failure - 

```
running 4 tests
test sumtree_append ... FAILED
test sumtree_reload ... ok
test sumtree_prune_compact ... ok
test sumtree_rewind ... ok

failures:

---- sumtree_append stdout ----
	thread 'sumtree_append' panicked at 'assertion failed: `(left == right)`
  left: `HashSum { hash: 1aa65473, sum: 11 }`,
 right: `HashSum { hash: 0e3d91b1, sum: 4132 }`', store/tests/sumtree.rs:65:2
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    sumtree_append

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by antiochp** [comment]
Is this a concurrency issue with the tests? Is the cargo test runner running more than one of these in parallel and they are stomping on each other?

**Comment by sesam** [comment]
[I had the same problem](https://www.dropbox.com/s/mucc1616iou3iig/cd_store_%26%26_cargo_test.mov?dl=0)

Concurrency (race condition) or sumtree bug?

Lets compare Cargo.lock files. Mine: `cat Cargo.lock | nc termbin.com 9999` => http://termbin.com/2r9d

**Comment by sesam** [comment]
On master, before 20575252 #555 I get "Could not compile rocksdb" and right after I get the spurios errors for grin test in store. I'm updating my dev. env. all the way now; OS updates, `rustup update` etc and hoping there's something in the toolchain that will change this for the better.

Another option could be trying a fresh checkout, going to a really old commit, and only cherry-picking 20575252 on top of that - I'm leaving that task to someone with a faster workstation :) #helpwanted
