### ISSUE TITLE
Miner is running while syncing in progress.

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#692]
Now, the miner thread is paused for 5 seconds as seen in the link below. However, what I see is the miner is building blocks for mining while the server is still syncing. That causes slow-down of syncing.
https://github.com/mimblewimble/grin/blob/b90b4b17cc828cad032c82f70d5dd4211c242154/grin/src/server.rs#L220 (both internal and plug-in miners do not pause while syncing.)

The miner should be paused while syncing is in progress for more efficient syncing the chain.

**Comment by yeastplume** [comment]
Think this needs to be addressed now. I'm going to close this issue and open a similar one.
