### ISSUE TITLE
Test valid reorgs older than horizon

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#697]
The node should get back into fast-sync mode and resync.

**Comment by hashmap** [comment]
I'd like to tackle this one, but appreciate if someone elaborates a bit

**Comment by ignopeverell** [comment]
Thanks for the offer for help! Fast sync takes a snapshot of the current MMR state and transfers it over to the new syncing node. To avoid the messiness of recent reorgs, the state that's transferred is set to be `horizon` blocks back. Then the regular sync takes over to catch up to the latest, downloading full block bodies.

Because of this, if a long reorg occurs, forking even further backward than `horizon`, a node won't be able to validate the fork. So normally, it should get back into fast sync mode and try to get the state for that new fork.

The actual value for the horizon is defined here:

https://github.com/mimblewimble/grin/blob/master/core/src/consensus.rs#L69

But it can be overriden to a much smaller value in globals to make testing easier:

**Comment by hashmap** [comment]
wow, thanks a lot, very helpful

**Comment by garyyu** [comment]
Just find this quite old requirement. I suppose it's already done by https://github.com/mimblewimble/grin/pull/1902 with a test case `simulate_long_fork`.

But please note that because of the long test time, I set `ignore` for this test case.

So, perhaps we can close this one.  Is OK for you? @ignopeverell

**Comment by antiochp** [comment]
This can be closed. :+1:
