### ISSUE TITLE
MimbleWimble relies on Elliptic Curve Cryptography -- Any post quantum candidates? 

### ISSUE THREAD

**Issue by nathanawmk** [mimblewimble/grin#701]
Quantum computers break public-key cryptography currently in use. i.e. cryptosystems based on factoring and (elliptic curve) discrete logarithms. Any post quantum candidates that MimbleWimble look to incorporate in its protocol?

**Comment by ignopeverell** [comment]
This belongs more in http://www.grin-forum.org.
