### ISSUE TITLE
Attempt to recover from isolated orphaning

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#705]
Due to occasional bad network conditions, a node can miss a block. When the next one is received and detected orphaned, we should at least try a request for the previous block, assuming it's not already an orphan in itself and we're not syncing already.

**Comment by mably** [comment]
Was forked again at height 73296:

https://gist.github.com/mably/9af1b92bbdcd27dba1a8ae1884ed8804

**Comment by hashmap** [comment]
I'd like to tackle this.

**Comment by ignopeverell** [comment]
Fixed by #724
