### ISSUE TITLE
Dandelion relay and aggregation for transactions

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#706]
This follows from #693 (and actually reading the paper [1] and the BIP [2]). From where we stand, implementing Dandelion seems somewhat straightforward, and adding a transaction aggregation phase specific to Grin, would offer an attractive anonymity boost.

The main tweaks to our current protocol would be:

* regularly elect 2 nodes for Dandelion relay
* add a Dandelion transaction relay message type
* aggregate a received valid Dandelion transaction with all other Dandelion transactions
* relay a valid Dandelion transaction as Dandelion 90% of the time, otherwise diffuse as we do now
* accept pool replacement for valid a Dandelion transaction with a strict (input, ouput, kernel) superset
* monitor our transactions so we can re-send if we never see them from the fluff phase

We currently do not support any transaction pool querying or transaction hash relays as bitcoin does, so we do not need to worry about specific pool policies or exclusion beyond the above. Please let me know if I forgot something important or if this would break something else

Paging @gfanti in case she'd like to follow this.

[1] https://arxiv.org/pdf/1701.04439.pdf
[2] https://github.com/gfanti/bips/blob/master/bip-dandelion.mediawiki

**Comment by antiochp** [comment]
#693 (not #687) I think?

**Comment by quentinlesceller** [comment]
Conversation here https://gitter.im/grin_community/dev?at=5a8c48866f8b4b99469bcaca.

**Comment by quentinlesceller** [comment]
More discussion with Giula Fanti https://gitter.im/grin_community/dev?at=5a8ee54f6f8b4b9946aa8ca6

**Comment by quentinlesceller** [comment]
Discussion here https://github.com/mimblewimble/grin/pull/732#issuecomment-369256394

**Comment by quentinlesceller** [comment]
Little simulation of Dandelion with a few nodes on paper. https://drive.google.com/file/d/1Yzcrs1dJ8N8SRPk26JtV_iturfjJAwqy/view?usp=sharing. Transactions are [Input,Output,EmbargoTimer]. This one simulates a failed tx cut through.

**Comment by quentinlesceller** [comment]
More discussion on using lock_height as aggregation parameter: https://gitter.im/grin_community/dev?at=5a96e1978f1c77ef3a685640.

**Comment by ignopeverell** [comment]
I'm good with this as a base to start.
