### ISSUE TITLE
Grin server won't run at basic execution

### ISSUE THREAD

**Issue by PanosChtz** [mimblewimble/grin#708]
Hello,
I compiled grin successfully with no errors. After creating the 'node1' directory and copying the 'grin.toml' file to in (used the default configuration, so I didn't change anything to it), I get the following results:

`~/grin/node1$ grin wallet -p "password" listen`

And on the second terminal window:
```
~/grin/node1$ grin server -m run
Feb 13 16:00:56.328 WARN P2P server started on 0.0.0.0:13414
Feb 13 16:00:56.329 WARN Grin server started.
```

It sits there and doesn't do anything.
Any suggestions?
Thanks

**Comment by CarstenHouweling** [comment]
Hi PanosChtz, What does your node1/grin.log say?

**Comment by PanosChtz** [comment]
grin.log contains a ton of stuff. I left it running today for about 3-4 minutes and the log was over 10MB, so I can't really make up anything useful from it to post here.
Also I am now getting the following output:

`~/grin/node1$ grin server -m run
Mar 01 10:48:43.720 WARN P2P server started on 0.0.0.0:13414
Mar 01 10:48:43.722 WARN Grin server started.
Mar 01 10:49:59.123 ERRO slog-async: logger dropped messages due to channel overflow, count: 184
Mar 01 10:51:04.612 ERRO slog-async: logger dropped messages due to channel overflow, count: 105
Mar 01 10:51:20.913 ERRO slog-async: logger dropped messages due to channel overflow, count: 107
Mar 01 10:51:20.913 ERRO slog-async: logger dropped messages due to channel overflow, count: 1
`
