### ISSUE TITLE
Message hiding in Bulletproofs

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#721]
Breaking out from https://github.com/mimblewimble/grin/issues/273, we need the wind a message into a bulletproof similarly to how it could be done in 'Rangeproof Classic'. This is an absolute requirement as we need to embed an Output's SwitchCommitHash (which is otherwise not committed to) and embed an output amount for wallet reconstruction.

We should be able to embed up to 64 bytes of message without too much difficulty, and another 32 with more difficulty (see original issue). 64 should be enough for the time being.

**Comment by yeastplume** [comment]
Just pinging @apoelstra  here for a question, (if you manage to see this before I figure out the answer).

From the previous thread:'Ok, I can get you 64 bytes without much trouble (xoring them into tau_1 and alpha which are easy to extract from tau_x and mu if you know the original seed used to produce the randomness).'

I've been digging into the code now and see how this should work, I'm just trying to figure how to get extract tau_1 and alpha back from the stored taux and mu. From what I can gather, it seems that getting alpha should be:
```
alpha = -mu - Rho*X
```
Where mu is available from the Proof, Rho can be re-derived using the RNG seeded with the same nonce (or blinding factor in this case). Then tau1 should be derivable from that. The only thing I'm puzzling over a bit is the challenge X, which I'd thought was just the commit, but it actually seems to rely on a big long chain of calculation before it becomes available. Am I on the right track here with getting alpha and tau1 back here, and if so, is there a simpler way of deriving the challenge X from the commit?

**Comment by apoelstra** [comment]
The verifier computes `x` as well, I think the code is easier to see there: https://github.com/apoelstra/secp256k1-mw/blob/bulletproofs/src/modules/bulletproof/rangeproof_impl.h#L214

Essentially you get it by hashing A, S, T1, T2 and whatever `extra_commit` there might be.

**Comment by yeastplume** [comment]
Ahh, brilliant, didn't notice it being calculated in the verifier as well... I can just return it as an out value from the verify function (I've modified my fork to return taux and mu as well).

Thanks! Will ping you when all of the changes are done, in case you want to fold any of them back upstream.

**Comment by apoelstra** [comment]
Awesome, thanks!

**Comment by yeastplume** [comment]
Just an update, @apoelstra I have a working (and unoptimized) implementation of this in our fork, around here: https://github.com/mimblewimble/grin/issues/721#issuecomment-367428809. Not sure if you want to take this back upstream due to it not working with aggregated proofs, but it's there as a start if you want it include it.

**Comment by yeastplume** [comment]
Addressed via https://github.com/mimblewimble/grin/pull/730
