### ISSUE TITLE
Internal Renaming due to Storage Changes

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#723]
After https://github.com/mimblewimble/grin/pull/702, PMMRTrees aren't sumtrees anymore, they're PMMR trees that store hashes, and the tree's node indexing optionally references data in flat storage files.. many variables and structure names which currently reference sumtrees should be renamed for clarity. Before this can happen, we need to decide on what names we're going to use for things.

* I'm thinking Sumtrees -> Hashtrees, however there's a data storage element that we might want to reflect in this. Also, should the term PMMR be exposed or would we only leave that in points in the code where it's an implementation detail? Would PMMRTrees be more appropriate? 
* The structure in chain/sumtree.rs currently called SumTrees that now holds all of the PMMRTrees.. can we refer to this as overall TXOSet? It contains utxos, rangeproofs and kernels, all of which are 'Transaction OBjects' (unless there's a more specific meaning for this term that I don't know)
* the object within that called utxo_pmmr_h should probably just be output_pmmr (for better clarity) but I think I changed this originally so my fault.

There are probably a couple more if anyone can think of any. If we can solidify this here I can go make the changes (which more annoying than you'd realise due to the number of references in the code and comments).

**Comment by ignopeverell** [comment]
I'm good with Hashtrees. I was thinking of leaving PMMR as an implementation detail.

TXOSet is a little ambiguous, as it usually means transaction Ouputs. How about TxHashSet? I agree for output_pmmr.
