### ISSUE TITLE
Use header hash for "by height" index

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#744]
We need an index of block header height to the actual block header for various operations. Right now this index stores the full block header for value. To avoid storing all headers twice (by hash and by height), we should have the index only store the header hash for value and do one more query to get the full header from its hash.

It should be easy to have this completely contained in `chains/src/store.rs`.

**Comment by antiochp** [comment]
:+1: this was on my mind a few weeks ago with the compact block work (then promptly forgot about it).

**Comment by aedesymen** [comment]
Hi, I'm new here and would like to contribute, maybe I can look into this one

**Comment by sesam** [comment]
@aedesymen have a look, and come to https://gitter.im/grin_community/dev with any general questions, how to get up and runnning etc. There you'd also see that nobody has yet asked to take this, so you can go ahead :)

**Comment by aedesymen** [comment]
@sesam thanks, then I will take this one :)

**Comment by antiochp** [comment]
Resolved in https://github.com/mimblewimble/grin/pull/761
