### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#750]
With the abundance of switches, mining, and sync options in testnet2, the need for a more fully complete User Guide is becoming more apparent. Some discussion might be required in order to decide exactly where/how we want to achieve this and in what format (wiki, forum posts, etc). A lot of the information for the various options is scattered all over the place, it might just be a matter of collating them in a logical manner.

This would be a very, very helpful thing for someone who really wants to get more involved but doesn't necessarily have the coding background to take on.

**Comment by ignopeverell** [comment]
A nice simplification would also be to get rid of the config file for most uses. Someone should be able to run a binary without having to worry about default config.

**Comment by kargakis** [comment]
Or make grin generate the file with sensible defaults if not found.

**Comment by Bmwwallace** [comment]
I'm not a particularly skilled coder but I could collect all the data and information and and create a wiki for Grin if needed?
I could divide it into technical and non-technical sections and include the history of the development for those curious to understand its origins?

**Comment by quentinlesceller** [comment]
Take a look at https://www.grin-forum.org/t/mimblewimble-grin-resources/60/5
and https://www.grin-forum.org/t/existing-docs-and-resources/28 if you need some ressources.

**Comment by ignopeverell** [comment]
No need for a new wiki, there's:

https://github.com/mimblewimble/docs/wiki

**Comment by Bmwwallace** [comment]
Ah perfect no problem at all. Would it be alright to do a Wikipedia article on it and explain the background to its development and perhaps give an overview of the mathematical and cryptographic elements to it? I think it would be great to bring it to as many platforms and forums as possible and give people a real understanding of the complexities :)

**Comment by ignopeverell** [comment]
Sure.

**Comment by yeastplume** [comment]
Think we're okayish here with the wiki documentation
