### ISSUE TITLE
Building on Windows [help wanted]

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#764]
Building grin on Windows is not yet supported.

A reasonable first goal is to make the wallet usable, and leave mining and leave platform-specific features like daemonization  for later (i.e. only support `grin server run` in an open console window, no console-less `grin server start` support).

Help wanted: 
_check when tasks are done or not wanted_
- [ ] separate out daemonization so `grin server run` can function without the `unix` dependency ([discussed](https://gitter.im/grin_community/Lobby?at=5aa51feb35dd17022e478b92))
- [ ] document which build tools are required (autotools, msvc, mingw?)
- [ ] fix empty dependency folder ([discussed](https://gitter.im/grin_community/Lobby?at=5aa5242627c509a7744d4d28))
- [ ] probably use cmake instead of autotools for the windows builds? (upstream issue on this)[https://github.com/bitcoin-core/secp256k1/issues/451]
- [ ] maybe add a quick workaround: by including a secp256k1.dll for windows to make it easy to get started, and default skip building that dll on windows during `cargo build`
- [ ] and/or do something about compiler flags that can't accept Windows C:... paths:

````
running: "C:\\Program Files (x86)\\mingw-w64\\i686-7.2.0-win32-dwarf-rt_v5-rev1\\mingw32\\bin\\gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "depend/secp256k1-zkp/" "-I" "depend/secp256k1-zkp/include" "-I" "depend/secp256k1-zkp/src" "-g" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-DUSE_ENDOMORPHISM=1" "-DENABLE_MODULE_ECDH=1" "-DENABLE_MODULE_GENERATOR=1" "-DENABLE_MODULE_RECOVERY=1" "-DENABLE_MODULE_RANGEPROOF=1" "-DENABLE_MODULE_BULLETPROOF=1" "-DENABLE_MODULE_AGGSIG=1" "-Wall" "-Wextra" "/FoC:\\Users\\user\\code\\grin\\target\\debug\\build\\secp256k1zkp-f02ed7404e8c3e65\\out\\depend/secp256k1-zkp/contrib\\lax_der_parsing.o" "/c" "depend/secp256k1-zkp/contrib/lax_der_parsing.c"
cargo:warning=gcc: error: /FoC:\Users\user\code\grin\target\debug\build\secp256k1zkp-f02ed7404e8c3e65\out\depend/secp256k1-zkp/contrib\lax_der_parsing.o: Invalid argument
cargo:warning=gcc: error: /c: No such file or directory
exit code: 1
````

**Comment by boorishpea** [comment]
To fix the empty dependency folder, we need more help from Andrew P
There appears to be an outstanding task
https://github.com/mimblewimble/rust-secp256k1-zkp/issues/6

**Comment by yeastplume** [comment]
closing for now, can re-open if this is picked up again
