### ISSUE TITLE
kernel offsets not accounted for in extension.validate()

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#766]
I suspect we are not correctly offsetting the kernels in extension.validate() when we sum the unspent outputs and sum the kernels and compare the sums - 

https://github.com/mimblewimble/grin/blob/a8fcc37a364059248a87198162dc3563e79f547b/chain/src/txhashset.rs#L565-L578

Each block has a kernel offset that I think we need to account for here.
Tests are likely passing because we are using a default offset of 0 for each kernel.

I noticed this because I was attempting to add a call to `extension.validate()` immediately after compaction to try and verify the compaction had not corrupted the MMRs and it was always failing with `InvalidTxHashSet("Differing Output commitment and kernel excess sums.")` both _before_ compaction and after compaction.

Presumably we would need to sum all the kernel offsets in all the block headers in the chain?
And then use this to offset the total kernel sum.

cc/ @ignopeverell 

Resolved in #753. (This was cropping up when trying to validate post compaction, txhashset validation was failing with kernels not summing correctly).

**Comment by antiochp** [comment]
Related question - to sum the kernel offsets up for a large chain of block headers we need to traverse them one by one via the previous hash.
For a million blocks this is going a non-trivial amount of time.
Is it worth considering storing a total offset on each block header? 
Similar to how we maintain `difficulty|total_difficulty`.

Not suggesting we _should_ do this - just thinking out loud.

**Comment by ignopeverell** [comment]
Another nice catch, thanks for coming up with a fix as well.

And yes, I think the block header should include the total offset instead of the offset on that block.

**Comment by antiochp** [comment]
Will work on modifying how we store offsets in block headers in a separate PR.

**Comment by antiochp** [comment]
Fixed in #753.
