### ISSUE TITLE
Are we still burning 50% fee in master (testnet2)?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#767]
Did we come to a decision on how we are planning to handle the fee calculation?

https://github.com/mimblewimble/grin/blob/a8fcc37a364059248a87198162dc3563e79f547b/core/src/consensus.rs#L40-L42

**Comment by ignopeverell** [comment]
We are still burning half and I was planning to tackle this in the next few days. And yes, I do think we should just give miners the whole fee (so no more burning).
