### ISSUE TITLE
we are not currently pruning/compacting the data file

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#770]
This functionality was commented out and disabled as part of #753.
We _are_ compacting the hash file but the data file is left un-compacted.
Now that #753 is merged in we should investigate and get this working again.

https://github.com/mimblewimble/grin/blob/65633c7611c07fc2467e352dab5367789f0a05bd/store/src/pmmr.rs#L375-L396

https://github.com/mimblewimble/grin/blob/65633c7611c07fc2467e352dab5367789f0a05bd/store/src/pmmr.rs#L417-L423

**Comment by yeastplume** [comment]
looking into this ATM
