### ISSUE TITLE
PoW hash suggestions

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#780]
currently the nonce and pow are in the middle of the header.
it would look neater to have them at the end, since they must causally follow the other fields.
this also allow a slight simplification in miner/verifier code in that it can create the siphash key by
hashing a prefix of the full header, rather than having to elide a field from the middle.

note that there are two kinds of header hashes:
the pre-pow hash used as siphash key to define the cuckoo graph, and
the post-pow hash that must satisfy the difficulty target.

currently, the post-pow hash is a hash of the whole header including the pow.
i would prefer to have it be just the pow hash (or what i call cyclehash in my solvers),
since the cycle already commits to the header.
so then the post-pow hash would be blake2(cuckoo_cycle(blake2(header))),
which can be compared to bitcoin's   sha256(                         sha256(header))
it's like we have another hash function sandwiched in between two blake2 iterations.

**Comment by yeastplume** [comment]
I'm fine with this and have no problem implementing if everyone is in agreement.. it would actually remove awkwardness from miner.rs and within cuckoo-miner (both will need to be updated).

I'd wait until @antiochp is finished his current work on removing diff from the header.

**Comment by ignopeverell** [comment]
Agreed about having them at the end. I think it was originally that way actually, but then stuff got removed and stuff got added.

I think I agree with the post-pow hash as well.

**Comment by yeastplume** [comment]
Done
