### ISSUE TITLE
miner.rs cleanup

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#781]
There's no urgency to the work here, but I thought I'd open this to explain the current state of miner.rs. It looks like a mess, but this is why cleanup is a bit more than a trivial exercise:

* It evolved to support 3 different versions of 'miners', the built-in miner, single-threaded cuckoo-miner and async cuckoo-miner, all of which require slightly different workflows and have slightly different interfaces, hence the multiple 'inner_loops'
* I think the best approach overall would be to get rid of 2 of these and just leave the cuckoo-miner async mode, however:
  * Current automated tests are using a very reduced version of cuckoo for speed (cuckoo 10 at solution length 4 or something along those lines), and removing the internal miner means these tests have to be addressed. They were working too slowly at cuckoo 16 (especially on travis), hence the need for an even-more-reduced cuckoo size. Cuckoo miner plugins currently only support cuckoo 16 and 30 (and a fixed solution size at present, I think), so we'd either need another plugin built or move the tests back to cuckoo 16 and deal with any CI issues.
  * There is currently some overhead when using cuckoo-miner in async mode that will need to be profiled and optimised before I'd feel comfortable allowing it to be the only mode of operation.

All of these will need to be addressed sooner or later and miner.rs can be cleaned up once this is all dealt with, but I thought I'd leave this here for now to document it.

**Comment by sesam** [comment]
What options exist to make the CI "mining" even more trivial? Could we have an async-ish internal miner? Does external miners have to have high startup cost? Could the CI miner actually call into a public IP:port with a IP source filter to make it exercise actual real mining resources but offsite from the CI host? If this could reuse pool mining functions now getting built.

**Comment by quentinlesceller** [comment]
We can probably close this issue since the miner is now a separated project.
