### ISSUE TITLE
consider storing rm_log in a more compact format?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#782]
We currently persist the rm_log as a vec where each entry is a tuple consisting of the pos to remove and the index it was removed at, effectively the block height, to facilitate "rewind" to a previous block - 

```
[(1, 1), (2, 2), (3, 2), (4, 2)]
```

This can be read as "at index 1 we removed pos 1, at index 2 we removed pos 2, 3, 4".
The index is maintained per entry and there is some redundancy here in how we store this. 

Could we potentially store a vec of pos, per index?
This would still be "append-only" in the common case, we just append batches of pos at each index as we currently do.

```
[(1, [1]), (2, [2, 3, 4])]
```

One requirement is that we can search for a removed pos efficiently.
I'm not sure this proposed impl would still allow this easily?
On the other hand it would make `append()`, `rewind()` and `cutoff()` easier as these operate on chunks of pos based on index. 
So maybe it is worth exploring?

Given that a regular tx will likely spend multiple previous outputs (we incentivize keeping the UTXO set small over time) and that the rm_log is going to get pretty big on a full archival node over time - we likely want to try and store this as efficiently as possible.

Additionally - maybe we can store it in a more compact way, similar to how we do the prune list (where we only store roots of removed trees).
So in the above example, removing pos 3 implies pos 2 is also removed (at that index) - 

```
[(1, [1]), (2, [3, 4])]
```

This would still allow rewind etc to behave as before.
We would need to be smarter around how we determine if a pos is removed (no longer just a simple search) as we would need to consider removed parents etc.

**Comment by yeastplume** [comment]
Think this is included in more recent issues @antiochp (please reopen if needed)
