### ISSUE TITLE
Web wallet

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#789]
As @CarstenHouweling et al mentioned here https://github.com/mimblewimble/grin/pull/765#issuecomment-372938807 it would be a good idea to have some web wallet. Discuss here :)

**Comment by CarstenHouweling** [comment]
Good idea 👍 

I was personally thinking about a simple wallet.dat upload (input type=file). This will give the same coin info as the grin wallet info command (total, awaiting confirmation, confirmed but locked, currently spendable & locked by prev. transactions). Very quick and easy but also very limited to coin info only.

Most ideal would be more functionality than that. As i discussed with @sesam in the gitter dev channel ([March 15, 2018 10:09 PM](https://gitter.im/grin_community/dev?at=5aaae11abb1018b37aeb7866)) the grin wallet would need to have endpoints available. Users will run their wallet locally, open a port to the wallet and enter the address and port into the webapp. Depending on the grin wallet endpoints, this will provide full functionality. This has my preference even though it requires a little bit of user-setup.

About the webapp itself: a publicly available webapp/wallet like that will be the front face of grin. Nice aesthetics would be a big plus for me personally. I don't know how everyone else sees this. As @sesam  mentioned in gitter: > One pager and no frameworks makes it easier to verify page security.

**Comment by ignopeverell** [comment]
Ideally the wallet would have a good Rust API layer. Then people could plug whatever they want on top of it, potentially using it from another programming language as well. Unfortunately we're pretty far from that right now. The wallet crate hasn't seen a lot of love lately. So hopefully we can focus on it a little more once testnet2 is out.

**Comment by CarstenHouweling** [comment]
Just wanted to leave this here for fun: https://carstenhouweling.github.io/grin-wallet

@ignopeverell when the wallet API comes available i can plug it right in :)

**Comment by yeastplume** [comment]
Started and exists, can open more specific issues if needed
