### ISSUE TITLE
API tests in crate Grin are failing randomly

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#796]
Just noticed that some of the API tests are failing for some obscure reason.
The test that fails is ```test_p2p```in ```api.rs```.

Error:
```
Mar 16 10:00:40.263 DEBG Error accepting peer 127.0.0.1:53308: Connection(Error { repr: Custom(Custom { kind: WouldBlock, error: StringError("read_exact") }) })
Mar 16 10:00:40.263 INFO Starting HTTP API server at 127.0.0.1:40005.
Mar 16 10:00:41.002 ERROThread 'unnamed' panicked with message:
"called `Result::unwrap()` on an `Err` value: P2P(Connection(Error { repr: Os { code: 54, message: "Connection reset by peer" } }))"
```

**Comment by yeastplume** [comment]
I've just run all tests locally and I just managed to get my last PR through travis (which is up to date with master+my changes) https://github.com/mimblewimble/grin/pull/794.. is it possibly something local to your environment?

**Comment by quentinlesceller** [comment]
Maybe, I just updated my Rustc just in case. Going to try on another machine.

**Comment by quentinlesceller** [comment]
Okay so found out it's probably linked to my environment since the most common error I have now is:
```
thread 'simulate_fast_sync' panicked at 'called `Result::unwrap()` on an `Err` value: P2P(Store(RocksDbErr("IO error: While open a file for appending: target/grin-fast/grin-sync-1001/peers/MANIFEST-000001: Too many open files")))': src/libcore/result.rs:916stack backtrace:
```

**Comment by quentinlesceller** [comment]
Closing since it seems related to my operating system.
