### ISSUE TITLE
More compact MMR serialization (txhashset during fast sync)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#804]
#797 got me thinking about how we zip up the MMRs and send them over as part of fast sync.

If we know the (unpruned) size of the MMR then we know all the pos in advance.

So if we have the following - 
* unpruned size of the MMR
* roots of all pruned subtrees (and corresponding pos)
* existing data file
* existing rm_log
* existing prune_list

Then I think we have enough information to reconstruct the full MMR all the way up to the peaks?

So one possibility to reduce the amount of data being sent over the wire during fast sync may be to just send the above over. And the receiving node can then hash nodes together as necessary to reconstruct the full MMR.

Without putting any actual numbers on it it feels like this would be less data than sending the entire MMR across.
The tradeoff would be the increased cost of hashing on the receiving side.

For example - if we send `pos 1` and `pos 2` over then the receiving node can reconstruct the hash for `pos 3`.
Edit: The data elements for `pos 1` and `pos 2` will be in the data file, so we can create these hashes as well. I think we just need the pos for each element in the data file (and the roots of the pruned subtrees that won't be in the data file).

**Comment by tromp** [comment]
If I understand them correctly, then a pruned MMR corresponds to a sequence of data points, each of which is either
an unpruned leaf, labeled as such, or
a pruned merkle subtree hash, labeled as such with its size (not height, since rightmost branch can have non-full binary trees).

**Comment by ignopeverell** [comment]
@antiochp seems that could be a good optimization. Re-hashing is necessary anyway, you can't trust the hashes sent to you, so they all need to be checked.

**Comment by antiochp** [comment]
Some back of the envelope numbers for how much data would be involved.

```
2^20 outputs (single peak, height 20, for a simple example)
1,048,576 leaves
2,097,151 hashes in hash file

full unpruned hash file: 2,097,151 * 32 bytes ~= 67 MB


Scenario 1:
No pruned nodes, full hash file.
Prune list is empty.

Instead of sending the data file and the hash file across we could send just the data file
and simply reconstruct the hash file from the full unpruned data file.
We would save the full 67 MB by not sending the hash file.


Scenario 2:
Hash file 50% pruned (full left hand side).
Prune list would consist of a single pos (and we would need a single hash for that node).

Pruned hash file would be approx 33MB.
Instead of sending that across we could send the single hash (and the pruned data file).
We would save 33MB by not sending the pruned hash file.


Scenario 3:
50% leaves pruned (worst case, every other pair of leaves, only prune one level up).
Prune list would contain 50% non-leaf nodes at height 2.

Pruned hash file would be (2,097,151 - 524,288)* 32 bytes ~= 50.3 MB
Prune list would consist of 262,144 pos. 
So hashes would be 262,144 * 32 bytes ~= 8.4 MB

Here we would send 8.4 MB of "pruned" hashes rather than the 50.3 MB pruned hash file.
```

In all 3 scenarios we would send significantly less hash data.

The trade-off would be the increased processing cost in collecting the pruned hashes to send over, and then reconstructing the hash file on the receiving side. [tbd]

**Comment by ignopeverell** [comment]
Thanks for doing that.

**Comment by antiochp** [comment]
:+1: (you may want to check my math there)

**Comment by antiochp** [comment]
Closing this for now - we are going to revisit at some point anyway. No need keeping this issue open.
