### ISSUE TITLE
Port GPU miner to OpenCL

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#806]
The Cuckoo Cycle project at https://github.com/tromp/cuckoo currently offers a GPU solver only for CUDA.
It would be nice to support AMD hardware as well, which requires a port to OpenCL.

The HIP tool at https://github.com/ROCm-Developer-Tools/HIP should make this a lot easier.

**Comment by tromp** [comment]
Apparently, photon is planning an OpenCL miner:

https://www.grin-forum.org/t/finding-a-cycle-in-trimmed-edges-help/282/4

**Comment by siemiatj** [comment]
Is it possible to mine with GPU ? The grin_miner docs only discus CPU options.

**Comment by sesam** [comment]
Yes. The current best GPU miner is here: https://github.com/mozkomor/GrinGoldMiner

**Comment by yeastplume** [comment]
Think this exists now anyhow.. we can open an issue on grin-miner or cuckoo-miner
