### ISSUE TITLE
investigate rewind on every extension (even if no-op)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#812]
Related - #808 .

- [x] We should `force_rollback()` when calling `chain.validate()` (we `rewind()` but it is readonly and throwaway)
- [x] audit for other places where we `rewind()` to make sure we explicitly force rollback where necessary
- [x] ~investigate _always_ calling calling rewind() when starting a new txhashset extension (I don't think there are any reasons why we want to simply assume the head is the latest block, particularly with the one thread per peer networking)~

It should be safe to always `rewind()` to the latest block (and be a no-op 99% of the time).
In the cases where `rewind()` would have an effect because a new block was processed - we actually do want to rewind to keep things consistent.

So I propose we always rewind when starting a new extension.
Maybe the cleanest way to do this is to require a block header to be provided when starting a new extension?

And we should take care to consistently force a rollback on any extension that is "readonly".

**Comment by ignopeverell** [comment]
Maybe 2 different functions would be cleaner to differentiate between rewinds with or without rollback? I'm not against always rewinding but there are performance implications. A large rm log will take a bit of time to filter through, and I'm not sure what's the cost of truncate on the mmap'd files.

**Comment by antiochp** [comment]
Added `rewind_readonly()` in #847 to make the intent more explicit and remove the need for the caller to remember to set the force_rollback flag.
