### ISSUE TITLE
put index first in Merkle Tree hashing

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#814]
hashes for Merkle tree leafs and internal nodes are computed in ser.rs functions
```
impl<T: PMMRable> PMMRIndexHashable for T {
	fn hash_with_index(&self, index: u64) -> Hash {
		(self, index).hash()
	}
}

// Convenient way to hash two existing hashes together with an index.
impl PMMRIndexHashable for (Hash, Hash) {
	fn hash_with_index(&self, index: u64) -> Hash {
		(&self.0, &self.1, index).hash()
	}
}
```
The IETF standard at https://tools.ietf.org/html/rfc6962#section-2.1 uses
```
    MTH({d(0)}) = SHA-256(0x00 || d(0)).
```
for leaf hashes and
```
    MTH(D[n]) = SHA-256(0x01 || MTH(D[0:k]) || MTH(D[k:n])),
```
for internal node hashes.
The index we use in grin is like a generalized leaf/node tag, and in fact one can easily tell whether an index corresponds to a leaf or internal node. Since tags are commonly the first field in structured data, I feel it's better to change our rust functions above to use
```
    		(index, self).hash()
```
for leafs and
```
		(index, &self.0, &self.1).hash()
```
for internal nodes.

**Comment by antiochp** [comment]
I think we were actually putting the index first.
I _arbitrarily_ changed this to putting the index last based on something mentioned somewhere - let me see if I can find it...

**Comment by tromp** [comment]
I guess when making a change based on something mentioned somewhere, it's worth
mentioning the something in a comment:-)

Btw, I think we should have a label "consensus breaking" for changes such as these.

**Comment by yeastplume** [comment]
Labels enhanced in a non-consensus breaking manner

**Comment by antiochp** [comment]
:+1: 
I guess this was a convenient time to introduce a consensus breaking change.
I fought the urge to open may laptop for this last night...

**Comment by ignopeverell** [comment]
Couldn't resist, I'm to weak...
