### ISSUE TITLE
Error of Subtract with overflow in chain for the server with genesis block only. 

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#816]
Branch: master
- The solo server
- No sync
- No mining
- only genesis block exists.

Error:
thread 'apis' panicked at 'attempt to subtract with overflow', chain/src/chain.rs:558:53

for
curl "http://127.0.0.1:13413/v1/chain/compact"

Trace:
0: std::sys::\imp::backtrace::tracing::\imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   7: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:71
   9: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:51
  10: grin_chain::chain::Chain::txhashset_write::{{closure}}
             at chain/src/chain.rs:558
  11: grin_api::handlers::ChainHandler::get_tip
             at api/src/handlers.rs:393
  12: grin_api::router::router::RouterContext::handle
             at api/src/router/router.rs:73
  13: <alloc::btree::map::BTreeMap<K, V> as core::iter::traits::IntoIterator>::into_iter
             at api/src/router/router.rs:51
  14: grin_api::router::radixtrie::node::match_path
             at api/src/rest.rs:147
  15: <alloc::arc::Arc<\S> as tokio_service::Service>::call
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-service-0.1.0/src/lib.rs:241
  16: <hyper::server::SocketAddrService<\S> as tokio_service::Service>::call
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/server/mod.rs:824
  17: <hyper::server::NotifyService<\S> as tokio_service::Service>::call
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/server/mod.rs:851
  18: <hyper::proto::h1::dispatch::Server<\S> as hyper::proto::h1::dispatch::Dispatch>::recv_msg
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/proto/h1/dispatch.rs:325
  19: <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, B, T, K>>::poll_read_head
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/proto/h1/dispatch.rs:163
  20: <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, B, T, K>>::poll_read
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/proto/h1/dispatch.rs:86
  21: <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, B, T, K>>::poll2
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/proto/h1/dispatch.rs:67
  22: <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, B, T, K> as futures::future::Future>::poll
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/proto/h1/dispatch.rs:275
  23: <hyper::server::Connection<I, S> as futures::future::Future>::poll
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/server/mod.rs:585
  24: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/map.rs:30
  25: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/map_err.rs:30
  26: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/mod.rs:113
  27: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  28: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  29: futures::task_impl::std::set
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/std/mod.rs:78
  30: <futures::task_impl::Spawn<T>>::enter
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  31: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  32: tokio_core::reactor::Core::dispatch_task::{{closure}}
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:359
  33: <scoped_tls::ScopedKey<T>>::set
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
  34: tokio_core::reactor::Core::dispatch_task
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:358
  35: tokio_core::reactor::Core::dispatch
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:319
  36: <alloc::raw_vec::RawVec<T, A> as core::ops::drop::Drop>::drop
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:307
  37: tokio_core::reactor::Core::run
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:241
  38: <hyper::server::Server<S, B>>::run_until
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/server/mod.rs:456
  39: <hyper::server::Server<S, B>>::run
             at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.22/src/server/mod.rs:392
  40: grin_api::handlers::start_rest_apis::{{closure}}
             at /Users/checkpartyon/Workspaces/cryptocurrency/heunglee/grin/api/src/handlers.rs:677

**Comment by yeastplume** [comment]
no longer relevant
