### ISSUE TITLE
TUI Log/Error handling

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#821]
Just putting there here to keep me reminded. Currently, if there's a panic on any thread the panic is written to the log, but not into the TUI, therefore a user looking at it has no idea there was a problem (or has to guess that there's been a problem from the way the stats aren't updating properly. To mitigate this and make it more user friendly, we need a way of communicating from the logger (which also handles panics) to the TUI.

Current thinking is:

* Create an slog drain that writes its output to an mpsc channel
* TUI can instantiate and provide a listener to the logger on initiation
* logger can then send messages back to the TUI that contain log information as well as panic status. Warnings for panics can be displayed on screen (popped-up nicely, even), and as an added feature we can add a log viewer screen right in the TUI.

**Comment by JosephGoulden** [comment]
I'm gonna have a go at this.

**Comment by quentinlesceller** [comment]
Can we consider this fixed by #3064?
