### ISSUE TITLE
Unable to sync new node, corrupted, ban

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#822]
On trying to sync a new node to the pre-testnet2 chain (all peers at 3878 or so):

```
Mar 20 14:15:01.471 DEBG Asking 198.245.50.26:13414 for txhashset archive at 997 2d99b82f.
Mar 20 14:15:02.567 INFO Client 198.245.50.26:13414 corrupted, ban (UnexpectedData { expected: [30], received: [0] }).
```

Also odd that it's asking for 997, think that's just further evidence for https://github.com/mimblewimble/grin/issues/803

**Comment by yeastplume** [comment]
Can reproduce very consistently by just wiping .grin on the new node and trying to sync. Also suspect this is why the yeastmonster decided to ignore Ingo's puny chain and take over.

**Comment by ignopeverell** [comment]
Looking at this now. If you need to resync, you can configure node for archival, will do the old-style sync.

**Comment by ignopeverell** [comment]
This seems a little more widespread than anticipated, while it's consistently reproduceable with fast sync, I get occasional and seemingly random message errors with other peers:

```
Mar 20 14:29:19.318 INFO Client 89.101.91.246:13414 corrupted, ban (UnexpectedData { expected: [30], received: [0] }).
Mar 20 14:29:19.318 DEBG cleaning V4(89.101.91.246:13414), peer banned
```

**Comment by ignopeverell** [comment]
Was caused by outdated nodes that had different network message indexes.
