### ISSUE TITLE
Stop mining when sync is occurring

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#827]
The mining thread needs to be stopped or suspended when sync is active, as is fairly evident from initial pre-testnet2 ad-hoc testing. 

This is very evident on intial sync now when a node is configured for mining, has recieved all headers but hasn't started receiving blocks (or the fast-sync package).. in this case the sync flag is set to 'not syncing', the miner is kicked into action and confusingly tries to start putting blocks on top of what's being read.

There may be another issue in that the sync flag is being set to 'not-synching' too early in the fast sync process, but that should become evident while doing this.

**Comment by ignopeverell** [comment]
Right, there's a gap when requesting the state, the sync is setup to only do headers beforehand and so for a short amount of time sync gets turned off. But that's enough for mining to kick in. I think we could be a little more clever here.
