### ISSUE TITLE
folding suggestion

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#829]
pmmr.rs  lines 215..221 read
```
			let mut bagged = None;
			for peak in self.peaks.iter().cloned() {
				bagged = match (bagged, peak) {
					(None, rhs) => Some(rhs),
					(Some(lhs), rhs) => Some(lhs.hash_with(rhs)),
				}
			}
```
This is folding the function hash_with over the elements of self.peaks,
which should be a one liner using the rust function fold1

**Comment by hashmap** [comment]
`fold1` is a part `itertools` which is an external crate used in `grin` crate but not (yet?) in `core`. Is it ok to add as an additional dependency to `core`? 
With regular `fold` code is just a bit shorter, smth like 
```
	return Some(self.root) == Some(self.peaks.iter().fold(ZERO_HASH, |b, &p| {
				if b == ZERO_HASH {
					p
				} else {
					b.hash_with(p)
				}
			}));
```

**Comment by sesam** [comment]
@hashmap I'm a bit unhappy with adding dependencie in general. For this specific case, there might have been things happening around how our MMR trees are constructed that impacts (or replaces?) this code. Lots of activities last hours - I'm still busy catching up.

**Comment by tromp** [comment]
code to be obsoleted in https://github.com/mimblewimble/grin/issues/797
