### ISSUE TITLE
proposal - add an (optional) full chain validation after accepting each block

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#838]
I'd like to propose adding a flag in grin.toml that would optionally run a full chain validation (via txhashset validation) after successfully processing a new block.
(We'd skip rangeproof verification as this would be too slow and unnecessary).

I think this would give us an "early warning" that a node gets out of consensus (for whatever reason).
Particularly during `testnetx`.

But still make it easy to disable this behavior via the setting in grin.toml.

**Comment by ignopeverell** [comment]
Sounds good to me. Are you thinking of having it on by default for the first few weeks?
