### ISSUE TITLE
Miner thread panic

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#845]
Looks like the miner threads panic during ```simple_server_wallet```.

```
'miner' panicked at 'attempt to subtract with overflow': /home/travis/build/mimblewimble/grin/core/src/global.rs:265stack
```
After that the test run for 50 minutes.

Example of failed builds:
https://travis-ci.org/mimblewimble/grin/builds/356857673
https://travis-ci.org/mimblewimble/grin/builds/356874701
https://travis-ci.org/mimblewimble/grin/builds/356771515

**Comment by ignopeverell** [comment]
Fixed by 9d366fe
