### ISSUE TITLE
How to use wallet

### ISSUE THREAD

**Issue by mveljko78** [mimblewimble/grin#848]
After I type: 
node3$ grin wallet -p "password" -a "http://127.0.0.1:30001" -l 35000 listen

wallet shows command prompt (see attachment)
how to send money?
![grin_wallet](https://user-images.githubusercontent.com/9944710/37783468-dd6c8bf4-2df5-11e8-9ae7-2839a713fa53.JPG)

**Comment by sesam** [comment]
Hi, please come to https://gitter.im/grin_community/Lobby with usage questions. The community will help you there.
