### ISSUE TITLE
Why do we need to store the full list of peak hashes in the MMR-tree to calculate root of tree?

### ISSUE THREAD

**Issue by sergorl** [mimblewimble/grin#852]
I don't understand one moment in [pmmr.rs](https://github.com/mimblewimble/grin/blob/master/core/src/core/pmmr.rs): 
```rust
pub struct MerkleProof {
	/// The root hash of the full Merkle tree (in an MMR the hash of all peaks)
	pub root: Hash,
	/// The hash of the element in the tree we care about
	pub node: Hash,
	/// The full list of peak hashes in the MMR ??? Why is it here?
	pub peaks: Vec<Hash>,
	/// The sibling (hash, pos) along the path of the tree
	/// as we traverse from node to peak
	pub path: Vec<(Hash, u64)>,
}
```
So why we need to store the full list of peak hashes in the MMR to calculate root of MMR-tree. I'm sure that it's enough to store only siblings in field path, because I can recursively calculate next peak and get finished calculated root. Here is the scheme-picture to this situation: [png](https://github.com/sergorl/docs/blob/master/sibling.png) 
Then I just compare calculated root and original root. Am I wrong? Please, help me to figure out.

**Comment by sergorl** [comment]
fix mistake

**Comment by sesam** [comment]
the MMR/proof implementation get slimmed down soon - see https://github.com/mimblewimble/grin/issues/797

**Comment by antiochp** [comment]
@sergorl Yes - this was actually being discussed the past couple of days in #797.

But in your diagram, what you label as "peaks" are not actually peaks in the MMR.

The peaks would actually be more like this (3 peaks in this example) - 

```
   /\
  /  \
 /\  /\  /\
/\/\/\/\/\/\/\
```

The overall root is generated from the list of peaks in the "mountain range".

**Comment by sergorl** [comment]
**@antiochp**, thank you for your explanation about peaks! So are peaks need to get original root of tree and then compare it with root, calculated from siblings?

**Comment by antiochp** [comment]
Yeah - each "mountain" in the mountain range generates a peak (root of the individual mountain).
The peaks are then all hashed together to generate the final root for the MMR.

The work proposed in #797 makes this "bagging the peaks" process more consistent with the nodes in the mountains themselves - end result is we can use handle the peaks via additional entries in the sibling path (rather than as a separate list of peaks).

**Comment by ignopeverell** [comment]
And to be clear, the above code isn't used at all to maintain the MMRs. This structure is an extraction of a Merkle Proof from the MMR.

**Comment by sergorl** [comment]
**@antiochp**, what is the situation when we have a few trees with different own peaks? Is it possible because of pruning? Or does it happen when  we combine three different transcations?
P.S.: In your example there are three treess with three peaks.

**Comment by antiochp** [comment]
It is "append only" so if add 4 leaves to an empty MMR we get a single peak - 
```
 /\
/\/\
```

If we then add two more leaves we get the following (two peaks) - 
```
 /\
/\/\/\
```

Etc.

**Comment by antiochp** [comment]
And adding 2 more leaves will cause the 2 peaks to collapse into a single (higher) peak, with the 8 leaves beneath it.

```
   /\
  /  \
 /\  /\
/\/\/\/\
```

**Comment by sergorl** [comment]
So it's just a way of store tree nodes in case when we add many groups of leaves sequentially, isn't it? Is it the main conception of full MMR-tree?

**Comment by antiochp** [comment]
Not even many groups of leaves. Adding any new leaves will always be "append only", we never need to go back and modify data already added. Anything new is appended to the right (both in the tree structure and in the file itself).

**Comment by sergorl** [comment]
Is it normal that in this situation we can have unbalanced tree?

**Comment by antiochp** [comment]
Yes - this particular mountain range (with say 6 leaves) will always look _exactly_ like this and will always be unbalanced.

**Comment by sergorl** [comment]
Ok, thank you. What is prunable MMR? What's the main difference between MMR- and PMMR-tree?
