### ISSUE TITLE
What is prunable MMR-tree in the context of transaction input?

### ISSUE THREAD

**Issue by sergorl** [mimblewimble/grin#857]
I've got MMR-tree, but I still don't understand *prunable* MMR-tree.  I see on this code:

```rust
pub fn prune(&mut self, position: u64, index: u32) -> Result<bool, String> {
		if let None = self.backend.get(position, false) {
			return Ok(false);
		}
		let prunable_height = bintree_postorder_height(position);
		if prunable_height > 0 {
			// only leaves can be pruned
			return Err(format!("Node at {} is not a leaf, can't prune.", position));
		}

		// loop going up the tree, from node to parent, as long as we stay inside
		// the tree.
		let mut to_prune = vec![];

		let mut current = position;
		while current + 1 <= self.last_pos {
			let (parent, sibling, _) = family(current);

			to_prune.push(current);

			if parent > self.last_pos {
				// can't prune when our parent isn't here yet
				break;
			}

			// if we have a pruned sibling, we can continue up the tree
			// otherwise we're done
			if let None = self.backend.get(sibling, false) {
				current = parent;
			} else {
				break;
			}
		}

		self.backend.remove(to_prune, index)?;
		Ok(true)
	}
```
and here I see that we get all parents on path frоm node to root and place them to *remove_list*... 

So there are my questions about pruning appplication in the context of input of transaction:

- Is this *remove_list* only to delete parent-nodes in the future? 
- PMMR-tree is one for all inputs of all transactions in one block, isn't it?
Or is it unique for every input of transaction?
- What does *index* mean like fucntion argument?

**Comment by antiochp** [comment]
The MMR is for the _entire_ transaction output (TXO) set over the full block chain at the point in time of the given block (we commit to the root of the PMMR in each block header).
So all transaction outputs across all blocks back to the genesis block.

On a "full archive node" the remove log is simply the full list of positions in the MMR of spent outputs.
On a "pruned" node we take the remove log and turn it into a more compact "prune list" during pruning.
If we spent output at pos 1, then 1 is pushed onto the remove log.
If we then spent the output at pos 2 we would push 2 onto the remove log.
This would also allow us to push 3 onto the remove log (the parent pos of 1 and 2).
When pruning we would only add pos 3 to the prune list (to represent pruning 1, 2 and 3).

The `index` is the block height that an output was spent, so here it is used to provide a "cutoff" block height, where we prune anything spent earlier than that.

**Comment by sergorl** [comment]
**@antiochp**, I try to understand your answer... So MMR-tree is a storage of output (TXO) of full blockchain and each net node store this data structure, isn't it? But when does net node prune MMR-tree (in what cases)?
P.S.: I want to realize conditions of pruning.

**Comment by antiochp** [comment]
In the context of the code you posted above - I believe "prune" there refers to when an output is spent.

Pruning here means the position of the element in the MMR (and potentially positions of ancestors in the MMR) will be added to the "remove log".

The data will not actually be pruned/compacted out of the MMR files until the remove log reaches a certain size (and only on a non-archival node).

**Comment by ignopeverell** [comment]
Closing this now. I need to write some much better docs on the MMRs and their storages.
