### ISSUE TITLE
Question - STXO MMR (aka the rm_log)?

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#859]
[Just thinking out loud here, but wanted to put it somewhere for reference.]

Right now we have a "remove log" and a "prune list" but we do not explicitly commit to these anywhere and they are are not part of the consensus data.

What if we stored the rm_log itself as an MMR?
Each leaf is a `(pos, index)` that is appended every time an output is spent.
The `pos` points back to the output MMR.
The `idx` is the block height (as we do today in the existing rm_log).

This MMR can always be aggressively pruned - in fact, so aggressively that as soon as you append a pair of leaves you can prune them back out again.
But before we do this we can - 
* build up the MMR (so we have peaks and a root)
* build a Merkle proof if we want (proof of inclusion here is proof of spend?)

Benefits (?)-  
* It's always append only (fits nicely into the existing MMR data structure).
* We get rewind of the rm_log effectively for free (particularly if we track the pos in the block marker index).
* The hash file could be aggressively pruned and compacted and remains relatively small (even though it tracks the majority of outputs over time).
* This "spent" MMR gives us a root that we can commit to (feels like this would be beneficial?)

Feel free to shoot this down as pointless/flawed - just thinking out loud and wondering about this.

**Comment by ignopeverell** [comment]
Interesting. Related thoughts, with no particular conclusion:

* The rm log isn't a particluarly interesting structure in itself. It's just an optimization to avoid too much data files churn and facilitates rewind. But we could compact and include in the prune list after every block (ignore merkle proofs extraction for a sec). It definitely has no place in consensus stuff.
* The prune list is more interesting. It's a list of all subtrees that have been pruned from the main MMR. I see it as the negative view (as in negative space) of the PMMR. It's also all peaks. I could see us committing to something like that.

What you're proposing is more alongside the prune list. I'm not sure we could make good use of it for Merkle proofs if they're pruned so aggressively. Space-wise, the prune list seems more optimal. Maybe there's something in between.

**Comment by tromp** [comment]
I like the idea of a STXO MMR, but I'm not sure what form the leaves should take.
Instead of (pos, index), one could just have pos.
A full node can easily map pos to the first block where n_outputs > pos, i.e. where the output was introduced.

Commiting to a pruned MMR is less flexible, since it forces full nodes to have a particular high maintenance data structure that's not append-only, even if we later find alternative more efficient data structures to track spent-ness state.

**Comment by antiochp** [comment]
I'm reading back through this and something is confusing me a bit.

Does the rm_log (in conjunction with the prune_list) not define _exactly_ which outputs are spendable and which are not spendable?
If we (fast sync) the txhashset from a peer - how do we know we have not been lied to about a particular output still being spendable?

An output at `pos n` could be in one of several states - 
1. unspent (still in the MMR, not in the rm_log)
1. spent (still in the MMR, but included in the rm_log)
1. spent (compacted out of the MMR, it or an ancestor included in prune_list)

The roots are the same for all the above scenarios (roots commit to the full TXO set).

The only thing differentiating (1) and (2) above is the contents of the rm_log.
So how do we know a peer has sent us the "correct" rm_log and has not altered it in any way?

I'm guessing we'd need to commit to something that covered both the rm_log _and_ the prune_list (in some form)?

The rm_log is just an optimization to avoid excessive churn on the files.
The prune_list is necessary to know how to accurately read the compacted hash and data files.
But neither is sufficient to know the state of the unspent (UTXO) set.
We need a combination of both.

**Comment by antiochp** [comment]
Ahh - I think `get()` was split into `get_data()` and `get_hash()` for readability at some point.
A call to `get()` used to return `(hash, data)` and we needed to then use `.0` or `.1` to get the respective parts.
What's the issue if we're no longer using `get()`?

**Comment by ignopeverell** [comment]
Nevermind that question. I got `get_data` confused with `get_data_from_file`. So that should check the rm log, which would lead to an incorrect utxo sum if it were lying.

**Comment by antiochp** [comment]
Closing - this is resolved with the new `leaf_set` bitmap impl and the MMR sizes and sums stored on the header.
