### ISSUE TITLE
merkle tree sizes in header

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#864]
It might be prudent to add two more header fields:

// number of outputs
n_outputs: u64;
// number of kernels
n_kernels: u64;

and these would also be necessary for non-full nodes to verify the revamped merkle proofs.

**Comment by ignopeverell** [comment]
At this point we don't really know what lighter nodes will look like, my guess is that the MMRs aren't going to be anywhere close to the more demanding areas in performance of data. So premature maybe?

**Comment by tromp** [comment]
Yes, not strictly necessary. But potentially convenient to have the two primary measures of blockchain size directly available...

**Comment by tromp** [comment]
I'd also like to have

// number of spent outputs
n_spent: u64;
// amount of burnt grin
nanos_burnt: n64;

assuming we opt for Small Block Incentives based on burning...

**Comment by antiochp** [comment]
Resolved in #1163 (kernel and output MMR sizes added to header).
