### ISSUE TITLE
Additional fees for Merkle proofs

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#873]
Right now they're free. Note that it doesn't necessarily matter to spend mining rewards are miners can always include their transactions for free, but in the general case they need to pay for the extra bandwidth usage.

**Comment by ignopeverell** [comment]
How large would the average proof be?

**Comment by hashmap** [comment]
If you have spare time I'd appreciate some context, I can't make any connection between fees and Merkle proof:)

**Comment by antiochp** [comment]
@hashmap Merkle proofs are relatively large (in terms of bytes).
So we want them to come with higher fees to prevent people spamming the network with large txs.

**Comment by antiochp** [comment]
We can't prevent a wallet impl from adding Merkle proofs to every input in lots of txs.

**Comment by hashmap** [comment]
Thanks, let me check if I'm able to help
