### ISSUE TITLE
[Enhancement] Removing hyper/iron dependencies on Api library.

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#876]
Currently Api library depends on hyper and iron with underlying Future and Tokio crates for async processing of http requests between the server and the wallet, and between wallets. The dependencies are heavy and iron is not actively maintained after hyper dumped to 0.11. Also grin uses iron for server and hyper for client, which causes conflict on error handling between the server and the wallet. (refert to https://github.com/mimblewimble/grin/issues/642). 

The requirements of Api library is Http protocol and json support for the server and the client. And the traffic is not significant. The data communication of wallet is limited by the function of locking the wallet data file. So no need of heavy duty web server. And the same for the communication between the server and the wallet.

The goal for this enhancement is easy maintenance with the requirements above fulfilled. The target http stack is a single (or very limited number of) thread(s) based on std.net, std.io, http crate and httparse create.

**Comment by yeastplume** [comment]
This is underway by @hashmap  (perhaps you can update or edit this issue)
