### ISSUE TITLE
TUI Improvements/Enhancements Suggestions

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#890]
TUI development is ongoing in the background, and will hopefully be improved and refined over time. Please put all requests for enhancements or changes to the information shown on the TUI here, and I'll get to them in whatever order seems to make the most sense.

**Comment by hashmap** [comment]
- Total number of nodes
Not sure if this functionality is already implemented in the core but:
- Banned peers (with reasons) + button to unban
- My bans by other peers (with reasons)

**Comment by tromp** [comment]
please show total difficulty together with height,
e.g. in Peers and Sync:
10862                     ->       10862 @ 87

and in Basic Status, add 
Total difficulty: 10862
below
Chain Height: 87

Related;  in grin.log, please show block hashes together with height, e.g.
adding block 016543cf.   ->   adding block 016543cf @ 21

Thanks!

**Comment by quentinlesceller** [comment]
It would be nice to see the Dandelion relay. Maybe in another color so the peers list stays light.

**Comment by tromp** [comment]
Oh, before I forget: please show every 42-cycle found by miner, together with cyclehash top 64 bits.

**Comment by sesam** [comment]
Usability:
* add "Esc" in legend in bottom left corner
* implement Esc also on peers page

Low prio:
* peers page: unshadow the "selected" entry when you're not in there "with cursor"
* front / status page: instead of just cumdiff or just height, I suggest "cumdiff @ height [hash]" because this is how it's (slowly) being standardised all over grin

**Comment by ignopeverell** [comment]
Looking forward to the day the TUI looks like SAP R2.

![image](https://user-images.githubusercontent.com/22927561/37996521-da6f0184-320f-11e8-8b88-6c9f7db41e68.png)

**Comment by yeastplume** [comment]
@ignopeverell that's a true thing of beauty, and something to be aspired to.

**Comment by tromp** [comment]
Sort the peer list by (State, Total Difficulty, Address)

In Mining Difficulty list, remove not-very-useful "Distance from Head" column.

**Comment by tromp** [comment]
there's a bug in that Average Difficulty is currently 0.
That can never be. It looks like it only summed 59 rather than 60 difficulties?!

**Comment by quentinlesceller** [comment]
Display the number of verified range proofs during the fast sync ?

**Comment by hashmap** [comment]
@yeastplume should we close it?
