### ISSUE TITLE
full sync appears to be churning a lot

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#897]
The sync process is pretty rudimentary - 
* every 5s
* look back over longest chain of headers
* look for earliest blocks we have not yet processed
* go request them from peers with more work than us

This worked pretty well when we had tokio in there at p2p layer and all peers ran on the same thread.

The networking rewrite (each peer in separate thread) means this sync process no longer works as well.
Seeing a lot of "churn" as we pull blocks back in large quantities in what appears to be a pretty randomized order.
I think we are asking for a large chunk of low height blocks, then because we haven't received them yet go ask for them a 2nd (or third) time. Then as we process them we start requesting more blocks at higher heights, but we are still receiving lower height blocks in the meantime and they are getting interleaved.

```
Mar 28 07:46:41.097 DEBG Received block 3e19a6ce at 533 from 139.59.105.169:13414, going to process.
Mar 28 07:46:41.098 DEBG pipe: process_block 3e19a6ce at 533 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.146 DEBG process_block: orphan: 5440dc4b, # orphans 287
Mar 28 07:46:41.148 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.149 TRCE handle_payload: Block 133dd65d
Mar 28 07:46:41.149 DEBG Received block 133dd65d at 549 from 167.99.87.54:13414, going to process.
Mar 28 07:46:41.150 DEBG pipe: process_block 133dd65d at 549 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.201 DEBG process_block: orphan: 256a0c8e, # orphans 288
Mar 28 07:46:41.202 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.203 TRCE handle_payload: Block 0dff3399
Mar 28 07:46:41.203 DEBG Received block 0dff3399 at 750 from 159.203.22.5:13414, going to process.
Mar 28 07:46:41.204 DEBG pipe: process_block 0dff3399 at 750 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.213 DEBG process_block: orphan: 28c90f98, # orphans 288
Mar 28 07:46:41.215 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.215 TRCE handle_payload: Block 1740ce9e
Mar 28 07:46:41.216 DEBG Received block 1740ce9e at 878 from 198.245.50.26:13414, going to process.
Mar 28 07:46:41.216 DEBG pipe: process_block 1740ce9e at 878 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.232 DEBG process_block: orphan: 352e5012, # orphans 289
Mar 28 07:46:41.234 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.236 TRCE handle_payload: Block 1401c685
Mar 28 07:46:41.236 DEBG Received block 1401c685 at 520 from 51.15.219.12:13414, going to process.
Mar 28 07:46:41.237 DEBG pipe: process_block 1401c685 at 520 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.276 DEBG process_block: orphan: 23afbe43, # orphans 289
Mar 28 07:46:41.278 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.279 TRCE handle_payload: Block 0c34fc21
Mar 28 07:46:41.280 DEBG Received block 0c34fc21 at 542 from 192.241.160.172:13414, going to process.
Mar 28 07:46:41.280 DEBG pipe: process_block 0c34fc21 at 542 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.296 DEBG process_block: orphan: 42832e14, # orphans 289
Mar 28 07:46:41.297 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.298 TRCE handle_payload: Block 335890d0
Mar 28 07:46:41.298 DEBG Received block 335890d0 at 797 from 207.246.91.44:13414, going to process.
Mar 28 07:46:41.298 DEBG pipe: process_block 335890d0 at 797 with 0 inputs, 1 outputs, 1 kernels
Mar 28 07:46:41.380 DEBG process_block: orphan: 346c92ed, # orphans 287
Mar 28 07:46:41.381 TRCE Received message header, type Block, len 1216.
Mar 28 07:46:41.382 TRCE handle_payload: Block 4d8115a2
Mar 28 07:46:41.383 DEBG process_block: orphan: 22455dbc, # orphans 288
Mar 28 07:46:41.383 DEBG Received block 4d8115a2 at 699 from 46.101.149.191:13414, going to process.
Mar 28 07:46:41.383 DEBG pipe: process_block 4d8115a2 at 699 with 0 inputs, 1 outputs, 1 kernels
```

We may want to consider putting some more state tracking in there as were doing in the original original sync process -
* go ask for n blocks
* track them as "received" as they come in
* do not ask for them again until we either receive them or we timeout
*do not ask for any much higher than those we are processing until we receive earlier ones (minimize orphan count)

**Comment by ignopeverell** [comment]
I'm not sure we'll gain that much by making sync a lot more complex, overall getting things out of order and relying on the orphans as a buffer isn't necessarily bad. But I think the current orphan processing is a little too simplistic to handle this case and will generally benefit from some improvements.

So I'm thinking of the following:

* Evict orphans that are the furthest away from our head first.
* Keep them for a lot longer than 30 secs (5 min?) but size-bound them in addition.
* Have a simple back-pressure in sync when we're at max orphan count.
