### ISSUE TITLE
Fail to have wallet info after restore

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#901]
After restore, I'm not able to do ```grin wallet info```

```
Mar 28 10:54:33.729 ERRO Failed to acquire wallet lock file (multiple retries)
```

**Comment by CarstenHouweling** [comment]
I also noticed that my wallet.lock file got 'stuck' at some point. I had to manually remove it to turn it back to normal. Not sure what the steps were to get it there though..

**Comment by mably** [comment]
I think I have been hit by the same problem too.

**Comment by yeastplume** [comment]
just remove 'wallet.lock' when this happens for now.. the wallet is going to go through significant changes during testnet2

**Comment by antiochp** [comment]
Yeah if a wallet process bombs out or panics for any reason the `wallet.lock` gets left in place and needs to be manually cleaned up.
Wallet stability and robustness definitely needs some love and attention soon.

**Comment by yeastplume** [comment]
Wallet.lock is being cleaned up in a Drop function now, so this should (hopefully) be addressed a bit better on T3
