### ISSUE TITLE
Error running cargo build

### ISSUE THREAD

**Issue by jcsmesquita** [mimblewimble/grin#903]
## Summary
Trying to build the project:
- Cloned the repo
- Ran ```cargo build```.
- Error (see blow).

## Terminal Error Message
```
error: use of unstable library feature 'ord_max_min' (see issue #25663)
   --> /Users/jcsmesquita/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-deque-0.3.0/src/lib.rs:667:27
    |
667 |         b.wrapping_sub(t).max(0) as usize
    |                           ^^^

error: aborting due to previous error

error: Could not compile `crossbeam-deque`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Environment
- MacOS 10.13.3
- cargo 0.21.0
- rustc 1.20.0

**Comment by quentinlesceller** [comment]
Can you try:
```
rustup update
```

**Comment by ignopeverell** [comment]
The build docs specify rustc 1.21+:

https://github.com/ignopeverell/grin/blob/master/doc/build.md

**Comment by jcsmesquita** [comment]
Ops, my bad! It works now after `rustup update`. On version 1.25.0.
Thanks!
