### ISSUE TITLE
unneccesary loss of precision in difficulty adjustment

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#907]
I was very surprised to see difficulty that was at 3 for more than 60 blocks turn into 2 and then to 1
in the very next block. I thought that should not happen. Studying the adjustment code:

    let diff_avg = diff_sum.into_num() / Difficulty::from_num(DIFFICULTY_ADJUST_WINDOW).into_num();
    ...
	let difficulty = diff_avg * Difficulty::from_num(BLOCK_TIME_WINDOW).into_num()
		/ Difficulty::from_num(adj_ts).into_num();

I realize it's because of the repeated truncation.
diff_avg could be the fraction 179/60 and in the bottom line that could get multiplied by 60*BLOCK_TIME_SEC/3601, giving (179/60) * 3600 / 3601 = 2 * 3600 / 3601 = 1.
Of course without truncation this would be about 2.98.
We should avoid this repeated truncation by just taking out the common factor and rewriting the above as

    ...
	let difficulty = diff_sum * Difficulty::from_num(BLOCK_TIME_SEC).into_num()
		                                      / Difficulty::from_num(adj_ts).into_num();

which would evaluate to 179 * 60 / 3601 = 2

**Comment by yeastplume** [comment]
Makes sense (and fortunately really only makes a significant difference at very low hashpower numbers, but I don't think we have a strategy yet for how we're going to handle consensus breaking changes.. we can either mark these off until the next hard fork or make changes into a 'consensus breaking' branch now and merge them later (at the risk of the branch getting very out of sync).

**Comment by tromp** [comment]
I'll add a commit that almost but not quite breaks consensus. Basically leaving a one line change to make later.
