### ISSUE TITLE
server stopped logging and syncinc

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#914]
The server had been running with tui for a few hours (after update to actual master and cargo build) and then stopped syncing. grin.log stopped being written to. tui showed node at height 2673 and has been responsive all the time. Other nodes were connected and there has been network traffic.

This is Grin version 0.2.0 (git testnet2-21-g2067c24), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27). Built with profile "debug", features "" on Thu, 29 Mar 2018 07:16:42 GMT.

I put together some information [here](http://z9.de/grin-debug-2018-03-29.tar.gz).

**Comment by chri2** [comment]
Updated to Grin version 0.2.0 (git testnet2-24-g3e3fe6c), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).

Same again: Nodes connected, tui responsive, no logging anymore, but grin.log still opened.

**Comment by ignopeverell** [comment]
Can you give it another shot? You need 5ba0db.

**Comment by chri2** [comment]
On it. Let's see what the european night brings...

**Comment by chri2** [comment]
Couldn't reproduce using testnet2-30-gc393910
