### ISSUE TITLE
Support SSE2 miner in grin.toml

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#920]
I updated the mean solver with better SSE2 support, courtesy of Aleksandar Avramov @OpticFlowX.
Maybe rename the various miners to
mean_miner
mean_sse2_miner
mean_avx2_miner

**Comment by OpticFlowX** [comment]
There also might be AVX-512 variant, some day in the future...

But having so many miners can be confusing to the users... Maybe one all-in binary with option to select advanced siphash variants would be more user friendly...

**Comment by yeastplume** [comment]
The miner implementations aren't really designed to probe and select intrinsics dynamically, they're implemented as compile time options, hence it's much easier to keep them as separate plugins (we want to make as few changes as possible to keep in sync with upstream code).  However, it could be possible to probe the system for which plugin would be most appropriate, either at compile time or (more likely) runtime.

**Comment by yeastplume** [comment]
Especially with the move to variable cuckoo size, could we open another issue on Grin-Miner to discuss the plugin variants we want to provide?

**Comment by OpticFlowX** [comment]
Yes, now that Grin-miner has its own repository.

**Comment by hashmap** [comment]
@tromp are you ok if I close this one?

**Comment by tromp** [comment]
i'll save you the trouble:-)
