### ISSUE TITLE
Full sync should only ask blocks from other archival nodes

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#929]
I believe it requires adding a feature bit for archival nodes, don't think we have that right now.

**Comment by quentinlesceller** [comment]
Isn't FULL_HIST the feature bit for archival nodes? (https://github.com/mimblewimble/grin/blob/master/p2p/src/types.rs#L179)

**Comment by ignopeverell** [comment]
Yes, thanks for looking into it (maybe should be renamed now). We have a `grin.toml` configuration property for this but I don't think we should fully trust it as people can still mess with it. Only sync can rely on it for the initial block download. So to detect whether to advertize our node as archival, we should also check whether we have the full block at height 1 I think.

**Comment by sesam** [comment]
Example: A node advertising Full_hist and cum.work like best peer can still have only last 2880 blocks? B syncs from 0, getting (say) best-3500 blocks as best chain due to not seeing all nodes, and finishes sync. Then finds A, and asks for a bunch of blocks A doesn't have.
Aee we seing this now?

**Comment by ignopeverell** [comment]
Yeah, so an archival node will start by asking blocks say 1..100 and right now will do so on any node. But most nodes are fast-sync'd so they don't have those. I don't think many people are setting their node on archival mode except Antioch and I so still fairly limited but needs fixing.
