### ISSUE TITLE
fast sync retries after 5 mins if we have not completed previous one (success or failure)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#939]
If we do not successfully complete a "fast sync" with 5 mins we kick another one off (and assume the previous one failed) even if we still have one in progress.
So we can end up in the state where we are requesting a new (and very expensive to process) txhashset archive while still fast syncing.

```
Apr 06 12:24:28.214 DEBG Header head before txhashset request: 18218 / 3ef7758a
# ----- asking for a txhashset archive here
Apr 06 12:24:28.329 DEBG Asking 139.59.105.169:13414 for txhashset archive at 15357 634f8a4b.
Apr 06 12:24:57.702 DEBG handle_payload: txhashset archive for 634f8a4b at 15357 rewind to 38349/34529
Apr 06 12:26:01.727 DEBG Going to validate new txhashset, might take some time...
Apr 06 12:26:01.747 TRCE Starting new txhashset extension.
Apr 06 12:26:01.750 DEBG Rewind txhashset to output pos: 38349, kernel pos: 34529
Apr 06 12:29:28.241 DEBG Header head before txhashset request: 18222 / 26c0d519
# ----- asking for another here 5 mins later (previous still in progress)
Apr 06 12:29:28.382 DEBG Asking 193.70.81.67:13414 for txhashset archive at 15361 c43bd1f1.
Apr 06 12:29:30.998 DEBG handle_payload: txhashset archive for c43bd1f1 at 15361 rewind to 38446/34581
```

**Comment by antiochp** [comment]
I think we should consider adding a "is fast syncing" flag to the SyncInfo and toggle it on/off as appropriate to give the fast sync process time to complete.

**Comment by antiochp** [comment]
Some log output with additional debug logging - 

```
Apr 06 18:49:10.587 DEBG Going to validate new txhashset, might take some time...
Apr 06 18:49:10.604 TRCE Starting new txhashset extension.
Apr 06 18:49:10.605 DEBG Rewind txhashset to output pos: 41397, kernel pos: 36794
Apr 06 18:49:10.608 DEBG txhashset extension validating output MMR
Apr 06 18:49:11.183 DEBG txhashset extension validating rproof MMR
Apr 06 18:49:11.741 DEBG txhashset extension validating kernel MMR
Apr 06 18:49:12.304 DEBG txhashset extension validating tree roots
Apr 06 18:49:12.305 DEBG txhashset extension validating kernel excess agains outputs
Apr 06 18:49:31.849 DEBG txhashset extension validating all the rangeproofs
Apr 06 18:54:48.323 DEBG txhashset extension finished validating all the rangeproofs
Apr 06 18:54:49.251 DEBG Committing txhashset extension. sizes (41397, 41397, 36794)
```

Verifying the rangeproofs for an MMR of size ~41,000 took just over 5 mins... (with subsequent txhashset requests disabled).

**Comment by ignopeverell** [comment]
Yes, I was starting to tell people to compile in release mode for that reason. Ideally we'd have something that suppresses further requests while validation is still ongoing. But regardless current validation times seem a little exaggerated, I don't think we can keep running in debug mode when the overhead of all crypto operations is so high.

Independently from those observations, the background rangeproof verification may be a good idea. But could be a little premature right now, maybe we should try with Andrew's recent perf improvements and batch validation first?

**Comment by antiochp** [comment]
Do you know if Andrew's perf improvements are in our version of the secp lib? Or do we need to merge these in from upstream?
And is batch validation supported today, either in our version or upstream? I'm assuming this is something we would potentially need to investigate adding to the secp lib ourselves?

**Comment by antiochp** [comment]
I'm going to look into addig some state back into the sync process - to suppress the subsequent txhashset requests.
We need to be able to handle a long running "fast sync" - but also robust enough to kick a new one off if a peer fails to give us a txhashset, or presumably if validation fails locally.

**Comment by ignopeverell** [comment]
I think he said he was going to merge this week-end, and then we'll need to merge. The APIs are changing a bit, and batch validation should be there.

**Comment by antiochp** [comment]
Closing this - we only run the fast sync once on init (we no longer kick a 2nd one off a few minutes later).
