### ISSUE TITLE
Error building new block: Core(KernelLockHeight(x))

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/grin#941]
Because most testnet blocks are empty, I wanted to spam some transactions between 2 wallets. Basically I am running 1) a server + wallet for mining 2) wallet A 3) wallet B and in an endless bash loop I am sending 10 tx of 0.1 A->B, followed by 10 tx of 0.1 B->A. At first it seems to work fine, but at some point these messages keep appearing in the server log:
```
Apr 05 17:07:53.279 INFO Acquiring wallet lock ...
Apr 05 17:07:53.279 TRCE making lock file for wallet lock
Apr 05 17:07:53.758 INFO ... released wallet lock
Apr 05 17:07:53.760 DEBG receive_coinbase: built candidate output - Identifier(c9f8f98fe9130a783ba4), 477
Apr 05 17:07:53.761 DEBG receive_coinbase: BlockFees { fees: 630000000, height: 16981, key_id: Some(Identifier(c9f8f98fe9130a783ba4)) }
Apr 05 17:07:53.761 TRCE Derived Key by key_id: c9f8f98fe9130a783ba4
Apr 05 17:07:53.761 TRCE ... Derived Key (cache hit) key_id: c9f8f98fe9130a783ba4, derivation: 477
Apr 05 17:07:53.761 TRCE Derived Key (fast) by derivation: 477
Apr 05 17:07:53.762 TRCE Block reward - Pedersen Commit is: Commitment(096aaefd8213a8ec9235a8b6bf60241cc95b99d94fa9380b33fb7affe5646b36ee)
Apr 05 17:07:53.762 TRCE Derived Key by key_id: c9f8f98fe9130a783ba4
Apr 05 17:07:53.763 TRCE ... Derived Key (cache hit) key_id: c9f8f98fe9130a783ba4, derivation: 477
Apr 05 17:07:53.763 TRCE Derived Key (fast) by derivation: 477
Apr 05 17:07:53.764 TRCE Derived Key by key_id: c9f8f98fe9130a783ba4
Apr 05 17:07:53.764 TRCE ... Derived Key (cache hit) key_id: c9f8f98fe9130a783ba4, derivation: 477
Apr 05 17:07:53.764 TRCE Derived Key (fast) by derivation: 477
Apr 05 17:07:53.994 TRCE Derived Key by key_id: c9f8f98fe9130a783ba4
Apr 05 17:07:53.994 TRCE ... Derived Key (cache hit) key_id: c9f8f98fe9130a783ba4, derivation: 477
Apr 05 17:07:53.994 TRCE Derived Key (fast) by derivation: 477
Apr 05 17:07:54.001 DEBG get_coinbase: BlockFees { fees: 630000000, height: 16981, key_id: Some(Identifier(c9f8f98fe9130a783ba4)) }
Apr 05 17:07:57.134 DEBG (Server ID: Port 13414) Built new block with 186 inputs and 180 outputs, network difficulty: 2, cumulative difficulty 35359
Apr 05 17:07:57.141 WARN Error building new block: Core(KernelLockHeight(16987)). Retrying.
```
When this message first pops up, it never succesfully builds a block again and the error keeps appearing, until I restart the server. Probably because the tx pool is cleared when stopping the server.

Another interesting thing (not sure if related) is that a part of the tx i create are never picked up by any other mining node. I've had at some point 1000+ tx in my pool while other nodes were mining empty blocks.

**Comment by ignopeverell** [comment]
It's likely there's a small window where your miner is still on block X but the chain has moved on to X+1. The issue is that a single Cuckoo Cycle find on a CPU miner can take 10 sec and right now can't be easily aborted. But I don't get why it keeps happening, as soon as the miner sees the chain update it should build on top of the new block and that should solve itself. Looks like the kernel was set for 16987, did you reach that height quickly after? At what block were you mining then?

Regarding your transactions not getting picked up, it could be because of the kernel height. What was the chain height at that point? Also did you try with Dandelion just to check (`--fluff`)?

**Comment by jaspervdm** [comment]
> Looks like the kernel was set for 16987, did you reach that height quickly after? At what block were you mining then?

The first time this message appeared the node was already at height 16987, so it was trying to build 16988. After a couple of minutes I stopped the server, but it was still at the same height. I dont know if that was just because no-one else mined a block in the mean time or that there is something else going on. I can try to reproduce it and let it run a while longer.

> Regarding your transactions not getting picked up, it could be because of the kernel height. 

I am not sure I understand this. In my bash script I am basically running the command
```
grin wallet send -f -d "http://IP" -s smallest 0.1
```
in a loop. Doesn't this only take previous outputs that are already have confirmations?

> Also did you try with Dandelion just to check (--fluff)?

Yes I am sending them all without Dandelion (see command above)

**Comment by jaspervdm** [comment]
I think this is fixed now, haven't seen it appear again
