### ISSUE TITLE
Track when a full-sync is ongoing

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#957]
This can be used for multiple purposes:

1. Avoid requesting additional txhashet if we're still processing one.
2. The corollary, speed up asking for another txhashet if we got a bad one.
3. Suppress unneeded or unwanted txhashset sent to us.

**Comment by hashmap** [comment]
Does it make sense to generalise and track all kinds of request? It would fix also https://github.com/mimblewimble/grin/issues/895

**Comment by ignopeverell** [comment]
I think that'd make sense yes. Maybe something the p2p server could do.

**Comment by antiochp** [comment]
We used to have something similar to this for block requests during the original full sync impl.
The sync layer would ask for n blocks (from individual peers) and would track receipt of these as they came in asynchronously. We would only ask for blocks we were not already waiting for.

I had taken a look into the feasibility of moving this into the p2p layer but it was pretty complex at the time.
We ended up simplifying and "brute-forcing" the full sync (which is basically what we do today).

I'd be :+1: if we could find a generic (opt-in) solution to this that did not add _too much_ complexity.

Some thoughts from looking at this earlier - 
  * some requests are peer specific (we want to ask one and only one peer)
  * some requests need retrying
    * sometimes from the _same_ peer, sometimes another peer
  * peers can drop from the network and we need a way of accounting for this
  * some requests end up redundant based on more recent data received
    * retrying these is wasteful after a certain point
  * sometimes we never get a response
    * for example asking for block 1 from a fast sync pruned node
    * this is different to a slow response or a peer that temporarily lost connectivity

**Comment by ignopeverell** [comment]
On that last point, a mistake of the old p2p code was to always _require_ a response. I think this was wrong because a peer should always be free to refuse responding. A typical example would be if it's above some bandwidth requirements.

So while a peer may require a response from _some_ peer, it shouldn't insist on wanting one from _a_ peer. Note that there are still some subtleties, for example if one peer advertises a fork with more work, this peer should get asked first. And if it ignores the request, the fork should get ignored as well.

**Comment by yeastplume** [comment]
Hands up for wanting to see this addressed... the TUI appearing to stall when sync is going on with no sync progress display seems to be a frequent source of noob confusion (and rightly so,)

**Comment by ignopeverell** [comment]
Fixed by #1210
