### ISSUE TITLE
Bulletproofs - Size change and other issues

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#962]
I've updated our secp* projects as follows:

* secp256k1-zkp has been updated with the latest upstream version, and includes @apoelstra's latest bulletproof PR: https://github.com/ElementsProject/secp256k1-zkp/pull/16 Once the PR is integrated properly into elements, it should be trivial to merge the upstream code now.
* I manually put our aggsig lib module on top of this, with no issues at all (the ECmult code is now consistent everywhere.
* I had to re-include the function: secp256k1_pedersen_commit_sum, which was in our fork but not upstream.
But otherwise, that's it. Our elements fork is fairly clean now, and I've put the changes into another branch at https://github.com/mimblewimble/secp256k1-zkp/tree/vendor-rebase. Once we get this into Grin I plan to remove the existing frankenstein monster 'vendor' branch and make this the main one.

The master on our rust-secp fork has been updated to use this branch: https://github.com/mimblewimble/rust-secp256k1-zkp (remember we're tagging this lib on release so it won't break any builds for now.

Now, as far as getting this integrated into Grin testnet2, there are a couple of problems:

* The size of a bullet proof is now 675 bytes instead of 674.. we have no mechanism of dealing with this in our PMMR data files, which assume all elements are the same size. You would assume hard forks could potentially change the data format sizes, so this is probably something we've overlooked in our flat-file design.

* I'm not sure whether the current code will verify proofs generated by the earlier code (perhaps @apoelstra can verify)

Of course, if we created a testnet3 and started again, none of this would be an issue... however, that's not really a future-proof approach. It would seem at the very least we need to address the flat-file size issue.

@ignopeverell @antiochp Thoughts?

**Comment by apoelstra** [comment]
No, the new code will not validate old proofs because there is one less recursion step in the inner product proof now (and also that extra byte means it won't parse).

**Comment by ignopeverell** [comment]
I've been thinking about how to get this in testnet2 and it's not pretty. Doable, but not pretty. Need to thinkg some more but a nasty virus is making that process slow... :P

**Comment by yeastplume** [comment]
@antiochp verify_multi is in place, though I haven't put together a rust binding for it.. it looks like we can give it a try anyhow once we get the new version in place (somehow). I can add the binding if you want to put a performance test together to try it?

@ignopeverell I can think of some nasty ways to shoehorn it in as well, but I think the crux of the issue is that we've made our PMMR data format a bit inflexible... but no panic here, we can think on it once you've reduced your viral load

**Comment by antiochp** [comment]
Just thinking out loud but maybe the size issue can be fixed via versioned MMRs and a migration process?
Take MMR v1 and migrate it to a new version v2 in a new dir.
Rather than attempting to have multiple versions of entries within a single MMR (pos < n are v1 and pos >= n v2 etc.)

(This ignores the fact that "legacy" rangeproofs would not validate with new code etc.)

**Comment by apoelstra** [comment]
@antiochp yes, this will give you batch verification (very different from aggregation, which MW doesn't support)

**Comment by ignopeverell** [comment]
Handling this as the `consensus_breaking` fork which should eventually become testnet3.
