### ISSUE TITLE
cpu_miner causes Segmentation fault: 11

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#964]
runnning grin with mining off works fine, but with mining on, the server crashes within several minutes.
setting tui false and RUST_BACKTRACE=1 provides no further clues.

**Comment by andybellenie** [comment]
I'm seeing this issue running the standalone miner in mean_compat_cpu mode on a Macbook Pro 2012

**Comment by andybellenie** [comment]
Duplicate of https://github.com/mimblewimble/grin-miner/issues/2

**Comment by quentinlesceller** [comment]
Can we close this now that the miner is on a separate project ?

**Comment by ignopeverell** [comment]
I say yes :-)
