### ISSUE TITLE
Do we need to still validate Odd Fee?

### ISSUE THREAD

**Issue by ziyuanliu** [mimblewimble/grin#968]
If I'm understanding the arch properly, isn't the OddFee restriction due to burning? (which has been recently removed here: #767 

https://github.com/mimblewimble/grin/blob/cc9ffcc1ab784be22e8fce2ae5b32e5c4b8bc500/core/src/core/transaction.rs#L423-L425

**Comment by antiochp** [comment]
I believe this is no longer necessary.
Want to open a PR to remove this check (and cleanup the OddFee error itself)?
There may or may not be test coverage around this that would need cleaning up also.

**Comment by antiochp** [comment]
Closing - resolved in #975.
