### ISSUE TITLE
do not fallback to requesting full block if we receive a compact block during syncing

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#973]
We fallback to requesting a full block if we fail to successfully hydrate a compact block.
This will _always_ happen if we receive a compact block while we are syncing.

We should be able to check the store for the previous full block (we have recent full blocks).
If we don't have the previous full block then there is no point requesting the current full block.

We should only ask the store for the previous full block if we fail to hydrate the compact block.

**Comment by i1skn** [comment]
Hello, I would like to work on this one, if nobody already started.

**Comment by sesam** [comment]
@i1skn great! Probably only @antiochp is working on something nearby right now.
See also https://gitter.im/grin_community/dev if you run into any troubles.

**Comment by i1skn** [comment]
@antiochp I have a question. I see here:
https://github.com/mimblewimble/grin/blob/master/servers/src/common/adapters.rs#L137-L149
that we are already check for the previous header existence in the chain and only than request the full block.   

I could not find here:
https://github.com/mimblewimble/grin/blob/master/core/src/core/block.rs#L646-L653
anything relying to the *full* previous block.   

Can you help me to understand why having a *full* previous block is important at this stage? Thanks!

**Comment by sesam** [comment]
I think the reason is to avoid filling up orphan pool (limited to max 200)
with blocks we don't yet need

**Comment by i1skn** [comment]
@sesam thanks for the answer. I have a clarification to ask, in case we do not have a *full* previous block and current compact block is invalid - we should just stop processing the current, right?

**Comment by sesam** [comment]
yes. Gitter is often faster, today is an exception :)

**Comment by quentinlesceller** [comment]
Should be fixed by #1002.
