### ISSUE TITLE
restarting a node during fast sync can cause problems

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#974]
Steps to reproduce (not sure we can reproduce this consistently or not) -
1. start a node in "fast sync" mode
2. wait for it to download and fully verify a txhashset
3. wait for it to start requesting individual blocks from the horizon
4. stop the node before it has fully sync'd
5. restart the node

```
Apr 17 21:28:16.220 DEBG Requesting block 96a38a4d from peer 167.99.53.226:13414.
Apr 17 21:28:16.242 DEBG Received block 96a38a4d at 32373 from 167.99.53.226:13414, going to process.
Apr 17 21:28:16.242 DEBG pipe: process_block 96a38a4d at 32373 with 0 inputs, 1 outputs, 1 kernels
Apr 17 21:28:16.278 DEBG -- outputs --
Apr 17 21:28:16.278 DEBG -- range proofs --
Apr 17 21:28:16.278 DEBG -- kernels --
Apr 17 21:28:16.278 DEBG validate_block: output roots - aab8bb5d, aab8bb5d
Apr 17 21:28:16.278 DEBG validate_block: rproof roots - 255eccb0, 255eccb0
Apr 17 21:28:16.278 DEBG validate_block: kernel roots - ca19cd8b, 644072e9
Apr 17 21:28:16.278 DEBG Error returned, discarding txhashset extension.
Apr 17 21:28:16.279 INFO Rejected block 96a38a4d at 32373: InvalidRoot
Apr 17 21:28:16.279 DEBG adapter: process_block: 96a38a4d is a bad block, resetting head
Apr 17 21:28:16.279 DEBG Received a bad block 96a38a4d from  167.99.53.226:13414, the peer will be banned
```

Once a node gets into this state we never get past the next block following a restart.
In this particular case we gradually ban _all_ our peers as they all provide block 96a38a4d at 32373 as above.

Looking at the above logs the output and rangeproof roots are correct.
But the kernel root is mismatched for some reason.

```
Apr 17 21:28:16.278 DEBG validate_block: kernel roots - ca19cd8b, 644072e9
```

Seems weird that there would be a mismatch there as these are never pruned.
Are we not rewinding the kernel MMR correctly?

**Comment by antiochp** [comment]
One observation - we see the following on restart - 
```
Apr 17 22:11:36.148 DEBG metadata not found for 32372 @ acbf1b0c
```

Block 32372 is the last block processed before the restart.
So maybe possible we stopped the node before writing the metadata?

**Comment by yeastplume** [comment]
Think this is resolved with block markers, please reopen if this isn't the case
