### ISSUE TITLE
block orphan pool maxed out during sync (slow block sync)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#977]
We seem to max out the block orphan pool during sync which limits how fast we request blocks from peers. 
Need to investigate this as we should not be continually at ~200 orphans during sync.

If we have ~200 blocks in the orphan pool and we receive the "missing" block then we should be able to quickly drain the orphan pool. But this appears to not be happening.

```
Apr 18 09:54:07.493 DEBG process_block: orphan: c81c7d0a, # orphans 196
Apr 18 09:54:07.496 DEBG process_block: orphan: a63ab66e, # orphans 197
Apr 18 09:54:07.504 DEBG process_block: orphan: 1ec09a26, # orphans 198
Apr 18 09:54:07.572 DEBG process_block: orphan: 416d3414, # orphans 199
Apr 18 09:54:07.574 DEBG process_block: orphan: 6f27aeb9, # orphans 200
Apr 18 09:54:07.609 DEBG process_block: orphan: 03d11801, # orphans 199
Apr 18 09:54:12.532 DEBG process_block: orphan: a60aa0da, # orphans 195
Apr 18 09:54:12.542 DEBG process_block: orphan: 4165417c, # orphans 196
Apr 18 09:54:12.594 DEBG process_block: orphan: 03d11801, # orphans 197
Apr 18 09:54:12.621 DEBG process_block: orphan: 8e5273f6, # orphans 198
Apr 18 09:54:12.637 DEBG process_block: orphan: b1378526, # orphans 199
Apr 18 09:54:12.640 DEBG process_block: orphan: 769d48cf, # orphans 200
```

These are presumably "current" blocks that we are receiving from peers while we are syncing. 
So maybe we want to just be dropping these and not filling the orphan pool with these?

**Comment by ignopeverell** [comment]
That should look a lot better now. We were too slow in processing those blocks (see #1050), causing a large backlog in orphans.
