### ISSUE TITLE
Dandelion Relay must be chosen even if there is no outbound peers

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#997]
Right now if the node does not have any outbound peers, it will unable to chose a Dandelion relay.
Maybe we should pick one inbound peer or force a connection on a new outbound peer.

**Comment by antiochp** [comment]
Current behavior (as of 20180531) is to fluff tx in this case and broadcast it as a normal tx.
I wonder if this works for now as any other solution would add some complexity and potentially runs the risk of leaking info about Dandelion/stempool.

**Comment by sesam** [comment]
Good.

We could create a separate potential issue about trying harder to get
outbound nodes, fully independently of stem messaging.

Any action the node takes as a result of having received a stem tx means
leaking info, delayed or not. So nodes must be proactive and if possible
not at all appear reactive.

**Comment by quentinlesceller** [comment]
Closing this issue as it is pretty out of date considering the new Dandelion++ algorithm introduced recently.
